### DISCUSSION TITLE
regex confs debugging

### DISCUSSION THREAD

**Discussion by electriquo** [renovatebot/renovate#10284] [Request Help] [answered]
using [Custom Manager Support using Regex](https://docs.renovatebot.com/modules/manager/regex/) to read `.deps.yaml` in the root of the project, which lists python package and docker images.

this is how [`.deps.yaml`](https://github.com/foolioo/renovate-regex/blob/master/.deps.yaml) looks

```yaml
prometheus: 0.2.1
anchor: renovate/renovate:25.34
# more lines
  anchor: stefanprodan/podinfo:5.2.0
# more lines
            anchor: mozilla/syncserver:1.9.0 baz
```

and the [`renovate.json`](https://github.com/foolioo/renovate-regex/blob/master/.github/renovate.json)

```json
{
  "enabledManagers": [ "regex" ],
  "regexManagers": [
    {
      "fileMatch": [ "(^|/)\\.deps\\.yaml$" ],
      "matchStrings": [ "^prometheus: (?<currentValue>.*?)$" ],
      "depNameTemplate": "prometheus",
      "datasourceTemplate": "pypi"
    },
    {
      "fileMatch": [ "(^|/)\\.deps\\.yaml$" ],
      "matchStrings": [ "^\\s*anchor: (?<depName>[^:]+):(?<currentValue>\\S+)" ],
      "datasourceTemplate": "docker"
    }
  ]
}
```

- both `matchStrings` were tested ([pypi-demo](https://regex101.com/r/tCawp7/1), [docker-demo](https://regex101.com/r/VSUajC/1))
- `datasourceTemplate` was taken from the [datasources](https://docs.renovatebot.com/modules/datasource/)
- `fileMatch` was inspired from [docker-compose manager](https://github.com/renovatebot/renovate/blob/da8676decaf8290a682a87bc6d6581e4c17ac89e/lib/manager/docker-compose/index.ts#L9)
- [`prometheus`](https://pypi.org/project/prometheus/) pypi package is not private and available on [pypi](pypi.org/) and can be installed with `pip`
- [`renovate/renovate`](https://hub.docker.com/layers/renovate/renovate), [`stefanprodan/podinfo`](https://hub.docker.com/r/stefanprodan/podinfo) and [`mozilla/syncserver`](https://hub.docker.com/r/mozilla/syncserver) images are not private and available on [docker hub](https://hub.docker.com/) and can be pulled with `docker`

the expectation is for renovate to open a pull-requests (for each dependency change) that will result in the following `.deps.yaml` file:

```yaml
prometheus: 0.3.0
anchor: renovate/renovate:25.35
# more lines
  anchor: stefanprodan/podinfo:5.2.1
# more lines
            anchor: mozilla/syncserver:1.9.1 baz
```

there are updates to the dependencies specified in `.deps.yaml` (refer to the result above), but renovatebot does not open pull-requests for them.

also tried to run renovatebot locally and examine its logs, but it did not reveal why renovatebot does not open pull-requests for the regex's.

please help
- what is the issue? is it a bug?
- any advise how to fix it?
