### DISCUSSION TITLE
Having trouble resolving secrets (config.js --> hostRules)

### DISCUSSION THREAD

**Discussion by nielsbasjes** [renovatebot/renovate#10399] [Request Help] [answered]
I'm having trouble resolving secrets in my setup.
I have an internal Gitlab CI on the google cloud and I've uploaded the renovate 25.38.2 in there (with a few additional tools in the image).

My need is to inject the output of a command (gcloud auth print-access-token) into the centralized config because the access token is short lived and persisting it would break the build after a while.

The problem I have that I have not been able to inject it into the hostRules.

The summary of my `.gitlab-ci.yaml` (only the renovate parts and I've replaced a few values with xxxxxx)
```yaml
variables:
  INTERNAL_RENOVATE_IMAGE: eu.gcr.io/xxxxxx/renovate-xxxxxx:25.38.2
  RENOVATE_BASE_DIR: $CI_PROJECT_DIR/renovate
  RENOVATE_ENDPOINT: https://gitlab.xxxxxx/api/v4/
  RENOVATE_PLATFORM: gitlab
  RENOVATE_GIT_AUTHOR: Renovate Bot <bot@renovateapp.com>
  RENOVATE_ONBOARDING_CONFIG: '{"$$schema": "https://docs.renovatebot.com/renovate-schema.json", "extends": ["config:base"] }'
  RENOVATE_OPTIMIZE_FOR_DISABLED: 'true'
  RENOVATE_REPOSITORY_CACHE: 'true'
  RENOVATE_REQUIRE_CONFIG: 'false'
  RENOVATE_ONBOARDING: 'false'
  RENOVATE_IGNORE_PR_AUTHOR: 'true'
  RENOVATE_LOG_FILE: renovate-log.ndjson
  RENOVATE_LOG_FILE_LEVEL: debug
  RENOVATE_LOG_LEVEL: debug
  LOG_LEVEL: debug
  RENOVATE_EXTRA_FLAGS: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
  RENOVATE_CONFIG_FILE: config.js

renovate:
  image: ${INTERNAL_RENOVATE_IMAGE}
  stage: renovate
  resource_group: production
  script:
    - 'echo "module.exports = { secrets: { NIELS_WAS_HERE:''Yes Really'' } };" > config.js'
    - renovate $RENOVATE_EXTRA_FLAGS

stages:
  - renovate
```

And my project has a `renovate.json` with (and lots of other settings).
```json
{
  "hostRules": [
    {
      "matchHost": "secret.test.basjes.nl",
      "token": "{{ secrets.NIELS_WAS_HERE }}",
      "authType": "{{ secrets.NIELS_WAS_HERE }}"
    }
  ]
}
```

Notes:
- I'm abusing the `authType` here to actually see the value as the token is blanked in logging.
- The config.js is generated because I want to inject a short lived bearer token that I cannot persist.
- The renovate.json is in my test a file in the project but I would like to include it using a variable like this
  `RENOVATE_CONFIG: '{ "extends": [ "local>renovate/config" ] }'`

The problem I have is that the provided secret value is not inserted into the values where I expect it to go.

Summary of the output I get:
```
DEBUG: Combined config
       "config": {
         "secrets": {
           "NIELS_WAS_HERE": "***********"
```
```
DEBUG: Repository config (repository=renovate/renovate-test-project)
       "fileName": "renovate.json",
       "config": {
...
         "hostRules": [
           {
             "matchHost": "secret.test.basjes.nl",
             "token": "***********",
             "authType": "{{ secrets.NIELS_WAS_HERE }}"
```

```
DEBUG: migrated config (repository=renovate/renovate-test-project)
       "config": {
...
         "hostRules": [
           {
             "matchHost": "secret.test.basjes.nl",
             "token": "***********",
             "authType": "{{ secrets.NIELS_WAS_HERE }}"
```

```
DEBUG: Setting hostRules from config (repository=renovate/renovate-test-project)
DEBUG: Adding token authentication for secret.test.basjes.nl to hostRules (repository=renovate/renovate-test-project)
```

```
DEBUG: Full resolved config including presets (repository=renovate/renovate-test-project)
       "config": {

NO secrets and NO hostRules in here.
```

To me it seems that the variables are never substituted in the hostRules.

How can I fix this?
