### DISCUSSION TITLE
Failed to look up dependency adrienverge/yamllint.git

### DISCUSSION THREAD

**Discussion by HaveFun83** [renovatebot/renovate#10397] [Request Help] [answered]
Hi we run renovate on a self-hosted gitlab and got the following warning
```
⚠️ Dependency Lookup Warnings ⚠️
Please correct - or verify that you can safely ignore - these lookup failures before you merge this MR.
Failed to look up dependency adrienverge/yamllint.git
Files affected: .pre-commit-config.yaml
```
Can someone help me what need to be done here?

**Comment by rarkins** [comment, marked as answer]
A dependency called `adrienverge/yamllint.git` has been detected however Renovate cannot look it up so it is warning you.

What does your `.pre-commit-config.yaml` look like?

**Reply by HaveFun83** [reply]
thanks for your reply
nothing special here:
```
repos:
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.26.0
  hooks:
  - id: yamllint
    args:
    - --config-data=.yamllint.yaml
    - --strict
   ```
