### DISCUSSION TITLE
Renovate is failing to bump a github-tags data-source for kustomize

### DISCUSSION THREAD

**Discussion by anthr76** [renovatebot/renovate#10403] [Request Help] [answered]
The log:

```json
           {
             "packageFile": "gitops/core/base/deployments/kubegres/default/kustomization.yaml",
             "deps": [
               {
                 "currentValue": "v1.5",
                 "datasource": "github-tags",
                 "depName": "reactive-tech/kubegres",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [],
                 "skipReason": "invalid-value"
               }
             ]
           },
```

The kustomization:

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/reactive-tech/kubegres/config/default?ref=v1.5
namespace: database
```

The data source repo: https://github.com/reactive-tech/kubegres
The source repo: https://gitlab.com/kutara/infra/-/blob/main/gitops/core/base/deployments/kubegres/default/kustomization.yaml

Are we seeing a regression of some sort? My other kustomizations are coming back clean. Though I see `invalid-value` in some other places..
