### DISCUSSION TITLE
How would I get a custom language?

### DISCUSSION THREAD

**Discussion by sasial-dev** [renovatebot/renovate#10411] [Request Help] [answered]
I have a `foreman.toml` file, which lists my dependencies.
```toml
[tools]
rojo = { source = "rojo-rbx/rojo", version = "6.0.2" }
selene = { source = "Kampfkarren/selene", version = "0.11.0" }
```
How can I setup renovate to see if there is an updated GH release and send a PR to bump the version?
