### DISCUSSION TITLE
Renovate does not integrate alternate NuGet feeds

### DISCUSSION THREAD

**Discussion by timmkrause** [renovatebot/renovate#10438] [Request Help] [answered]
We are running on an Azure DevOps Server 2019 instance with self-hosted Ubuntu agents and are having problems with our internal NuGet package feeds which are not recognized by Renovate.

A `nuget.config` is present in the repository, additionally I tried

```
{
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",

    // ...    
    
    "nuget": {
        "registryUrls": [
            "https://api.nuget.org/v3/index.json",
            "https://something.com/foo/_packaging/bar1/nuget/v3/index.json",
            "https://something.com/foo/_packaging/bar2/nuget/v3/index.json"
        ]
    },

    // ...
}
```

in the `renovate.json5` config according to the ["Alternate feeds"](https://docs.renovatebot.com/nuget/) section (the JSON example misses a `,` btw if somebody cares about it). The build log doesn't seem to log any details regarding detected package sources or what went wrong with them.

What am I doing wrong or how can I get further details to diagnose the problem?

**Comment by rarkins** [comment]
Can you create a minimal public repo to reproduce the problem? Then we can debug and let you know if it's solvable with config or needs a bug fix. Before then you could also try this package rule in case it  instead works:

```json
{
  "packageRules": [{
    "matchDatasources": ["nuget"],
    "registryUrls": [
        "https://api.nuget.org/v3/index.json",
        "https://something.com/foo/_packaging/bar1/nuget/v3/index.json",
        "https://something.com/foo/_packaging/bar2/nuget/v3/index.json"
    ]
  }]
}
```

**Reply by timmkrause** [reply]
Thanks for the suggestion. Unfortunately no change in behavior, additionally I cannot really provide a public repro with the given setup (completely self-hosted/on-prem).

I am using the [Renovate Me](https://marketplace.visualstudio.com/items?itemName=jyc.vsts-extensions-renovate-me) task by the way with "latest" version configured. The build user has contributor permissions to the Azure DevOps Artifacts Feed.

I am new to Renovate, is there really no log available which summarizes the package sources or the gathering process?
Do you have any further ideas how I can dig deeper?
Are there any arguments which can raise the verbosity?
Try it locally via the CLI? Does it have a more detailed log or possibilities?

**Reply by rarkins** [reply]
If you run with `LOG_LEVEL=debug` in env, can you look for mentions of `registryUrls` or any of those particular URLs in the logs?

**Reply by timmkrause** [reply]
Nice, that helped, thanks! It's logging error objects with 401s and also finding the `nuget.config`. Thought that there is some kind of implicit auth happening, as the task is configured to access the OAuth token.

Now trying this: https://docs.renovatebot.com/private-modules/#hostrules-configuration-using-environment-variables

**Reply by timmkrause** [reply]
Doing it this way now and it works like a charm, without any config changes, thank you so much for your kickstart:

```
- task: jyc.vsts-extensions-renovate-me.default-build-task.RenovateMe@0
  displayName: Renovate
  inputs:
    renovateOptionsArgs: '--host-rules="[{\"domainName\":\"github.com\",\"token\":\"$(GITHUB_COM_TOKEN)\"},{\"domainName\":\"my.domain.com\",\"username\":\"irrelephant\",\"password\":\"$(MY_ORG_AZURE_DEVOPS_NUGET_PAT)\"}]"'
```

**Reply by viceice** [reply]
@timmkrause Please copy your solutions to a new answer and mark is as solution.

**Comment by timmkrause** [comment, marked as answer]
The assumption, that `nuget.config` is not detected and its package sources not being included was wrong.
The log simply didn't show any warnings/errors.

A higher verbosity log level via `LOG_LEVEL=debug` as @rarkins pointed out led to the actual problem: `401 Unauthorized`

The solution for our private Azure DevOps feeds looks like this:

```
- task: jyc.vsts-extensions-renovate-me.default-build-task.RenovateMe@0
  displayName: Renovate
  inputs:
    renovateOptionsArgs: '--host-rules="[{\"domainName\":\"my.domain.com\",\"username\":\"irrelephant\",\"password\":\"$(MY_ORG_AZURE_DEVOPS_NUGET_PAT)\"}]"'
```

`MY_ORG_AZURE_DEVOPS_NUGET_PAT` is configured as a secret pipeline/environment variable containing the personal access token.
