### DISCUSSION TITLE
Self-hosted multi-repo approach does not inherit configuration

### DISCUSSION THREAD

**Discussion by timmkrause** [renovatebot/renovate#10742] [Request Help] [answered]
We have the following "Renovate repository" (let's call it `repo-renovate`) whose pipeline should target multiple other repositories while using/inheriting the config from `repo-renovate`:

**azure-pipelines.yml**
```
trigger: none

schedules:
- cron: '30 5 * * 1-5'
  displayName: Daily package updates
  branches:
    include:
      - master
  always: true

pool:
  name: ubuntu-18.04

steps:
- task: UseNode@1
  displayName: 'Use Node 14.17.0'
  inputs:
    version: '14.17.0'

- bash: |
    git config --global user.email 'bot@renovateapp.com'
    git config --global user.name 'Renovate Bot'
    npx renovate --host-rules="[{\"matchHost\":\"my.company.com\",\"username\":\"irrelephant\",\"password\":\"$(AZURE_DEVOPS_NUGET_PAT)\"}]"
  displayName: "Run Renovate"
  env:
    system_accesstoken: $(System.AccessToken)
```

**config.js**
```
module.exports = {
  platform: 'azure',
  endpoint: 'https://my.company/org/',
  token: process.env.system_accesstoken,
  repositories: [
    'project/repo-a',
    'project/repo-b',
    'project/repo-c'
  ]
};
```

**renovate.json5**
```
{
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "assignAutomerge": true,
    "azureAutoComplete": true,
    "packageRules": [
        // Several groupings
    ]
}
```

All target repos have received an onboarding PR and do have an empty `renovate.json` under the `.github` root folder:

```
{
    "$schema": "https://docs.renovatebot.com/renovate-schema.json"
}
```

Now it seems that the settings from `repo-renovate` are not merged with the ones sitting inside the target repos, so PRs are created based on the empty config files (no package rules are applied etc.).

What are we doing wrong here?

I've read about recommendations regarding shared presets, but I would first like to get this one working (to get going quickly and also I don't know how I can store/apply them within Azure Devops (Server) yet).
