### DISCUSSION TITLE
The CircleCI config example seems to be wrong (it couldn't pass CircleCI's config validator)

### DISCUSSION THREAD

**Discussion by central182** [renovatebot/renovate#10759] [Suggest an Idea]
Let's say I've saved the config shown at https://docs.renovatebot.com/self-hosting/#circleci as `example.yml`.
```yaml
# example.yml

version: '2.1'
orbs:
  renovate: daniel-shuy/renovate@2.1.1
workflows:
  renovate:
    jobs:
      - renovate/self-hosted:
          config_file_path: renovate-config.js
    nightly:
      triggers:
        - schedule:
            cron: 0 * * * *
            filters:
              branches:
                only:
                  - main
```

Running
```bash
> circleci config validate example.yml
```
gives me
```
Error: Config does not conform to schema: {:workflows {:renovate {:nightly disallowed-key}}}
```
(I'm using the CircleCI CLI here: see https://circleci.com/docs/2.0/local-cli/#validate-a-circleci-config.)

I believe the config should have been as follows:
```yaml
# example.yml (modified)

version: '2.1'
orbs:
  renovate: daniel-shuy/renovate@2.1.1
workflows:
  renovate:
    jobs:
      - renovate/self-hosted:
          config_file_path: renovate-config.js
    triggers:
      - schedule:
          cron: 0 * * * *
          filters:
            branches:
              only:
                - main
```
(More details of the syntax can be found at https://circleci.com/docs/2.0/configuration-reference/#workflows.)
