### DISCUSSION TITLE
`fatal: repository not found` in self-hosted Renovate-Runner

### DISCUSSION THREAD

**Discussion by samithShetty** [renovatebot/renovate#10799] [Request Help] [answered]
I am using self-hosted Gitlab-runner to run Renovate (the plan is to eventually do this against both gitlab and bitbucket-server from the gitlab-runner). I've gotten the runner to work on a personal test repo, but in my company GL, it seems that before it can even start running renovate, it crashes in trying to detect the repo? Here is the full log and my gitlab-ci.yml for the job:

<details>
<summary> Click me to show logs </summary>

```
Running with gitlab-runner 14.0.1 (c1edb478)
  on docker-auto-scale 72989761
  feature flags: FF_SKIP_DOCKER_MACHINE_PROVISION_ON_CREATION_FAILURE:true
Resolving secrets   00:00
Preparing the "docker+machine" executor
Using Docker executor with image renovate/renovate:25.53.3@sha256:39347fa5a6091640339d477a2e29f73115e695b00a672d16a438afb08d1ac4a3 ...
Pulling docker image renovate/renovate:25.53.3@sha256:39347fa5a6091640339d477a2e29f73115e695b00a672d16a438afb08d1ac4a3 ...
Using docker image sha256:77231fe2c7ca13a9ee9d4869b9a4d05a8dfc8189acafa1f0a37996ee23b398d9 for renovate/renovate:25.53.3@sha256:39347fa5a6091640339d477a2e29f73115e695b00a672d16a438afb08d1ac4a3 with digest renovate/renovate@sha256:39347fa5a6091640339d477a2e29f73115e695b00a672d16a438afb08d1ac4a3 ...
Preparing environment
Running on runner-z3wu8uu-project-26970473-concurrent-0 via runner-z3wu8uu-srm-1626103211-99b15b72...
Getting source from Git repository   00:02
$ eval "$CI_PRE_CLONE_SCRIPT"
Fetching changes with git depth set to 50...
Initialized empty Git repository in /builds/<company>/<project>/<repo>/.git/
Created fresh repository.
remote: The project you were looking for could not be found or you don't have permission to view it.
fatal: repository 'https://gitlab.com/<company>/<project>/<repo>.git/' not found
Uploading artifacts for failed job   00:01
Uploading artifacts...
WARNING: renovate-log.ndjson: no matching files    
ERROR: No files to upload                          
Cleaning up file based variables   00:01
ERROR: Job failed: exit code 1
```
</details>

<details>
<summary> Click me to show gitlab-ci.yml </summary>

```yaml
image: renovate/renovate:25.53.3@sha256:39347fa5a6091640339d477a2e29f73115e695b00a672d16a438afb08d1ac4a3

variables:
  RENOVATE_BASE_DIR: $CI_PROJECT_DIR/renovate
  RENOVATE_ENDPOINT: $CI_API_V4_URL
  RENOVATE_PLATFORM: gitlab
  RENOVATE_GIT_AUTHOR: Renovate Bot <bot@renovateapp.com>
  RENOVATE_ONBOARDING_CONFIG: '{"$$schema": "https://docs.renovatebot.com/renovate-schema.json", "extends": ["config:base"] }'
  RENOVATE_OPTIMIZE_FOR_DISABLED: 'true'
  RENOVATE_REPOSITORY_CACHE: 'true'
  RENOVATE_REQUIRE_CONFIG: 'true'
  RENOVATE_ONBOARDING: 'false'
  RENOVATE_IGNORE_PR_AUTHOR: 'true'
  RENOVATE_EXTENDS: 'github>whitesource/merge-confidence:beta'
  RENOVATE_LOG_FILE: renovate-log.ndjson
  RENOVATE_LOG_FILE_LEVEL: debug
  LOG_LEVEL: info

  RENOVATE_CONFIG_FILE: 'src/config.js'

default:
  cache:
    key: ${CI_COMMIT_REF_SLUG}-renovate
    paths:
      - $CI_PROJECT_DIR/renovate


renovate:
  stage: deploy
  resource_group: production
  only:
    - schedules
    - web
    - pushes
  before_script:
    - export PASSWORD=$PASSWORD
    - export GL_PASSWORD=$GL_PASSWORD
  script:
    - renovate $RENOVATE_EXTRA_FLAGS
  artifacts:
    when: always
    expire_in: 1d
    paths:
      - "$RENOVATE_LOG_FILE"
```
</details>

My config.js has a hostRule setup for gitlab so that it can properly login/authenticate to it, but I suspect that perhaps it fails before this even comes into play?
```javascript
        {
            hostType: "gitlab",
            username: 'samithShetty',
            password: process.env.GL_PASSWORD
        }
```
I pass my GL account personal access token as PASSWORD (I also tried RENOVATE_TOKEN) and my GL account password as GL_PASSWORD in the CI variables, but once again, I think that it's failing before these even come into play. Is this some sort of proxy/firewall issue, or have I missed something basic with my credentials/authentication? 
Thanks!

**Comment by viceice** [comment, marked as answer]
checkout our official gitlab runner template for basic configuration

https://gitlab.com/renovate-bot/renovate-runner

**Reply by samithShetty** [reply]
Yup, my configuration is just the `renovate.gitlab-ci.yml` and ` _common.gitlab-ci.yml` files from official configuration merged into one gitlab-ci.yml rather than splitting it and using `include` so functionally I figured its the same (atleast it worked properly this way in my personal test repo).  I'll try using it the official way now though...

**Reply by viceice** [reply]
Then you didn't read the readme, there is a section for configuration of gitlab variables.

So you need a PAT. Which must be passed as `RENOVATE_TOKEN`

https://gitlab.com/renovate-bot/renovate-runner#configure-cicd-variables

**Reply by samithShetty** [reply]
Yup just tried that again and this time with the official gitlab-ci.yml as well, still getting the exact same error. Once again, I did this on my personal computer and it worked, so is it possible that a company proxy or something like that is getting in the way and causing this error? Thanks

**Reply by viceice** [reply]
Your logs showing a gitlab pipeline error. Gitlab isn't able to clone your runner repo. Renovate isn't run yet. You need to check you env vars, maybe you've overridden the gitlab git checkout credentials.

**Reply by samithShetty** [reply]
I haven't overridden anything that is in that example configuration, as right now I am only using the exact example config. Is there a way to see the details of that CI_PRE_CLONE_SCRIPT? That seems to be where I'm running into this issue and since it is failing before my renovate job is even run, I am not able to just add an export or echo statement to the script. At first I thought it was a built-in [gitlab predefined ci variable](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html), but after checking the documentation it seems to be something from the renovate-runner repo itself?

**Reply by viceice** [reply]
`CI_PRE_CLONE_SCRIPT` is not from renovate, can you try a simple gitlab pipeline with a single job which echo something.

If this doesn't work, i assume your gitlab runner isn't able to connect to the gitlab server maybe you need some proxy configuration?

https://docs.gitlab.com/runner/configuration/proxy.html

**Reply by samithShetty** [reply]
Alright, thanks for your help, I finally got it to work. For anybody experiencing a similar issue, It was a company-side gitlab configuration. We have tags are built into our ci-templates to provide permissions/config, and obviously the default renovate didn't have those. After adding the tags to the renovate stage, permissions/config sorted themselves out and we got it up and running. 
```yml

include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate.gitlab-ci.yml'
renovate:
  only:
    - schedules
    - pushes
    - web
  tags:
    - "docker"
    - "<Account>"
    - "<Role>"
```
Thank you so much!
