### DISCUSSION TITLE
Upgrade only paticular deps on running self-hosted renovate

### DISCUSSION THREAD

**Discussion by evgenosiptsov** [renovatebot/renovate#10928] [Request Help] [answered]
Hey folks! 

I'm just wondering is there any solution to upgrade only particular dependency in repo (instead of all repo's dependencies specified in `package.json` and configured in `renovate.json`)

**Use case:**
I run Renovate Bot aimed to the particular repository where I wanna update depency
```
$ npm run renovate -- "packages/core"
> renovate "packages/core"
```

`packages/core` has own `renovate.json` which tells Renovate Bot upgrade all dependencies to the its rules:
```
{
  "packageRules": [
    {
      "updateTypes": ["patch", "pin", "digest"],
      "automerge": true,
      "automergeType": "branch",
      "labels": ["renovate-patch"]
    },
    {
      "updateTypes": ["minor", "pin", "digest"],
      "labels": ["renovate-minor"]
    }
  ],
  "gitLabAutomerge": true,
  "separateMinorPatch": true
}
```
As a result Renovate Bot update create/update renovate branches for all upgraded repositories.

**Question**
Is there any chance to somehow upgrade only one dependency (instead of all)?

**Comment by evgenosiptsov** [comment]
I've tried [to specify `packageRules` in `RENOVATE_CONFIG`](https://github.com/renovatebot/renovate/pull/9491) env, unfortunately, Renovate Bot still observer all dependencies in the repo.

**Comment by rarkins** [comment, marked as answer]
Before answering, I don't think that will work the way you hope it will. All other branches will be closed and if the dependency is part of a group then other dependencies will be removed from it too.

**Reply by evgenosiptsov** [reply]
Thanks! You're right, I recall how Renovate Bot closes non-matched PRs after `packageRules` changes.

**Reply by evgenosiptsov** [reply]
Is it real to do not close non-related PRs and update particular dependency via running Renovate Bot with custom `branchPrefix` and `prTitle`? Will it work the way I expect?

**Reply by rarkins** [reply]
It's unsupported behaviour currently although you're welcome to experiment with it. What's the "real" requirement you're trying to do though?

**Reply by evgenosiptsov** [reply]
Yep, I going to try.

I aim to deliver releases to consumers' repositories as quickly as we can. To achieve that I run a pipeline with a job that runs Renovate Bot targeted to the needed consumer's repository, but unfortunately, that job upgrades all dependencies, generates unrelevant logs and lasts few minutes (some time)

Would be nice to have logs and upgrade dependencies only related to delivering the released package.

**Reply by rarkins** [reply]
There is the ability to skip branch pruning in Renovate so that might be useful for this purpose. Maybe we're now back to the packageRules via env or CLI question. I'd prefer to fix the env config or work out why it's not working as expected

**Reply by evgenosiptsov** [reply]
Thanks @rarkins, I likely will fix env the config to adjust Renovate Bot to update only needed package.

Would you please point me out how I can skip branch pruning via config?

**Reply by rarkins** [reply]
https://docs.renovatebot.com/configuration-options/#prunestalebranches

**Reply by evgenosiptsov** [reply]
Unfortunately `packageRules` in `RENOVATE_CONFIG` does not override Repository Config (specified by `renovate.json` in repository where we would update dependecy)

```
force-run:
  extends:
    - .shared-run
  script:
    - >-
      npm run renovate -- $REPOSITORIES --prune-stale-branches=false --dry-run=true 
  variables:
    LOG_LEVEL: 'DEBUG'
    RENOVATE_CONFIG: "{\"prTitle\":\"Force Update Particular Dependency\",\"packageRules\":[{\"matchPackagePatterns\":[\"^@codemirror/state\"],\"automerge\":true,\"automergeType\":\"branch\"}]}"
    REPOSITORIES: '*****'
```
