### DISCUSSION TITLE
pre-commit support for renovate-config-validator

### DISCUSSION THREAD

**Discussion by andormarkus** [renovatebot/renovate#10973] [Suggest an Idea]
This is reopening of #10971, opened with correct account

Hi Community,

I would like to start the discussion about adding pre-commit support for `renovate-config-validator` command.

Currently, renovate is missing `.pre-commit-config.yaml` and `.pre-commit-hooks.yaml` file to have "native" integration into pre-commit.

I'm happy to submit a PR if the community agrees.

Thanks,
Andor

**Comment by rarkins** [comment]
I'm not familiar with how this works - can you explain more and/or provide some examples?

**Reply by andormarkus** [reply]
I'm talking about [pre-commit](https://pre-commit.com/) framework. Pre-commit is a framework for managing and maintaining multi-language pre-commit hooks. 

You can use pre-commit in two ways:
1. You connect it with your pre-commit hook and as git pre-commit hook does not led you commit until you pass all of the checks
2. You run in you CI/CD pipeline. In that case you need to manually call it like `pre-commit run --all-file`


You can configure all of your pre-commit hook in the `.pre-commit-config.yaml`. This is sample how it looks like
```yaml
default_language_version:
  python: python3.8

fail_fast: true # stops executing subsequent hooks if one hook fails

repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.8
    hooks:
      - id: commitizen
        stages: [ commit-msg ]
```

If a repo has a "native" integration with pre-commit than you have to only define the repo name and which hooks you want to execute. When you first run pre-commit it will install the repo and all its dependencies.

In the `.pre-commit-hooks.yaml` you define the hooks which means which command you want to run.  It would look like this
```yaml
-   id: renovate-config-validator
    name: renovate-config-validator
    description: "renovatebot: Universal dependency update tool that fits into your workflows."
    entry: renovate-config-validator
    language: node
```

**Reply by rarkins** [reply]
There doesn't seem to be any downside to adding this, assuming it's a single file addition. Is there anything we should be aware of? If not then I'm fine with a PR to add it.

**Reply by killermoehre** [reply]
I created a PR for this https://github.com/renovatebot/renovate/pull/12811.

**Reply by rarkins** [reply]
Does this work, considering our repo is uncompiled TypeScript?

**Reply by andormarkus** [reply]
Last time when I wanted to install renovate into a clean environment the following bug blocked it:
https://github.com/npm/cli/issues/3580

**Reply by andormarkus** [reply]
Underlying pre-commit issue: https://github.com/pre-commit/pre-commit/issues/1440

**Reply by viceice** [reply]
as commented in #12811, this project needs yarn and a compile step, Is that possible as pre step  for `pre-commit`?

**Reply by killermoehre** [reply]
No, it isn't. `pre-commit` just does a `npm install .` after checking out the repository.

**Comment by electriquo** [comment]
from what i know, pre-commit does not have a support for setting environment variables dynamically, in our case [`RENOVATE_CONFIG_FILE`](https://github.com/renovatebot/renovate/blob/main/docs/usage/getting-started/running.md#global-config). if it did, then we could have done something like

```yaml
# .pre-commit-hooks.yaml
- id: renovate-config-validator
  name: Validate Renovate configuration
  description: Validate Renovate configuration using renovate-config-validator
  entry: -e RENOVATE_CONFIG_FILE=<pass the detected filename here> renovate/renovate renovate-config-validator
  language: docker_image
  pass_filenames: false
  files: (^|/).?renovate(?:rc)?(?:\.json5?)?$
```

note the unpinned docker image version that is used above. alternatively, if renovate-config-validator would accept the filename as a parameter, we could add pre-commit hooks to renovate code base. it should look something like

```yaml
# .pre-commit-hooks.yaml
- id: renovate-config-validator
  name: Validate Renovate configuration
  description: Validate Renovate configuration using renovate-config-validator
  entry: renovate/renovate renovate-config-validator
  language: docker_image
  pass_filenames: true
  files: (^|/).?renovate(?:rc)?(?:\.json5?)?$
```

the proposal uses the docker image to eliminate the troublesome in cloning renovate repository, install nodejs package and then transpile the project.

i did not review the logic renovate-config-validator. if it only verifies that the schema of the file, then running other pre-commit hook that validate renovate schema might be another sufficient alternative.
