### DISCUSSION TITLE
Renovate-runner use on gitlab.com - defaults

### DISCUSSION THREAD

**Discussion by StingRayZA** [renovatebot/renovate#11072] [Request Help] [answered]
Hi

I'm trying to start using [renovate-runner](https://gitlab.com/renovate-bot/renovate-runner) on some private gitlab.com projects. So far it's working really well - I've worked through two projects with a manual onboard. I've made it onboard a few more projects, but I'd like to be able to tweak the settings of the onboarding MR (PR)...

Settings I'd like to change:

* renovate config file from `renovate.json` -> `.gitlab/renovate.json`
* default config contents - should I just set the `RENOVATE_ONBOARDING_CONFIG` variable?

I've found a bunch of things I can change with CI Variables (found them [here in `_common.gitlab-ci.yml`](https://gitlab.com/renovate-bot/renovate-runner/-/blob/main/templates/_common.gitlab-ci.yml) - is this the right way to do it? I can't find any explicit docs for these variables, so there's been a bit of trial and error with tweaking these so far. 

Thanks in advance!

**Comment by viceice** [comment, marked as answer]
Configure global bot config basics 👉  https://docs.renovatebot.com/self-hosting/#configuration

```yaml
include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate-dind.gitlab-ci.yml'

# override templates env
variables:
  RENOVATE_ONBOARDING_CONFIG: '{"$$schema": "https://docs.renovatebot.com/renovate-schema.json", "extends": ["local>my/preset"] }'
  RENOVATE_ONBOARDING_CONFIG_FILE_NAME: .gitlab/renovate.json

```
