### DISCUSSION TITLE
How to replace/customize the format of the version?

### DISCUSSION THREAD

**Discussion by okainov** [renovatebot/renovate#11233] [Request Help]
I think I missed the part of documentation which would point to possibility to customize version format in the resulted files in the repo.

Here is particular example:

CURL (https://github.com/curl/curl/releases/tag/curl-7_78_0) has tags/releases like `7_78_0`. In some of our files we use version with dots like `7.78.0`. 

Alternative (but probably the same) question would be if we would have only part of the version (like without trailing zero, but just `7.78`). There is case in [documentation](https://docs.renovatebot.com/configuration-options/#extractversion) to grab only major in minor, but it still assumes the very same format and doesn't seem to show ways to shuffle/replace something inside the version in more advanced way than just substring.

I would think `extractVersion` or template should be the suitable place for this, but it seems it doesn't support `major/minor/patch` regexp groups, only whole `version`, so my understanding is that it strictly means that final version will be a substring of version in datasource.

Question - what would be the configuration for Renovate which would work for this case?

config:
```yaml

    {
      "fileMatch": ["\\.yaml$"],
      "matchStrings": [
        "#\\s*renovate:\\s*datasource=(?<datasource>.*?) depName=(?<depName>.*?)( versioning=(?<versioning>.*?))?\\s+.*?(?<currentValue>\\d+[.]\\d+[.]\\d+)\\s"
      ],
      "versioningTemplate": "{{#if versioning}}{{{versioning}}}{{else}}semver{{/if}}",
      
      "extractVersionTemplate": "(?<version>\\d+.\\d+.\\d+)"
    }
```

related part of the file to be renovated:
```yaml
 curl:
    # renovate: datasource=github-releases depName=curl/curl versioning=regex:.*?(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$
    - version: 7.77.0
      paths:
```
