### DISCUSSION TITLE
Use parallel matrix jobs on GitLab

### DISCUSSION THREAD

**Discussion by mbrodala** [renovatebot/renovate#11314] [Suggest an Idea]
GitLab allows setting up [matrix jobs](https://docs.gitlab.com/ee/ci/yaml/#parallel-matrix-jobs) to have multiple jobs run in parallel. This speeds up processing for a single job and makes the overall pipeline more resilient against failures in single jobs.

It would be useful if Renovate could make use of this. Technically one could manually add `parallel` to the `renovate` pipeline job but this would require statically listing all repositories Renovate should process. (E.g. using [`autodiscoverFilter`](https://docs.renovatebot.com/self-hosted-configuration/#autodiscoverfilter) or [`repositories`](https://docs.renovatebot.com/self-hosted-configuration/#repositories))

A more flexible approach would be running Renovate twice in each pipeline:

1. Output a list of repositories Renovate would process if it was run regularly.
2. Run Renovate for a single repository.

This could be achieved using [dynamic child pipelines](https://docs.gitlab.com/ee/ci/pipelines/parent_child_pipelines.html#dynamic-child-pipelines). Where the list of repositories from the first run is used to generate a GitLab pipeline config for the actual run.

Before digging deeper into this my question: can Renovate already output the list of repositories it would process in a regular run? Of course, without actually processing them. ;-)

**Comment by rarkins** [comment]
I don't think it can do that already. Even with `--dry-run` it's going to do a full dry run through each repo.

Assuming this will require changes to Renovate's code in this repo, and you plan on making such changes, it would be good if you can create a feature request issue first and describe the changes that would need to be made. We'd want to then decide:
- Is this the best way to do it? Go ahead
- Is there a better way - please take our advice, or
- This will add too much complexity and we're not happy to add it at this point until a better way is found

**Comment by viceice** [comment]
I think this can be easily achived with a small script with is fetching repos via gitlab api and then prepareing the dynamic pipelines. 
I don't see much value to include such complex stuff in renovate. Bu we can extend https://gitlab.com/renovate-bot/renovate-runner to have such an option / implementation

**Reply by mbrodala** [reply]
Sure, this doesn't need to be part of Renovate itself since it's too specific for GitLab anyways. (Although e.g. Github Actions have a [similar feature](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix).)

Still a slight integration would ensure that whatever fetches the list of repositories does it exactly the same way as Renovate. Otherwise we risk getting out of sync which would mean repositories are not processed or processed without access.

**Reply by viceice** [reply]
OK, but even for renovate it higly depends on platform, eg for gitlab we do this query:

`projects?membership=true&per_page=100&with_merge_requests_enabled=true&min_access_level=30`

https://github.com/renovatebot/renovate/blob/5b38392796e2378ed01523a75fe63d6b140f8a08/lib/platform/gitlab/index.ts#L124-L139

**Comment by mbrodala** [comment]
For now we use the following to at least have some parallelization:

```yaml
renovate:
  # ...
  parallel:
    matrix:
      - RENOVATE_AUTODISCOVER_FILTER:
          - <group>/a*
          - <group>/b*
          - <group>/c*
          - <group>/d*
          - <group>/e*
          - <group>/f*
          - <group>/g*
          - <group>/h*
          - <group>/i*
          - <group>/j*
          - <group>/k*
          - <group>/l*
          - <group>/m*
          - <group>/n*
          - <group>/o*
          - <group>/p*
          - <group>/q*
          - <group>/r*
          - <group>/s*
          - <group>/t*
          - <group>/u*
          - <group>/v*
          - <group>/w*
          - <group>/x*
          - <group>/y*
          - <group>/z*
  resource_group: $RENOVATE_AUTODISCOVER_FILTER
  # ...

```

This basically groups all of our repositories by letter leading to 26 jobs running in parallel. While the workload is not distributed evenly at all it is rather cheap to set up and already helps. If necessary one could add more specific prefixes.

**Comment by mbrodala** [comment]
I just saw that a new `--write-discovered-repos` flag has been added with [Renovate 27.15.0](https://github.com/renovatebot/renovate/releases/tag/27.15.0).

One could probably use this to generate a dynamic child pipeline with one job per repository.

**Reply by viceice** [reply]
you can try that 😉

**Reply by mbrodala** [reply]
OK, I finally got around and finished this exactly like desired. Now we have a [generated child pipeline](https://docs.gitlab.com/ee/ci/pipelines/parent_child_pipelines.html#dynamic-child-pipelines) which runs the `renovate` job once for each project in parallel. :tada: 

![image](https://user-images.githubusercontent.com/5037116/164419829-11e3b187-545b-4ff1-842e-5d85c19a4156.png)

For this we have two GitLab YAML files, the toplevel `.gitlab-ci.yaml` and a `templates/.gitlab-ci.yaml`:

<details>
<summary>.gitlab-ci.yml</summary>

```yaml
include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate-dind.gitlab-ci.yml'
    ref: v8.81.6

renovate:
  variables:
    RENOVATE_AUTODISCOVER: 'true'
    RENOVATE_AUTODISCOVER_FILTER: '<group>/**'
  script:
    - renovate --write-discovered-repos=template/renovate-repos.json
    - sed "s~###RENOVATE_REPOS###~$(cat template/renovate-repos.json)~" template/.gitlab-ci.yml > .gitlab-renovate-repos.yml
  artifacts:
    paths:
      - renovate-repos.json
      - .gitlab-renovate-repos.yml

renovate:repos:
  stage: deploy
  needs:
    - renovate
  inherit:
    variables: false
  trigger:
    include:
      - job: renovate
        artifact: .gitlab-renovate-repos.yml
```
</details>

This slightly adjusts the `renovate` job imported from [renovate-bot/renovate-runner](https://gitlab.com/renovate-bot/renovate-runner) to fetch and write the list of discovered repositories to `template/renovate-repos.json`. This file and the `template/.gitlab-ci.yml` is then used to generate a `.gitlab-renovate-repos.yml`. Here we use `sed` but anything else would be equally fine; for `sed` it's important to use a different delimiter than the common `/` since the `template/renovate-repos.json` will contain `/` characters.

The `inherit.variables: false` here is essential to [ensure all predefined GitLab variables are populated](https://gitlab.com/gitlab-org/gitlab/-/issues/214340#note_423996331) normally in the child pipeline.

<details>
<summary>template/.gitlab-ci.yml</summary>

```yaml
include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate-dind.gitlab-ci.yml'
    ref: v8.81.6

variables:
  RENOVATE_ONBOARDING: 'true'

renovate:
  parallel:
    matrix:
      - RENOVATE_EXTRA_FLAGS: ###RENOVATE_REPOS###
  resource_group: $RENOVATE_EXTRA_FLAGS
```
</details>

This is a fairly basic integration of the original `renovate` job with the most interesting part being the `RENOVATE_EXTRA_FLAGS` variable used as [parallel matrix](https://docs.gitlab.com/ee/ci/yaml/#parallelmatrix). Since `template/renovate-repos.json` contains a JSON array, it can directly be used as YAML list here. The `###RENOVATE_REPOS###` is an arbitrary identifier (and valid YAML comment).

The `template/.gitlab-ci.yml` uses this filename since the [Renovate `gitlabci-include` manager](https://docs.renovatebot.com/modules/manager/gitlabci-include/) works with `.gitlab-ci.yml` only by default and we want to leave it at that. (Yes, we use the Renovate runner to renovate our Renovate runner.)

The result:

<details>
<summary>Example .gitlab-renovate-repos.yml</summary>

```yaml
include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate-dind.gitlab-ci.yml'
    ref: v8.81.6

variables:
  RENOVATE_ONBOARDING: 'true'

renovate:
  parallel:
    matrix:
      - RENOVATE_EXTRA_FLAGS: ["<group>/project-foo", "<group>/project-bar", ...]
  resource_group: $RENOVATE_EXTRA_FLAGS
```
</details>
