### DISCUSSION TITLE
Gradle deepExtract /certs/client/ca.pem: no such file or directory

### DISCUSSION THREAD

**Discussion by t-kulmburg** [renovatebot/renovate#11317] [Request Help]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

gitlab.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

26.1.2

### Describe the bug

I am running renovate on gitlab.com with GitLab CI. When running gradle deepExtract, there is an issue pulling the renovate/gradle docker image. 

I am not sure if this is a real certificate error, or if it is trying to pull the wrong image `docker.io/renovate/gradle\nunable`.
I am using the https://gitlab.com/renovate-bot/renovate-runner/ runner as base.

Yesterday  I started having this issue with 25.x, and today updating to 26 didn't help.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Start gradle command (repository=...)
       "cmd": "./gradlew --init-script renovate-plugin.gradle renovate"
DEBUG: Using docker to execute (repository=...)
DEBUG: No tag or tagConstraint specified (repository=...)
       "image": "docker.io/renovate/gradle"
DEBUG: Fetching Docker image: docker.io/renovate/gradle (repository=...)
 WARN: Gradle extraction failed (repository=...)
       "errMessage": "Command failed: docker pull docker.io/renovate/gradle\nunable to resolve docker endpoint: open /certs/client/ca.pem: no such file or directory\n"
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
It seems like `docker pull` has failed. Is/was this working on v25 previously?

**Comment by viceice** [comment]
Please provide your pipeline config. It seems you've made some wrong changes.

**Comment by t-kulmburg** [comment]
I just ran it with the template from the https://gitlab.com/renovate-bot/renovate-runner/, as you can see in the config below.

The template uses the following 25 version:`renovate/renovate:25.76.1-slim@sha256:8684628b84867b2f8cf3671855af4a635a0077fc3fa9185bdfe7097f8abff1ce`

I still get the exact same log output. Here is my pipeline configuration:

```
include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate-dind.gitlab-ci.yml'


variables:
  LOG_LEVEL: debug
  RENOVATE_HOST_RULES: '[{"hostType":"maven","matchHost":"https://gitlab.com/api/v4/groups/<REDACTED>/-/packages/maven/","token":"$RENOVATE_TOKEN"}, {"hostType":"docker","matchHost":"registry.gitlab.com","username":"$USER","password":"$RENOVATE_TOKEN"}]'
  RENOVATE_EXTRA_FLAGS: '--autodiscover=true --autodiscover-filter=<REDACTED>/* --print-config=true'
  RENOVATE_CUSTOM_ENV_VARIABLES: '{"CI_JOB_TOKEN":"$CI_JOB_TOKEN", "RENOVATE_RUN":"true"}'

renovate:
  tags:
    - type:build
  only:
    - schedules
    - pushes

stages:
  - test
  - deploy
  - release

```
