### DISCUSSION TITLE
Renovate wont use Node 16 to update lock file

### DISCUSSION THREAD

**Discussion by darthf1** [renovatebot/renovate#11372] [Request Help] [answered]
Hi!

In my `package.json` I defined the `engines.node` and `engines.npm` fields, but Renovate will stay on the current LTS version. How can I make Renovate use Node 16 instead of 14 to update my lock file? 

-------
`package.json`
```json
{
  "engines": {
    "node": "^16.6.2",
    "npm": "^7.20.3"
  },
}
```

In my `.npmrc` file I set `engine-strict`. 
```
engine-strict=true
```

But now Renovate cant update my Node deps:
```
WARN: artifactErrors (repository=xxx/xxx, branch=renovate/all-minor-patch)
       "artifactErrors": [
         {
           "lockFile": "client/package-lock.json",
           "stderr": "npm ERR! code ENOTSUP\nnpm ERR! notsup Unsupported engine for client-next@1.0.0: wanted: {\"node\":\"^16.6.2\",\"npm\":\"^7.20.3\"} (current: {\"node\":\"14.17.0\",\"npm\":\"6.14.13\"})\nnpm ERR! notsup Not compatible with your version of node/npm: client-next@1.0.0\nnpm ERR! notsup Not compatible with your version of node/npm: client-next@1.0.0\nnpm ERR! notsup Required: {\"node\":\"^16.6.2\",\"npm\":\"^7.20.3\"}\nnpm ERR! notsup Actual:   {\"npm\":\"6.14.13\",\"node\":\"14.17.0\"}\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /builds/xHeNr941/0/xxx/xxx/renovate/cache/others/npm/_logs/2021-08-22T22_30_15_000Z-debug.log\n"
         }
       ]
```

I'm using Gitlab  and configured Renovate to run as a scheduled job. I have my own Gitlab runner hosted via Kubernetes.

```toml
[[runners]]
  environment = ["FF_GITLAB_REGISTRY_HELPER_IMAGE=1"]
  [runners.feature_flags]
    FF_GITLAB_REGISTRY_HELPER_IMAGE = true
  [runners.kubernetes]
    image = "ubuntu:20.04"
    [runners.cache]
      Type = "s3"
      Path = "runner"
      Shared = true
    [runners.cache.s3]
      ServerAddress = "xxx"
      AccessKey = "xxx"
      SecretKey = "xxx"
      BucketName = "xxx"
      Insecure = true
```

I tried updating my `renovate.json` with the rule below, but I guess that's only applicable for updating the Node package itself as a dependency.
```json
"packageRules": [
    {
      "matchPackageNames": ["node"],
      "ignoreUnstable": false
    },
],
```

My gitlab-ci job definition:
```yaml
deploy:renovate:
  stage: deploy
  image: renovate/renovate
  cache:
    key: ${CI_COMMIT_REF_SLUG}-renovate-02
    paths:
      - ${CI_PROJECT_DIR}/renovate
  variables:
    GIT_STRATEGY: none
    GITHUB_COM_TOKEN: ${GITHUB_COM_TOKEN}
    RENOVATE_BASE_DIR: ${CI_PROJECT_DIR}/renovate
    RENOVATE_ENDPOINT: ${CI_API_V4_URL}
    RENOVATE_PLATFORM: gitlab
    RENOVATE_TOKEN: ${RENOVATE_TOKEN}
    RENOVATE_EXTRA_FLAGS: 'xxx'
    RENOVATE_GIT_AUTHOR: xxx
    RENOVATE_ONBOARDING_CONFIG: '{"$$schema": "https://docs.renovatebot.com/renovate-schema.json", "extends": ["config:base"] }'
    RENOVATE_OPTIMIZE_FOR_DISABLED: 'true'
    RENOVATE_REPOSITORY_CACHE: 'true'
    RENOVATE_REQUIRE_CONFIG: 'true'
    RENOVATE_ONBOARDING: 'false'
    RENOVATE_IGNORE_PR_AUTHOR: 'true'
    RENOVATE_EXTENDS: 'github>whitesource/merge-confidence:beta'
    RENOVATE_LOG_FILE: renovate-log.ndjson
    RENOVATE_LOG_FILE_LEVEL: debug
    LOG_LEVEL: info
  artifacts:
    when: always
    expire_in: 1d
    paths:
      - "$RENOVATE_LOG_FILE"
  script:
    - renovate $RENOVATE_EXTRA_FLAGS
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
```
