### DISCUSSION TITLE
Artifact update problem with Renovate Runner

### DISCUSSION THREAD

**Discussion by darthf1** [renovatebot/renovate#11403] [Request Help]
Hi,

I switched to the `Renovate Runner` with `docker-dind`, but now I'm getting artifact issues updating my helm and php dependencies. Other dependencies get updated ok.

Managers in use:
```json
"managers": {
 "composer": {"fileCount": 1, "depCount": 75},
 "docker-compose": {"fileCount": 1, "depCount": 6},
 "dockerfile": {"fileCount": 2, "depCount": 5},
 "gitlabci": {"fileCount": 1, "depCount": 21},
 "helm-values": {"fileCount": 2, "depCount": 6},
 "helmv3": {"fileCount": 2, "depCount": 5},
 "npm": {"fileCount": 1, "depCount": 55},
 "pip_setup": {"fileCount": 1, "depCount": 4}
},
```

helmv3 issue:
```
Command failed: docker run --rm --name=renovate_helm --label=renovate_child -v "/builds/6_niUUZp/0/www/www/renovate/repos/gitlab/xxx/xxx":"/builds/6_niUUZp/0/www/www/renovate/repos/gitlab/xxx/xxx" -v "/builds/6_niUUZp/0/www/www/renovate/cache":"/builds/6_niUUZp/0/www/www/renovate/cache" -w "/builds/6_niUUZp/0/www/www/renovate/repos/gitlab/xxx/" docker.io/renovate/helm bash -l -c "helm dependency update ''"
Error: no cached repository for helm-manager-e3c72eeff68d5caf4d7d2fc7dd2472e04c713619960920455d7d9af64a25b544 found. (try 'helm repo update'): open /home/ubuntu/.cache/helm/repository/helm-manager-e3c72eeff68d5caf4d7d2fc7dd2472e04c713619960920455d7d9af64a25b544-index.yaml: no such file or directory
```

php composer issue:
```
Command failed: docker run --rm --name=renovate_php --label=renovate_child -v "/builds/6_niUUZp/0/www/www/renovate/repos/gitlab/xxx/xxx":"/builds/6_niUUZp/0/www/www/renovate/repos/gitlab/xxx/xxx" -v "/builds/6_niUUZp/0/www/www/renovate/cache":"/builds/6_niUUZp/0/www/www/renovate/cache" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w "/builds/6_niUUZp/0/www/www/renovate/repos/gitlab/xxx/xxxapi" docker.io/renovate/php:8.0.9 bash -l -c "install-tool composer 2.1.6 && composer update symfony/flex --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins"
curl: (28) Operation timed out after 300156 milliseconds with 0 out of 0 bytes received
```

My CI job config (taken from https://gitlab.com/renovate-bot/renovate-runner/-/blob/main/templates/_common.gitlab-ci.yml and https://gitlab.com/renovate-bot/renovate-runner/-/blob/main/templates/renovate-dind.gitlab-ci.yml):
```yaml
deploy:renovate:
  stage: deploy
  image: renovate/renovate:slim
  services:
    - docker:20.10.8-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_TLS_CERTDIR: /certs
    DOCKER_CERT_PATH: /certs/client
    GIT_STRATEGY: none
    GITHUB_COM_TOKEN: ${GITHUB_COM_TOKEN}
    RENOVATE_BASE_DIR: ${CI_PROJECT_DIR}/renovate
    RENOVATE_ENDPOINT: ${CI_API_V4_URL}
    RENOVATE_PLATFORM: gitlab
    RENOVATE_TOKEN: ${RENOVATE_TOKEN}
    RENOVATE_EXTRA_FLAGS: 'xxx'
    RENOVATE_GIT_AUTHOR: xxx
    RENOVATE_ONBOARDING_CONFIG: '{"$$schema": "https://docs.renovatebot.com/renovate-schema.json", "extends": ["config:base"] }'
    RENOVATE_OPTIMIZE_FOR_DISABLED: 'true'
    RENOVATE_REPOSITORY_CACHE: 'true'
    RENOVATE_REQUIRE_CONFIG: 'true'
    RENOVATE_ONBOARDING: 'false'
    RENOVATE_IGNORE_PR_AUTHOR: 'true'
    RENOVATE_EXTENDS: 'github>whitesource/merge-confidence:beta'
    RENOVATE_LOG_FILE: renovate-log.ndjson
    RENOVATE_LOG_FILE_LEVEL: debug
    LOG_LEVEL: info
  cache:
    key: ${CI_COMMIT_REF_SLUG}-renovate
    paths:
      - renovate/cache/renovate/**
  artifacts:
    when: always
    expire_in: 1d
    paths:
      - "$RENOVATE_LOG_FILE"
  script:
    - renovate $RENOVATE_EXTRA_FLAGS
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
```

My gitlab runner config (from https://docs.gitlab.com/runner/executors/kubernetes.html#using-dockerdind and https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#docker-in-docker-with-tls-enabled-in-kubernetes):
```toml
[[runners]]
  [runners.kubernetes]
    image = "ubuntu:20.04"
    privileged = true
  [[runners.kubernetes.volumes.empty_dir]]
    name = "docker-certs"
    mount_path = "/certs/client"
    medium = "Memory"
  [runners.cache]
    Type = "s3"
    Path = "runner"
    Shared = true
  [runners.cache.s3]
    ServerAddress = "minio:9000"
    AccessKey = "xxx"
    SecretKey = "xxx"
    BucketName = "xxx"
    Insecure = true
```
