### DISCUSSION TITLE
Passing ssh-agent socket to composer and other called tools

### DISCUSSION THREAD

**Discussion by simonschaufi** [renovatebot/renovate#11575] [Request Help] [answered]
I'm struggling with an error and I don't know what is the source of it. The renovate pipeline runs successfully but in the PR that contains the composer update, I see the following error:

```
Command failed: docker pull docker.io/renovate/php
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? 
```

I'm using the slim docker image. Docker is definitively running on my host system. Do you have an idea what is wrong here?

**Comment by viceice** [comment]
Please add some more context from previous discussion. Looks like you don't mount the docker socket to the pipeline.

If you like to use dind, you need some more env config:

* https://gitlab.com/renovate-bot/renovate-runner/-/blob/main/templates/renovate-dind.gitlab-ci.yml
* https://gitlab.com/renovate-bot/renovate-runner#other-config-options
* https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-the-docker-executor-with-the-docker-image-docker-in-docker

**Reply by simonschaufi** [reply]
I have really no idea how renovate internally works, it's just a black box for me. I don't know when I need docker in docker and when not. I just have a minimal php composer project to play around and then was confronted with the error and have no idea as renovate error messages are not clear for me.

All my files can be seen here: https://github.com/renovatebot/renovate/issues/5616#issuecomment-908324685

**Reply by viceice** [reply]
Pleas follow https://gitlab.com/renovate-bot/renovate-runner to setup a basic working pipeline. Then we can fine tune it to support your ssh agent stuff.

**Reply by simonschaufi** [reply]
@viceice can we do a live hacking session together to work on this issue https://github.com/renovatebot/renovate/issues/5616#issuecomment-912605392 ?

**Reply by viceice** [reply]
no, sorry, out of time

**Reply by viceice** [reply]
Please follow our gitlab pipeline docu to get a basic running renovate pipeline. If you can adapt it later to your needs,
i can't help you with a fully custom pipeline.

**Reply by simonschaufi** [reply]
@viceice  The basic pipeline works great, I have it running in several other projects. The feature which several people already requested is that renovate is aware of private ssh keys so it is able to fetch those repos as well and for that I need some help.

**Reply by viceice** [reply]
Are yoiu using the dind ot the full version on your working pipelines?

**Reply by simonschaufi** [reply]
I'm using the full version and not the dind. I only want to talk with you about https://github.com/renovatebot/renovate/issues/5616#issuecomment-912605392, nothing else

**Reply by viceice** [reply]
ok, so your pipeline should look like this:

```yaml
include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate.gitlab-ci.yml'
    ref: v1.0.0
```

**Reply by simonschaufi** [reply]
I guess we are mixing up 2 different topics here. I only want to talk with you about implementing this: https://github.com/renovatebot/renovate/issues/5616#issuecomment-912605392, nothing else

**Reply by viceice** [reply]
Sure, but the the headline of this discussion is about DinD, not SSH-Agent.

So i posted two solutions below, so your can choose / try one of them.

**Comment by viceice** [comment, marked as answer]
Full renovate image with SSH agent

**.gitlab-ci.yml**
```yaml
include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate.gitlab-ci.yml'
    ref: v4.4.2 # check latest at https://gitlab.com/renovate-bot/renovate-runner/-/releases

variables:
  SSH_AUTH_SOCK: $RENOVATE_BASE_DIR/cache/ssh.sock
  RENOVATE_CUSTOM_ENV_VARIABLES: '{"SSH_AUTH_SOCK":"$RENOVATE_BASE_DIR/cache/ssh.sock"}'

before_script:
  - mkdir -p $RENOVATE_BASE_DIR/cache
  - eval $(ssh-agent -s -a $SSH_AUTH_SOCK)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan example.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
```

See comment below for DinD  / slim solution

**Reply by simonschaufi** [reply]
I had to include the project template file locally like this because it's not working on a self running gitlab instance:

```
include:
  - remote: 'https://gitlab.com/renovate-bot/renovate-runner/-/raw/main/templates/_common.gitlab-ci.yml'

image: renovate/renovate:27.6.3@sha256:e11e1c1fcd13141b62e315bc0ca61c38d3d583b2f8719665f7b6407bcbef84f3
```

but now I get this:

```
$ renovate $RENOVATE_EXTRA_FLAGS
 WARN: No repositories found - did you want to run with flag --autodiscover?
```

In my other projects it works if I call renovate like that: `renovate "${CI_PROJECT_PATH}"`

**Reply by viceice** [reply]
simply add `RENOVATE_EXTRA_FLAGS: $CI_PROJECT_PATH` to the env vars

```yaml
include:
  - remote: 'https://gitlab.com/renovate-bot/renovate-runner/-/raw/main/templates/_common.gitlab-ci.yml'

image: renovate/renovate:27.6.4@sha256:eeda293ad6cf866acc9b90c0f0f54a21baf3e3287dd90dbc365e742df0980a0e

variables:
  SSH_AUTH_SOCK: $RENOVATE_BASE_DIR/cache/ssh.sock
  RENOVATE_CUSTOM_ENV_VARIABLES: '{"SSH_AUTH_SOCK":"$RENOVATE_BASE_DIR/cache/ssh.sock"}'
  RENOVATE_EXTRA_FLAGS: $CI_PROJECT_PATH

before_script:
  - mkdir -p $RENOVATE_BASE_DIR/cache
  - eval $(ssh-agent -s -a $SSH_AUTH_SOCK)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan example.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
```

we usally set `RENOVATE_EXTRA_FLAGS` in gitlab ui

**Reply by simonschaufi** [reply]
:tada: this works! thank you! So this finally resolves issue #5616

**Reply by simonschaufi** [reply]
@viceice Sorry for the false alarm! Yes I had a successfully pipeline afterwards but the whole process still doesn't get through all the way till the end as I still get this error, especially when the followup task `renovate/artifacts` runs:

```
DEBUG: rawExec err (repository=vendor/ci_test_renovate, branch=renovate/giggsey-libphonenumber-for-php-8.x-lockfile)
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "composer update giggsey/libphonenumber-for-php --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins",
         "stdout": "",
         "stderr": "Loading composer repositories with package information
[RuntimeException]
Failed to execute git clone --mirror -- 'git@git.vendor.de:vendor/surf-deployment.git' '/builds/vendor/ci_test_renovate/renovate/cache/others/composer/vcs/git-git.vendor.de-vendor-surf-deployment.git/'
Cloning into bare repository '/builds/vendor/ci_test_renovate/renovate/cache/others/composer/vcs/git-git.vendor.de-vendor-surf-deployment.git'...
Warning: Permanently added the ECDSA host key for IP address '192.168.0.0' to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
git@git.vendor.de: Permission denied (publickey,password).
fatal: Could not read from remote repository
Please make sure you have the correct access rights and the repository exists
```

Do you have a test repository on gitlab where it actually works?

**Reply by viceice** [reply]
I don't use any ssh with renovate so please create two minimal repos one should be private and the public should only reference the private one.

Then run with `RENOVATE_LOG_FILE_LEVEL=trace` which will print a huge logfile `renovate-log.ndjson` as build artifact. please extract the context lines to that error message. That should print all args including the passed env.

**Comment by viceice** [comment]
Slim image with DinD and SSH agent. Requires [GitLab DinD configuration](https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-the-docker-executor-with-the-docker-image-docker-in-docker) for self-hosted gitlab runner.

**.gitlab-ci.yml**
```yaml
include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate-dind.gitlab-ci.yml'
    ref: v4.4.2 # check latest at https://gitlab.com/renovate-bot/renovate-runner/-/releases

variables:
  SSH_AUTH_SOCK: $RENOVATE_BASE_DIR/cache/ssh.sock
  RENOVATE_CUSTOM_ENV_VARIABLES: '{"SSH_AUTH_SOCK":"$RENOVATE_BASE_DIR/cache/ssh.sock"}'

before_script:
  - mkdir -p $RENOVATE_BASE_DIR/cache
  - eval $(ssh-agent -s -a $SSH_AUTH_SOCK)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan example.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
```
