### DISCUSSION TITLE
Gitlab private repository: renovate local successfuly, in gitlab pipeline error message "repo not found"

### DISCUSSION THREAD

**Discussion by svenmarnitz** [renovatebot/renovate#11697] [Request Help]
Moin,

When I execute the renovate command locally, it is successful.
But if I run it in a Gitlab pipeline, I get the message that the repository cannot be found.

config.js
```
module.exports = {
    "hostRules": [
        {
            "matchHost": "https://gitlab.com/api/v4/",
            "platformType": "gitlab",
            "token": process.env.RENOVATE_TOKEN,
        }
    ],
    platform: "gitlab",
    timezone: "Europe/Berlin",
    requireConfig: true,
    onboarding: true,
    onboardingConfig: {
        extends: ["config:base"],
    },
    stabilityDays: 3,
    logLevel: 'verbose',
    logFile: "renovate-log.json",
    gitAuthor: "<author>",
    baseBranches: ["master"],
    assignees: ["<assignee>"],
    repositories: [
        "namespace/repo-name",
    ]
};
```

renovate.json
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "prHourlyLimit": 100,
  "prConcurrentLimit": 3,
  "separateMinorPatch": false,
  "rangeStrategy": "pin",
  "baseBranches": [
    "master"
  ],
  "enabledManagers": [
    "npm"
  ]
}
```

gitlab-ci.yml
```
image: <own renovate image>

stages:
  - update

dependencies:
  tags:
    - docker
  only:
    - schedules
    - web
  stage: update
  before_script:
    - touch $PWD/renovate-log.json
    - npm i --silent
  script:
    -  RENOVATE_TOKEN="${RENOVATE_TOKEN}" GITHUB_COM_TOKEN="${GITHUB_COM_TOKEN}" npm run renovate -- --dry-run
  artifacts:
    when: always
    paths:
      - renovate-log.json
```

error message:
```
{"name":"renovate","hostname":"runner-<runner>-concurrent-0","pid":105,"level":20,"logContext":"AcmoRQvUu","repository":"<namespace>/<repo>","url":"https://gitlab.com/api/v4/projects/<namespace>%2F<repo>","msg":"GitLab API 404","time":"2021-09-12T17:15:46.456Z","v":0}
```

Does anyone have any helpful hints?

thx
Sven
