### DISCUSSION TITLE
Timeouts while fetching release notes

### DISCUSSION THREAD

**Discussion by pshakhov** [renovatebot/renovate#11736] [Request Help] [answered]
Hello. We are using renovate as self-hosted i suppose. Our CI/CD system is Gitlab, and all its integrations to external resources routing via proxies, and i suppose this leads to this error:
```json
{"name":"renovate","hostname":"4c42e0ac264b","pid":9,"level":20,"logContext":"UQOy8chYl","repository":"vladmihalcea/hibernate-types","type":"github","apiBaseUrl":"https://api.github.com/","err":{"name":"TimeoutError","code":"ETIMEDOUT","timings":{"start":1631605342581,"socket":1631605342581,"lookup":1631605342604,"error":1631605402607,"phases":{"wait":0,"dns":23,"total":60026}},"event":"request","message":"Timeout awaiting 'request' for 60000ms","stack":"RequestError: Timeout awaiting 'request' for 60000ms\n    at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/dist/source/core/index.js:956:65)\n    at Object.onceWrapper (events.js:520:26)\n    at ClientRequest.emit (events.js:412:35)\n    at ClientRequest.emit (domain.js:470:12)\n    at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at TLSSocket.socketErrorListener (_http_client.js:475:9)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:470:12)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)\n    at Timeout.timeoutHandler [as _onTimeout] (/usr/src/app/node_modules/got/dist/source/core/utils/timed-out.js:36:25)\n    at listOnTimeout (internal/timers.js:559:11)\n    at processTimers (internal/timers.js:500:7)","options":{"headers":{"user-agent":"RenovateBot/27.6.2 (https://github.com/renovatebot/renovate)","accept":"application/vnd.github.v3+json","authorization":"***********","accept-encoding":"gzip, deflate, br"},"url":"https://api.github.com/repos/vladmihalcea/hibernate-types/releases?per_page=100","hostType":"github","username":"","password":"","method":"GET","http2":false}},"msg":"getReleaseList error","time":"2021-09-14T07:43:22.608Z","v":0}
```
How can i set up explicitly proxy for Renovate interactions withj Github?

**Comment by viceice** [comment, marked as answer]
1. please format your logs
2. you can use normal linux proxy environment variables

**Reply by pshakhov** [reply]
> 2. you can use normal linux proxy environment variables

Which proxy env vars i can use? 
I used in .gitlab-ci.yml this:
```yml
HTTPS_PROXY: https//our.proxy.com:8080
HTTPS_PROXY: http://our.proxy.com:8080
no_proxy: 'localhost, 127.0.0.1, docker, our.clour, our.cloud.com'
```

**Reply by viceice** [reply]
We are reading those here 
https://github.com/renovatebot/renovate/blob/03ac68e912f3646766f24cb5593ad318c5335b92/lib/proxy.ts#L4

Can you please share your pipeline

**Reply by pshakhov** [reply]
> Can you please share your pipeline
```yaml
variables:
  HTTPS_PROXY: http://proxy.our.ru:8080
  HTTP_PROXY: http://proxy.our.ru:8080
  no_proxy: 'localhost,127.0.0.1,docker,.our.cloud,.our.ru,.ourcloud.ru'
  LOG_FORMAT: 'json'
  LOG_LEVEL: 'debug'
  RENOVATE_TOKEN: $renovate_token
  GITHUB_COM_TOKEN: $github_com_token

services:
  - name: docker-proxy.our.ru/docker:20.10-dind
    alias: docker

stages:
  - pre-build
  - renovate

renovate-config-validator:
  stage: pre-build
  trigger:
    project: infra/renovate-config
    branch: master

renovate:
  stage: renovate
  # image: docker-proxy.our.ru/renovate/renovate:24.20.0
  script:
    - docker run --env LOG_LEVEL=debug --env LOG_FORMAT=json
      --env RENOVATE_TOKEN=$renovate_token --env GITHUB_COM_TOKEN=$github_com_token
      --rm -v "$(pwd)/config.js:/usr/src/app/config.js" renovate/renovate
  when: manual

renovate_schedules:
  stage: renovate
  # image: docker-proxy.our.ru/renovate/renovate:24.20.0
  only:
    - schedules
  script:
    - docker run --env LOG_LEVEL=debug --env LOG_FORMAT=json
      --env RENOVATE_TOKEN=$renovate_token --env GITHUB_COM_TOKEN=$github_com_token
      --rm -v "$(pwd)/config.js:/usr/src/app/config.js" renovate/renovate
```

**Reply by viceice** [reply]
You need to pass those variables to the docker container 😉 
You can also pass existing env via `--env LOGE_LEVEL` so the value is used from parent env.

```yaml
renovate:
  stage: renovate
  # image: docker-proxy.our.ru/renovate/renovate:24.20.0
  script:
    - docker run --env LOG_LEVEL --env LOG_FORMAT
      --env RENOVATE_TOKEN --env GITHUB_COM_TOKEN
      --env HTTPS_PROXY --env HTTP_PROXY --env no_proxy
      --rm -v "$(pwd)/config.js:/usr/src/app/config.js" renovate/renovate
  when: manual

renovate_schedules:
  stage: renovate
  # image: docker-proxy.our.ru/renovate/renovate:24.20.0
  only:
    - schedules
  script:
    - docker run --env LOG_LEVEL --env LOG_FORMAT
      --env RENOVATE_TOKEN --env GITHUB_COM_TOKEN
      --env HTTPS_PROXY --env HTTP_PROXY --env no_proxy
      --rm -v "$(pwd)/config.js:/usr/src/app/config.js" renovate/renovate
```

Also checkout our official gitlab pipeline templates at https://gitlab.com/renovate-bot/renovate-runner/
