### DISCUSSION TITLE
How to use an SSH agent socket from a Docker volume?

### DISCUSSION THREAD

**Discussion by mbrodala** [renovatebot/renovate#11745] [Request Help]
Similar to https://github.com/renovatebot/renovate/discussions/11575 but slightly different. (Related: #5616)

We set up an SSH agent using Docker Compose and expose a named volume which contains the SSH agent socket file.

Any of our services can now mount this volume and define `SSH_AUTH_SOCK` pointing to the socket file in the locally mounted directory.

Example `docker-compose.yml`:

```yaml
version: '3.9'

services:
  app:
    # ...
    environment:
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
    volumes:
      - ssh-agent:/.ssh-agent

volumes:
  ssh-agent:
    external: true
```

A GitLab pipeline (on a GitLab shell executor) now runs `docker-compose run --rm -T app <command>` and any command in `app` can rely on a working SSH agent connection.

Now the question: how could we get this setup working with Renovate?

We use GitLab and the DinD version and it's rather unclear how we could mount the agent volume into the Renovate base container and its sidecar containers.

**Comment by viceice** [comment]
can you provide a basic sample pipeline where you use the socket, so i can see how you get the mounts for your services?

**Reply by mbrodala** [reply]
I've added an example.

**Reply by viceice** [reply]
ok, so you are using the shell executor and not the docker executor and you like to use the renovate docker sidecars?

Maybe something like this works?
```yaml
services:
  init:
    image: renovate/renovate:slim
    command: mkdir -p /tmp/renovate/cache && chown -R 1000 /tmp/renovate
    volumes:
      - data:/tmp/renovate
  docker:
    image: docker:20.10.8-dind
    privileged: true # need for docker children, maybe rootless dind works too
    environment:
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: /certs
      DOCKER_CERT_PATH: /certs/client
    volumes:
      - certs:/certs/client
      - data:/tmp/renovate
  renovate:
    image: renovate/renovate:slim
    depends_on:
      - "init"
      - "docker"
    environment:
      SSH_AUTH_SOCK: /tmp/renovate/cache/.ssh-agent/proxy-socket
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
      # ...
    volumes:
      - certs:/certs/client
      - data:/tmp/renovate
      - ssh-agent:/tmp/renovate/cache/.ssh-agent

volumes:
  ssh-agent:
    external: true
  data:
  certs:
```

**Reply by mbrodala** [reply]
> ok, so you are using the shell executor and not the docker executor and you like to use the renovate docker sidecars?

No, for Renovate we have set up additional Docker executors actually. These are used exclusively by Renovate, all other pipelines run on Shell executors since all use Docker Compose.

Do you think this could also be achieved using the default DinD setup?

**Reply by viceice** [reply]
yes, but seems pretty complicated. 🤔 because the socket file needs to be in renovate cache folder to be shared to all sidecar container

**Reply by mbrodala** [reply]
OK, thanks for the confirmation. I'll see if I can manage to implement it like this.

**Reply by viceice** [reply]
can you try something like this:

```yaml
include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate-dind.gitlab-ci.yml'
    ref: v4.4.2 # check latest at https://gitlab.com/renovate-bot/renovate-runner/-/releases

variables:
  RENOVATE_CUSTOM_ENV_VARIABLES: '{"SSH_AUTH_SOCK":"$RENOVATE_BASE_DIR/cache/ssh.sock"}'

before_script:
  - mkdir -p $RENOVATE_BASE_DIR/cache
  - ln -s $SSH_AUTH_SOCK $RENOVATE_BASE_DIR/cache/ssh.sock 
```
