### DISCUSSION TITLE
Helmsman Support

### DISCUSSION THREAD

**Discussion by ekhaydarov** [renovatebot/renovate#11844] [Suggest an Idea]
When browsing initially I saw the availability of all these managers helm-requirements, helm-values, helmfile, helmv3 and just assumed that one of them would take care of [helmsman](https://github.com/Praqma/helmsman). Unfortunately helmsman is a different file structure and only really looking update helm charts rather than docker images. The file itself would be straightforward to parse. 

```yaml
helmRepos:
  ingress-nginx: "https://kubernetes.github.io/ingress-nginx"
  jetstack: "https://charts.jetstack.io"

apps:
  ingress-nginx:
    enabled: true
    chart: ingress-nginx/ingress-nginx
    version: 3.33.0

  cert-manager:
    enabled: true
    chart: jetstack/cert-manager
    version: v1.3.1
```

Would it be possible to add a helmsman manager? 

Thanks
