### DISCUSSION TITLE
Can I also update the version of Terraform on GitHub Actions?

### DISCUSSION THREAD

**Discussion by holidayworking** [renovatebot/renovate#11924] [Request Help] [answered]
Hi, 

I'm validating renovate to update Terraform.

I'm running the terraform plan on GitHub Actions and specifying the terraform version.
```
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.3
```
Is it possible to update the version specified above with the same PR as `.terraform_version` ?

**Comment by viceice** [comment]
Sure,you need a regex manager. Checkout our `renovatebot/.github` repo for samples

**Reply by holidayworking** [reply]
Thank you for your reply.

I have configured the following to use a regex manager.

```json
{
  "extends": [
    "config:base"
  ],
  "regexManagers": [
    {
      "fileMatch": ["^\\.github/workflows/[^/]+\\.ya?ml$"],
      "matchStrings": ["terraform_version: (?<currentValue>.*?)\n"],
      "depNameTemplate": "hashicorp/terraform",
      "datasourceTemplate": "github-releases",
      "versioningTemplate": "hashicorp"
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/11025/135194495-9710f36c-8735-4c44-8bb0-1d3d7390230d.png)

I was able to update it, but now the version is prefixed with `v`. How do I delete v ?

**Reply by viceice** [reply]
https://docs.renovatebot.com/configuration-options/#extractversiontemplate

https://docs.renovatebot.com/configuration-options/#extractversion

**Comment by ericbsantana** [comment]
For anyone that is looking for a quick solution, if your Github Actions has this format:

```yaml
- name: Setup Terraform
  uses: hashicorp/setup-terraform@v3
  with:
    terraform_version: "1.10.1"
```

You can use the following `customManagers` field on your Renovate config file:

```json
 "customManagers": [
    {
      "customType": "regex",
      "depNameTemplate": "hashicorp/terraform",
      "datasourceTemplate": "github-releases",
      "versioningTemplate": "hashicorp",
      "managerFilePatterns": [
        ".github/workflows/*.yml",
      ],
      "extractVersionTemplate": "^v(?<version>.*)$",
      "matchStrings": [
        "terraform_version: \"(?<currentValue>.*)\""
      ]
    }
  ],
 ```

This is the updated version of the snippet presented [here](https://github.com/renovatebot/renovate/discussions/11924#discussioncomment-1399756).
