### DISCUSSION TITLE
PR limit per package group / package.json?

### DISCUSSION THREAD

**Discussion by gustaff-weldon** [renovatebot/renovate#11969] [Request Help]
I'm migrating a few of our monorepo projects from dependabot to renovate.
We are currently using pr limiting per subproject:

```
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: bundler
    directory: /api-docs
    open-pull-requests-limit: 3
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /apollo-service-push
    open-pull-requests-limit: 3
    schedule:
      interval: weekly
      day: monday
```

I would like to recreate such a setup, eg. make sure only 3 PRs are open per subdirectory with `package.json` and all projects will be checked and PRs for them created.

`prConcurrentLimit`  seem to be repository level only, and it does not really ensure I will get a PR for each subproject. When I set this up originally, I got swamped with PRs for only one project. 

If I cannot ensure limits eg. per `packageRule`, can I at least ensure that each project is treated equally?  I checked the code and hoped `prPriority` might help, but it does not really ensure all priority 1 prs will not come from one project...

Any suggestions are welcome, I can share the config I have so far if that helps.
