### DISCUSSION TITLE
How to get release notes?

### DISCUSSION THREAD

**Discussion by micah** [renovatebot/renovate#12195] [Request Help] [answered]
I've configured renovate in gitlab to run on a schedule in gitlab's CI in a project I call 'renovate-cron'. That project simply has a `.gitlab-ci.yml` which pulls the renovate image and then runs it:

```
stages:
  - cron

services:
  - docker:20.10.9-dind

variables:
  RENOVATE_CONFIG_FILE: $CI_PROJECT_DIR/config.js
  RENOVATE_BASE_DIR: /cache/renovate
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_CLI_EXPERIMENTAL: enabled

before_script:
  - mkdir -p $RENOVATE_BASE_DIR

cron:
  stage: cron
  resource_group: production
  image: renovate/renovate:28.1.3-slim
  script:
    - ls -al
    - renovate
  only:
    - schedule
```

 I've configured renovate to run against this project, so I get merge requests telling me that there is a new release of the renovate docker image, this is very helpful to stay up to date! However, I don't know what changed between 28.1.3 and 28.1.4, so it would be helpful if I could get the changes in the MR. Is there a way to do that?

This is what I'm using for the renovate.json for this project:
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base",
    ":disableDependencyDashboard"
  ]
}
```

and the config.js for renovate is fairly simple:

```
module.exports = {
  endpoint: 'https://code.example.org/api/v4/',
  platform: 'gitlab',
  logLevel: 'debug',
  onboardingConfig: {
    extends: ['config:base', ':disableDependencyDashboard'],
  },
  repositories: [
      'software/renovate-cron',
  ],
};
```
