### DISCUSSION TITLE
Unable to add authentication for nuget host

### DISCUSSION THREAD

**Discussion by CorruptComputer** [renovatebot/renovate#12521] [Request Help] [answered]
Using Renovate NPM package (version 29.1.0) to run in a Azure DevOps pipeline. 
Azure DevOps is hosted on-prem and using a Windows Server as its pipeline agent, we do not have Docker available to run.
Need to authenticate to a locally hosted nuget repo, but running into a ton of issues doing so.

I have tried all of the following:

---

Passing in through the command line:
```yaml
trigger: none

pool: [Removed]

steps:
  - task: UseNode@1
    inputs:
      version: '14.x'
      checkLatest: true
  - powershell: |
      npm install -g renovate;

      # Setup Authentication
      $NugetAuth = @(
          @{
              hostType = "nuget"
              matchHost = "[Removed]"
              username = "$(NugetUsername)"
              password = "$(NugetPassword)"
          } 
      );
      $NugetAuthJson = ConvertTo-Json -InputObject $NugetAuth;
      
      # Finally run Renovate
      renovate `
        --platform=azure `
        --endpoint=[Removed] `
        --token=$env:TOKEN `
        --host-rules $NugetAuthJson `
        [Removed];
    env:
      TOKEN: $(AccessToken)
      DEBUG: true
      LOG_LEVEL: debug
```

Renovate is not able to properly parse the json passed in:
```
DEBUG: CLI config
       "config": {
         "repositories": ["[Removed]"],
         "platform": "azure",
         "endpoint": "[Removed]",
         "token": "***********",
         "hostRules": [
           "[\r\n    {\r\n        username:  [Removed]",
           "hostType:  nuget",
           "password:  [Removed]",
           "matchHost:  [Removed]\r\n    }\r\n]"
         ]
       }
```

The json returned by `ConvertTo-Json` is in the following format:
```json
[
    {
        "username":  "[Removed]",
        "hostType":  "nuget",
        "password":  "[Removed]",
        "matchHost":  "[Removed]"
    }
]
```

There is no documentation available on the command line usage, other than the `renovate --help` which is extremely unhelpful and only gives this info:
```
  --host-rules <array>                                Host rules/configuration including credentials.
```
---

Passing in through the environment variables:
```yaml
trigger: none

pool: [Removed]

steps:
  - task: UseNode@1
    inputs:
      version: '14.x'
      checkLatest: true
  - powershell: |
      npm install -g renovate;

      # Finally run Renovate
      renovate `
        --platform=azure `
        --endpoint=[Removed] `
        --token=$env:TOKEN `
        [Removed];
    env:
      TOKEN: $(AccessToken)
      NUGET_[Removed]_USERNAME: $(NugetUsername)
      NUGET_[Removed]_PASSWORD: $(NugetPassword)
      DEBUG: true
      LOG_LEVEL: debug
```

Renovate does not even read the environment variables:
```
DEBUG: Env config
       "config": {"hostRules": []}
```

Setup using this documentation:
https://docs.renovatebot.com/getting-started/private-packages/#hostrules-configuration-using-environment-variables

---

Adding the info in renovate.json for the repo:
```json
{
	"$schema": "https://docs.renovatebot.com/renovate-schema.json",
	"extends": [
		"config:base",
		":rebaseStalePrs",
		":prImmediately",
		":prHourlyLimitNone",
		":prConcurrentLimitNone",
		":automergeDisabled",
		":disableDependencyDashboard"
	],
	"baseBranches": [ "master" ],
	"enabledManagers": [ "nuget" ],
	"separateMajorMinor": false,
	"hostRules": [
		{
			"matchHost": "nuget.org",
			"enabled": false
		},
		{
			"hostType":  "nuget",
			"matchHost":  "[Removed]",
			"username":  "[Removed]",
			"password":  "[Removed]"
			
		}
	],
	"nuget": {
            "registryUrls": [
                "https://[Removed]"
            ]
	}
}
```

This works, however our InfoSec team would never approve of this and as far as I can tell there is no way to tell this to read an environment variable. 

Setup using this documentation: 
https://docs.renovatebot.com/configuration-options/#hostrules

---

Could someone help me figure out why this is not working? 
I have been trying for over a week to get this setup, and the documentation for doing so is extremely unhelpful.
