### DISCUSSION TITLE
Self-hosted Azure pipeline for multiple repos and Github token

### DISCUSSION THREAD

**Discussion by ggravlingen** [renovatebot/renovate#12539] [Request Help] [answered]
Hi,

I'm getting the error below when running a pipeline self-hosted on Azure Devops, even though I have configured a Github token with read-only access to public information and passed this token to my pipeline.

I had a look at the source code and it looks like the error below is thrown when the `token` variable does not exist for Github. I read somewhere that the existence of `GITHUB_COM_TOKEN` adds a configuration line to match the host `github.com`. Nethertheless, I've tried adding the host-matching lines manually to my config to no avail.

It would be appreciated it someone could point me in the right direction here where I'm going wrong?

```
FATAL: You must configure a GitHub personal access token
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "logContext": "OwW0HDdUb",
           "msg": "You must configure a GitHub personal access token"
         }
       ]
```

--- Further details ---

I have installed the `Renovate Me` extension from Azure Marketplace. My pipeline looks like this and the Github token is fetched from a Azure pipeline library:
```
trigger: none # Disable CI trigger

schedules:
  - cron: "0 1 * * *" # daily at 1am UTC
    always: true # run even when there are no code changes
    batch: true
    displayName: Daily
    branches:
      include:
        - dev

variables:
  - group: Renovate

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: self
  - checkout: git://Python/my-little-repo
    fetchDepth: 1

  - bash: |
      git config --global user.email 'renovatebot@host.com'
      git config --global user.name 'Renovate Bot'
      npx renovate
    env:
      TOKEN: $(System.AccessToken)
      GITHUB_COM_TOKEN: $(GIT_PAT)
    displayName: "Run Renovate"

```

And I also have a `package.json` sitting in the root of my repo:
```
{
    "renovate": {
        "platform": "azure",
        "endpoint": "https://dev.azure.com/MyOrg/",
        "labels": [
            "upgrade",
            "bot"
        ]
    },
    "repositories": [
        "Python/my-little-repo"
    ],
    "printConfig": true
}
```

There's also a `renovate.json` sitting in the root of my repo:
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json"
}
```

**Comment by rarkins** [comment, marked as answer]
You need to set `RENOVATE_PLATFORM=azure`. It defaults to `github`

**Reply by ggravlingen** [reply]
Thank you! For anyone else having the same issue, I also had to set `RENOVATE_ENDPOINT` and `RENOVATE_TOKEN` for the step to run.

```
  - bash: |
      git config --global user.email 'renovatebot@host.com'
      git config --global user.name 'Renovate Bot'
      npx renovate
    env:
      RENOVATE_PLATFORM: "azure"
      RENOVATE_ENDPOINT: "https://dev.azure.com/MyOrg/"
      RENOVATE_TOKEN: $(System.AccessToken)
      GITHUB_COM_TOKEN: $(GIT_PAT)
    displayName: "Run Renovate"

```
