### DISCUSSION TITLE
Create new repo for pre-commit-hook

### DISCUSSION THREAD

**Discussion by killermoehre** [renovatebot/renovate#12823] [Suggest an Idea]
Hi,

as https://github.com/renovatebot/renovate/pull/12811 won't work, I suggest a new repository `renovatebot/pre-commit` with the following content:

`.pre-commit-hooks.yaml`
```yaml
---
- id: renovate-config-validator
  name: renovate-config-validator
  description: "renovatebot: Universal dependency update tool that fits into your workflows."
  entry: renovate-config-validator
  language: node
  files: ^((\.git(hub|lab)/)?renovate\.json5?|\.renovaterc(\.json)?)
```

and a `package.json` just installing `renovate`. Probably after setting up this repository won't be touched in the future at all.
