### DISCUSSION TITLE
Rate limit rebaseStalePrs

### DISCUSSION THREAD

**Discussion by philippe-granet** [renovatebot/renovate#12898] [Suggest an Idea]
**What would you like Renovate to be able to do?**
Have a new parameter `rebaseStalePrsHourlyLimit` : 
Rate limit Rebase stale PRs to maximum x rebased per hour. 0 (default) means no limit.

**Comment by rarkins** [comment]
We can hopefully work out an elegant way to do this, but it needs some digging into the code and how we'd achieve it.

**Comment by avdland** [comment]
This would great for reducing the amount of concurrent builds in Jenkins whenever the merge requests need to be rebased.

**Comment by rarkins** [comment]
The amount of rebasing of stale PRs is directly tied to the number of open PRs. Why not reduce concurrent PRs further?

Also, I assume that you're really just wanting to limit how many commits you have, because every commit triggers a job? It's not necessarily about staleness alone?

**Comment by jjonescz** [comment]
Imagine you have 10 PRs created over time, with e.g., 1 hour between each PR created, so CI builds run in sequence, no pressure there. Then you merge one PR, the other 9 are rebased immediately and now all 9 CI builds run in parallel. That's my use-case.

Sure, there are solutions to this (disabling automatic rebase and triggering it manually; or limiting open PRs and manually selecting them in Dependency Dashboard), but option `rebaseStalePrsHourlyLimit` doesn't require manual input. For example, I could trigger "auto merge" on some of the open PRs, then forget about them and let Renovate + CI do their job without having many concurrent CI jobs (which create unnecessary pressure on the CI host).

**Comment by rarkins** [comment]
I had in mind the existing solution of `prConcurrentLimit`. 

Why have e.g. 10 concurrently open PRs in the first place and not e.g. 3? What good is a stale PR (i.e. stale because of this new feature blocking rebasing) compared to it simply being in the queue to be created once one of the three open ones are merged or closed? This approach also doesn't require manual input.

**Comment by philippe-granet** [comment]
> Imagine you have 10 PRs created over time, with e.g., 1 hour between each PR created, so CI builds run in sequence, no pressure there. Then you merge one PR, the other 9 are rebased immediately and now all 9 CI builds run in parallel. That's my use-case.

At work, we have the same problem, but with Gitlab-CI.  
To reduce pressure on our Gitlab runners, I have do that:
* launch renovate bot only at night, when developers sleep
* use tags (https://docs.gitlab.com/ee/ci/yaml/#tags) to launch jobs on branches `renovate/*` only on specific runners with limited concurrent build:
```yaml
variables:
  RENOVATE_TAG: ""

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^renovate\//
      variables:
        RENOVATE_TAG: "renovate"

build:
  tags:
    - tag-for-maven-jobs
    - $RENOVATE_TAG
  script: maven deploy ....
```
So build launched by renovate bot only execute on runners with tags `tag-for-maven-jobs` and `renovate`.

I think you can do similar thing with Jenkins using a specific agent with a low number of executors on that Jenkins agent, and build `renovate/*` branches only on that Jenkins agent.

But a `rebaseStalePrsHourlyLimit` option would be great :smile:

**Comment by rarkins** [comment]
I've converted this from a feature request issue to a discussion idea now because in reality Renovate cannot accurately measure rebases in an hour without maintaining external state, which we don't plan, therefore this feature cannot be implemented as described. I was hoping to explore an alternative way to solve the true *requirement* but it did not seem to satisfy anyone involved.

**Comment by philippe-granet** [comment]
rebased stale PR are included in `prCommitsPerRunLimit` ?
If not, a limit per Renovate run `rebaseStalePrsPerRunLimit` could be helpfull

**Reply by rarkins** [reply]
Yes, any type of commit is included

**Comment by philippe-granet** [comment]
I have found an other way to reduce pressure on our Gitlab runners.  
I limit concurrent jobs execution with `Resource group` Gitlab functionnality (https://docs.gitlab.com/ee/ci/resource_groups/)  

Example:
```yaml
workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /renovate\//
      variables:
        RESOURCE_GROUP: Renovate pipeline
    - when: always

job-1:
  stage: build
  resource_group: $RESOURCE_GROUP
  ...

job-2:
  stage: build
  resource_group: $RESOURCE_GROUP
```
If pipeline is launch on `main` branch, variable `RESOURCE_GROUP` is empty, `job-1` and `job-2` are executed in parallel, and if `n` pipelines are launched, I have `n * 2` jobs executed in parallel.  

If pipeline is launch on a `renovate/*` branch by the Renovate bot, variable `RESOURCE_GROUP` is equals to `Renovate pipeline`, `job-1` and `job-2` are not executed in parallel, they are executed once at a time, and if `n` pipelines are launched by the Renovate bot, I always have only 1 job once at a time on my project, less pressure on Gitlab runners 😄
