### DISCUSSION TITLE
Support for private Buildkite plugins

### DISCUSSION THREAD

**Discussion by jhpierce** [renovatebot/renovate#12984] [Suggest an Idea]
We would like to use Renovate to keep our Buildkite plugins (hosted on Github Enterprise) up to date. However, Renovate cannot parse the versions from our pipeline files. A sample pipeline file might look like:

```yaml
- label: "Linting"
  plugins:
    - ssh://git@github.our-domain.com/secure/some-buildkite-plugin#v5.0.2:
        some_parameter: "some value"
```

Renovate would throw this error:

```
WARN: Something is wrong with buildkite plugin name (repository=some-org/some-repository, dependency=ssh://git@github.our-domain.com/some-org/some-buildkite-plugin)
```

I'm wondering whether this would be something that we could contribute to, or whether there is a reason this has not been built already. It seems like the datasource for Buildkite is simply Github tags, which is how we manage plugins in our org. Could it be as simple as updating the regex?
