### DISCUSSION TITLE
Updating the services component of a GitHub action

### DISCUSSION THREAD

**Discussion by paulzakin** [renovatebot/renovate#13019] [Request Help] [answered]
So, after reading the documentation and experimenting a fair amount, I cannot quite figure out to use Renovate to update the [services section](https://docs.github.com/en/actions/using-containerized-services/about-service-containers) of a GitHub action.

For example, if I have this GitHub action

```yml
services:
      postgres:
        image: postgres:13.5
        env:
          POSTGRES_DB: db
          ...
```

I tried this in my renovate.json

```json
 "regexManagers": [
    {
      "fileMatch": ["^(\\.github\\/workflows)\\/[^/]+\\.ya?ml$"],
      "matchStrings": ["image:\\s+(?<depName>):(?<currentValue>[^\\s]+)"],
      "autoReplaceStringTemplate": "image: {{{depName}}}:{{{newValue}}}",
      "datasourceTemplate": "docker"
    }
  ]
```

And while I get that Renovate successfully matches the file (pull_request.yml) it isn't bumping up the image. 

Any help would be greatly appreciated!
