### DISCUSSION TITLE
registryUrls don't work for packagist/composer manager

### DISCUSSION THREAD

**Discussion by event15** [renovatebot/renovate#13134] [Request Help] [answered]
Is a related with https://github.com/renovatebot/config-help/issues/812

I have a `composer.json` file on self-hosted gitlab instance:
```json
{
  "description": "Renovate test project",
  "name": "event15/renovate-test",
  "authors": [
    {
      "name": "Developers project",
      "email": "developer@[*****].pl"
    }
  ],
  "repositories": [
    {
      "type": "composer",
      "url": "https://nexus-rm.[****].pl/repository/composer"
    },
    {
      "name": "[****]/mvc",
      "type": "vcs",
      "url": "https://[****]:[****]@git.[****].pl/[****]/libraries/mvc.git"
    }
  ],
  "require": {
    "[****]/mvc": "~1.0.10",
    "libraries/kibanaapmclient": "~2.0.0", // from nexus 
  }
}
```

I created a `renovate.json` in project with this `composer.json` file:
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "local>config:base"
  ],
  "packageRules": [
    {
      "datasources": ["packagist"],
      "registryUrls": [
        "https://nexus-rm.[****].pl/repository/composer/"
      ]
    },
    {
      "datasources": ["packagist"],
      "updateTypes": ["major"],
      "enabled": false
    }
  ]
}
```

I try also in `renovate.json` configure `hostRules`:
```json
"hostRules": [
    {
      "matchHost": "https://nexus-rm.[****].pl/repository/composer/"
    }
  ]
```

I have a project with renovate-bot configured by `gitlab-ci.yml`:
```yml
variables:
  RENOVATE_BASE_DIR: $CI_PROJECT_DIR/renovate
  RENOVATE_ENDPOINT: $CI_API_V4_URL
  RENOVATE_PLATFORM: 'gitlab'
  RENOVATE_GIT_AUTHOR: 'renovate-bot <renovate-bot@[****].pl>'
  RENOVATE_ONBOARDING_CONFIG: '{"$$schema": "https://docs.renovatebot.com/renovate-schema.json", "extends": ["config:base"] }'
  RENOVATE_OPTIMIZE_FOR_DISABLED: 'true'
  RENOVATE_DISABLE_FILE_RECURSION: 'true'
  RENOVATE_REPOSITORY_CACHE: 'false'
  RENOVATE_REQUIRE_CONFIG: 'true'
  RENOVATE_ONBOARDING: 'true'
  RENOVATE_IGNORE_PR_AUTHOR: 'true'
  RENOVATE_LOG_FILE: 'renovate-log.ndjson'
  RENOVATE_LOG_FILE_LEVEL: 'debug'
  RENOVATE_CONFIG_FILE: $CI_PROJECT_DIR/config.js
  LOG_LEVEL: 'debug'
  NODE_TLS_REJECT_UNAUTHORIZED: '0'

default:
  cache:
    key: ${CI_COMMIT_REF_SLUG}-renovate
    paths:
      - renovate/cache/renovate/**

renovate:
  stage: deploy
  image: common.dockerhub.[****].pl/operations/renovatebot:28.0.0
  script:
    - renovate $RENOVATE_EXTRA_FLAGS $(cat repositories.txt | xargs)
  only:
    - schedules
    - web
  tags:
    - docker
  artifacts:
    when: always
    expire_in: 1d
    paths:
      - "$RENOVATE_LOG_FILE"
```

My debug from renovate-bot:
```
DEBUG: Matched 1 file(s) for manager composer: composer.json (repository=event15/renovate-test)
DEBUG: Found composer lock file (repository=event15/renovate-test, packageFile=composer.json)
DEBUG: Found composer package files (repository=event15/renovate-test)
DEBUG: Found 1 package file(s) (repository=event15/renovate-test)
 INFO: Dependency extraction complete (repository=event15/renovate-test)
       "baseBranch": "main",
       "stats": {
         "managers": {"composer": {"fileCount": 1, "depCount": 7}},
         "total": {"fileCount": 1, "depCount": 7}
       }
 WARN: Custom registries are not allowed for this datasource and will be ignored (repository=event15/renovate-test)
       "datasource": "git-tags",
       "registryUrls": [
         "https://nexus-rm.[****].pl/repository/composer",
         "https://packagist.org"
       ]
DEBUG: Failed to look up dependency libraries/kibanaapmclient (repository=event15/renovate-test, packageFile=composer.json, dependency=libraries/kibanaapmclient)

(...)

DEBUG: http statistics (repository=event15/renovate-test)
       "urls": {
         "https://git.[****].pl/api/v4/projects/event15%2Frenovate-test (GET)": 1,
         "https://git.[****].pl/api/v4/projects/event15%2Frenovate-test/issues (GET)": 1,
         "https://git.[****].pl/api/v4/projects/event15%2Frenovate-test/issues/1 (GET)": 2,
         "https://git.[****].pl/api/v4/projects/event15%2Frenovate-test/issues/1 (PUT)": 1,
         "https://git.[****].pl/api/v4/projects/event15%2Frenovate-test/merge_requests (GET)": 1,
         "https://git.[****].pl/api/v4/projects/event15%2Frenovate-test/repository/files/renovate.json (GET)": 1,
         "https://nexus-rm.[****].pl/repository/composer/packages.json (GET)": 1
       },
       "hostStats": {
         "git.[****].pl": {"requestCount": 7, "requestAvgMs": 136, "queueAvgMs": 0},
         "nexus-rm.[****].pl": {
           "requestCount": 1,
           "requestAvgMs": 62,
           "queueAvgMs": 2
         }
       },
       "totalRequests": 8
```

Recommendations and ideas are welcome
