### DISCUSSION TITLE
ERROR: Datasource getReleases without lookupName

### DISCUSSION THREAD

**Discussion by hongbo-miao** [renovatebot/renovate#13413] [Request Help] [answered]
I recently got this error in my [Dependency Dashboard](https://github.com/Hongbo-Miao/hongbomiao.com/issues/3259):

> ## Repository problems
> 
> These problems occurred while renovating this repository.
> 
>  - ERROR: Datasource getReleases without lookupName

Just wonder what does this error mean and how can I fix it? Thanks! 😃

**Comment by rarkins** [comment, marked as answer]
Can you log into app.renovatebot.com and check the logs for this message?

**Reply by schuch** [reply]
Its a kind of wild guess, but i encountered the same error when renovating a repository containing a rasa helm chart.

In my case a very similar line to

https://github.com/Hongbo-Miao/hongbomiao.com/blob/main/kubernetes/config/rasa/rasa/values.yaml#L218

is contained in my repo:

--> values.yaml:
```
## Define the rasa image to work with
image:
  # -- Rasa Open Source image name to use (relative to `registry`)
  name: rasa

  # -- Rasa Open Source image tag to use
  tag: "2.8.11"
  # -- Override default registry + image.name for Rasa Open Source
  repository: ""
```

This gets resolved as 

```
"deps": [
           {
             "depName": "",
             "currentValue": "2.8.11",
             "datasource": "docker",
             "replaceString": "2.8.11",
             "versioning": "docker",
             "autoReplaceStringTemplate": "{{newValue}}{{#if newDigest}}@{{newDigest}}{{/if}}",
             "depIndex": 0
           }
         ],
```

I suspect `"depName": ""` might cause the error (at least the version printed in the TRACE line before the ERROR matches the mentioned section in the `values.yaml`:

```
TRACE: lookupUpdates (repository=...)
       "currentValue": "2.8.11"
ERROR: Datasource getReleases without lookupName (repository=...)
```

According to https://docs.renovatebot.com/modules/manager/helm-values/ renovate expects the notation

```
image:
  repository: 'some-docker/dependency'
  tag: v1.0.0
  registry: registry.example.com # optional key, will default to "docker.io"
```

not

```
image:
  name: 'some-docker/dependency'
  tag: v1.0.0
  registry: registry.example.com # optional key, will default to "docker.io"
```

Is the expected format a standard or just a best practice found in most charts?
