### DISCUSSION TITLE
how to configure renovate for private vcs composer repository

### DISCUSSION THREAD

**Discussion by yigitcicek** [renovatebot/renovate#13540] [Request Help]
Hi,

First of all, your effort for this project is greatly appreciated by all of my colleagues.

Here is my question:
Could you guide me on how to configure and authenticate renovate for our composer repository?

Information:
We are self-hosting renovate at local gitlab with a fork from:
https://gitlab.com/renovate-bot/renovate-runner/
version: 31.18.0
Project has RENOVATE_TOKEN and GITHUB_COM_TOKEN as ci/cd variable from gitlab ui.
Our composer repository is also hosted on same gitlab server as vcs.
We also have private maven and nexus repositorties they are working fine yet.

Files:
gitlab-ci.yaml
```yaml
variables:
  RENOVATE_PLATFORM: gitlab
  RENOVATE_OPTIMIZE_FOR_DISABLED: 'false'
  RENOVATE_REPOSITORY_CACHE: 'false'
  RENOVATE_REQUIRE_CONFIG: 'true'
  RENOVATE_ONBOARDING: 'false'
  RENOVATE_IGNORE_PR_AUTHOR: 'true'
  RENOVATE_LOG_FILE: renovate-log.ndjson
  RENOVATE_LOG_FILE_LEVEL: debug
  LOG_LEVEL: debug
  RENOVATE_CONFIG_FILE: $CI_PROJECT_DIR/config.js

include:
  - project: 'group/renovate-runner'
    file: '/templates/renovate-dind.gitlab-ci.yml'
    ref: v7.47.0 # check latest at https://gitlab.com/renovate-bot/renovate-runner/-/releases

renovate:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  script:
    - renovate $RENOVATE_EXTRA_FLAGS
```

config.js
```js
module.exports = {
    platform: 'gitlab',
    endpoint: 'https://gitlab.company.com/api/v4/',
    gitLabAutomerge: false,
    onboardingConfig: {
      extends: ['config:base'],
    },
    repositories: [
      'group/project',
    ],
    packageRules: [
      {
        registryUrls: [
          "https://repo.maven.apache.org/maven2",
          "https://maven.company.com/nexus/",
          "https://nexus.company.com/repository",
        ]
      },
      {
        datasources: ["packagist"],
        registryUrls: [
          "https://gitlab.company.com"
        ]
      },
      {
        matchUpdateTypes: ["patch", "pin"],
        automerge: false
      },
    ],
    hostRules: [
      {
        hostType: 'packagist',
        matchHost: 'gitlab.company.com',
        token: process.env.RENOVATE_TOKEN,
      },
    ],
}
```

sample composer file from a project
```json
{
    "name": "group/project",
    "description": "Page",
    "homepage": "https://gitlab.company.com/group/project",
    "type": "project",
    "license": "proprietary",
    "repositories": [
        {
            "type": "vcs",
            "url": "git@gitlab.company.com:test/package-name.git"
        },
    
    ],
    "require": {
        "test/package-name": "^1.0.0"
    }
}
```

I have tried several different things with no success.
If I used datasource registry url as above I got the log as:
```
DEBUG: Datasource 404 (repository=group/project)
       "datasource": "packagist",
       "lookupName": "test/package-name",
       "url": "https://gitlab.company.com/users/sign_in"
```

With datasource I have tried giving it git@gitlab.company.com: instead of http url. Log is:
```
DEBUG: Datasource connection error (repository=group/project)
       "datasource": "packagist",
       "lookupName": "test/package-name",
       "url": undefined,
       "errCode": "ERR_INVALID_URL"
```

I have also tried to workaround with git configs. Adding following line with a before_scipt to the renovate gitlab-ci job:
`- git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.company.com/".insteadOf "git@gitlab.company.com:"`
This didn't seem to change anything at all.

Appreciate your help,
Best,

**Comment by rarkins** [comment]
It's possible that you could use `git config --global url.<new-url>.insteadOf <old-url>` to rewrite the URL to one which uses a token, assuming that composer calls `git`.

**Comment by yigitcicek** [comment]
As soon as I put git@ to the datasource of renovate config I got Invalid Url error.
Is this not supported for private vcs repositories?
My last settings are here:

gitlab-ci.yaml

```yaml
variables:
  RENOVATE_PLATFORM: gitlab
  RENOVATE_OPTIMIZE_FOR_DISABLED: 'false'
  RENOVATE_REPOSITORY_CACHE: 'false'
  RENOVATE_REQUIRE_CONFIG: 'true'
  RENOVATE_ONBOARDING: 'false'
  RENOVATE_IGNORE_PR_AUTHOR: 'true'
  RENOVATE_LOG_FILE: renovate-log.ndjson
  RENOVATE_LOG_FILE_LEVEL: debug
  LOG_LEVEL: debug
  RENOVATE_CONFIG_FILE: $CI_PROJECT_DIR/config.js

include:
  - project: 'group/renovate-runner'
    file: '/templates/renovate-dind.gitlab-ci.yml'
    ref: v7.47.0 # check latest at https://gitlab.com/renovate-bot/renovate-runner/-/releases

renovate:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.company.com/".insteadOf "git@gitlab.company.com:"
    - renovate $RENOVATE_EXTRA_FLAGS
  ```

config.js

```javascript
module.exports = {
    platform: 'gitlab',
    endpoint: 'https://gitlab.company.com/api/v4/',
    gitLabAutomerge: false,
    onboardingConfig: {
      extends: ['config:base'],
    },
    repositories: [
      'group/project',
    ],
    packageRules: [
      {
        registryUrls: [
          "https://repo.maven.apache.org/maven2",
          "https://maven.company.com/nexus/",
          "https://nexus.company.com/repository",
        ]
      },
      {
        datasources: ["packagist"],
        registryUrls: [
          "git@gitlab.company.com"
        ]
      },
      {
        matchUpdateTypes: ["patch", "pin"],
        automerge: false
      },
    ],
    hostRules: [
      {
        hostType: 'packagist',
        matchHost: 'gitlab.company.com',
        token: process.env.RENOVATE_TOKEN,
      },
    ],
}
```

composer of gitlab.company.com/group/project
```json
{
    "name": "group/project",
    "description": "Page",
    "homepage": "https://gitlab.company.com/group/project",
    "type": "project",
    "license": "proprietary",
    "repositories": [
        {
            "type": "vcs",
            "url": "git@gitlab.company.com:test/package-name.git"
        },
    
    ],
    "require": {
        "test/package-name": "^1.0.0"
    }
}
```

Logs:
```
DEBUG: Datasource connection error (repository=group/project)
       "datasource": "packagist",
       "lookupName": "test/package-name",
       "url": undefined,
       "errCode": "ERR_INVALID_URL"
```
