### DISCUSSION TITLE
is using private gitlab repos unsupported in helmfile?

### DISCUSSION THREAD

**Discussion by pspurlock07** [renovatebot/renovate#13629] [Request Help]
Just wanted to make sure I wasn't doing anything wrong. current helmfile.yaml:

```yaml
repositories:
- name: test-app-chart
  url: reg.gitlab.com/testapp/test-app-chart/charts
  oci: true  

releases:
- name: test-app-chart
  namespace: {{ .Values.namespace }}
  chart: test-app-chart/test-app-chart
  version: 4.1.5
  values:
  - values/test-app.yaml.gotmpl
```

This currently gives an error of:

```
DEBUG: Datasource connection error (repository=devsecops/testapp/test-app-env)
       "datasource": "helm",
       "lookupName": "test-app-chart",
       "url": undefined,
       "errCode": "ERR_INVALID_URL"
```
