### DISCUSSION TITLE
How to go directly from 1.1.0 -> 1.6.0

### DISCUSSION THREAD

**Discussion by tennox** [renovatebot/renovate#13693] [Request Help] [answered]
My (awesome) renovate creates PRs for an update, but only goes one version up - once I've merged, it creates the next update PR :see_no_evil: 

Did not find a relevant config option (also don't really know which term to search for)

Is there something like that?

Config:
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base",
    ":automergeMinor"
  ]
}
```

Target: `.gitlab-ci.yml`
```yaml
include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate-dind.gitlab-ci.yml'
    ref: v8.3.0 # this way, renovate can run against itself ;)
```
