### DISCUSSION TITLE
Renovate cache grows continually

### DISCUSSION THREAD

**Discussion by bizrad** [renovatebot/renovate#13730] [Request Help]
We have been running renovate (latest) in GitLab CI. Initially we used the gitlab cache for the cache directory, but then this was taking too long to update and download on each run due to the size. We switched to a gitlab runner with a disk mounted just for renovate. It seems that on each run renovate simply adds to the cache and does no garbage collection. I don't see any options in renovate to control this.

Should this cache not be preserved? 
Is there a cleanup function that can be run?
Are there other settings or best practices we should use?
Or is this an issue?

This directory seems to just continually grow on each run.
```
88.3G   cache/renovate/renovate-cache-v1/content-v2
```

Reasonable sized directories
```
515.3M  cache/renovate/renovate-cache-v1/index-v5
4.0K    cache/renovate/renovate-cache-v1/tmp/
224.0K  cache/renovate/repository/gitlab
845.0M  cache/others/berry
8.0K    cache/others/npm
4.0K    cache/others/pnpm
1.0G    cache/others/yarn
```

Config in GitLab CI
```
renovate:
  stage: static
  image: renovate/renovate
  variables:
    RENOVATE_BASE_DIR: /renovate-runner-pv/renovate
    RENOVATE_ENDPOINT: $CI_API_V4_URL
    RENOVATE_PLATFORM: gitlab
    RENOVATE_GIT_AUTHOR: Renovate Bot <bot@renovateapp.com>
    RENOVATE_ONBOARDING_CONFIG: '{"$$schema": "https://docs.renovatebot.com/renovate-schema.json", "extends": ["config:base"] }'
    RENOVATE_OPTIMIZE_FOR_DISABLED: 'true'
    RENOVATE_REPOSITORY_CACHE: 'true'
    RENOVATE_REQUIRE_CONFIG: 'true'
    RENOVATE_ONBOARDING: 'true'
    RENOVATE_IGNORE_PR_AUTHOR: 'true'
    RENOVATE_EXTENDS: 'github>whitesource/merge-confidence:beta'
    RENOVATE_LOG_FILE: renovate-log.ndjson
    RENOVATE_LOG_FILE_LEVEL: debug
  tags:
    -  renovate-runner-pv # Uses special runner with 100GB PV mounted at /renovate-runner-pv/
  script:
    - renovate  mycompany/myrepo
  artifacts:
    when: always
    expire_in: 1d
    paths:
      - "$RENOVATE_LOG_FILE"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "renovate"
```

renovate.json
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": ["config:base"],
  "enabledManagers": ["dockerfile", "npm", "cargo", "gitlabci"],
  "dependencyDashboard": true,
  "rangeStrategy": "replace",
  "semanticCommits": "enabled",
  "lockFileMaintenance": {
    "enabled": true
  },
  "includePaths": ["src/myapp/**", "ci/myapp*"],
  "gitlabci": {
    "fileMatch": "ci/myapp_(main|common).yml"
  },
  "dockerfile": {
    "fileMatch": [
      "\\.dockerfile$"
    ]
  },
  "packageRules": [
    {
      "matchPackagePatterns": "^@types/",
      "enabled": false
    }
  ],
  "hostRules": [
    {
      "abortOnError": true
    }
  ]
}

```
