### DISCUSSION TITLE
Ideas on how to automatically update a `helm pull` command in Gitlab CI

### DISCUSSION THREAD

**Discussion by mcritchlow** [renovatebot/renovate#13866] [Request Help] [answered]
I'm curious if folks have any idea how I might teach Renovate how to update a Helm chart version that we're deploying in a Gitlab CI pipeline.

The chart is being pulled from `ghcr.io`. So it's being packaged and submitted using OCI.

Here is a link to where this deployment is defined: https://gitlab.com/surfliner/surfliner/-/blob/trunk/ci/comet.yml#L26

An inline:

```yaml
.comet-chart-deploy:
  variables:
	HELM_EXPERIMENTAL_OCI: 1
  script:
	- helm pull oci://ghcr.io/samvera/charts/hyrax --version 1.0.2 --untar --untardir charts
	- deploy ./charts/hyrax
```

So ideally, I'd like to get Renovate to submit a merge request with the
`--version` changed when a new chart version is available in the OCI registry.

This might not be possible, but I figured I could ask. Thanks in advance for any
ideas!
