### DISCUSSION TITLE
Custom Yaml Files

### DISCUSSION THREAD

**Discussion by ahmedfourti** [renovatebot/renovate#13881] [Request Help]
Hello guys,

I starting using Renovate some days ago and find it a very nice tool :pray: 
However I am trying to track Chart Helm version defined in a config yam file like : 

```
applications:
  aws-load-balancer-controller:
    namespace: alb-ingress
    repoURL: https://aws.github.io/eks-charts
    chartName: aws-load-balancer-controller
    chartVersion: 1.3.2
    releaseName: aws-load-balancer-controller
  external-dns:
    namespace: external-dns
    repoURL: https://charts.bitnami.com/bitnami
    chartName: external-dns
    chartVersion: 6.1.2
    releaseName: external-dns
  external-secret:
    namespace: external-secret
    repoURL: https://external-secrets.github.io/kubernetes-external-secrets
    chartName: kubernetes-external-secrets
    chartVersion: 8.5.1
    releaseName: external-secret
```

Is there any way to do it please ?

Thanks
