### DISCUSSION TITLE
Permission issues when npm is being installed in renovate/node sidecar container on Bamboo

### DISCUSSION THREAD

**Discussion by cascornelissen** [renovatebot/renovate#13961] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.65.1

### Please select which platform you are using if self-hosting.

Bitbucket Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

7.20.0

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

We tried adding the following snippet to the Renovate configuration file to ensure NPM lockfiles are generated with the correct version:

```
"constraints": {
    "npm": ">= 8.0.0"
}
```

This seems to correctly kick off the `renovate/node` sidecar container (see logs) which tries to install npm 8 but this fails because of permission issues on `/home/ubuntu/npm` within the sidecar container.

Renovate itself is ran with both the `docker run` `--user` flag and the `RENOVATE_DOCKER_USER` environment variable set to the same value, which maps back to:

```
RENOVATE_DOCKER_USER="$(id -u):$(getent group docker | cut -d ':' -f 3)" // 500:115 (bamboo:docker)
```

This `500:115` user/group then also gets used for the sidecar container (it's passed to the `--user` flag, see logs) but that user does not seem to have permissions to create the `/home/ubuntu/npm` directory to install `npm` in.

I'm not sure how to debug this issue any further, so any help is much appreciated.

### Relevant debug logs

<details><summary>Logs</summary>

```
build	02-Feb-2022 12:03:22	DEBUG: Executing command (repository=namespace/project, branch=renovate/testing-packages)
build	02-Feb-2022 12:03:22	       "command": "docker run --rm --name=renovate_node --label=renovate_child --user=500:115 -v \"/path-to-build-dir/project\":\"/path-to-build-dir/project\" -v \"/path-to-build-dir-dir npm_config_store -w \"/path-to-build-dir/project\" docker-registry.**redacted**/renovate/node bash -l -c \"install-tool npm 8.4.0 && hash -d npm 2>/dev/null || true && npm install --package-lock-only --no-audit --ignore-scripts\""
build	02-Feb-2022 12:03:29	DEBUG: exec completed (repository=namespace/project, branch=renovate/testing-packages)
build	02-Feb-2022 12:03:29	       "cmd": "docker run --rm --name=renovate_node --label=renovate_child --user=500:115 -v \"/path-to-build-dir/project\":\"/path-to-build-dir/project\" -v \"/path-to-build-dir-dir npm_config_store -w \"/path-to-build-dir/project\" docker-registry.**redacted**/renovate/node bash -l -c \"install-tool npm 8.4.0 && hash -d npm 2>/dev/null || true && npm install --package-lock-only --no-audit --ignore-scripts\"",
build	02-Feb-2022 12:03:29	       "durationMs": 7252,
build	02-Feb-2022 12:03:29	       "stdout": "Installing tool npm v8.4.0\nadded 476 packages in 5.918s\n",
build	02-Feb-2022 12:03:29	       "stderr": "mkdir: cannot create directory ‘/home/ubuntu/npm’: Permission denied\nnpm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.3.2 (node_modules/jest-haste-map/node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {\"os\":\"darwin\",\"arch\":\"any\"} (current: {\"os\":\"linux\",\"arch\":\"x64\"})\nnpm WARN project@2.1.0 No license field.\n\n\n┌──────────────────────────────────────────────────────────┐\n│                 npm update check failed                  │\n│           Try running with sudo or get access            │\n│           to the local update config store via           │\n│ sudo chown -R $USER:$(id -gn $USER) /home/ubuntu/.config │\n└──────────────────────────────────────────────────────────┘\n"
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment, marked as answer]
Groupid needs to be 0, i also think you don't need to override the user if both Are running in containers

**Reply by viceice** [reply]
`RENOVATE_DOCKER_USER=500:0`

**Reply by cascornelissen** [reply]
Wow, I should've posted a question earlier... That does indeed seem to solve the issue. I inherited our Renovate setup so don't know the ins and outs on why this was set up in this way. Is there any documentation that I can read through, especially anything on why group ID needs to be `0`.

**Reply by viceice** [reply]
There is no renovate documentsation, but we use some common linux stuff.
A user can only write to it's own home dir, but you override it, so your user has no home and we implicit redirect it to our user (1000).
To make other userid working, you need to override the default group, because we made the home dir writable by root group.

So you should do this:
```sh
> export RENOVATE_DOCKER_USER="$(id -u):0" # 500:0 (bamboo:root)
```

@rarkins @HonkingGoose Maybe we should extend the docs to include the root group requirements for `binarySource=docker|install` ?

**Reply by rarkins** [reply]
Maybe as part of the existing `dockerUser` documentation?

**Reply by cascornelissen** [reply]
Thanks for the additional information, I understand it now. Adding this to the docs would make sense to me but I'll leave that up to you guys ❤️

**Reply by viceice** [reply]
> Maybe as part of the existing `dockerUser` documentation?

Sounds good to me

**Reply by HonkingGoose** [reply]
PR https://github.com/renovatebot/renovate/pull/14086 will add this to the documentation.

**Reply by MalteMagnussen** [reply]
@viceice - Does it **have** to be group 0?

I am trying to run Renovate Bot as a CronJob in our Kubernetes cluster, but it seems Kyverno policies are getting in the way.

`"validate.kyverno.svc-ignore" denied the request: resource CronJob/systems-renovate/renovate-bot-1 was blocked due to the following policies require-non-root-groups: autogen-cronjob-check-fsgroup: 'validation error: Containers cannot run with a root primary or supplementary GID. The field spec.securityContext.fsGroup must be unset or set to a value greater than zero.`

```
one or more objects failed to apply, reason: admission webhook "validate.kyverno.svc-ignore" denied the request: resource CronJob/systems-renovate/renovate-bot-1 was blocked due to the following policies require-non-root-groups: autogen-cronjob-check-fsgroup: 'validation error: Containers cannot run with a root primary or supplementary GID. The field spec.securityContext.fsGroup must be unset or set to a value greater than zero. rule autogen-cronjob-check-fsgroup failed at path /spec/jobTemplate/spec/template/spec/securityContext/fsGroup/',admission webhook "validate.kyverno.svc-ignore" denied the request: resource CronJob/systems-renovate/renovate-bot-2 was blocked due to the following policies require-non-root-groups: autogen-cronjob-check-fsgroup: 'validation error: Containers cannot run with a root primary or supplementary GID. The field spec.securityContext.fsGroup must be unset or set to a value greater than zero. rule autogen-cronjob-check-fsgroup failed at path /spec/jobTemplate/spec/template/spec/securityContext/fsGroup/',admission webhook "validate.kyverno.svc-ignore" denied the request: resource CronJob/systems-renovate/renovate-bot-3 was blocked due to the following policies require-non-root-groups: autogen-cronjob-check-fsgroup: 'validation error: Containers cannot run with a root primary or supplementary GID. The field spec.securityContext.fsGroup must be unset or set to a value greater than zero. rule autogen-cronjob-check-fsgroup failed at path /spec/jobTemplate/spec/template/spec/securityContext/fsGroup/',admission webhook "validate.kyverno.svc-ignore" denied the request: resource CronJob/systems-renovate/renovate-bot-0 was blocked due to the following policies require-non-root-groups: autogen-cronjob-check-fsgroup: 'validation error: Containers cannot run with a root primary or supplementary GID. The field spec.securityContext.fsGroup must be unset or set to a value greater than zero. rule autogen-cronjob-check-fsgroup failed at path /spec/jobTemplate/spec/template/spec/securityContext/fsGroup/'. Retrying attempt #5 at 3:47PM.
```

Here is the Desired Manifest:

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    private/instance: systems-renovate
  name: renovate-bot-2
  namespace: systems-renovate
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          containers:
            - env:
                - name: LOG_LEVEL
                  value: DEBUG
                - name: RENOVATE_DRY_RUN
                  value: ''
                - name: RENOVATE_AUTODISCOVER
                  value: 'false'
                - name: RENOVATE_DOCKER_USER
                  value: '1000:0'
                - name: RENOVATE_PLATFORM
                  value: gitlab
                - name: RENOVATE_ENDPOINT
                  value: 'https://private/api/v4/'
                - name: RENOVATE_GIT_AUTHOR
                  value: RenovateBot <noreply+renovate-bot@private>
                - name: RENOVATE_REPOSITORIES
                  value: >-
                    ["foo","baz","boof","bak","bar"]
                - name: RENOVATE_DETECT_HOST_RULES_FROM_ENV
                  value: 'true'
                - name: GOPRIVATE
                  value: private-gitlab
                - name: DOCKER_GITLAB_ONE_COM_USERNAME
                  value: renovate-bot
              envFrom:
                - secretRef:
                    name: renovate-env
              image: 'private-mirror/docker.io/renovate/renovate:latest'
              name: renovate-bot
              resources:
                limits:
                  cpu: '2'
                  memory: 2000Mi
                requests:
                  cpu: '1'
                  memory: 1000Mi
          restartPolicy: Never
          securityContext:
            runAsGroup: 0
            runAsUser: 1000
  schedule: '@hourly'
``` 

If I run 1000:1000 I see errors like

`rm: cannot remove '/opt/containerbase/env.d/node.sh': Permission denied` 

or something similar with mkdir in `/opt/containerbase`
