### DISCUSSION TITLE
How to implement renovatebot self hosted on a gitea instance?

### DISCUSSION THREAD

**Discussion by OCram85** [renovatebot/renovate#14246] [Request Help]
Hello renovatebot community,
I'm fairly new to renovate and ty to use it in a self hosted scenario.

I'm running basically gitea + drone.io in a docker swarm environment. Are there any example configurations I could start with? - To be honest - I'm overwhelmed by the  the [self-hosted config](https://docs.renovatebot.com/examples/self-hosting/)

**Comment by viceice** [comment]
My drone ci pipeline
```yaml
---
kind: pipeline
type: docker
name: renovate

node:
  renovate: 'true'

concurrency:
  limit: 1

trigger:
  event:
    - cron
    - push
    - custom

environment:
  LOG_LEVEL: debug

steps:
  - name: test
    image: ghcr.io/visualon/renovate:31.70.0@sha256:593964d569b08476c8af5ef4b1a0c5382f4c5ef6b8a6a839593d4240a8dec8bf
    commands:
      - unset GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL
      - renovate-config-validator

  - name: renovate
    image: ghcr.io/visualon/renovate:31.70.0@sha256:593964d569b08476c8af5ef4b1a0c5382f4c5ef6b8a6a839593d4240a8dec8bf
    commands:
      # - echo "$BOT_PSW" | docker login harbor.domain.test -u bot --password-stdin
      - unset GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL
      - renovate
    volumes:
      - name: tmp
        path: /tmp
      - name: dockersock
        path: /var/run/docker.sock

    environment:
      SVC_CI_PSW:
        from_secret: SVC_CI_PSW
      # BOT_PSW:
      #   from_secret: BOT_PSW
      RENOVATE_TOKEN:
        from_secret: RENOVATE_TOKEN
      GITHUB_COM_TOKEN:
        from_secret: GITHUB_COM_TOKEN
      NPM_TOK:
        from_secret: NPM_TOKEN
      GPG_KEY:
        from_secret: GPG_KEY

volumes:
  - name: tmp
    host:
      path: /tmp
  - name: dockersock
    host:
      path: /var/run/docker.sock
```

My partial renovate config
```js
const cfg = require('./src/config');

const dryRun = process.env.CI && process.env.DRONE_BRANCH != process.env.DRONE_REPO_BRANCH;

const autodiscoverFilter = dryRun ? 'test/*' : '!test/*';

module.exports = {
  ...cfg,

  endpoint: 'https://gitea.domain.test/api/v1/',
  platform: 'gitea',
  autodiscover: true,
  autodiscoverFilter,

  dryRun,

  hostRules: [
    ...cfg.hostRules,
    {
      hostType: 'npm',
      matchHost: 'https://verdaccio.domain.test/',
      token: process.env.NPM_TOK,
    },
    {
      matchHost: 'https://proget.domain.test/',
      username: 'svc-ci',
      password: process.env.SVC_CI_PSW,
    },
    {
      matchHost: 'some.docker.registry',
      username: 'svc-ci',
      password: process.env.SVC_CI_PSW,
    },
  ],

  onboarding: true,
  onboardingConfig: {
    $schema: 'https://docs.renovatebot.com/renovate-schema.json',
    extends: ['orh/renovate-config'],
  },
  optimizeForDisabled: true,

  persistRepoData: true,

  dockerImagePrefix: `hub.registry.proxy/renovate`,
};

if (process.env.GPG_KEY) {
  module.exports.gitPrivateKey = process.env.GPG_KEY;
}
```
