### DISCUSSION TITLE
Not baseDir, not parentDir... but highestDir?

### DISCUSSION THREAD

**Discussion by cypher7682** [renovatebot/renovate#14361] [Request Help] [answered]
We have a terragrunt folder structure that looks like this:

```
account1:
  - app1:
    - region1
  - app2:
    - region1
account2:
  - app1:
    - region1
  - app2:
    - region2
```

I'm trying to segregate the PRs such that they are grouped by "account" and not region or app. BaseDir appears to give you the whole path, and ParentDir is just the "app". Is it possible at all to get the highest level dir available? 🤔
