### DISCUSSION TITLE
EACCES error on `package-lock.json` file update with dind setup.

### DISCUSSION THREAD

**Discussion by himanshumehta1114** [renovatebot/renovate#14594] [Request Help]
I want to use `lockFileVersion2` to update package-lock files in JavaScript projects. For that, I migrated my project from using full Renovate image to dind setup. On running my self-hosted GitLab config for renovate, I get following error:

```json
{
  "name": "renovate",
  "hostname": "runner-sJWebjxy-project-23754-concurrent-0",
  "pid": 12,
  "level": 40,
  "logContext": "TmkyZJlHuW_qPp9rX5hAh",
  "repository": "himanshu.mehta/test-renovate-js",
  "branch": "renovate/patch-all-minor-patch",
  "artifactErrors": [
    {
      "lockFile": "package-lock.json",
      "stderr": "npm WARN using --force Recommended protections disabled.\nnpm notice \nnpm notice New minor version of npm available! 8.3.1 -> 8.5.3\nnpm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.3>\nnpm notice Run `npm install -g npm@8.5.3` to update!\nnpm notice \nnpm WARN using --force Recommended protections disabled.\nchmod: cannot access '/home/ubuntu/.npm': No such file or directory\nnpm ERR! code EACCES\nnpm ERR! syscall open\nnpm ERR! path /tmp/renovate/repos/gitlab/himanshu.mehta/test-renovate-js/package-lock.json\nnpm ERR! errno -13\nnpm ERR! Error: EACCES: permission denied, open '/tmp/renovate/repos/gitlab/himanshu.mehta/test-renovate-js/package-lock.json'\nnpm ERR!  [Error: EACCES: permission denied, open '/tmp/renovate/repos/gitlab/himanshu.mehta/test-renovate-js/package-lock.json'] {\nnpm ERR!   errno: -13,\nnpm ERR!   code: 'EACCES',\nnpm ERR!   syscall: 'open',\nnpm ERR!   path: '/tmp/renovate/repos/gitlab/himanshu.mehta/test-renovate-js/package-lock.json'\nnpm ERR! }\nnpm ERR! \nnpm ERR! The operation was rejected by your operating system.\nnpm ERR! It is likely you do not have the permissions to access this file as the current user\nnpm ERR! \nnpm ERR! If you believe this might be a permissions issue, please double-check the\nnpm ERR! permissions of the file and its containing directories, or try running\nnpm ERR! the command again as root/Administrator.\n\nnpm ERR! A complete log of this run can be found in:\n"
    }
  ],
  "msg": "artifactErrors",
  "time": "2022-03-10T05:02:57.920Z",
  "v": 0
}
```

Here's my `gitlab-ci.yml` file:
```yaml
default:
  image: renovate/renovate:32.0.6-slim@sha256:b50942275766a33e9c72575fb10f97930533547beb8e384e2f7dcef67dd52a8d
  tags:
    - dind
  cache:
    key: ${CI_COMMIT_REF_SLUG}-renovate
    paths:
      - $CI_PROJECT_DIR/renovate

services:
  - name: docker:19.03-dind
    alias: docker

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''
  RENOVATE_LOG_FILE: renovate-log.ndjson
  RENOVATE_LOG_FILE_LEVEL: debug

stages:
  - deploy

run:
  stage: deploy
  script:
    - renovate
  rules:
    # repos should receive updates on schedule and pipeline manual trigger
    - if: '$CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web"'

    # repos should not receive updates when renovate-runner is updated
    - if: '$CI_COMMIT_MESSAGE =~ /renovate\/renovate/ || $CI_COMMIT_MESSAGE =~ /renovate-renovate/'
      when: never

    # run when the runner configuration is changed or new repo is onboarded.
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - repositories.js
        - config.js
        - .gitlab-ci.yml
  artifacts:
    paths:
      - $RENOVATE_LOG_FILE
```
