### DISCUSSION TITLE
Pre-commit dependencies with pep440 versioning fails

### DISCUSSION THREAD

**Discussion by bavedarnow** [renovatebot/renovate#14600] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.94.1

### Please select which platform you are using if self-hosting.

GitHub Enterprise Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

3.2.1

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When running renovate against a pre-commit config, the [black](https://github.com/psf/black) package does not upgrade because it uses pep440 formatting(instead of semver)

example .pre-commit-config.yaml
```
repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   description: "Black: The uncompromising Python code formatter"
        entry: black
        id: black
        name: black
        language: python
        language_version: python3
        require_serial: true
        args: [src/]
        types: [python]
```

I tried setting the `versioning` in my shared default.json, but renovate didn't pick it up. Not sure if that's related to this or a different issue altogether

```
    {
      "matchDatasources": ["github-tag"],
      "matchPackageNames": ["psf/black"],
      "versioning": "pep440"
    }
```

### Relevant debug logs

<details><summary>Logs</summary>

```
{
    "datasource": "github-tags",
    "depName": "psf/black",
    "depType": "repository",
    "lookupName": "psf/black",
    "currentValue": "20.8b1",
    "depIndex": 2,
    "updates": [],
    "warnings": [],
    "versioning": "semver",
    "skipReason": "invalid-value"
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository
