### DISCUSSION TITLE
Renovate keeps reverting lockfileversion to 1 despite engine constraint on npm@8

### DISCUSSION THREAD

**Discussion by abarre** [renovatebot/renovate#14871] [Request Help] [answered]
### How are you running Renovate?
Gitlab runner on Gitlab CI (https://gitlab.com/renovate-bot/renovate-runner)

### Describe the bug

One of our gitlab repo has a package-lock.json file with lockfileversion 2 as we are now using Node 16.13.0 and npm 8.1.0. Our understanding was that the latest versions of Renovate would respect the lockfileversion in package-lock.json, however it seems to revert to lockfileversion 1 in every PR, causing huge diffs on the package-lock.json file.

I have tried adding an npm.engine constraint to the package.json file without effect.

The issue seems related to https://github.com/renovatebot/renovate/discussions/13027 but I don't understand how I can customize the renovate-runner to fix the issue.

Moreover, we have some git repo that are still using npm 6 and node 14.

The runner is launch via this gitlab-ci.yml : 
```yml
variables:
  LOG_LEVEL: debug

include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate.gitlab-ci.yml'
```

The include file is :
```yml
include: '/templates/_common.gitlab-ci.yml'

image: ${CI_RENOVATE_IMAGE}

variables:
  CI_RENOVATE_IMAGE: renovate/renovate:32.10.2@sha256:2d4955bc544ad54b3e76a81aa5332680fc62a310941a6e3b75635b9c41b0d185
```

https://github.com/renovatebot/renovate/issues/11984 that was linked to the previous issue is closed but I don't if this is related to gitlab-runner.

Do you have an insight on how I can use renovate bot on project using npm 6 and npm 8 via gitlab-runner ?
