### DISCUSSION TITLE
Tips on handling custom image registry with image & tag combo on diff lines

### DISCUSSION THREAD

**Discussion by pashcan** [renovatebot/renovate#15013] [Request Help] [answered]
Hi,
Been trying to use self-hosted renovate (`v32.10.2-slim`) to update image versions defined inside jenkins' helm chart values.yaml in combination with having to use internal image registry.
```yaml
controller:
  image: "harbor.inhouse.com/dockerhub/jenkins/jenkins"
  tag: "team-v0.0.2-plugins"
```
I've tried using this config (basically copy-pasting https://docs.renovatebot.com/configuration-options/#combination), but no luck.
```yaml
  "regexManagers": [
    {
      "description": "Update image in values.yaml",
      "fileMatch": ["^values.yaml$"],
      "matchStringsStrategy": "combination",
      "matchStrings": [
        "image:\\s*\"(?<depName>.*)\"\\s*//",
        "tag:\\s*\"(?<currentValue>.*)\"\\s*//"
      ],
      "datasourceTemplate": "docker"
    }
  ] 
```
Getting this in debug run
```
"config": {
  "helm-values": [
    {
      "packageFile": "values.yaml",
      "deps": [
        {
          "depName": "harbor.inhouse.com/dockerhub/jenkins/jenkins",
          "replaceString": "harbor.inhouse.com/dockerhub/jenkins/jenkins",
          "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
          "datasource": "docker",
          "depIndex": 0,
          "updates": [],
          "warnings": [],
          "versioning": "docker",
          "skipReason": "invalid-value"
        }
      ]
    }
  ],
  ```
Got any tips for configuring this?

**Comment by pashcan** [comment]
My global renovate config that gets loaded by the cronjob:
```
data:
  renovate.json: |
    {
      "platform": "bitbucket-server",
      "endpoint": "https://ourbb.com",
      "enabledManagers": ["helm-values", "helmv3", "dockerfile", "kubernetes"],
      "customRegistrySupport": true,
      "repositories": [
        "ee/test-renovate-1"
      ]
    }
```

**Comment by pashcan** [comment]
I've tried suggestion inspired by this https://github.com/renovatebot/renovate/discussions/12020#discussioncomment-1441533
```
{
  "extends": [
    "config:base"
  ],
  "regexManagers": [
    {
      "description": "Update alpine image in values.yaml",
      "fileMatch": ["^values\\.yaml$"],
      "matchStrings": ["image:\\s?\"?(?<depName>[^\\s\"]*)\"?\\s*?tag:\\s?\"?(?<currentValue>[^\\s\"]*)\"?"],
      "datasourceTemplate": "docker",
      "versioningTemplate": "docker"
    }
  ]
}
```
but getting the same result
```
...
"skipReason": "invalid-value"   
...
```

**Reply by pashcan** [reply]
Some progress on just semver tags (`tag: "3.11") with custom registry by actually enabling regex manager :facepalm: and using this config:
```yaml
{
  "extends": [
    "config:base"
  ],
  "registryUrls": ["https://harbor.ourcompany.com/"],
  "regexManagers": [
    {
      "description": "Yet another regex",
      "fileMatch": "values.yaml$",
      "matchStringsStrategy": "combination",
      "matchStrings": [
        "image: \"(?<registryUrl>harbor.ourcompany.com\/?)(?<depName>.*?)\"\n",
        "tag: \"?(?<currentValue>.*)?\""
      ],
      "datasourceTemplate": "docker"
    }
  ]
}
```
But still need help setting versioning lookup (i guess) on more elaborate tags. i.e. `tag: "team-v3.11-plugins"`. I am back to getting `"skipReason": "invalid-value" `.

**Reply by viceice** [reply]
try regex versioning.

**Reply by pashcan** [reply]
Got it working by adding `"versioning": "regex:^team-(?<major>\\d+)(\\.(?<minor>\\d+))?(\\.(?<patch>\\d+))-plugins$"`.

**Comment by pashcan** [comment, marked as answer]
Works with this: 
```yaml
{
  "extends": [
    "config:base"
  ],
  "registryUrls": ["https://harbor.ourcompany.com/"],
  "packageRules": [
    {
      "matchPackageNames": ["match-depName-below"],
      "versioning": "regex:^team-(?<major>\\d+)(\\.(?<minor>\\d+))?(\\.(?<patch>\\d+))-plugins$"
    }
  ],
  "regexManagers": [
    {
      "description": "Yet another regex",
      "fileMatch": "values.yaml$",
      "matchStringsStrategy": "combination",
      "matchStrings": [
        "image: \"(?<registryUrl>harbor.ourcompany.com\/?)(?<depName>.*?)\"\n",
        "tag: \"?(?<currentValue>.*)?\""
      ],
      "datasourceTemplate": "docker"
    }
  ]
}
```
