### DISCUSSION TITLE
Gitea: Wrong commit author when running renovate from CI

### DISCUSSION THREAD

**Discussion by mschoettle** [renovatebot/renovate#15049] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.17.1

### If you're self-hosting Renovate, tell us what version of the platform you run.

Gitea

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I set up Renovate with Gitea and at the beginning ran it manually with a `config.js` and `docker run ...` and everything worked fine. I use Drone and configured a pipeline to run Renovate on a schedule. For some reason, the PRs Renovate creates are created by the `renovate-bot` user I set up but the commits are attributed to my user.

The pipeline is setup as follows:

```yml
steps:
- name: renovate
  image: renovate/renovate:32.17.1-slim
  environment:
    RENOVATE_PLATFORM: gitea
    RENOVATE_ENDPOINT: <removed>
    RENOVATE_AUTODISCOVER: true
    RENOVATE_GIT_AUTHOR: "Renovate Bot <removed>"
    RENOVATE_ONBOARDING_CONFIG_FILE_NAME: renovate.json5
    RENOVATE_TOKEN:
      from_secret: gitea_token
    GITHUB_COM_TOKEN:
      from_secret: github_token
    LOG_LEVEL: debug
```

In the debug log I can see that the git author is read correctly (see below). It did work once where the commit was made by the `renovate-bot` user so I wonder if it has anything to do with which user triggers the pipeline.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: 1 file(s) to commit (repository=mschoettle/some-repo, branch=renovate/alpine-3.x)

DEBUG: Preparing files for committing to branch renovate/alpine-3.x (repository=mschoettle/some-repo, branch=renovate/alpine-3.x)

DEBUG: Setting git author name (repository=mschoettle/some-repo, branch=renovate/alpine-3.x)

       "gitAuthorName": "Renovate Bot"

DEBUG: Setting git author email (repository=mschoettle/some-repo, branch=renovate/alpine-3.x)

       "gitAuthorEmail": "renovate@example.com"

DEBUG: git commit (repository=mschoettle/some-repo, branch=renovate/alpine-3.x)

       "deletedFiles": [],

       "ignoredFiles": [],

       "result": {

         "author": null,

         "branch": "renovate/alpine-3.x",

         "commit": "0a6d3a4",

         "root": false,

         "summary": {"changes": 1, "insertions": 1, "deletions": 1}

       }

DEBUG: Pushing branch renovate/alpine-3.x (repository=mschoettle/some-repo, branch=renovate/alpine-3.x)

DEBUG: git push (repository=mschoettle/some-repo, branch=renovate/alpine-3.x)

       "result": {

         "pushed": [

           {

             "deleted": false,

             "tag": false,

             "branch": true,

             "new": true,

             "alreadyUpdated": false,

             "local": "refs/heads/renovate/alpine-3.x",

             "remote": "refs/heads/renovate/alpine-3.x"

           }

         ],

         "ref": {"local": "refs/remotes/origin/renovate/alpine-3.x"},

         "remoteMessages": {

           "all": [

             "Create a new pull request for 'renovate/alpine-3.x':",

             "https://<removed>/mschoettle/some-repo/compare/master...renovate/alpine-3.x",

             ". Processing 1 references",

             "Processed 1 references in total"

           ]

         }

       }
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository
