### DISCUSSION TITLE
Github Actions fails with Authentication Error

### DISCUSSION THREAD

**Discussion by AMMJ93** [renovatebot/renovate#15225] [Request Help]
Despite passing a PAT with the correct permissions, I am getting an Authentication Error. Also tried it with a GitHub App, which also gave me the same authentication error.

```
jobs:
  renovate:
    runs-on: [self-hosted, linux, dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.0.1
        with:
          configurationFile: config/renovate-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
```
<details><summary>Click me to see logs</summary>

```
FATAL: Authentication failure
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "logContext": "ZcEu9Uv72yFU0TjY2_XAE",
           "msg": "Authentication failure"
         }
       ]
```

</details>
