### DISCUSSION TITLE
How/Where to configure "imagePullSecrets" inside renovate config?

### DISCUSSION THREAD

**Discussion by kishorkk91** [renovatebot/renovate#15449] [Request Help]
I have "RenovateBot" deployed on the Kubernetes cluster. Secrets , configmap, and CronJob are created. Renovate creates the PR against Bitbucket if there are any new dependency updates. Inside CronJob I am directly specifying the renovate image to be pulled from the docker hub. [](https://docs.renovatebot.com/examples/self-hosting/#kubernetes)

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: renovate
  namespace: test-renovate
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
            - name: LOG_LEVEL
              value: debug
            envFrom:
            - secretRef:
                name: renovate-env
            image: renovate/renovate:31.97 
            imagePullPolicy: IfNotPresent
            name: renovate
```

But instead of pulling image from [docker.io](https://hub.docker.com/) "**image: renovate/renovate:31.97**", I would like to pull it from private/internal registry(Artifactory).

**Something like this:**

```
            imagePullSecrets:
              - name: "artifactory-docker-regcred"
            containers:
              - name: "renovate"
                image: "docker.artifactory.mycompanyname.com/renovate/renovate:31.97"
```
I found this on [renovatebot](https://docs.renovatebot.com/) documentation but am not sure how to configure it. 

https://docs.renovatebot.com/self-hosted-configuration/#dockerimageprefix
https://docs.renovatebot.com/getting-started/private-packages/
https://docs.renovatebot.com/getting-started/private-packages/#package-manager-credentials-for-artifact-updating

**How to achieve this?** Any lead will be really helpful. Thanks
