### DISCUSSION TITLE
Kubernetes self-hosted does not run node 16 / npm 8 when package.json uses engines

### DISCUSSION THREAD

**Discussion by hppycoder** [renovatebot/renovate#15474] [Request Help] [answered]
Using the Kubernetes configuration, package.json, and renovate.json below we cannot seem to get Node 16 / NPM 8 to run. All lock files are in version 1.0 which fail our pipeline compile / tests due to that issue. We have a mix of projects which use Node 12 and some using Node 16. All have the appropriate engines set in their package.json, and .nvmrc

Kubernetes config:
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: pipeline
data:
  config.json: |-
    {
      "autodiscover": true,
      "autodiscoverFilter": "/(Frontend/.*)/",
      "dryRun": false,
      "prCommitsPerRunLimit": 50,
      "onboardingConfig": {
        "extends": ["config:base", "preview:dockerCompose", "preview:dockerVersions"]
      },
      "allowPostUpgradeCommandTemplating": true,
      "allowedPostUpgradeCommands": ["^npm install --dry-run$"]
    }
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: renovate
  namespace: pipeline
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            team: "infra"
          annotations:
            "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
        spec:
          containers:
            - name: renovate
              # Update this to the latest available and then enable Renovate on the manifest
              image: renovate/renovate:32.38.0
              # Environment Variables
              env:
                - name: GOPROXY
                  value: 'http://local-proxy.pipeline.svc.cluster.local'
                - name: RENOVATE_PLATFORM
                  valueFrom:
                    secretKeyRef:
                      key: renovate-platform
                      name: renovate-env
                - name: RENOVATE_ENDPOINT
                  valueFrom:
                    secretKeyRef:
                      key: renovate-endpoint
                      name: renovate-env
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: renovate-token
                      name: renovate-env
                - name: GITHUB_COM_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: github-token
                      name: renovate-env
                - name: RENOVATE_ONBOARDING_BRANCH
                  value: renovate-configure
                - name: RENOVATE_CONFIG_FILE
                  value: '/opt/renovate/config.json'
                - name: LOG_LEVEL
                  value: debug
                - name: LOG_FORMAT
                  value: json
                - name: RENOVATE_ADD_LABELS
                  value: "dependencies"
                # https://docs.renovatebot.com/self-hosted-configuration/#npmjs-registry-token-example
                - name: RENOVATE_DETECT_HOST_RULES_FROM_ENV
                  value: "true"
                - name: NPM_REGISTRY_NPMJS_ORG_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: npm-token
                      name: renovate-env
                - name: DOCKER_REGISTRY_XXX_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: registry-username
                      name: renovate-env
                - name: DOCKER_REGISTRY_XXX_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: registry-password
                      name: renovate-env
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
---
... Secrets below
```

Package.json:
``` json
{
  "name": "@my-org/feature-flag-module",
  "version": "1.1.3",
  "description": "Feature Flag Module",
  "main": "lib/index.js",
  "types": "lib/index.d.ts",
  "files": ["lib/*"],
  "scripts": {
    "compile": "rm -rf ./lib && tsc",
    "test": "jest --coverage",
    "test:dev": "rm -rf ./coverage && jest --coverage --coverageDirectory='./coverage' --coverageReporters='html'"
  },
  "repository": {
    "type": "git",
    "url": "real-url-to-our-repo"
  },
  "author": "My Company",
  "license": "ISC",
  "peerDependencies": {
    "react": ">= 16.8 || 17",
    "axios": ">= 0.21.1"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "5.16.4",
    "@testing-library/react": "12.1.5",
    "@testing-library/react-hooks": "8.0.0",
    "@testing-library/user-event": "14.1.0",
    "@types/jest": "27.4.1",
    "@types/node": "16.11.33",
    "@types/react": "17.0.44",
    "@types/react-dom": "17.0.15",
    "eslint": "8.13.0",
    "jest": "27.5.1",
    "jest-junit": "13.1.0",
    "msw": "0.39.2",
    "prettier": "2.6.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-test-renderer": "17.0.2",
    "ts-jest": "27.1.4",
    "typescript": "4.6.3"
  },
  "engines": {
    "node": "^16",
    "npm": "^8"
  },
  "scope": "private"
}
```

Renovate.json file
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base",
    "preview:dockerCompose",
    "preview:dockerVersions"
  ]
}
```

.nvmrc
``` text
16
```

When renovate runs it produces a package-lock.json which looks like:
``` json
{
  "name": "@my-org/feature-flag-module",
  "version": "1.1.3",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "@ampproject/remapping": {
      "version": "2.2.0",
      "resolved": "https://registry.npmjs.org/@ampproject/remapping/-/remapping-2.2.0.tgz",
      "integrity": "sha512-qRmjj8nj9qmLTQXXmaR1cck3UXSRMPrbsLJAasZpF+t3riI71BXed5ebIOYwQntykeZuhjsdweEc9BxH5Jc26w==",
      "dev": true,
      "requires": {
        "@jridgewell/gen-mapping": "^0.1.0",
        "@jridgewell/trace-mapping": "^0.3.9"
      }
    },
... etc
```

The logs show no errors when it runs nor does the dependency dashboard. I've tried using force constraints, constraints, and nothing seems to have Node 16 (NPM 8) run.
