### DISCUSSION TITLE
docker rm cache: device or resource busy

### DISCUSSION THREAD

**Discussion by narwold** [renovatebot/renovate#15571] [Request Help]
I'm getting this error when a Renovate Docker sidecar tries to update the pnpm lockfile:

```
DEBUG: Executing command (repository=<org>/<repo>, branch=renovate-test/<dep_name>)
       "command": "docker run --rm --name=renovate_node --label=renovate_child --user=0:0 -v \"/tmp/renovate/repos/github/<org>/<repo>\":\"/tmp/renovate/repos/github/<org>/<repo>\" -v \"/tmp/renovate/cache\":\"/tmp/renovate/cache\" -e NPM_CONFIG_CACHE -e npm_config_store -w \"/tmp/renovate/repos/github/<org>/<repo>\" docker.io/renovate/node:16.15.0 bash -l -c \"install-tool pnpm 7.1.0 && pnpm install --recursive --lockfile-only\""
DEBUG: rawExec err (repository=<org>/<repo>, branch=renovate-test/<dep_name>)
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "docker run --rm --name=renovate_node --label=renovate_child --user=0:0 -v \"/tmp/renovate/repos/github/<org>/<repo>\":\"/tmp/renovate/repos/github/<org>/<repo>\" -v \"/tmp/renovate/cache\":\"/tmp/renovate/cache\" -e NPM_CONFIG_CACHE -e npm_config_store -w \"/tmp/renovate/repos/github/<org>/<repo>\" docker.io/renovate/node:16.15.0 bash -l -c \"install-tool pnpm 7.1.0 && pnpm install --recursive --lockfile-only\"",
         "stdout": "Installing legacy tool pnpm v7.1.0\n\nadded 1 package in 755ms\n7.1.0\n",
         "stderr": "rm: cannot remove '/tmp/renovate/repos/github/<org>/<repo>': Device or resource busy\nrm: cannot remove '/tmp/renovate/cache': Device or resource busy\n",
         "message": "Command failed: docker run --rm --name=renovate_node --label=renovate_child --user=0:0 -v \"/tmp/renovate/repos/github/<org>/<repo>\":\"/tmp/renovate/repos/github/<org>/<repo>\" -v \"/tmp/renovate/cache\":\"/tmp/renovate/cache\" -e NPM_CONFIG_CACHE -e npm_config_store -w \"/tmp/renovate/repos/github/<org>/<repo>\" docker.io/renovate/node:16.15.0 bash -l -c \"install-tool pnpm 7.1.0 && pnpm install --recursive --lockfile-only\"\nrm: cannot remove '/tmp/renovate/repos/github/<org>/<repo>': Device or resource busy\nrm: cannot remove '/tmp/renovate/cache': Device or resource busy\n",
         "stack": "Error: Command failed: docker run --rm --name=renovate_node --label=renovate_child --user=0:0 -v \"/tmp/renovate/repos/github/<org>/<repo>\":\"/tmp/renovate/repos/github/<org>/<repo>\" -v \"/tmp/renovate/cache\":\"/tmp/renovate/cache\" -e NPM_CONFIG_CACHE -e npm_config_store -w \"/tmp/renovate/repos/github/<org>/<repo>\" docker.io/renovate/node:16.15.0 bash -l -c \"install-tool pnpm 7.1.0 && pnpm install --recursive --lockfile-only\"\nrm: cannot remove '/tmp/renovate/repos/github/<org>/<repo>': Device or resource busy\nrm: cannot remove '/tmp/renovate/cache': Device or resource busy\n\n    at ChildProcess.exithandler (child_process.js:383:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:475:12)\n    at maybeClose (internal/child_process.js:1088:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)"
       }
```

Any idea how to resolve this?

**Comment by viceice** [comment]
I've never saw this, please provide some more details how you run renovate. Also check your host, maybe some disk / filesystem issue

**Reply by narwold** [reply]
It's self-hosted and runs through a Buildkite pipeline.

Relevant Buildkite step:
```
  - label: 'Build Docker image'
    key: build_docker
    plugins:
      - docker#v3.8.0:
          image: 'renovate/renovate'
          privileged: true
          propagate-uid-gid: true
          environment:
            - 'LOG_LEVEL=debug'
            - 'RENOVATE_CONFIG_FILE=/workdir/renovate-config.js'
          volumes:
            - './scripts:/scripts'
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/tmp:/tmp'
```

Relevant `renovate-config.js` config:
```
module.exports = {
  hostRules: [
    {
      hostType: 'npm',
      hostName: 'registry.npmjs.org',
      token: RENOVATE_NPMJS_NPM_TOKEN,
    },
  ],
  pnpmShrinkwrap: 'pnpm-lock.yaml',
  trustLevel: 'high',
  binarySource: 'docker',
  dockerUser: '0:0',
}
```
