### DISCUSSION TITLE
Update multiple minor version

### DISCUSSION THREAD

**Discussion by dsch** [renovatebot/renovate#15633] [Request Help] [answered]
## Use case

We run our tests with multiple python versions to spot incompatibilities between minor versions. I'd like to keep all jobs update to date by Renovate Bot.

Example CI definition:
```yaml
test_python_3_8:
  stage: test
  image: python:3.8.2
  script:
    - python --version

test_python_3_9:
  stage: test
  image: python:3.9.2
  script:
    - python --version

test_python_3_10:
  stage: test
  image: python:3.10.2
  script:
    - python --version
```

To prevent the bot to update all jobs to the latest Python version (at time of writing 3.10.4) I have disable major and minor updates with following package rule:
```json
{
  "packageRules": [
    {
      "enabled": false,
      "matchManagers": [
        "gitlabci"
      ],
      "matchPackageNames": [
        "python"
      ],
      "matchUpdateTypes": [
        "major",
        "minor"
      ]
    }
  ]
}
```

This works only for the latest minor version: A PR for Python update 3.10.2 -> 3.10.4 gets created.

Is there a way to also gets PRs for the Python 3.8 and 3.9 job?

Is this a bug or a feature?

References: 
Example repo: https://gitlab.com/dsch1/renovate-unittest-versions
MR: https://gitlab.com/dsch1/renovate-unittest-versions/-/merge_requests/1
Renovate Bot version: 32.60.0
