### DISCUSSION TITLE
How to update an actions/checkout ref tag ?

### DISCUSSION THREAD

**Discussion by nitrocode** [renovatebot/renovate#15857] [Request Help] [answered]
Is there a way for renovatebot to look at the actions/checkout `repository`, retrieve the latest release, and raise the pin from ref `v0.0.4` to the latest one retrieved ?

Note: the org and repo are private

```yaml
name: cd
on: [deployment, deployment_status]
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        # This one already auto-updates
        uses: actions/checkout@v3
        with:
          repository: privateorg/github-actions
          # I want to update this ref tag from v0.0.4 to the latest reference
          ref: v0.0.4
          token: ${{ secrets.MY_SECRET }}
          path: actions
```

How would I do this ?
