### DISCUSSION TITLE
Configure different docker image configuration in helm-values

### DISCUSSION THREAD

**Discussion by arthurzenika** [renovatebot/renovate#15976] [Request Help]
I'm trying to use and configure the manager `helm-values` https://docs.renovatebot.com/modules/manager/helm-values/  that uses the `docker` datasource. It correctly detects the `values.yaml` but inside of it I'm having trouble detecting something that is a bit different from the examples.

```
# renovate bot testing
image:
  repository: 'project/component/subcomponent'
  tag: "0.0.1"
  registry: harbor.example.org
# end renovate test


images:
  # syntax one
  - repository: 'project/component/subcomponentA'
    pullPolicy: IfNotPresent
    tag: "0.0.1"
  # syntax two
  - registry: harbor.example.org
    repository: 'project/component/subcomponentB'
    tag: "0.0.1"
    pullPolicy: IfNotPresent
  # syntax three
  - image: harbor.example.org/project/component/subcomponentC:0.0.1
    pullPolicy: IfNotPresent

```
The first section works correctly but we have an helm chart that loops over a list of components that each have a docker image. 

Is there a way one needs to structure the configuration in the list or does renovate only look in the `image:` root section ? Can this be configured ?

**Comment by viceice** [comment]
the parent object key needs to be `image` or end with `Image`

**Reply by arthurzenika** [reply]
So "syntax three" should work ? 

Would something like the below work ?  

```
components: 
  - image: 
      repository: 'project/component/subcomponentA'
      registry: 'harbor.example.org'
      tag: '0.0.1'
  - image: 
      repository: 'project/component/subcomponentB'
      registry: 'harbor.example.org'
      tag: '0.0.1'
```
