### DISCUSSION TITLE
rebaseWhen="conflicted" is ignored

### DISCUSSION THREAD

**Discussion by haldunanil** [renovatebot/renovate#16094] [Request Help]
Hi, I have a `rebaseWhen="conflicted"` flag set for a repo's configuration, but it still rebases when the PR is behind the base branch, which I don't want. Am I doing something wrong in the config? Here's what it looks like:

```json
{
  "extends": ["config:base"],
  "enabledManagers": ["npm"],
  "includePaths": ["dashboard/**"],
  "packageRules": anArrayOfObjects,
  "labels": ["dependencies"],
  "schedule": ["before 9am on the first day of the month"],
  "assigneesFromCodeOwners": true,
  "rebaseWhen": "conflicted",
  "hostRules": [
    {
      "hostType": "npm",
      "matchHost": "some url"
    }
  ]
}
```

When I look at the PR, it even says:

> ♻ Rebasing: Whenever PR is behind base branch, or you tick the rebase/retry checkbox.

which seems wrong based on my rules 😕

**Comment by github-actions** [comment]
Hi there,

Get your issue fixed faster by creating a minimal reproduction. This means a repository dedicated to reproducing this issue with the minimal dependencies and config possible.

Before we start working on your issue we need to know exactly what's causing the current behavior. A minimal reproduction helps us with this.

To get started, please read our guide on creating a [minimal reproduction](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md).

We may close the issue if you, or someone else, haven't created a minimal reproduction within two weeks. If you need more time, or are stuck, please ask for help or more time in a comment.

Good luck,

The Renovate team

**Comment by rarkins** [comment]
Can you reproduce the same thing on GitHub using the app?

**Reply by haldunanil** [reply]
Using the hosted Renovate app on GitHub doesn't work at all for us because our main private package repository (Artifactory) is behind a VPN, so self-hosted is the only solution available. I can provide any additional info if it's helpful though!

**Reply by haldunanil** [reply]
What's also odd is that every other piece of config I have in `renovate.json` appears to be working fine, it's only `rebaseWhen` that seems to get ignored completely.

**Reply by haldunanil** [reply]
Also possibly worth mentioning that I'm using the docker image on Buildkite like so:

```yaml
steps:
  - label: ":pipeline: Renovate Platform"
    agents:
      queue: "image-builder"
    plugins:
      - docker-login#v2.0.1:
          server: some-url
          username: some-user
          password-env: some-password-from-env
      - docker#v3.13.0:
          image: "renovate/renovate"
          volumes:
            - "config.js:/usr/src/app/config.js"
          environment:
            - RENOVATE_TOKEN=$GITHUB_API_TOKEN
```
