### DISCUSSION TITLE
Support updating dependencies defined with variables in .gitlab-ci.yml

### DISCUSSION THREAD

**Discussion by FelixK-Witt** [renovatebot/renovate#16287] [Suggest an Idea]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32

### Please select which platform you are using if self-hosting.

gitlab.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

In the current state, dependencies defined with variables in .gitlab-ci.yml are not updated.

Given the following .gitlab-ci.yml:

```yml

variables:
  IMAGE_CYPRESS: cypress/included:4.12.1
  IMAGE_MYSQL: mysql:8.0.23

test-with-variable-dependencies:
  image: cypress/included:4.12.1
  services:
    - name: $IMAGE_MYSQL
      command: ["--sql-mode=STRICT_TRANS_TABLES"]
```

Or is that perhaps already possible now?

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository
