### DISCUSSION TITLE
Renovate / ArgoCD / Helm image tags in values not updated

### DISCUSSION THREAD

**Discussion by reefland** [renovatebot/renovate#16292] [Request Help] [answered]
I have a self-hosted renovate on k3s, against a provide github repository.   Renovate works great with just about everything in ArgoCD, but I have one Helm based ArgoCD application which might be a special case.

The developer of the Helm Chart mostly pins specific image versions in the Chart, but two of the images uses `latest` tags in the Chart.   I'm overriding the `latest` tags with pinned version via `values` within ArgoCD such as:

```
project: default
source:
  repoURL: 'https://democratic-csi.github.io/charts/'
  targetRevision: 0.13.1
  helm:
    values: |
      csiDriver:
        # should be globally unique for a given cluster
        name: "org.democratic-csi.iscsi"

      controller:
        driver:
          image: docker.io/democraticcsi/democratic-csi:v1.6.3
    
      node:
        driver:
          image: docker.io/democraticcsi/democratic-csi:v1.6.3

  <stuff here removed for brevity>

  destination:
    server: https://kubernetes.default.svc
    namespace:  democratic-csi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
 ```

If the chart does not have a new version, but the images above do have a newer version, renovate either does not see this or ignores this (nothing happens).   For example, while above tags are using `v1.6.3` the current version is `v1.7.1` and I can't get renovate to see this update and apply it.

If the chart does have a new version, renovate acts on it.  However, the two images with latest tags still get the `v1.6.3` tag applied as renovate does not detect the `v1.7.1` is available.

The `renovate.json` file is pretty simple:
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "argocd": {
    "fileMatch": ["applications/.+\\.yaml$"]
  }
}
```
The ArgoCD application in question is `/applications/democratic_csi_iscsi.yaml`.

I figure I could copy his `Chart.yaml` locally and maintain it myself and renovate would have no problem.  But it seems like my current configuration should handle this... just missing something.
