### DISCUSSION TITLE
Subgroups in gitlab runner

### DISCUSSION THREAD

**Discussion by kyeshmz** [renovatebot/renovate#16316] [Request Help]
There seems to be no clear documentations on how subgroups in the renovate gitlab runner are handled, which makes autodiscover filter very hard to set up.

```
include:
  - project: "renovate-bot/renovate-runner"
    file: "/templates/renovate-dind.gitlab-ci.yml"

variables:
  RENOVATE_EXTRA_FLAGS: --autodiscover=true --onboarding=true --autodiscover-filter=["MYGROUP/**/*"]
  LOG_LEVEL: debug
renovate:
    rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
      - if: '$CI_PIPELINE_SOURCE == "push"'
```

Are wildcards like this supported?
