### DISCUSSION TITLE
Grafana Dashboard revisions and Renovate

### DISCUSSION THREAD

**Discussion by ruzickap** [renovatebot/renovate#16624] [Suggest an Idea]
Does anybody using renovate to upgrade grafana dashboard revisions?

For example here are revisions for `Node Exporter Full`: https://grafana.com/grafana/dashboards/1860/revisions

In the grafana helm chart you can find sections which defined the grafana dashboard and revision like here:

https://github.com/grafana/helm-charts/blob/d869e93faebf3df819ad02fd4ded5a09e682e824/charts/grafana/values.yaml#L551-L554

There is no datasource in renovate which can handle grafana dashboard revisions :-(

Is it possible to use renovate to upgrade grafana dashboard revisions:

```yaml
dashboards:
  default:
    k8s-cluster-summary:
    # https://grafana.com/grafana/dashboards/1860/revisions
    node-exporter-full:
      gnetId: 1860
      revision: 27                <<<--- grafana dashboard revision
      datasource: Prometheus
```

Thank you

**Comment by secustor** [comment]
EDIT: as this is the top result for searching Grafana and Renovate: 
This is now possible using [`customDatasources`](https://docs.renovatebot.com/modules/datasource/custom/#grafana-dashboard)

There is no way I'm aware of, as you already mentioned there is no datasource or other repository to follow. 

If you want this to be implemented then the best way would be to open a feature request for a datasource and beforehand investigate if there is an API for the public registry.  
Alternatively you can wait for the generic datasource and then implement a middleware.

**Reply by ruzickap** [reply]
Seems like there is an API where you can get details about the dashboard: 

```
curl https://grafana.com/api/dashboards/1860
```

Anyway - thank you for the answer...

**Reply by viceice** [reply]
if they have a json API which returns all versions, you could try the new generic JSON datasource

**Reply by dsegurag** [reply]
Finally I was able to get updates from dashboards.

For my approach I'm using Terraform. Having this into the `main.tf` file:

```hcl
data "http" "node_exporter_dashboard" {
  # renovate: depName="Node Exporter Full"
  url = "https://grafana.com/api/dashboards/1860/revisions/30/download"
}
```

And with this Renovate configuration:

```json
  "regexManagers": [
    {
      "fileMatch": [
        "^main.tf$"
      ],
      "matchStrings": [
        "#\\s+renovate:\\s+depName=\"(?<depName>.*)\"\\n\\s+url\\s+=\\s+\\\"https://grafana\\.com/api/dashboards/(?<packageName>.*?)/revisions/(?<currentValue>.*)/download\\\""
      ],
      "versioningTemplate": "regex:^(?<major>\\d+)$",
      "datasourceTemplate": "custom.grafana-dashboards"
    }
  ],
  "customDatasources": {
    "grafana-dashboards": {
      "defaultRegistryUrlTemplate": "https://grafana.com/api/dashboards/{{packageName}}",
      "format": "json",
      "transformTemplates": [
        "{\"releases\":[{\"version\": $string(revision)}]}"
      ]
    }
  }
```

This was the result:

![image](https://github.com/renovatebot/renovate/assets/21098646/70257793-9ac9-462a-9fd3-2c4bf12a9fb0)

**Reply by ruzickap** [reply]
Thank you @dsegurag for a great tip :-)

I'm updating my Grafana Dashbords version in `grafana` / `kube-prometheus-stack` helm charts similar way:

```yaml
grafana:
  dashboards:
    default:
      1860-node-exporter-full:
        # renovate: depName="Node Exporter Full"
        gnetId: 1860
        revision: 31
        datasource: Prometheus
      15760-kubernetes-views-pods:
        # renovate: depName="Kubernetes / Views / Pods"
        gnetId: 15760
        revision: 20
        datasource: Prometheus
```

Renovate configuration:

```json
  "regexManagers": [
    {
      "fileMatch": [
        ".*\\.yml$",
      ],
      "matchStrings": [
        "#\\s+renovate:\\s+depName=\"(?<depName>.*)\"\\n\\s+gnetId:\\s+(?<packageName>.*?)\\n\\s+revision:\\s+(?<currentValue>.*)"
      ],
      "versioningTemplate": "regex:^(?<major>\\d+)$",
      "datasourceTemplate": "custom.grafana-dashboards"
    },
  ],
  "customDatasources": {
    "grafana-dashboards": {
      "defaultRegistryUrlTemplate": "https://grafana.com/api/dashboards/{{packageName}}",
      "format": "json",
      "transformTemplates": [
        "{\"releases\":[{\"version\": $string(revision)}]}"
      ],
    },
  },
```

Thank you all...

**Reply by viceice** [reply]
please open a PR to update the docs for custom datasource with those samples. 🤗

**Reply by ruzickap** [reply]
Here is is: https://github.com/renovatebot/renovate/pull/23954

**Reply by thibveni** [reply]
For those using yaml instead of yml value files, don't forget to change the fileMatch ;)

**Reply by onedr0p** [reply]
It looks like something broke recently and this no longer works

Config: https://github.com/onedr0p/home-ops/blob/main/.github/renovate/grafanaDashboards.json5

Workflow run: https://github.com/onedr0p/home-ops/actions/runs/7145912697

PR: https://github.com/onedr0p/home-ops/pull/6518/files

While the `revision` is getting updated correctly, the `gnetId`'s first digit is getting mutated with the dashboard `revision` number which is not expected.

**Reply by viceice** [reply]
please create a new discussion with a reproduction

**Reply by buroa** [reply]
For anyone that sees this in the future, here is the fix: https://github.com/buroa/k8s-gitops/blob/master/.github/renovate/grafanaDashboards.json5

**Reply by vtmocanu** [reply]
I'm facing the same issue with mutated first digits.
Any chance you could update the readme, or provide a renovate.json file please?
I find it difficult to translate that json5 to the renovate.json syntax with all that escaping needed.
Thank you for posting this!

here is an example of yaml that gets mutated on the PR:
```
        node-exporter-full:
          # renovate: depName="Node Exporter Full"
          gnetId: 1860
          revision: 37
          datasource:
            - name: DS_PROMETHEUS
              value: Prometheus
```

```
commit 77e0a4ffe51a75627472443c284da6a99e6b3652
Author: Renovate Bot <renovatebot@wxs.ro>
Date:   Thu Aug 29 14:37:45 2024 +0000

    Update dependency Node Exporter Full to v37

diff --git a/helm/values-grafana.yaml b/helm/values-grafana.yaml
index 85b5e11..7abe229 100644
--- a/helm/values-grafana.yaml
+++ b/helm/values-grafana.yaml
@@ -63,8 +63,8 @@ kps:
               value: ""
         node-exporter-full:
           # renovate: depName="Node Exporter Full"
-          gnetId: 1860
-          revision: 1
+          gnetId: 37860
+          revision: 37
           datasource:
             - name: DS_PROMETHEUS
               value: Prometheus
```
