### DISCUSSION TITLE
gitlabci does not resolve into trigger-included gitlab-ci versions

### DISCUSSION THREAD

**Discussion by pritho** [renovatebot/renovate#16652] [Suggest an Idea]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

v32.119.1

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

15.1.2

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

trigger-included gitlab-ci templates are not correctly resolved and managed.
Only the main include is being properly resolved.
In this example, only v0.0.1 would be updated, but not v0.1.0 to an existing later release.

Minimal reproduction repo: https://gitlab.com/thopr/renovate-gitlab-ci
Included repo (tags v0.0.1, v0.1.0 & v0.2.0) : https://gitlab.com/thopr/ci-template

````
include:
  - project: MyGroup/ci-template
    file: hello-world.yml
    ref: v0.0.1

2nd-hello:
  stage: hello
  trigger:
    include:
      - project: MyGroup/ci-template
        file: hello-world.yml
        ref: v0.1.0
    strategy: depend
````

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description
