### DISCUSSION TITLE
Understanding onboarding (repo is always skipped)

### DISCUSSION THREAD

**Discussion by lrxw** [renovatebot/renovate#16702] [Request Help] [answered]
Hi folks,
I set up renovate on a self hosted gitlab instance. I imported the runner into our group, created a new project for renovate and pushed a config.js and a gitlab-ci.yml into the project.

Now I try to understand the onboarding process.
I configured one of our project as repository in config.js as a test repo. There is no renovate.json in that repo.
I thought that the onboarding PR which renovate creates, also create the renovate.json if I set onboarding to true? Or do I need at least an empty renovate.json in every case?
I thought I can just skip that step for every repo and let renovate do the work.
But my repo is always skipped:

> DEBUG: config file not found (repository=project/group/myrepo)
>  INFO: Repository is disabled - skipping (repository=project/group/myrepo)
> DEBUG: Repository result: disabled-no-config, status: disabled, enabled: false, onboarded: undefined (repository=project/group/myrepo)

gitlab-ci.yml:
```
include:
    - project: 'project/group/renovate-runner'
      file: '/templates/renovate-dind.gitlab-ci.yml'

variables:
  LOG_LEVEL: debug


renovate:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - renovate $RENOVATE_EXTRA_FLAGS
```

config.js:
```
module.exports = {
  "platform": "gitlab",
  "endpoint": "https://ourgitlab.org/api/v4/",
  "repositories": ["project/group/myrepo"],
  "logLevel": "info",
  "requireConfig": "required",
  "onboarding": true,
  "onboardingConfig": {"extends": ["config:base"], "prConcurrentLimit": 5},
  "enabledManagers": ["gradle"]
};
```
