### DISCUSSION TITLE
Manager ansible-galaxy doesn't update dependencies of the galaxy.yml

### DISCUSSION THREAD

**Discussion by SirUli** [renovatebot/renovate#16853] [Suggest an Idea]
I'm running renovate self-hosted (32.133.0) on Bitbucket server and was running into a situation where renovate updates through the ansible-galaxy manager the requirements.yml files but not the galaxy.yml for self-hosted dependencies.

My galaxy.yml:

```yml
---
namespace: "company"
name: "awesomename"
version: "2.3.15"
authors:
  - SirUli
description: Some description
dependencies:
  "git+https://bitbucket.company.com/scm/department/ansible-collection-platform.git": "v1.1.0"
  "git+https://bitbucket.company.com/scm/department/ansible-collection-tools.git": "v1.8.0"
```

While a requirements.yml in the same directory is picked up and updated, renovate detects the galaxy.yml for the manager ansible-galaxy but then doesn't act on the dependencies above.

Going through the source code of renovate (starting from the [extract.ts](https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/ansible-galaxy/extract.ts#L37)) via the [extractCollectionsMetaDataFile](https://github.com/renovatebot/renovate/blob/2c5fd14e252d8cf06eb57d7b951256e47dce592d/lib/modules/manager/ansible-galaxy/collections-metadata.ts#L5) method which utilizes the [galaxyRegEx](https://github.com/renovatebot/renovate/blob/2c5fd14e252d8cf06eb57d7b951256e47dce592d/lib/modules/manager/ansible-galaxy/util.ts#L7) i believe that is simply currently not implemented that such dependencies are taken into account (although they work and are correctly handled by ansible-galaxy).

Is that assumption correct?
