### DISCUSSION TITLE
Private NPM package on Gitlab and Artifact update problem

### DISCUSSION THREAD

**Discussion by Igor-lkm** [renovatebot/renovate#16915] [Request Help] [answered]
## Updated, answer:

1) hostRules in `runner` > `config.js` should contain whole path if registry with a path, not only host name (`matchHost: 'gitlab.myorg.com'` - not correct)

```
...
hostRules: [
    {
      hostType: 'npm',
      matchHost: 'https://gitlab.myorg.com/api/v4/packages/npm/',
      token: process.env.CI_JOB_TOKEN,
    },
  ],
...
```

2) In `config` > `default.json`

```
   ...
  "npmrc": "@myorg:registry=https://gitlab.myorg.com/api/v4/packages/npm/",
  "ignoreNpmrcFile": true,
   ...
```

### Setup
I have a self hosted gitlab.

I have two repos for renovate:

- `renovate-runner`
- `renovate-config`

I have a Node.js project called `project1`

This node.js project uses private gitlab npm registry, so package I have there in `package.json` is `@myorg/mypackage`

So package is available here: `https://gitlab.myorg.com/api/v4/packages/npm/@myorg%2fmypackage`

`.npmrc` inside `project1` looks like this:

```
@myorg:registry=https://gitlab.myorg.com/api/v4/packages/npm/
//gitlab.myorg.com/api/v4/packages/npm/:_authToken=${MYORG_NPM_TOKEN}
```

### renovate-runner

`.gitlab-ci`:

```yaml
image: renovate/renovate:32

variables:
  RENOVATE_BASE_DIR: $CI_PROJECT_DIR/renovate
  RENOVATE_GIT_AUTHOR: Renovate Bot <renovatebot@myorg.com>
  RENOVATE_OPTIMIZE_FOR_DISABLED: "true"
  RENOVATE_REPOSITORY_CACHE: "true"
  LOG_LEVEL: debug

cache:
  key: ${CI_COMMIT_REF_SLUG}-renovate
  paths:
    - $CI_PROJECT_DIR/renovate

stages:
  - deploy

renovate:
  stage: deploy
  only:
    - schedules
    - master
  script:
    - renovate $RENOVATE_EXTRA_FLAGS

```

`config.js`:

```js
module.exports = {
  endpoint: 'https://gitlab.myorg.com/api/v4/',
  platform: 'gitlab',
  persistRepoData: true,
  logLevel: 'info',
  onboardingConfig: {
    extends: ['local>renovate-config'],
  },
  repositories: [
    'project1',
  ],
  hostRules: [
    {
      matchHost: 'gitlab.myorg.com',
      token: process.env.CI_JOB_TOKEN,
    },
  ],
};
```

### renovate-config

`default.json`

```

{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "npmrc": "@myorg:registry=https://gitlab.myorg.com/api/v4/packages/npm/",
  "ignoreNpmrcFile": true,
  "enabledManagers": ["gitlabci", "dockerfile", "npm"],
  "assigneesFromCodeOwners": true,
  "rangeStrategy": "bump",
  "packageRules": [
    {
      "depTypeList": [ "dependencies" ],
      "updateTypes": [ "patch", "minor"],
      "groupName": "dependencies (non-major)",
      "prCreation": "immediate",
      "automerge": true,
      "automergeStrategy": "fast-forward"
    },
    {
      "depTypeList": [ "dependencies" ],
      "updateTypes": [ "major"],
      "groupName": "dependencies",
      "prCreation": "immediate"
    },
    {
      "depTypeList": [ "devDependencies" ],
      "updateTypes": [ "patch", "minor"],
      "groupName": "dev dependencies (non-major)",
      "prCreation": "immediate",
      "automerge": true,
      "automergeStrategy": "fast-forward"
    },
    {
      "depTypeList": [ "devDependencies" ],
      "updateTypes": [ "major"],
      "groupName": "dev dependencies",
      "prCreation": "immediate"
    }
  ],
  "extends": [
    "config:base",
    ":preserveSemverRanges",
    ":dependencyDashboard",
    ":rebaseStalePrs",
    ":enableVulnerabilityAlertsWithLabel('security')",
    "group:recommended"
  ],
  "ignorePresets": [":prHourlyLimit2"]
}
```

An issue:

MR is created successfully even has information that scoped package needs to be updated:

![Screenshot 2022-08-02 at 18 10 56](https://user-images.githubusercontent.com/6287367/182422106-aeb40bc6-5e01-40be-8759-0e1a66d31c6b.png)

However then I have this message ` Artifact update problem`:

```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code E404
npm ERR! 404 Not Found - GET https://gitlab.myorg.com/api/v4/packages/npm/@myorg%2fmypackage
npm ERR! 404 
npm ERR! 404  '@myorg/mypackage@^0.2.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'project1'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build...
```

At the end:

So MR contains only changes into `package.json`, but `package-lock.json` can not be created.

Thank you for the help
