### DISCUSSION TITLE
what is release stage in pipeline for

### DISCUSSION THREAD

**Discussion by marvinfischenich** [renovatebot/renovate#17071] [Request Help] [answered]
Hi guys,
what is the purpose of the release stage in the [pipeline ](https://gitlab.com/renovate-bot/renovate-runner/-/blob/main/.gitlab-ci.yml)?

Is there something in the docs about that?
I couldn't find anything.

Thanks!

**Comment by rarkins** [comment, marked as answer]
I think that's just for that repo's own internal use/releasing

**Reply by viceice** [reply]
If you like to use that templates, just follow https://gitlab.com/renovate-bot/renovate-runner/-/tree/main#create-a-gitlab-ci-file

So this pipeline should be enough for you:

```yaml
include:
    - project: 'renovate-bot/renovate-runner'
      file: '/templates/renovate-dind.gitlab-ci.yml'
```
