### DISCUSSION TITLE
Renovate failed to look up the following dependencies

### DISCUSSION THREAD

**Discussion by btxbtx** [renovatebot/renovate#17186] [Request Help] [answered]
I posted a similar question earlier on an example repo, but the example was flawed, so I am reposting using output from an actual run.

My setup:

- gitlab.com private repositories
- gitlab private registries
- renovate gitlab runner

The token has `api, read_user, write_repository`.  The token belongs to an account with `Developer` access to all private repos.

`config.js`
```js
module.exports = {
  onboardingConfig: {
    globalExtends: ["config:base"],
  },
  platform: "gitlab",


  repositories: [
    "<helm chart repo>",
  ],

  baseBranches: ["develop"],


  "helm-values": {
    "fileMatch": ["helmfiles\\/.+\\/*values\\.yaml$"],
  },

  "enabledManagers": ["helm-values"],

};
```

`.gitlab-ci.yml`
```yaml
include:
    - project: 'renovate-bot/renovate-runner'
      file: '/templates/renovate-dind.gitlab-ci.yml'
      ref: v8.182.0

variables:
  RENOVATE_GIT_AUTHOR: <account with valid token>
  RENOVATE_TOKEN: $RENOVATE_TOKEN
  LOG_LEVEL: debug

renovate:
  rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
      - if: '$CI_PIPELINE_SOURCE == "push"'
```

In the helm chart repo, renovate.json
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],

  "ignorePaths": ["**charts/**"]
}

```

Running the pipeline produces a dashboard with this message "Renovate failed to look up the following dependencies" and a list of dependencies.

Debug output:
https://gist.github.com/btxbtx/9f171b168557eb454e3317b701637ad7
