### DISCUSSION TITLE
GitLab Runner GPG / RENOVATE_GIT_PRIVATE_KEY support?

### DISCUSSION THREAD

**Discussion by btxbtx** [renovatebot/renovate#17206] [Request Help]
I am using the GitLab Runner,

```
include:
    - project: 'renovate-bot/renovate-runner'
      file: '/templates/renovate-dind.gitlab-ci.yml'
      ref: v8.182.0
```

On a private repo.  Commits are being denied because my repo has a setting to reject unsigned commits.  I looked around for an option to set a signing key, but only found `RENOVATE_GIT_PRIVATE_KEY` which is for self hosted renovate.

How can I setup a signing key to be used by the runner?
