### DISCUSSION TITLE
renovate:slim with bitbucket pipelines

### DISCUSSION THREAD

**Discussion by setchy** [renovatebot/renovate#17245] [Request Help]
Seeking any input / pro-tips on how to successfully get renovate/renovate:slim working with Bitbucket Pipelines.  

I've followed the example from https://github.com/renovatebot/docker-renovate/blob/main/docs/bitbucket.md, but am receiving several PRs with the following comment added to them
```
You don't have permission to create /opt/atlassian/pipelines/agent/build/renovate/cache/buildpack/7576b42decc67f70b61585f41c5074bea75c260886346e567578ea0e0dc2d571.
curl: (23) Failed writing received data to disk/application
tar: /opt/atlassian/pipelines/agent/build/renovate/cache/buildpack/7576b42decc67f70b61585f41c5074bea75c260886346e567578ea0e0dc2d571/node-v16.17.0-linux-x64.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
bash: npm: command not found
```

🤔

**Comment by viceice** [comment]
do you use the plain template or did you changed something?

is there something specific to your pipeline against the bitbucket defaults?

**Reply by setchy** [reply]
We use the plain template pretty much as-is.  

The only two notable changes would be

- `RENOVATE_REDIS_URL` is set to our distributed redis
- we use bitbucket pipeline local runners so that it has connectivity to our redis service

```yml
branches:
    master:
      - step:
          name: renovate
          services:
            - docker
          caches:
            - docker
            - renovate
          script:
            - export LOG_LEVEL=debug RENOVATE_CONFIG_FILE="$BITBUCKET_CLONE_DIR/config.js" RENOVATE_REDIS_URL="rediss://...."
            - renovate
          runs-on:
            - "self.hosted"
            - "linux"
 ```
