### DISCUSSION TITLE
GitLab 403 - hostRules set and token with api, read user, read registry, write repo

### DISCUSSION THREAD

**Discussion by btxbtx** [renovatebot/renovate#17253] [Request Help] [answered]
My setup:

- gitlab.com private repositories
- gitlab private registries
- running renovate 32 in kubernetes
- gitlab token with `api, read_user, write_repository, read_registry`

What's odd is I had a very similar config that passed after getting help in [this thread](https://github.com/renovatebot/renovate/discussions/17186).  The config from that thread ran fine when running `renovate` locally after adding in the token/host rules to config.js (not using the runner).  However, this config is resulting in 403s and I can't figure out why.

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: renovate
  namespace: "renovate"
  labels:
    app.kubernetes.io/name: renovate
    helm.sh/chart: renovate-0.1.0
    app.kubernetes.io/instance: renovate
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  GITHUB_COM_TOKEN: <valid github token>
  RENOVATE_TOKEN: <valid gitlab token>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate
  namespace: "renovate"
  labels:
    app.kubernetes.io/name: renovate
    helm.sh/chart: renovate-0.1.0
    app.kubernetes.io/instance: renovate
    app.kubernetes.io/managed-by: Helm
data:
  config.json: |-
    {
      onboardingConfig: {
        globalExtends: [
          "config:base",
          ":pinVersions",
          ":rebaseStalePrs",
        ],
      },

        platform: "gitlab",

        commitMessageAction: "Update",
        commitMessageTopic: "",
        commitMessageExtra: "",
        commitMessageSuffix: "",
        prTitle: "",

        "hostRules": [
          {
            "matchHost":"registry.gitlab.com",
            "username":"<gitlab user>",
            "token":"<valid token>"
          }
        ],

        repositories: ["<helm chart repo>"],

        branchPrefix: "change/RENOVATE-",

        baseBranches: ["develop"],

        groupName: "all outdated image tags",

        "helm-values": {
          fileMatch: ["helmfiles\\/.+\\/*values\\.yaml$"],
        },

        enabledManagers: ["helm-values"],
    }
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: renovate
  namespace: "renovate"
  labels:
    app.kubernetes.io/name: renovate
    helm.sh/chart: renovate-0.1.0
    app.kubernetes.io/instance: renovate
    app.kubernetes.io/managed-by: Helm
spec:
  schedule: "50 * * * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 0
      template:
        metadata:
          labels:
            app.kubernetes.io/name: renovate
            helm.sh/chart: renovate-0.1.0
            app.kubernetes.io/instance: renovate
            app.kubernetes.io/managed-by: Helm
        spec:
          restartPolicy: Never
          containers:
            - name: renovate
              image: renovate/renovate:32
              imagePullPolicy: "IfNotPresent"
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: RENOVATE_AUTODISCOVER
                  value: "false"
                - name: RENOVATE_CONFIG_FILE
                  value: /opt/renovate/config.json
                - name: RENOVATE_GIT_AUTHOR
                  value: <author>
                - name: RENOVATE_PLATFORM
                  value: gitlab                
                - name: GITHUB_COM_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate
                      key: GITHUB_COM_TOKEN
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate
                      key: RENOVATE_TOKEN
              resources:
                limits: {}
                requests: {}
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
          volumes:
            - name: config-volume
              configMap:
                name: renovate
            - name: work-volume
              emptyDir: {}

```

helm chart repo renovate.json
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],

  "ignorePaths": ["**charts/**"]
}
```

Debug Logs: https://gist.github.com/btxbtx/b4c5a06c7db58ee75d6c51add20a367d

Also side question, how do I apply your discussion template to my posts?
