### DISCUSSION TITLE
Error obtaining docker token - ghcr.io

### DISCUSSION THREAD

**Discussion by omercnet** [renovatebot/renovate#17546] [Request Help]
Running self hosted via github actions, but even when debugging locally with docker on my own machine, with my personal token instead of app token, the same error happens

a similar (if not identical) config worked using the hosted github app - I'm unable to detect the reason it's not even sending credentials here

```
# config.js
module.exports = {
  username: "organization[bot]",
  gitAuthor: "organization <devops@organization.com>",
  platform: "github",
  includeForks: false,
  hostRules: [
    {
      hostType: "docker",
      matchHost: "https://ghcr.io/organization",
      username: "organization",
      password: process.env.RENOVATE_TOKEN,
    },
  ],
};

```

```
# error

DEBUG: getManifestResponse(https://ghcr.io, organization/repo1, latest) (repository=organization/repo2)
 WARN: Error obtaining docker token (repository=organization/repo2)
       "registryHost": "https://ghcr.io",
       "dockerRepository": "organization/repo1",
       "err": {
         "err": {
           "name": "HTTPError",
           "code": "ERR_NON_2XX_3XX_RESPONSE",
           "timings": {
             "start": 1661952641809,
             "socket": 1661952643071,
             "upload": 1661952643071,
             "response": 1661952643409,
             "end": 1661952643412,
             "phases": {
               "wait": 1262,
               "request": null,
               "firstByte": 338,
               "download": 3,
               "total": 1603
             }
           },
           "message": "Response code 401 (Unauthorized)",
           "stack": "HTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
           "options": {
             "headers": {
               "user-agent": "RenovateBot/32.185.3 (https://github.com/renovatebot/renovate)",
               "accept": "application/json",
               "accept-encoding": "gzip, deflate, br"
             },
             "url": "https://ghcr.io/token?service=ghcr.io&scope=repository:organization/repo1:pull",
             "hostType": "docker",
             "username": "",
             "password": "",
             "method": "GET",
             "http2": true
           },
           "response": {
             "statusCode": 401,
             "statusMessage": "Unauthorized",
             "body": {
               "errors": [
                 {"code": "UNAUTHORIZED", "message": "authentication required"}
               ]
             },
             "headers": {
               ":status": 401,
               "content-type": "application/json",
               "docker-distribution-api-version": "registry/2.0",
               "www-authenticate": "Bearer realm=\"https://ghcr.io/token\",service=\"ghcr.io\",scope=\"repository:user/image:pull\"",
               "date": "Wed, 31 Aug 2022 13:30:43 GMT",
               "content-length": "73",
               "x-github-request-id": "CA6C:7B14:4167C5:45E200:630F6283"
             },
             "httpVersion": "2.0"
           }
         },
         "message": "external-host-error",
         "stack": "Error: external-host-error\n    at Http.request (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:180:15)\n    at Http.requestJson (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:219:17)\n    at getAuthHeaders (/usr/src/app/node_modules/renovate/lib/modules/datasource/docker/index.ts:172:7)\n    at DockerDatasource.getManifestResponse (/usr/src/app/node_modules/renovate/lib/modules/datasource/docker/index.ts:399:23)\n    at DockerDatasource.getDigest (/usr/src/app/node_modules/renovate/lib/modules/datasource/docker/index.ts:978:28)\n    at /usr/src/app/node_modules/renovate/lib/util/cache/package/decorator.ts:78:20\n    at lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:376:34)\n    at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:58:15)\n    at /usr/src/app/node_modules/p-map/index.js:57:22"
       }
 WARN: No docker auth found - returning (repository=organization/repo2)

```

**Comment by PhilipAbed** [comment]
Hi, What is the docker command you are running?

**Reply by omercnet** [reply]
this is the workflow

```
jobs:
  renovate:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}

      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.118.0
        env:
          LOG_LEVEL: "DEBUG"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RENOVATE_TOKEN: ${{ steps.get_token.outputs.app_token }}
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: "organization/*"
        with:
          configurationFile: renovate-config.js
          token: "x-access-token:${{ steps.get_token.outputs.app_token }}"
```

the equivalent docker command is
`docker run --rm -v "`pwd`/config.js:/usr/src/app/config.js" --env-file=.env renovate/renovate`
where .env has `RENOVATE_TOKEN` set to a PAT with full privileges
