### DISCUSSION TITLE
Can't get postUpgradeTasks to work with with terraform

### DISCUSSION THREAD

**Discussion by sjoerd-dijkstra** [renovatebot/renovate#17806] [Request Help] [answered]
### Question

Hey! Most probably we're doing something wrong, but we can't get the post upgrade tasks to run for our terraform repos. The  `postUpgradeTasks` seem to be skipped no matter what we put in the configuration files.

What are we doing wrong!? 👀 

### Runners

We're using self hosted gitlab renovate runners, with the below `.gitlab-ci.yaml` config:

```yaml
include:
  - project: renovate-bot/renovate-runner
    file: /templates/renovate-dind.gitlab-ci.yml

image: our-cumstom-renovate-container-with-terraform-docs:v1

variables:
  RENOVATE_EXTRA_FLAGS: --autodiscover=true --onboarding=true
```

### Configuration

Our `renovate.json` in the terraform repositories looks like this:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "packageRules": [
    {
      "matchDatasources": [
        "terraform-provider"
      ],
      "postUpgradeTasks": {
        "commands": [
          "terraform providers lock -platform=darwin_amd64 -platform=linux_amd64"
        ],
        "fileFilters": [
          ".terraform.lock.hcl"
        ]
      }
    },
    {
      "matchDatasources": [
        "terraform-module",
        "terraform-provider"
      ],
      "postUpgradeTasks": {
        "commands": [
          "terraform-docs markdown --output-file=README.md --recursive=true ."
        ],
        "fileFilters": [
          "**/README.md"
        ]
      }
    }
  ]
}
```

Renovate runs fine in all our projects, but the additional commands are not run... 

Thanks in advance! 🙏

**Comment by viceice** [comment, marked as answer]
You need to configure allowed commands as described here[^1]

[^1]: https://docs.renovatebot.com/configuration-options/#postupgradetasks

**Reply by sjoerd-dijkstra** [reply]
Thank you sir , that was it! 😃

We had tried this before, but only locally... The "allowed post upgrade commands" setting is however a global config, which makes total sense.

We have solved it by adjusting our `.gitlab-ci.yaml` to:

```yaml
# omitted

variables:
  RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: '["^terraform"]'

# omitted
```
