### DISCUSSION TITLE
You don't have permission to create /tmp/renovate/cache/containerbase

### DISCUSSION THREAD

**Discussion by monwolf** [renovatebot/renovate#17977] [Request Help] [answered]
I'm trying to update Pipfiles.lock with a docker in docker setup and renovate-slim  (renovate/renovate:32-slim). But when it tries to download the Python toolchain from containerbase inside the sidecar it fails with the error:   
```
You don't have permission to create /tmp/renovate/cache/containerbase
```
See the full log: 

```
DEBUG: Failed to update Pipfile.lock (repository=mpa/naru, branch=renovate/all-minor-patch)
       "err": {
         "name": "ExecError",
         "cmd": "/bin/sh -c docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/tmp/renovate/repos/bitbucket-server/mpa/naru\":\"/tmp/renovate/repos/bitbucket-server/mpa/naru\" -v \"/tmp/renovate/cache\":\"/tmp/renovate/cache\" -e PIPENV_CACHE_DIR -e PIP_CACHE_DIR -e BUILDPACK_CACHE_DIR -w \"/tmp/renovate/repos/bitbucket-server/mpa/naru\" docker.io/renovate/sidecar bash -l -c \"install-tool python 3.7.14 && pip install --user pipenv && pipenv lock\"",
         "stderr": "You don't have permission to create /tmp/renovate/cache/containerbase.\ncurl: (23) Failed writing received data to disk/application\nDownload failed: https://github.com/containerbase/python-prebuild/releases/download/3.7.14/python-3.7.14-focal-x86_64.tar.xz\n",
         "stdout": "installing v2 tool python v3.7.14\n",
         "options": {
           "cwd": "/tmp/renovate/repos/bitbucket-server/mpa/naru",
           "encoding": "utf-8",
           "env": {
             "PIPENV_CACHE_DIR": "/tmp/renovate/cache/others/pipenv",
             "PIP_CACHE_DIR": "/tmp/renovate/cache/others/pip",
             "HOME": "/home/ubuntu",
             "PATH": "/home/ubuntu/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
             "LC_ALL": "C.UTF-8",
             "LANG": "C.UTF-8",
             "DOCKER_HOST": "tcp://localhost:2376",
             "DOCKER_TLS_VERIFY": "1",
             "DOCKER_CERT_PATH": "/certs/client/",
             "BUILDPACK_CACHE_DIR": "/tmp/renovate/cache/containerbase"
           },
           "maxBuffer": 10485760,
           "timeout": 900000
         },
         "exitCode": 1,
         "message": "Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/tmp/renovate/repos/bitbucket-server/mpa/naru\":\"/tmp/renovate/repos/bitbucket-server/mpa/naru\" -v \"/tmp/renovate/cache\":\"/tmp/renovate/cache\" -e PIPENV_CACHE_DIR -e PIP_CACHE_DIR -e BUILDPACK_CACHE_DIR -w \"/tmp/renovate/repos/bitbucket-server/mpa/naru\" docker.io/renovate/sidecar bash -l -c \"install-tool python 3.7.14 && pip install --user pipenv && pipenv lock\"\nYou don't have permission to create /tmp/renovate/cache/containerbase.\ncurl: (23) Failed writing received data to disk/application\nDownload failed: https://github.com/containerbase/python-prebuild/releases/download/3.7.14/python-3.7.14-focal-x86_64.tar.xz\n",
         "stack": "ExecError: Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/tmp/renovate/repos/bitbucket-server/mpa/naru\":\"/tmp/renovate/repos/bitbucket-server/mpa/naru\" -v \"/tmp/renovate/cache\":\"/tmp/renovate/cache\" -e PIPENV_CACHE_DIR -e PIP_CACHE_DIR -e BUILDPACK_CACHE_DIR -w \"/tmp/renovate/repos/bitbucket-server/mpa/naru\" docker.io/renovate/sidecar bash -l -c \"install-tool python 3.7.14 && pip install --user pipenv && pipenv lock\"\nYou don't have permission to create /tmp/renovate/cache/containerbase.\ncurl: (23) Failed writing received data to disk/application\nDownload failed: https://github.com/containerbase/python-prebuild/releases/download/3.7.14/python-3.7.14-focal-x86_64.tar.xz\n\n    at ChildProcess.<anonymous> (/usr/src/app/node_modules/renovate/lib/util/exec/common.ts:99:11)\n    at ChildProcess.emit (node:events:525:35)\n    at ChildProcess.emit (node:domain:489:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)"
       }
```

This is my config file:

```      
module.exports = {
          platform: "bitbucket-server",
          username: "renovatebot",
          password: process.env.BITBUCKET_TOKEN,
          endpoint: "https://git.example.com/stash",
          repositories: [
              "mpa/naru"
          ],
          gitAuthor: "Renovate Bot <renovate@example.com>",
          onboarding: true,
          logLevel: "trace",
          dryRun: false,
          autodiscover: false,
          bbUseDefaultReviewers: true,
          bumpVersion: "patch",
          lockFileMaintenance: { "enabled": true },
          renovateFork: true,
          prConcurrentLimit: 1000,
          binarySource: "docker",
          packageRules: [{
              "managers": ["maven"],
              "registryUrls": ["https://nexus.example.com/repository/example-central/"],
              "matchPackagePatterns": ["example","example2"]
          }
          ],
          onboardingConfig: { extends: ["config:base", "group:allNonMajor", ":preserveSemverRanges"] } 
      };

```
And my deployment:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: renovate-bot
  namespace: renovate
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: renovate/renovate:32-slim
              name: renovate-bot
              env: # For illustration purposes, please use secrets.
                - name: BITBUCKET_TOKEN
                  value: 'xxxxx'
                - name: GITHUB_COM_TOKEN
                  value: 'xxxxxxx'
                - name: RENOVATE_BASE_DIR
                  value: '/tmp/renovate/'
                - name: RENOVATE_CONFIG_FILE
                  value: '/opt/renovate/config.js'
                - name: LOG_LEVEL
                  value: debug
                - name: "DOCKER_TLS_VERIFY"
                  value: "1"
                - name: "DOCKER_HOST"
                  value: "tcp://localhost:2376"
                - name: "DOCKER_CERT_PATH"
                  value: "/certs/client/"
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
                - mountPath: "/certs"
                  name: "volume-0"
                  readOnly: false
            - image: "xxxx.dkr.ecr.eu-west-1.amazonaws.com/devops/docker-in-docker:20.10.8-dind"
              imagePullPolicy: "Always"
              name: "dind"
              resources:
                limits: {}
                requests: {}
              securityContext:
                privileged: true
              tty: true
              volumeMounts:
              - mountPath: "/certs"
                name: "volume-0"
                readOnly: false
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
            - emptyDir:
                medium: "Memory"
              name: "volume-0"

```

Do you know how I can solve it?

**Comment by viceice** [comment, marked as answer]
checkout our official helm chart, there is a working dind setup.

you need to mount the tmp volume to the dind container 😉

**Reply by monwolf** [reply]
Thanks It worked, I'll take a look there :)

**Comment by FallenAngel97** [comment]
I have a similar issue, but with Docker Swarm setup. 
I am using [swarm-cronjob](https://crazymax.dev/swarm-cronjob/examples/renovate/) as an example, and I have following config:
```yaml
version: "3.8"

services:
  renovate:
    image: "renovate/renovate:34.77-slim"
    healthcheck:
      disable: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/root/renovate-config.js:/usr/src/app/config.js"
      - "/root/renovateTmp:/tmp:z"
    environment:
      - GITHUB_COM_TOKEN=***
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=*/5 * * * *"
      restart_policy:
        condition: none
 ```
 
 And the logs are:
 ```
     |  WARN: Gradle wrapper is missing the executable bit (repository=F97A/simbackup, branch=renovate/gradle-7.x)
    |  WARN: Error executing gradle wrapper update command. It can be not a critical one though. (repository=F97A/simbackup, branch=renovate/gradle-7.x)
    |        "err": {
    |          "name": "ExecError",
    |          "cmd": "/bin/sh -c docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/tmp/renovate/repos/gitlab/F97A/simbackup\":\"/tmp/renovate/repos/gitlab/F97A/simbackup\" -v \"/tmp/renovate/cache\":\"/tmp/renovate/cache\" -e GRADLE_OPTS -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/tmp/renovate/repos/gitlab/F97A/simbackup\" docker.io/renovate/sidecar bash -l -c \"install-tool java 16.0.2+7 && ./gradlew wrapper --gradle-distribution-url https://services.gradle.org/distributions/gradle-7.6-all.zip\"",
    |          "stderr": "You don't have permission to create /tmp/renovate/cache/containerbase.\ncurl: (23) Failed writing received data to disk/application\nDownload failed: https://github.com/adoptium/temurin16-binaries/releases/download/jdk-16.0.2%2B7/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz\n",
    |          "stdout": "installing v2 tool java v16.0.2+7\n",
    |          "options": {
    |            "cwd": "/tmp/renovate/repos/gitlab/F97A/simbackup",
    |            "encoding": "utf-8",
    |            "env": {
    |              "GRADLE_OPTS": "-Dorg.gradle.parallel=true -Dorg.gradle.configureondemand=true -Dorg.gradle.daemon=false -Dorg.gradle.caching=false",
    |              "HOME": "/home/ubuntu",
    |              "PATH": "/home/ubuntu/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    |              "LC_ALL": "C.UTF-8",
    |              "LANG": "C.UTF-8",
    |              "BUILDPACK_CACHE_DIR": "/tmp/renovate/cache/containerbase",
    |              "CONTAINERBASE_CACHE_DIR": "/tmp/renovate/cache/containerbase"
    |            },
    |            "maxBuffer": 10485760,
    |            "timeout": 900000
    |          },
    |          "exitCode": 1,
    |          "message": "Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/tmp/renovate/repos/gitlab/F97A/simbackup\":\"/tmp/renovate/repos/gitlab/F97A/simbackup\" -v \"/tmp/renovate/cache\":\"/tmp/renovate/cache\" -e GRADLE_OPTS -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/tmp/renovate/repos/gitlab/F97A/simbackup\" docker.io/renovate/sidecar bash -l -c \"install-tool java 16.0.2+7 && ./gradlew wrapper --gradle-distribution-url https://services.gradle.org/distributions/gradle-7.6-all.zip\"\nYou don't have permission to create /tmp/renovate/cache/containerbase.\ncurl: (23) Failed writing received data to disk/application\nDownload failed: https://github.com/adoptium/temurin16-binaries/releases/download/jdk-16.0.2%2B7/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz\n",
    |          "stack": "ExecError: Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/tmp/renovate/repos/gitlab/F97A/simbackup\":\"/tmp/renovate/repos/gitlab/F97A/simbackup\" -v \"/tmp/renovate/cache\":\"/tmp/renovate/cache\" -e GRADLE_OPTS -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/tmp/renovate/repos/gitlab/F97A/simbackup\" docker.io/renovate/sidecar bash -l -c \"install-tool java 16.0.2+7 && ./gradlew wrapper --gradle-distribution-url https://services.gradle.org/distributions/gradle-7.6-all.zip\"\nYou don't have permission to create /tmp/renovate/cache/containerbase.\ncurl: (23) Failed writing received data to disk/application\nDownload failed: https://github.com/adoptium/temurin16-binaries/releases/download/jdk-16.0.2%2B7/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz\n\n    at ChildProcess.<anonymous> (/opt/buildpack/tools/renovate/34.77.1/node_modules/renovate/lib/util/exec/common.ts:99:11)\n    at ChildProcess.emit (node:events:525:35)\n    at ChildProcess.emit (node:domain:489:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)"
    |        }
    |  INFO: Branch updated (repository=F97A/simbackup, branch=renovate/gradle-7.x)
    |        "commitSha": "623e9f0569c5f1ee9ef38c67b65a2ca61fbb9b67"
    |  INFO: Branch updated (repository=F97A/simbackup, branch=renovate/com.google.android.gms-play-services-ads-21.x)
    |        "commitSha": "e726e771cb600ad7c48e4e1b23796c077f5b403c"
    |  INFO: Repository finished (repository=F97A/simbackup)
    |        "cloned": true,
    |        "durationMs": 93973
