### DISCUSSION TITLE
Multiple projects with different Ruby versions

### DISCUSSION THREAD

**Discussion by aedryan** [renovatebot/renovate#17992] [Request Help] [answered]
Hello, I'm having some difficulty running renovate across multiple projects and am seeing some oddities around what I think are the binaries it selects to install.  I have a renovate job running GL CI across a dozen or so projects, some of which use Ruby, some don't  When renovate encounters a Ruby project it manages to update the `Gemfile` but fails the `Gemfile.lock` with a couple notable logs:
```
Gemfile.lock update failed due to an unknown reason
```
And
```
"env": {
    "GEM_HOME": "/home/ubuntu/.gem/ruby/3.1.0",
```
And
```
"message": "Command failed: install-tool bundler 2.3.22\nNo /bin/bundler defined - aborting\n"
```
I have my Ruby version pinned for all projects using a `.ruby-version` file and in the `Gemfile` at 2.7.6 and yet it appears to be running bundler for 3.1.0.  Is there some configuration somewhere to try and get it to install binaries per project instead of what appears to be per CI job?  I had thought about separate my CI jobs up to run separately for Ruby and non-Ruby projects but that doesn't seem like an optimal path forward.

**Comment by rarkins** [comment]
Exactly how are you running Renovate? e.g. are you extending https://gitlab.com/renovate-bot/renovate-runner and using dind mode?

**Reply by aedryan** [reply]
I am indeed using that runner however I am not using DinD mode.  I am using ``/templates/renovate.gitlab-ci.yml`` with `binarySource="install"`

**Reply by rarkins** [reply]
Unfortunately Ruby is one of the languages which doesn't yet support dynamic install. To support separate Ruby versions you'd need to use dind so that it can spin up separate containers per Ruby version

**Reply by aedryan** [reply]
Thanks, I did end up switching over to dind and found that our Ruby projects are installing the correct version of Bundler and the Gemfile.lock updates are coming in as expected.  However now our Node projects are not installing the correct version of npm/node and are not getting package-lock.json updates.  I was under the impression that specifying a node/npm version in package.json's "engines" field would tell even dind which version to install.

I've tried this in dind with docker and install binary source.

**Reply by viceice** [reply]
yes, that should work. do you have a reproduction?

**Reply by aedryan** [reply]
I don't have a downstream public repo to share that would have MRs generated for it by renovate but I can share our Gitlab CI and renovate config:
`.gitlab-ci.yml`
```
include:
  - project: "renovate-bot/renovate-runner"
    file: "/templates/renovate-dind.gitlab-ci.yml"

services:
  - name: docker:20.10.10-dind
    command:
      # Required with 20.10 to disable TLS; previously was assumed when DOCKER_TLS_CERTDIR was empty string
      - "--tls=false"

renovate:
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_VERIFY: ""
  timeout: 150m
  before_script:
    - npm config set @myorg:registry https://gitlab.com/api/v4/packages/npm/
    - npm config set -- '//gitlab.com/api/v4/packages/npm/:_authToken' $SOME_ENV_VAR
    - export RENOVATE_TOKEN=$SOME_ENV_VAR
    - export GOPRIVATE=gitlab.com/myorg/*
    - echo "machine gitlab.com login gitlab-ci-token password ${SOME_ENV_VAR}" > ~/.netrc
    - until docker info; do sleep 1; done
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "push"'
```
`config.js`
```
// List of repo groups to run against
const pathsToMatch = [
  'myorg/path/to/some/specific/project',
  'myorg/path/to/group/projects/*',
];

module.exports = {
  onboarding: false,
  binarySource: 'install',
  detectGlobalManagerConfig: true,
  autodiscover: true,
  autodiscoverFilter: `{${pathsToMatch.join(',')}}`,
}
```
I've tried this without specifying `binarySource`, with it set to `"install"` and `"docker"`.  The result downstream in any Node 14 project is that it doesn't get a `package-lock.json` update.
