### DISCUSSION TITLE
Get Renovate to work with GitLab NPM Package registry using Yarn 3

### DISCUSSION THREAD

**Discussion by bryanjtc** [renovatebot/renovate#18145] [Request Help]
I have several npm packages in my gitlab private registry. I can't update them using renovate. The token I need to authenticate to the registry is showing up on the ci correctly. Renovate shows the added host rule with the token correctly in the log file. I have ran out of ideas to make it work. 
Here are the config files:
yarnrc.yml
```yml
nodeLinker: pnp

npmScopes:
  bthomasorg:
    npmPublishRegistry: "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID:-}/packages/npm/"
    npmRegistryServer: "https://gitlab.com/api/v4/packages/npm/"
    npmAlwaysAuth: true
    npmAuthToken: "${CI_JOB_TOKEN:-}"

npmRegistries:
  //gitlab.com/api/v4/packages/npm/:
    npmAuthToken: "${CI_JOB_TOKEN:-}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.4.cjs

```

renovate.json
```json
{
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
      "config:base"
    ],
    "dependencyDashboard": true,
    "baseBranches": ["main"],
    "prHourlyLimit": 0,
    "packageRules": [
      {
        "matchUpdateTypes": ["major", "minor", "patch", "pin", "digest"],
        "rebaseWhen": "behind-base-branch",
        "automerge": true,
        "platformAutomerge": true,
        "gitLabIgnoreApprovals": true,
        "semanticCommits": true,
        "semanticCommitType": ":arrow_up: build"
      }
    ]
  }
```

config.js
```js
module.exports = {
  hostRules: [
    {
      matchHost: "https://gitlab.com/api/v4/projects/34454635/packages/npm/",
      token: "{{ secrets.GITLAB_TOKEN }}",
      hostType: "npm",
    },
  ],
};
```

gitlab-ci.yml
I only included parts of the file relevant to renovate.
```yml
- project: "renovate-bot/renovate-runner"
    file: "/templates/_common.gitlab-ci.yml"

renovate:
  stage: test
  variables:
    RENOVATE_SECRETS: "{\"GITLAB_TOKEN\": \"${GITLAB_TOKEN}\"}"
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_TLS_CERTDIR: /certs
    DOCKER_CERT_PATH: /certs/client
    CI_RENOVATE_SERVICE: docker:20.10.18-dind@sha256:1be6768d332a4aaed59b344e6525e1701c467c4ef8553d5d18bac086cbd82ef1
    CI_RENOVATE_IMAGE: renovate/renovate:32.217.0-slim@sha256:36655df4b00883518bc3d2d2b0b29d7f3997919d5f7e77dd12a87d324ef4deb2
  image: ${CI_RENOVATE_IMAGE}
  services:
    - name: ${CI_RENOVATE_SERVICE}
      alias: docker
```
