### DISCUSSION TITLE
Usage with ECR pull through cache

### DISCUSSION THREAD

**Discussion by tleuschner** [renovatebot/renovate#18191] [Request Help]
Hey all,

I'd like to use a self-hosted renovate with a private ECR pull through cache but ran into some challenges.
Our images are declared in a kustomize file and renovate picks them up without any issues. The registryUrl is part of the image name. E.g
```
images:
  - name: grafana
    newName: 111111111111.dkr.ecr.my-region.amazonaws.com/pull-through-cache-namespace/bitnami/grafana
    newTag: '9.1.5'
```
Our registry doesn't contain the most recent images/tags, since it is just a cache. Therefore I'd like to check against a public registry if any newer versions or tags are present, but have not been able to configure renovate in a way to do so. I tried the `packageRules` but it doesn't seem to send a request towards the public registry.

My renovate.json looks something like this

```
{
  "repositories": [
    {
      "repository": "my-repsitory/rrepo",
      "enabledManagers": ["kustomize"],
      "baseBranches": ["feature/TEST-123_configure-renovate"],
      "packageRules": [
        {
          "matchDatasources": ["docker"],
          "registryUrls": ["public.ecr.aws"]
        }
      ]
    }
  ]
}
```

Any ideas on how to make renovate pick up the newest images when using this approach?

Regards, Tim
