### DISCUSSION TITLE
Which GitHub Actions events should Renovate trigger?

### DISCUSSION THREAD

**Discussion by aaronadamsCA** [renovatebot/renovate#18516] [Request Help] [answered]
I was really surprised to discover this workflow doesn't run when Renovate opens a new pull request:

```yml
name: Preview
on:
  pull_request:
    branches: [main]
jobs:
  release:
    name: Release
    uses: ./.github/workflows/_release.yml
```

By comparison, it runs fine when a developer opens a PR.

I've tried every search term I can think of, and I can't find any reason for this behaviour. Can anyone shed any light?

Our current Renovate config (minus irrelevant `packageRules`):

```json
{
  "extends": [
    "group:monorepos",
    "group:recommended",
    "workarounds:typesNodeVersioning",
    ":enableVulnerabilityAlertsWithLabel(type: security)",
    ":label(type: dependencies)",
    ":automergeMinor",
    ":dependencyDashboardApproval",
    ":maintainLockFilesWeekly",
    ":pinVersions"
  ],
  "internalChecksFilter": "strict",
  "packageRules": [],
  "platformAutomerge": true,
  "postUpdateOptions": ["yarnDedupeHighest"],
  "stabilityDays": 3
}
```
