### DISCUSSION TITLE
Update Azure devOps git tags reference

### DISCUSSION THREAD

**Discussion by HammerNL89** [renovatebot/renovate#18542] [Request Help]
In our Azure DevOps project we a repo (repo_a) that contains generic ado templates files, that we use in other repo's (e.g. repo_b). We use tags to reference specific versions of these templates in repo_a. So for example:

repo_a: contains ado templates
repo_b: consumes ado templates

repo B azure-pipelines.yaml:
``` 
resources:
  repositories:
  - repository: templates
    name: my_team/repo_a
    type: git
    ref: refs/tags/main_20220829.1
```
We would like to use renovate to bump templates version when a new tag is created in repo_a. 

I found [this topic](https://github.com/renovatebot/renovate/issues/15028), about the default azure-pipeline manager but that doesn't seems to support git (azure-repositories) at the moment, so I probably need a custom config. I did some research but I couldn't find working examples that could guide me a bit.
