### DISCUSSION TITLE
What is a possible alternative for RENOVATE_BASE_DIR?

### DISCUSSION THREAD

**Discussion by jjcaballero** [renovatebot/renovate#18550] [Request Help] [answered]
My company has some policies that disallow to have root user and root file systems writable. Therefore for Kubernetes, we need to use:

```
securityContext:
   privileged:   false
   runAsNonRoot: true
   readOnlyRootFilesystem: true
```

When running Renovate image like that I get errors because /tmp is not writable.

Can I give an alternative value for RENOVATE_BASE_DIR that exists on the official renovate docker image?
