### DISCUSSION TITLE
regexManager: multiple occurences of currentValue

### DISCUSSION THREAD

**Discussion by jbergstroem** [renovatebot/renovate#18588] [Request Help]
Considering a github action that contains something like:
```yaml
  actionlint:
    name: Actionlint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Install Actionlint
        run: curl -Ls "https://github.com/rhysd/actionlint/releases/download/v1.6.21/actionlint_1.6.21_linux_amd64.tar.gz" | sudo tar -x -z -C /usr/local/bin actionlint
      - name: Run Actionlint
        run: |
          echo "::add-matcher::.github/matcher-actionlint.json"
          actionlint -color
```

How would I match this with a `matchStrings` directive? If I only define one `currentValue`, would both version entries get updated as part of a bump? Right now I extrapolate the version into an environment variable but would like to standardize this into one regexMatcher directive instead of doing one per similar entry as above.

..something like:
```json
{
  "fileMatch": [
    "^\\.github/workflows/[^/]+\\.yml$"
  ],
  "matchStrings": [
    "https://github\\.com/(?<depName>.*?)/releases/download/v(?<currentValue>[^/]+)/actionlint_(?<currentValue>.*?)\\.linux_amd64\\.tar\\.gz",
    "https://github\\.com/(?<depName>.*?)/archive/refs/tags/(?<currentValue>.*?)\\.tar\\.gz"
  ],
  "datasourceTemplate": "github-releases"
}
```
