### DISCUSSION TITLE
Exclude specific libraries（regexManagers）

### DISCUSSION THREAD

**Discussion by asa08** [renovatebot/renovate#18595] [Request Help] [answered]
I am using XcodeGen and have the package listed in the project.yml file.
When setting up regexManagers, I want to exclude certain packages from the list.

project.yml
```
packages:
  FloatingPanel:
    url: https://github.com/scenee/FloatingPanel
    version: 1.7.4
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    version: 6.2.4
  OHHTTPStubs:
    url: https://github.com/AliSoftware/OHHTTPStubs
    from: 9.0.0
```

I want to exclude FloatingPanel from the scope.

The renovate.json I am writing
```
  "regexManagers": [
    {
      "fileMatch": [
        "^project.yml$"
      ],
      "matchStrings": [
        "url: https:\\/\\/github\\.com\\/(?<depName>.*?)(\\.git)?\\s*version: (?<currentValue>.*)\\s"
      ],
      "datasourceTemplate": "github-releases"
    }
  ]
```
