### DISCUSSION TITLE
Extract package manager to select tests, e.g. via branchName

### DISCUSSION THREAD

**Discussion by golane-august** [renovatebot/renovate#18607] [Request Help] [answered]
We don't want to run all tests via GitHub Actions, when a dependency is updated. So we need to somehow filter / select when which tests should run depending on the package manager.

Is there a way to do this?

I saw that one can change the branch name, so we could add the manger in here, to determine when a test should be executed. But this is not recommended:
https://docs.renovatebot.com/configuration-options/#branchname

E.g.
`.github/test.yaml`
```
...
jobs:
  test:
    if: ${{ !startsWith(github.head_ref, 'renovate/my-manager/') }}
    run: my-tests-for-this-manager
```
