### DISCUSSION TITLE
Why Renovate won't update Docker NodeJS image version to 18?

### DISCUSSION THREAD

**Discussion by tal-rofe** [renovatebot/renovate#18626] [Request Help] [answered]
I have the following `renovate.json` file configuration:
```json
{
	"$schema": "https://docs.renovatebot.com/renovate-schema.json",
	"extends": ["config:base", ":semanticCommitTypeAll(chore)", ":semanticCommitScopeDisabled"],
	"regexManagers": [
		{
			"fileMatch": ["^Dockerfile$"],
			"matchStrings": ["FROM node:(?<currentValue>.*?)\\n"],
			"depNameTemplate": "node",
			"datasourceTemplate": "node",
			"versioningTemplate": "node"
		}
	],
	"packageRules": [
		{
			"updateTypes": ["minor", "patch"],
			"automerge": true
		},
		{
			"matchPackageNames": ["node"],
			"matchManagers": ["dockerfile"],
			"enabled": false
		}
	],
	"ignoreDeps": ["chalk"],
	"commitMessageAction": "🤖 Update"
}
```

The reason I configured manager for Dockerfile was because Renovate pushed `current` versions instead of `LTS` versions.
However, I don't get a push to `node:18`. Could anyone tell why?

This is my `FROM` statement:
`FROM node:16`

Same for a GitHub workflow file:
```yaml
name: Integration

on:
    pull_request:
        branches: [main]

jobs:
    test_pull_request:
        name: Testing & Checking the code
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
```

I expect to get `node-version` updated to `18`

**Comment by rarkins** [comment, marked as answer]
Are you expecting the `with.node-version` value to be updated? I'm not sure Renovate understands/detects that in the first place. Check your `packageFiles with updates` log message.

**Reply by tal-rofe** [reply]
Ok, what about the `Dockerfile` issue

**Reply by rarkins** [reply]
It you're using a regular node image, e.g. `node:16.10.0` then you can apply `node` versioning which understands LTS. However if you're using e.g. `node:16.10.0-alpine` then `node` versioning doesn't understand these Docker-specific suffixes and you can also get v19 suggested. You can use a package rule with `allowedVersions=<19` to control it manually

**Reply by tal-rofe** [reply]
@rarkins 

So will this work?
```json
	"regexManagers": [
		{
			"fileMatch": ["^(\\.github\\/workflows)\\/[^/]+\\.yaml$"],
			"matchStrings": ["node-version: (?<currentValue>.*?)"],
			"depNameTemplate": "node",
			"datasourceTemplate": "node",
			"versioningTemplate": "node"
		}
	],
```

For this file:
```yaml
name: Integration

on:
    pull_request:
        branches: [main]

jobs:
    call_pnpm_caching_workflow:
        uses: ./.github/workflows/pnpm-caching.yaml
        with:
            runner: ubuntu-latest
            node-version: 18
            pnpm-version: 7.14.0
```

Will it update the `node-version`?
