### DISCUSSION TITLE
Invalid regex manager to update pnpm

### DISCUSSION THREAD

**Discussion by tal-rofe** [renovatebot/renovate#18657] [Request Help] [answered]
I have set the following `renovate.json` configuration file:

```json
{
	"$schema": "https://docs.renovatebot.com/renovate-schema.json",
	"extends": ["config:base", ":semanticCommitTypeAll(chore)", ":semanticCommitScopeDisabled"],
	"regexManagers": [
		{
			"fileMatch": ["^(\\.github\\/workflows)\\/[^/]+\\.yaml$"],
			"matchStrings": ["node-version: (?<currentValue>.*?)"],
			"depNameTemplate": "node",
			"datasourceTemplate": "node",
			"versioningTemplate": "node"
		},
		{
			"fileMatch": ["^(\\.github\\/workflows)\\/[^/]+\\.yaml$"],
			"matchStrings": ["pnpm-version: (?<currentValue>.*?)"],
			"depNameTemplate": "pnpm",
			"datasourceTemplate": "npm"
		},
		{
			"fileMatch": ["^docker\\/Dockerfile\\..*$"],
			"matchStrings": ["FROM node:(?<currentValue>.*?)"],
			"depNameTemplate": "node",
			"datasourceTemplate": "node",
			"versioningTemplate": "node"
		}
	],
	"packageRules": [
		{
			"updateTypes": ["minor", "patch"],
			"automerge": true
		},
		{
			"matchPackageNames": ["node"],
			"matchManagers": ["dockerfile"],
			"enabled": false
		}
	],
	"ignoreDeps": ["chalk"],
	"commitMessageAction": "🤖 Update"
}
```

If you look the `regexManagers`, in the second object you can see I've configured Renovate to auto update `pnpm` version within GitHub Action files.

For example here, file is `./.github/workflows/integrate.yaml`:
```yaml
name: Integration

on:
    pull_request:
        branches: [main]

jobs:
    call_pnpm_caching_workflow:
        name: Set pnpm caching
        uses: ./.github/workflows/pnpm-caching.yaml
        with:
            runner: ubuntu-latest
            node-version: 18
            pnpm-version: 7.14.0
```

But yet, after `pnpm` should update to version `7.14.1`, I did get Pull Request from Renovate, but if I enter the `file changes` I don't see Renovate tries to update this entry: `pnpm-version: 7.14.0` But I don't understand where my Renovate configuration file is invalid.

Reproduce: https://github.com/tal-rofe/renovate-pnpm-issue
