### DISCUSSION TITLE
Gitea+Drone: Why does self-hosted Renovate open and immediately autoclose a PR?

### DISCUSSION THREAD

**Discussion by loganmarchione** [renovatebot/renovate#18666] [Request Help] [answered]
I'm running the Renovate Docker image as a Drone step in my self-hosted Gitea+Drone setup. My Gitea user is called `logan`. Renovate has its own Gitea user called `renovate` that has access `logan`'s repos and can open PRs. When Renovate runs, it opens and immediately autocloses PRs. Why is this? What am I missing?

Below is how I'm running Renovate in my Drone pipeline. This `.drone.yml` file runs via a Drone cronjob once a week.

```
---
kind: pipeline
type: docker
name: renovate

trigger:
  event:
    - cron
    - push
    - custom

environment:
  LOG_LEVEL: debug

steps:
  - name: renovate - validate config
    image: renovate/renovate:33.2.0
    # https://github.com/renovatebot/renovate/discussions/15049
    commands:
      - unset GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL
      - renovate-config-validator

  - name: renovate
    image: renovate/renovate:33.2.0
    # https://github.com/renovatebot/renovate/discussions/15049
    commands:
      - unset GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL
      - renovate

    environment:
      RENOVATE_TOKEN:
        from_secret: RENOVATE_TOKEN
      GITHUB_COM_TOKEN:
        from_secret: GITHUB_COM_TOKEN

  - name: notify on failure
    image: drillster/drone-email
    settings:
      host: postfixrelay
      port: 25
      from: donotreply@mydomain.com
      from.name: "[Alert from Drone CI/CD]"
    when:
      status:
        - failure
```

Below is the `config.js` for my `renovate` user (it's in the same directory as the above file).

```
module.exports = {
  platform: 'gitea',
  endpoint: 'https://git.internal.mydomain.com/api/v1/',
  gitAuthor: 'Renovate Bot <renovate@mydomain.com>',
  username: 'renovate',
  autodiscover: true,
  onboardingConfig: {
    $schema: 'https://docs.renovatebot.com/renovate-schema.json',
    extends: ['config:base']
  },
  optimizeForDisabled: true,
  persistRepoData: true,
  repositories: [
    "logan/docker",
    "logan/terraform",
    "logan/ansible"
  ]
}
```

Here is an example of a PR where Renovate successfully identified an update and opened the PR, but then closed it.
![Screenshot 2022-10-31 at 01-40-24 Update jellyfin_jellyfin Docker tag to v10 8 6 - autoclosed](https://user-images.githubusercontent.com/4955337/198914469-8630d62e-a944-489b-8c7c-b36b50817777.png)

Searching in the logs of the weekly cron run via Drone for the word `jellyfin`, I've identified some lines about Jellyfin.

```
DEBUG: 12 flattened updates found: linuxserver/code-server, mongo, opensearchproject/opensearch, opensearchproject/opensearch, jellyfin/jellyfin, influxdb, grafana/grafana-oss, grafana/grafana-oss, ryansch/unifi-rpi, python, python, python (repository=logan/docker)
...
...
...
           {
             "packageFile": "docker_app_host/jellyfin/docker-compose.yml",
             "deps": [
               {
                 "depName": "jellyfin/jellyfin",
                 "currentValue": "10.8.5",
                 "replaceString": "jellyfin/jellyfin:10.8.5",
                 "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "depIndex": 0,
                 "updates": [
                   {
                     "bucket": "non-major",
                     "newVersion": "10.8.6",
                     "newValue": "10.8.6",
                     "newMajor": 10,
                     "newMinor": 8,
                     "updateType": "patch",
                     "branchName": "renovate/jellyfin-jellyfin-10-x"
                   }
                 ],
                 "warnings": [],
                 "versioning": "docker",
                 "currentVersion": "10.8.5",
                 "isSingleVersion": true,
                 "fixedVersion": "10.8.5"
               }
             ]
           },
...
...
...
 INFO: PR created (repository=logan/docker, branch=renovate/jellyfin-jellyfin-10-x)
       "pr": 34,
       "prTitle": "Update jellyfin/jellyfin Docker tag to v10.8.6"
DEBUG: addParticipants(pr=34) (repository=logan/docker, branch=renovate/jellyfin-jellyfin-10-x)
DEBUG: Created Pull Request #34 (repository=logan/docker, branch=renovate/jellyfin-jellyfin-10-x)
DEBUG: PR is not configured for automerge (repository=logan/docker, branch=renovate/jellyfin-jellyfin-10-x)
DEBUG: setBranchCommit() (repository=logan/docker, branch=renovate/jellyfin-jellyfin-10-x)
...
...
...
DEBUG: getBranchPr(renovate/jellyfin-jellyfin-10-x) (repository=logan/docker)
DEBUG: findPr(renovate/jellyfin-jellyfin-10-x, undefined, open) (repository=logan/docker)
DEBUG: Found PR #34 (repository=logan/docker)
```

The only two it is autoclosing are not the PR 34 from above. What am I missing here?

```
 INFO: Autoclosing PR (repository=logan/docker)
       "branchName": "renovate/opensearchproject-opensearch-1.x",
       "prNo": 32,
       "prTitle": "Update opensearchproject/opensearch Docker tag to v1.3.6"
DEBUG: Deleted remote branch (repository=logan/docker)
       "branchName": "renovate/opensearchproject-opensearch-1.x"
DEBUG: No local branch to delete (repository=logan/docker)
       "branchName": "renovate/opensearchproject-opensearch-1.x"
DEBUG: findPr(renovate/python-3.x, undefined, open) (repository=logan/docker)
DEBUG: Found PR #33 (repository=logan/docker)
DEBUG: branch.isModified(): using git to calculate (repository=logan/docker)
DEBUG: branch.isModified() = false (repository=logan/docker)
DEBUG: setCachedModifiedResult(): Branch cache not present (repository=logan/docker)
 INFO: Autoclosing PR (repository=logan/docker)
       "branchName": "renovate/python-3.x",
       "prNo": 33,
       "prTitle": "Update python Docker tag to v3.11"
DEBUG: Deleted remote branch (repository=logan/docker)
       "branchName": "renovate/python-3.x"
DEBUG: No local branch to delete (repository=logan/docker)
       "branchName": "renovate/python-3.x"
DEBUG: ensureIssueClosing(Action Required: Fix Renovate Configuration) 
```
