### DISCUSSION TITLE
Unable to modify versions in plugins.yml file

### DISCUSSION THREAD

**Discussion by izorster** [renovatebot/renovate#18701] [Request Help]
`renovate command line:`
`LOG_LEVEL=debug renovate --platform "gitlab" --endpoint https://gitlab.mygitlab.com/api/v4 --token $TOKEN sandbox/k_reno_k --autodiscover-filter=group/project --onboarding=false > RENO_LOG
`
```
% cat renovate.json 
{
 "regexManagers": [
     {
         "fileMatch": "plugins/kaniko/plugin.yaml",
         "matchStrings": [
         "# renovate: depName=(?<depName>.*?)( versioning=(?<versioning>.*?))?( registryUrl=(?<registryUrl>.*?))?\\s.*?version: (?<currentValue>.*)\\s"
         ],
         "datasourceTemplate": "docker"
    }
  ]
}
```

```
% more config.json 
module.exports = {
  "hostRules": [
    {
      "hostType": "docker",
      "matchHost": _"registry-myregistryname",_
      "username": "process.env.CI_REGISTRY_USER",
      "password": "process.env.CI_REGISTRY_PASSWORD"
    }
  ]
}

```
renovate log file:
[RENO_LOG.gz](https://github.com/renovatebot/renovate/files/9913197/RENO_LOG.gz)

I cannot seem to find a reasonable resource type to modify versions in my plugins.yml file:

```
presets:
  - id: kaniko-local
    name: Local Dockerfile
    description: Build a Dockerfile from disk
    steps:
      - id: build-image
        image: registry-mygitlab.com/sandbox/k_reno_k
        # renovate: depName=sandbox/k_reno_k versioning=semver registryUrl=https://mygitlab.com
        version: v1.9.0-debug
        command:
          - sh
        script: |
          set -euo pipefail
```
