### DISCUSSION TITLE
unpublishSafe Status Check

### DISCUSSION THREAD

**Discussion by adam-moss** [renovatebot/renovate#18720] [Request Help]
Currently the `npm` preset `npm:unpublishSafe` is

```json
"npm": {
    "stabilityDays": 3
}
```

however as per the [docs](https://docs.renovatebot.com/configuration-options/#suppress-branchpr-creation-for-x-days) if you include `internalChecksFilter: strict` this delays merge requests being created until the time limit is reached.

If `internalChecksFilter` isn't set to `strict` then (in GitLab) you end up with the following:

<img width="1038" alt="Screenshot 2022-11-02 at 15 17 07" src="https://user-images.githubusercontent.com/2951486/199533829-86274daa-b317-4f7d-95f9-873567a8a4e2.png">

I.e. the MR is raised and the pipeline has failed, but the `stabilityDays` check is triggered and in this example passes.  This then leads to a scenario where the latest pipeline for the merge request is effectively green and so things like `automerge` and human errors can occur resulting in an actual merge taking place.

This then leaves the code base "broken".

Is there a rationale for not including `internalChecksFilter: strict` in the preset or would you be amenable to a merge request that adds it?

Thanks!

**Comment by viceice** [comment]
strict is the new default value since renovate v33. so you probably need to update.

**Reply by adam-moss** [reply]
I'm actually running v34

```yaml
default:
  image:
    name: renovate/renovate:34@sha256:c5a4b4ee7ac938197d31fed2658c5d07ce0264963b55df81646140733d9c4439
    entrypoint: [""]
```

**Reply by rarkins** [reply]
It should be defaulting to strict then. Can you verify that? You should see special log messages when it's strict

**Reply by adam-moss** [reply]
Can't see anything jumping out at me in the logs I'm afraid

**Reply by rarkins** [reply]
Actually I may have remembered wrong. It was the `is pending status checks` messages I was thinking of. But anyway, you should have internalChecksFilter=strict by default, so your original question is kind of incorrect. If you *don't* have internalChecksFilter=strict by default, it sounds like a bug

**Reply by viceice** [reply]
> I'm actually running v34
> 
> ```yaml
> default:
>   image:
>     name: renovate/renovate:34@sha256:c5a4b4ee7ac938197d31fed2658c5d07ce0264963b55df81646140733d9c4439
>     entrypoint: [""]
> ```

why do you override our entry point? shouldn't necessary.

**Reply by adam-moss** [reply]
I'm running renovate across ~12k repos every night, so have to dynamically generate _a lot_ of pipelines to get the performance at scale, and apply additional config to use our cacheing proxies etc

```yaml
.renovate:
  variables:
    RENOVATE_CONFIG_FILE: "$CI_PROJECT_DIR/config.json"
    LOG_FORMAT: "json"
  script:
    - mkdir ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_<redact>
    - chmod 600 ~/.ssh/id_<redact>
    - npm config set registry "https://<redact>"
    - pip3 config set --user global.index-url https://<redact>
    - poetry config <redact>
    - echo "Renovating $REPOSITORY_LIST"
    - LOG_LEVEL=${LOG_LEVEL:-fatal} renovate $DRY_RUN $ADDITIONAL_CONFIG $REPOSITORY_LIST
  artifacts:
    paths:
      - renovate-log.json
    when: on_failure
    expire_in: 18 hours
```
