### DISCUSSION TITLE
Setup gitlab renovate with self-signed certs

### DISCUSSION THREAD

**Discussion by Renovate-bot-slashwhy** [renovatebot/renovate#18733] [Request Help]
Running the recommended gitlab renovate via https://gitlab.com/renovate-bot/renovate-runner we seem to get failures due to our self signed cert.

But that `renovate-runner` config doesn't seem to support adding in self-signed certs? At least I can't find docs for that. So am I really stuck having to create our own docker image now? Like mentioned in https://docs.renovatebot.com/examples/self-hosting/#self-signed-tlsssl-certificates but that seems incompatible with the above approach.

For reference https://gitlab.com/renovate-bot/renovate-runner/-/issues/65#note_1158828500

**Comment by rarkins** [comment]
Running [update-ca-certificates](https://manpages.ubuntu.com/manpages/xenial/man8/update-ca-certificates.8.html) requires `sudo` rights so that's why you likely can't do it at runtime. I don't think this is any limitation or decision by us at Renovate but if you have ideas for how it could be done at runtime, go ahead.

**Reply by viceice** [reply]
Maybe we should link to this docs from renovate bot or add that to the official docs
https://github.com/containerbase/base/blob/main/docs/custom-root-ca.md

**Comment by viceice** [comment]
Try setting `SSL_CERT_FILE` and `NODE_EXTRA_CA_CERTS` via env

**Reply by razzeee** [reply]
Setting it like this doesn't seem to help:

```yml
include:
    - project: 'renovate-runner'
      file: '/templates/renovate-dind.gitlab-ci.yml'

variables:
  NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/ca.crt
  SSL_CERT_FILE: /usr/local/share/ca-certificates/ca.crt
```

**Reply by viceice** [reply]
yes, custom certs currently don't work with dind (renovate docker mode), so you probably need to sue the full image for now.

Most tools are now also installed there dynamically

**Reply by razzeee** [reply]
Okay, I've moved everything to our own docker image now, but somehow it does not seem to pickup the gitlab env vars.

Tried to reuse most of the gitlab repo, but even the logging doesn't seem to work, probably cause I'm calling docker and am not in the container, when I enter the script tag?

```yaml
variables:
  RENOVATE_BASE_DIR: $CI_PROJECT_DIR/renovate
  RENOVATE_ENDPOINT: $CI_API_V4_URL
  RENOVATE_PLATFORM: gitlab
  RENOVATE_ONBOARDING_CONFIG: '{"$$schema": "https://docs.renovatebot.com/renovate-schema.json", "extends": ["config:base"] }'
  RENOVATE_OPTIMIZE_FOR_DISABLED: "true"
  RENOVATE_REPOSITORY_CACHE: "enabled"
  RENOVATE_REQUIRE_CONFIG: "required"
  RENOVATE_ONBOARDING: "false"
  RENOVATE_IGNORE_PR_AUTHOR: "true"
  RENOVATE_EXTENDS: "github>whitesource/merge-confidence:beta"
  RENOVATE_LOG_FILE: renovate-log.ndjson
  RENOVATE_LOG_FILE_LEVEL: debug
  LOG_LEVEL: info

default:
  cache:
    key: ${CI_COMMIT_REF_SLUG}-renovate
    paths:
      - renovate/cache/renovate/repository/

renovate:
  stage: deploy
  resource_group: production
  variables:
    RENOVATE_TOKEN: $RENOVATE_TOKEN
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  script:
    - cp ${SOSO_CA} ${CI_PROJECT_DIR}/soso-ca.crt
    - docker build -t slashwhy/renovate .
    - >
      docker run slashwhy/renovate $RENOVATE_EXTRA_FLAGS
  artifacts:
    when: always
    expire_in: 1d
    paths:
      - "$RENOVATE_LOG_FILE"

```

**Reply by viceice** [reply]
if you use `docker run`, you need to manually pass all env values

```sh
> docker run --rm -e RENOVATE_BASE_DIR -e ...
```

**Reply by razzeee** [reply]
Hrm, with:

`docker run --rm -e RENOVATE_BASE_DIR -e RENOVATE_ENDPOINT -e RENOVATE_PLATFORM -e RENOVATE_ONBOARDING_CONFIG -e RENOVATE_OPTIMIZE_FOR_DISABLED -e RENOVATE_REPOSITORY_CACHE -e RENOVATE_REQUIRE_CONFIG -e RENOVATE_ONBOARDING -e RENOVATE_IGNORE_PR_AUTHOR -e RENOVATE_EXTENDS -e RENOVATE_TOKEN slashwhy/renovate $RENOVATE_EXTRA_FLAGS`


I end up getting:

```

FATAL: Fatal error: EACCES: permission denied, mkdir '/builds'
       "err": {
         "errno": -13,
         "code": "EACCES",
         "syscall": "mkdir",
         "path": "/builds",
         "message": "EACCES: permission denied, mkdir '/builds'",
         "stack": "Error: EACCES: permission denied, mkdir '/builds'"
       }
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "logContext": "6FIcyzZmIdt_t2QZM4BTL",
           "err": {
             "errno": -13,
             "code": "EACCES",
             "syscall": "mkdir",
             "path": "/builds",
             "message": "EACCES: permission denied, mkdir '/builds'",
             "stack": "Error: EACCES: permission denied, mkdir '/builds'"
           },
           "msg": "Fatal error: EACCES: permission denied, mkdir '/builds'"
         }
       ]
```

When I include the log file env vars, I error earlier, due to it not being able to find the logfile defined in the env. Might be the same cause, but I can't find any mention of a build dir in the Dockerfile or the gitlab repo.

**Reply by viceice** [reply]
remove base dir config

**Reply by razzeee** [reply]
That seems to work, if I also remove the RENOVATE_LOG_FILE and RENOVATE_LOG_FILE_LEVEL vars

**Reply by razzeee** [reply]
I can't figure out how to get the cache and the logfile to work, but other then that it seems fine. I can probably live with that.

For future reference
```yaml
variables:
  RENOVATE_ENDPOINT: $CI_API_V4_URL
  RENOVATE_PLATFORM: gitlab
  RENOVATE_ONBOARDING_CONFIG: '{"$$schema": "https://docs.renovatebot.com/renovate-schema.json", "extends": ["config:base"] }'
  RENOVATE_OPTIMIZE_FOR_DISABLED: "true"
  RENOVATE_REPOSITORY_CACHE: "enabled"
  RENOVATE_IGNORE_PR_AUTHOR: "true"
  RENOVATE_EXTENDS: "github>whitesource/merge-confidence:beta"
  RENOVATE_LOG_FILE: /tmp/renovate/renovate-log.ndjson
  RENOVATE_LOG_FILE_LEVEL: debug
  LOG_LEVEL: info
  RENOVATE_TOKEN: $RENOVATE_TOKEN
  GITHUB_COM_TOKEN: $GITHUB_COM_TOKEN

default:
  cache:
    key: ${CI_COMMIT_REF_SLUG}-renovate
    paths:
      - /tmp/renovate/repository/

renovate:
  stage: deploy
  resource_group: production
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  script:
    - cp ${SOSO_CA} ${CI_PROJECT_DIR}/soso-ca.crt
    - docker build -t slashwhy/renovate .
    - >
      docker run --rm
      -e RENOVATE_ENDPOINT
      -e RENOVATE_PLATFORM
      -e RENOVATE_ONBOARDING_CONFIG
      -e RENOVATE_OPTIMIZE_FOR_DISABLED
      -e RENOVATE_REPOSITORY_CACHE
      -e RENOVATE_IGNORE_PR_AUTHOR
      -e RENOVATE_EXTENDS
      -e RENOVATE_LOG_FILE
      -e RENOVATE_LOG_FILE_LEVEL
      -e RENOVATE_TOKEN
      -e GITHUB_COM_TOKEN
      slashwhy/renovate $RENOVATE_EXTRA_FLAGS
  artifacts:
    when: always
    expire_in: 1d
    paths:
      - "$RENOVATE_LOG_FILE"

```
