### DISCUSSION TITLE
Extracting version from a github tag.

### DISCUSSION THREAD

**Discussion by mikhail-khodorovskiy** [renovatebot/renovate#18952] [Request Help]
I am trying to make Renovate update lambda runtime version in a custom dsl that looks like that 

```
lambda_functions:
    - function_name: print_event
      handler: print_event.lambda_handler
      # renovate: datasource=github-tags depName=lambda_runtime_python packageName=our-org/spec-validator extractVersion=^lambda_runtime_python(?<version>.+)$
      runtime: python3.8
      timeout: 300
      memory: 128
      triggers:
        - queue_name: notification-queue
```

with the renovate config file:

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "local>our-org/renovate-config"
  ],
  "schedule": ["at any time"],
  "hostRules": [
    {
      "hostType": "github",
      "matchHost": "https://github.com/our-org",
      "authType": "Token-Only",
      "encrypted": {
        "token": "redacted"      
      }
    }
  ],
  "regexManagers": [
    {
      "fileMatch": ["^.janus/deploy\.yml$"],
      "matchStrings": [
        "# renovate: datasource=(?<datasource>.+?) depName=(?<depName>.+?) packageName=(?<packageName>.+?)( extractVersion=(?<extractVersion>.+?))?( registryUrl=(?<registryUrl>.+?))?\\s.*?runtime:\\spython(?<currentValue>.*)\\s"
      ],
      "extractVersionTemplate": "{{#if extractVersion}}{{{extractVersion}}}{{else}}^lambda_runtime_python?(?<version>.+)${{/if}}",
      "versioningTemplate": "regex:(?<major>\d+)\.(?<minor>\d+)"
    }
  ]
}

```
the private org repository our-org/spec-validator has the following tags:

lambda_runtime_python3.8
lambda_runtime_python3.9

I would like Renovate to propose a pr to upgrade "python3.8" to "python3.9" in the lambda function spec.

The error I currently get with the setup:
```
"regex": [
      {
        "deps": [
          {
            "currentValue": "3.8",
            "datasource": "github-tags",
            "depIndex": 0,
            "depName": "lambda_runtime_python",
            "extractVersion": "^lambda_runtime_python(?<version>.+)$",
            "packageName": "our-org/spec-validator",
            "replaceString": "# renovate: datasource=github-tags depName=lambda_runtime_python packageName=our-org/spec-validator extractVersion=^lambda_runtime_python(?<version>.+)$\n      runtime: python3.8\n",
            "skipReason": "invalid-value",
            "versioning": "regex:(?<major>d+).(?<minor>d+)",
            "warnings": [],
            "updates": []
          }
        ],
        "extractVersionTemplate": "{{#if extractVersion}}{{{extractVersion}}}{{else}}^lambda_runtime_python?(?<version>.+)${{/if}}",
        "matchStrings": [
          "# renovate: datasource=(?<datasource>.+?) depName=(?<depName>.+?) packageName=(?<packageName>.+?)( extractVersion=(?<extractVersion>.+?))?( registryUrl=(?<registryUrl>.+?))?\\s.*?runtime:\\spython(?<currentValue>.*)\\s"
        ],
        "packageFile": ".janus/deploy.yml",
        "versioningTemplate": "regex:(?<major>d+).(?<minor>d+)"
      }
    ]
  }
}
```

Any help is appreciated!!
