### DISCUSSION TITLE
Can Renovate GitHub App work with SSH based repo access?

### DISCUSSION THREAD

**Discussion by okiedork** [renovatebot/renovate#18984] [Request Help] [answered]
Hello. I did find some discussions related to *self-hosted* Renovate, but I'm trying to use the GitHub App version.

My Ansible Galaxy `requirements.yaml` file has this content:

```yaml
---

roles:
  - src: git@github.com:org/roles-repo.git
    scm: git
    version: rolename-v0.1.2
    name: rolename

  - src: git@github.com:org/roles-repo.git
    scm: git
    version: otherrole-v0.1.0
    name: otherrole
```

The roles are stored as branches in the same repo, which is accessed via SSH.

The Renovate config file has this:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends":
  [
    "config:base"
  ],
  "hostRules":
  [
    {
      "encrypted":
      {
        "token": "TOKEN"
      },
      "matchHost": "https://api.github.com/repos/org/roles-repo"
    }
  ],
  "packageRules":
  [
    {
      "matchDepTypes":
      [
        "role"
      ],
      "matchManagers":
      [
        "ansible-galaxy"
      ],
      "versioning": "regex:^(\\w+-)+v(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)$"
    }
  ]
}
```

The regex is working, but Renovate app can't access the repository because it has no SSH key and there is no option to provide one (checked in the not-self-hosted [docs](https://docs.renovatebot.com/configuration-options/)).

I've also tried to add `registryUrls` to the `packageRules`, but it throws a warning:

```
WARN: Custom registries are not allowed for this datasource and will be ignored
{
  "datasource": "git-tags",
  "registryUrls": [
    "https://github.com/org/roles-repo"
  ],
  "defaultRegistryUrls": null
}
```

Can you please confirm that I'll need to self-host it in order to use this functionality?
