### DISCUSSION TITLE
Golang Support for private pseudo host

### DISCUSSION THREAD

**Discussion by Okeanos** [renovatebot/renovate#18985] [Request Help]
I am currently trying to setup `gomod` based Go projects correctly with Renovate using the following project base setup:

`go.mod`:

```
module go.example.org/module-name

go 1.19

require (
	go.example.org/other-module.git v1.6.16
	go.example.org/another-module.git v1.6.2
	go.opentelemetry.io/otel v1.10.0
)
```

`go env`:

```shell
GONOPROXY='*.example.org'
GONOSUMDB='*.example.org'
GOPRIVATE='*.example.org'
```

`.gitconfig`:

```
[url "https://OAuth:<PAT>@dev.azure.com/ORG/SOME%20PROJECT/_git/"]
        insteadOf = https://go.example.org/
```

We have a pseudo-host (name doesn't exist) called `go.example.org` and use Git `insteadOf` syntax to automagically rewrite it to the actual repository URL. This works perfectly fine everywhere (locally, in CI pipelines, …) and there isn't much else we can do because of the way the remote repository structure is set up: the project name contains a space and Go itself cannot handle that and there is NO way we can change that.
Now, I cannot for the life of me get this to work with Renovate Bot.

The current approach is using in the GitHub pipeline:

```shell
RENOVATE_CUSTOM_ENV_VARIABLES='{ "GONOPROXY": "*.example.org","GONOSUMDB": "*.example.org","GOPRIVATE": "*.example.org","GIT_CONFIG_KEY_0":"url.https://OAuth:${{ secrets.AZURE_GO_REPOS }}@dev.azure.com/ORG/SOME%20PROJECT/_git/.insteadOf", "GIT_CONFIG_VALUE_0":"https://go.example.org/", "GIT_CONFIG_COUNT": 1 }' \
  RENOVATE_REPOSITORIES="ORG/repo-name" \
  npx renovate
```

But this doesn't work 🤷‍♂️ . Any pointers would be very much appreciated. The following [discussion#14347](https://github.com/renovatebot/renovate/discussions/14347) may be related but is still different because there is no wholesale rewrite of the host involved.

The log output is:

```
Command failed: go get -d -t ./...
go: go.example.org/other-module.git@v1.6.16: reading go.example.org/other-module.git/go.mod at revision v1.6.16: git ls-remote -q origin in /tmp/renovate/cache/others/go/pkg/mod/cache/vcs/7e437c014b694177bd24002421d994d153b5dc08d08ebc51cde7980ea0c935e6: exit status 128:
	fatal: unable to look up go.example.org (port 9418) (Name or service not known)
```

As you can see, the `insteadOf` rewrite isn't actually applied.

**Comment by rarkins** [comment]
How exactly are you running Renovate? Eg which image and binarySource setting? Please include the debug messages leading up to that go get command

**Reply by Okeanos** [reply]
Renovate is running in GitHub Actions with the following setup:

```json
{
  "name": "renovate",
  "version": "1.0.0",
  "description": "Renovate Dependency Bot",
  "main": "index.js",
  "repository": "dev.azure.com/ORG/SOME%20PROJECT/_git/renovate",
  "author": "Nikolas Grottendieck <nikolas.grottendieck@example.org>",
  "private": true,
  "dependencies": {
    "renovate": "34.27.3"
  }
}
```

```yaml
jobs:
  renovate:
    name: Renovate
    runs-on: [ 'ubuntu' ]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions' # 18
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: 'Setup Access to NPM Artifact Feeds'
        run: |
         echo "" # this step here creates `.npmrc` & `.yarnrc.yml` files
      - name: 'Install Tools'
        run: |
          npm install -g yarn pnpm
          npm update -g npm
          npm ci
      - name: Renovate
        run: |
          # repositories.txt is a CSV list of all repos to check
          RENOVATE_REPOSITORIES=$(< repositories.txt) npx renovate
        env:
          LOG_LEVEL: debug
          GITHUB_COM_TOKEN: ${{ secrets.GIT_GITHUB_PAT }} 
          RENOVATE_TOKEN: ${{ secrets. RENOVATE_TOKEN }} 
          RENOVATE_CUSTOM_ENV_VARIABLES='{ "GONOPROXY": "*.example.org","GONOSUMDB": "*.example.org","GOPRIVATE": "*.example.org","GIT_CONFIG_KEY_0":"url.https://OAuth:${{ secrets.AZURE_GO_REPOS }}@dev.azure.com/ORG/SOME%20PROJECT/_git/.insteadOf", "GIT_CONFIG_VALUE_0":"https://go.example.org/", "GIT_CONFIG_COUNT": 1 }'
          AZURE_GO_REPOS: ${{ secrets.AZURE_GO_REPOS }}
          AZURE_JAVA_FEED: ${{ secrets.AZURE_JAVA_FEED }}
          AZURE_NPM_FEED: ${{ secrets.AZURE_NPM_FEED }}
```

```js
module.exports = {
  endpoint: 'https://git.example.org/api/v3/',
  platform: 'github',
  updateInternalDeps: true,
  hostRules: [
    {
      hostType: 'maven',
      matchHost: 'https://pkgs.dev.azure.com/ORG/uuid/_packaging/SOME_FEED/maven/v1',
      username: 'ORG',
      password: process.env.AZURE_JAVA_FEED,
    },
    {
      hostType: 'npm',
      matchHost: 'https://pkgs.dev.azure.com/ANOTHER-ORG/_packaging/SOME-NAME/npm/registry/',
      username: 'ANOTHER-ORG',
      password: process.env.AZURE_NPM_FEED,
    },
  ],
}
```

Logfile attached: 
[2022-11-21-renovate.log](https://github.com/renovatebot/renovate/files/10054574/2022-11-21-renovate.log)
