### DISCUSSION TITLE
Allow overriding depName with Kubernetes annotations in Flux manager resources

### DISCUSSION THREAD

**Discussion by onedr0p** [renovatebot/renovate#19039] [Suggest an Idea]
Tagging @5cat @anthr76 @bjw-s @danports

I am wondering if it would be a good idea to use the standard depName of the `GitRepository`, `HelmRepository` and `OCIRespository` but then use a annotation to override the `depName` in cases where you want the name to be different.

For example say you have the following `GitRepository` manifest:

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-installation
  namespace: flux-system
spec:
  url: https://github.com/fluxcd/flux2
  ref:
    tag: v0.36.0
  ignore: |
    # exclude all
    /*
    # path to manifests
    !/manifests
---
```

The current behavior is to use the `.metadata.name` as the `depName`, so in the above example `flux-installation` is the `depName`. See [this](https://github.com/onedr0p/home-ops/pull/4246) example.

I would suggest that it would be by default set to the `GitRepository` URL, e.g. `fluxcd/flux2` instead. See [this](https://github.com/onedr0p/home-ops/pull/4111) example of previous behavior with using a custom regex matcher.

In cases where the above is not ideal.  What I would suggest is that if people want a custom `depName` there could be an annotation on the resource under `metadata` e.g.

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-installation
  namespace: flux-system
  annotations:
    flux.manager.mend.io/customDepName: "flux-installation"
spec:
  url: https://github.com/fluxcd/flux2
  ref:
    tag: v0.36.0
  ignore: |
    # exclude all
    /*
    # path to manifests
    !/manifests
```

These annotations could be supported on any repository type (Git, Helm, OCI)

Would that make sense?

**Comment by 5cat** [comment]
I like the idea since I can see it being an issue when we have the same `metadata.name` across different namespaces, but what about other kubernetes objects that are not managed by flux such as the helm manager or the kustomize manager. If we applied this metadata annotation for flux i dont see a reason why to not apply it to the rest of the managers, so If we found a solution here it might be wise to apply it to the rest of the manager.

Regarding making `GitRepository` depName as the URL, the same URL could exist in two separate namespaces. 
What do you think about using `{metadata.namesapce}/{metadata.name}` format to name `depName`s? This way we avoided having dependency collusion in renovate; This way we derive the uniqueness from kubernetes since it guarantees that no two objects of the same kind in the same space exists. Of course I dont mind adding custom annotation to override the `{metadata.namespace}/{metadata.name}` depName.

Let me know your thoughts on this idea.

**Reply by onedr0p** [reply]
There could also be another layer on top of `{metadata.namespace}/{metadata.name}` which is if you have multiple clusters defined in a mono repo, then you would probably want it to be named `{cluster-name}/{metadata.namespace}/{metadata.name}`. I think defaulting to the Git source for the `depName` would be best and allowing people to override it someway, either by annotation or a renovate comment as described by @viceice in the reply below.

**Comment by viceice** [comment]
Maybe it's better to derive the depName from the url (gitRepo) as most other managers do, so it's more visible on PR for users which dependency is updated.

We can then maybe allow to override via a comment. this is also possible on some managers.
@zharinov How complex would be a yaml parser which also holds the comments?

**Reply by zharinov** [reply]
🤷‍♂️ As complex as `github-actions` implementation?

**Reply by viceice** [reply]
no, with your parser. as regex is propably not enough / to complex, because we go through multiple levels of the object structure.

**Reply by zharinov** [reply]
Should be doable I think, since it supports tab-based nesting

**Reply by onedr0p** [reply]
I take an example of this would be something like the following?

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kyverno-controller
  namespace: flux-system
spec:
  interval: 1h0m0s
  provider: generic
  url: oci://ghcr.io/kyverno/manifests/kyverno
  ref:
    tag: v1.8.2 # renovate: depName=kyverno
    # or
    # digest: sha256:761c3189c482d0f1f0ad3735ca05c4c398cae201d2169f6645280c7b7b2ce6fc  # renovate: depName=kyverno
```

This works too, but I feel like the annotation method is a bit more inline with Kubernetes standards and the annotations will flow over into the deployed resource which means you could query the cluster and aggregate based on that annotation.

**Reply by viceice** [reply]
should probably be the full oci name: `ghcr.io/kyverno/manifests/kyverno`

**Reply by onedr0p** [reply]
Currently in the PR I have open for `OCIRepository`, `depName` would be`ghcr.io/kyverno/manifests/kyverno`, I meant as a way to override it with `kyverno`

**Reply by viceice** [reply]
ok, yes. the comment would a good idea but needs a new yaml parser 🙃

**Reply by onedr0p** [reply]
Would it be acceptable to use kubernetes annotations instead? e.g.

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kyverno-controller
  namespace: flux-system
  annotations:
    flux.manager.mend.io/depName: kyverno
spec:
  interval: 1h0m0s
  provider: generic
  url: oci://ghcr.io/kyverno/manifests/kyverno
  ref:
    tag: v1.8.2
```

This way it's defined in code and also embedded into the resource in the Kubernetes cluster.
