### DISCUSSION TITLE
Dependency not getting detected for longhorn helm-values

### DISCUSSION THREAD

**Discussion by c0depool** [renovatebot/renovate#19057] [Request Help] [answered]
Official Longhorn Helm chart helm-values are not getting detected by renovate. I can see below error in the logs, not sure if this is related

```
Failed to parse helm-values YAML
{
  "err": {
    "name": "YAMLException",
    "reason": "expected a single document in the stream, but found more",
    "message": "expected a single document in the stream, but found more",
    "stack": "YAMLException: expected a single document in the stream, but found more\n    at load (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/loader.js:1722:9)\n    at Object.extractPackageFile (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/manager/helm-values/extract.js:50:44)\n    at extractPackageFile (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/manager/index.js:55:13)\n    at getManagerPackageFiles (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/extract/manager-files.js:40:64)\n    at async /home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/extract/index.js:40:30\n    at async Promise.all (index 1)\n    at async extractAllDependencies (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/extract/index.js:39:28)\n    at async extract (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/extract-update.js:77:24)\n    at async extractDependencies (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/index.js:84:30)\n    at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:45:56)\n    at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:260:26)\n    at async /home/ubuntu/renovateapp/app/worker/index.js:454:5"
  }
}
```

[This](https://github.com/c0depool/suradhi-ops/blob/main/renovate.json) is my renovate.json. Looks like renovate is unable to parse the package names since it has multiple sub sections.

```
  values:
    image:
     longhorn:
       engine:
         repository: longhornio/longhorn-engine
         tag: v1.3.0
       manager:
         repository: longhornio/longhorn-manager
         tag: v1.3.0
       ui:
         repository: longhornio/longhorn-ui
         tag: v1.3.0
       instanceManager:
         repository: longhornio/longhorn-instance-manager
         tag: v1_20220611
       shareManager:
         repository: longhornio/longhorn-share-manager
         tag: v1_20220531
       backingImageManager:
         repository: longhornio/backing-image-manager
         tag: v3_20220609
     csi:
       attacher:
         repository: longhornio/csi-attacher
         tag: v3.4.0
       provisioner:
         repository: longhornio/csi-provisioner
         tag: v2.1.2
       nodeDriverRegistrar:
         repository: longhornio/csi-node-driver-registrar
         tag: v2.5.0
       resizer:
         repository: longhornio/csi-resizer
         tag: v1.2.0
       snapshotter:
         repository: longhornio/csi-snapshotter
         tag: v3.0.3
```
