### DISCUSSION TITLE
self hosted gitlab - access to container registry

### DISCUSSION THREAD

**Discussion by andyinno** [renovatebot/renovate#19451] [Request Help] [answered]
Hi!

I am trying  to access my private self hosted gitlab docker container registry.

My first naive approach was to 

```
docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
```

as I usually do in ci before-script.

Then, seen that it does not work. In the dependency dashboard I see 
```
Dependency Lookup Warnings ⚠

Renovate failed to look up the following dependencies mycontainer
```

So... After some RTFM I reached this page https://docs.renovatebot.com/modules/platform/gitlab/ where it is stated that I need to put everything in the variable RENOVATE_HOST_RULES.

I tried it in different ways, all the times, my repos are not discovered anymore.

I get this in the CI logs:

```
Discovered 0 project(s)
```

If I remove the variable:

```
Discovered 165 project(s)
```

renovate is configured to run out of a group access token, the way that gitlab suggests in order to have bot running in the system. Scopes for the access token are all selected.

Any ideas in order to get the bot see the projects while enabling the access to the container registry?

thank you for reading and sorry for the long post
Andrea

UPDATE: I made a test by using my username and access token, the same issue described before happens also in this case.

**Comment by viceice** [comment]
Please describe exactly how you set-up renovate. With your current information it's not possible to guess anything.

**Reply by andyinno** [reply]
Hi,

sorry for the lack of information.

I don't know exactly what to provide to you as additional information.

What I am observing is that when I follow the instruction provided here: https://docs.renovatebot.com/modules/platform/gitlab/

```
If you're using a private [GitLab container registry](https://docs.gitlab.com/ee/user/packages/container_registry/), you must:

    Set the RENOVATE_HOST_RULES CI variable to [{"matchHost": "${CI_REGISTRY}","username": "${GITLAB_USER_NAME}","password": "${RENOVATE_TOKEN}"}].
    Make sure the user that owns the RENOVATE_TOKEN PAT is a member of the corresponding GitLab projects/groups with the right permissions.
    Make sure the RENOVATE_TOKEN PAT has the read_registry scope.
```
I tried to login by using both "my bot access key" that I created as a group level access key (this is how gitlab suggests to create users to be intended to be used as bots) and my personal login info.
I have the following in the logs:

```
"autodiscover": true,
         "hostRules": [
           {
             "matchHost": "my.internal.site:6000",
             "username": "my-username",
             "password": "***********"
           },
```

and then some lines below:

```
DEBUG: Autodiscovering GitLab repositories
DEBUG: Discovered 0 project(s)
DEBUG: The account associated with your token does not have access to any repos
```

I am using my username and a freshly created access token.

If I omit that configuration line the reposories are correctly discovered by renovate by using the bot key (I setup that in gitlab => project settings => CI => Variables)
and I make the bot run:

```
DEBUG: Autodiscovering GitLab repositories
DEBUG: Discovered 167 project(s)
```

I have 167 projects autodiscovered.

Therefore my question is related to

```
Set the RENOVATE_HOST_RULES CI variable to [{"matchHost": "${CI_REGISTRY}","username": "${GITLAB_USER_NAME}","password": "${RENOVATE_TOKEN}"}].
```
This line in the documentation, how it behaves? Why it does not allow to autodiscover the projects? It is not only related to the docker registry, it does other things.

There is other ways to login to the private docker registry that do not broke the autodiscovery process?

**Reply by andyinno** [reply]
This is my gitlab-ci config:

```
image: 
  name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/renovate/renovate:34
  pull_policy: if-not-present

variables:
  RENOVATE_BASE_DIR: $CI_PROJECT_DIR/renovate
  RENOVATE_GIT_AUTHOR: Renovate Bot <bot@renovate.com>
  RENOVATE_OPTIMIZE_FOR_DISABLED: 'true'
  RENOVATE_REPOSITORY_CACHE: 'true'
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: fast
  CACHE_COMPRESSION_LEVEL: fast
  LOG_LEVEL: info
  #LOG_LEVEL: debug
  RENOVATE_LOG_FILE: renovate-log.ndjson
  RENOVATE_LOG_FILE_LEVEL: debug
  
cache:
  key: ${CI_COMMIT_REF_SLUG}-renovate
  paths:
    - renovate/cache/renovate/repository/

renovate:
  stage: deploy
  resource_group: production
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@my-intranet/".insteadOf "git@my-intranet:"
    - docker login -u $CI_DEPENDENCY_PROXY_USER -p $CI_DEPENDENCY_PROXY_PASSWORD $CI_DEPENDENCY_PROXY_SERVER
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  only:
    - schedules
  script:
    - renovate $RENOVATE_EXTRA_FLAGS
  artifacts:
    when: always
    expire_in: 1d
    paths:
      - '$RENOVATE_LOG_FILE'
   ```
with this, I am able to process all the projects but where I use my private docker images I get the warning 

```
Dependency Lookup Warnings ⚠

Renovate failed to look up the following dependencies mycontainer

```
