### DISCUSSION TITLE
Fail to create pull request - To https://**redacted**@renovateapp.com' does not follow the pattern

### DISCUSSION THREAD

**Discussion by halimulkazi** [renovatebot/renovate#19478] [Request Help]
Hello!

How are you running Renovate?
Self-hosted

If you're self-hosting Renovate, tell us what version of Renovate you run.
latest

If you're self-hosting Renovate, select which platform you are using.
gitlab

If you're self-hosting Renovate, tell us what version of the platform you run.
No response

Was this something which used to work for you, and then stopped?
no

Describe the problem

```"message": "To [https://**redacted**@renovateapp.com'](https://**redacted**@renovateapp.com%27/) does not follow the pattern '^.*@(abc.com|abcmerchants.com)$'\nerror: failed to push some refs to 'https://gitlab.corp.abc.com/<>/<>/<>.git'\n"```

I'm getting this error message but not sure how to fix it.

```
variables:
  RENOVATE_BASE_DIR: $CI_PROJECT_DIR/renovate
  RENOVATE_ENDPOINT: 'https://gitlab.corp.abc.com/api/v4/'
  RENOVATE_PLATFORM: gitlab
  RENOVATE_ONBOARDING_CONFIG: '{"$$schema": "https://docs.renovatebot.com/renovate-schema.json", "extends": ["config:base"] }'
  RENOVATE_OPTIMIZE_FOR_DISABLED: 'true'
  RENOVATE_REPOSITORY_CACHE: 'enabled'
  RENOVATE_REQUIRE_CONFIG: 'false'
  RENOVATE_ONBOARDING: 'true'

  RENOVATE_EXTENDS: 'github>whitesource/merge-confidence:beta'
  RENOVATE_LOG_FILE: renovate-log.ndjson
  RENOVATE_LOG_FILE_LEVEL: debug
  LOG_LEVEL: debug
  RENOVATE_BRANCH_PREFIX: "cep-111-cardeasepushTest--"
  RENOVATE_COMMIT_MESSAGE_PREFIX: "CEP-111  "

.tags: &tags
  - fk3
default:
  cache:
    key: ${CI_COMMIT_REF_SLUG}-renovate
    paths:
      - renovate/cache/renovate/repository/

renovate:
  tags: *tags
  stage: deploy
  resource_group: production
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  script:
    - renovate $RENOVATE_EXTRA_FLAGS
  artifacts:
    when: always
    expire_in: 1d
    paths:
      - '$RENOVATE_LOG_FILE'

```

```
module.exports = {
  labels: ["dependencies"],
  hostRules: [
    {
      hostType: 'nuget',
      matchHost: 'https://gitlab.corp.abc.com/api/v4/groups/17/-/packages/nuget/',
      username: '<>',
      password: '<>',
    }
  ],
   nuget: {
    registryUrls: [
      "https://gitlab.corp.abc.com/api/v4/groups/17/-/packages/nuget/index.json",
        "https://api.nuget.org/v3/index.json",
    ]
  },
   useBaseBranches: true,
   repositories: [
      {
        repository: '<>/<>/<>',
      }
    ],
   baseBranches: ["cep-111-<>--renovate"],

};


```
