### DISCUSSION TITLE
Getting 401 when hitting Github API for /merge-confidence/

### DISCUSSION THREAD

**Discussion by jbrardport** [renovatebot/renovate#19522] [Request Help] [answered]
I have renovate selfhosted in GitLab.

My renovate repo has the following gitlabci:
```yaml
include:
    - project: 'renovate-bot/renovate-runner'
      file: '/templates/renovate-dind.gitlab-ci.yml'

variables:
  RENOVATE_EXTRA_FLAGS: '--onboarding=false --autodiscover=true --autodiscover-filter=<HIDDEN>
```
The is an autodiscover filter that will interact with repos that have configs defined.

It was working for some time, and now it is broken.
I am seeing error messages like this:

```
{"name":"renovate","hostname":"runner-zxwgkjap-project-37413421-concurrent-0","pid":13,"level":20,"logContext":"exe4oIqAyJe-djEvAs3LY","msg":"GET https://api.github.com/repos/whitesource/merge-confidence/contents/beta.json = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=401 retryCount=0, duration=81)","time":"2022-12-21T16:20:16.193Z","v":0}
```

Does anyone have advice for what went wrong? Thanks.
