### DISCUSSION TITLE
Self-hosted GitLab - error 401 with private container registry

### DISCUSSION THREAD

**Discussion by WhoAmI0501** [renovatebot/renovate#19570] [Request Help] [answered]
Hi,
we are hosting our own GitLab with the GitLab Docker Registry enabled.
Renovate is running as a container next to the GitLab container.

Since today, our renovate needs to make a lookup in our private GitLab docker registry.

So - from the start. 

- User is created, it is called Example-RenovateBot and is having a PAT with api, read_user, write_repository and read_registry. Further, the User is Maintainer in the group, where the problematic project is located
- Renovate is configured to use the self-hosted GitLab with the mentioned PAT:
  - "endpoint": "https://gitlab.example.de/api/v4/",
  - "platform": "gitlab",
  - "token": \`${process.env.GITLAB_TOKEN}`,
- Renovate is configured with a hostRule for the registry:
  - "matchHost": "registry.example.de",
  - "hostType": "docker",
  - "username": "Example-RenovateBot",
  - "password": \`{process.env.GITLAB_TOKEN}`,
- normal access (like e.g. creating MRs etc.) is working with the user and the token

The problem is: Renovate fetches something from the registry and is forwarded to `https://gitlab.example.de/jwt/auth?service=container_registry&scope=repository:mygroup/problemproject:pull`, where it **should** do Basic-Authentication. But it is going to be rejected with an http status code 401 (`HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password.`). So the lookup for the dependency is failing.

But, suprise: if i call exactly this URL via curl with the same token (so basically with `-u Example-RenovateBot:mytoken123`) it works flawless and returns a JWT + http status code 200. And, as i stated before, the user can create MRs etc. without any problems using its PAT.

I debugged this for a few hours now but dont have any clue, whats going on there. From my point of view, i configured my GitLab + Renovate exactly as stated by the Renovate docs. But it is not working.

May somebody can help me? I am absolutely frustrated... :(

**Comment by viceice** [comment]
please provide your sanitized config

**Reply by WhoAmI0501** [reply]
Hi,
of course. Please note, that i currently moved Renovate into the GitLab instance, where it runs now as a Pipeline job. Therefore, i will also attach the `.gitlab-ci.yml`. (Renovate still works flawless, except the problem explained here.)

```javascript
module.exports = {
    // presets
    "extends": [
        // import basic configuration
        "config:base",

        // disable rate limiting since we are using a GitHub token
        ":disableRateLimiting",
    ],

    // credentials and GitLab endpoint configuration
    "endpoint": "https://gitlab.example.de/api/v4/",
    "platform": "gitlab",
    "token": `${process.env.GITLAB_TOKEN}`,

    // renovate is finding the project/his scope itself
    // it updates everytime itself and the pattern, which is passed by the variable "AUTODISCOVER_FILTER"
    "autodiscover": true,
    "autodiscoverFilter": [
        "rootserver/renovate",
        `${process.env.AUTODISCOVER_FILTER}`
    ],

    // behavior of renovate
    "fetchReleaseNotes": true,
    "printConfig": false,
    "includeForks": false,
    "requireConfig": false,
    "onboarding": false,
    "postUpdateOptions": ["gomodTidy"],
    "pinDigests": false,
    "rangeStrategy": "auto",
    "semanticCommitType": "cicd",
    "pruneStaleBranches": true,
    "cloneSubmodules": true,
    "labels": ["renovate"],
    "git-submodules": {
        "enabled": true
    },
    "rebaseWhen": "conflicted",

    "packageRules": [
        // ignore the following projects, since they are leading to renovate errors
        {
            "matchDatasource": ["gitlab-tags"],
            "matchPackageNames": ["RootServer/cicd-templates", "Development/Infrastructure/cicd-templates"],
            "enabled": false,
        },
        // Dockerfile and docker-compose updates of digests or pinnings of digests should be updated automatically
        {
            "matchDatasources": ["docker"],
            "matchUpdateTypes": ["pin", "pinDigest", "digest"],
            "automerge": true,
            "automergeType": "branch",
            "ignoreTests": true,
        },
        // renovate should be updated automatically, even if its a minor or a patch update
        {
            "matchDatasources": ["docker"],
            "matchPackageNames": ["renovate/renovate"],
            "matchUpdateTypes": ["minor", "patch", "pin", "pinDigest", "digest"],
            "automerge": true,
            "automergeType": "branch",
            "ignoreTests": true,
        },
        // pin the digests of all base images in Dockerfiles
        {
            "matchDatasources": ["docker"],
            "matchFiles": ["Dockerfile"],
            "pinDigests": true,
        },
        // all RootServer MRs are work for WhoAmI0501
        {
            "matchPackageNames": ["RootServer/**"],
            "assignees": ["@WhoAmI0501"],
        },
    ],

    // technical config for the connection to the gitlab server and token config for lookups at GitHub
    "hostRules": [
        {
            "enableHttp2": true,
            "keepalive": true,
            "dnsCache": true,
            "timeout": 10000,
        },
        {
            "matchHost": "https://github.com/",
            "token": `${process.env.GITHUB_COM_TOKEN}`,
            "hostType": "go",
        },
        {
            "matchHost": "https://api.github.com/",
            "token": `${process.env.GITHUB_COM_TOKEN}`,
            "hostType": "github",
        },
        // configure docker registry credentials for the registry
        {
            "matchHost": `{process.env.CI_REGISTRY}`,
            "hostType": "docker",
            "username": "Example-RenovateBot",
            "password": `{process.env.GITLAB_TOKEN}`,
        },
    ]
};

```

```yaml
---

include:
  - project: 'RootServer/cicd-templates'
    ref: 'master'
    file: 'includes/default.yml'

variables:
  AUTODISCOVER_FILTER:
    description: The autodiscover filter, for selecting the target projects of renovate - "**" means everything, where the renovate GitLab user is having access to
    value: "**"
  LOG_LEVEL:
    description: The log level, at which renovate should run (you mostly want to use "DEBUG")
    value: DEBUG
    options:
      - DEBUG
      - INFO
      - WARN
      - ERROR
      - FATAL

renovate:
  stage: deployment
  image: renovate/renovate:34.73.1
  variables:
    TZ: Europe/Berlin
    RENOVATE_REDIS_URL: redis://redis
    FF_NETWORK_PER_BUILD: 1
  services:
    - name: registry.example.de/rootserver/docker/images/example-redis:latest
      alias: redis
  script:
    - renovate
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "webide"
    - changes:
        - config.js
        - renovate.json
      variables:
        LOG_LEVEL: DEBUG
        AUTODISCOVER_FILTER: $CI_PROJECT_PATH


# disable linting jobs at web and schedule trigger
json-lint:
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule" && $CI_PIPELINE_SOURCE != "web" && $CI_PIPELINE_SOURCE != "webide"

markdown-lint:
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule" && $CI_PIPELINE_SOURCE != "web" && $CI_PIPELINE_SOURCE != "webide"

shellcheck:
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule" && $CI_PIPELINE_SOURCE != "web" && $CI_PIPELINE_SOURCE != "webide"

yaml-lint:
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule" && $CI_PIPELINE_SOURCE != "web" && $CI_PIPELINE_SOURCE != "webide"

```

`GITLAB_TOKEN` and `GITHUB_COM_TOKEN` are passed as CI/CD variables in GitLab.

Here is a error message from the renovate log:
```
DEBUG: GET https://gitlab.example.de/jwt/auth?service=container_registry&scope=repository:rootserver/project-releases:pull = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=403 retryCount=0, duration=16) (repository=rootserver/docker/images/example-project-daemon)
DEBUG: Not allowed to access docker registry (repository=rootserver/docker/images/example-project-daemon)
       "registryHost": "https://registry.example.de",
       "dockerRepository": "rootserver/project-releases"
DEBUG: Response code 403 (Forbidden) (repository=rootserver/docker/images/example-project-daemon)
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1672038506886,
           "socket": 1672038506886,
           "upload": 1672038506886,
           "response": 1672038506902,
           "end": 1672038506902,
           "phases": {
             "wait": 0,
             "request": null,
             "firstByte": 16,
             "download": 0,
             "total": 16
           }
         },
         "message": "Response code 403 (Forbidden)",
         "stack": "HTTPError: Response code 403 (Forbidden)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/34.73.1 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://gitlab.example.de/jwt/auth?service=container_registry&scope=repository:rootserver/project-releases:pull",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": true
         },
         "response": {
           "statusCode": 403,
           "statusMessage": "Forbidden",
           "body": {
             "errors": [{"code": "DENIED", "message": "access forbidden"}],
             "http_status": 403
           },
           "headers": {
             ":status": 403,
             "alt-svc": "h3=\":443\"; ma=2592000",
             "cache-control": "no-cache",
             "content-security-policy": "default-src 'self'; img-src 'self' data:; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'; upgrade-insecure-requests; block-all-mixed-content;",
             "content-type": "application/json; charset=utf-8",
             "date": "Mon, 26 Dec 2022 07:08:26 GMT",
             "expect-ct": "enforce, max-age=21600",
             "page-title": "GitLab",
             "permissions-policy": "geolocation=(), midi=(), notifications=(), push=(), sync-xhr=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), speaker=(), vibrate=(), fullscreen=(), payment=(), interest-cohort=()",
             "pragma": "no-cache",
             "referrer-policy": "same-origin",
             "strict-transport-security": "max-age=63072000; includeSubDomains",
             "vary": "Accept",
             "x-content-type-options": "nosniff",
             "x-download-options": "noopen",
             "x-frame-options": "SAMEORIGIN",
             "x-gitlab-custom-error": "1",
             "x-permitted-cross-domain-policies": "none",
             "x-request-id": "01GN6M5RC73J727TK4WM3828K1",
             "x-robots-tag": "none",
             "x-runtime": "0.013440",
             "x-ua-compatible": "IE=edge",
             "x-xss-protection": "1; mode=block",
             "content-length": "77"
           },
           "httpVersion": "2.0",
           "retryCount": 0
         }
       }
DEBUG: Failed to get authHeaders for getTags lookup (repository=rootserver/docker/images/example-project-daemon)
DEBUG: Failed to look up docker dependency registry.example.de/rootserver/project-releases (repository=rootserver/docker/images/example-project-daemon, packageFile=Dockerfile, dependency=registry.example.de/rootserver/project-releases)
```
