### DISCUSSION TITLE
ERR_UNSUPPORTED_PROTOCOL when looking up OCI registry on GHCR.io

### DISCUSSION THREAD

**Discussion by loganmarchione** [renovatebot/renovate#19600] [Request Help] [answered]
I'm using the Renovate app on GitHub.com. Renovate helps me update a K8s cluster that is managed using [Flux CD](https://fluxcd.io/). My repo in question is [here](https://github.com/loganmarchione/k8s_homelab).

In my Renovate dashboard issue, I'm getting this error:

```
warning Dependency Lookup Warnings warning

    Renovate failed to look up the following dependencies: weave-gitops.

Files affected: cluster/apps/weave-gitops/weave-gitops/helmrelease.yaml
```

In the Renovate debug logs, I see this.

```
DEBUG: Using queue: host=ghcr.io, concurrency=10
DEBUG: GET oci://ghcr.io/weaveworks/charts/index.yaml = (code=ERR_UNSUPPORTED_PROTOCOL, statusCode=-1 retryCount=-1, duration=-1)
DEBUG: Datasource connection error
{
  "datasource": "helm",
  "packageName": "weave-gitops",
  "errCode": "ERR_UNSUPPORTED_PROTOCOL"
}
DEBUG: Failed to look up helm dependency weave-gitops (weave-gitops)(packageFile="cluster/apps/weave-gitops/weave-gitops/helmrelease.yaml", dependency="weave-gitops")
```

The HelmRepository in question ([here](https://github.com/loganmarchione/k8s_homelab/blob/master/cluster/charts/weave-charts.yml)) looks like this:

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-charts
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/weaveworks/charts
  type: oci
```

Kubectl seems to show the repository is functioning.

```
NAME           URL                               AGE   READY   STATUS
weave-charts   oci://ghcr.io/weaveworks/charts   20h   True    Helm repository is ready
```

The HelmRelease in question ([here](https://github.com/loganmarchione/k8s_homelab/blob/master/cluster/apps/weave-gitops/weave-gitops/helmrelease.yaml)) looks like this:

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.10
      sourceRef:
        kind: HelmRepository
        name: weave-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  # https://docs.gitops.weave.works/docs/references/helm-reference/
  values:
    image:
      repository: ghcr.io/weaveworks/wego-app
    ingress:
      enabled: false
    service:
      create: true
      type: ClusterIP
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    adminUser:
      create: true
      createClusterRole: true
      createSecret: false
      username: "admin"
    rbac:
      create: true
      impersonationResources: ["users", "groups"]
```

Kubectl seems to show the release is functioning.

```
NAME           AGE   READY   STATUS
weave-gitops   32m   True    Release reconciliation succeeded
```

 The Weave GitOps app works fine and I can load the web UI, it's just that Renovate doesn't seem to pickup the correct chart name. Is there something about the combo of Flux+OCI that causes `ERR_UNSUPPORTED_PROTOCOL`? Where is the `index.yaml` error coming from? Is Renovate appending that?
