### DISCUSSION TITLE
Custom Regex with changing depNames/packageNames

### DISCUSSION THREAD

**Discussion by cloudmatt** [renovatebot/renovate#19615] [Request Help] [answered]
I'm a bit perplexed on how to get renovate working to update a field in a helm value file using the `github-releases` datasource and would love some assistance from the internet 😄 

So basically the file is formatted like so:
```yaml
config: |
  kind: source
  spec:
    name: gcp
    path: cloudquery/gcp
    version: "v3.0.5"
    tables: ["*"]
    destinations: ["postgresql"]
  ---
  kind: destination
  spec:
    name: postgresql
    path: cloudquery/postgresql
    version: "v1.7.16"
    write_mode: overwrite-delete-stale
    spec:
      connection_string: ${CQ_DSN}
```

But the tool I'm using [cloudquery](https://www.cloudquery.io/) uses a monorepo approach where the releases are named like `plugins-{{kind}}-{{path}}-{{version}}` so an update would look like:
`plugins-source-gcp-v3.0.5` -> `plugins-source-gcp-v3.0.6`

The `name` field is arbitrary and can't be used as there might be multiple instantiations of the source/destination plugin so I need to find some way to extract the kind, path, and version into something that I can pass into github-release? I just can't seem to figure out what the best approach would be to make this work, I'm sure I need a custom regex manager but my regex skills are subpar on a good day and I don't quite understand how to extract the fields out correctly and template them and I'm desperate for some help here 😄
