### DISCUSSION TITLE
AWS Codeartifact support

### DISCUSSION THREAD

**Discussion by jonathanpruvost** [renovatebot/renovate#19651] [Request Help]
Hi,

We are currently testing the Renovate implementation on the repos of our applications.

Our stack:
- renovate hosted Github app
- pnpm
- lockFileMaintenance: true
- AWS codeartifact

We are having a problem with our private packages.
We use AWS codeartifact for our own npm registry.

We tested adding hostedRules with a hard-written token in the config and it works fine.

The problem is that the maximum duration of an AWS codeartifact token is 12 hours.
We haven't found in the documentation to be able to do this dynamically.

In the self-hosted version it seems possible to run the github action and pass the RENOVATE_HOST_RULES environment variable.

What solution do you recommend?

Thank you

**Comment by HonkingGoose** [comment]
Related issue:

- https://github.com/renovatebot/renovate/issues/13833

**Reply by jonathanpruvost** [reply]
Hello,

Thank you for your reply.
I managed to make it work with github action Renovate by adding a Github workflow.

```
name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2.0.0

      - name: Configure AWS credentials from GithubActions account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure AWS codeartifact
        run: >
          echo "GITHUB_CODEARTIFACT_TOKEN=$(
          aws codeartifact get-authorization-token
          --domain ${{ secrets.CODEARTIFACT_DOMAIN_NAME }}
          --domain-owner ${{ secrets.CODEARTIFACT_DOMAIN_OWNER }}
          --query authorizationToken
          --output text
          --region ${{ secrets.AWS_REGION }})" >> $GITHUB_ENV

      - name: Renovate
        uses: renovatebot/github-action@v34.78.0
        env:
          RENOVATE_HOST_RULES: '[{"hostType": "npm", "matchHost": "https://${{ secrets.CODEARTIFACT_DOMAIN_NAME }}-${{ secrets.CODEARTIFACT_DOMAIN_OWNER }}.d.codeartifact.${{ secrets.AWS_REGION }}.amazonaws.com/npm/${{ secrets.CODEARTIFACT_REPOSITORY }}/", "token": "${{ env.GITHUB_CODEARTIFACT_TOKEN }}"}]'
          RENOVATE_NPMRC: '${{ secrets.CODEARTIFACT_NAMESPACE }}:registry=https://${{ secrets.CODEARTIFACT_DOMAIN_NAME }}-${{ secrets.CODEARTIFACT_DOMAIN_OWNER }}.d.codeartifact.${{ secrets.AWS_REGION }}.amazonaws.com/npm/${{ secrets.CODEARTIFACT_REPOSITORY }}/\n\nauto-install-peers=true'
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_CONFIG_FILE: renovate.json
          LOG_LEVEL: 'debug'
```

My original question was about native AWS support using the Github App Renovate or for example the possibility of executing a script before executing analyze.
https://github.com/apps/renovate

Thank you
