### DISCUSSION TITLE
Update only patch version for multiple of the same dependency found in a file

### DISCUSSION THREAD

**Discussion by superseb** [renovatebot/renovate#19668] [Request Help] [answered]
I have the following file contents, and the goal is to check for newer Docker images for each patch version within major.minor. So each major.minor needs to update the version to the same major.minor.patch (1.25.0 -> 1.25.1, 1.24.3 -> 1.24.4).

```
versionOverrides:
  - constraint: "~ 1.25"
    values:
      cloudControllerManager:
        repository: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager
        tag: v1.25.0
  - constraint: ">= 1.24 < 1.25"
    values:
      cloudControllerManager:
        repository: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager
        tag: v1.24.3
  - constraint: ">= 1.23 < 1.24"
    values:
      cloudControllerManager:
        repository: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager
        tag: v1.23.3
  - constraint: "~ 1.22"
    values:
      cloudControllerManager:
        repository: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager
        tag: v1.22.7
```

I've been playing with it a bit already, but can't seem to find if this is supposed to work or not. Currently working with the following;

```
  "regexManagers": [
    {
      "fileMatch": [
        "vsphere-chart/values.yaml$"
      ],
      "matchStrings": [
        "repository: (?<depName>.*?)\n *tag: (?<currentValue>.*)\n"
      ],
      "datasourceTemplate": "docker"
    }
  ],
  "packageRules": [
    {
      "matchDepNames": ["rancher/mirrored-cloud-provider-vsphere-cpi-release-manager"],
      "matchCurrentValue": "/^v1\\.24/",
      "allowedVersions": ">1.24.0 <1.25.0",
      "separateMinorPatch": true
    }
  ]
```

The current result is that all occurrences get updated to the latest found Docker image (`v1.25.0`). Is this possible to accomplish? I started with this, of course I would create more `packageRules` as soon as I have this working but that's an acceptable solution.
