### DISCUSSION TITLE
Using multiple Renovate configurations

### DISCUSSION THREAD

**Discussion by tomkerkhove** [renovatebot/renovate#19666] [Request Help] [answered]
When using a monorepo, there can be multiple components to maintain and a single configuration file can become big.

I'm wondering if we can have multiple Renovate configurations and specify what configuration file to use?

Currently; our pipeline looks as following:

```yaml
jobs:
  - job:

    steps:
      - bash: |
          cat renovate.json
        displayName: Show Renovate configuration

      - bash: |
          npm install renovate

          git config --global user.email 'bot@renovateapp.com'
          git config --global user.name 'Renovate Bot'
          npx --userconfig .npmrc renovate
        displayName: "Run Renovate"
        env:
          LOG_LEVEL: info
          TOKEN: $(System.AccessToken)
```

And our npmrc as following:
```
registry=https://pkgs.dev.azure.com/<something>/_packaging/Renovate/npm/registry/
always-auth=true
```

However, based on https://docs.renovatebot.com/configuration-options/ I'm afraid we have to follow one of these file names?

An alternative would be to use shared presets but that does not allow sharing general configuration such as includePaths I think.
