### DISCUSSION TITLE
Renovate keeps overriding my configuration file

### DISCUSSION THREAD

**Discussion by felixranesberger** [renovatebot/renovate#19674] [Request Help] [answered]
Hi, I want to implement Renovate using the [Gitlab CI runner.](https://gitlab.com/renovate-bot/renovate-runner) 
I followed the instructions and got Renovate to generate a merge request in my chosen repository. 

Right now I have the problem, that I want to adjust the Renovate configuration. 

As in the merge request stated, I update the configuration inside the merge request and rerun the Renovate pipeline. 

But everytime I do that, my configuration resets to the default configuration, which gets generated on the initial setup

## Settings:
**Runner settings**
`RENOVATE_EXTRA_FLAGS=--autodiscover=true --autodiscover-filter=mygroup/*`

**.gitlab-ci.yml**
```yaml
include:
  - project: 'in2code-Team/Tools/renovate-runner'
    file: '/templates/renovate-dind.gitlab-ci.yml'

renovate:
  variables:
    GITLAB_NPM_TOKEN: "${CI_JOB_TOKEN}"
  script:
    - renovate $RENOVATE_EXTRA_FLAGS
```

## My new configuration should look something like this (im not entirly sure if this works yet):
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "packageRules": [
    {
      "groupName": "TYPO3",
      "matchPackagePrefixes": [
        "typo3"
      ],
      "allowedVersions": "<12.0.0"
    }
  ],
  "hostRules": [
    {
      "hostType": "npm",
      "matchHost": "gitlab.domain.de/api/v4/projects/321/packages/npm/",
      "token": "process.env.GITLAB_NPM_TOKEN",
      "authType": "Basic"
    }
  ]
}
```
