### DISCUSSION TITLE
Redundant url with gitlab-tags

### DISCUSSION THREAD

**Discussion by jdauliac** [renovatebot/renovate#19671] [Request Help]
Hi,

With renovate container `34.77.0` in self hosted on my gitlab on premise, I get the following log:

```
DEBUG: Datasource 404 (repository=xxx/libraries/php/workers-bundle)
       "datasource": "gitlab-tags",
       "packageName": "iac/docker/php7",
       "url": "https://gitlab.xxx.com/api/v4/gitlab.xxx.com/api/v4/projects/iac%2Fdocker%2Fphp7/repository/tags?per_page=100"
DEBUG: Failed to look up gitlab-tags dependency iac/docker/php7 (repository=xxx/libraries/php/workers-bundle, packageFile=.pre-commit-config.yaml, dependency=iac/docker/php7)
```

We can clearly see that the host url appears twice in the url: `//gitlab.xxx.com/api/v4/gitlab.xxx.com`

## Configs
I use it with the following configurations:

`renovate.json`:
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "platform": "gitlab",
  "packageRules": [
    {
      "depTypeList": [
        "devDependencies",
        "require-dev"
      ],
      "updateTypes": [
        "patch",
        "minor",
        "digest"
      ],
      "groupName": "devDependencies (non-major)"
    }
  ],
  "extends": [
    "config:base",
    ":preserveSemverRanges",
    ":dependencyDashboard",
    ":rebaseStalePrs",
    ":enableVulnerabilityAlertsWithLabel('security')",
    "group:recommended"
  ],
  "branchPrefix": "renovate-",
  "branchName": "issue/{{{branchPrefix}}}{{{additionalBranchPrefix}}}{{{branchTopic}}}",
  "onboardingBranch": "feature/add-renovate-config",
  "labels": [
    "⬆ Upgrade dependencies"
  ],
  "pre-commit": {
    "enabled": true
  }
}
```

`.gitlab-ci.yml`:
```yml
stage: ⬆️ Dependencies upgrade
  variables:
    RENOVATE_BASE_DIR: $CI_PROJECT_DIR/renovate
    RENOVATE_GIT_AUTHOR: Renovate Bot <ops+renovate@xxx.com>
    RENOVATE_OPTIMIZE_FOR_DISABLED: 'true'
    RENOVATE_REPOSITORY_CACHE: 'true'
    LOG_LEVEL: debug
  needs: []
  extends:
    - .runner_tag_shared_small
  script:
    - |
      cat > config.js <<- EOM
        module.exports = {
          endpoint: process.env.CI_API_V4_URL,
          token: process.env.RENOVATE_TOKEN,
          persistRepoData: true,
          logLevel: 'debug',
          onboardingConfig: {
                  "extends": [
                          "local>iac/cicd/renovate/renovate-config"
                  ],
          },
          autodiscover: true,
          hostRules: [
            {
              hostType: 'docker',
              matchHost: process.env.CI_REGISTRY,
              username: process.env.CI_REGISTRY_USER,
              password: process.env.CI_REGISTRY_PASSWORD,
            },
            {
              hostType: 'docker',
              matchHost: process.env.CI_DEPENDENCY_PROXY_SERVER,
              username: process.env.CI_DEPENDENCY_PROXY_USER,
              password: process.env.CI_DEPENDENCY_PROXY_PASSWORD,
            }
          ],
        };
      EOM
      renovate $RENOVATE_EXTRA_FLAGS
```

Do you have any idea how to get around or to fix this problem?
