### DISCUSSION TITLE
How to properly customize versioning for github-action dependencies?

### DISCUSSION THREAD

**Discussion by LiuVII** [renovatebot/renovate#19705] [Request Help] [answered]
I have a GitHub workflow in `./github/workflows/tf-check.yml` that contains the code

```yaml
name: Check Terraform Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tf_fmt_lint:
    uses: merit/github-actions/.github/workflows/tffmt-lint.yml@w_tffmt-lint/v1
    with:
      workflow_id: tf-check.yml
      tflint_config_file: '.tflint.hcl'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      gh_repo_read_token: ${{ secrets.GH_REPO_READ_TOKEN }}
```

As the versioning scheme for this dependency `merit/github-actions/.github/workflows/tffmt-lint.yml@w_tffmt-lint/v1` is irregular
renovate doesn't know how to properly update it
```
...
         "packageFile": ".github/workflows/tf-check.yml",
         "deps": [
           {
             "depName": "merit/github-actions",
             "commitMessageTopic": "{{{depName}}} action",
             "datasource": "github-tags",
             "versioning": "docker",
             "depType": "action",
             "replaceString": "merit/github-actions/.github/workflows/tffmt-lint.yml@w_tffmt-lint/v1",
             "autoReplaceStringTemplate": "{{depName}}/.github/workflows/tffmt-lint.yml@{{#if newDigest}}{{newDigest}}{{#if newValue}} # {{newValue}}{{/if}}{{/if}}{{#unless newDigest}}{{newValue}}{{/unless}}",
             "currentValue": "w_tffmt-lint/v1",
             "skipReason": "invalid-version",
             "depIndex": 0,
             "updates": []
           }
...
```

I was trying to provide config in a different way via

1.  Customizing manager
```
  "github-actions": {
    fileMatch: [
      "^(workflow-templates|\\.github\\/workflows)\\/[^/]+\\.ya?ml$",
      "(^|\\/)action\\.ya?ml$"
    ],
    versioning: "regex:^(?<compatibility>.*\\/v)?(?<major>\\d+)(\\.(?<minor>\\d+))?(\\.(?<patch>\\d+))?$",
  },
```
2. Adding package rules
```
      packageRules: [
        {
          matchManagers: ["github-actions"],
          matchDatasources: ["github-tags"],
          versioning: "regex:^(?<compatibility>.*\\/v)?(?<major>\\d+)(\\.(?<minor>\\d+))?(\\.(?<patch>\\d+))?$",
        },
```
3. Trying regexManagers config

But nothing changed the versioning result and the skipReason, I'm not even sure why it's using `docker` by default in the first place.

Any idea on how to make a Renovate config to support the custom versioning pattern I described is appreciated.
