### DISCUSSION TITLE
Recursive matchStringsStrategy trouble

### DISCUSSION THREAD

**Discussion by guidojw** [renovatebot/renovate#19727] [Request Help] [answered]
Hi,

I want to create a regex manager that updates the `version` input of a particular action I'm using.

regexManager configuration in my `renovate.json`:

```yml
{
  "description": "Update Aftman version in setup-aftman action inputs",
  "fileMatch": [
    "^(workflow-templates|\\.github\\/workflows)\\/[^/]+\\.ya?ml$",
    "(^|\\/)action\\.ya?ml$"
  ],
  "matchStringsStrategy": "recursive",
  "matchStrings": [
    "uses:\\s*ok-nick\\/setup-aftman@.+?\\n\\s+-",
    "version:\\s*(?<currentValue>[^\\n]*)"
  ],
  "depNameTemplate": "LPGhatguy/aftman",
  "datasourceTemplate": "github-releases"
}
```

Example workflow configuration:

```yml
      - name: Setup Aftman
        uses: ok-nick/setup-aftman@c52e3c91524316f8ca696574d576ea21b7518ec8 # v0.3.0
        with:
          version: v0.1.0
```

My idea is to match the specific action's entry starting at `uses:` until and including the next `-` that is the first character on its line. Above configuration however does not work yet, checking the logs it seems that it does not find an entry in my workflow files at all at the moment.

What could I do to fix this/is this use case supported?
