### DISCUSSION TITLE
Trigger another github action workflow on Renovate automerge

### DISCUSSION THREAD

**Discussion by zaggash** [renovatebot/renovate#19845] [Request Help] [answered]
I have a Renovate workflow schedule running periodically.
Renovate is running from a workflow. An application is setup to make it run.

I can't find why another workflow waiting on a 'push' event is not triggered after Renovate auto-merge commit to the main branch.
Is Renovate auto-merge not pushing the commit that could be handled by another workflow?

Here is the Renovate autoMerge config:  
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "packageRules": [
    {
      "description": "Auto merge container digests",
      "matchDatasources": ["docker"],
      "automerge": true,
      "automergeType": "branch",
      "matchUpdateTypes": ["digest"],
      "ignoreTests": true
    }
  ]
}
```
  
The workflow I'd like to start is waiting on the following events:  
```
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "./Dockerfile"
      - "./run.sh"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
```
