### DISCUSSION TITLE
Every time I run renovate, an issue is created in the dependency dashboard.

### DISCUSSION THREAD

**Discussion by sunecosuri** [renovatebot/renovate#19913] [Request Help] [answered]
### How are you running Renovate?
Self-hosted by github-action (renovatebot/github-action@v34.82.0)

### If you're self-hosting Renovate, tell us what version of Renovate you run.
34.82.0

### If you're self-hosting Renovate, select which platform you are using.
github.com

<details>
<summary>my renovate config</summary>

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base",
    ":timezone(Asia/Tokyo)"
  ],
  "repositories": ["XXXX/XXXXX"],
  "labels": [
    "renovate"
  ],
  "logFileLevel": "debug",
  "prConcurrentLimit": 10,
  "major": {
    "stabilityDays": 7
  },
  "minor": {
    "stabilityDays": 3
  },
  "patch": {
    "stabilityDays": 2
  },
  "vulnerabilityAlerts": {
    "enabled": true,
    "labels": [
      "renovate",
      "Security"
    ],
    "stabilityDays": 0
  },
  "packageRules": [
    {
      "matchDepTypes": [
        "devDependencies"
      ],
      "labels": [
        "renovate",
        "devDependencies"
      ],
      "groupName": "Update devDependencies"
    }
  ]
}

```

</details>

Each run creates the following issue.

```
This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

## Rate-Limited

These updates are currently rate-limited. Click on a checkbox below to force their creation now.

 - [ ] XXXXXXX
 - [ ] <!-- create-all-rate-limited-prs -->🔐 **Create all rate-limited PRs at once** 🔐

## Edited/Blocked

These updates have been manually edited so Renovate will no longer make changes. To discard all commits and start over, click on a checkbox.

 - [ ] XXXXXXX

---

### ⚠ Dependency Lookup Warnings ⚠

-   Renovate failed to look up the following dependencies: `XXXXXX`, `YYYYYYY`, `ZZZZZZZZZ`.

Files affected: `package.json`

---


## Open

These updates have all been created already. Click a checkbox below to force a retry/rebase of any.

 - [ ] XXXXXX
 - [ ] XXXXXX
 

```

**Comment by rarkins** [comment, marked as answer]
This is usually caused because you haven't configured the `username` correctly in your bot config. For example you configure `username: 'foo'` but it should be `username: 'foo[bot]'`.

If the username is wrong, then Renovate doesn't "see" its previously created issues, so assumes it needs to create them again.

**Reply by sunecosuri** [reply]
@rarkins 

thanks.

env.`RENOVATE_USERNAME` and env.`RENOVATE_GIT_AUTHOR` didn't seem to replace the User name. Am I specifying it wrong...?
From the documentation, it's probably because they are not supported Platforms, but is there any other way to specify...?

https://docs.renovatebot.com/self-hosted-configuration/#username

```yaml
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.82.0
        env:
          RENOVATE_USERNAME: "renovate[bot]"
          RENOVATE_GIT_AUTHOR: "Self-hosted Renovate Bot <79356887+self-hosted-renovate[bot]@users.noreply.github.com>"
          LOG_LEVEL: 'debug'
        with:
          token: ${{ secrets.RENOVATE_TOKEN }} # I create a "Personal Access Token" from Bot User and set it to secrets.RENOVATE_TOKEN.

```

**Reply by rarkins** [reply]
Those env names are correct, so if they're not working then likely it's because they're not being passed fully through to Renovate. You need to look at the debug logs from the start of each run where config is parsed.

The username env looks wrong though - you do not own/run `renovate[bot]`.

**Reply by sunecosuri** [reply]
env.`RENOVATE_USERNAME` is Changed as follows.

```yaml
env:
  LOG_LEVEL: debug
  RENOVATE_CONFIG_FILE: renovate.json5
  RENOVATE_USERNAME: ${{ github.repository_owner }}
  RENOVATE_GIT_AUTHOR: "Self-hosted Renovate Bot <79356887+self-hosted-renovate[bot]@users.noreply.github.com>"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.82.0
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}

```
