### DISCUSSION TITLE
No custom config file found on disk

### DISCUSSION THREAD

**Discussion by domWinter** [renovatebot/renovate#19922] [Request Help] [answered]
Hi,

I am running renovate in a Gitlab CI pipeline job of a node project and getting the error:

```
 $ renovate $RENOVATE_EXTRA_FLAGS
DEBUG: Using RE2 as regex engine
DEBUG: Parsing configs
DEBUG: Checking for config file in /builds/test/test-project/config.js
FATAL: No custom config file found on disk
```
However, there definitily is a config.js file in the root of the project with the required config for gitlab.
I also tried using the env variable _RENOVATE_CONFIG_FILE_ to point to the _./config.js_ file, but getting a similar error.

Here is my gitlab-ci.yaml:
```yaml
renovate:
  stage: renovate
  image: renovate/renovate
  resource_group: production
  variables:
    RENOVATE_BASE_DIR: $CI_PROJECT_DIR/renovate
    RENOVATE_GIT_AUTHOR: Renovate Bot <renovatebot@foo.com>
    RENOVATE_OPTIMIZE_FOR_DISABLED: 'true'
    RENOVATE_REPOSITORY_CACHE: 'true'
    LOG_LEVEL: debug
  rules:
    - if: $RENOVATE == "true"
      when: on_success
    - when: never
  script:
    - renovate $RENOVATE_EXTRA_FLAGS
```

Any sugesstions?

Best regards
Dominik
