### DISCUSSION TITLE
Separate configuration for /backend and /frontend in monorepo

### DISCUSSION THREAD

**Discussion by janez-svetin** [renovatebot/renovate#20036] [Request Help] [answered]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

If it is possible I would like to have a configuration per path in the repo. For example, our monorepo has `/backend` and `/frontend` subfolders. And for each, I would like to set different intervals/schedules, open PR limits, version limitations, etc.

I know dependabot has something like this:

```
updates:
  - package-ecosystem: "npm"
    directory: "/frontoffice"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 4
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
- package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]
```

But how to solve this in Renovate?

### What you tried so far.

Did not actually find anywhere in the documentation that this is possible.
