### DISCUSSION TITLE
Update only dependencies for a specific branch ( github )

### DISCUSSION THREAD

**Discussion by sebastianjnuwu** [renovatebot/renovate#20093] [Request Help] [answered]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

Latest

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

I just wanted to update the dependencies on a specific branch
```yml
{
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": ["config:base"],
    "assignees": ["sebastianjnuwu"],
    "reviewers": ["sebastianjnuwu"],
    "dependencyDashboard": false,
    "fetchReleaseNotes": true,
    "packageRules": [
        {
            "matchPackagePatterns": ["*"],
            "matchUpdateTypes": ["minor", "patch"],
            "groupName": "all non-major dependencies",
            "groupSlug": "all-minor-patch",
            "labels": ["dependencies"]
        },
        {
            "matchPackagePatterns": ["*"],
            "matchUpdateTypes": ["major"],
            "labels": ["dependencies", "breaking"]
        }
    ]
}
```

### What you tried so far.

Ask university students

**Comment by sebastianjnuwu** [comment]
Summary: how do you make the bot open PR or just update the dependencies of a specific branch my settings so far is:
```yml
{
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": ["config:base"],
    "assignees": ["sebastianjnuwu"],
    "reviewers": ["sebastianjnuwu"],
    "dependencyDashboard": false,
    "fetchReleaseNotes": true,
    "packageRules": [
        {
            "matchPackagePatterns": ["*"],
            "matchUpdateTypes": ["minor", "patch"],
            "groupName": "all non-major dependencies",
            "groupSlug": "all-minor-patch",
            "labels": ["dependencies"]
        },
        {
            "matchPackagePatterns": ["*"],
            "matchUpdateTypes": ["major"],
            "labels": ["dependencies", "breaking"]
        }
    ]
}
```
