### DISCUSSION TITLE
How to specify helm registries for flux (HelmRelease) ?

### DISCUSSION THREAD

**Discussion by igor-golubovich** [renovatebot/renovate#20179] [Request Help] [answered]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

I have k8s manifests for flux (kind: HelmRelease). Renovatebot finds "packageFile" but it doesn't know "registryUrls" ("skipReason"). How to configurate renovate.json right for this issue?

release.yaml:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: v1.6.3
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 10m
  values:
    logLevel: 6
```

### What you tried so far.

I tried this but it didn't work:

```
  "packageRules": [
    {
      "matchDatasources": ["helm"],
      "matchDepNames": ["cert-manager"],
      "registryUrls": [
        "https://charts.jetstack.io"
      ]
    }
  ]
```

### Relevant debug logs

<details><summary>Logs</summary>

```
 "packageFile": "apps/clusters/k8s-02/cert-manager/release.yaml",
        "deps": [
          {
            "depName": "cert-manager",
            "currentValue": "v1.6.3",
            "datasource": "helm",
            "skipReason": "unknown-registry",
            "depIndex": 0,
            "updates": []
          }
        ]
```

</details>

**Comment by igor-golubovich** [comment, marked as answer]
This solution is work, but need to add additional line to .yaml:
```
# renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
```
release.yaml:
```
 "regexManagers": [
    // regexManager to read and process helm repositories
    {
      // tell renovatebot to parse only helm releases
      "fileMatch": ["cluster/.+helm-release\\.yaml$"],
      // tell renovatebot to match the following pattern in helm release files
      "matchStrings": [
        "registryUrl=(?<registryUrl>.*?)\n *chart: (?<depName>.*?)\n *version: (?<currentValue>.*)\n"
      ],
      // tell renovatebot to search helm repositories
      "datasourceTemplate": "helm"
    },
```

**Comment by raidlman** [comment]
I'm using the following custom Manager:

```
    {
      "customType": "regex",
      "fileMatch": [
        "(^|/)release\\.ya?ml$"
      ],
      "matchStrings": [
        "registryUrl:\\s+(?<registryUrl>[^\\s]*?)\\s+chart:\\s+(?<depName>[^\\s]*?)\\s+version:\\s+\"(?<currentValue>[^\"]*?)\""
      ],
      "datasourceTemplate": "helm"
    }
```

which will work for all FluxCD HelmRelease files named `release.yaml` or `release.yml` with the following structure (e.g. my ingress-nginx helm release):

```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      # registryUrl: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: "4.11.2"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    ...
```

I though I'd share since it took me way too long due to some silly mistake I made by matching until `$`.

**Comment by viceice** [comment]
if you configure the helm repository inside the same repo, then renovate will find it

**Comment by raidlman** [comment]
Wait what? Since when? How do I have to set this up to make this work?

I have a separate `repository,yaml` file for each Helm repo which looks like this:

```
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
spec:
  interval: 5m
  url: https://kubernetes.github.io/ingress-nginx
```

The file is in the same folder as the release.yaml file.

When I did the research to find out why renovate doesn't finde any updates for my releases, someone said that if the repository is stored in a different file, this doesn't work.
