### DISCUSSION TITLE
Regex manager for GitHub releases file urls

### DISCUSSION THREAD

**Discussion by Kampfmoehre** [renovatebot/renovate#20270] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.125.1

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

15.8

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

I want Renovate to update plugins for our SonarQube instance. We deploy SonarQube with the GitLab agent (GitOps) from a repository. The repo contains a `kustomization.yaml` referencing the SonarQube chart and a `values.yaml` file. In this `values.yaml` file we add plugins for the SonarQube instance. These plugins are download urls of `.jar` files from GitHub releases and I am trying to come up with a working regex manager that allows to extract and update these.

This is what the yaml file looks like
```yaml
plugins:
  install:
    # renovate: datasource=github-tags depName=dependency-check/dependency-check-sonar-plugin
    - "https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/3.0.1/sonar-dependency-check-plugin-3.0.1.jar"
    # renovate: datasource=github-tags depName=javamachr/sonar-gitlab-plugin
    - "https://github.com/javamachr/sonar-gitlab-plugin/releases/download/5.3.0/sonar-gitlab-plugin-5.3.0.jar"
    # renovate: datasource=github-tags depName=sbaudoin/sonar-yaml
    - "https://github.com/sbaudoin/sonar-yaml/releases/download/v1.7.0/sonar-yaml-plugin-1.7.0.jar"
    # renovate: datasource=github-tags depName=sbaudoin/sonar-ansible
    - "https://github.com/sbaudoin/sonar-ansible/releases/download/v2.5.1/sonar-ansible-plugin-2.5.1.jar"
```
Is this somehow possible with the Regex manager?

### What you tried so far.

I tried to orientate on my experience with regex managers in container files and the [documantation](https://docs.renovatebot.com/modules/manager/regex/). I have come up with the following config:
```json
{
  "regexManagers": [
    {
      "fileMatch": ["^tools/(.*)/values.ya?ml$"],
      "matchStrings": [
        "#\\s?renovate: datasource=(?<datasource>.*?) depName=(?<depName>.*?)\\s*-\\s\\\".*\\/(?<currentValue>v?[\\d\\.]*)\\/.*-(?<currentValue2>[\\d\\.]*).jar\\\""
      ],
      "versioningTemplate": "{{#if versioning}}{{{versioning}}}{{else}}semver{{/if}}"
    }
  ]
}
```

The config is working in detecting the dependencies but I have two obstacles. First, the link contains the `currentVersion` two times, but regex capute groups must be unique (this is why I use `currentValue2` in the second ocassion.
Second, some of those plugins use leading v but only on the tag. This leads to an url with two different versions, one with the leading v, one without. I tried to circumvent that with the `v?` part but I am unsure if this could work. Maybe I should use `"extractVersion": "^v(?<version>.*)$"` in the package rule for the plugins?

### Relevant debug logs

<details><summary>Logs</summary>

I can see in the logs that the dependencies are detected, the problem is not to match them but how to update them.

```
-
```

</details>
