### DISCUSSION TITLE
Azure DevOps Pipeline -- Trying to create turn off PR creation and just create a single md file in my artifact folder.

### DISCUSSION THREAD

**Discussion by Al3xDaniels** [renovatebot/renovate#20616] [Request Help]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

Azure DevOps (dev.azure.com)

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Wanted end result.

In Azure DevOps Pipelines I am trying to turn off PR requests from being created and append all results to a master md file. So far, I have tried a bunch of different config options and still no such luck. Any help would be greatly appreciated. 

This is my pipeline yaml
```
schedules:
  - cron: "0 3 * * Sun"
    displayName: "Every Sunday at 3am"
    branches:
      include: [main]

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: "renovatebot"

steps:
  - bash: |
      ls -a
      git config --global user.email 'bot@renovateapp.com'
      git config --global user.name 'Renovate Bot'
      npx renovate
      ls -a
    env:
      TOKEN: $(AZ_TOKEN)
      GITHUB_COM_TOKEN: $(GITHUB_TOKEN)
      #RENOVATE_CONFIG_FILE: "./pipelines/renovate/config.js" # use this environment variable if you prefer to have the renovate pipeline definition and the config file in it's own dictionary instead of the repository root.

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/results.md'
      ArtifactName: 'renovate-results'
```

This is my config.json file
```
module.exports = {
  platform: 'azure',
  endpoint: 'https://dev.azure.com/xxx/',
  token: process.env.TOKEN,
  pr: {
    pullRequest: 'none'
  },
  markdown: {
    fileExtension: 'md',
    directory: './',
    fileName: 'renovate'
  },
  hostRules: [
    {
      "azureAutoApprove": true,
      "automerge": true
    }
  ],
  repositories: ['POC/foo']
};

```

### What you tried so far.

far too much

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>
