### DISCUSSION TITLE
Stop adding me as a participant to every merge request on GitLab

### DISCUSSION THREAD

**Discussion by simon-liebehenschel** [renovatebot/renovate#20621] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

renovate/renovate:34.152-slim

### If you're self-hosting Renovate, select which platform you are using.

gitlab.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

gitlab.com latest

### Was this something which used to work for you, and then stopped?

I never saw this working

## Wanted

Do not add me as a participant to every merge request on GitLab.

## Result

I am added to "participants" to every new merge request. This means I get email notifications for every event in every merge request.

### What you tried so far.

I checked Renovate-bot and GitLab documentation about disabling adding me to "participants" but I found no information.

### Config

```js
module.exports = {
  // Self-Hosted configuration options
  autodiscover: true,
  autodiscoverFilter: ["/backend/*/"],
  platform: "gitlab",
  prCommitsPerRunLimit: 50, // The default is no limit, but set some random generous value to stay safe.
  allowedPostUpgradeCommands: ["^poetry version [a-z0-9-]+$", "poetry lock"],

  // Configuration Options
  hostRules: [
    {
      matchHost: "gitlab.com",
      hostType: "pypi",
      username: "gitlab-ci-token",
      password: process.env.CI_JOB_TOKEN,
    },
  ],
  extends: ["config:base", ":semanticCommits"],
  automerge: true,
  prConcurrentLimit: 20, // The default is no limit, but set some random generous value to stay safe.
  branchNameStrict: true, // I am not sure if we need this, but let us remove special characters to stay safe.
  cloneSubmodules: true,
  dependencyDashboard: true,
  "pre-commit": {
    enabled: true,
  },
  // "git-submodules": {
  //   enabled: true,
  // },
  dnsCache: true, // Warning: experimental feature
  enableHttp2: true,
  keepalive: true, // Warning: experimental feature
  packageRules: [
    {
      matchPackagePatterns: ["^python"],
      // Because of "renovate-bot/-/merge_requests/60" we will update later all repositories at once.
      allowedVersions: "<3.11",
    },
    {
      // Define this group so only Python major versions will have separate merge requests
      matchManagers: ["poetry"],
      matchUpdateTypes: ["major"],
      groupName: "all Python major",
      groupSlug: "all-major-python",
      rangeStrategy: "widen",
    },
    {
      matchUpdateTypes: ["minor", "patch", "major"],
      // While this is not a best practice, the `matchCurrentVersion` rule is disabled to save CI minutes even more.
      // matchCurrentVersion: "!/^0/", // exclude any dependencies which are pre-1.0.0 because those can make breaking changes at any time according to the SemVer spec
      groupName: "all dependencies except Python major",
      groupSlug: "all-minor-patch-major",
      rangeStrategy: "widen",
    },
  ],
  platformAutomerge: true,
  prHourlyLimit: 20, // The default is no limit, but set some random generous value to stay safe.
  rebaseWhen: "behind-base-branch",
};
```
.gitlab-ci.yaml
```yaml
variables:
  # Docker
  DOCKER_IMAGE_RENOVATE_PYTHON: ${CI_REGISTRY_IMAGE}/renovate_python:34.24
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
  # Renovate
  RENOVATE_BASE_DIR: $CI_PROJECT_DIR/renovate
  RENOVATE_ENDPOINT: $CI_API_V4_URL
  RENOVATE_PLATFORM: gitlab
  RENOVATE_ONBOARDING_CONFIG: '{"$$schema": "https://docs.renovatebot.com/renovate-schema.json", "extends": ["config:base"] }'
  RENOVATE_OPTIMIZE_FOR_DISABLED: "true"
  RENOVATE_REPOSITORY_CACHE: "enabled"
  RENOVATE_ONBOARDING: "false"
  RENOVATE_EXTENDS: "github>whitesource/merge-confidence:beta"
  RENOVATE_PERSIST_REPO_DATA: "true"
  RENOVATE_LOG_FILE: renovate-log.ndjson
  RENOVATE_LOG_FILE_LEVEL: debug
  LOG_LEVEL: info
  RENOVATE_TOKEN: $RENOVATE_TOKEN
  GITHUB_COM_TOKEN: $GITHUB_COM_TOKEN
  RENOVATE_CACHE_DIR: $CI_PROJECT_DIR/.cache/renovate_cache/
  RENOVATE_REQUIRE_CONFIG: "optional"
  RENOVATE_IGNORE_PR_AUTHOR: "false"
  RENOVATE_BINARY_SOURCE: "install"
  # Git LFS uses a pre-push git hook, which is disabled by "renovate" using `--no-verify`.
  # See https://github.com/renovatebot/renovate/issues/6842#issuecomment-824307938
  RENOVATE_GIT_NO_VERIFY: "[]"
```
