### DISCUSSION TITLE
Renovate not authorizing with private helm repository

### DISCUSSION THREAD

**Discussion by tarakaprabhuchinta** [renovatebot/renovate#20680] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.146.0

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Wanted end result.

Im using self hosted renovate and I am trying to use Renovate to access helm chart hosted in custom repository. I have supplied the token in Github Actions like this.

```
- name: Finding Dependencies For Dev
        uses: renovatebot/github-action@v34.146.0
        with:
          configurationFile: renovate-config/palm-ops-apps-dev.js
          token: 'x-access-token:${{ steps.get_token.outputs.app_token }}'
        env:
          LOG_LEVEL: 'debug'
          token: ${{ secrets.HELM_TOKEN }}
```

My config.js has host rules setup like this.

```
  "hostRules": [{
        "matchHost": "custom-chart-location-url",
        "token": process.env.token,
        "authType": "Basic"
    }]
```

So, if I pass the token in plain text format it authenticates without any problem. But, if I pass the token with process.env then the end result is always unauthorized. Github secret is having correct credential but, I think process.env is having some problem.

### What you tried so far.

The authentication works if the text is in plain format. But when I tried to acess token from envirnoment variable using process.env it doesn't seem to work. Im not sure what Im doing wrong.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: GET https://charts-url/index.yaml = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=401 retryCount=0, duration=98) (repository=org/repo-name, baseBranch=master)
DEBUG: Datasource unauthorized (repository=org/repo-name, baseBranch=master)
       "datasource": "helm",
```

</details>
