### DISCUSSION TITLE
Updating pre-commit additional dependencies

### DISCUSSION THREAD

**Discussion by adam-moss** [renovatebot/renovate#20708] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest official docker build

### If you're self-hosting Renovate, select which platform you are using.

gitlab.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

With `pre-commit` enable renovate correctly updates the dependencies.  I am unsure however if it should be, or can, update the `additional_dependencies` attribute of the `.pre-commit-config.yaml`.

For example an MR raised today for `prettier`:

```yaml
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0-alpha.5                                      < -- this updated
      hooks:
          - id: prettier
            additional_dependencies:
                - prettier@3.0.0-alpha.4                       < -- this was not updated
                - eslint-config-prettier
                - stylelint-config-prettier
                - prettier-plugin-java
                - prettier-plugin-sh
                - "@prettier/plugin-xml"
```

This may be that it is out-of-scope, or I need to include some comment directive or something?

### What you tried so far.

tbc

### Relevant debug logs

n/a
