### DISCUSSION TITLE
How to debug regexManagers?

### DISCUSSION THREAD

**Discussion by dbanty** [renovatebot/renovate#20881] [Request Help]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

In general, I want to know how to debug a regexManager. When looking at logs on https://app.renovatebot.com, I see no indication that my regexManager was run, nor any error messages about what's wrong with it.

For more info, I want to auto-update a string within my GitHub workflows:

```yaml
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Install Knope
        uses: knope-dev/action@v1
        with:
          version: 0.6.2
      - run: knope release --dry-run
```

That `version: 0.6.2` defines the version of the tool which should be auto-updated. It is [a crate called knope](https://crates.io/crates/knope).

### What you tried so far.

This is my Renovate config:

```json
{
  "extends": [
    "config:base",
    ":semanticCommitTypeAll(chore)"
  ],
  "rangeStrategy": "widen",
  "regexManagers": [
    {
      "fileMatch": ["release.*\\.yml"],
      "matchStrings": ["version:\\s*(?<currentValue>.*?)"],
      "depNameTemplate": "knope",
      "datasourceTemplate": "crate"
    }
  ]
}
```

I've tried several variations on `fileMatch` and `matchStrings`, none seem to give any feedback in the Renovate logs.

### Relevant debug logs

I haven't found any relevant logs, which is the main problem. I don't even know how to diagnose 😓. Here is a gist containing the full output of one run though: https://gist.github.com/dbanty/093db02c482add9f7c2fbc89e6b61d93
