### DISCUSSION TITLE
Docker Registry connections time out with Renovate v35

### DISCUSSION THREAD

**Discussion by uhthomas** [renovatebot/renovate#20982] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

35.8.1

### If you're self-hosting Renovate, select which platform you are using.

Bitbucket Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

N/A

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Wanted end result.

The latest version 35.8.1 cannot lookup private Docker dependencies. Previous versions (<35.0.0) seem to work okay. We have custom host rules for the private dependencies. It just says "failed to lookup dependency" and doesn't seem to actually attempt to look anything up. Renovate actively declines the existing PRs.

<img width="429" alt="Screenshot 2023-03-16 at 12 03 47" src="https://user-images.githubusercontent.com/9749173/225611277-8d6608ae-98f0-4687-8a29-b515949c76c7.png">

The above image shows me running an older version of Renovate, and it is then declined later by the new version.

Possibly related?

https://github.com/renovatebot/renovate/discussions/20809

```yaml
  envList:
    - name: DOCKER_REDACTED_USERNAME
      value: devtools-renovate
    - name: DOCKER_REDACTED_PASSWORD
      valueFrom:
        secretKeyRef:
          name: renovate
          key: dockerRegistryPassword
```

### What you tried so far.

I opened [this issue](https://github.com/renovatebot/renovate/issues/20972) but it was closed as invalid. I'd appreciate some help understanding what's invalid about it. With the same config, an old version of Renovate works, whereas the current one does not.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

**Comment by rarkins** [comment]
Hi, it's invalid because we specifically ask for Discussions first, and there was no reproduction, nor help logs. The last problem is not really yours, but altogether it is not actionable yet so therefore is not ready to be a bug issue. Please create Discussions first in future, it does not negatively impact how quickly we will look into things.

For now, please describe in more detail what type of registry it is, and how you configure the hostRules.

**Reply by uhthomas** [reply]
Of course, thanks. I'll keep that in mind.

I'm using [detectHostRulesFromEnv](https://docs.renovatebot.com/self-hosted-configuration/#detecthostrulesfromenv) and the host rules are exactly as I put in the original issue. If it helps, here are all the env host rules:

```yaml
envList:
    - name: RENOVATE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: renovate
          key: renovatePassword
    - name: GITHUB_COM_TOKEN
      valueFrom:
        secretKeyRef:
          name: renovate
          key: githubComToken
    - name: DOCKER_REDACTED_USERNAME
      value: redacted
    - name: DOCKER_REDACTED_PASSWORD
      valueFrom:
        secretKeyRef:
          name: renovate
          key: dockerRegistryPassword
    - name: DOCKER_USERNAME
      value: redacted
    - name: DOCKER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: renovate-docker-hub
          key: password
    - name: NPM_REDACTED_TOKEN
      valueFrom:
        secretKeyRef:
          name: redacted
          key: token
```

We're running the standard Docker [distribution](https://github.com/distribution/distribution) server. I'm a little concerned as mentioned previously this _does_ work with an older version of Renovate (v34.153.3 confirmed ok). What can I do to help understand what's happening?
