### DISCUSSION TITLE
velaci plugin should support template updates in addition to image updates

### DISCUSSION THREAD

**Discussion by colindean** [renovatebot/renovate#20988] [Suggest an Idea]
### Type of discussion.

I'm proposing an idea

### Tell us more.

The velaci plugin for Vela CI detects the `step[].image` Docker updates, but it does not currently detect `templates[].source` updates. 

For example, in this config:

```yaml
templates:
  - name: python-make-tasks
    source: git.example.com/myorg/vela-templates/python-make-tasks.star@3.3.2 ## THIS IS NOT DETECTED
    format: starlark
    type: github

steps:
- name: make tasks with Python 3.9
    template:
      name: python-make-tasks
      vars:
        python: py39

  - name: Set version and build package using Python 3.9
    image: python:3.9  # THIS IS DETECTED
    pull: not_present
    ruleset:
      event: [tag]
    commands:
      - pipx install poetry
      - poetry version "${BUILD_TAG}"
      - poetry build
```

I value that the step images are managed, but I'd love for the template sources to be managed, too.

I know this can be achieved with a custom matcher and that's what I'm going to do for now, but I figure that it's something that could be baked into the velaci support.
