### DISCUSSION TITLE
Docker unauthorized despite user and pw

### DISCUSSION THREAD

**Discussion by darox** [renovatebot/renovate#21037] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

35.12.0

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Wanted end result.

Docker tag update works. 

### What you tried so far.

For a long time, renovate has worked flawlessly for docker tags update, but after a few months, I can't get it working anymore. Even if I configure my dockerhub account:
```
{
  "repositories": ["darox/k8s-home"],
  "hostRules": [
    {
      "matchHost": "docker.io",
      "username": "dariomader",
      "password": "pw"
    }
  ]
}
```

It seems like Renovate can't obtain the 

### Relevant debug logs

```
         "message": "Response code 401 (Unauthorized)",
         "stack": "HTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/opt/buildpack/tools/renovate/34.157.1/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/34.157.1 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "authorization": "***********",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://index.docker.io/v2/prometheus/alertmanager/tags/list?n=10000",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 401,
           "statusMessage": "Unauthorized",
           "body": {
             "errors": [
               {
                 "code": "UNAUTHORIZED",
                 "message": "authentication required",
                 "detail": [
                   {
                     "Type": "repository",
                     "Class": "",
                     "Name": "prometheus/alertmanager",
                     "Action": "pull"
                   }
                 ]
               }
             ]
           },
           "headers": {
             "content-type": "application/json",
             "docker-distribution-api-version": "registry/2.0",
             "www-authenticate": "Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:prometheus/alertmanager:pull\",error=\"insufficient_scope\"",
             "date": "Sun, 19 Mar 2023 16:38:21 GMT",
             "content-length": "166",
             "strict-transport-security": "max-age=31536000",
             "connection": "close"
           },
           "httpVersion": "1.1",
           "retryCount": 0
         }
       }
 INFO: External host error causing abort - skipping (repository=darox/k8s-home)
 INFO: Repository finished (repository=darox/k8s-home)
       "cloned": true,
       "durationMs": 28860
```

**Comment by github-actions** [comment]
Hi there,

We have found that there's a problem with the logs. Depending on which situation applies follow one, some or all of these instructions.

### No logs at all
If you haven't posted any log yet, we need you to find and copy/paste the log into the issue template.

#### Finding logs on hosted app
<details><summary>Select me to read instructions</summary>

If you use the Renovate app (GitHub):
1. Go to the affected PR, and search for "View repository job log here"
1. Select the link to go to the "Mend Renovate Dashboard" and log in
1. You are now in the correct repository log overview screen
1. Copy/paste the correct log
1. Follow the steps in the **formatting your logs** section
</details>

#### Finding logs when self-hosting
<details><summary>Select me to read instructions</summary>

If you're running self-hosted, run with `LOG_LEVEL=debug` in your environment variables and search for whatever dependency/branch/PR that is causing the problem.
</details>

### Insufficient logs
<details><summary>Select me to read instructions</summary>

If you already gave us a log, and the Renovate team said it's not enough, then follow the instructions from the **No logs at all** section.
</details>

### Formatting your logs
<details><summary>Select me to read instructions</summary>

Please put your logs in a `<details>` and `<summary>` element like this:


    <details><summary>Select me to see logs</summary>

    ```
    Copy/paste your logs here, between the starting and ending backticks
    ```

    </details>

</details>

**Comment by darox** [comment, marked as answer]
Go it working with:
```
renovate:
  config: |
     {
          "repositories": ["darox/k8s-home"],
     }
cronjob:
  schedule: "0 */8 * * *"
secrets:
  RENOVATE_HOST_RULES: '[{"hostType":"docker","matchHost":"docker.io","username":"process.env.DOCKER_HUB_LOGIN","password":"process.env.DOCKER_HUB_PASSWORD"}]'
  DOCKER_HUB_PASSWORD: {{ .Values.docker.password | fetchSecretValue }}
  DOCKER_HUB_LOGIN: dariomader
  RENOVATE_AUTODISCOVER: "false"
  RENOVATE_TOKEN: {{ .Values.github.token | fetchSecretValue }}
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
         - matchExpressions:
             - key: kubernetes.io/arch
               operator: In
               values:
                 - amd64
```
