### DISCUSSION TITLE
Help with unsupported/unversioned value alpine-jre

### DISCUSSION THREAD

**Discussion by setchy** [renovatebot/renovate#21133] [Request Help] [answered]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Wanted end result.

 Looking to implement a rule like the following, the shuffle deprecated `adoptopenjdk/*` image uses to `eclipse-temurin`
 
 eg: `adoptopenjdk/openjdk11:alpine-jre` -> `eclipse-temurin:17.0.6_10-jre-alpine`
 
 ```yml
  packageRules: [
    {
      matchDatasources: ["docker"],
      matchPackagePatterns: ["^adoptopenjdk/"],
      replacementNameTemplate: "eclipse-temurin:17.0.6_10-jre-alpine"
    }
  ]
  ```

### What you tried so far.

I've tried 
* setting `allowedVersion` to`/^alpine-jre/`. 
* setting `verisoning` to loose

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Dependency adoptopenjdk/openjdk11 has unsupported/unversioned value alpine-jre (versioning=loose) (repository=****)
```

</details>

**Comment by viceice** [comment]
you can't use the version inside the package name. Use `replacementName` and `replacementVersion` config instead

**Reply by setchy** [reply]
Yes, good point, that was a copy/paste error on my part.  I have tried all of the other replacement options prior 😄 

As shared from the logs, it seems that it never gets the opportunity to perform the the replacement

```yml
packageRules: [
    {
      matchDatasources: ["docker"],
      matchPackageName: ["adoptopenjdk/openjdk11"],
      matchCurrentValue: "/alpine-jre/",
      replacementNameTemplate: "eclipse-temurin",
      replacementVersion: "17.0.6_10-jre-alpine",
      versioning: "loose"
    }
  ],
```

LOGs:
```
DEBUG: Dependency adoptopenjdk/openjdk11 has unsupported/unversioned value alpine-jre (versioning=loose) (repository=test-service)

DEBUG: packageFiles with updates (repository=wfscorp/test-service, baseBranch=master)
"config": {
 "dockerfile": [
           {
             "deps": [
               {
                 "depName": "adoptopenjdk/openjdk11",
                 "currentValue": "alpine-jre",
                 "replaceString": "adoptopenjdk/openjdk11:alpine-jre",
                 "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "depType": "final",
                 "updates": [],
                 "packageName": "adoptopenjdk/openjdk11",
                 "warnings": [],
                 "versioning": "docker"
               }
             ],
             "packageFile": "Dockerfile"
           }
         ],

```
