### DISCUSSION TITLE
Ensure that the artifact path is relative to the working directory

### DISCUSSION THREAD

**Discussion by micah** [renovatebot/renovate#21154] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

35.20

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

15.10.0

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

When my renovate job runs, it always says this at the end, I'm wondering how to fix that, or what it actually means:

```

Saving cache for successful job 00:01
Creating cache main-renovate-protected...
WARNING: /builds/tpx/tpy/renovate-cron/renovate: no matching files. Ensure that the artifact path is relative to the working directory (/builds/tpx/tpy/renovate-cron) 
Archive is up to date!                             
Created cache
Cleaning up project directory and file based variables 00:00
Job succeeded
```

My `config.js`:
```
module.exports = {
  endpoint: 'https://gitlab.local/api/v4/',
  platform: 'gitlab',
  onboardingConfig: {
    extends: ['config:base'],
  },
  persistRepoData: true,
  logLevel: 'debug',
  forkProcessing: 'enabled',
  repositories: [
      'test/repo'
  ],
};
```

My `renovate.json`:
```{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "packageRules": [
    {
      "matchUpdateTypes": ["minor", "patch"],
    }
  ],
  "extends": [
     "config:base",
     ":enableVulnerabilityAlertsWithLabel('security')",
  ]
}
```

My `.gitlab-ci.yml`:
```
stages:
  - cron

variables:
  RENOVATE_CONFIG_FILE: $CI_PROJECT_DIR/config.js
  RENOVATE_BASE_DIR: /cache/renovate
  RENOVATE_OPTIMIZE_FOR_DISABLED: 'true'
  RENOVATE_REPOSITORY_CACHE: 'true'

cache:
  key: ${CI_COMMIT_REF_SLUG}-renovate
  paths:
    - $CI_PROJECT_DIR/renovate

before_script:
  - mkdir -p $RENOVATE_BASE_DIR

cron:
  stage: cron
  image: renovate/renovate:35.20
  script:
    - renovate $RENOVATE_EXTRA_FLAGS
  only:
    refs:
      - schedule
```

### What you tried so far.

I have only searched bug reports to see if anyone else had this issue, I didn't know what else to try.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

**Comment by viceice** [comment]
you changed the renovate base dir to `/cache/...` so your gitlab cache path is wrong

**Comment by micah** [comment]
Unfortunately, I removed all of those, but I still get the error, should I be setting the gitlab cache path to something so it will be found?:

```
Saving cache for successful job 00:01
Creating cache main-renovate-protected...
WARNING: /builds/tpx/tpy/renovate-cron/renovate: no matching files. Ensure that the artifact path is relative to the working directory (/builds/tpx/tpy/renovate-cron) 
Archive is up to date!                             
Created cache
Cleaning up project directory and file based variables
```

My current configs, did I miss something?

```
stages:
  - cron

variables:
  RENOVATE_CONFIG_FILE: $CI_PROJECT_DIR/config.js
  RENOVATE_OPTIMIZE_FOR_DISABLED: 'true'
  RENOVATE_REPOSITORY_CACHE: 'true'

cache:
  key: ${CI_COMMIT_REF_SLUG}-renovate
  paths:
    - $CI_PROJECT_DIR/renovate

cron:
  stage: cron
  image: renovate/renovate:35.20
  script:
    - renovate $RENOVATE_EXTRA_FLAGS
  only:
    refs:
      - schedule
```

```
module.exports = {
  endpoint: 'https://gitlab.localhost/api/v4/',
  platform: 'gitlab',
  onboardingConfig: {
    extends: ['config:base'],
  },
  persistRepoData: true,
  logLevel: 'debug',
  forkProcessing: 'enabled',
  repositories: [
          'test/repo
  ],
};

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "packageRules": [
    {
      "matchUpdateTypes": ["minor", "patch"],
    }
  ],
  "extends": [
     "config:base",
     ":enableVulnerabilityAlertsWithLabel('security')",
  ]
}
```
