### DISCUSSION TITLE
Check for Helm chart versions inside Gitlab/Jenkins build scripts

### DISCUSSION THREAD

**Discussion by lathspell** [renovatebot/renovate#21224] [Suggest an Idea]
### Type of discussion.

I'm proposing an idea

### Tell us more.

Helm charts are often installed using Gitlab ".gitlab-ci.yml" or similar Jenkins control files.:

```
deploy_dev:
  stage: deploy_dev
  image: alpine/helm:3.11.2
  script:
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm repo update
    - helm upgrade foo bitnami/postgresql --version=12.1.9 --install --debug --wait -f values.yaml
```

Here version "12.1.9" ist not the Postgres version but the version of the Helm chart that is used to deploy Postgres.
Currently Renovate Bot does not seem to check for updates of such a helm chart.

It is probably a bit tricky to find and extract the version number from such a shell script but scanning for "helm install" or "helm upgrade" and then searching the same line for "--version=(.*)" should do the trick in most situations.

This request was originially filed as https://github.com/renovatebot/renovate/issues/21128 but moved here, as requested.
