### DISCUSSION TITLE
Updating "short versions" (`major`.`minor` only)

### DISCUSSION THREAD

**Discussion by multani** [renovatebot/renovate#21235] [Request Help] [answered]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### If you're self-hosting Renovate, select which platform you are using.

None

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

I have a GitHub Action that uses [`actions/setup-python`](https://github.com/actions/setup-python) this way (shorten):

```yaml
      - name: Setup Python                                                                
        id: py
        uses: actions/setup-python@v4                                                     
        with:
          python-version: "3.10"
```

I'd like to keep that version up to date, with:

```yaml
      - name: Setup Python                                                                
        id: py
        uses: actions/setup-python@v4                                                     
        with:
          python-version: "3.11"
```


### What you tried so far.

See it here: https://github.com/multani/renovate-python

I managed to capture the version in the GitHub Action using the `regexManager`:

```json5
  "regexManagers": [
    {
      "fileMatch": [".github/workflows/.*"],
      "matchStrings": ["python-version: \"(?<currentValue>\\S+)\"\\n"],
      "depNameTemplate": "python/cpython",
      "datasourceTemplate": "github-tags",
      "versioningTemplate": "docker",                                                                                                                                                                                                                                           
    },
  ]
```

But then, I'm not really sure how to update this version wrt. to the available versions on GitHub.

I managed to extract the major + minor version from the GitHub tags using a `packageRule`:

```json5
  "packageRules": [
    {
      "matchPackageNames": ["python/cpython"],
      "matchManagers": ["regex"],
      "matchDatasources": ["github-tags"],
      "extractVersion": "^v(?<version>\\d+\\.\\d+)",
    },
  ]
```

But then, it proposes me an update for 3.12, which is still in alpha as of today ([`v3.12.0a6`](https://github.com/python/cpython/releases/tag/v3.12.0a6)).

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: packageFiles with updates
{
  "baseBranch": "main",
  "config": {
    "regex": [
      {
        "datasourceTemplate": "github-tags",
        "depNameTemplate": "python/cpython",
        "deps": [
          {
            "currentValue": "3.10",
            "currentVersion": "3.10",
            "datasource": "github-tags",
            "depName": "python/cpython",
            "fixedVersion": "3.10",
            "isSingleVersion": true,
            "packageName": "python/cpython",
            "registryUrl": "https://github.com",
            "replaceString": "python-version: \"3.10\"\n",
            "sourceUrl": "https://github.com/python/cpython",
            "versioning": "docker",
            "warnings": [],
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "3.12",
                "newValue": "3.12",
                "releaseTimestamp": "2023-03-07T21:48:18.000Z",
                "newMajor": 3,
                "newMinor": 12,
                "updateType": "minor",
                "branchName": "renovate/python-cpython-3.x"
              }
            ]
          }
        ],
        "matchStrings": [
          "python-version: \"(?<currentValue>\\S+)\"\\n"
        ],
        "packageFile": ".github/workflows/python.yaml",
        "versioningTemplate": "docker"
      }
    ]
  }
}
[...]


```

</details>

**Comment by rarkins** [comment, marked as answer]
Try `"extractVersion": "^v(?<version>\\d+\\.\\d+)\\.\\d+$",`. The `$` means that the string must terminate after it matches the patch digit(s).

**Reply by multani** [reply]
Thanks, that was really useful and that works in my case.

For the reference, I also got another suggestion. In this case, the GitHub Action support [reading the version from an external file](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-the-python-version-file-input) `.python-version`, which is supported natively by [the `pyenv` manager](https://github.com/renovatebot/renovate/blob/2bd80d60716532d051f2fb66bb1a3c84fc379b20/lib/modules/manager/pyenv/index.ts).

So either:

replace my GitHub Action with:

```yaml
      - name: Setup Python                                                                
        id: py
        uses: actions/setup-python@v4                                                     
        with:
          python-version-file: .python-version
```
and have:
```
$ cat .python-version
3.10
```

In this case, Renovate works out of the box without any special configuration.

Another option is to use the same configuration as [the `pyenv` manager](https://github.com/renovatebot/renovate/blob/2bd80d60716532d051f2fb66bb1a3c84fc379b20/lib/modules/manager/pyenv/index.ts):

```json5
  "regexManagers": [
    {
      "fileMatch": [".github/workflows/.*"],
      "matchStrings": ["python-version: \"(?<currentValue>\\S+)\"\\n"],
      "depNameTemplate": "python",
      "datasourceTemplate": "docker",
      "versioningTemplate": "docker",
    },
  ],
```

And that seems to work too.
