### DISCUSSION TITLE
Self-hosted renovate action unable to write to logs

### DISCUSSION THREAD

**Discussion by toestreich** [renovatebot/renovate#21269] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

enovate/renovate:32.118.0-slim

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

Id like to write the logs to a json file in the github action runner but would settle for the logs just being outputted to stdout to help troubleshoot other issues. 

### What you tried so far.

Setting the GHA env variable to:
```
env:
  RENOVATE_LOG_FILE_LEVEL: "DEBUG" 
  RENOVATE_LOG_FILE: "./renovatelogs.json"
  ```

and setting the variables in the json config file - when I do this I dont get any errors, renovate just fails to create/write to the file

### Relevant debug logs

<details><summary>Logs</summary>

```
Status: Downloaded newer image for renovate/renovate:32.118.0-slim
Error: EACCES: permission denied, open './renovatelogs.json'
Error: The process '/usr/bin/docker' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/renovatebot/github-action/v32.118.0/dist/index.js:1679:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/renovatebot/github-action/v32.118.0/dist/index.js:1662:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/renovatebot/github-action/v32.118.0/dist/index.js:1556:27)
Error: Error: The process '/usr/bin/docker' failed with exit code 1
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:10[92](https://github.com/Tomtestash/test-DVWA/actions/runs/4577295492/jobs/8082524262#step:9:93):16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)```

</details>

**Comment by viceice** [comment]
please provide the action yaml

**Reply by toestreich** [reply]
Please see below:

The steps prior to running are just to pull the default config from a central repo if its the first time running on that repo 

```
name: Golden Security Pipeline
on:
  workflow_dispatch: 

env:
  RENOVATE_LOG_FILE_LEVEL: "DEBUG"
  RENOVATE_LOG_FILE: "./renovatelogs.json"

jobs:
  renovate: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false
      - name: Check first run
        shell: bash
        run: |
          if test -f "renovate.json"; then echo "initial=False" >> $GITHUB_ENV; else  echo "initial=True" >> $GITHUB_ENV; fi
      - if: ${{ env.initial }} == 'True'
        uses: actions/checkout@v3
        with:
          repository: _ORG_/renovate-config
          token: ${{ secrets.RENOVATE_TOKEN }}
          ref: main
          clean: false
      - name: Add Local Repo
        run: |
          jq '.repositories=["${{ github.repository }}"]' < renovate.json >> final.json  
      - name: Cat
        run: |
          cat final.json
      - name: Cat logs
        shell: bash
        run: |
          touch ./renovatelogs.json
      - name: cat file
        shell: bash
        run: |
          ls -l 
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.118.0
        with:
          configurationFile: final.json
          token: ${{ secrets.RENOVATE_TOKEN }}

      - name: ls
        shell: bash
        run: |
          ls
      - name: Cat logs
        shell: bash
        run: |
          cat ./renovatelogs.json
          
         ```
