### DISCUSSION TITLE
AWS Lambda Runtime Upgrade Suggestions

### DISCUSSION THREAD

**Discussion by chezsmithy** [renovatebot/renovate#21586] [Suggest an Idea]
### Type of discussion.

I'm proposing an idea

### Tell us more.

Curious if anyone else might be interested in having AWS Lambda runtime upgrade support?

We currently allow our developers to request the runtime in custom app-spec files we process in our build pipelines. As such we would need a regex manager with a source of runtime reference data in renovate to support suggesting automated upgrades.

Example YML from our app-spec:

```
lambda_functions:
        - function_name: s3_events
          handler: s3events
          runtime: go1.x
```
