### DISCUSSION TITLE
Included file `https://gitlab.com/renovate-bot/renovate-runner/-/blob/main/templates/renovate.gitlab-ci.yml` does not have valid YAML syntax!

### DISCUSSION THREAD

**Discussion by lmilbaum** [renovatebot/renovate#21584] [Request Help] [answered]
### How are you running Renovate?

self-hosted

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

Renovate workflow working

### What you tried so far.

.gitlab-ci.yml file:

```yaml
---
include:
    - 'https://gitlab.com/renovate-bot/renovate-runner/-/blob/main/templates/renovate.gitlab-ci.yml'

renovate:
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
```

### Relevant debug logs

Unable to create pipeline
Included file `https://gitlab.com/renovate-bot/renovate-runner/-/blob/main/templates/renovate.gitlab-ci.yml` does not have valid YAML syntax!
