### DISCUSSION TITLE
Buildkite: Support multiple plugins per pipeline section

### DISCUSSION THREAD

**Discussion by rarkins** [renovatebot/renovate#21663] [Suggest an Idea]
#### This is a:

* [ ] Bug report (non-security related)
* [x] Feature request
* [ ] I'm not sure which of those it is

#### Please describe the issue:

Currently Renovate only looks for the first line of a `plugins:` section in the pipeline yml. Instead, we should support multiple nested plugins if found.

**Comment by rarkins** [comment]
- [ ] Define a valid example buildkite definition to use which has multiple plugins in one pipeline
- [ ] Enhance the buildkite/extract function to extract multiple dependencies per file
- [ ] Enhance the buildkite/update function (if necessary) to support patching a multi-dependency file. It's possible it already works
- [ ] Test it against a real repo. Run multiple times to make sure it doesn't unnecessarily keep editing each time.
- [ ] Add unit tests

**Comment by rarkins** [comment]
@toolmantim @ticky do you have a valid example of a buildkite file with multiple plugins per pipeline?

**Comment by toolmantim** [comment]
I've been meaning to reach out to fix Renovate's handling of our plugin syntax, because we've changed it from being a map/hash to being an array. And since we have, Renovate has stop parsing them it seems.

This is the old syntax, which is still valid, but not recommended because older Buildkite agents won't guarantee the order in which they're run:

```yml
steps:
  - plugins:
      docker-login#v2.0.1:
        username: xyz
      docker-compose#v2.5.1:
        build: app
        image-repository: index.docker.io/myorg/myrepo
  - wait
  - command: test.sh
    plugins:
      docker-login#v2.0.1:
        username: xyz
      docker-compose#v2.5.1:
        run: app
```

The new syntax is:

```yml
steps:
  - plugins:
      - docker-login#v2.0.1:
          username: xyz
      - docker-compose#v2.5.1:
          build: app
          image-repository: index.docker.io/myorg/myrepo
  - wait
  - command: test.sh
    plugins:
      - docker-login#v2.0.1:
          username: xyz
      - docker-compose#v2.5.1:
          run: app
```

I think https://github.com/renovatebot/renovate/blob/44d119823fdf904101bb05a476708c9297872be8/lib/manager/buildkite/extract.js#L20 is the part that needs updating, perhaps to `^\s+(?:-\s+)?([^#]+)#([^:]+):`
