### DISCUSSION TITLE
Easy way to manage versions in multiple files?

### DISCUSSION THREAD

**Discussion by tanguynicolas** [renovatebot/renovate#21816] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

35.32.1

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitLab CE

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

Hello, I would like to ask a last question before the implementation of Renovate in my company.

Is there a simple way to make sure that when the Helm manager updates a chart, it also updates another file?

Helm chart like
```yaml
apiVersion: v2
name: redis
description: A Helm chart for Kubernetes

type: application
version: 16.13.0

appVersion: "6.2.7"

dependencies:
- name: redis
  version: "16.13.0"
  repository: "https://charts.bitnami.com/bitnami"
```

Another file like
```plaintext
redis_version="16.13.0"
```

### What you tried so far.

I tried to create a regex manager, but I end up doing exactly the same thing as the Helm manager, only worse. The only difference is that I can maybe put another file in fileMatch, with an associated regex so I can update the version.

But this solution seems to me to be a DIY solution. I wonder if there isn't a better way?

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

**Comment by secustor** [comment]
No, if you want to update update some custom dependency your only choice is to use the regex manager. 

That being said, upgrades will get merged if they have the same `depName` or the same `groupName`.    
you can set the second using packageRules.

**Reply by tanguynicolas** [reply]
So in my case, do I have to go through a comment like: `"# renovate: datasource=helm depName=elasticsearch registryUrl=https://helm.elastic.co versioning=helm"`?

**Reply by secustor** [reply]
No, you can also hardcode this values in your regex manager and only extract the version from your file. https://docs.renovatebot.com/modules/manager/regex/#configuration-templates

**Reply by tanguynicolas** [reply]
Oh yes of course, but I use a centralized configuration to all my repositories, so it must remain universal, I can't afford to hardcode these values in the configuration.

Thanks for these explanations !

I take the opportunity to ask you a small subsidiary question, is there a method to tell the Helm manager not to touch a version if it matches a particular string?

For example :
```yaml
apiVersion: v2
name: myapp
description: A Helm chart

type: application
version: 0.1.0

appVersion: "5.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: 45.10.1
    repository:  https://prometheus-community.github.io/helm-charts
  - name: thanos
    version: **dont_touch_here**
    repository: https://charts.bitnami.com/bitnami
  - name: loki-stack
    version: 2.6.5
    repository: https://grafana.github.io/helm-charts
```

I thought of something like
```json
    "helmv3": {
        "enabled": "(containsString depName 'dont_touch_here')"
    },
```
But don't think it would work. Is there a more appropriate way?
