### DISCUSSION TITLE
Renovate ignoring HTTP_PROXY when contacting https://api.github.com/graphql returns ECONNREFUSED

### DISCUSSION THREAD

**Discussion by JossWhittle** [renovatebot/renovate#21849] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

renovatebot/github-action@v36.0.3

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

Desired result is that renovate running in self-hosted mode (via the Github Action) in a CI script executing on a self-hosted Github ARC runner where the runner is behind a corporate proxy should be able to make requests to the Github API.

### What you tried so far.

Previously our Renovate config was working as expected on Github hosted runners. When migrating to self-hosted runners which are located behind our corporate HTTP_PROXY we are struggling to get Renovate to be able to contact the github API through the proxy.

We can curl the github API directly and it returns as expected and also running the action to retrieve an app token works correctly which also requires communicating with the github api. 

The HTTP_PROXY, HTTPS_PROXY, and NO_PROXY variables are set and are working correctly except for from renovate's perspective.

```
name: Renovate
on:
  workflow_dispatch:
  repository_dispatch:
    types: [renovate]
  schedule:
    - cron: '0/5 * * * *'

env:
  HTTP_PROXY: "http://proxy:8080"
  HTTPS_PROXY: "http://proxy:8080"
  NO_PROXY: "10.0.0.0/8,127.0.0.1,localhost,192.168.0.0/16"
  
jobs:
  renovate:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: clone repo
        uses: actions/checkout@v3
        
      - name: test curl
        run: |
          curl https://api.github.com/graphql

      - name: generate token
        id: generate-token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ vars.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_PRIVATE_KEY }}

      - name: renovate
        uses: renovatebot/github-action@v36.0.3
        with:
          configurationFile: .github/renovate.js
          token: ${{ steps.generate-token.outputs.token }}

        env:
          LOG_LEVEL: debug
          RENOVATE_HARBOR_REGISTRY: ${{ vars.HARBOR_REGISTRY }}
          RENOVATE_HARBOR_USER: ${{ vars.HARBOR_USER }}
          RENOVATE_HARBOR_TOKEN: ${{ secrets.HARBOR_TOKEN }}

```

In the debug logs below we show an excerpt of a POST request made to https://api.github.com/graphql  which resulted in an ECONNREFUSED code.

### Relevant debug logs

<details><summary>Logs</summary>

```
Run renovatebot/github-action@v36.0.3
  with:
    configurationFile: .github/renovate.js
    token: ***
  env:
    HTTP_PROXY: http://proxy:8080/
    HTTPS_PROXY: http://proxy:8080/
    NO_PROXY: 10.0.0.0/8,127.0.0.1,localhost,192.168.0.0/16
    LOG_LEVEL: debug
    RENOVATE_HARBOR_REGISTRY: ***
    RENOVATE_HARBOR_USER: robot$SwanseaUniversityMedical
    RENOVATE_HARBOR_TOKEN: ***

/usr/local/bin/docker run --env LOG_LEVEL --env RENOVATE_HARBOR_REGISTRY --env RENOVATE_HARBOR_USER --env RENOVATE_HARBOR_TOKEN --env RENOVATE_TOKEN=*** --env RENOVATE_CONFIG_FILE=/github-action/renovate.js --volume /runner/_work/nrda-renovate/nrda-renovate/.github/renovate.js:/github-action/renovate.js --volume /tmp:/tmp --user 1000:0 --rm renovate/renovate:slim

...

DEBUG: POST https://api.github.com/graphql = (code=ECONNREFUSED, statusCode=-1 retryCount=0, duration=4) (repository=SwanseaUniversityMedical/nrda-container-airflow)
DEBUG: Unexpected GraphQL Error (repository=SwanseaUniversityMedical/nrda-container-airflow)
       "err": {
         "name": "RequestError",
         "code": "ECONNREFUSED",
         "timings": {
           "start": 1682601948154,
           "socket": 1682601948154,
           "lookup": 1682601948157,
           "error": 1682601948158,
           "phases": {"wait": 0, "dns": 3, "total": 4}
         },
         "message": "connect ECONNREFUSED 140.82.121.6:443",
         "stack": "RequestError: connect ECONNREFUSED 140.82.121.6:443\n    at ClientRequest.<anonymous> (/opt/buildpack/tools/renovate/35.61.0/node_modules/got/dist/source/core/index.js:970:111)\n    at Object.onceWrapper (node:events:628:26)\n    at ClientRequest.emit (node:events:[525](https://github.com/SwanseaUniversityMedical/nrda-renovate/actions/runs/4820328239/jobs/8584669276#step:5:526):35)\n    at ClientRequest.emit (node:domain:489:12)\n    at ClientRequest.origin.emit (/opt/buildpack/tools/renovate/35.61.0/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at TLSSocket.socketErrorListener (node:_http_client:502:9)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket.emit (node:domain:489:12)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/35.61.0 (https://github.com/renovatebot/renovate)",
             "accept": "application/vnd.github.machine-man-preview+json",
             "authorization": "***********",
             "content-type": "application/json",
             "content-length": "441",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://api.github.com/graphql",
           "hostType": "github",
           "username": "",
           "password": "",
           "method": "POST",
           "http2": false
         }
       },
       "query": "\nquery($owner: String!, $name: String!) {\n  repository(owner: $owner, name: $name) {\n    id\n    isFork\n    isArchived\n    nameWithOwner\n    hasIssuesEnabled\n    autoMergeAllowed\n    mergeCommitAllowed\n    rebaseMergeAllowed\n    squashMergeAllowed\n    defaultBranchRef {\n      name\n      target {\n        oid\n      }\n    }\n  }\n}\n",
       "options": {
         "variables": {
           "owner": "SwanseaUniversityMedical",
           "name": "nrda-container-airflow"
         }
       }
```

</details>

**Comment by rarkins** [comment]
Try running renovate CLI standalone with proxy settings. If it works, then you know the problem is related to how the env is passed through GitHub actions

**Reply by JossWhittle** [reply]
I modified the CI workflow to install and run the renovate CLI and it works correctly as expected before failing when the Github Action tries to run. So this does appear to be an issue with how the Github Action is passing through the proxy variables.

Does anything stick out to you that I might be doing wrong for the action? I have tried also including the HTTP_PROXY variables additionally prefixed as RENOVATE_HTTP_PROXY to see if that would pass them through but to no avail.

```
name: Renovate
on:
  workflow_dispatch:
  repository_dispatch:
    types: [renovate]
  schedule:
    - cron: '0/5 * * * *'

env:
  HTTP_PROXY: "http://proxy:8080"
  HTTPS_PROXY: "http://proxy:8080"
  NO_PROXY: "10.0.0.0/8,127.0.0.1,localhost,192.168.0.0/16"
  
jobs:
  renovate:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: clone repo
        uses: actions/checkout@v3
        
      - name: test curl
        run: |
          curl https://api.github.com/graphql

      - name: generate token
        id: generate-token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ vars.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          
      - name: install node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
          
      - name: renovate cli
        run: |
          npm i -g renovate
          renovate
          
        env:
          RENOVATE_CONFIG_FILE: .github/renovate.js
          RENOVATE_TOKEN: ${{ steps.generate-token.outputs.token }}
          LOG_LEVEL: debug
          RENOVATE_HARBOR_REGISTRY: ${{ vars.HARBOR_REGISTRY }}
          RENOVATE_HARBOR_USER: ${{ vars.HARBOR_USER }}
          RENOVATE_HARBOR_TOKEN: ${{ secrets.HARBOR_TOKEN }}

      - name: renovate
        uses: renovatebot/github-action@v36.0.3
        with:
          configurationFile: .github/renovate.js
          token: ${{ steps.generate-token.outputs.token }}

        env:
          LOG_LEVEL: debug
          RENOVATE_HARBOR_REGISTRY: ${{ vars.HARBOR_REGISTRY }}
          RENOVATE_HARBOR_USER: ${{ vars.HARBOR_USER }}
          RENOVATE_HARBOR_TOKEN: ${{ secrets.HARBOR_TOKEN }}
```

Where the task executes with the following env:

```
Run npm i -g renovate
  npm i -g renovate
  renovate
  shell: /usr/bin/bash -e {0}
  env:
    HTTP_PROXY: http://proxy:8080
    HTTPS_PROXY: http://proxy:8080
    NO_PROXY: 10.0.0.0/8,127.0.0.1,localhost,192.168.0.0/16
    RENOVATE_CONFIG_FILE: .github/renovate.js
    RENOVATE_TOKEN: ***
    LOG_LEVEL: debug
    RENOVATE_HARBOR_REGISTRY: ***
    RENOVATE_HARBOR_USER: robot$SwanseaUniversityMedical
    RENOVATE_HARBOR_TOKEN: ***
```

**Comment by viceice** [comment, marked as answer]
https://github.com/renovatebot/github-action#environment-variables

by default renovate action doesn't pass all ENV to the docker container

**Reply by JossWhittle** [reply]
No dice. We did try prefixing them with RENOVATE_ in addition to specifying them normally.

From old issue threads from when proxy config was originally added (that I can't find now I want to link them) there was a comment from @rarkins about being open to supporting these three env vars directly with no prefixing and it appears they were implemented that way (hence renovate CLI detecting them).

**Reply by rarkins** [reply]
Keep reading further down that guide

**Reply by JossWhittle** [reply]
```
env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|GITHUB_COM_TOKEN|NODE_OPTIONS|AWS_TOKEN|HTTP_PROXY|HTTPS_PROXY|NO_PROXY)$"
```

Do you mean like this? I'll give it a go.

**Reply by JossWhittle** [reply]
Setting the `env-regex` filter did the trick. Potentially worth adding a sentence under https://github.com/renovatebot/github-action#environment-variables specifically mentioning HTTP_PROXY so that it shows up in search results. 

With the filter set I found that I didn't even need to specify HTTP_PROXY variables in the CI script since they are set in the deployment of the ARC Runner objects in kubernetes. The following CI script worked.

```
name: Renovate
on:
  workflow_dispatch:
  repository_dispatch:
    types: [renovate]
  schedule:
    - cron: '0/5 * * * *'
  
jobs:
  renovate:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - name: generate token
        id: generate-token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ vars.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_PRIVATE_KEY }}

      - name: renovate
        uses: renovatebot/github-action@v36.0.3
        with:
          configurationFile: .github/renovate.js
          token: ${{ steps.generate-token.outputs.token }}
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|GITHUB_COM_TOKEN|HTTP_PROXY|HTTPS_PROXY|NO_PROXY)$"

        env:
          LOG_LEVEL: debug
          RENOVATE_HARBOR_REGISTRY: ${{ vars.HARBOR_REGISTRY }}
          RENOVATE_HARBOR_USER: ${{ vars.HARBOR_USER }}
          RENOVATE_HARBOR_TOKEN: ${{ secrets.HARBOR_TOKEN }}
```

Outside the purview of the Renovate project but in case anyone else finds this thread while searching the ARC Runner has the following to set the proxy variables at that level.



```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: my-org-arc

spec:

  template:
    spec:

      # Limit runner to all repos on our organization (that the Github App for the ARC controller has access too)
      organization: my-org

      # Runner must be selected in workflow yaml using:
      # runs-on: [self-hosted, linux, x64]
      labels:
        - linux
        - x64

      # Runner can't phone out to github.com without being able to traverse the proxy
      env:
        - name: http_proxy
          value: "http://proxy:8080"
        - name: https_proxy
          value: "http://proxy:8080"
        - name: no_proxy
          value: "10.0.0.0/8,127.0.0.1,localhost,192.168.0.0/16"
```

Many thanks @rarkins @viceice :)
