### DISCUSSION TITLE
Issues Using Aws Machine Image Datasource

### DISCUSSION THREAD

**Discussion by meghan-kast** [renovatebot/renovate#21941] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

I am trying to configure a self-hosted version of renovate bot to automatically pull AMI version changes. I see a new version properly pulled when I run renovate; however, as seen in the logs, I get an error message "Could not determine new digest for update (datasource: aws-machine-image)" & the AMI version is not properly updated.

### What you tried so far.

I have a regexManager configured in my renovate.json like this:
```
"regexManagers": [
    {
      "fileMatch": [".*"],
      "matchStrings": [
        ".*amiFilter=(?<packageName>.*?)\n(.*currentImageName=(?<currentDigest>.*?)\n)?(.*\n)?.*?(?<depName>[a-zA-Z0-9-_:]*)[ ]*?[:|=][ ]*?[\"|']?(?<currentValue>ami-[a-z0-9]{17})[\"|']?.*"
      ],
      "datasourceTemplate": "aws-machine-image",
      "versioningTemplate": "aws-machine-image"
    }
  ],
```

I have a line in my terraform that looks like this:
```
locals {
  # Latest AWS EKS AMI
  # amiFilter=[{"Name":"owner-id","Values":["602401143452"]},{"Name":"name","Values":["amazon-eks-node-1.21-*"]}]
  # currentImageName=amazon-eks-node-1.21-v20211003
  renovate_ami_id      = "ami-0be0ed539bf62558c"
}
```

I was wondering if anyone can see anything that I have done wrong for renovate to not update the AMI ID once the new version is being pulled? I have added the debug logs to this discussion. 

### Relevant debug logs

<details><summary>Logs</summary>

```
"regex": [
           {
             "deps": [
               {
                 "depName": "renovate_ami_id",
                 "packageName": "[{\"Name\":\"owner-id\",\"Values\":[\"602401143452\"]},{\"Name\":\"name\",\"Values\":[\"amazon-eks-node-1.21-*\"]}]",
                 "currentValue": "ami-0be0ed539bf62558c",
                 "currentDigest": "amazon-eks-node-1.21-v20211003",
                 "datasource": "aws-machine-image",
                 "versioning": "aws-machine-image",
                 "replaceString": "  # amiFilter=[{\"Name\":\"owner-id\",\"Values\":[\"602401143452\"]},{\"Name\":\"name\",\"Values\":[\"amazon-eks-node-1.21-*\"]}]\n  # currentImageName=amazon-eks-node-1.21-v20211003\n  renovate_ami_id      = \"ami-0be0ed539bf62558c\"",
                 "updates": [
                   {
                     "bucket": "non-major",
                     "newVersion": "ami-0ac2f1bf9769d65f3",
                     "newValue": "ami-0ac2f1bf9769d65f3",
                     "newDigest": "amazon-eks-node-1.21-v20230304",
                     "releaseTimestamp": "2023-03-05T17:39:51.000Z",
                     "newMajor": 1,
                     "newMinor": 0,
                     "updateType": "patch",
                     "branchName": "renovate/renovate_ami_id-1.x"
                   }
                 ],
                 "warnings": [
                   {
                     "message": "Could not determine new digest for update (datasource: aws-machine-image)",
                     "topic": "[{\"Name\":\"owner-id\",\"Values\":[\"602401143452\"]},{\"Name\":\"name\",\"Values\":[\"amazon-eks-node-1.21-*\"]}]"
                   }
                 ],
                 "currentVersion": "ami-0be0ed539bf62558c",
                 "isSingleVersion": true,
                 "fixedVersion": "ami-0be0ed539bf62558c"
               }
             ],
             "matchStrings": [
               ".*amiFilter=(?<packageName>.*?)\n(.*currentImageName=(?<currentDigest>.*?)\n)?(.*\n)?.*?(?<depName>[a-zA-Z0-9-_:]*)[ ]*?[:|=][ ]*?[\"|']?(?<currentValue>ami-[a-z0-9]{17})[\"|']?.*"
             ],
             "datasourceTemplate": "aws-machine-image",
             "versioningTemplate": "aws-machine-image",
             "packageFile": "modules/aws/bootstrap/common.tf"
           },
```

</details>

**Comment by secustor** [comment]
v36.0.0 is not released yet. Please update the version.

**Reply by meghan-kast** [reply]
@secustor -
Sorry I was actually using renovatebot/github-action@v36.0.0 and not specifying a renovate-version which I believe just pulls the latest docker image? I will try forcing it to be version 35.0.0 & see if that fixes the issue though

**Reply by rarkins** [reply]
I think we'd still want you using the latest.

**Reply by secustor** [reply]
I have been referring to the discussion questionnaire. 

If you are using the latest version, does the ec2 instance running the action has permission to describe the AMI image?

**Reply by meghan-kast** [reply]
@secustor Yep it does - this is the github workflow running the self-hosted renovate bot. As you can see, the IAM role assumed gives permissions to describe the AMI images, and those AWS credentials are passed as env variables into the renovate docker image. The role has IAM privileges to "Action": ["ec2:DescribeImages"]. I don't think describing images is the issue, as you can see in the debug logs that I attached, renovate successfully pulls a new AMI image but then fails to update it in the terraform definition.

```
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::************:role/ami-lookup-role
          aws-region: us-west-2
          role-duration-seconds: 3600
      
      - name: Get Renovate Token
        id: get_token
        uses: tibdex/github-app-token@v1
        with:
          private_key: ${{ secrets.renovate_private_key }}
          app_id: ${{ secrets.renovate_app_id }}
      
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v36.0.0
        with:
          configurationFile: renovate.json
          token: '${{ steps.get_token.outputs.token }}'
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|AWS_REGION|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY|AWS_SESSION_TOKEN)$"
        env:
          LOG_LEVEL: 'debug'
```
