### DISCUSSION TITLE
Lockfile diffs

### DISCUSSION THREAD

**Discussion by rarkins** [renovatebot/renovate#22041] [Suggest an Idea]
It would be helpful to PR reviewers if updates to Lock files (both npm and yarn) could include a "diff" of what changed. 

For repositories pinning every dependency, they already know today whenever "direct" (package.json) dependencies are upgrading, but this would help track when indirect (2nd+ level) dependencies update. 

For repositories retaining semver ranges for some or all dependencies, this would help to show explicitly when direct versions are being updated too. 

Right now the main intention of this is to assist with backtracking when things have gone wrong (eg need to find and revert a bad upgrade that had passed tests). 

Difficulty is high due to need to reverse engineer lockfile logic (npm and yarn) and even format (yarn)

**Comment by rarkins** [comment]
https://yarnpkg.com/en/package/@yarnpkg/lockfile

**Comment by edmorley** [comment]
Instead of reverse engineering lockfile format, could the diff instead be generated from comparing eg a `yarn list --json` before/after?

**Comment by rarkins** [comment]
Actually the package I linked to earlier is “official” for yarn so it would not really be reverse engineering now.

**Comment by edmorley** [comment]
Ah sorry I misread that URL as a link to the Yarn lockfile docs (I'm so used to npmjs.com links for package listings themselves).

**Comment by rarkins** [comment]
We might need to experiment to work out how this should look and what people like. One possibility would be dividing into two categories: direct and indirect (transitive) dependencies. And then for each, listing how many major/minor/patch changes, with the ability for the user to expand to see the details.

It can be a little hard to know these exactly though, e.g. many people might have "duplicate" transitive dependencies because a single common one can't be found. If a lock file update removes the duplication so that now there's just a single version left, does that count as a minor or patch, for example? It's hard to define.

At the very least we can have a list of dependencies changed, and a count of major/minor/changes that ignores the edge case I mentioned above.

A really simple approach would be lines of code changed! But that is kind of viewable easily already in the PR diff.

**Comment by HonkingGoose** [comment]
We discussed some approaches in #7536, I'm getting stuck on the "figuring out how the Renovate Markdown should look for a real lock file PR" part... I'm really sorry, but I can't for the life of me figure out how it should look when dependencies can be updated multiple times, have transient dependencies, etc... This is probably only doable by somebody who has a better understanding of lock files than me... 😄 

Also GitHub now has a "rich diff" button for some lockfile update PRs (I don't think this supports all languages yet). So this feature is there in some shape, but not integrated into Renovate itself.

I like the `octoclairvoyant` page with the summary of release notes. We could maybe figure out a way to use that to create the changelogs between the lock file updates? 
https://octoclairvoyant.vercel.app/?repo=renovatebot%2Frenovate&from=23.95.0&to=24.22.3

So maybe it's a good idea to re-evaluate our options?

**Comment by rarkins** [comment]
https://github.com/Simek/yarn-lock-changes

**Comment by Leksat** [comment]
And https://github.com/marketplace/actions/composer-diff
<details>
<summary>My lock-file-changes.yml GitHub workflow for both Yarn and Composer lock changes</summary>

```yaml
name: Lock File Changes
on: [pull_request]
jobs:
  lock_file_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # yarn.lock
      - name: Yarn Lock Changes
        uses: Simek/yarn-lock-changes@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          collapsibleThreshold: 1

      # composer.lock
      - name: Generate composer diff
        id: composer_diff
        uses: IonBazan/composer-diff-action@v1
        with:
          base: ${{ github.event.pull_request.base.sha }}:apps/silverback-drupal/composer.lock
          target: apps/silverback-drupal/composer.lock
      - uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.composer_diff.outputs.composer_diff }}
        with:
          header: composer-diff
          # Make the message look similar to the one produced by
          # Simek/yarn-lock-changes.
          message: |
            ## `composer.lock` changes
            
            <details>
            <summary>Click to toggle table visibility</summary>
            ${{ steps.composer_diff.outputs.composer_diff }}
            </details>
      - uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.composer_diff.outputs.composer_diff == 0 }}
        with:
          header: composer-diff
          delete: true
```

</details>
