### DISCUSSION TITLE
regexManagers - Could not extract Cargo.toml

### DISCUSSION THREAD

**Discussion by Oliboy50** [renovatebot/renovate#22070] [Request Help] [answered]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

I want to update the `serde_dynamo`'s `features = ["aws-sdk-dynamodb+0_25"]` version accordingly with the `aws-sdk-dynamodb` version below

e.g. I want Renovate to make a single PR which updates the following `Cargo.toml` file from: 
```toml
[package]
name = "sample-project"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_dynamo = { version = "=4.2.0", features = ["aws-sdk-dynamodb+0_25"] }
aws-config = { version = "=0.55.0" }
aws-sdk-dynamodb = { version = "=0.25.1" }
```

to:
```toml
[package]
name = "sample-project"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_dynamo = { version = "=4.2.2", features = ["aws-sdk-dynamodb+0_27"] }
aws-config = { version = "=0.55.2" }
aws-sdk-dynamodb = { version = "=0.27.0" }
```

### What you tried so far.

Here is a simple reproduction repository: https://github.com/Oliboy50/renovate-discussions-22070

Updating the 3 `crate` dependencies (serde_dynamo, aws-config and aws-sdk-dynamodb) in a single PR is easy, but updating `features = ["aws-sdk-dynamodb+0_27"]` is what I struggle with.

```json
{
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
        "config:base"
    ],
    "packageRules": [
        {
            "matchDepPatterns": [
                "^aws-",
                "^serde_dynamo$"
            ],
            "groupName": "aws"
        }
    ],
    "regexManagers": [
        {
            "fileMatch": ["^Cargo\\.toml$"],
            "matchStrings": [
                "\"aws-sdk-dynamodb\\+(?<currentValue>\\d+_\\d+)\""
            ],
            "versioningTemplate": "loose",
            "autoReplaceStringTemplate": "\"aws-sdk-dynamodb\\+{{{newMajor}}}_{{{newMinor}}}\"",
            "depNameTemplate": "aws-sdk-dynamodb",
            "datasourceTemplate": "crate"
        }
    ]
}
```

### Relevant debug logs

<details><summary>Logs</summary>

```
"regex": [
      {
        "deps": [
          {
            "depName": "aws-sdk-dynamodb",
            "currentValue": "0_25",
            "datasource": "crate",
            "versioning": "loose",
            "replaceString": "\"aws-sdk-dynamodb+0_25\"",
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "0.27.0",
                "newValue": "0.27.0",
                "newMajor": 0,
                "newMinor": 27,
                "updateType": "minor",
                "branchName": "renovate/aws"
              }
            ],
            "packageName": "aws-sdk-dynamodb",
            "warnings": [],
            "sourceUrl": "https://github.com/awslabs/aws-sdk-rust",
            "registryUrl": "https://crates.io",
            "dependencyUrl": "https://crates.io/crates/aws-sdk-dynamodb",
            "currentVersion": "0_25",
            "isSingleVersion": true,
            "fixedVersion": "0_25"
          }
        ],
        "matchStrings": [
          "\"aws-sdk-dynamodb\\+(?<currentValue>\\d+_\\d+)\""
        ],
        "depNameTemplate": "aws-sdk-dynamodb",
        "datasourceTemplate": "crate",
        "versioningTemplate": "loose",
        "autoReplaceStringTemplate": "\"aws-sdk-dynamodb\\+{{{newMajor}}}_{{{newMinor}}}\"",
        "packageFile": "Cargo.toml"
      }
    ]

...

DEBUG: Value is not updated(packageFile="Cargo.toml", branch="renovate/aws")
{
  "manager": "regex",
  "expectedValue": "0.27.0",
  "foundValue": "0_25"
}
DEBUG: Starting search at index 134(packageFile="Cargo.toml", branch="renovate/aws")
{
  "depName": "aws-sdk-dynamodb"
}
DEBUG: Found match at index 134(packageFile="Cargo.toml", branch="renovate/aws")
{
  "depName": "aws-sdk-dynamodb"
}
DEBUG: Could not extract Cargo.toml(branch="renovate/aws")
WARN: Error updating branch: update failure(branch="renovate/aws")
```

</details>
