### DISCUSSION TITLE
Crossplane Support

### DISCUSSION THREAD

**Discussion by patrickleet** [renovatebot/renovate#22363] [Suggest an Idea]
### Type of discussion.

I'm proposing an idea

### Tell us more.

Crossplane is a project for Kubernetes that allows consumers to create resources, similar to Terraform, but via the Kubernetes control plane by installing versioned providers - such as provider-aws, or provider-gcp. Users can also created versioned packages of their own configs.

I'd like renovate to monitor these dependencies as well.

Everything is found on https://marketplace.upbound.io/ 

Here's an example Helm provider https://marketplace.upbound.io/providers/crossplane-contrib/provider-helm/

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-helm
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.14.0
```

And a configuration (https://marketplace.upbound.io/configurations/devops-toolkit/dot-application/v0.5.28)

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: crossplane-app
spec:
  package: xpkg.upbound.io/devops-toolkit/dot-application:v0.3.9
``` 

Also, it'd be nice to get PRs for Helm releases created by Crossplane's provider-helm:

```yaml
    - name: externalSecrets
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        spec:
          rollbackLimit: 3
          forProvider:
            namespace: external-secrets
            chart:
              name: external-secrets
              repository: https://charts.external-secrets.io
              version: "0.8.1"
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-external-secrets"
        - fromFieldPath: spec.id
          toFieldPath: spec.providerConfigRef.name
```

Is there a simple way to achieve this now?
