### DISCUSSION TITLE
Helmfile manager should support `helm registry login` when updating helmfile.lock.

### DISCUSSION THREAD

**Discussion by mugioka** [renovatebot/renovate#22486] [Suggest an Idea]
I have a private helm chart stored in an GitHub Container Registry with OCI format and use it in helmfile.
ex.)
```
repositories:
- name: private-charts
  url: ghcr.io/mugioka/private-charts # this is the private oci registry, so i cannot download chart without authentication
  oci: true

releases:
- name: test
  chart: private-charts/test
  version: 1.0.0
```

Then i created hostRules bellows
```json
{
  // snip
  "hostRules": [
    {
      "matchHost": "ghcr.io",
      "hostType": "docker",
      "username": "user",
      "encrypted": {
        "password": "encrypted password"
      }
    }
  ]
}
```

By adding the above settings, i can detect when a new version of a chart has been published to datasource(docker).
However, when helmfile manager actually tries to update the version, an authentication error occurs when updating helmfile.lock with the `helmfile deps` command.
```
Error: failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized
```
The reason is that when helmfile manager runs the `helmfile deps` command, it tries to get the chart listed in the version of helmfile.yaml from the private chart registry, but helmfile manager are not authenticated via `helm registry login` or `docker login`. 

So, we should support `helm registry login` command when updating helmfile.lock like [helmv3](https://github.com/renovatebot/renovate/pull/13726).

**Comment by rarkins** [comment]
Seems closely related to #19241

This would require more details in order to be converted to a feature request issue: details/examples of how hostRules should be converted to login commands (you have left out the important part)

**Reply by mugioka** [reply]
Thank you for reply.

> Seems closely related to https://github.com/renovatebot/renovate/issues/19241

The above issue seems to be focused on the datasource (docker) and not the helmfile manager. What we would like to achieve is a situation where updating helmfile.lock does not fail with an authentication error by logging into the helm registry when helmfile.yaml/hostRules is set as follows

helmfile.yaml
```yaml
repositories:
- name: private-charts
  url: ghcr.io/mugioka/private-charts # this is the private oci registry, so i cannot download chart without authentication
  oci: true

releases:
- name: test
  chart: private-charts/test
  version: 1.0.0
```

hostRules
```json
{
  // snip
  "hostRules": [
    {
      "matchHost": "ghcr.io",
      "hostType": "docker",
      "username": "user",
      "encrypted": {
        "password": "encrypted password"
      }
    }
  ]
}
```

> This would require more details in order to be converted to a feature request issue: details/examples of how hostRules should be converted to login commands (you have left out the important part)

Sorry i understood. I will clarify more solutions and examples for this feature request.
