### DISCUSSION TITLE
Support ArgoCD multi sources applications

### DISCUSSION THREAD

**Discussion by gaeljw** [renovatebot/renovate#22545] [Suggest an Idea]
### Tell us more.

ArgoCD recently added a feature called "multi sources apps".

The idea is that in addition to supporting those kind of definition:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  source:
    repoURL: somehelmrepo.github.io
    chart: some-chart
    targetRevision: 1.2.0
```

ArgoCD now supports the following:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  sources:
    - repoURL: somehelmrepo.github.io
      chart: some-chart
      targetRevision: 1.2.0
      helm:
        valueFiles:
          - $values/some-folder/values.yaml
    - repoURL: http://gitlab.cop/my-repo.git
      targetRevision: HEAD
      ref: values
```

That is, a `sources` (notice the **s**) attribute with multiple items.

It would be nice to support the same features currently supported with a single `source`. I'm mainly thinking of supporting Helm chart revision upgrades.

I can provide a real life example if needed.
