### DISCUSSION TITLE
using SSH config under kubernetes not working

### DISCUSSION THREAD

**Discussion by RyuunosukeDS3** [renovatebot/renovate#22554] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

35.98.4

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

I'm trying to use SSH with renovate under kubernetes. I want it to be able to proceed clone the repository.

### What you tried so far.

I've tried creating a secret with the following format:

```yaml
secretData:
  id_rsa: ******
  id_rsa_pub: *******
```

both are converted to base64.

And then referencing it in the renovate kubernetes yaml like this:

```yaml
ssh_config:
  # -- Whether to enable the use and creation of a secret containing .ssh files
  enabled: true

  # Provide .ssh config file contents
  # -- Contents of the id_rsa file
  id_rsa: ''
  # -- Contents of the id_rsa_pub file
  id_rsa_pub: ''
  # -- Contents of the config file
  config: ''

  # or provide the name of an existing secret to be read instead.
  # -- Name of the existing secret containing a valid .ssh configuration
  existingSecret: 'ssh-key-secret'
  ```
  But it simply wont work...
  
  I've set `gitAuthor` and `gitUrl`, btw.
  
  

### Relevant debug logs

<details><summary>Logs</summary>

```
ERROR: Repository has unknown error (repository=devops/matheus-teste)
       "err": {
         "task": {
           "commands": [
             "ls-remote",
             "--heads",
             "git@git****.com.br:devops/matheus-teste.git"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "Connection closed by **IP** port 22\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n",
         "stack": "Error: Connection closed by **IP** port 22\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n\n    at Object.action (/opt/buildpack/tools/renovate/35.87.0/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/opt/buildpack/tools/renovate/35.87.0/node_modules/simple-git/src/lib/plugins/plugin-store.ts:29:29)\n    at /opt/buildpack/tools/renovate/35.87.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:127:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/opt/buildpack/tools/renovate/35.87.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:14)\n    at GitExecutorChain.<anonymous> (/opt/buildpack/tools/renovate/35.87.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:100:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/buildpack/tools/renovate/35.87.0/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
       }
```

</details>

EDIT: on the configs I pasted above I had the "enable" set as false, but that's incorrect, it was properly enabled when I tried xD
