### DISCUSSION TITLE
helmfile: support dependencies of a release

### DISCUSSION THREAD

**Discussion by PatrickSpies** [renovatebot/renovate#22560] [Suggest an Idea]
### Tell us more.

helmfile supports adding dependencies to an existing chart (see https://helmfile.readthedocs.io/en/latest/advanced-features/#adding-dependencies-without-forking-the-chart)

Example:
```yaml
repositories:
  - name: k8s-as-helm
    url: https://ameijer.github.io/k8s-as-helm/

releases:

  - name: rbac
    chart: k8s-as-helm/serviceaccount
    version: 1.0.0
    dependencies:
      - chart: k8s-as-helm/clusterrolebinding
        version: 1.0.0
```

Running renovate with enabled helmfile-manager is only detecting helm-chart serviceaccount but not the additional chart clusterrolebinding.

Looking at https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/helmfile/types.ts and https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/helmfile/extract.ts the `dependencies`-keyword for a release is currently not supported by renovate!? Would be nice to add this :)
