### DISCUSSION TITLE
FluxCD OCI Helm Chart with prereleases and build information

### DISCUSSION THREAD

**Discussion by justusbunsi** [renovatebot/renovate#22601] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

Docker image `renovate/renovate:35.105.5@sha256:3b0a83ce5c463e230b67e633c592f02f0ccfeb2944352e7d067fa64da8d01e43`

### If you're self-hosting Renovate, select which platform you are using.

Gitea

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

I would like Renovate to update version prereleases that are referenced within a FluxCD HelmRelease.

Lets say there is this `HelmRepository`:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 6h
  url: oci://ghcr.io/kyverno/charts
  type: oci
```

which is used in this `HelmRelease` (please ignore the fact that the specified version does not exist for that Chart):

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 6h
  releaseName: kyverno
  targetNamespace: kyverno
  install:
    createNamespace: true
  chart:
    spec:
      chart: kyverno
      version: "2.6.0-rc1+build1"
      interval: 6h
      sourceRef:
        kind: HelmRepository
        name: kyverno
  values:
    networkPolicy:
      enabled: true
```

I am aware of the recently implemented feature for Flux OCI Helm releases (https://github.com/renovatebot/renovate/pull/22291). Unfortunately, this does not solves the prerelease scenario.

### What you tried so far.

From the [Helm documentation](https://helm.sh/docs/topics/registries/) regarding OCI registries:

> SemVer tags that include build information can be pushed and used. OCI registries don't support `+` as a tag character. Helm translates the `+` to `_` when stored as a tag.

So the imaginary Kyverno prerelease will be pushed as `2.6.0-rc1_build1` instead of `2.6.0-rc1+build1`. Renovate retrieves the tag `2.6.0-rc1_build1` from the registry. If I use that string in the FluxCD HelmRelease and set `versioning: "loose"`, Renovate is capable of providing an update PR for those versions.

On the other hand, FluxCD work with valid semver (using `+` instead of the `_`). That's why FluxCD is not able to find the version `2.6.0-rc1_build1` but can pull `2.6.0-rc1+build1`.

I am scratching my head for about 3 hours now, trying to solve that situation with `regex manager`. But it seems I am not able to have `currentValue: 2.6.0-rc1+build1` while fetching tags with `_` instead of `+` and then finally writing `newValue: 2.6.0-rc1+build2` in the PR.

Is that a bug for FluxCD OCI Helm Charts? To me it feels like somewhere in the codebase should happen a replacement of `+` for OCI Helm Charts in general. Have I missed an obvious solution for this problem? Hope all this makes sense. If not, please ask and I try to explain. I posted this as a question since I am not sure whether or not this is me not finding the correct settings.

Thanks for your response.
