### DISCUSSION TITLE
`flux` should support same docker image heuristics like `helm-values` manager

### DISCUSSION THREAD

**Discussion by viceice** [renovatebot/renovate#22698] [Suggest an Idea]
### Tell us more.

`helm-values` manager supports some general image constructs inside `values.yaml`

**sample**
```yaml
image:
  repository: nginx
  tag: 1.16.1
```

`flux` manager should support this too inside `values` of `HelmRelease` resources.

**sample**
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: search
spec:
  interval: 30m
  chart:
    spec:
      chart: elasticsearch
      version: 19.10.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: specxplorer
      interval: 12h
  values:
    image:
      repository: bitnami/elasticsearch
      tag: 7.17.10-debian-11-r13
```

Workaround is to use regex manager.
