### DISCUSSION TITLE
Renovate for Docker image that doesn't use semantic versioning?

### DISCUSSION THREAD

**Discussion by loganmarchione** [renovatebot/renovate#22754] [Request Help] [answered]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

I have a file called `cluster/apps/media/jellyfin-vue.yaml` that is a Kubernetes manifest. The image `jellyfin-vue:unstable.2023-05-31.6e056b4` doesn't use semantic versioning tags. Instead it uses `unstable.year-month-day.commit_hash`.

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-vue-deployment
  namespace: media
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: jellyfin-vue
  template:
    metadata:
      labels:
        app: jellyfin-vue
    spec:
      containers:
        - name: jellyfin-vue
          image: ghcr.io/jellyfin/jellyfin-vue:unstable.2023-05-31.6e056b4
          ports:
            - containerPort: 80
          env:
            - name: DEFAULT_SERVERS
              value: https://jellyfin.${SECRET_INTERNAL_DOMAIN_NAME}
```

As an example, this is the latest unstable version, which isn't being seen by Renovate. [Here](https://github.com/jellyfin/jellyfin-vue/pkgs/container/jellyfin-vue) is a link to the GHCR page with more examples. Am I missing something easy here?

```
ghcr.io/jellyfin/jellyfin-vue:unstable.2023-06-12.88761db
```

### What you tried so far.

I've had good luck with `loose` on other non-standard packages, but it's not working for this one. I'm getting `invalid-value` in the logs (below).

```
  "packageRules": [
    {
      "matchPackageNames": ["ghcr.io/jellyfin/jellyfin-vue"],
      "versioning": "loose"
    }
```

### Relevant debug logs

<details><summary>Logs</summary>

```
      {
        "deps": [
          {
            "depName": "ghcr.io/jellyfin/jellyfin-vue",
            "currentValue": "unstable.2023-05-31.6e056b4",
            "replaceString": "ghcr.io/jellyfin/jellyfin-vue:unstable.2023-05-31.6e056b4",
            "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
            "datasource": "docker",
            "updates": [],
            "packageName": "ghcr.io/jellyfin/jellyfin-vue",
            "warnings": [],
            "versioning": "loose",
            "skipReason": "invalid-value"
          },
          {
            "depName": "Deployment",
            "currentValue": "apps/v1",
            "datasource": "kubernetes-api",
            "versioning": "kubernetes-api",
            "updates": [],
            "packageName": "Deployment",
            "warnings": [],
            "currentVersion": "apps/v1",
            "fixedVersion": "apps/v1"
          },
          {
            "depName": "Ingress",
            "currentValue": "networking.k8s.io/v1",
            "datasource": "kubernetes-api",
            "versioning": "kubernetes-api",
            "updates": [],
            "packageName": "Ingress",
            "warnings": [],
            "currentVersion": "networking.k8s.io/v1",
            "fixedVersion": "networking.k8s.io/v1"
          }
        ],
        "packageFile": "cluster/apps/media/jellyfin-vue.yaml"
      },
```

</details>
