### DISCUSSION TITLE
Kustomize: Renovate remote files referenced in generators

### DISCUSSION THREAD

**Discussion by Preisschild** [renovatebot/renovate#22810] [Suggest an Idea]
### Tell us more.

Renovate already renovates helmcharts, remote resources, components and images, but it does not renovate remote files referenced in configMap- and secretGenerators.

## Example

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: ingress-nginx-dashboards
    files:
      - https://raw.githubusercontent.com/kubernetes/ingress-nginx/helm-chart-4.6.0/deploy/grafana/dashboards/nginx.json
secretGenerator:
  - name: ingress-nginx-dashboards
    files:
      - https://raw.githubusercontent.com/kubernetes/ingress-nginx/helm-chart-4.6.0/deploy/grafana/dashboards/nginx.json 
 ```
