### DISCUSSION TITLE
Release notes in PR for Helm charts stored as OCI artifacts

### DISCUSSION THREAD

**Discussion by MShekow** [renovatebot/renovate#23001] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

35.142.0

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

Suppose I have a `Chart.yaml` of the following form:

```yaml
apiVersion: v2
name: foo
type: application

version: 0.1.0

appVersion: 2.8.0

dependencies:
- name: some-chart
  version: "2.8.0"
  repository: "oci://registry:5000/synced-helm-charts"
```

I would like Renovate to create a PR (which updates `some-chart`) that contains the **Release notes** for the `some-chart` Helm chart (as of now, the release notes are missing). Note that I synchronized the Helm chart from some ChartMuseum to the Docker image registry using a tool, which I modified so that it sets the `org.opencontainers.image.source` annotation to point to the GitHub repository that has GitHub releases for each chart.

Note that I did _not_ set the `org.opencontainers.image.revision` annotation, not sure whether it is needed.

### What you tried so far.

--
