### DISCUSSION TITLE
How to access the current date with the hosted app on GitHub?

### DISCUSSION THREAD

**Discussion by kevinmatthes** [renovatebot/renovate#23051] [Request Help] [answered]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

I would like to update the release date of a CFF reference entry whenever the corresponding project creates a new GitHub release.

[CFF](https://github.com/citation-file-format/citation-file-format) is a technology to make software citable by the provision of a configuration file named CITATION.cff which has a YAML syntax.  GitHub accepts this format and renders a "Cite this repository" blob on the project's main page which contains the defined citation information in both APA and BibTeX formats such that users can copy and paste these information to their lists of references.  A CFF file is allowed to contain a list of references itself; a sane use case is to add the CFF data of the bound dependencies there.

I apply the Rust library [Clap](https://github.com/clap-rs/clap) in one of my projects and cite its CFF data in the CITATION.cff of that project.  The Clap maintainers only update the version and release date fields when publishing a new version to the Rust package registry such that technically, it would suffice to just update exactly these fields in the reference entry in my CITATION.cff whenever Renovate suggests an update for Clap instead of having to re-extract the entire data from Clap's CITATION.cff each time manually.

Luckily, the Clap maintainers also create a GitHub release for each version they publish to the package registry such that I could fetch the version information from the generated release and update the version field with a regex matcher.  The only thing I do not know is how to update the date; is there maybe a template available?

Here is an example for the CFF reference entry for Clap before the update:

```yaml
  - type: software
    date-released: 2023-06-28 # clap date
    version: 4.3.9 # clap version
    abstract: A full featured, fast Command Line Argument Parser for Rust
    authors:
      - alias: kbknapp
        family-names: Knapp
        given-names: Kevin B.
      - name: The Clap Community
    license:
      - Apache-2.0
      - MIT
    repository-artifact: https://crates.io/crates/clap
    repository-code: https://github.com/clap-rs/clap
    title: clap
    url: https://docs.rs/clap
```

And here is how the reference entry will look after the update:

```yaml
  - type: software
    date-released: 2023-06-30 # clap date
    version: 4.3.10 # clap version
    abstract: A full featured, fast Command Line Argument Parser for Rust
    authors:
      - alias: kbknapp
        family-names: Knapp
        given-names: Kevin B.
      - name: The Clap Community
    license:
      - Apache-2.0
      - MIT
    repository-artifact: https://crates.io/crates/clap
    repository-code: https://github.com/clap-rs/clap
    title: clap
    url: https://docs.rs/clap
```

### What you tried so far.

A possible solution I already considered in theory would basically look as follows:

```json5
{
  packageRules: [
    {
      matchManagers: [
        "regex",
      ],
      matchPackageNames: [
        "clap",
      ],
    },
  ],
  regexManagers: [
    {
      datasourceTemplate: "github-releases",
      depNameTemplate: "clap",
      fileMatch: [
        "^CITATION\\.cff$",
      ],
      matchStrings: [
        "    version: (?<currentValue>\\d+\\.\\d+\\.\\d+) # clap version",
      ],
      packageNameTemplate: "clap-rs/clap",
    },
  ],
}
```

This should at least update the version field.  I am sure that the update for the release date would just require another `matchString` but I do not know how to define the replacement rules for the current date.
