### DISCUSSION TITLE
[Helm Values] Precise the image key in yaml

### DISCUSSION THREAD

**Discussion by qjoly** [renovatebot/renovate#23062] [Request Help]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

In my `values.yaml` file, the key containing the image is common.image.name and the tag corresponds to the key common.image.tag.
```
common:
  image:
    repository:
      name: null
      isPrivate: false
      secretName: null
    name: gotify/server
    tag: 2.2.4
    pullPolicy: Always
```

I get this error with Renovate: 

```
warning Dependency Lookup Warnings warning

    Renovate failed to look up the following dependencies: Failed to look up docker package [object Object].

Files affected: charts/gotify/values.yaml
```

### What you tried so far.

Nothing, I do not want to change the `values.yaml` file and I don't know what parameter I can change in renovateBot
