### DISCUSSION TITLE
Include `renovate-config-validator` functionality into Renovate

### DISCUSSION THREAD

**Discussion by remal** [renovatebot/renovate#23192] [Suggest an Idea]
### Tell us more.

Migration to version 36 becomes tricky if a repository has a complex configuration.

Could you make Renovate validate the config and display all issues?

This issue becomes very critical when `extends` sections are used. In this case, `renovate-config-validator` doesn't work correctly. So, it would be very useful if Renovate could:
1. Load the repository config
2. Process all `extends` sections (including nested `extends` - when the repository config includes another config, which includes another config, etc...)
3. Validate the result config

Thanks!

**Comment by rarkins** [comment]
Does a dry run satisfy that? e.g. `renovate --dry-run=extract foo/bar`

**Reply by remal** [reply]
It's not that simple - I use `extends` with `local>...`.

Moreover, old config sections like `java` are simply ignored in v36. So even if I execute Renovate with `--dry-run`, I won't know about issues like this.

I think it would be beneficial for all users if it was implemented as a part if normal run.

**Reply by rarkins** [reply]
I don't understand what you mean. A dry run is much more deeper than a config validation. Also sections like Java are migrated, not ignored.

**Reply by lmilbaum** [reply]
I would suggest using pre-commit such that the configuration is validated before your code is pushed

**Reply by remal** [reply]
@rarkins are you sure that java sections are migrated? I'm asking because they didn't work unless I migrated them manually.

Unfortunately can't show logs and code, as it was an internal project

**Reply by remal** [reply]
@lmilbaum does Renovate config validator resolve `extends` section?

**Comment by rpdelaney** [comment]
We are using pre-commit to validate the renovate configuration against a schema. Our configurations are relatively lightweight, but in case it might help you, here's the configuration:
```yaml
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.23.2                                                
  hooks:                                                     
    - id: check-renovate                                     
      name: validate renovate config                         
```
