### DISCUSSION TITLE
use mvn (maven) in postUpgradeTask

### DISCUSSION THREAD

**Discussion by marwin1991** [renovatebot/renovate#23259] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

35.135.0

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

use maven in `postUpgradeTask`

### What you tried so far.

.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

**Comment by rarkins** [comment]
You will need to run `install-tool maven 3.9.2` first

**Comment by marwin1991** [comment]
Do you know how to do it in GitHub Actions?

**Reply by rarkins** [reply]
It's no different to any other. Have you got any post upgrade task working yet?

**Reply by marwin1991** [reply]
honestly, I don't know what it is. I use GitLab CI on a daily basis and I would use before_script there.

My workflow looks like this:

https://github.com/logchange/logchange/blob/main/.github/workflows/renovate.yml

Should I add some step before renovate to install maven ?

**Reply by rarkins** [reply, marked as answer]
No, installing maven can be done as part of the post upgrade task

**Reply by marwin1991** [reply]
```
Command failed: install-tool maven 3.9.2
No java defined - aborting
```

Form dockefile-full I see thath there is java, should I set JAVA_HOME or what?

**Reply by rarkins** [reply]
Sorry, if you're using the default slim image then you'll need to install java first with `install-tool java 17.0.7+7`

**Reply by marwin1991** [reply]
I think i am using full version. `Unable to find image 'ghcr.io/renovatebot/renovate:latest' locally`

and i have:

```yml
        with:
          token: ${{ secrets.LOGCHANGE_PAT_TOKEN }}
          configurationFile: .github/renovate-config.js
          useSlim: false
```

**Reply by rarkins** [reply]
That's the slim one

**Comment by marwin1991** [comment]
Final solution:

Instaling maven in postUpgradeTask in renovate-config.js

```js
  postUpgradeTasks: {
    //commands: ['curl -sSL https://raw.githubusercontent.com/logchange/logchange/main/add_entry.sh | bash -s -- -DfileName=renovate-{{{depNameSanitized}}}-{{{newVersion}}}.yml -Dtitle="Upgraded {{{depName}}} from {{{currentVersion}}} to {{{newVersion}}}" -Dauthor=marwin1991 -Dtype=dependency_update -Dlink.name=notes -Dlink.url={{{url}}}'],
    commands: [
      'install-tool maven 3.9.2',
      'mvn dev.logchange:logchange-maven-plugin:add --non-recursive -DbatchMode -DfileName=renovate-{{{depNameSanitized}}}-{{{newVersion}}}.yml -Dtitle="Upgraded {{{depName}}} from {{{currentVersion}}} to {{{newVersion}}}" -Dauthor=marwin1991 -Dtype=dependency_update -Dlink.name=notes -Dlink.url={{{url}}}'],
    fileFilters: ['**/*.yml'],
    executionMode: 'update',
  }
```

Change GitHub action to use full version

```yml
name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v38.1.11
        with:
          token: ${{ secrets.LOGCHANGE_PAT_TOKEN }}
          configurationFile: .github/renovate-config.js
          renovate-version: 36.5.2-full
          useSlim: false
        env:
          RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: ".*"
          LOG_LEVEL: debug
```
