### DISCUSSION TITLE
GitLab - Registry and Packages, public and private

### DISCUSSION THREAD

**Discussion by adam-moss** [renovatebot/renovate#23251] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

36

### If you're self-hosting Renovate, select which platform you are using.

gitlab.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

I'm trying to update our renovate config so it can authenticate to our private container and package registries on gitlab.com whilst also maintaining access to public ones.

### What you tried so far.

I added the following to our `config.yaml` (yaml being used due to some knarly regex prettier kept mangling)

```yaml
    # authentication for private repositories
    - enabled: true
      hostType: docker
      matchHost: registry.gitlab.com
      token: process.env.GITLAB_REGISTRY_TOKEN

    - enabled: true
      hostType: gitlab-packages
      matchHost: https://gitlab.com
      token: process.env.GITLAB_PACKAGES_TOKEN

    - enabled: true
      hostType: gitlab-releases
      matchHost: https://gitlab.com
      token: process.env.GITLAB_RELEASES_TOKEN

    - enabled: true
      hostType: gitlab-tags
      matchHost: https://gitlab.com
      token: process.env.GITLAB_TAGS_TOKEN
```

Unfortunately this led to use getting 401 unauthorised errors for all requests to those `hostType`.

Ideally we'd scope the match host rule to our group only but I'm not sure that is possible.
