### DISCUSSION TITLE
Authenticating to private ECR repository from GitHub Actions?

### DISCUSSION THREAD

**Discussion by andredms** [renovatebot/renovate#23292] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

renovatebot/github-action@v38.1.6

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

Authenticate to a private ECR repository from within GitHub Actions. 

### What you tried so far.

Here is my GitHub Actions file, which runs on a schedule but can also be manually triggered. It assumes an AWS role with the required ECR permissions and then passes the credentials to `renovate.js`. Not sure if I’m missing something? Is it possible to grab an ECR password in the workflow and then just pass that in instead of the AWS credentials? 

`workflow.yml`:

```
name: Renovate
on:
  schedule:
    - cron: '30 22 * * 0'
    # Targeting Monday 08:30AM UTC+10 (Sydney, ignoring AEDT)
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS role for deployment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::xyz:role/renovate-role
          aws-region: eu-west-1
          mask-aws-account-id: 'no'

      - name: Run Renovate
        uses: renovatebot/github-action@v38.1.6
        with:
          configurationFile: renovate.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          RENOVATE_REPOSITORIES: 'andredms/my-repo'
          LOG_LEVEL: 'debug'
```

`renovate.js`:

```
module.exports = {
  extends: ["config:base"],
  onboarding: false,
  requireConfig: false,
  rebaseWhen: "conflicted",
  dependencyDashboard: true,
  enabledManagers: ["helm-values"],
  hostRules: [
    {
      matchHost: "https://xyz.dkr.ecr.eu-west-1.amazonaws.com",
      hostType: "docker",
      username: process.env.AWS_ACCESS_KEY_ID,
      password: process.env.AWS_SECRET_KEY,
    }
  ]
};
```

Any ideas? 

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: ECR getAuthorizationToken error
DEBUG: Failed to get authHeaders for getTags lookup
DEBUG: Failed to look up package xyz.dkr.ecr.eu-west-1.amazonaws.com/...
```

</details>

**Comment by viceice** [comment]
yes, check the action readme, especially the environment variables section. you need to change the ENV regex to pass your custom variables

**Reply by andredms** [reply]
I've added the regex but still getting the same error:


```
      - name: Run Renovate
        uses: renovatebot/github-action@v38.1.6
        with:
          configurationFile: renovate.js
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|RENOVATE_REPOSITORIES|AWS_SECRET_ACCESS_KEY|AWS_ACCESS_KEY_ID)$"
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          RENOVATE_REPOSITORIES: 'andredms/my-repo'
          LOG_LEVEL: 'debug'
```
