### DISCUSSION TITLE
Help with regex

### DISCUSSION THREAD

**Discussion by jmctune** [renovatebot/renovate#23379] [Request Help] [answered]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

I am interested in using renovate to update buildkite plugins in a pipeline file. There is support for buildkite using the buildkite manager, but there isn't any support for git-refs. We don't use tags in our files as these are mutable.

I am trying to parse for all keys under the "plugins" key into different groups. I can only seem to get it to match the first key under "plugins", but I am interested in grabbing them all. Additionally, some plugins use ssh, https, or just reference the depName as this is valid for Buildkite - so there's no real pattern (that I can see) here.

Here's an example of the yaml I am working with. I am trying to get both plugin keys to match under `  - label: "Repo sync"`, as well as the next key to match under `  - label: "Repo sync 2"`.

```yaml
steps:
  - label: "Is my branch up to date?"
    env:
      PULL_REQUEST_BRANCH: "$PULL_REQUEST_BRANCH"

  - label: "Repo sync"
    depends_on: branch_is_up_to_date
    agents:
      cpu: 0.5 
      memory: 2G
    branches: "main"
    plugins:
      - ssh://git@github.com/myorg/a-buildkite-plugin.git#v1.0.0:
          role: "arn:aws:sts::999999999999:role/role"
          region: aws-region
      - envato/aws-assume-role#aea2dc1ae6be19eec04de73518ef3f0070ae5f41:
          parameters:
            ROLLBAR_ACCESS_TOKEN: /path/to/rollbar

  - label: "Repo sync 2"
    plugins:
      - envato/aws-assume-role#aea2dc1ae6be19eec04de73518ef3f0070ae5f41:
          role: "arn:aws:sts::999999999999:role/role"
    agents:
      cpu: 0.5 
      memory: 2G
    branches: "main"

  - label: "Load Tests Pipeline"
    agents:
      cpu: 0.5 
      memory: 2G
    branches: "!main !v*.*.*"
    command: buildkite-agent pipeline upload
    env:
      PULL_REQUEST_BRANCH: "$PULL_REQUEST_BRANCH"
```

### What you tried so far.

https://regex101.com/r/K5yzgy/1

### Relevant debug logs

<details><summary>Logs</summary>

```
Logs are not relevant for this question.
```

</details>
