### DISCUSSION TITLE
Helm chart version resolving with ArgoCD ApplicationSet and external YAML

### DISCUSSION THREAD

**Discussion by szpak** [renovatebot/renovate#23427] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.129.0

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

I've been successfully using Renovate with ArgoCD configuration file where the chart version was got from Git tags:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nice-app
  ...
spec:
  destination:
    ...
  project: some-project
  source:
    path: .
    repoURL: git@git.example.com:ops/charts/generic-chart.git
    targetRevision: v0.6.1
    helm:
      ...
```

Unfortunately, the DevOps team remodeled the Argo configuration to use `ApplicationSet` instead of `Application` and currently the configuration is not properly recognized any longer.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-nice-app
  labels:
    app.kubernetes.io/declarative-app: "true"
    project: "some-project"
spec:
  generators:
    - git:
        repoURL: git@git.example.com:ops/environments/non-production.git
        revision: HEAD
        files:
          - path: "apps/**/*-my-nice-app.yaml"
  template:
    metadata:
      ...
    spec:
      source:
        helm:
          valueFiles:
            - values.yaml
          values: |-
            {{values}}
        ...
```

The generator files are plain YAML files, e.g.:

```yaml
name: test-my-nice-app
chartRepoUrl: "git@git.example.com:ops/charts/generic-chart.git"
chartName: ""
targetRevision: v0.6.1
namespace: some-namespace
cluster: "c001"
managedBy: "helm"
values: |-
  ...
```

I wonder, what would be simplest way to convience Renovate to look into the pointed YAMLs and resolve "chartRepoUrl" and "targetRevision" as "input values" for Git tags resolving (or maybe whathever ArgoCD datasource can use)?

### What you tried so far.

I was reading about regexp matcher, but maybe it could be done in any more simply way?

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

**Comment by secustor** [comment, marked as answer]
For custom files currently the only option is the [`regex` manager](https://docs.renovatebot.com/configuration-options/#regexmanagers)

**Reply by szpak** [reply]
Thanks for you response. I will try to work it out.

Most likely #15193 will simplify that, once available.

**Reply by szpak** [reply]
As a quick "regexp fighting", I created (for Renovate `\` would need be quoted):

```
\s*chartRepoUrl: [\"']?(?<depName>.*?)[\"']?\s+(^.*$\n)*\s*targetRevision: [\"']?(?<currentValue>.*?)[\"']?\s+
```

which seems to work in [regex101](https://regex101.com/r/reRBmh/1) with:

```yaml
name: test-my-nice-app
chartRepoUrl: "git@git.example.com:ops/charts/generic-chart.git"
chartName: ""
targetRevision: v0.6.1
namespace: some-namespace
cluster: "c001"
managedBy: "helm"
values: |-
  ...
```

(I haven't got a chance to test it with Renovate yet)

However, I'm not a regexp specialist, so maybe you could suggest any improvements in that?
