### DISCUSSION TITLE
Default docker example doesn't work for CodeCommit

### DISCUSSION THREAD

**Discussion by Marvin0098** [renovatebot/renovate#23449] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest

### If you're self-hosting Renovate, select which platform you are using.

AWS CodeCommit

### Was this something which used to work for you, and then stopped?

Placeholder value, please select the correct response from the dropdown

### Describe the problem

This is the example buildspec file to run renovate using the docker image from the documentation:

```
version: 0.2
env:
  shell: bash
  git-credential-helper: yes
  variables:
    RENOVATE_PLATFORM: 'codecommit'
    RENOVATE_REPOSITORIES: '["repoName1", "repoName2"]'
    RENOVATE_CONFIG: '{"extends":["config:recommended"]}'
    LOG_LEVEL: 'debug'
    AWS_REGION: 'us-east-1'
phases:
  build:
    on-failure: CONTINUE
    commands:
      - docker run --rm -e AWS_REGION -e RENOVATE_CONFIG -e RENOVATE_PLATFORM -e RENOVATE_REPOSITORIES -e LOG_LEVEL renovate/renovate
```
https://docs.renovatebot.com/modules/platform/codecommit/#renovate-cli-buildspecyml

However, the pipeline run fails, with following error message:
```
FATAL: Fatal error: Could not load credentials from any providers
--
111 | "err": {
112 | "tryNextLink": false,
113 | "name": "CredentialsProviderError",
114 | "$metadata": {"attempts": 1, "totalRetryDelay": 0},
115 | "message": "Could not load credentials from any providers",
116 | "stack": "CredentialsProviderError: Could not load credentials from any providers\n    at /opt/containerbase/tools/renovate/36.11.0/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js:13:11\n    at /opt/containerbase/tools/renovate/36.11.0/node_modules/@smithy/property-provider/dist-cjs/chain.js:11:28\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at coalesceProvider (/opt/containerbase/tools/renovate/36.11.0/node_modules/@smithy/property-provider/dist-cjs/memoize.js:14:24)\n    at SignatureV4.credentialProvider (/opt/containerbase/tools/renovate/36.11.0/node_modules/@smithy/property-provider/dist-cjs/memoize.js:33:24)\n    at SignatureV4.signRequest (/opt/containerbase/tools/renovate/36.11.0/node_modules/@smithy/signature-v4/dist-cjs/SignatureV4.js:106:29)\n    at /opt/containerbase/tools/renovate/36.11.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:16:18\n    at /opt/containerbase/tools/renovate/36.11.0/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46\n    at /opt/containerbase/tools/renovate/36.11.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26\n    at Object.listRepositories (/opt/containerbase/tools/renovate/36.11.0/node_modules/renovate/lib/modules/platform/codecommit/codecommit-client.ts:261:10)\n    at Proxy.initPlatform (/opt/containerbase/tools/renovate/36.11.0/node_modules/renovate/lib/modules/platform/codecommit/index.ts:91:3)\n    at initPlatform (/opt/containerbase/tools/renovate/36.11.0/node_modules/renovate/lib/modules/platform/index.ts:49:24)\n    at globalInitialize (/opt/containerbase/tools/renovate/36.11.0/node_modules/renovate/lib/workers/global/initialize.ts:72:12)\n    at /opt/containerbase/tools/renovate/36.11.0/node_modules/renovate/lib/workers/global/index.ts:134:16\n    at start (/opt/containerbase/tools/renovate/36.11.0/node_modules/renovate/lib/workers/global/index.ts:123:5)\n    at /opt/containerbase/tools/renovate/36.11.0/node_modules/renovate/lib/renovate.ts:18:22"
117 | }
```

When using the renovate npm package instead of the docker image it works. The correct permissions were set and the `git-credentials-helper` was activated.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

Placeholder value, please select the correct response from the dropdown
