### DISCUSSION TITLE
Renovatebot ignores pnpm's link-workspace-packages in a pnpm workspace

### DISCUSSION THREAD

**Discussion by Paalar** [renovatebot/renovate#23536] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.82.1

### If you're self-hosting Renovate, select which platform you are using.

GitHub Enterprise Server

### Was this something which used to work for you, and then stopped?

I am trying to get this working for the first time

### Describe the problem

When `renovatebot` is updating packages in a `pnpm` monorepo, it will install as if the root `.npmrc` files does not include `link-workspace-packages = false`. The same will occur if we run `pnpm install` locally without that line (or sat to true).

This monorepo contains apps and a component library which is updated to a self hosted npm registry. Other libraries downloaded from the same npm registry works fine and as expected. This makes it more difficult to replicate.

Result
```yaml
'@custom-registry/component-library':
        specifier: 0.1.27
        version: link:../../common/component-library
```

Expected
```yaml
'@custom-registry/component-library':
        specifier: 0.1.27
        version: 0.1.27
```

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible
