### DISCUSSION TITLE
Update github repository monorepo tag using renovate bot

### DISCUSSION THREAD

**Discussion by Montek30** [renovatebot/renovate#23559] [Request Help]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

Update the monorepo tag to the latest one. I want the kube-prometheus-stack-1.0.0 to upgrade to the latest one. 

The GitRepository yaml which I want to upgrade currently looks like this:
```
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 30m
  ref:
    tag: kube-prometheus-stack-48.1.2
  url: https://github.com/prometheus-community/helm-charts
---

```

I want to trigger update on the tag "kube-prometheus-stack-48.1.2" to be the latest one.

Can someone assist/provide with some valuable info

### What you tried so far.

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base",
    ":dependencyDashboard"
  ],
  "major": {
    "dependencyDashboardApproval": true
  },
  "packageRules": [
    // setup datasources
    {
      "matchDatasources": [
        "docker",
        "helm",
        "kubernetes-api"
      ],
      "ignoreDeprecated": true
    }
  ],
  "flux": {
    "fileMatch": [
      "flux/.+\\.yaml$",
      "base/.+\\.yaml$",
      "crds/.+\\.yaml$",
      "apps/cnp-eu-dev/monitoring/.+\\.yaml$",
      "apps/cnp-eu-staging/monitoring/.+\\.yaml$"
    ]
  },
  "kubernetes": {
    "fileMatch": ["infra/base/.+\\.yaml$"]
  },
  "ignorePaths": [
    "infra/base/aws-vpc-cni/**"
  ],
  "regexManagers": [
    {
      "fileMatch": [
        "crds/.+\\.yaml$"
      ],
      "matchStrings": [
        "tag:\\s*(?kube-prometheus-stack}-(?<currentValue>.*)"
      ],
      "datasourceTemplate": "github-tags",
      "depNameTemplate": "prometheus-community/helm-charts"
    }
  ]
}

```

Curren the renovate.json5 looks like this.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

**Comment by viceice** [comment]
you need regex versioning

**Reply by Montek30** [reply]
I didn't get it exactly If you can please post an answer here that'd be great.
How does this part look like?

```
 "regexManagers": [
    {
      "fileMatch": [
        "crds/.+\\.yaml$"
      ],
      "matchStrings": [
        "tag:\\s*(?kube-prometheus-stack}-(?<currentValue>.*)"
      ],
      "datasourceTemplate": "github-tags",
      "depNameTemplate": "prometheus-community/helm-charts"
    }
  ]
```

**Reply by viceice** [reply]
wrong, you need to match the full git tag and configure versioning to a custom regex, so renovate understand that tag format.

our docs have samples for regex versioning

**Reply by m477r1x** [reply]
Hi there, im looking at doing this as well, is it this part of the documentaiton you are referring to? https://docs.renovatebot.com/modules/versioning/#git-versioning

I'm struggling to understand exactly what the regex should look like, can you point me in the right direction if this is the wrong section of the docs?

**Reply by viceice** [reply]
no, I mean regex versioning

https://docs.renovatebot.com/modules/versioning/#regular-expression-versioning

**Reply by Montek30** [reply]
Hi, I'm still struggling to get this working.

```
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 30m
  ref:
    tag: kube-prometheus-stack-48.1.2
  url: https://github.com/prometheus-community/helm-charts
---
```

 tag is "kube-prometheus-stack-48.1.2" in which I wanna update the 48.1.2 part. Can u plz help me out w the correct regex versioning
