### DISCUSSION TITLE
docker.io/hadolint/hadolint container image - wrong tag is picked up

### DISCUSSION THREAD

**Discussion by lmilbaum** [renovatebot/renovate#23637] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

The image hadolint/hadolint is used in .gitlab-ci.yml:
```
---
stages:
  - lint

lint-dockerfile:
  image: $CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX/hadolint/hadolint:v2.12.0-debian@sha256:27173fe25e062448490a32de410c08491c626a0bef360aa2ce5d5bdd9384b50d  # yamllint disable-line rule:line-length
  stage: lint
  script:
    - hadolint Dockerfile
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
```
Renovate should not update the tag

### What you tried so far.

Renovate produces:
```
hadolint/hadolint image major `v2.12.0-debian` -> `12473f0317f35fb685c19caaac8a253d187a99c9-debian-arm64`
```

config.js:
```
module.exports = {
  platform: "gitlab",
  endpoint: "https://gitlab.com/api/v4/",
  onboardingConfig: {
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
      "github>platform-engineering-org/.github",
      "workarounds:supportRedHatImageVersion"
    ]
  },
  onboardingRebaseCheckbox: true,
  commitBody: "Related: RHELPLAN-17567",
  repositories: [
    "redhat/red-hat-ci-tools/platform-engineering/renovate-runner",
    "redhat/rhel/containers/ubi9-init",
    "redhat/rhel/containers/go-toolset"
  ],
  hostRules: [
    {
      matchHost: "github.com",
      token: process.env.GITHUB_COM_TOKEN,
    },
    {
      hostType: "docker",
      matchHost: "docker.io",
      username: process.env.DOCKER_HUB_USERNAME,
      password: process.env.DOCKER_HUB_TOKEN
    },
    {
      hostType: "docker",
      matchHost: "<proxy registry>",
      username: process.env.QUAY_USERNAME,
      password: process.env.QUAY_PASSWORD
    }
  ],
  packageRules: [
    {
      matchDatasources: "docker",
      matchManagers: ["dockerfile"],
      registryUrls: ["<proxy registry>"],
      allowedVersions: "/^\\d\\-\\d+\\.\\d+$/",
      versioning: "loose"
    },
    {
      matchDatasources: "docker",
      matchManagers: ["gitlabci"],
      registryUrls: ["docker.io"]
    }
  ]
};
```

Same .gitlab-ci.yml file with the following config.js keeps the tag unchanged (as it should):
```
module.exports = {
  platform: "gitlab",
  endpoint: "https://<self hosted gitlab>/api/v4/",
  onboardingConfig: {
      "extends": [
          "github>platform-engineering-org/.github"
      ]
  },
  hostRules: [
    {
      "matchHost": "github.com",
      "token": process.env.GITHUB_COM_TOKEN,
    },
    {
      "hostType": "docker",
      "matchHost": "docker.io",
      "username": process.env.DOCKER_HUB_USERNAME,
      "password": process.env.DOCKER_HUB_TOKEN
    }
  ],
  repositories: [
    "automotive/platform-engineering/renovate-image"
  ]
};
```

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>
