### DISCUSSION TITLE
Support for renovate token in docker secrets

### DISCUSSION THREAD

**Discussion by kvandermast** [renovatebot/renovate#23659] [Suggest an Idea]
### Tell us more.

Dear all,

We have set-up Renovate (latest) as a self-hosted Docker image and are passing the container configuration via then ENV, eg

```yaml
version: "3.9"

services:
  renovate:
    image: renovate/renovate
    container_name: renovate
    environment:
      RENOVATE_LOG_FILE_LEVEL: debug
      RENOVATE_GITHUB_TOKEN_WARN: false
      RENOVATE_PLATFORM: gitea
      RENOVATE_USERNAME: renovate
      RENOVATE_TOKEN: f......4
      RENOVATE_ENDPOINT: http://host:3000
      RENOVATE_GIT_AUTHOR: Renovate-Bot <renovate@example.com>
      # set to false if you don't want to discover all repo's you have push access to
      RENOVATE_AUTODISCOVER: true 
      RENOVATE_BRANCH_PREFIX: renovate/
      RENOVATE_ONBOARDING: false
```

As we are trying to remove all clear text passwords from container manifests we would like to use the Docker secrets which are mounted on a specific path, eg `/run/secrets/RENOVATE_TOKEN`.

Some images offer the possibility to either assign a token as ENV variable, or from FILE. Would it possible to add the possibility in Renovate?

eg

```yaml
version: "3.9"

secrets:
  RENOVATE_TOKEN:
    file: /run/secrets/RENOVATE_TOKEN

services:
  renovate:
    image: renovate/renovate
    container_name: renovate
    environment:
      RENOVATE_LOG_FILE_LEVEL: debug
      RENOVATE_GITHUB_TOKEN_WARN: false
      RENOVATE_PLATFORM: gitea
      RENOVATE_USERNAME: renovate
      #RENOVATE_TOKEN: f......4
      RENOVATE_TOKEN_FILE: /run/secrets/RENOVATE_TOKEN
      RENOVATE_ENDPOINT: http://host:3000
      RENOVATE_GIT_AUTHOR: Renovate-Bot <renovate@example.com>
      # set to false if you don't want to discover all repo's you have push access to
      RENOVATE_AUTODISCOVER: true 
      RENOVATE_BRANCH_PREFIX: renovate/
      RENOVATE_ONBOARDING: false
    secrets:
      - RENOVATE_TOKEN
```

Thanks,
Kris
