### DISCUSSION TITLE
config help

### DISCUSSION THREAD

**Discussion by jeremycohensolal-paylead** [renovatebot/renovate#23711] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

36.31.0

### If you're self-hosting Renovate, select which platform you are using.

gitlab.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

I found renovatebot can check gitlab-ci files.

I have a renovatebot repository targeting only another "test repository" (test-rbot-registry).

In the test-rbot-registry I have a gitlab-ci file including this:

```yml
stages:
 - build
 - use

... TRUNCATED ...

use:
  stage: use
  services:
    # use the 1.0.0 (outdated version of my container image) 
    - name: $CI_REGISTRY_IMAGE/my-container:1.0.0
      alias: outdated
  script:
    - echo pouet
```

In the test-rbot-registry container registry there is 3 tags
- v1.0.0
- v1.0.1
- latest (-> v1.0.1)

I would expect  renovatebot to suggest to update my service image from v1.0.0 to v1.0.1

### What you tried so far.

I also tried with 1.0.0 and 1.0.1 (without the v). It didn't helped

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

**Comment by github-actions** [comment]
Hi there,

This issue or discussion is missing some logs, making it difficult or impossible to help you. Depending on which situation applies follow one, some or all of these instructions.

### No logs at all
If you haven't posted any log yet, we need you to find and copy/paste the log into the issue template.

#### Finding logs on hosted app
<details><summary>Select me to read instructions</summary>

If you use the Renovate app (GitHub):
1. Go to the affected PR, and search for "View repository job log here"
1. Select the link to go to the "Mend Renovate Dashboard" and log in
1. You are now in the correct repository log overview screen
1. Copy/paste the correct log
1. Follow the steps in the **formatting your logs** section
</details>

#### Finding logs when self-hosting
<details><summary>Select me to read instructions</summary>

If you're running self-hosted, run with `LOG_LEVEL=debug` in your environment variables and search for whatever dependency/branch/PR that is causing the problem.
</details>

### Insufficient logs
<details><summary>Select me to read instructions</summary>

If you already gave us a log, and the Renovate team said it's not enough, then follow the instructions from the **No logs at all** section.
</details>

### Formatting your logs
<details><summary>Select me to read instructions</summary>

Please put your logs in a `<details>` and `<summary>` element like this:


    <details><summary>Select me to see logs</summary>

    ```
    Copy/paste your logs here, between the starting and ending backticks
    ```

    </details>

</details>

Good luck,

The Renovate team

**Reply by jeremycohensolal-paylead** [reply]
Here is the log trace

```
Running with gitlab-runner 15.10.1 (dcfb4b66)
  on ci-worker-ovh-01 pDi3UdKb, system ID: s_00a31b[2](https://gitlab.com/paylead/projects/renovatebot/-/jobs/4806961321#L2)2be57
Resolving secrets
00:00
Preparing the "docker" executor
00:02
Using Docker executor with image ghcr.io/renovatebot/renovate:[3](https://gitlab.com/paylead/projects/renovatebot/-/jobs/4806961321#L3)6.31.0@sha256:3200185a78780b438423019971d28a0215decd42ad3a84201410da859a7fd278 ...
Pulling docker image ghcr.io/renovatebot/renovate:36.31.0@sha256:3200185a78780b438423019971d28a0215decd42ad3a84201410da859a7fd278 ...
Using docker image sha256:d48f4796f296ed3c3e20e6232dd0aef8344d40db6204b96f45670a04e84ef52a for ghcr.io/renovatebot/renovate:36.31.0@sha256:3200185a78780b438423019971d28a0215decd42ad3a84201410da859a7fd278 with digest ghcr.io/renovatebot/renovate@sha256:3200185a78780b438423019971d28a0215decd42ad3a84201410da859a7fd278 ...
Preparing environment
00:00
Running on runner-pdi3udkb-project-4806076[5](https://gitlab.com/paylead/projects/renovatebot/-/jobs/4806961321#L5)-concurrent-0 via ci-worker-ovh-01...
Getting source from Git repository
00:02
Fetching changes with git depth set to 20...
Reinitialized existing Git repository in /builds/paylead/projects/renovatebot/.git/
Checking out 3c3c18a4 as detached HEAD (ref is add-renovatebot)...
Removing renovate-log.ndjson
Removing renovate/
Skipping Git submodules setup
Restoring cache
00:01
Checking cache for add-renovatebot-renovate-non_protected...
No URL provided, cache will not be downloaded from shared cache server. Instead a local version of cache will be extracted. 
Successfully extracted cache
Executing "step_script" stage of the job script
00:15
Using docker image sha25[6](https://gitlab.com/paylead/projects/renovatebot/-/jobs/4806961321#L6):d48f4[7](https://gitlab.com/paylead/projects/renovatebot/-/jobs/4806961321#L7)96f296ed3c3e20e6232dd0aef[8](https://gitlab.com/paylead/projects/renovatebot/-/jobs/4806961321#L8)344d40db6204b96f45670a04e84ef52a for ghcr.io/renovatebot/renovate:36.31.0@sha256:3200185a78780b438423019971d28a0215decd42ad3a842014[10](https://gitlab.com/paylead/projects/renovatebot/-/jobs/4806961321#L10)da859a7fd278 with digest ghcr.io/renovatebot/renovate@sha256:3200185a78780b438423019971d28a0215decd42ad3a84201410da859a7fd278 ...
$ renovate $RENOVATE_EXTRA_FLAGS
 INFO: Autodiscovered repositories
       "length": 1,
       "repositories": ["paylead/tests/jcohen/test-rbot-registry"]
 INFO: Repository started (repository=paylead/tests/jcohen/test-rbot-registry)
       "renovateVersion": "36.31.0"
 INFO: Dependency extraction complete (repository=paylead/tests/jcohen/test-rbot-registry, baseBranch=main)
       "stats": {
         "managers": {
           "dockerfile": {"fileCount": 1, "depCount": 1},
           "gitlabci": {"fileCount": 1, "depCount": 5}
         },
         "total": {"fileCount": 2, "depCount": 6}
       }
 INFO: Repository finished (repository=paylead/tests/jcohen/test-rbot-registry)
       "cloned": true,
       "durationMs": 10291
Saving cache for successful job
00:00
Creating cache add-renovatebot-renovate-non_protected...
renovate/cache/renovate/repository/: found 7 matching artifact files and directories 
No URL provided, cache will not be uploaded to shared cache server. Cache will be stored only locally. 
Created cache
Uploading artifacts for successful job
00:02
Uploading artifacts...
renovate-log.ndjson: found 1 matching artifact files and directories 
Uploading artifacts as "archive" to coordinator... 201 Created  id=480696[13](https://gitlab.com/paylead/projects/renovatebot/-/jobs/4806961321#L13)[21](https://gitlab.com/paylead/projects/renovatebot/-/jobs/4806961321#L21) responseStatus=201 Created token=64_TQWBx
Cleaning up project directory and file based variables
00:00
Job succeeded
``` 



My  renovatebot repository ci file:

```yaml
variables:
  RENOVATE_EXTRA_FLAGS: --autodiscover=true --autodiscover-filter=paylead/tests/jcohen/test-rbot-registry
  
include:
    - project: 'renovate-bot/renovate-runner'
      file: '/templates/renovate.gitlab-ci.yml'
```



my whole CI file in the test-rebot-registry repository

```yaml
stages:
 - build
 - use

default:
  before_script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY

build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    # Image 1.0.0
    - echo "1.0.0" > foo.txt
    - docker build -t $CI_REGISTRY_IMAGE/my-container -f Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/my-container:latest
    - docker tag $CI_REGISTRY_IMAGE/my-container $CI_REGISTRY_IMAGE/my-container:v1.0.0
    - docker push $CI_REGISTRY_IMAGE/my-container:v1.0.0
    - docker tag $CI_REGISTRY_IMAGE/my-container:v1.0.0 $CI_REGISTRY_IMAGE/my-container:latest

    # Image 1.0.1
    - echo "1.0.1" > foo.txt
    - docker build -t $CI_REGISTRY_IMAGE/my-container -f Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/my-container:latest
    - docker tag $CI_REGISTRY_IMAGE/my-container $CI_REGISTRY_IMAGE/my-container:v1.0.1
    - docker push $CI_REGISTRY_IMAGE/my-container:v1.0.1
    - docker tag $CI_REGISTRY_IMAGE/my-container:v1.0.1 $CI_REGISTRY_IMAGE/my-container:latest
    

use:
  stage: use
  image: docker:24.0.5
  variables:
    GIT_STRATEGY: none
  services:
    - docker:24.0.5-dind
    - name: "$CI_REGISTRY_IMAGE/my-container:v1.0.0"
      alias: outdated
  script:
    - echo foobar

```
