### DISCUSSION TITLE
How do I get the Renovate GitHub Action to pick up my own DockerHub credentials?

### DISCUSSION THREAD

**Discussion by mark-thm** [renovatebot/renovate#23722] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

36.33.3

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

Renovate uses my organization's DockerHub credentials.

### What you tried so far.

I've tried configuring the self-hosted environment variables recommended by the docs:
```
      - name: Run Renovate
        uses: renovatebot/github-action@v39.0.1
        with:
          # options in this file are defined by
          # https://docs.renovatebot.com/self-hosted-configuration/
          configurationFile: .github/renovate-config.json
          token: ${{ steps.get_token.outputs.token }}
        env:
          RENOVATE_DETECT_HOST_RULES_FROM_ENV: true
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
```

I've verified that DOCKERHUB_USERNAME and DOCKERHUB_PASSWORD are secrets that are available to the action and set to the correct values.

Notably the logs below show username and password are set to empty. When I set LOG_LEVEL to "debug" I'm not finding any additional information about whether my host rules are getting picked up.

### Relevant debug logs

<details><summary>Logs</summary>

```
WARN: Host error (repository=<redacted>)
       "hostType": "docker",
       "packageName": "<redacted>",
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1691185247219,
           "socket": 1691185247219,
           "lookup": 1691185247225,
           "connect": 1691185247233,
           "secureConnect": 1691185247243,
           "upload": 1691185247243,
           "response": 1691185247246,
           "end": 1691185247246,
           "phases": {
             "wait": 0,
             "dns": 6,
             "tcp": 8,
             "tls": 10,
             "request": 0,
             "firstByte": 3,
             "download": 0,
             "total": 27
           }
         },
         "message": "Response code 429 (Too Many Requests)",
         "stack": "HTTPError: Response code 429 (Too Many Requests)\n    at Request.<anonymous> (/opt/containerbase/tools/renovate/36.33.3/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/36.33.3 (https://github.com/renovatebot/renovate)",
             "authorization": "***********",
             "accept": "application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.docker.distribution.manifest.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://index.docker.io/v2/jimmidyson/configmap-reload/manifests/latest",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 429,
           "statusMessage": "Too Many Requests",
           "body": "{\n  \"errors\": [\n    {\n      \"code\": \"TOOMANYREQUESTS\",\n      \"message\": \"You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: [https://www.docker.com/increase-rate-limit\](https://www.docker.com/increase-rate-limit/)"\n    }\n  ]\n}\n",
           "headers": {
             "cache-control": "no-cache",
             "content-type": "application/json",
             "connection": "close"
           },
           "httpVersion": "1.1",
           "retryCount": 2
         }
       }
```

</details>

**Comment by mark-thm** [comment, marked as answer]
For posterity and those running into the same challenge, the problem here was that the GitHub action by default filters most environment variables from being passed to Renovate using a regular expression.

A working configuration for me:
```
      - name: Run Renovate
        uses: renovatebot/github-action@v39.0.1
        with:
          # options in this file are defined by
          # https://docs.renovatebot.com/self-hosted-configuration/
          configurationFile: .github/renovate-config.json
          token: ${{ steps.get_token.outputs.token }}
          # the default value of env-regex excludes the DOCKER_ creds
          env-regex: "^(RENOVATE_.*|DOCKER_.*|LOG_LEVEL)$"
        env:
          RENOVATE_DETECT_HOST_RULES_FROM_ENV: true
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
```
