### DISCUSSION TITLE
Support for kustomize field images replacement in argocd application

### DISCUSSION THREAD

**Discussion by zephyros-dev** [renovatebot/renovate#23848] [Suggest an Idea]
### Tell us more.

Argocd support defining the kustomization options in its application definition, and it allows overriding the image. A minimum example look something like this:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
  namespace: argocd
spec:
  source:
    kustomize:
      images:
        # The format is {image-to-be-replaced}={image-to-replace-with}:{tag}@{sha256}
        - ghcr.io/renovatebot/renovate=ghcr.io/renovatebot/renovate:35.159.6-slim@sha256:bff0c20324ae62cedd2d7f64f5ba49885f6fd10cfef7bfb7939b299f89d517cd
```
It would be nice if renovate can support updating the image for this use case.

**Comment by j-be** [comment]
+1 for the feature.

I currently use the following in `renovate.json`:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "customManagers": [
    {
      "customType": "regex",
      "fileMatch": [
        "^path/to/argo-cd/application-.+\\.yaml$"
      ],
      "matchStrings": [
        "\\s+-\\s+.*=(?<depName>.+):(?<currentValue>.+)"
      ],
      "datasourceTemplate": "docker"
    }
  ]
}
```

It only works for YAML style lists, i.e.:

```yaml
spec:
  ...
  source:
    repoURL: **redacted**
    path: **redacted**
    targetRevision: **redacted**
    kustomize:
      images:
        - image1=ghcr.io/some/image:1.2.3
        - image2=some-other/image:2.3.4
```

it does NOT handle quotes, and most probably a lot of other corner cases are not handled either, but the happy path works :smile:
