### DISCUSSION TITLE
Support for Cargo source replacement

### DISCUSSION THREAD

**Discussion by dylanowen** [renovatebot/renovate#23943] [Suggest an Idea]
### Tell us more.

Right now renovate supports alternative registries explicitly defined for a cargo dependency, however it is also possible to override the source of registries for mirroring.

For example: https://jfrog.com/help/r/artifactory-how-to-integrate-artifactory-with-cargo-using-sparse-indexing/artifactory-configuration
```toml
[registries.artifactory-remote]
index = "sparse+http://JFROG_PLATFORM_URL/artifactory/api/cargo/cargo-remote/index/"

[source.crates-io]
replace-with = "artifactory-remote"
```

https://doc.rust-lang.org/cargo/reference/source-replacement.html

I've hacked together a version locally which fixes this problem and I'm planning on working on a full PR for this
