### DISCUSSION TITLE
BuildKite: Add support for managing Docker images

### DISCUSSION THREAD

**Discussion by jamietanna** [renovatebot/renovate#24015] [Suggest an Idea]
### Tell us more.

When using the BuildKite manager, we currently only support retrieving plugins, not any agent-specific Docker images.

For instance, [this BuildKite configuration](https://github.com/elastic/elasticsearch/blob/bba8d1e25abe793618036fdf5e6872e844fd9737/.buildkite/pipelines/periodic.yml#L17-L21) we have an `agents.image` defined:

```yaml
        agents:
          provider: gcp
          # this wouldn't need updating anyway, as it's pulling `:latest` implicitly, but for other images that do define a tag, we'd want to keep them updated
          image: family/elasticsearch-ubuntu-2004
          machineType: custom-32-98304
          buildDirectory: /dev/shm/bk
```

As a workaround, there is currently the ability to use the `regex` manager for this:

```javascript
{
	"regexManagers": [
		{
			"fileMatch": [
				"buildkite\\.ya?ml",
				"\\.buildkite/.+\\.ya?ml$",
				"\\.buildkite/.+/.+\\.ya?ml$"
			],
			"matchStrings": [
				"image:\\s*\"?(?<depName>[^\\s]+):(?<currentValue>[^\\s\"]+)\"?",
			],
			"datasourceTemplate": "docker"
		},
	]
}
```
