### DISCUSSION TITLE
Command failed: install-tool helm v3.12.3

### DISCUSSION THREAD

**Discussion by MichaelBreedveldSchiphol** [renovatebot/renovate#24043] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

Latest

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the problem

While renovate is creating a PR I get the error below,

Log in the PR:

```
⚠ Artifact update problem

Renovate failed to update an artifact related to this branch. You probably do not want to merge this PR as-is.

♻ Renovate will retry this branch, including artifacts, only when one of the following happens:

any of the package files in this branch needs updating, or
the branch becomes conflicted, or
you click the rebase/retry checkbox if found above, or
you rename this PR's title to start with "rebase!" to trigger it manually
The artifact failure details are included below:

File name: chart/Chart.lock

Command failed: install-tool helm v3.12.3
```

Log in the Renovate bot:

```
DEBUG: Resolved stable matching version (repository=GitHubOrg/repo-name-account, branch=renovate/redis-17.x)
       "toolName": "helm",
       "constraint": undefined,
       "resolvedVersion": "v3.12.3"
DEBUG: Executing command (repository=GitHubOrg/repo-name-account, branch=renovate/redis-17.x)
       "command": "install-tool helm v3.12.3"
DEBUG: rawExec err (repository=GitHubOrg/repo-name-account, branch=renovate/redis-17.x)
       "err": {
         "cmd": "/bin/sh -c install-tool helm v3.12.3",
         "stderr": "",
         "stdout": "[12:37:16.777] INFO (478): Installing tool helm v3.12.3...\ninstalling v2 tool helm v3.12.3\nlinking tool helm v3.12.3\nversion.BuildInfo{Version:\"v3.12.3\", GitCommit:\"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e\", GitTreeState:\"clean\", GoVersion:\"go1.20.7\"}\n[12:37:17.427] FATAL (478): EACCES: permission denied, scandir '/tmp/snap-private-tmp'\n    err: {\n      \"type\": \"Error\",\n      \"message\": \"EACCES: permission denied, scandir '/tmp/snap-private-tmp'\",\n      \"stack\":\n          Error: EACCES: permission denied, scandir '/tmp/snap-private-tmp'\n      \"errno\": -13,\n      \"code\": \"EACCES\",\n      \"syscall\": \"scandir\",\n      \"path\": \"/tmp/snap-private-tmp\"\n    }\n[12:37:17.818] INFO (478): Installed tool helm with errors in 1s.\n",
         "options": {
           "cwd": "/tmp/renovate/repos/github/GitHubOrg/repo-name-account",
           "encoding": "utf-8",
           "env": {
             "HELM_EXPERIMENTAL_OCI": "1",
             "HELM_REGISTRY_CONFIG": "/tmp/renovate/cache/__renovate-private-cache/registry.json",
             "HELM_REPOSITORY_CONFIG": "/tmp/renovate/cache/__renovate-private-cache/repositories.yaml",
             "HELM_REPOSITORY_CACHE": "/tmp/renovate/cache/__renovate-private-cache/repositories",
             "HOME": "/home/ubuntu",
             "PATH": "/home/ubuntu/.cargo/bin:/home/ubuntu/.local/bin:/go/bin:/home/ubuntu/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/.cargo/bin:/home/ubuntu/.local/bin:/go/bin:/home/ubuntu/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/.cargo/bin:/home/ubuntu/.local/bin:/go/bin:/home/ubuntu/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
             "LC_ALL": "C.UTF-8",
             "LANG": "C.UTF-8",
             "CONTAINERBASE_CACHE_DIR": "/tmp/renovate/cache/containerbase"
           },
           "maxBuffer": 10485760,
           "timeout": 900000
         },
         "exitCode": 1,
         "name": "ExecError",
         "message": "Command failed: install-tool helm v3.12.3\n",
         "stack": "ExecError: Command failed: install-tool helm v3.12.3\n\n    at ChildProcess.<anonymous> (/opt/containerbase/tools/renovate/36.57.2/node_modules/renovate/lib/util/exec/common.ts:99:11)\n    at ChildProcess.emit (node:events:526:35)\n    at ChildProcess.emit (node:domain:489:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)"
       },
```

Chart.yaml

```
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.0
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: v0.0.0
dependencies:
  - name: mysql
    condition: mysql.enabled
    version: 9.12.0
     repository: https://charts.bitnami.com/bitnami
   - name: redis
     condition: redis.enabled
     version: 17.15.6
     repository: https://charts.bitnami.com/bitnami
```

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible
