### DISCUSSION TITLE
[manager: helm-values] Support multiple documents in one yaml file

### DISCUSSION THREAD

**Discussion by DerRockWolf** [renovatebot/renovate#24067] [Suggest an Idea]
### Tell us more.

The helm-values manager fails if the file contains more than one document.
<details><summary>error log</summary>

```
DEBUG: Failed to parse helm-values YAML
{
  "err": {
    "name": "YAMLException",
    "reason": "expected a single document in the stream, but found more",
    "message": "expected a single document in the stream, but found more",
    "stack": "YAMLException: expected a single document in the stream, but found more\n    at load (/opt/containerbase/tools/renovate/36.56.0/node_modules/js-yaml/lib/loader.js:1722:9)\n    at Object.extractPackageFile (/opt/containerbase/tools/renovate/36.56.0/node_modules/renovate/lib/modules/manager/helm-values/extract.ts:69:25)\n    at extractPackageFile (/opt/containerbase/tools/renovate/36.56.0/node_modules/renovate/lib/modules/manager/index.ts:75:9)\n    at getManagerPackageFiles (/opt/containerbase/tools/renovate/36.56.0/node_modules/renovate/lib/workers/repository/extract/manager-files.ts:45:43)\n    at /opt/containerbase/tools/renovate/36.56.0/node_modules/renovate/lib/workers/repository/extract/index.ts:63:28\n    at async Promise.all (index 1)\n    at extractAllDependencies (/opt/containerbase/tools/renovate/36.56.0/node_modules/renovate/lib/workers/repository/extract/index.ts:60:26)\n    at extract (/opt/containerbase/tools/renovate/36.56.0/node_modules/renovate/lib/workers/repository/process/extract-update.ts:140:28)\n    at extractDependencies (/opt/containerbase/tools/renovate/36.56.0/node_modules/renovate/lib/workers/repository/process/index.ts:154:26)\n    at Object.renovateRepository (/opt/containerbase/tools/renovate/36.56.0/node_modules/renovate/lib/workers/repository/index.ts:61:9)\n    at attributes.repository (/opt/containerbase/tools/renovate/36.56.0/node_modules/renovate/lib/workers/global/index.ts:184:11)\n    at start (/opt/containerbase/tools/renovate/36.56.0/node_modules/renovate/lib/workers/global/index.ts:169:7)\n    at /opt/containerbase/tools/renovate/36.56.0/node_modules/renovate/lib/renovate.ts:18:22"
  }
  "packageFile": "base/core/metallb.yaml"
}
```
</details> 

<details><summary>Example file</summary>

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 30m
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 5m
  install:
    createNamespace: true
  targetNamespace: metallb-system
  chart:
    spec:
      chart: metallb
      version: 0.13.10
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  values:
    controller:
      image:
        repository: quay.io/metallb/controller
        tag: v0.13.10
    speaker:
      image:
        repository: quay.io/metallb/speaker
        tag: v0.13.10
      frr:
        enabled: false
```
</details> 

This could be "fixed" by extracting the relevant document into its own yaml file.

However it would be nice if the helm-values manager would be able to parse files with multiple yaml documents.
Same thing was already done for the helmfile manager: https://github.com/renovatebot/renovate/pull/8828

Relevant line(s) of code: 
https://github.com/renovatebot/renovate/blob/57dc9389ae69cbd817a2c4d6c2be4b6f0dd8c86f/lib/modules/manager/helm-values/extract.ts#L69

I have zero experience with typescript, but if you accept this feature request I can give it a shot :slightly_smiling_face:
