### DISCUSSION TITLE
Versioning support files in gitlab-ci include with tag prefixes

### DISCUSSION THREAD

**Discussion by chris-melman** [renovatebot/renovate#24239] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

I have the following gitlab-ci file with includes:
```
include:
  - project: 'tools/gitlab-ci-scripts'
    ref: 'git_push/1.0.1'
    file:
      - 'git_push.yml'
  - project: 'tools/gitlab-ci-scripts'
    ref: 'deploy/1.0.0'
    file:
      - 'deploy.yml'
```

The repository has tags for each include file with prefixes (the general tags are outdated this was the previous way of releasing).
However the renovate bot ignores the prefix and suggests to update it to general 1.2 tag:

```
include:
  - project: 'tools/gitlab-ci-scripts'
    ref: '1.2'
    file:
      - 'git_push.yml'
  - project: 'tools/gitlab-ci-scripts'
    ref: '1.2'
    file:
      - 'deploy.yml'
```
 
I would like to keep the prefix and let renovate only consider tags with the same prefix.

### What you tried so far.

I tried to use the extractVersion, to get the prefix being part of the the version. This didn't change the result.

I found the followTag configuration, but I don't think that can me used for this usecase.

I could get some configuration to ignore versions, however that is only part of the problem

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>
