### DISCUSSION TITLE
Renovate rerunning repos it already ran

### DISCUSSION THREAD

**Discussion by RyuunosukeDS3** [renovatebot/renovate#24235] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

35.144.3

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

Renvoate is configued to run in over 3k projects, it started running on saturday 1am and it is still running. The problem is: Renvoate is running again in repositories it already ran instead of running in repositories it did not run yet and finish the job. Is there a way to fix that? I'm using autodiscovery and no onboarding btw.

EDIT: in fact it started running on saturday 1am, not sunday 1am.

### What you tried so far.

I've tried reconfiguring renovate but never found an option that avoids repeating repositories in the same job.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

**Comment by rarkins** [comment]
That doesn't seem very likely, so you need to think if there's another explanation. The Renovate CLI will build up a list of repositories at startup, then go through them sequentially. It does not go back and do any twice before it's finished.

How are you determining that it's running on the same repo twice? Perhaps you have a second Renovate startup (e.g. due to cron) and that explains if you see it taking actions on the first repo.

**Reply by RyuunosukeDS3** [reply]
This is the cronjob:

![image](https://github.com/renovatebot/renovate/assets/31015675/9c777019-d87e-43c0-a59d-438790cdf5df)

We're running it through kubernetes, and i've watched it the whole weekend as it ran. Never saw any other job pop up. I thought it could be because it ran through multiple days and then it started repeating repos because it is "a new day".

Here are the prints from the same project: 

![image](https://github.com/renovatebot/renovate/assets/31015675/33b731f1-22b0-4d94-b0ff-a18d6920d5a6)
![image](https://github.com/renovatebot/renovate/assets/31015675/78d1bc53-8894-4f26-bc23-8ec925bf4955)
![image](https://github.com/renovatebot/renovate/assets/31015675/6341db7b-91b7-4257-8982-db048a87bd55)

It is split up because there is comments from other applications inbetween.

**Reply by RyuunosukeDS3** [reply]
Just tested it out in a single group, and it ran as expected. Config was the same the only difference is that it was ran on docker instead od kubernetes.

**Reply by rarkins** [reply]
Have you set it to restart on exit or error?

Renovate will exit once it's done. It will exit with non-zero exit code if it sees any errors, so maybe it's restarting?

**Reply by RyuunosukeDS3** [reply]
It didn't show any errors nor signs of restarts. And it didn't cover all the 3k projects, so it never finished running.

Here's the whole helm chart so it's easier to see how it is set up.

```yaml
global:
  # -- Additional labels to be set on all renovate resources
  commonLabels: {}

# -- Override the name of the chart
nameOverride: ''
# -- Override the fully qualified app name
fullnameOverride: ''

cronjob:
  # -- Schedules the job to run using cron notation
  schedule: 'TZ=America/Sao_Paulo 0 1 * * 6'  # At 01:00 every day
  # -- If it is set to true, all subsequent executions are suspended. This setting does not apply to already started executions.
  suspend: false
  # -- Annotations to set on the cronjob
  annotations: {}
  # -- Labels to set on the cronjob
  labels: {}
  # -- "Allow" to allow concurrent runs, "Forbid" to skip new runs if a previous run is still running or "Replace" to replace the previous run
  concurrencyPolicy: ''
  # -- Amount of failed jobs to keep in history
  failedJobsHistoryLimit: ''
  # -- Amount of completed jobs to keep in history
  successfulJobsHistoryLimit: ''
  # -- Set to Never to restart the job when the pod fails or to OnFailure to restart when a container fails
  jobRestartPolicy: Never
  # -- Time to keep the job after it finished before automatically deleting it
  ttlSecondsAfterFinished: ''
  # -- Deadline for the job to finish
  activeDeadlineSeconds: ''
  # -- Number of times to retry running the pod before considering the job as being failed
  jobBackoffLimit: ''
  # -- Deadline to start the job, skips execution if job misses it's configured deadline
  startingDeadlineSeconds: ''
  # -- Additional initContainers that can be executed before renovate
  initContainers: []
  # initContainers:
  # - name: INIT_CONTAINER_NAME
  #   image: INIT_CONTAINER_IMAGE

  # -- Prepend shell commands before renovate runs
  preCommand: ''
  # preCommand: |
  #   echo hello
  #   echo world

  # -- Append shell commands after renovate runs
  postCommand: ''
  # postCommand: |
  #   echo hello
  #   echo world

pod:
  # -- Annotations to set on the pod
  annotations: {}
  # -- Labels to set on the pod
  labels: {}

image:
  # -- Repository to pull renovate image from
  repository: renovate/renovate
  # -- Renovate image tag to pull
  tag: 35.144.3
  # -- "IfNotPresent" to pull the image if no image with the specified tag exists on the node, "Always" to always pull the image or "Never" to try and use pre-pulled images
  pullPolicy: IfNotPresent

# -- Add `-slim` suffix to image tag and `binarySource=install`
slim: false

# -- Secret to use to pull the image from the repository
imagePullSecrets: {}

renovate:
  # -- Custom exiting global renovate config
  existingConfigFile: ''
  # -- Inline global renovate config.json
  # See https://docs.renovatebot.com/self-hosted-configuration
  config: |
    {
      "platform": "gitlab",
      "endpoint": '**REDACTED**',
      "token": "**REDACTED**",
      "onboarding": false,
      "requireConfig": "optional",
      "automerge": false,
      "autodiscover": true,
      "branchNameStrict": true,
      "branchConcurrentLimit": 0,
      "prHourlyLimit": 0,
      "prConcurrentLimit": 0,
      "separateMajorMinor": false,
      "separateMinorPatch": false,
      "hostRules": [
        {
          "hostType": "nuget",
          "matchHost": "https://**REDACTED**/repository",
        }
      ],
      "packageManagers": [
        "pip",
        "npm",
        "yarn",
        "nuget",
        "gomod",
        "pub",
        "maven"
      ],
      "hostRules": [
        {
          "hostType": 'docker',
          "username": "**REDACTED**",
          "password": "**REDACTED**",
        },
      ],
      "packageRules": [
        {
          "matchDatasources": ['maven'],
          "registryUrls": ['https://repo.maven.apache.org/maven2', "https://**REDACTED**/repository/plugins-release-local/", "https://**REDACTED**/repository/libs-release-local/"],
          "rangeStrategy": "widen",
        },
        {
          "matchDepPatterns": ['.*sdl.*'],
          "prBodyTemplate": "{{{header}}}{{{table}}}{{{warnings}}}{{{notes}}}\n### Changelog\n[sdl Changelog](https://**REDACTED**/arquitetura/sdl/-/blob/develop/CHANGELOG.md){{{configDescription}}}{{{controls}}}{{{footer}}}",
          "rangeStrategy": "widen",
        },
        {
          "matchDepPatterns": ['.*edl.*'],
          "prBodyTemplate": "{{{header}}}{{{table}}}{{{warnings}}}{{{notes}}}\n### Changelog\n[pdl Changelog](https://**REDACTED**/arquitetura/edl/-/blob/develop/CHANGELOG.md){{{configDescription}}}{{{controls}}}{{{footer}}}",
          "rangeStrategy": "widen",
        },
        {
          "matchDepPatterns": ['.*pdl.*'],
          "prBodyTemplate": "{{{header}}}{{{table}}}{{{warnings}}}{{{notes}}}\n### Changelog\n[pdl Changelog](https://**REDACTED**/arquitetura/pdl/-/blob/develop/CHANGELOG.md){{{configDescription}}}{{{controls}}}{{{footer}}}",
          "rangeStrategy": "widen",
        },
        
        {
          "matchPackagePatterns": [
            "*"
          ],
          "groupName": "all dependencies",
          "groupSlug": "all-dependencies",
        },
        {
          "matchPackagePrefixes": ["@angular"],
          "allowedVersions": "<9"
        },
        {
          "matchPackagePrefixes": ["@codemirror"],
          "allowedVersions": "<0.19"
        },
        {
          "matchPackageNames": ["primeng"],
          "allowedVersions": "<9"
        },
        {
          "matchPackageNames": ["typescript"],
          "allowedVersions": "<3"
        },
        {
          "matchPackageNames": ["zone.js"],
          "allowedVersions": "<0.10"
        },
        {
          "matchPackageNames": ["cropperjs"],
          "allowedVersions": "<1"
        },
        {
          "matchPackageNames": ["flag-icons"],
          "allowedVersions": "<6"
        },
        {
          "matchPackageNames": ["bignumber.js"],
          "allowedVersions": "<9"
        },
        {
          "matchPackageNames": ["@fortawesome/fontawesome-pro"],
          "allowedVersions": "<5"
        },
        {
          "matchPackageNames": ["@ngx-translate/core"],
          "allowedVersions": "<12.1"
        },
        {
          "matchPackageNames": ["@ngx-translate/http-loader"],
          "allowedVersions": "<5.0"
        },
        {
          "matchPackageNames": ["@lezer/generator"],
          "allowedVersions": "<0.15"
        },
        {
          "matchPackageNames": ["angular2-hotkeys"],
          "allowedVersions": "<2"
        },
        {
          "matchDepPatterns": ['.*maven-wrapper.*'],
          "enabled": false
        }
      ],
      
    }

  # -- Use the Helm tpl function on your configuration. See README for how to use this value
  configEnableHelmTpl: false

  # -- Use this to create the renovate-config as a secret instead of a configmap
  configIsSecret: false

  # -- Renovate Container-level security-context
  securityContext: {}

  # -- Options related to persistence
  persistence:
    cache:
      # -- Allow the cache to persist between runs
      enabled: false
      # -- Storage class of the cache PVC
      storageClass: ""
      # -- Storage size of the cache PVC
      storageSize: "512Mi"

ssh_config:
  # -- Whether to enable the use and creation of a secret containing .ssh files
  enabled: false

  # Provide .ssh config file contents
  # -- Contents of the id_rsa file
  id_rsa: ''
  # -- Contents of the id_rsa_pub file
  id_rsa_pub: ''
  # -- Contents of the config file
  config: ''

  # or provide the name of an existing secret to be read instead.
  # -- Name of the existing secret containing a valid .ssh configuration
  existingSecret: ''

# -- Environment variables that should be referenced from a k8s secret, cannot be used when existingSecret is set
secrets: {}
# -- k8s secret to reference environment variables from. Overrides secrets if set
existingSecret: ''

dind:
  # -- Enable dind sidecar usage?
  enabled: false
  slim:
    # -- Do not add `-slim` suffix to image tag when using dind
    enabled: true
  image:
    # -- Repository to pull dind image from
    repository: docker
    # -- dind image tag to pull
    tag: 24.0.2-dind
    # -- "IfNotPresent" to pull the image if no image with the specified tag exists on the node, "Always" to always pull the image or "Never" to try and use pre-pulled images
    pullPolicy: IfNotPresent

  # -- DinD Container-level security-context. Privileged is needed for DinD, it will not work without!
  securityContext:
    privileged: true

# -- Additional configmaps. A generated configMap name is: "renovate.fullname" + "extra" + name(below) e.g. renovate-netrc-config
extraConfigmaps: []
# extraConfigmaps:
#   - name: netrc-config
#     data:
#       .netrc: |-
#         machine gitlab.example.com
#         login gitlab-ci-token
#         password some-pass
#   - name: yet-another-config
#     data:
#       ya-config.yaml: |-
#         "key"="value"
#         "key1"="value1"

# -- Additional volumes to the pod
extraVolumes: []
# extraVolumes:
#   - name: netrc-config
#     configMap:
#       name: renovate-extra-netrc-config

# -- Additional volumeMounts to the container
extraVolumeMounts: []
# extraVolumeMounts:
#   - name: netrc-config
#     mountPath: /home/ubuntu/.netrc
#     subPath: .netrc

# -- Additional containers to the pod
extraContainers: []
# extraContainers:
#   - name: vault-agent
#     image: vault:1.6.2
#     args:
#     - agent
#     - -config
#     - /vault/config/config.hcl
#     env:
#     - name: VAULT_ADDR
#       value: https://vault:8200
#     - name: VAULT_SKIP_VERIFY
#       value: "false"
#     - name: VAULT_CACERT
#       value: /vault/tls/ca.crt

serviceAccount:
  # -- Specifies whether a service account should be created
  create: false
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use
  # If not set and create is true, a name is generated using the fullname template
  name: ''

# -- Specify resource limits and requests for the renovate container
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

# -- Environment variables to add from existing secrets/configmaps. Uses the keys as variable name
envFrom: []
# envFrom:
#   - secretRef:
#     name: env-secrets
#   - configMapRef:
#     name: env-configmap

# -- Environment variables to set on the renovate container
env: {}

# -- Additional env. Helpful too if you want to use anything other than a `value` source.
envList: []
# envList:
#   - name: POD_NAME
#     valueFrom:
#       fieldRef:
#         fieldPath: metadata.name

redis:
  # Configuration for a Redis subchart. Additional documentation at
  # https://github.com/bitnami/charts/tree/master/bitnami/redis

  # -- Enable the Redis subchart?
  enabled: false

  # -- Override the prefix of the redisHost
  nameOverride: ''

  # -- Disable replication by default
  architecture: standalone

  auth:
    # -- Don't require a password by default
    enabled: false

  # -- Override Kubernetes version for redis chart
  kubeVersion: ''

# Override APIVersions
# If you want to template helm charts but cannot access k8s API server
# you can set api versions here
apiVersionOverrides:
  # -- String to override apiVersion of cronjob rendered by this helm chart
  cronjob: ''

# -- Override hostname resolution
hostAliases: []
# See: https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/
# hostAliases:
#   - ip: "your-ip"
#     hostnames:
#       - "your-hostname"

# -- Pod-level security-context
securityContext: {}

# -- Select the node using labels to specify where the cronjob pod should run on
nodeSelector: {}
# See: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
# renovate: true

# -- Configure the pod(Anti)Affinity and/or node(Anti)Affinity
affinity: {}
# See: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

# -- Configure which node taints the pod should tolerate
tolerations: []
# See: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

```
