### DISCUSSION TITLE
[flux]How can I tell renovate my HelmRepositry URL defined in my HelmRelease

### DISCUSSION THREAD

**Discussion by el-memer** [renovatebot/renovate#24265] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

36.52.0

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

I have a Flux HelmRespoitory pointing to a HelmRegistry located in another namespace and defined in another repo :
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: release-podinfo-demo
spec:
  interval: 2h
  releaseName: release-podinfo-demo
  chart:
    spec:
      chart: chart-release
      version: x.y.z
      sourceRef:
        kind: HelmRepository
        name: my-registry
        namespace: othernamespace
      interval: 1m
```
But with this configuration and the registry located in another repo, renovate doesn't succeed to fetch updates.
I want to renovate to know that this registryUrl in order to fetch updates for this HelmRelease

I know there's is the [solution of placeholder](https://github.com/renovatebot/renovate/discussions/20179#discussioncomment-4855584) but there's no other way to define aliases for flux ?

Thanks in advance

_This is my first discussion, feel free to tell me what I've done wrong or should have done before asking :grin:_

### What you tried so far.

Things I tried : 

- Add the registry in the same repo 
It worked, but it is not what I want (because that would means I have to add the registry in every flux repo using it)

- Adding variables `registryAliases` & `aliases` to manager `flux`, and to datasource `helm`

### Relevant debug logs

<details><summary>Logs</summary>

```
 "deps": [
   {
     "depName": "release-podinfo-demo",
     "currentValue": "x.y.z",
     "datasource": "helm",
     "skipReason": "unknown-registry",
     "updates": [],
     "packageName": "release-podinfo-demo"
   }
 ]
```

</details>
