### DISCUSSION TITLE
How to write a regex manager rule to update also ratchet comments for github actions

### DISCUSSION THREAD

**Discussion by mkurde** [renovatebot/renovate#24325] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

36.87.6

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

Some developers use the tool [ratchet](https://github.com/sethvargo/ratchet) to pin the sha hash of their github actions while and before whitelisting their repository for our self-hosted renovate bot. This is fine, at least the versions are pinned. Now, after the bot comes around and finds an update, the github-actions manager "just" updates the sha hash and leaves the ratched version comment untouched.

Example from a GitHub PR diff where renovate just updated the sha hash but not the version in the ratched comment:

```yaml
      - name: 'Setup Workload Identity Provider'
        id: 'auth'
        uses: 'google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033' # ratchet:google-github-actions/auth@v1
        uses: 'google-github-actions/auth@87b651ab4a60ba1164458f539d64a58d055f4b03' # ratchet:google-github-actions/auth@v1
```

**Wanted end result**

The github-action manager or regex manager also updates the version in the ratchet comment to be in sync with the sha hash.

### What you tried so far.

I've tried to come up with an custom regex manager block but since I lag of understanding the syntax never got it right so far. I tried this:

```
	"regexManagers": [
		{
			"description": |
				Ratchet comments in github actions workflow files,
			"fileMatch": [
				"\\.github/workflows/.*\\.ya?ml$"
			],
			"matchStrings": [
				"uses: \"(?<depName>.*?)@(?<currentValue>.*?)\\s+#\\s*ratchet:(?<depName>[^@]+)@(?<currentValue>[^\\s]+)\""
			],
			"matchStringsStrategy": "any",
			"datasourceTemplate": "github-actions",
			"versioningTemplate": "semver"
		}
	]
```

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>
