### DISCUSSION TITLE
Update Github Runners inside matrix

### DISCUSSION THREAD

**Discussion by nijel** [renovatebot/renovate#24354] [Suggest an Idea]
### Tell us more.

Presently, GitHub runners (github-runners) are updated only in `runs-on`. It would be useful to support matrix builds as well and update them in the matrix builds.

Typically, it looks like:

```
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [macos-latest, windows-latest, ubuntu-20.04]
```
