### DISCUSSION TITLE
Is there a way to specify which version of Renovate to use in azure pipeline yml

### DISCUSSION THREAD

**Discussion by snowleopard24** [renovatebot/renovate#24384] [Request Help]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Wanted end result.

We recently bumped by the minor version on a few of our modules and renovate bot failed to to recognize the newer modules/packages present in our feed and keeps referring to older version - 
older versions were - 
6.3.0-beta.37
6.3.0-beta.35

New version->
6.4.0-beta.2
```
Bot recognizes update from 6.3.0-beta.35 to 6.3.0-beta.37 but doesn't recognize 6.4.0-beta.2 version available in the feed and hence doesn't update.
```
This was first observed in on Thu/Fri last week when 6.4.0-beta.2 was published and I'm wondering if this has something to do with this change for semantic versioning - https://github.com/renovatebot/renovate/pull/24240 which was released with version v36.81.0 https://github.com/renovatebot/renovate/releases/tag/36.81.0

This is impacting our development so wanted to check if I could specify in my yaml a specific version of renovate bot say, v36.80.0 or earlier and use and older version to get around this.

Thanks

### What you tried so far.

my pipeline yml looks like this

```
# trigger: none

pool:
  vmImage: macOS-13

steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '20.5.0'
      checkLatest: true

  - task: npmAuthenticate@0
    inputs:
      workingFile: $(Build.SourcesDirectory)/renovate/.npmrc

  - bash: |
      git config --global user.email 'XYZ@company.com'
      git config --global user.name 'XYZ'
      npx --userconfig $(Build.SourcesDirectory)/renovate/.npmrc renovate
    env:
      TOKEN: $(System.AccessToken)s

```

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>
