### DISCUSSION TITLE
Can you run renovate bot within a woodpecker-ci pipeline?

### DISCUSSION THREAD

**Discussion by Andre601** [renovatebot/renovate#24412] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

36.93.5

### If you're self-hosting Renovate, select which platform you are using.

Gitea or Forgejo

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

My goal is to have a woodpecker-ci pipeline with a cron-job configured to pull `renovate/renovate` on a weekly basis to perform depencency update checks using a dedicated user account.

### What you tried so far.

The following woodpecker file has been tried so far:
```yaml
platform: linux/amd64

when:
  event:
    - cron
    - push
    - manual

steps:
  renovateDryRun:
    image: renovate/renovate
    pull: true
    commands:
      - renovate $${CI_REPO}
    environment:
      RENOVATE_PLATFORM: gitea
      RENOVATE_ENDPOINT: https://codeberg.org
      LOG_LEVEL: debug
      RENOVATE_DRY_RUN: full
    secrets:
      - source: rb_token
        target: renovate_token
    when:
      - event: push
  renovate:
    image: renovate/renovate
    pull: true
    commands:
      - renovate $${CI_REPO}
    environment:
      RENOVATE_PLATFORM: gitea
      RENOVATE_ENDPOINT: https://codeberg.org
      LOG_LEVEL: debug
    secrets:
      - source: rb_token
        target: renovate_token
    when:
      - event: cron
        cron: renovate
      - event: manual
```
`renovateDryRun` completes with no error warnings while `renovate` fails with git-related errors:
```sh
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email \"you@example.com\"
  git config --global user.name \"Your Name\"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <andre@andre601.ch>) not allowed
```

Attempts at setting the git using using the recommended commands through steps before the renovate command failed with permission errors.
Note that I use a pre-existing CI instance and therefore have no admin permissions whatsoever.

Also note, that the user token has the recommended scopes described here: https://docs.renovatebot.com/modules/platform/gitea/#authentication

### Relevant debug logs

<details><summary>Logs</summary>

```sh
DEBUG: Setting git author email: andre@andre601.ch (repository=Andre601/AdvancedServerList)
DEBUG: Unknown error committing files (repository=Andre601/AdvancedServerList)
       "err": {
         "task": {
           "commands": [
             "-c",
             "core.abbrev=40",
             "commit",
             "-m",
             "Add renovate.json",
             "--no-verify"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "Author identity unknown\n\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email \"you@example.com\"\n  git config --global user.name \"Your Name\"\n\nto set your account's default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: empty ident name (for <andre@andre601.ch>) not allowed\n",
         "stack": "Error: Author identity unknown\n\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email \"you@example.com\"\n  git config --global user.name \"Your Name\"\n\nto set your account's default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: empty ident name (for <andre@andre601.ch>) not allowed\n\n    at Object.action (/opt/containerbase/tools/renovate/36.93.5/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/opt/containerbase/tools/renovate/36.93.5/node_modules/simple-git/src/lib/plugins/plugin-store.ts:29:29)\n    at /opt/containerbase/tools/renovate/36.93.5/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:127:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/opt/containerbase/tools/renovate/36.93.5/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:14)\n    at GitExecutorChain.<anonymous> (/opt/containerbase/tools/renovate/36.93.5/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:100:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/containerbase/tools/renovate/36.93.5/node_modules/simple-git/dist/cjs/index.js:55:24)"
       }
ERROR: Repository has unknown error (repository=Andre601/AdvancedServerList)
       "err": {
         "task": {
           "commands": [
             "-c",
             "core.abbrev=40",
             "commit",
             "-m",
             "Add renovate.json",
             "--no-verify"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "Author identity unknown\n\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email \"you@example.com\"\n  git config --global user.name \"Your Name\"\n\nto set your account's default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: empty ident name (for <andre@andre601.ch>) not allowed\n",
         "stack": "Error: Author identity unknown\n\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email \"you@example.com\"\n  git config --global user.name \"Your Name\"\n\nto set your account's default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: empty ident name (for <andre@andre601.ch>) not allowed\n\n    at Object.action (/opt/containerbase/tools/renovate/36.93.5/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/opt/containerbase/tools/renovate/36.93.5/node_modules/simple-git/src/lib/plugins/plugin-store.ts:29:29)\n    at /opt/containerbase/tools/renovate/36.93.5/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:127:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/opt/containerbase/tools/renovate/36.93.5/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:14)\n    at GitExecutorChain.<anonymous> (/opt/containerbase/tools/renovate/36.93.5/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:100:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/containerbase/tools/renovate/36.93.5/node_modules/simple-git/dist/cjs/index.js:55:24)"
       }
```

</details>
