### DISCUSSION TITLE
Is it possible not to have a `renovate.json` in favor of a `renovate.js`?

### DISCUSSION THREAD

**Discussion by raulfdm** [renovatebot/renovate#24566] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

39.0.5

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

Placeholder value, please select the correct response from the dropdown

### Wanted end result.

Hi there 👋

I have a question regarding the self-hosted option + GHA.

I was trying to have a cleaner renovate setup using a single config file, but I noticed that even if I point to a config file in the action setup, renovate also expects me to have a `.json` config.

My case is this one: I had the following setup:

```
root/
├─ ...
├─ renovate.json
└─ renovate-config.js
```

Where `renovate.json` was like:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json"
}
```

And `renovate-config.js`:

```js
module.exports = {
  /**
   * Self-hosted Options
   * https://docs.renovatebot.com/self-hosted-configuration
   */
  username: 'renovate-release',
  onboarding: true,
  platform: 'github',
  repositories: ['raulfdm/raulmelo-studio'],
  // branchConcurrentLimit: 10,

  /**
   * Renovate options
   */
  baseBranches: ['main'],
  // recreateClosed: true,
  gitAuthor: 'Renovate Bot <bot@renovateapp.com>',
  pruneStaleBranches: true,
  packageRules: [
    // ...
  ]
}
```

In the workflow file, it was pointing to the `.js` file:

```yaml
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.5
        with:
          configurationFile: 'renovate.js' # HERE
          token: ${{ secrets.RENOVATE_TOKEN }}
```

The reason I had a `.js` config was just convenience. I'd rather write JS + comments instead of json.

When I tried to delete `renovate.json` in favor of my custom config, I noticed that renovate would open a PR to onboard my repository and add back that `.json` file.

If I set `onboard: false`, then renovate will say my repository is disabled.

My question is: why do we need both files? can't we rely upon a single config (in my case, the `.js`) file?

### What you tried so far.

- delete `.json` config in favor of `.js` -> creates onboard PR;
- set `onboard: false` -> renovate consider my repo as disabled;

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>
