### DISCUSSION TITLE
Packagerule to upgrade minor version without patch

### DISCUSSION THREAD

**Discussion by samvdb** [renovatebot/renovate#24595] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

v15.39.1

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

I'm trying to upgrade gitlab include templates to use only minor version scheme.

So renovate wants to set the ref to `1.1.1`, i would like to have it set to `1.1` without patch nr.

.gitlab-ci.yml
```yaml 
include:
  - project: "to-be-continuous/custom/golang"
    ref: "1.0"
    file: "templates/gitlab-ci-application.yml"
```

Expected result:
```yaml
include:
  - project: "to-be-continuous/custom/golang"
    ref: "1.1"
    file: "templates/gitlab-ci-application.yml"
```

### What you tried so far.

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "packageRules": [
    {
      "description": "Upgrade to-be-continuous CI templates",
      "matchManagers": ["gitlabci-include"],
      "matchUpdateTypes": ["minor"],
      "versioning": "regex:^v?(?<major>\\d+)\\.(?<minor>\\d+)?$",
      "matchPackagePatterns": ["^to-be-continuous/"],
      "automerge": true,
      "automergeType": "branch",
      "commitMessageSuffix": "[skip ci]",
      "groupName": "to be continuous",
      "groupSlug": "to-be-continuous",
      "ignoreTests": true
    }
    ]
}

```

### Relevant debug logs

<details><summary>Logs</summary>

```
{
           "branchName": "chore/to-be-continuous",
           "prNo": null,
           "prTitle": "Update dependency to-be-continuous/custom/golang to v1.1.1 [skip ci]",
           "result": "no-work",
           "upgrades": [
             {
               "datasource": "gitlab-tags",
               "depName": "to-be-continuous/custom/golang",
               "displayPending": "",
               "fixedVersion": "1.0",
               "currentVersion": "1.0",
               "currentValue": "1.0",
               "newValue": "1.1.1",
               "newVersion": "1.1.1",
               "packageFile": ".gitlab-ci.yml",
               "updateType": "minor",
               "packageName": "to-be-continuous/custom/golang"
             }
           ]
         },
```

</details>
