### DISCUSSION TITLE
PR Body and Title resets

### DISCUSSION THREAD

**Discussion by youngcm2** [renovatebot/renovate#24658] [Request Help]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

I would like to edit part of the body or title of the PR and have it persist between edits from renovate.

### What you tried so far.

I created a GitHub action that listens on pull_request with types created, synchronize, and edit

- If I rebase PR 1 through renovate, it starts the workflow using pull_request.synchronize for PR 1
- If I rebase PR 2 through renovate, it updates the title and body for PR 1, but it does not start the workflow for that PR 1, but does for PR 2
- If renovate runs its hourly job, it resets the title and body for PR 1 and PR 2

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```
Here is the job id: e18a7203-78f7-496b-b3e0-c27228944cd8
</details>

**Comment by rarkins** [comment]
If you want to change it, it's best to change it using Renovate config, otherwise Renovate will reset it back

**Reply by youngcm2** [reply]
The problem is that it needs to have data that is specific to each PR.

**Reply by rarkins** [reply]
I suggest you add it as a comment then, instead of modifying the body

**Reply by youngcm2** [reply]
Unfortunately, that does not allow Jira to link to GitHub.
![image](https://github.com/renovatebot/renovate/assets/862338/516482bb-097e-4da9-bbb9-6b109bfeaa53)

**Reply by rarkins** [reply]
So do you create a new Jira issue _after_ each Renovate PR and then want to add it back to the PR title?

**Reply by youngcm2** [reply]
Correct. We create a jira for each PR opened.

Here is the workflow and script I created. 

```
name: Create Renovate Jira
on:
  workflow_call:
    inputs:
      jira_host:
        description: "The Jira host to use"
        default: "foo.atlassian.net"
        type: string
        required: false
      jira_project:
        description: "The Jira project to use"
        default: "SPT"
        type: string
        required: false
      jira_user:
        description: "The Jira user to use"
        type: string
        required: true
      affects_version:
        description: "The Jira version to use"
        type: string
        required: false
      pr_number:
        description: "The PR number to use"
        type: string
        required: true
    secrets:
      jira_token:
        required: true
      PRIVATE_GITHUB_TOKEN:
        required: true

jobs:
  push-to-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "foo/renovate-config"
          path: "shared"
          fetch-depth: 0
          token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: |
          npm install jira-client

      - name: Push to Jira
        uses: actions/github-script@v6.4.0
        id: push-to-jira
        env:
          HOST: ${{inputs.jira_host}}
          JIRA_USER: ${{inputs.jira_user}}
          JIRA_TOKEN: ${{secrets.jira_token}}
          JIRA_PROJECT: ${{inputs.jira_project}}
          CURRENT_VERSION: ${{inputs.affects_version}}
          PR_NUMBER: ${{inputs.pr_number}}
        with:
            github-token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
            script: |
              const script = require('./shared/.github/workflows/scripts/createRenovateJiraTicket.js')
              await script({github, core, context})
  

``` 

```javascript
module.exports = async ({github, core, context}) => {
    const {default: JiraApi} = await import('jira-client');

    const {HOST, JIRA_USER, JIRA_TOKEN, JIRA_PROJECT, CURRENT_VERSION, PR_NUMBER} = process.env;
    const {payload} = context;
    let {pull_request} = context;
    const repoName = payload.repository.name;
    const owner = payload.repository.owner.login;

    if (!pull_request) {
        core.warning('Could not find pull_request on context')
        const pr = await github.rest.pulls.get({
            owner,
            repo: repoName,
            pull_number: PR_NUMBER
        })
        pull_request = pr.data
    }

    const {number, html_url, title, body} = pull_request

    const jira = new JiraApi({
        protocol: 'https',
        host: HOST,
        username: JIRA_USER,
        password: JIRA_TOKEN,
        apiVersion: '2',
        strictSSL: true
    });

    const match = title.match(/^([a-z]+)(\([^)]+\))?:\s*([^\n]+)/);
    const subject = match ? match[3] : null;
    const search = `${owner}/${repoName}(${number})`
    const summary = `${search}: ${subject}`;

    const searchString = `project = ${JIRA_PROJECT} AND issuetype = Task AND summary ~ "${search}"`;
    const matchingIssues = await jira.searchJira(searchString);

    const description = `${title}\n\n[Pull Request|${html_url}]`;

    const priority = 'P3';
    const issue = {
        fields: {
            project: {
                key: "SPT"
            },
            issuetype: {
                name: "Task"
            },
            summary: summary,
            labels: ['dependency-update'],
            priority: {
                name: priority
            },
            description: description,
            customfield_13323: {
                value: 'Internal',
                child: {
                    value: 'Dependency'
                }
            }//Component \ Feature
        }
    }

    if (CURRENT_VERSION) {
        issue.fields.versions = [{
            name: CURRENT_VERSION || ''
        }]
    }
    let key
    if (matchingIssues.total > 0) {
        core.info(`Jira ticket already exists for ${search}`);
        const existingIssue = matchingIssues.issues[0];
        key = existingIssue.key
        if (existingIssue.fields.status.name === 'Done' || existingIssue.fields.status.name === 'Closed') {
            core.info(`Jira ticket ${key} is already ${existingIssue.fields.status.name}}`);
            await jira.transitionIssue(key, {transition: {id: '61'}}) //Change request
        }
        issue.fields.description = description;
        await jira.updateIssue(key, issue);
        const message = `Updating jira issue: [${key}] - ${search}`;
        core.notice(message);
        await github.rest.issues.createComment({
            owner,
            repo: repoName,
            issue_number: PR_NUMBER,
            body: message
        })
    } else {
        const response = await jira.addNewIssue(issue)
        key = response.key;
        const message = `Creating jira issue: [${key}] - ${search}`;
        await jira.transitionIssue(key, {transition: {id: '31'}}) //ready for dev
        await jira.transitionIssue(key, {transition: {id: '41'}}) //start working
        await jira.transitionIssue(key, {transition: {id: '51'}}) //Ready for Code Review

        core.notice(message);
        await github.rest.issues.createComment({
            owner,
            repo: repoName,
            issue_number: PR_NUMBER,
            body: message
        })
        if (!title.startsWith(key)) {
            await github.rest.pulls.update({
                owner,
                repo: repoName,
                pull_number: PR_NUMBER,
                title: `${key} | ${title}`
            })
        }
    }

    const startTag = "<!--jira-start-->"
    const endTag = "<!--jira-end-->"

    const titleWithKey = !title.startsWith(key) ?
        `${key} | ${title}` :
        title

    const bodyWithLink = !body.includes(startTag) ?
        `${body}\n\n${startTag}\n\nJira Issue: [${key}](https://foo.atlassian.net/browse/${key})\n\n${endTag}`:
        body

    await github.rest.pulls.update({
        owner,
        repo: repoName,
        pull_number: PR_NUMBER,
        title: titleWithKey,
        body: bodyWithLink
    })
}


```
