### DISCUSSION TITLE
Detect + update Docker versions in CircleCI stages

### DISCUSSION THREAD

**Discussion by jamietanna** [renovatebot/renovate#24756] [Suggest an Idea]
### What would you like Renovate to be able to do?

Inside CircleCI configuration, as well as managing the Docker images referenced, there are mentions of the Docker engine that is used to run Docker executions.

For instance, the following snippet of a CircleCI step:

```yaml
      - setup_remote_docker:
          docker_layer_caching: true
          reusable: true
          version: 20.10.7
```

Has a Docker version of `20.10.7`, which could be highlighted as needing an update.

### If you have any ideas on how this should be implemented, please tell us here.

This may be do-able with a `regex` manager until this is fully supported.

### Is this a feature you are interested in implementing yourself?

Maybe
