### DISCUSSION TITLE
Kustomize: support docker digest pinning

### DISCUSSION THREAD

**Discussion by rarkins** [renovatebot/renovate#24767] [Suggest an Idea]
**What would you like Renovate to be able to do?**

Pin digests for docker images in Kustomize

**Did you already have any implementation ideas?**

Likely we need to use `autoReplaceStringTemplate`

**Comment by daurnimator** [comment]
We'd love this feature (and infact it would be required to use renovate)!
Is there any way to jury-rig it?

**Comment by rarkins** [comment]
If you *set* a digest manually then you should find it updates fine after that. This FR is just to automate the state of going from no digest to digest.

**Comment by daurnimator** [comment]
> If you _set_ a digest manually then you should find it updates fine after that. This FR is just to automate the state of going from no digest to digest.

In https://github.com/hashbang/gitops/blob/4df5f4c7f815ed2e993c7e15122bb4f4f60926f2/argocd/kustomization.yaml the images section was not updated, it still contains:
```
  - name: argoproj/argocd:v1.7.7
    digest: sha256:b835999eb5cf75d01a2678cd971095926d9c2566c9ffe746d04b83a6a0a2849f
```

**Comment by viceice** [comment]
digest pinning is currently not supported on kustomize, you can workaround using regex manager. looking into it

**Comment by viceice** [comment]
It's partially supported if you put digest to newTag, see #7987

**Comment by rarkins** [comment]
We maybe don't support that particular syntax. Can you create a reproduction repo (ie as simple as possible) and crest a separate issue to track?

**Comment by viceice** [comment]
Kustomize [images](https://kubectl.docs.kubernetes.io/references/kustomize/images/) are more complicated than i initially thought.

This are all working samples taken from [here](https://github.com/viceice-tests/kustomization/)
```yaml
kind: Kustomization

resources:
- deployment.yaml

images:
  - name: renovate/renovate
    newTag: 19-slim

  - name: mariadb
    digest: sha256:3f18ce9e12e3ece07029895336f5497eeb2d9cb8fe148cc54d4905f77cbc062d

  - name: alpine
    newTag: 3.12.2
    digest: sha256:25f5332d060da2c7ea2c8a85d2eac623bd0b5f97d508b165f846c7d172897438

  - name: postgres
    newTag: 11@sha256:b0cfe264cb1143c7c660ddfd5c482464997d62d6bc9f97f8fdf3deefce881a8c

  - name: busybox:1.30.0
    digest: sha256:e1488cb900233d035575f0a7787448cb1fa93bed0ccc0d4efc1963d7d72a8f17
    newTag: 1.32.1

  - name: busybox
    newName: amd64/busybox:1.30.1

  - name: busybox:1.0.0@sha256:e1488cb900233d035575f0a7787448cb1fa93bed0ccc0d4efc1963d7d72a8f17
    newName: amd64/busybox:1.1.1@sha256:53071b97a88426d4db86d0e8436ac5c869124d2c414caf4c9e4a4e48769c7f37
```
For some of them it's not clear what renovate should do.
