### DISCUSSION TITLE
Support `kustomize` manager with `github-releases` datasource

### DISCUSSION THREAD

**Discussion by djmcgreal-cc** [renovatebot/renovate#24769] [Suggest an Idea]
### What would you like Renovate to be able to do?

[Kserve](https://github.com/kserve/kserve) is an example of a project that publishes Kubernetes manifests through GitHub releases.

Could renovate extract from a URL like https://github.com/kserve/kserve/releases/download/v0.8.0/kserve-runtimes.yaml and assign it to the `github-releases` datasource?

### If you have any ideas on how this should be implemented, please tell us here.

Having browsed the code (nicely laid out by the way!), it seems like a possibly simple change within https://github.com/renovatebot/renovate/blob/24691ac42f3e7c6dda0d83e9dd62d8ee9e958593/lib/modules/manager/kustomize/extract.ts#L19 and https://github.com/renovatebot/renovate/blob/24691ac42f3e7c6dda0d83e9dd62d8ee9e958593/lib/modules/manager/kustomize/index.ts#L12

I'm answering "Maybe" to self-implementing because I don't yet know what tests and documentation might be affected.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by github-actions** [comment]
Hi there,

Get your issue fixed faster by creating a minimal reproduction. This means a repository dedicated to reproducing this issue with the minimal dependencies and config possible.

Before we start working on your issue we need to know exactly what's causing the current behavior. A minimal reproduction helps us with this.

To get started, please read our guide on creating a [minimal reproduction](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md).

We may close the issue if you, or someone else, haven't created a minimal reproduction within two weeks. If you need more time, or are stuck, please ask for help or more time in a comment.

Good luck,

The Renovate team

**Comment by rarkins** [comment]
I think your idea sounds right, but we'd need a reproduction repo to be sure.

**Comment by djmcgreal-cc** [comment]
I was able to add the support I needed via the regex manager:
```json
  "regexManagers": [
    {
      "fileMatch": "kustomization.yaml",
      "matchStrings": ["https:\/\/github\.com\/(?<depName>.*\/.*?)\/releases\/download\/(?<currentValue>.*?)\/"],
      "datasourceTemplate": "github-releases",
    },
    {
      "fileMatch": "kustomization.yaml",
      "matchStrings": ["https:\/\/raw.githubusercontent.com\/(?<depName>[^\/]*\/[^\/]*)\/(?<currentValue>.*?)\/"],
      "datasourceTemplate": "github-tags",
    }
  ]
```

That was easy, though an in-tree solution would still be preferable for better validation, etc! Thanks :)

**Reply by Ch4s3r** [reply]
Wanted to have a self updating argocd instance via gitops.
I used `argocd-autopilot repo bootstrap --app https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.0/manifests/install.yaml` to get a versioned app link in `bootstrap/argo-cd/kustomization.yaml` like this:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  literals:
  - |
    repository.credentials=- passwordSecret:
        key: git_token
        name: autopilot-secret
      url: https://github.com/
      usernameSecret:
        key: git_username
        name: autopilot-secret
  name: argocd-cm
kind: Kustomization
namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.0/manifests/install.yaml
```

And this solution still works flawless today:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:recommended"
  ],
  "customManagers": [
    {
      "customType": "regex",
      "description": "Update GitHub release references in kustomization.yaml",
      "fileMatch": ["kustomization.yaml"],
      "matchStrings": [
        "https:\\/\\/github\\.com\\/(?<depName>.*\\/.*?)\\/releases\\/download\\/(?<currentValue>.*?)\\/"
      ],
      "datasourceTemplate": "github-releases"
    },
    {
      "customType": "regex",
      "description": "Update GitHub tag references in kustomization.yaml",
      "fileMatch": ["kustomization.yaml"],
      "matchStrings": [
        "https:\\/\\/raw.githubusercontent.com\\/(?<depName>[^\\/]*\\/[^\\/]*)\\/(?<currentValue>.*?)\\/"
      ],
      "datasourceTemplate": "github-tags"
    }
  ]
}
```

This could be part of the `kustomize` manager or maybe a predefined config
