### DISCUSSION TITLE
[poetry] detect if allow-prereleases=true

### DISCUSSION THREAD

**Discussion by MrGreenTea** [renovatebot/renovate#24777] [Suggest an Idea]
**What would you like Renovate to be able to do?**

currently, If I have a `pyproject.toml` like this I won't get updates for the version `1.1a1` of `example`.
```toml
[tool.poetry.dependencies]
python = "^3.9"
example = { version = "1.0", allow-prereleases=true }
```

With some guidance/introduction I could see myself implementing this.
