### DISCUSSION TITLE
Updating go.sum artifact on Bitbucket Cloud

### DISCUSSION THREAD

**Discussion by caphrim007** [renovatebot/renovate#24783] [Suggest an Idea]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

Bitbucket Cloud

### Have you checked the logs? Don't forget to include them if relevant

I'm not sure if the logs are relevant or not. If they are, please advise.

### What would you like to do?

I have a BitBucket cloud repo with a go.mod file in it which resembles the following,

```
module bitbucket.org/myorg/service

go 1.13

require (
	bitbucket.org/myorg/services-sdk v0.0.0-20200304002603-d4886093cfe2
	github.com/aws/aws-sdk-go v1.30.23
	github.com/go-chi/chi v4.0.3+incompatible
	github.com/go-chi/cors v1.0.0
)
```

The relevant part of this question concerns the bitbucket.org `require` line. This is a private Bitbucket-cloud repository.

Renovate successfully finds and creates an issue with an update to the github.com requirements. I have a `excludePackagePatterns` package rule defined for the bitbucket.org due to missing support for such things in Renovate.

After Renovate creates the PR, it attempts to update the go.sum file. It fails though and adds a comment to the PR with the following in it

```
Command failed: go get -d ./...
go: bitbucket.org/myorg/services-sdk@v0.0.0-20200304002603-d4886093cfe2: reading https://api.bitbucket.org/2.0/repositories/myorg/services-sdk?fields=scm: 403 Forbidden
    server response: Access denied. You must have write or admin access.
```

For the life of me, I can't see to figure out what I need to configure to give it the necessary access. The user that renovate runs as has an app token and is a member of a group in Bitbucket which has write access to all repos.

I was hoping there is an obvious config or environment variable I can configure on the renovate side (not the repo side) to give it the necessary info (like a host rule or something).

I see mention of Github specific config concerning preCommands here

https://github.com/renovatebot/renovate/blob/master/lib/manager/gomod/artifacts.ts#L13

though its unclear to me if applying the same for Bitbucket would make the above `go` command work as this appears to be specifically raised by `go`.

Any help is appreciated.

**Comment by rarkins** [comment]
`You must have write or admin access.` is strange. Perhaps it's an incorrect log message and only read is necessary.

We will need an enhancement to our go artifacts code here: https://github.com/renovatebot/renovate/blob/6ec460b735e45f5a6d65662a2c5ffd51f8e3a5d6/lib/manager/gomod/artifacts.ts#L13-L29

**Comment by caphrim007** [comment]
@rarkins in much the same spirit as was done with python hash support, I'm happy to test anything that may be proposed. I will try duplicating the mentioned code and adjusting for Bitbucket to see if that results in any progress. Will provide feedback here for you.

One question, are host-rules capable of being specified in the Renovate configuration that runs as a cronjob? or must it be specified in the renovate.json within the repository under management.

**Comment by rarkins** [comment]
hostRules can be defined in the bot config too

**Comment by taraspos** [comment]
Hey, I'm having a similar issue.

I'm using renovate cli from docker image on bitbucket pipelines like:
```yaml
    renovate-bot:
      - step:
          image: renovate/renovate:23.89 
          name: Renovate Bot
          clone:
            enabled: false
          script:
            - export GOPRIVATE=bitbucket.org/my_org/*
            - export BB_USER=renovateuser
            - git config --global url."https://${BB_USER}:${RENOVATE_PASSWORD}@bitbucket.org".insteadOf "https://bitbucket.org"
            - renovate  --username=${BB_USER} --log-level debug --platform=bitbucket $BITBUCKET_REPO_FULL_NAME
```

however, getting the following error:
```
DEBUG: Failed to look up dependency bitbucket.org/my_org/go-lib
```

Question:
1. `git config --global` I provided before, seems to be ignored. Is it because `renovatebot` overwrites it during run?
2. Can I solve the problem by providing custom `hostRules` or it will not work until #3496 is implemented? If adding `hostRules` can help, what is the correct format for the CLI parameter? Is it `--host-rules hostName:bitbucket.org,username:${BB_USER},password:${RENOVATE_PASSWORD}`?
