### DISCUSSION TITLE
Support npmv7 (lock file v2) for transitiveRemediation

### DISCUSSION THREAD

**Discussion by rarkins** [renovatebot/renovate#24816] [Suggest an Idea]
**What would you like Renovate to be able to do?**

Support `transitiveRemediation` option for npm v7.

**Did you already have any implementation ideas?**

Unfortunately it needs some bugs in `npm` identified and either fixed by the `npm` team or a workaround found.

**Comment by HonkingGoose** [comment]
@rarkins Can you maybe add links/references to those bugs you need to get fixed before we can start on this feature? It's not clear to me what upstream fixes you need before this can get unblocked. 😉

**Comment by rarkins** [comment]
One of them is https://github.com/npm/cli/issues/3171

I didn't have time to document any other problems I found, unfortunately.

**Comment by HonkingGoose** [comment]
> One of them is [npm/cli#3171](https://github.com/npm/cli/issues/3171)

The author of the bug report says:

> Closing this issue as it's now resolved (tested with npm 7.20.3, but I think it was already fixed since a few minor versions).

But I think you're still waiting on bugfixes for other things as well? So this is still `status:blocked` I think?

**Comment by rarkins** [comment]
Todo:
- [ ] Test whether npm@7 "heals" a `package-lock.json` when it is incomplete

Example:
- Find an example repo where the lock file is at least a little out of date (could benefit from lock file maintenance)
- Find a range which can be bumped
- Replace the existing version with a valid newer version
- Delete the resolved file entry + hash
- Run `npm install`
- Verify if the lock file has been updated (not just the file + hash but also its transitive dependencies if relevant)

npm@6 does this, npm@7 did not when I last tried it. In other words npm@7 failed to identify invalid lock files, while npm@6 and all versions of yarn do.

**Comment by wrslatz** [comment]
👋🏻 Is there any update for this issue? With [Node.js 12 approaching EOL](https://nodejs.org/en/about/releases/) on 2022-04-30, many projects will be updating to Node.js 14 / 16. [Newer npm versions come packaged](https://nodejs.org/en/download/releases/) with Node.js 14 / 16, meaning more projects will be using the v2 version for lock files and lack of Renovate support for transitive remediation with lock file v2 version will impact more projects.

Edited: clarity

**Comment by rarkins** [comment]
Are you sure you understand what this issue is about? Because it's certainly no blocker for updating your npm version.

**Comment by wrslatz** [comment]
> Are you sure you understand what this issue is about? Because it's certainly no blocker for updating your npm version. 

If we update to npm v7 / v8, our lock files will update to the v2 format. Won't that mean we would lose out on transitive remediation until that support is added?

**Comment by rarkins** [comment]
Thanks for the clarification. Transitive remediation is quite an edge case, so that's why I don't consider it a blocker. Unfortunately some changes to npm>6 make it much harder to achieve.

**Comment by codepunkt** [comment]
That's interesting to hear.

Transitive remediation and de-duping of transitive dependencies are really important to us - just wanted to let you know.

**Comment by wrslatz** [comment]
> Transitive remediation and de-duping of transitive dependencies are really important to us - just wanted to let you know.

Same here. Transitive dependencies make up the _vast_ majority of our findings and automated fixes from Renovate.

**Comment by wrslatz** [comment]
Linking related issue for awareness: https://github.com/renovatebot/renovate/issues/3080

**Comment by rarkins** [comment]
This is now partially supported. If a transitive remediation bubbles all the way up to to cause a `package.json` change, then the PR will be created. But any transitive remediation which affects the `package-lock.json` only will not create a PR. This is still due to npm 7+ limitations we have not been able to overcome. The good news it that any such vulnerabilities would be remediated by a simple "lock file update" PR so you should enable those e.g. on a weekly basis and you should achieve essentially the same level of remediation.

**Comment by mizdra** [comment]
## Workaround: Use dependabot for security updates
Official support is available now, but I'd like to introduce the workaround I use. This allows normal package updates to be opened in renovate and security updates in dependabot. This may be useful for those who want to automate the review of security updates.

```yaml
# .github.dependabot.yml

# NOTE: Yaml aliases are not allowed in dependabot.yml. Therefore, there are many duplicates.

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      # PR of security update ignores interval and opens PR at arbitrary timing,
      # but this is a required option, so I have no choice to specify it.
      interval: "daily"
    # Prevent PRs from opening except for security updates
    open-pull-requests-limit: 0
    # Add reviewers automatically
    reviewers:
      - "my-org/my-team"
      - "octocat"

  - package-ecosystem: "npm"
    directory: "/packages/pakcage-a"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    reviewers:
      - "my-org/my-team"
      - "octocat"

  - package-ecosystem: "npm"
    directory: "/packages/pakcage-b"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    reviewers:
      - "my-org/my-team"
      - "octocat"
```
