### DISCUSSION TITLE
Support Hatch (PEP621) environment's dependencies

### DISCUSSION THREAD

**Discussion by jonathanberthias** [renovatebot/renovate#24956] [Suggest an Idea]
### Tell us more.

[Hatch](https://hatch.pypa.io/latest/) is a python dependency manager which uses the PEP621 standard. As such, we can reuse the work that has been done for the [pep621 manager](https://docs.renovatebot.com/modules/manager/pep621/) to update dependencies in the `project.dependencies` table.

This request is to support hatch's [environments](https://hatch.pypa.io/latest/config/environment/overview/), which can each have their own set of [dependencies](https://hatch.pypa.io/latest/config/environment/overview/#dependencies). This is an example config for an environment named `lint`:
```toml
[tool.hatch.envs.lint]
detached = true
dependencies = [
  "black==23.1.0",
  "mypy>=1.0.0",
  "ruff>=0.0.243",
]
```

It would be nice if Renovate could update these dependencies.

Note that hatch does not have a lock file at the moment, but [it should be added in the future](https://github.com/pypa/hatch/issues/749).
