### DISCUSSION TITLE
"Lock file error - aborting" after switching to JS config

### DISCUSSION THREAD

**Discussion by ZacSweers** [renovatebot/renovate#25081] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

37.6.3

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

I am trying to get this working for the first time

### Describe the problem

After switching from a JSON config to a JS config (so we can access env vars for an authenticated artifactory), we started getting soft failures from renovate due to a vague `Lock file error - aborting` error. After re-running with debug and also testing with full logging, I don't get any extra details beyond what's pasted below.

I have attempted to make a minimal reproducer in a couple of public repositories, but am unable to so far. The internal codebase is quite large so it's almost certainly hitting some sort of edge case.

### Relevant debug logs

<details><summary>Logs</summary>

```
Status: Downloaded newer image for ghcr.io/renovatebot/renovate:latest
 INFO: Repository started (repository=<redacted>)
       "renovateVersion": "37.6.3"
 INFO: Dependency extraction complete (repository=<redacted>, baseBranch=main)
       "stats": {
         "managers": {
           "buildkite": {"fileCount": 14, "depCount": 16},
           "dockerfile": {"fileCount": 1, "depCount": 1},
           "github-actions": {"fileCount": 29, "depCount": 102},
           "gradle": {"fileCount": 770, "depCount": 509},
           "gradle-wrapper": {"fileCount": 1, "depCount": 1},
           "kotlin-script": {"fileCount": 14, "depCount": 45},
           "npm": {"fileCount": 1, "depCount": 16}
         },
         "total": {"fileCount": 830, "depCount": 690}
       }
 INFO: Use matchDepPatterns instead of matchPackagePatterns (repository=<redacted>, baseBranch=main)
       "packageRule": {
         "matchPackagePatterns": [
           "^androidx\\.([\\w-:]+)$",
           "^org\\.robolectric([\\w-.]*):([\\w-]+)$",
           "^com\\.google\\.accompanist:([\\w-]+)$"
         ],
         "description": "Libraries allowed to use non-stable releases.",
         "ignoreUnstable": false
       },
       "packageName": "androidx.baselineprofile:androidx.baselineprofile.gradle.plugin",
       "depName": "androidx.baselineprofile"
 INFO: Use matchDepNames instead of matchPackageNames (repository=<redacted>, baseBranch=main)
       "packageRule": {
         "matchPackageNames": ["detekt", "io.gitlab.arturbosch.detekt"],
         "groupName": "Detekt"
       },
       "packageName": "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin",
       "depName": "io.gitlab.arturbosch.detekt"
 INFO: DRY-RUN: Would ensure edited/blocked PR comment in PR #82351 (repository=<redacted>, baseBranch=main, branch=renovate/compose-libraries-and-tools)
 INFO: DRY-RUN: Would commit files to branch renovate/androidx.benchmark (repository=<redacted>, baseBranch=main, branch=renovate/androidx.benchmark)
 INFO: Lock file error - aborting (repository=<redacted>)
 INFO: Repository finished (repository=<redacted>)
       "cloned": true,
       "durationMs": 501422
```

</details>

<details><summary>New JS Config</summary>

```javascript
module.exports = {
  extends: [
    "config:recommended"
  ],
  reviewers: [
    "team:android-librarians"
  ],
  labels: [
    "type:dependency",
    "mergequeue:queued"
  ],
  prHourlyLimit: 30,
  allowedPostUpgradeCommands: [
    "^\\./gradlew dependencyGuardBaseline$"
  ],
  postUpgradeTasks: {
    description: "Run dependencyGuardBaseline to update classpath files.",
    commands: [
      "./gradlew dependencyGuardBaseline"
    ],
    fileFilters: [
      "**/*.versions.toml",
      "**/dependencies/*lasspath.txt",
      "dependencies/classpath.txt"
    ],
    executionMode: "update"
  },
  hostRules: [
    {
      hostType: 'maven',
      matchHost: 'redacted internal artifactory',
      username: process.env.<redacted>,
      password: process.env.<redacted>,
    },
  ],
  packageRules: [
    {
      matchPackageNames: [
        "python"
      ],
      allowedVersions: "3.9.13-slim",
      description: "Must be kept in sync with mdevxp repo interpreter_constraints."
    },
    {
      matchDatasources: ['maven'],
      registryUrls: [
        // Slack Artifactory
        'redacted internal artifactory',
        // Google Maven
        'https://dl.google.com/dl/android/maven2/',
        // Gradle Plugins Portal
        'https://plugins.gradle.org/m2/',
        // Maven central
        'https://repo.maven.apache.org/maven2/',
        // Maven central s01
        'https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/'
      ],
    },
    {
      matchPackageNames: [
        "com.microsoft.thrifty:thrifty-runtime"
      ],
      allowedVersions: "0.4.3",
      description: "Pinned due to us using a diabolically old version."
    },
    {
      matchPackageNames: [
        "dev.chrisbanes.insetter:insetter"
      ],
      allowedVersions: "0.5.0",
      description: "Pinned due to issues we need to fix in 0.6.1."
    },
    {
      matchPackageNames: [
        "detekt",
        "io.gitlab.arturbosch.detekt"
      ],
      groupName: "Detekt"
    },
    {
      matchPackageNames: [
        "com.google.guava:guava"
      ],
      allowedVersions: "32.0.1-jre",
      description: "Pinned until Paparazzi fixes itself: https://github.com/cashapp/paparazzi/issues/552. Note when we remove the pinned version, we should replace the allowed version with !/\\-android$/ again."
    },
    {
      matchPackageNames: [
        "com.microsoft.intune.mam:sdk",
        "com.microsoft.intune.mam"
      ],
      groupName: "Intune",
      additionalReviewers: [
        "team:android-enterprise"
      ]
    },
    {
      matchPackageNames: [
        "androidx.benchmark:benchmark-junit4",
        "androidx.benchmark:benchmark-gradle-plugin",
        "androidx.benchmark:benchmark-macro-junit4",
        "androidx.benchmark:benchmark-macro",
        "androidx.benchmark"
      ],
      groupName: "AndroidX Benchmark"
    },
    {
      matchPackagePatterns: [
        "^com\\.squareup\\.anvil([\\w-:]+)$"
      ],
      groupName: "Anvil"
    },
    {
      matchPackageNames: [
        "flipper-pkg",
        "com.facebook.flipper:flipper",
        "com.facebook.flipper:flipper-leakcanary2-plugin",
        "com.facebook.flipper:flipper-network-plugin",
        "com.facebook.soloader:soloader"
      ],
      ignoreUnstable: false,
      groupName: "Flipper",
      extends: [
        "schedule:monthly"
      ]
    },
    {
      matchPackagePatterns: [
        "^androidx\\.compose([\\w-.]*):([\\w-]+)$",
        "^androidx\\.emoji2:([\\w-]+)$",
        "^com\\.google\\.accompanist:([\\w-]+)$"
      ],
      groupName: "Compose Libraries and Tools"
    },
    {
      matchPackagePatterns: [
        "^androidx\\.activity:([\\w-]+)$",
        "^androidx\\.core:([\\w-]+)$",
        "^androidx\\.fragment:([\\w-]+)$",
        "^androidx\\.lifecycle:([\\w-]+)$"
      ],
      description: "AndroidX core libraries usually must be updated together due to cross-dependencies.",
      groupName: "AndroidX Core Libraries"
    },
    {
      matchPackagePatterns: [
        "^androidx\\.test([\\w-.]*):([\\w-]+)$",
        "^org\\.robolectric([\\w-.]*):([\\w-]+)$"
      ],
      groupName: "AndroidX Test/Robolectric"
    },
    {
      matchPackageNames: [
        "com.android.tools.build:gradle"
      ],
      groupName: "AGP",
      description: "We have multiple renovate-triggered AGP updates for shadow builds, so this tells renovate to batch them together when possible."
    },
    {
      matchPackageNames: [
        "renovatebot/github-action"
      ],
      extends: [
        "schedule:monthly"
      ]
    },
    {
      matchPackagePatterns: [
        "^androidx\\.([\\w-:]+)$",
        "^org\\.robolectric([\\w-.]*):([\\w-]+)$",
        "^com\\.google\\.accompanist:([\\w-]+)$"
      ],
      description: "Libraries allowed to use non-stable releases.",
      ignoreUnstable: false
    },
    {
      matchPackageNames: [
        "org.jetbrains.kotlinx.kover"
      ],
      allowedVersions: "0.6.1",
      description: "Pinned until we finish upgrading to 0.7.1"
    },
    {
      matchPackagePrefixes: [
        "com.squareup.anvil:"
      ],
      allowedVersions: "2.4.7",
      description: "Anvil uses a weird versioning scheme where renovate incorrectly thinks an older version is newer"
    },
    {
      matchPackagePrefixes: [
        "com.google.android.exoplayer:"
      ],
      allowedVersions: "2.18.7",
      description: "This is pinned until we migrate to media3"
    },
    {
      matchPackageNames: [
        "org.mockito:mockito-inline",
        "org.mockito:mockito-core"
      ],
      allowedVersions: "4.11.0",
      description: "Pinned until we can migrate to 5.0"
    },
    {
      matchPackageNames: [
        "com.android.tools:r8"
      ],
      allowedVersions: "3.0.9-dev",
      description: "Pinned until we can update Keeper to a newer R8 version."
    },
    {
      matchPackageNames: [
        "software.aws.chimesdk:amazon-chime-sdk-media",
        "software.aws.chimesdk:amazon-chime-sdk"
      ],
      description: "We upgrade and test the Chime SDK once a month to reduce likelihood of bugs.",
      ignoreUnstable: true,
      extends: [
        "schedule:monthly"
      ]
    },
    {
      matchManagers: [
        "maven"
      ],
      description: "Disable snapshot versions. THIS MUST GO AT THE END OF THE PACKAGE RULES LIST! Note this doesn't appear to work currently, but left as a toe-hold for future experimentation.",
      matchCurrentVersion: "/.*-SNAPSHOT/",
      enabled: false
    }
  ]
}

```

</details>

<details><summary>Old JSON Config</summary>

```json
{
  "extends": [
    "config:recommended"
  ],
  "reviewers": [
    "team:android-librarians"
  ],
  "labels": [
    "type:dependency",
    "mergequeue:queued"
  ],
  "prHourlyLimit": 30,
  "postUpgradeTasks": {
    "description": "Run dependencyGuardBaseline to update classpath files.",
    "commands": [
      "./gradlew dependencyGuardBaseline"
    ],
    "fileFilters": [
      "**/*.versions.toml",
      "**/dependencies/*lasspath.txt",
      "dependencies/classpath.txt"
    ],
    "executionMode": "update"
  },
  "packageRules": [
    {
      "matchPackageNames": [
        "python"
      ],
      "allowedVersions": "3.9.13-slim",
      "description": "Must be kept in sync with mdevxp repo interpreter_constraints."
    },
    {
      "matchPackageNames": [
        "com.microsoft.thrifty:thrifty-runtime"
      ],
      "allowedVersions": "0.4.3",
      "description": "Pinned due to us using a diabolically old version."
    },
    {
      "matchPackageNames": [
        "dev.chrisbanes.insetter:insetter"
      ],
      "allowedVersions": "0.5.0",
      "description": "Pinned due to issues we need to fix in 0.6.1."
    },
    {
      "matchPackageNames": [
        "detekt",
        "io.gitlab.arturbosch.detekt"
      ],
      "groupName": "Detekt"
    },
    {
      "matchPackageNames": [
        "com.google.guava:guava"
      ],
      "allowedVersions": "32.0.1-jre",
      "description": "Pinned until Paparazzi fixes itself: https://github.com/cashapp/paparazzi/issues/552. Note when we remove the pinned version, we should replace the allowed version with !/\\-android$/ again."
    },
    {
      "matchPackageNames": [
        "com.microsoft.intune.mam:sdk",
        "com.microsoft.intune.mam"
      ],
      "groupName": "Intune",
      "additionalReviewers": [
        "team:android-enterprise"
      ]
    },
    {
      "matchPackageNames": [
        "androidx.benchmark:benchmark-junit4",
        "androidx.benchmark:benchmark-gradle-plugin",
        "androidx.benchmark:benchmark-macro-junit4",
        "androidx.benchmark:benchmark-macro",
        "androidx.benchmark"
      ],
      "groupName": "AndroidX Benchmark"
    },
    {
      "matchPackagePatterns": [
        "^com\\.squareup\\.anvil([\\w-:]+)$"
      ],
      "groupName": "Anvil"
    },
    {
      "matchPackageNames": [
        "flipper-pkg",
        "com.facebook.flipper:flipper",
        "com.facebook.flipper:flipper-leakcanary2-plugin",
        "com.facebook.flipper:flipper-network-plugin",
        "com.facebook.soloader:soloader"
      ],
      "ignoreUnstable": false,
      "groupName": "Flipper",
      "extends": [
        "schedule:monthly"
      ]
    },
    {
      "matchPackagePatterns": [
        "^androidx\\.compose([\\w-.]*):([\\w-]+)$",
        "^androidx\\.emoji2:([\\w-]+)$",
        "^com\\.google\\.accompanist:([\\w-]+)$"
      ],
      "groupName": "Compose Libraries and Tools"
    },
    {
      "matchPackagePatterns": [
        "^androidx\\.activity:([\\w-]+)$",
        "^androidx\\.core:([\\w-]+)$",
        "^androidx\\.fragment:([\\w-]+)$",
        "^androidx\\.lifecycle:([\\w-]+)$"
      ],
      "description": "AndroidX core libraries usually must be updated together due to cross-dependencies.",
      "groupName": "AndroidX Core Libraries"
    },
    {
      "matchPackagePatterns": [
        "^androidx\\.test([\\w-.]*):([\\w-]+)$",
        "^org\\.robolectric([\\w-.]*):([\\w-]+)$"
      ],
      "groupName": "AndroidX Test/Robolectric"
    },
    {
      "matchPackageNames": [
        "com.android.tools.build:gradle"
      ],
      "groupName": "AGP",
      "description": "We have multiple renovate-triggered AGP updates for shadow builds, so this tells renovate to batch them together when possible."
    },
    {
      "matchPackageNames": [
        "renovatebot/github-action"
      ],
      "extends": [
        "schedule:monthly"
      ]
    },
    {
      "matchPackagePatterns": [
        "^androidx\\.([\\w-:]+)$",
        "^org\\.robolectric([\\w-.]*):([\\w-]+)$",
        "^com\\.google\\.accompanist:([\\w-]+)$"
      ],
      "description": "Libraries allowed to use non-stable releases.",
      "ignoreUnstable": false
    },
    {
      "matchPackageNames": [
        "org.jetbrains.kotlinx.kover"
      ],
      "allowedVersions": "0.6.1",
      "description": "Pinned until we finish upgrading to 0.7.1"
    },
    {
      "matchPackagePrefixes": [
        "com.squareup.anvil:"
      ],
      "allowedVersions": "2.4.7",
      "description": "Anvil uses a weird versioning scheme where renovate incorrectly thinks an older version is newer"
    },
    {
      "matchPackagePrefixes": [
        "com.google.android.exoplayer:"
      ],
      "allowedVersions": "2.18.7",
      "description": "This is pinned until we migrate to media3"
    },
    {
      "matchPackageNames": [
        "org.mockito:mockito-inline",
        "org.mockito:mockito-core"
      ],
      "allowedVersions": "4.11.0",
      "description": "Pinned until we can migrate to 5.0"
    },
    {
      "matchPackageNames": [
        "com.android.tools:r8"
      ],
      "allowedVersions": "3.0.9-dev",
      "description": "Pinned until we can update Keeper to a newer R8 version."
    },
    {
      "matchPackageNames": [
        "software.aws.chimesdk:amazon-chime-sdk-media",
        "software.aws.chimesdk:amazon-chime-sdk"
      ],
      "description": "We upgrade and test the Chime SDK once a month to reduce likelihood of bugs.",
      "ignoreUnstable": true,
      "extends": [
        "schedule:monthly"
      ]
    },
    {
      "matchManagers": [
        "maven"
      ],
      "description": "Disable snapshot versions. THIS MUST GO AT THE END OF THE PACKAGE RULES LIST! Note this doesn't appear to work currently, but left as a toe-hold for future experimentation.",
      "matchCurrentVersion": "/.*-SNAPSHOT/",
      "enabled": false
    }
  ]
}
```

</details>

<details><summary>Renovate github action</summary>

```yml
name: Renovate

on:
  schedule:
    # Run once per day at 12pm PST, M/Tu/W/Fr. Skip Thursdays because of friday's build cuts
    - cron: '0 20 * * 1,2,3,5'
  # Always run on PRs if this file was modified! We won't PR changes if we modify the file though
  pull_request:
    paths:
      - '.github/workflows/renovate.yml'
      - 'renovate.json'
      - 'config/renovate/renovate.config.js'
  workflow_dispatch:
    inputs:
      dryRun:
        type: choice
        description: "Dry-Run (leave empty for default)"
        default: ""
        options:
          - ''
          - 'extract'
          - 'lookup'
          - 'full'
        required: false

concurrency:
  group: '${{ github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

env:
  RENOVATE_DRY_RUN: false
  RENOVATE_REPOSITORIES: ${{ github.repository }}
  RENOVATE_GIT_AUTHOR: "<redacted>"

jobs:
  renovate:
    runs-on: [self-hosted, Linux, X64, mobile-build-release, android-large]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: '${{ secrets.<redacted> }}'

      - name: Prepare build env
        uses: ./.github/actions/prepare-android-env

      - name: Override default config from dispatch variables
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" || "${{ github.event_name }}" == "merge_group" ]]; then
            # Always dry-run in PRs
            echo "RENOVATE_DRY_RUN=full" >> "${GITHUB_ENV}"
            # Always use debug logging if it's a PR
            echo "RENOVATE_BASE_BRANCHES=${{ github.event.pull_request.base.ref }}" >> "${GITHUB_ENV}"
          elif [[ "${{ github.event.inputs.dryRun }}" != "" ]]; then
            # Use the input dryRun value
            echo "RENOVATE_DRY_RUN=${{ github.event.inputs.dryRun }}" >> "${GITHUB_ENV}"
          fi

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.5
        with:
          configurationFile: 'config/renovate/renovate.config.js'
          token: '${{ secrets.<redacted> }}'

```

</details>

### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible
