### DISCUSSION TITLE
For helm manager is there is a way to restrict not just chart version but app version as well?

### DISCUSSION THREAD

**Discussion by ivankatliarchuk** [renovatebot/renovate#25087] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

`allowedversions` or similar attribute to allow with regex max Aplication version for a helm chart.

Let's say we have a helm A that depends on helm B

```yml
apiVersion: v2
name: cluster-autoscaler-A
type: application
version: 1.0.0
appVersion: "1.23.0"
home: https://github.com/my-custom-helm-with-dependencies/autoscaler
dependencies:
- name: cluster-autoscaler
  version: 9.27.0
  repository: https://kubernetes.github.io/autoscaler
  condition: enabled
```

and B

```yaml
apiVersion: v2
name: cluster-autoscaler-B
type: application
version: 9.27.0
appVersion: "1.24.0"
home: https://github.com/kubernetes/autoscaler
```

So that in Renovate configuration, I can not just limit a chart `version` but an `appVersion` as well.

Currently we can configure

```js
    {
        "description": "Version range for cluster-autoscaler helm chart",
        "matchPackageNames": ["cluster-autoscaler"],
        "allowedVersions": "<= 9.27"
    },
```

but not able to configure something like

```js
    {
        "description": "Version range for cluster-autoscaler helm chart",
        "matchPackageNames": ["cluster-autoscaler"],
        "allowedAppVersions": "<= 1.24"
    },
```

### What you tried so far.

This is how it's currently configured

```js
packageRules = [
    {
        "description": "Version range for cluster-autoscaler helm chart",
        "matchPackageNames": ["cluster-autoscaler"],
        "allowedVersions": "<= 9.27"
    },
]
```

This configuration will successfuly create a pull request with helm chart version limited to 9.27.

What I'm trying to achieve, is restrict max application version 
![Screenshot 2023-10-07 at 10 01 27](https://github.com/renovatebot/renovate/assets/5395690/ac6dc073-2bc3-4232-b565-2d768d982e60)

something like that

```js
packageRules = [
    {
        "description": "Version range for cluster-autoscaler helm chart",
        "matchPackageNames": ["cluster-autoscaler"],
        "matchManagers": ["helmv3"],
        "allowedAppVersions": "<= 1.24"
    },
]
```

The use case;
- there is a number of kubernetes components that must run on kuberntes cluster and they app versioniong is restricted to a cluster version `± 1`

Probably similar functionality already exists. 

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>
