### DISCUSSION TITLE
exec format error

### DISCUSSION THREAD

**Discussion by audibleblink** [renovatebot/renovate#25124] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

36.97.3

### If you're self-hosting Renovate, select which platform you are using.

Gitea or Forgejo

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Wanted end result.

I'd like to continue to update renovate

### What you tried so far.

Renovate used to work and after an attempt to take the output of 

```sh
helm template renovate renovate/renovate
```

and use kustomize moving forward, I began to receive an error that's usually associated with trying to run a binary built for a different architecture. Upon running the helm-built yaml files, and after deleting renovate completely from my k8s cluster, I'm receiving `exec format error`. I reverted my repo to use the same working helm config and I'm still receiving the same exec error.

If I use the crontab.yaml provided in the documentation, (which sports a version 35.14.4), it will run, but because I used to use a more recent version, my error is one of having a bad config file at the repo root. But at least renovate is running. Attempting to update to any version after 35.14.4 yields the exec error.

Nodes are running ubuntu 22.04 and are amd64. Still, I tried swapping out the image in the crontab.yaml with the following.

    # newTag: "37.11-full@sha256:1a69af791eb6c64ff9c9bad7995fa651a25888a23f6d56cfb55b4110ad190131" #arm
    # newTag: "37.11-full@sha256:84b304d9bfd649c0cc6fe8166431fc0df0839aca6f6122114fe75aafccd6fbb9" #amd64
    # newTag: "37.11" #amd64
    # newTag: "37.11-full"

All gave `exec format error`

I'm throughly confused and hoping someone has seen something similar.

---

I cut out any CI involved and tried to just deploy clean in a new namespace. Results below.

```sh

❯❯ helm install renovate renovate/renovate --create-namespace --namespace renovate --values values.yaml                                               ⎈ renovate

NAME: renovate
LAST DEPLOYED: Tue Oct 10 15:25:58 2023
NAMESPACE: renovate
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
A renovate CronJob will run with schedule 0 9 * * *.

❯❯ k create job --from=cronjob/renovate asdf-manual-job                                                                                               ⎈ renovate
job.batch/asdf-manual-job created

❯❯ kgp                                                                                                                                                ⎈ renovate
NAME                    READY   STATUS   RESTARTS   AGE
asdf-manual-job-jxk8d   0/1     Error    0          3s

❯❯ k logs asdf-manual-job-jxk8d                                                                                                                       ⎈ renovate
exec /usr/local/bin/docker-entrypoint.sh: exec format error

```

### Relevant debug logs

<details><summary>cronjob.yaml</summary>

```yml
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
            - name: RENOVATE_CONFIG_FILE
              value: /usr/src/app/config.json
            envFrom:
            - secretRef:
                name: renovate-gitea
            image: ${image}
            imagePullPolicy: Always
            name: renovate
            volumeMounts:
            - mountPath: /usr/src/app/config.json
              name: config-volume
              subPath: config.json
          restartPolicy: Never
          volumes:
          - configMap:
              name: renovate-config
            name: config-volume
  schedule: '@hourly'

```
</details>

<details><summary>configmap.yaml</summary>

```yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |-
    {
      "platform": "gitea",
      "endpoint": "https://git.i.ctrl.red/api/v1",
      "gitAuthor": "Renovate Bot <bot@renovateapp.com>"
    }
```
</details>

<details><summary>values.yaml</summary>

```yml
---
cronjob:
  schedule: '0 9 * * *'  # Everyday at 09:00
existingSecret: renovate-gitea
renovate:
  config: |
    {
      "platform": "gitea",
      "endpoint": "https://git.ctrl.red/api/v1",
      "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
      "autodiscover": "true"
    }
```

</details>
