### DISCUSSION TITLE
Sign Commits using Ephemeral Keys

### DISCUSSION THREAD

**Discussion by adam-moss** [renovatebot/renovate#25126] [Suggest an Idea]
### Tell us more.

Renovate currently supports the signing of commits using PGP.

In https://github.com/renovatebot/renovate/issues/18197 I suggested extending this to support `ssh` based key signing since that is somewhat easier to use/manage than pgp based keys, especially if you aren't familiar with pgp.

A further enhancement could be the utilisation of ephemeral keys via `sigstore`, with configuration options to use the public instance (default), or an on-prem instance.

This may be challenging due to the OIDC auth flow, I haven't looked in to that in too much detail currently.

Related https://github.com/renovatebot/renovate/discussions/11228, which I think would be a fantastic addition to renovate, helping promote supply chain security more widely.

**Comment by adam-moss** [comment]
Just to add like `ssh` based signing renovate _can_ currently do it if the `.gitconfig` file is configured appropriately prior to renovate executing, so this may be more appropriate for documentation if we don't want to support configuration directly (the same could apply to pgp if you wanted to _remove_ that capability)

Simple example for ssh signing:

```yaml
default:
    image:
        name: renovate/renovate:37@sha256:1179e913e97f5221922b680650f2d31eddd9645609c84406d839599e1ecfc0c1
        entrypoint: [""]

.renovate:
    variables:
        RENOVATE_CONFIG_FILE: "$CI_PROJECT_DIR/config.js"
        LOG_FORMAT: "json"
    script:
        - mkdir ~/.ssh
        - chmod 700 ~/.ssh
        - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
        - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        - chmod 600 ~/.ssh/id_ed25519
        - echo "$SSH_PRIVATE_KEY_SIGNING" > ~/.ssh/id_ed25519_renovate_signing_key
        - chmod 600 ~/.ssh/id_ed25519_renovate_signing_key
        - eval $(ssh-agent -s)
        - ssh-add ~/.ssh/id_ed25519
        - ssh-add ~/.ssh/id_ed25519_renovate_signing_key
        - git config --global commit.gpgsign true
        - git config --global gpg.format ssh
        - git config --global user.signingkey "$SSH_PUBLIC_KEY_SIGNING"
        - npm config set registry "<redact>"
        - pip3 config set --user global.index-url <redact>
        - poetry config http-basic.gitlab gitlab-ci-token "$CI_JOB_TOKEN"
        - echo "Renovating $REPOSITORY_LIST"
        - LOG_LEVEL=${LOG_LEVEL:-fatal} renovate $DRY_RUN $ADDITIONAL_CONFIG $REPOSITORY_LIST
    artifacts:
        paths:
            - renovate-log.json
        when: on_failure
        expire_in: 18 hours
    allow_failure: true
```
