### DISCUSSION TITLE
Explicit credentials no longer working after `automatic ghcr.io auth when using github.com`

### DISCUSSION THREAD

**Discussion by tomachristian** [renovatebot/renovate#25134] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

37.13.0

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the problem

Continuing the discussion from here https://github.com/renovatebot/renovate/pull/25017#discussion_r1354634293.

Explicit `hostRules` with credentials no longer working:

![image](https://github.com/renovatebot/renovate/assets/176021/9db4642f-62f8-43e4-99da-66909b8f7f20)

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

Placeholder value, please select the correct response from the dropdown

**Comment by rarkins** [comment]
Do you mean that you have configured ghcr.io authentication into hostRules which is a different token/permissions to the one which you use for github.com?

**Reply by tomachristian** [reply]
Correct, and that one is being completely ignored. I might add that we configure that through environment variables like so:

```
- name: "🔁 Renovate"
        id: renovate
        uses: renovatebot/github-action@v39.0.5

        env:
          # Repository taken from variable to keep configuration file generic
          RENOVATE_REPOSITORIES: ${{ github.repository }}

          # Unfortunately we need to use PAT tokens for now, GitHub App tokens are not supported by GitHub Packages
          # See https://docs.renovatebot.com/self-hosted-configuration/#detecthostrulesfromenv on how we pass these
          DOCKER_GHCR_IO_USERNAME: ${{ secrets.GH_READ_PACKAGES_USERNAME }}
          DOCKER_GHCR_IO_PASSWORD: ${{ secrets.GH_READ_PACKAGES_PAT }}

          NUGET_NUGET_PKG_GITHUB_COM_USERNAME: "renovate"
          NUGET_NUGET_PKG_GITHUB_COM_PASSWORD: ${{ secrets.GIT_PACKAGES_PAT }}

          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}

        with:
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|DOCKER_GHCR_IO_USERNAME|DOCKER_GHCR_IO_PASSWORD|NUGET_NUGET_PKG_GITHUB_COM_USERNAME|NUGET_NUGET_PKG_GITHUB_COM_PASSWORD)$"
          configurationFile: ".github/workflows/renovate.js"
          token: "${{ steps.login_github.outputs.token }}"
```

our `renovate.js`

```
﻿module.exports = {
    // No need for onboarding anymore, already done
    onboarding: false,

    // Give renovate access to our GitHub feeds

    // Some of the credentials are passed from our GitHub workflow
    // See the 'renovate.yml' file and https://docs.renovatebot.com/self-hosted-configuration/#detecthostrulesfromenv
    detectHostRulesFromEnv: true,

    hostRules: [
        {
            hostType: "docker",
            matchHost: "ghcr.io",
        },
        {
            hostType: "nuget",
            matchHost: "nuget.pkg.github.com",
        },
    ],

    // We are hosting Renovate ourselves as a GitHub Workflow, so there is no other user that it can use to approve its
    // own PRS; in this case we configure Renovate to auto-merge its own PRs by bypassing the rule.
    // This should also be configured under our repository branch rules to allow the bot to bypass rules and merge PRs.
    // See https://docs.renovatebot.com/configuration-options/#platformautomerge and
    // https://docs.renovatebot.com/key-concepts/automerge/#required-pull-request-reviews
    platformAutomerge: false,
};
```

this worked before this change: https://github.com/renovatebot/renovate/pull/25017
