### DISCUSSION TITLE
renovate cli timeout reached

### DISCUSSION THREAD

**Discussion by paymand** [renovatebot/renovate#25144] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

Placeholder value, please select the correct response from the dropdown

### Describe the problem

Getting these cli timeouts quite a lot:
<img width="1275" alt="image" src="https://github.com/renovatebot/renovate/assets/951563/2ed52dd2-d6ee-4ba8-8f4e-dd88232af2c5">
Any idea why and how to fix?

### Relevant debug logs

<details><summary>Logs</summary>

```
			"err": {
				"stack": "ExecError: Command failed: npm exec -- renovate\nInterrupted by SIGTERM\n    at ChildProcess.<anonymous> (/usr/src/app/node_modules/renovate/dist/util/exec/common.js:80:24)\n    at ChildProcess.emit (node:events:529:35)\n    at ChildProcess.emit (node:domain:489:12)\n    at ChildProcess._handle.onexit (node:internal/child_process:292:12)",
				"stdout": "",
				"options": {
					"stdio": "inherit",
					"encoding": "utf-8",
					"timeout": 900000
				},
				"name": "ExecError",
				"cmd": "/bin/sh -c npm exec -- renovate",
				"stderr": "",
				"message": "Command failed: npm exec -- renovate\nInterrupted by SIGTERM",
				"signal": "SIGTERM"
			},
			"level": 50,
			"v": 0,
			"name": "renovate",
			"pid": 8,
			"logContext": "GNTsYcHzmRgrQ3k_czSZz",
			"time": "2023-10-11T16:02:26.820Z",
			"status": "Error"
		}
```

</details>

### Have you created a minimal reproduction repository?

Placeholder value, please select the correct response from the dropdown

**Comment by paymand** [comment]
never mind, looks like the default timeout is 15 minutes (900000 ms as you can see in the logs).
Will need to bump: https://docs.renovatebot.com/self-hosted-configuration/#executiontimeout

**Comment by paymand** [comment]
mmm, bumping the timeout to 30 minutes did not help.
It's still timing out, albeit after 30 minutes:
<img width="850" alt="image" src="https://github.com/renovatebot/renovate/assets/951563/09547d20-81cc-46f1-920f-f9b65f5cdf7b">

**Reply by paymand** [reply]
There are about 160 repositories in our Github organization. Could that explain these timeouts?

1. I think I might need to consider persistent caching to see if the runtime improves.
2. Or maybe consider migrating from Renovate CE to Renovate EE. Having multiple workers might be the way to go?

**Reply by rarkins** [reply]
This looks to me like it is one particular repository which is timing out, and therefore independent of how many total repositories you have.

Renovate CE calls the Renovate CLI per-repo, and it appears to have a default timeout of 15 minutes per repo.

I think you can raise this to e.g. 30 minutes by setting RENOVATE_EXECUTION_TIMEOUT=30 in environment.

@Gabriel-Ladzaretti I think we should consider a higher per-repo timeout by default, perhaps even 60 minutes.

**Reply by Gabriel-Ladzaretti** [reply]
The only downside i can think of is that we will diverge from the renovate cli docs which might be confusing.

**Reply by rarkins** [reply]
Where in the Renovate CLI docs does it define a timeout per-repo?

**Reply by paymand** [reply]
I'm not sure if this timeout is per repo. From what I can see in the logs, the repos are being iterated sequentially.
I **am** using `RENOVATE_EXECUTION_TIMEOUT=30`.
Now I'm trying to change the cron schedule to every two hours and bumping the timeout to 90 minutes.

**Reply by Gabriel-Ladzaretti** [reply]
are you using autodiscoverFilter ?

**Reply by paymand** [reply]
Yes. Here's the current config:
```
mend-renovate-ce:
  renovate:
    logLevel: "debug"
    mendRnvPlatform: "github"
    mendRnvAcceptTos: "y"
    mendRnvEndpoint: "https://api.github.com/"
    # Existing secret with secret values with the following keys:
    #   mendRnvLicenseKey: # You can request a license key by submitting the form at https://www.mend.io/renovate-community/.
    #   mendRnvGithubAppId: # The GitHub App ID provided when you provisioned the Mend Renovate app. Force string format by quoting value.
    #   mendRnvGithubAppKey: # A string representation of the private key provided by GitHub Enterprise when you provisioned Mend Renovate
    #   mendRnvWebhookSecret: # Optional, defaults to 'renovate'
    #   mendRnvServerApiSecret: # Required if Admin APIs are enabled.
    existingSecret: "renovate"
    mendRnvCronJobScheduler: "0 */2 * * *" # Optional, defaults to '0 * * * *' (hourly)
    # mendRnvCronAppSync: # Optional AppSync schedule: defaults to '0 0,4,8,12,16,20 * * *' (every 4 hours, on the hour)
    # mendRnvSqliteFilePath: /db/renovate-ce.sqlite # Optional: Provide a path to persist the SQLite database (eg. '/db/renovate-ce.sqlite', where 'db' is defined as a volume)
    npmrc: |
      <REDACTED>
    mendRnvAdminApiEnabled: "true"
    extraEnvVars:
      - name: RENOVATE_USERNAME
        value: "<REDACTED>"
      - name: RENOVATE_GIT_AUTHOR
        value: "<REDACTED>"
      - name: RENOVATE_PLATFORM_COMMIT
        value: "true"
      - name: RENOVATE_NPMRC_MERGE
        value: "true"
      - name: RENOVATE_AUTODISCOVER
        value: "true"
      - name: RENOVATE_CONFIG_FILE
        value: "/mnt/secrets-store/config.json"
      - name: RENOVATE_DETECT_GLOBAL_MANAGER_CONFIG
        value: "true"
      - name: RENOVATE_BINARY_SOURCE
        value: "global"
      - name: LOG_FORMAT
        value: "json"
      - name: RENOVATE_EXECUTION_TIMEOUT
        value: "90"
```
