### DISCUSSION TITLE
Renovate hosted app fails to lookup docker package from codeberg (gitea-based)

### DISCUSSION THREAD

**Discussion by pat-s** [renovatebot/renovate#25171] [Request Help]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

Placeholder value, please select the correct response from the dropdown

### Describe the problem

Local exec works fine and doesn't show lookup errors. However, the GH renovate app throws the errors below.

Judging from the `ERR_TLS_CERT_ALTNAME_INVALID` msg, this could also be a codeberg issue?

The package in question is https://codeberg.org/woodpecker-plugins/-/packages/container/trivy/latest and the repo renovate is running on is 

when executing locally via `RENOVATE_ONBOARDING=false LOG_LEVEL=debug GITHUB_COM_TOKEN=<token> renovate  --platform=local` it seems to work

```yml
               {
                 "depName": "codeberg.org/woodpecker-plugins/trivy",
                 "currentValue": "1.0.0",
                 "replaceString": "codeberg.org/woodpecker-plugins/trivy:1.0.0",
                 "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "updates": [],
                 "packageName": "codeberg.org/woodpecker-plugins/trivy",
                 "versioning": "docker",
                 "warnings": [],
                 "sourceUrl": "https://codeberg.org/woodpecker-plugins/trivy.git",
                 "registryUrl": "https://codeberg.org",
                 "currentVersion": "1.0.0",
                 "fixedVersion": "1.0.0"
               }
             ],
             "packageFile": ".woodpecker/securityscan.yml"
           },
```

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: GET https://codeberg.org/v2/token?scope=*&service=container_registry = (code=ERR_TLS_CERT_ALTNAME_INVALID, statusCode=-1 retryCount=0, duration=9084)
WARN: Error obtaining docker token
DEBUG: Failed to get authHeaders for getTags lookup
DEBUG: Failed to look up docker package codeberg.org/woodpecker-plugins/trivy
DEBUG: Failed to look up docker package codeberg.org/woodpecker-plugins/trivy
DEBUG: Failed to look up docker package codeberg.org/woodpecker-plugins/trivy
```

</details>

### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible
