### DISCUSSION TITLE
docker hostRules apply credentials for unspecified hosts

### DISCUSSION THREAD

**Discussion by MPritsch** [renovatebot/renovate#25247] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

37.24.0

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

I am trying to get this working for the first time

### Describe the problem

Hello, I have tried for several days to get renovate properly configured on our gitlab repositories. I have trouble with the hostRules specifically. We use a mix of a single private and a multiple public docker registries. This happens when we configure hostRules:
* No hostRule configured:
  ✅ Public registry lookup
  ❌ Private registry lookup
* hostRule with credentials to the private registry: 
  ❌ Public registry lookup
  ✅ Private registry lookup
* hostRule with credentials to the private registry + defining public registry with matchHost e.g. "gcr.io" and no credentials:
  ❌ Public registry lookup
  ✅ Private registry lookup

When I say the lookup does not work, I mean that the debug log says 401 Unauthorized. This seems to indicate, that renovate uses the credentials of the private registry to try to authenticate on the public registry. Explicitly defining a hostRule for which a matchHost e.g. "index.docker.io" or "https://index.docker.io" or "auth.docker.io" or "ghcr.io" etc. does not seem to do anything.
I also tried to configure the same hostRules on either the config.js or my own base.json with the same result.

It could be a bad configuration on my part, but at this point it feels like a bug. I'm not sure how you could replicate this on a public repo easily. Our gitlab is in a private subnet and communicates via webproxy to the public repos. For the internal registry it has a no_proxy rule.

### Relevant debug logs

<details><summary>Logs</summary>

Configuration for private registry:
```
module.exports = {
    ...
    "hostRules": [
        {
            "hostType": "docker",
            "matchHost": process.env.CI_REGISTRY,
            "username": process.env.GITLAB_USER_NAME,
            "password": process.env.RENOVATE_TOKEN
        }
    ]
    platform: "gitlab"
};
```

Configuration with public docker registries and no credentials:
```
module.exports = {
    ...
    "hostRules": [
        {
            "hostType": "docker",
            "matchHost": process.env.CI_REGISTRY,
            "username": process.env.GITLAB_USER_NAME,
            "password": process.env.RENOVATE_TOKEN
        },
        {
            "hostType": "docker",
            "matchHost": "gcr.io"
        },
        {
            "hostType": "docker",
            "matchHost": "https://gcr.io"
        }
    ]
    platform: "gitlab"
};
```

Then it logs these logs:
```
DEBUG: GET https://ghcr.io/token?scope=repository%3Aanchore%2Fsyft%3Apull&service=ghcr.io = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=403 retryCount=0, duration=350) (repository=my-project)
DEBUG: Not allowed to access docker registry (repository=my-project)
       "registryHost": "https://ghcr.io",
       "dockerRepository": "anchore/syft"
DEBUG: Response code 403 (Forbidden) (repository=my-project)
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1697526660182,
           "socket": 1697526660302,
           "lookup": 1697526660302,
           "connect": 1697526660302,
           "secureConnect": 1697526660360,
           "upload": 1697526660360,
           "response": 1697526660532,
           "end": 1697526660532,
           "phases": {
             "wait": 120,
             "dns": 0,
             "tcp": 0,
             "tls": 58,
             "request": 0,
             "firstByte": 172,
             "download": 0,
             "total": 350
           }
         },
         "message": "Response code 403 (Forbidden)",
         "stack": "HTTPError: Response code 403 (Forbidden)\n    at Request.<anonymous> (/opt/containerbase/tools/renovate/37.24.0/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/37.24.0 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "authorization": "***********",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://ghcr.io/token?scope=repository%3Aanchore%2Fsyft%3Apull&service=ghcr.io",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 403,
           "statusMessage": "Forbidden",
           "body": {"errors": [{"code": "DENIED", "message": "denied"}]},
           "headers": {
             "content-type": "application/json",
             "docker-distribution-api-version": "registry/2.0",
             "date": "Tue, 17 Oct 2023 07:11:00 GMT",
             "content-length": "50",
             "x-github-request-id": "34ED:119FF:4A704A:4C803C:652E3384",
             "connection": "close"
           },
           "httpVersion": "1.1",
           "retryCount": 0
         }
       }
DEBUG: Failed to get authHeaders for getTags lookup (repository=my-project)
DEBUG: Failed to look up docker package ghcr.io/anchore/syft (repository=my-project, packageFile=.gitlab-ci.yml, dependency=ghcr.io/anchore/syft)
```

With **no** hostRules or credentials for the private registry configured, our target repo logs these dependency lookup issues:
```
Failed to look up docker package <our-registry>/path/to/docker/repo/image-1
Failed to look up docker package <our-registry>/path/to/docker/repo/image-2
```

With hostRule and credentials for the private registry, our target repo logs these dependency lookup issues:
```
Failed to look up docker package node
Failed to look up docker package ghcr.io/anchore/syft
Failed to look up docker package cyclonedx/cyclonedx-cli
Failed to look up docker package ghcr.io/anchore/grype
Failed to look up docker package docker
```

</details>

### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible

**Comment by github-actions** [comment]
Hi there,

This issue or discussion is missing some logs, making it difficult or impossible to help you. Depending on which situation applies follow one, some or all of these instructions.

### No logs at all
If you haven't posted any log yet, we need you to find and copy/paste the log into the issue template.

#### Finding logs on hosted app
<details><summary>Select me to read instructions</summary>

If you use the Renovate app (GitHub):
1. Go to the affected PR, and search for "View repository job log here"
1. Select the link to go to the "Mend Renovate Dashboard" and log in
1. You are now in the correct repository log overview screen
1. Copy/paste the correct log
1. Follow the steps in the **formatting your logs** section
</details>

#### Finding logs when self-hosting
<details><summary>Select me to read instructions</summary>

If you're running self-hosted, run with `LOG_LEVEL=debug` in your environment variables and search for whatever dependency/branch/PR that is causing the problem.
</details>

### Insufficient logs
<details><summary>Select me to read instructions</summary>

If you already gave us a log, and the Renovate team said it's not enough, then follow the instructions from the **No logs at all** section.
</details>

### Formatting your logs
<details><summary>Select me to read instructions</summary>

Please put your logs in a `<details>` and `<summary>` element like this:


    <details><summary>Select me to see logs</summary>

    ```
    Copy/paste your logs here, between the starting and ending backticks
    ```

    </details>

</details>

Good luck,

The Renovate team

**Comment by rarkins** [comment]
Impossible to troubleshoot without detailed logs

**Reply by MPritsch** [reply]
Hello, thank you for the quick response. I pulled the logs from our gitlab job and replaced customer sensitive data. Hope this helps with the troubleshooting.

In the attached logs you can see our config.js configurations at the top. There are mvn repositories configured, which work for other projects. For clarity I performed the renovate scan on a single project, which does not use maven. The attached logs are from a job which only contain the private registry credentials and no configuration for the public registries. My expectation is that renovate should apply the credentials to the private registry and use no credentials on the public ones. As you should see by the logs, this is not the case.

The project itself has this onboarding config:
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:recommended",
    "local>path/to/renovate-runner:project-base"
  ]
}
```

The project-base.json contains this:
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "schedule:daily",
    ":rebaseStalePrs",
    ":semanticCommits"
  ],
  "platform": "gitlab",
  "separateMinorPatch": false,
  "dependencyDashboard": false,
  "docker": {
    "enabled": true
  },
  "vulnerabilityAlerts": {
    "enabled": true,
    "labels": [
      "vulnerability"
    ]
  },
  "labels": [
    "renovate"
  ],
  "gitlabci": {
    "fileMatch": [
      "\\.gitlab-ci\\.yml$"
    ]
  },
  "regexManagers": [
    {
      "fileMatch": [
        "(^|/)Dockerfile$",
        "(^|/)Dockerfile\\.[^/]*$"
      ],
      "matchStrings": [
        "#\\srenovate:\\sdatasource=(?<datasource>.*?) depName=(?<depName>.*?)( versioning=(?<versioning>.*?))?( extractVersion=(?<extractVersion>.*?))?\\s(ENV|ARG) .*?_VERSION=(?<currentValue>.*)\\s"
      ],
      "datasourceTemplate": "docker"
    }
  ]
}
```

The gitlab-ci.yml looks like this:
```yaml
variables:
  RENOVATE_BASE_DIR: $CI_PROJECT_DIR/renovate
  RENOVATE_ENDPOINT: $CI_API_V4_URL
  RENOVATE_PLATFORM: gitlab
  RENOVATE_OPTIMIZE_FOR_DISABLED: 'true'
  RENOVATE_REPOSITORY_CACHE: 'disabled'
  RENOVATE_REQUIRE_CONFIG: 'required'
  RENOVATE_IGNORE_PR_AUTHOR: 'true'
  RENOVATE_EXTENDS: 'github>whitesource/merge-confidence:beta'
  RENOVATE_LOG_FILE: renovate-log.ndjson
  RENOVATE_LOG_FILE_LEVEL: debug
  LOG_LEVEL: debug
  # the renovate image is the original renovate dockerhub image with a certificate for our private gitlab included
  CI_RENOVATE_IMAGE: private-gitlab-registry:5005/path/to/image/repo/renovate:37.24.0
  # all following vars are secret variables configured in ci settings
  RENOVATE_EXTRA_FLAGS: --autodiscover=true --onboarding=true --autodiscover-filter=path/to/target-project
  RENOVATE_TOKEN: group-level-access-token
  http_proxy: proxy-config
  https_proxy: proxy-config
  no_proxy: no-proxy-config

.renovate:
  cache:
    key: ${CI_COMMIT_REF_SLUG}-renovate
    paths:
      - renovate/cache/renovate/repository/
  image: ${CI_RENOVATE_IMAGE}
  script:
    - renovate $RENOVATE_EXTRA_FLAGS

renovate:
  extends: .renovate
  stage: deploy
  resource_group: production
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  artifacts:
    when: always
    expire_in: 1d
    paths:
      - '$RENOVATE_LOG_FILE'

```

[renovate-private-registry-credentials.log](https://github.com/renovatebot/renovate/files/12927851/renovate-private-registry-credentials.log)
