### DISCUSSION TITLE
How to only update patch versions and group PRs?

### DISCUSSION THREAD

**Discussion by pmalek** [renovatebot/renovate#25248] [Request Help]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

Instead of

```
kindest/node v1.28.0
kindest/node v1.27.3→ [Updates: v1.28.0]
kindest/node v1.26.6→ [Updates: v1.28.0]
kindest/node v1.25.11→ [Updates: v1.28.0]
kindest/node v1.24.15→ [Updates: v1.28.0]
kindest/node v1.23.17→ [Updates: v1.28.0]
```

I want

```
kindest/node v1.27.3→ [Updates: v1.27.4]
kindest/node v1.26.6→ [Updates: v1.26.7]
kindest/node v1.25.11→ [Updates: v1.25.12]
```

grouped into 1 PR.

### What you tried so far.

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "configMigration": true,
  "enabledManagers": ["regex"],
  "automerge": false,
  "separateMinorPatch": true,
  "labels": ["dependencies"],
  "customManagers": [
    {
      "customType": "regex",
      "fileMatch": [
        "^.github/test_dependencies.yaml$"
      ],
      "matchStrings": [
        "#\\s+renovate:\\s+datasource=(?<datasource>.*)\\s+depName=(?<depName>.*)\\s+versioning=(?<versioning>.*)\\n.+'(?<currentValue>.*)'"
      ]
    }
  ],
  "packageRules": [
    {
      "matchPackagePatterns": ["istio/istioctl"],
      "groupName": "istio",
      "matchUpdateTypes": [
        "patch"
      ]
    },
    {
      "matchPackagePatterns": ["kindest/node"],
      "groupName": "node",
      "matchUpdateTypes": [
        "patch"
      ]
    }
  ]
}
```

```
e2e:
  kind:
    # renovate: datasource=docker depName=kindest/node versioning=docker
    - 'v1.28.0'
    # renovate: datasource=docker depName=kindest/node versioning=docker
    - 'v1.27.3'
    # renovate: datasource=docker depName=kindest/node versioning=docker
    - 'v1.26.6'
    # renovate: datasource=docker depName=kindest/node versioning=docker
    - 'v1.25.11'
    # renovate: datasource=docker depName=kindest/node versioning=docker
    - 'v1.24.15'
    # renovate: datasource=docker depName=kindest/node versioning=docker
    - 'v1.23.17'
  gke:
    # renovate: datasource=custom.gke-rapid depName=gke versioning=semver
    - '1.26.9'

  # For Istio, we define combinations of Kind and Istio versions that will be
  # used directly in the test matrix `include` section.
  istio:
    - # renovate: datasource=docker depName=kindest/node versioning=docker
      kind: 'v1.28.0'
      # renovate: datasource=docker depName=istio/istioctl versioning=docker
      istio: '1.19.3'
    - # renovate: datasource=docker depName=kindest/node versioning=docker
      kind: 'v1.27.3'
      # renovate: datasource=docker depName=istio/istioctl versioning=docker
      istio: '1.18.5'
    - # renovate: datasource=docker depName=kindest/node versioning=docker
      kind: 'v1.26.6'
      # renovate: datasource=docker depName=istio/istioctl versioning=docker
      istio: '1.17.8'
    - # renovate: datasource=docker depName=kindest/node versioning=docker
      kind: 'v1.25.11'
      # renovate: datasource=docker depName=istio/istioctl versioning=docker
      istio: '1.16.7'
```

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>
