### DISCUSSION TITLE
You must configure a GitLab personal access token

### DISCUSSION THREAD

**Discussion by lmilbaum** [renovatebot/renovate#25725] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the problem

I can't share the log file but I did notice that the token value is empty. 

.gitlab-ci.yml

```
---
default:
  tags:
    - docker

stages:
  - deploy
  - ci

include:
  - remote: https://gitlab.com/renovate-bot/renovate-runner/-/raw/v16.45.4/templates/renovate.gitlab-ci.yml 

variables:
  RENOVATE_VERSION: "37.46.0@sha256:fa0610709d962e9f905dd1a8c64a34ade2fb875385d7c19812bd3b19a2d4115a" 
  CI_RENOVATE_IMAGE: "${CONTAINER_REGISTRY}/${REGISTRY_NAMESPACE}/${REPONAME}:${RENOVATE_VERSION}" 

renovate:
  rules:
    - when: never

renovate-gitlab:
  extends: renovate
  variables:
    RENOVATE_CONFIG_FILE: config.js
    RENOVATE_PLATFORM: "gitlab"
    RENOVATE_ENDPOINT: "https://gitlab.cee.redhat.com/api/v4/"
    RENOVATE_TOKEN: $GITLAB_TOKEN
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
```

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

Placeholder value, please select the correct response from the dropdown
