### DISCUSSION TITLE
Possibility to scan ArgoCD application generated with helm

### DISCUSSION THREAD

**Discussion by MikeDevresse** [renovatebot/renovate#25895] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

37.64.2

### If you're self-hosting Renovate, select which platform you are using.

Azure DevOps (dev.azure.com)

### What is your question?

Hi,
I have a multi cluster infrastructure and I deploy everything using argocd. I also have components that are commons between clusters, and in order to deploy them I created a helm chart that create ArgoCD application. but unfortunately, renovate don't see them as ArgoCD application file. Is there any way to make this work ? Like generate the template maybe ? 
If you need further informations I can provide what you want.
Thank you !

**Comment by rarkins** [comment]
I don't understand what you're describing, but you can nearly always fall back to defining your own custom/regex manager

**Reply by MikeDevresse** [reply]
Sorry if it is unclear. 

I have a argocd application which deploys a helm chart that is hosted in the same repository, and this helm chart deploys argocd application like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.aws.clusterName }}-external-dns
  namespace: argocd
spec:
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  destination:
    name: {{ .Values.argocd.destinationClusterName }}
    namespace: external-dns
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.13.1
    helm:
      releaseName: external-dns
      values: |
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.aws.accountId }}:role/{{ .Values.aws.zone }}-ExternalDNSPolicy"
        provider : aws
        policy: sync
        registry: txt
        txtOwnerId: {{ .Values.aws.clusterName }}
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
          limits:
            memory: 40Mi
```

The issue is that this file is not detected as an ArgoCD application. I also have more complex template than this one that I would like to scan. Is there a way to tell renovate for every yaml file, check that spec.source.targetRevision is the latest of spec.source.repoUrl ? And also I have ArgoCD applications that has multiples sources, is this supported ?  

Edit: I think the issue is that because this is a helm template, it is not detected as a valid yaml file
