### DISCUSSION TITLE
How to escape slash in host rules env vars?

### DISCUSSION THREAD

**Discussion by Kampfmoehre** [renovatebot/renovate#25929] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

37.65.1

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### What is your question?

We are using GitLab CI Pipeline extending the config from https://gitlab.com/renovate-bot/renovate-runner. We host our own NuGet packages in GitLab and had setup up the config with hostRules like this
```js
[
  {
    hostType: "nuget",
    matchHost: "gitlab.example.com",
    username: "<some-user>",
    password: process.env.GITLAB_TOKEN,
  }
]
```
and then overwrite the password with in the CI config with
```yaml
variables:
  NUGET_GITLAB_EXAMPLE_COM_PASSWORD: ${GITLAB_PACKAGE_REGISTRY_PASSWORD}
```

This worked in the past, however we now have a NuGet package hosted in a different Group in GitLab. [The docs](https://docs.renovatebot.com/getting-started/private-packages/#dependency-version-lookups) state that match host should now be written as a full path which we did:
```js
[
  {
    hostType: "nuget",
    matchHost: "https://gitlab.example.com/api/v4/groups/1",
    username: "<first_user>",
    password: process.env.GITLAB_TOKEN,
  },
  {
    hostType: "nuget",
    matchHost: "https://gitlab.example.com/api/v4/groups/2",
    username: "<second_user>",
    password: process.env.GITLAB_TOKEN,
  }
]
```

But how do we set the password via Env Variable now? [The docs](https://docs.renovatebot.com/self-hosted-configuration/#detecthostrulesfromenv) only state how to replace dots and hyphens but not slashes.
First impulse was to try
```yaml
variables:
  NUGET_GITLAB_EXAMPLE_COM/API/V4/GROUPS/1_PASSWORD: ${GITLAB_PACKAGE_REGISTRY_PASSWORD}
```
but slashes are not allowed in ENV variable names. We also tried

```yaml
variables:
  NUGET_GITLAB_EXAMPLE_COM_API_V4_GROUPS_1_PASSWORD: ${GITLAB_PACKAGE_REGISTRY_PASSWORD}
```
but that does also not work - presumely Renovate replaces all slashes with dots. So how should we escape the full path?

PS: Bonus question: As you can see we tried to set the password directly via `process.env.GITLAB_TOKEN` but that also does not work, is there a way to make this work?

### Logs (if relevant)

-

**Comment by rarkins** [comment]
I recommend you use RENOVATE_HOST_RULES with stringified values instead

**Reply by Kampfmoehre** [reply]
So I would put the whole host Rules array in a single variable?

**Comment by viceice** [comment]
it should be possible to use `process.env` instead `config.js`. 

so please describe your setup in more detail. how are you running renovate?

**Reply by Kampfmoehre** [reply]
Renovate runs as a scheduled CI in a sepearate repo in GitLab. The repo contains the `config.js` file and a `.gitlab-ci.yml`which uses the Renovate template
```yaml
include:
  - remote: https://gitlab.com/renovate-bot/renovate-runner/-/raw/v16.51.1/templates/renovate.gitlab-ci.yml

stages:
  - test
  - deploy

image: ${CI_RENOVATE_IMAGE}

variables:
  RENOVATE_TOKEN: ${GITLAB_TOKEN} # So we can reuse GITLAB_TOKEN from GitLab group
  RENOVATE_DETECT_HOST_RULES_FROM_ENV: "true" # Allows to specify host rules via env
  DOCKER_REGISTRY_EXAMPLE_COM_PASSWORD: ${GITLAB_TOKEN} # Credential for GitLab container registry
  NPM_GITLAB_EXAMPLE_COM_TOKEN: ${GITLAB_TOKEN} # Credential for GitLab NPM registry
  GITLAB__TAGS_GITLAB_EXAMPLE_COM_TOKEN: ${GITLAB_TOKEN} # Credential for Changelog fetching via GitLab tags
#  NUGET_GITLAB_EXAMPLE_COM_PASSWORD: ${GITLAB_PACKAGE_REGISTRY_PASSWORD} # Credential for GitLab NuGet registry
  RENOVATE_CUSTOM_ENV_VARIABLES: "{\"GITLAB_TOKEN\": \"${GITLAB_TOKEN}\"}"

validate-config:
  tags:
    - docker
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_RENOVATE_IMAGE
      when: always
  variables:
    GITLAB_TOKEN: test # needed or validator will complain about process.env.GITLAB_TOKEN in MR pipelines
  script:
    - renovate-config-validator

renovate:
  tags:
    - docker
  rules:
  - if: $CI_PIPELINE_SOURCE == "schedule"
  - if: $CI_PIPELINE_SOURCE == "web"
  artifacts:
    expire_in: 1 day
    paths:
      - renovate-log.ndjson

```
