### DISCUSSION TITLE
Renovate is not detecting host rules from env

### DISCUSSION THREAD

**Discussion by davidusken** [renovatebot/renovate#25942] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

37.64.3

### If you're self-hosting Renovate, select which platform you are using.

Bitbucket Server

### What is your question?

We deploy Renovate through the Helm chart and it is working very well so far. However, one issue we cannot resolve is that when we are trying to add our private container registry (Harbor) it seems Renovate is not detecting this and keeps warning that it failed to lookup docker package xxx

Our values.yaml
(Ignore extra indentations)
```
renovate:
  global:  
  cronjob:
    # -- Schedules the job to run using cron notation
    schedule: '0 * * * *'  # Every hour
  renovate:
    config: 
        '
        {
          "platform": "bitbucket-server",
          "endpoint": "https://X.X/bitbucket",
          "autodiscover": false,
          "repositories": ["infra/XXX", "infra/XXX", "infra/XXX"]
        }
        '

  # -- k8s secret to reference environment variables from. Overrides secrets if set
  existingSecret: renovate-secret
  
  env:
    env: 
      RENOVATE_DETECT_HOST_RULES_FROM_ENV: True
```
And our secret looks like this:
```
apiVersion: v1
kind: Secret
metadata:
  name: renovate-secret
  namespace: renovate
type: Opaque
stringData:
  RENOVATE_USERNAME: XXX
  RENOVATE_PASSWORD: XXX
  GITHUB_COM_TOKEN: XXX
  DOCKER_QUAY_XXX_X_USERNAME: XXX
  DOCKER_QUAY_XXX_X_PASSWORD: XXX
```
From what I understand in the docs this should be all that is required for Renovate to authenticate to the private registry. Verified that the env variable is actually set to true on the pod itself.

### Logs (if relevant)

<details><summary>Logs</summary>

```

 WARN: Package lookup failures (repository=infra/xxx, branch=renovate/quay.io-keycloak-keycloak-23.x)
       "warnings": [
         "Failed to look up docker package quay.xxx.x/prod/optools/statusagent",
         "Failed to look up docker package quay.xxx.x/tools/crates"
       ],
```

</details>
