### DISCUSSION TITLE
helmfile: YAML document separators break dependency resolution

### DISCUSSION THREAD

**Discussion by pathob** [renovatebot/renovate#26077] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

37.79.0

### If you're self-hosting Renovate, select which platform you are using.

Azure DevOps (dev.azure.com)

### Was this something which used to work for you, and then stopped?

I have not seen this working

### Describe the problem

The Renovate dependency resolution breaks when a Helmfile contains a document separator between the repositories and the releases blocks. Using a document separator can be necessary when working with environments, as the following example Helmfile output shows:

```
$ helmfile -e qa template
Warning: environments and releases cannot be defined within the same YAML part. Use --- to extract the environments into a dedicated part
Warning: environments and releases cannot be defined within the same YAML part. Use --- to extract the environments into a dedicated part
...
```

Since these blocks are lists, they can not be extended in later documents. so e.g. a repositories list defined in the first document would completely be overridden by a repositories list in a later document (that's normal YAML behaviour). The Renovate manager should be adjusted to mimic this behaviour and properly support multi-document Helmfiles.

The following [simple example from the Helmfile documentation](https://helmfile.readthedocs.io/en/stable/#getting-started) can be used for reproducing the issue.

Working:

```yaml
repositories:
 - name: prometheus-community
   url: https://prometheus-community.github.io/helm-charts

releases:
- name: prom-norbac-ubuntu
  namespace: prometheus
  chart: prometheus-community/prometheus
  ## Add a version to the example
  version: 25.7.0
  set:
  - name: rbac.create
    value: false
```

Not working:

```yaml
repositories:
 - name: prometheus-community
   url: https://prometheus-community.github.io/helm-charts

environments:
  qa:
  staging:
  prod:

## document separator to satisfy Helmfile:
---

releases:
- name: prom-norbac-ubuntu
  namespace: prometheus
  chart: prometheus-community/prometheus
  ## Add a version to the example
  version: 25.7.0
  set:
  - name: rbac.create
    value: false
```

### Relevant debug logs

<details><summary>Logs</summary>

DEBUG: Found helmfile package files (repository=test/service)
DEBUG: Found 1 package file(s) (repository=test/service)
INFO: Dependency extraction complete (repository=test/service, baseBranch=main)

       "stats": {
         "managers": {"helmfile": {"fileCount": 1, "depCount": 1}},
         "total": {"fileCount": 1, "depCount": 1}
       }

DEBUG: PackageFiles.add() - Package file saved for base branch (repository=test/service, baseBranch=main)
DEBUG: Package releases lookups complete (repository=test/service, baseBranch=main)

...

DEBUG: packageFiles with updates (repository=test/service, baseBranch=main)

       "config": {
         "helmfile": [
           {
             "deps": [
               {
                 "depName": "prometheus",
                 "currentValue": "25.7.0",
                 "registryUrls": [],
                 "skipReason": "unknown-registry",
                 "updates": [],
                 "packageName": "prometheus"
               }
             ],
             "datasource": "helm",
             "packageFile": "helmfile.yaml.gotmpl"
           }
         ]
       }

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above
