### DISCUSSION TITLE
Enabling Renovate OpenTelemetry doesn't send traces to collector

### DISCUSSION THREAD

**Discussion by chandapukiran** [renovatebot/renovate#26105] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, select which platform you are using.

gitlab.com

### What is your question?

Hi, 

I am testing opentelemetry and renovate by following https://docs.renovatebot.com/opentelemetry/ . 
I have set OTEL_EXPORTER_OTLP_ENDPOINT environment and used docker-compose in an ec2 instance with ports opened "16686 and 4138" but i don't see any traces as explained in the above link when I access Jaeger UI, infact I don't see renovate service. 

I have then tried to run both open telemetry stack and renovate on same ubuntu machine but renovate fails with following. 

```
ERROR: unhandledRejection
       "err": {
         "errno": -111,
         "code": "ECONNREFUSED",
         "syscall": "connect",
         "address": "127.0.0.1",
         "port": 4318,
         "message": "connect ECONNREFUSED 127.0.0.1:4318",
         "stack": "Error: connect ECONNREFUSED 127.0.0.1:4318\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:128:17)"
```

I see the ports are open

```
ubuntu@ip-172-31-20-63:~$ netstat -tulpn
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:13133           0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:55679           0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:1888            0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:16686           0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:9123            0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:32768           0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:4317            0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:4318            0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::13133                :::*                    LISTEN      -                   
tcp6       0      0 :::55679                :::*                    LISTEN      -                   
tcp6       0      0 :::1888                 :::*                    LISTEN      -                   
tcp6       0      0 :::16686                :::*                    LISTEN      -                   
tcp6       0      0 :::9123                 :::*                    LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
tcp6       0      0 :::32768                :::*                    LISTEN      -                   
tcp6       0      0 :::4317                 :::*                    LISTEN      -                   
tcp6       0      0 :::4318                 :::*                    LISTEN      -                   
udp        0      0 127.0.0.1:323           0.0.0.0:*                           -                   
udp        0      0 127.0.0.53:53           0.0.0.0:*                           -                   
udp        0      0 172.31.20.63:68         0.0.0.0:*                           -                   
udp6       0      0 ::1:323                 :::*                                -  
```

### Logs (if relevant)

<details><summary>Logs</summary>

```

Copy/paste the relevant log(s) here, between the starting and ending backticks

```

</details>

**Comment by secustor** [comment]
What is your docker compose setup? Do you run Renovate in a container?

**Reply by chandapukiran** [reply]
```
cat docker-compose.yaml 
version: '3'
services:
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
      - '16686:16686'
      - '4317'

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.88.0
    command: ['--config=/etc/otel-collector-config.yml']
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - '1888:1888' # pprof extension
      - '13133:13133' # health_check extension
      - '55679:55679' # zpages extension
      - '4318:4318' # OTLP HTTP
      - '4317:4317' # OTLP GRPC
      - '9123:9123' # Prometheus exporter
    depends_on:
      - jaeger
```
```
cat otel-collector-config.yml 
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  logging:
  prometheus:
    endpoint: '0.0.0.0:9123'

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus
    latency_histogram_buckets: [10ms, 100ms, 250ms, 1s, 30s, 1m, 5m]
    dimensions:
      - name: http.method
      - name: http.status_code
      - name: http.host
    dimensions_cache_size: 1000
    aggregation_temporality: 'AGGREGATION_TEMPORALITY_CUMULATIVE'

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger, logging]
      processors: [spanmetrics, batch]

    metrics:
      receivers: [otlp]
      exporters: [prometheus]
```

I run renovate self-hosted in github.com , which is not working ; so tried to test it first locally by running renovate as container with this command 

```
docker run   --rm   -e OTEL_EXPORTER_OTLP_ENDPOINT=http://127.0.0.1:4318   -v "/home/ubuntu/config.js:/usr/src/app/config.js"   renovate/renovate:latest
```

**Reply by secustor** [reply, marked as answer]
127.0.0.1/localhost in a container is not referring to the host, but rather to the container in which Renovate is running currently. 

The easiest way here would be to add Renovate to the docker compose file and using `OTEL_EXPORTER_OTLP_ENDPOINT= http://<name of the renovate container>:4318`

**Reply by chandapukiran** [reply]
I have tried to include renovate in docker-compose and now i don't see connection refused error but below. 

```
renovate_1        | ERROR: unhandledRejection
renovate_1        |        "err": {
renovate_1        |          "name": "OTLPExporterError",
renovate_1        |          "data": "{\"code\":3,\"message\":\"ReadString: expects \\\" or n, but found {, error found in #10 byte of ...|message\\\":{}},\\\"links\\\"|..., bigger context ...|oppedEventsCount\\\":0,\\\"status\\\":{\\\"code\\\":2,\\\"message\\\":{}},\\\"links\\\":[],\\\"droppedLinksCount\\\":0},{\\\"traceId\\\":\\\"1|...\"}",
renovate_1        |          "code": 400,
renovate_1        |          "message": "Bad Request",
renovate_1        |          "stack": "OTLPExporterError: Bad Request\n    at IncomingMessage.<anonymous> (/opt/containerbase/tools/renovate/37.83.0/node_modules/@opentelemetry/otlp-exporter-base/src/platform/node/util.ts:131:27)\n    at /opt/containerbase/tools/renovate/37.83.0/node_modules/@opentelemetry/context-async-hooks/src/AbstractAsyncHooksContextManager.ts:75:49\n    at AsyncLocalStorage.run (node:async_hooks:327:14)\n    at AsyncLocalStorageContextManager.with (/opt/containerbase/tools/renovate/37.83.0/node_modules/@opentelemetry/context-async-hooks/src/AsyncLocalStorageContextManager.ts:40:36)\n    at IncomingMessage.contextWrapper (/opt/containerbase/tools/renovate/37.83.0/node_modules/@opentelemetry/context-async-hooks/src/AbstractAsyncHooksContextManager.ts:75:26)\n    at IncomingMessage.emit (node:events:529:35)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1400:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)"
```
here is my docker-compose file 

```
version: '3'
services:
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
      - '16686:16686'
      - '4317'

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.88.0
    command: ['--config=/etc/otel-collector-config.yml']
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - '1888:1888' # pprof extension
      - '13133:13133' # health_check extension
      - '55679:55679' # zpages extension
      - '4318:4318' # OTLP HTTP
      - '4317:4317' # OTLP GRPC
      - '9123:9123' # Prometheus exporter
    depends_on:
      - jaeger

  renovate:
    image: renovate/renovate:latest
    volumes:
      - /home/ubuntu/config.js:/usr/src/app/config.js
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    depends_on:
      - otel-collector
```
