### DISCUSSION TITLE
Support for dart git packages

### DISCUSSION THREAD

**Discussion by RobinIrmer** [renovatebot/renovate#26319] [Suggest an Idea]
### Tell us more.

Hello,

we're currently unable to use renovate for dart git packages (go, terraform and bazel are working great!) - is there any chance this feature request could be added to renovate? 

```
xxx:
    git:
      url: git@github.com:org/xxx.git
      ref: v2.10.12
      path: pkg/dart
```

ref: https://dart.dev/tools/pub/dependencies#git-packages

**Comment by github-actions** [comment]
Hi there,

Get your discussion fixed faster by creating a minimal reproduction. This means a repository dedicated to reproducing this issue with the minimal dependencies and config possible.

Before we start working on your issue we need to know exactly what's causing the current behavior. A minimal reproduction helps us with this.

To get started, please read our guide on creating a [minimal reproduction](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md).

We may close the discussion if you, or someone else, haven't created a minimal reproduction within two weeks. If you need more time, or are stuck, please ask for help or more time in a comment.

Good luck,

The Renovate team

**Comment by Conrad598** [comment]
Maybe this is more feasible now that [Dart 3.9.0](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#390) added support for a 'tag_pattern' field in the `pubspec.yaml`?

```yaml
dependencies:
  my_dependency:
    git:
      url: https://github.com/example/my_dependency
      tag_pattern: v{{version}}
    version: ^2.0.1
```
The 'version' field must be a semantic version, unlike `ref` which can be anything Git allows to identify a commit.
