### DISCUSSION TITLE
Remove v prefix from version with custom manager

### DISCUSSION THREAD

**Discussion by bobvandevijver** [renovatebot/renovate#26325] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

37.99.1

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### What is your question?

Considering the following Gitlab CI file:

```yaml
variables:
  # renovate: datasource=github-releases depName=fabpot/local-php-security-checker versioning=semver-coerced
  PHP_SEC_CHECK_VERSION: 2.0.3
```

And the following custom manager:
```json
{
            "customType": "regex",
            "fileMatch": ["^\\.gitlab-ci\\.yml$"],
            "matchStrings": [
                "#\\s?renovate: datasource=(?<datasource>.*?) depName=(?<depName>.*?)( versioning=(?<versioning>.*?))?\\s.*?_VERSION: (?<currentValue>.*)\\s"
            ],
            "versioningTemplate": "{{#if versioning}}{{{versioning}}}{{else}}semver{{/if}}"
        }
```

I'm getting the following change:

```git
   # renovate: datasource=github-releases depName=fabpot/local-php-security-checker
-  PHP_SEC_CHECK_VERSION: 2.0.3
+  PHP_SEC_CHECK_VERSION: v2.0.6
```

This is somewhat logical, as the `v` prefix is also in the Github release, but how would I remove this prefix?

I already tried `versioning=semver-coerced`, but that did not seem to make a change at all.
