### DISCUSSION TITLE
Renovate skips HelmReleases without Namespace with skipReason unknown-registry

### DISCUSSION THREAD

**Discussion by jan-kantert** [renovatebot/renovate#26381] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

37.105.0

### If you're self-hosting Renovate, select which platform you are using.

Bitbucket Server

### Was this something which used to work for you, and then stopped?

I have not seen this working

### Describe the problem

When not specifying `namespace` in a HelmRepository + HelmRelease renovate will skip updates. This is common in kustomizations (i.e. in flux/argoCD).

This configuration will reproduce the issue:

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: my-service
spec:
  interval: 5m
  url: https://my.registry/yyy/my-service/master
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-service
spec:
  releaseName: my-service
  interval: 1m
  chart:
    spec:
      chart: my-service
      version: 0.0.42
      sourceRef:
        name: my-service
        kind: HelmRepository
```

If you add any namespace to both objects it will start working.

### Relevant debug logs

<details><summary>Logs</summary>

```

{\"deps\":[{\"currentValue\":\"0.0.42\",\"datasource\":\"helm\",\"depName\":\"my-service\",\"packageName\":\"my-service\",\"skipReason\":\"unknown-registry\",\"updates\":[]}],\"packageFile\":\"my-service/base/release.yaml\"}

```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above
