### DISCUSSION TITLE
Add support for embedded Helmfiles inside a Helmfile

### DISCUSSION THREAD

**Discussion by nikita2206** [renovatebot/renovate#26446] [Suggest an Idea]
### Tell us more.

**Feature description**

Example of our Helmfile:
```
# helmfile.yaml
repositories:
  - name: acme-charts
    url: https://acme.com/repository/helm/

helmfiles:
  - '*.releases.yaml'
```
followed up by the releases files:
```
# acme-site1.releases.yaml
releases:
  - name: acme-site1-foo
    version: ...
    ...

  - name: acme-site1-bar
    ...
```

It would be nice if Renovate could detect those included files, and update the chart versions inside those files as well.

**Our current workaround**

We copy the `repositories: ...` section to every `*.releases.yaml` file at the top, and then instruct Renovate to look into those files as well by specifying the following configuration:

```json
  "helmfile": {
    "fileMatch": [
      "(^|/)helmfile\\.ya?ml(?:\\.gotmpl)?$",
      "(^|/).+\\.releases\\.ya?ml$"
    ]
  }
```
