### DISCUSSION TITLE
Handle Encrypted creds using regex CustomManager

### DISCUSSION THREAD

**Discussion by nsalfos** [renovatebot/renovate#26520] [Request Help] [answered]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### What is your question?

Saw this [discussion](https://github.com/renovatebot/renovate/discussions/25895) which i think is related to my issue. 
i have a similar ArgoCD file that uses a helm-cart, but difference is, that the chart i have in the manifest is a custom made chart, located in a private Artifactory registry. 
So, adding to what was posted in that discussion, i thought i would just add the `encrypted`  block (with user and token) but got an error saying _"Message: Custom Manager contains disallowed fields: encrypted"._ 

So, i have a 2 part question: 

1. is this the only way to handle helm-charts for ArgoCD apps, so that when a new version of the chart is pushed to AF i get the ArgoCD app updated?

2. Is there a way to handle/pass the encrypted creds so Renovate can auth to the private registry?  

If there is a totally different approach i'd love the advise, i've been struggling for a couple of days trying to make this work.
also, let me know if you need more info o anything. 

Here's the snippet i'm using for that.

```
"customManagers": [
  {
      "customType": "regex",
      "fileMatch": ["\\.ya?ml$"],
      "matchStringsStrategy": "combination",
      "matchStrings": [
          "[\\s-]*targetRevision:\\s+\"?(?<currentValue>[^\"\\s]+)\"?\\s*",
          "[\\s-]*chart:\\s+\"?(?<depName>[^\"\\s]+)\"?\\s*",
          "[\\s-]*repoURL:\\s+\"?(?<registryUrl>[^\"\\s]+)\"?\\s*",
      ],
      "datasourceTemplate": "helm",
      "encrypted": {
        "username": "<ENCRYPTED-USER>",
        "token": "<ENCRYPTED-TOKEN>"
      }
    }
  ],
```

### Logs (if relevant)

<details><summary>Logs</summary>

```

Copy/paste the relevant log(s) here, between the starting and ending backticks

```

</details>

**Comment by rarkins** [comment, marked as answer]
Username and token don't belong there. Try hostRules instead, but you need either only token or username+password

**Reply by nsalfos** [reply]
Thanks for the quick reply!!! 
what do you mean by "try hostRules" instead, 
using hostRules is actually my current config, (before regex) and that is not picking the new chart versions...
i did swap token for password, but still no luck.

This is my renovate.json now:

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "additionalBranchPrefix": "{{{parentDir}}}-",
  "commitMessagePrefix": "[RENOVATE]",
  "commitMessageSuffix": "({{baseDir}})",
  "bumpVersion": "patch",
  "assigneesFromCodeOwners": true,
  "reviewersFromCodeOwners": true,
  "packageRules": [
    {
      "matchPackagePatterns": [
        "*"
      ],
      "matchUpdateTypes": [
        "minor",
        "patch"
      ],
      "groupName": "all non-major dependencies",
      "groupSlug": "all-minor-patch"
    }
  ],
  "hostRules": [
    {
      "matchHost": "<private>.jfrog.io/artifactory/helm/",
      "hostType": "helm",
      "encrypted": {
        "username": "<USER>",
        "password": "<PASSWORD>"
      }
    }
  ],
  "includePaths": [
    "gitops/**"
  ]
}
```

But from what i got from the other discussion, this config wont pick up on the new `targetRevision`


this is a simplified sample file which has `targetRevision: 0.3.2` and currently in our AF we have v.0.3.7

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <custom-chart>
  namespace: <namespace>
spec:
  project: <project>
  source:
    chart: <custom-chart>
    helm:
      values: {}
    repoURL: 'https://<private>.jfrog.io/artifactory/helm'
    targetRevision: 0.3.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    name: <cluster>
    namespace: <custom-chart>
```
