### DISCUSSION TITLE
Using depName in custom datasource transformTemplates

### DISCUSSION THREAD

**Discussion by fuero** [renovatebot/renovate#26577] [Request Help] [answered]
### How are you running Renovate?

Self-Hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

37.98.1

### If you're self-hosting Renovate, select which platform you are using.

Github

### What is your question?

I'm trying to use a yaml file as a custom datasource. It looks like this (excerpt):

```yaml
# relatedImages are used when an image is omitted from PostgresCluster, PGAdmin or PGUpgrade specs.
relatedImages:
  postgres_16:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-16.1-0
  pgadmin:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4:ubi8-4.30-19
```

I want to use this datasource for various packages (the keys in relatedImages).
It doesn't work though, I can't use {{depName}} in transformTemplates. From reading the docs, I'd have expected this to work.

renovate.json:

```json
{
  "extends": [
    "config:best-practices"
  ],
  "packageRules": [
    {
      "matchDatasources": [ "custom.pgimages" ],
      "versionCompatibility": "^(?<compatibility>ubi\\d+-)(?<version>.*)$"
    }
  ],
  "regexManagers": [
    {
      "fileMatch": [".*-sync[.]ya?ml$"],
      "matchStrings": [
        "\\s+#\\s+renovate:\\s+datasource=(?<datasource>\\S+)\\s+depName=(?<depName>\\S+)(?:\\s+registryUrl=(?<registryUrl>\\S+))?(?:\\s+versioning=(?<versioning>.*))?\\s+-\\s+(?<currentValue>\\S+)"
      ],
      "versioningTemplate": "{{#if versioning}}{{{versioning}}}{{else}}loose{{/if}}"
    }
  ],
  "customDatasources": {
    "pgimages": {
      "defaultRegistryUrlTemplate": "https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/helm/install/values.yaml",
      "format": "yaml",
      "transformTemplates": [
        "{\"releases\":[{\"version\":$substringAfter($.relatedImages.{{depName}}.image,\":\")}]}"
      ]
    },
    "pgo": {
      "defaultRegistryUrlTemplate": "https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/helm/install/Chart.yaml",
      "format": "yaml",
      "transformTemplates": [
        "{\"releases\":[{\"version\":$.version}]}"
      ]
    }
  },
  "dockerfile": {
    "enabled": false
  },
  "nuget": {
    "enabled": false
  },
  "terraform": {
    "enabled": false
  }
}
```

crunchy-sync.yaml (excerpt):
```yaml
registry.developers.crunchydata.com/crunchydata:
  images:
    crunchy-pgadmin4:
      # renovate: datasource=custom.pgimages depName=pgadmin
      - ubi8-4.30-18
```

For the pgadmin dependency, this yields:

```
             "deps": [
               {
                 "depName": "pgadmin",
                 "currentValue": "ubi8-4.30-18",
                 "datasource": "custom.pgimages",
                 "versioning": "regex:^ubi\\d+-(?<major>\\d+)[.](?<minor>\\d+)(?:[.](?<patch>\\d+))?(?:-\\d+[.]\\d+)?-(?<compatibility>\\d+)$",
                 "replaceString": "\n      # renovate: datasource=custom.pgimages depName=pgadmin\n      - ubi8-4.30-18",
                 "updates": [],
                 "packageName": "pgadmin",
                 "warnings": [
                   {
                     "topic": "pgadmin",
                     "message": "Failed to look up custom.pgimages package pgadmin"
                   }
                 ]
               },
```

Using e.g. pgadmin instead of {{depName}} works as expected.

### Logs (if relevant)

<details><summary>Logs</summary>

```

Copy/paste the relevant log(s) here, between the starting and ending backticks

```

</details>

**Comment by rarkins** [comment, marked as answer]
Datasources have no concept of depName - there is only the package name

**Reply by fuero** [reply]
Excellent, thank you!

**Comment by lmilbaum** [comment]
@fuero How are you working out the right configuration? I'm struggling with html custom data source. Can't figure out the right syntax.

**Reply by fuero** [reply]
Write a question post and include your config and the HTML Resource, it's hard to help you without data.

**Reply by lmilbaum** [reply]
#26570

**Comment by victorthaulow** [comment]
Hi! Just if anyone hits the same situation as me -

I wanted to do a multiple renovate setup for different images in my Kubernetes cluster. Specifically, I encountered an issue with the `postgres-exporter` image not being updated due to a mismatch in the versioning regex pattern and also generally just setting it up.

I got this working config I wanted to share:

```json
{
  "extends": ["config:best-practices"],
  "branchConcurrentLimit": 20,
  "prConcurrentLimit": 20,
  "packageRules": [
    {
      "matchDatasources": [
        "helm",
        "docker",
        "kustomize",
        "yaml",
        "custom.pgimages",
        "custom.pgbouncerimages",
        "custom.pgbackrestimages",
        "custom.pgadminimages",
        "custom.pgexporterimages"
      ],
      "groupName": "all-updates"
    },
    {
      "matchDatasources": ["custom.pgimages"],
      "versioning": "regex:^ubi(?<major>\\d+)-(?<minor>\\d+)\\.(?<patch>\\d+)-(?<build>\\d+)$"
    },
    {
      "matchDatasources": ["custom.pgbouncerimages"],
      "versioning": "regex:^ubi(?<major>\\d+)-(?<minor>\\d+)\\.(?<patch>\\d+)-(?<build>\\d+)$"
    },
    {
      "matchDatasources": ["custom.pgbackrestimages"],
      "versioning": "regex:^ubi(?<major>\\d+)-(?<minor>\\d+)\\.(?<patch>\\d+)-(?<build>\\d+)$"
    },
    {
      "matchDatasources": ["custom.pgadminimages"],
      "versioning": "regex:^ubi(?<major>\\d+)-(?<minor>\\d+)\\.(?<patch>\\d+)-(?<build>\\d+)$"
    },
    {
      "matchDatasources": ["custom.pgexporterimages"],
      "versioning": "regex:^ubi(?<major>\\d+)-(?<minor>\\d+\\.\\d+\\.\\d+)-(?<build>\\d+)$"
    }
  ],
  "regexManagers": [
    {
      "fileMatch": ["\\.ya?ml$"],
      "matchStrings": [
        "image:\\s*registry\\.developers\\.crunchydata\\.com/crunchydata/crunchy-(?<depName>\\S+):(?<currentValue>[\\w.-]+)\\s+#\\s+renovate:\\s+datasource=(?<datasource>\\S+)"
      ],
      "datasourceTemplate": "{{{datasource}}}",
      "versioningTemplate": "regex:^ubi(?<major>\\d+)-(?<minor>\\d+)\\.(?<patch>\\d+)-(?<build>\\d+)$"
    }
  ],
  "customDatasources": {
    "pgimages": {
      "defaultRegistryUrlTemplate": "https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/helm/install/values.yaml",
      "format": "yaml",
      "transformTemplates": [
        "{\"releases\":[{\"version\": $substringAfter($.relatedImages.postgres_16.image, \":\")}]}"
      ]
    },
    "pgbouncerimages": {
      "defaultRegistryUrlTemplate": "https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/helm/install/values.yaml",
      "format": "yaml",
      "transformTemplates": [
        "{\"releases\":[{\"version\": $substringAfter($.relatedImages.pgbouncer.image, \":\")}]}"
      ]
    },
    "pgbackrestimages": {
      "defaultRegistryUrlTemplate": "https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/helm/install/values.yaml",
      "format": "yaml",
      "transformTemplates": [
        "{\"releases\":[{\"version\": $substringAfter($.relatedImages.pgbackrest.image, \":\")}]}"
      ]
    },
    "pgadminimages": {
      "defaultRegistryUrlTemplate": "https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/helm/install/values.yaml",
      "format": "yaml",
      "transformTemplates": [
        "{\"releases\":[{\"version\": $substringAfter($.relatedImages.pgadmin.image, \":\")}]}"
      ]
    },
    "pgexporterimages": {
      "defaultRegistryUrlTemplate": "https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/helm/install/values.yaml",
      "format": "yaml",
      "transformTemplates": [
        "{\"releases\":[{\"version\": $substringAfter($.relatedImages.pgexporter.image, \":\")}]}"
      ]
    }
  },
  "dockerfile": {
    "enabled": false
  },
  "nuget": {
    "enabled": false
  },
  "terraform": {
    "enabled": false
  }
}
```

I then tagged my `PostgresCluster` like the following:

```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: my-postgres-cluster
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-16.3-1 # renovate: datasource=custom.pgimages
  backup:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.51-1 # renovate: datasource=custom.pgbackrestimages
  proxy:
    pgbouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.22-1 # renovate: datasource=custom.pgbouncerimages
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-0.15.0-7 # renovate: datasource=custom.pgexporterimages
  manager:
    pgadmin:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4:ubi8-8.6-1 # renovate: datasource=custom.pgadminimages
```

By implementing these changes, I was able to successfully manage and update the various images in my Kubernetes cluster using Renovate. Hopefully, this helps anyone facing a similar situation!
