### DISCUSSION TITLE
custom environment variables are not passed to renovate via renovate GitHub action

### DISCUSSION THREAD

**Discussion by florianmutter** [renovatebot/renovate#26576] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

37.127.0

### If you're self-hosting Renovate, select which platform you are using.

github.com

### What is your question?

We cannot get authentication to work for private packages from github. Our project is a `pnpm` project using workspaces.

Our workflow:
```yaml
name: Renovate
on:
  pull_request:
    paths:
      - ".github/workflows/renovate.yml"
  workflow_dispatch:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0 */2 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: 186101
          private_key: ${{ secrets.RENOVATE_APP_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@f9c81dddc9b589e4e6ae0326d1e36f6bc415d230 # v39.2.4
        with:
          configurationFile: .github/renovate-config.js
          token: '${{ steps.generate-token.outputs.token }}'
        env:
          LOG_LEVEL: 'debug'
          GITHUB_TOKEN_FOR_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
 ```

`.github/renovate-configs.js`:
```js
module.exports = {
  branchPrefix: 'renovate/',
  platform: 'github',
  repositories: ['fadi-nextgen-shop/ngshop'],
  username: 'nrp-renovate[bot]',
  gitAuthor: 'nrp-renovate[bot] <186101+nrp-renovate[bot]@noreply.users.github.com>',
  hostRules: [
    {
      hostType: 'npm',
      matchHost: 'https://npm.pkg.github.com',
      token: process.env.GITHUB_TOKEN_FOR_PACKAGES,
    },
    {
      hostType: 'maven',
      matchHost: 'https://maven.pkg.github.com',
      token: process.env.GITHUB_TOKEN_FOR_PACKAGES,
    },
    {
      hostType: 'npm',
      matchHost: 'https://registry.npmjs.org',
      timeout: 360000,
      // See https://github.com/renovatebot/renovate/issues/17677#issuecomment-1242005840
      enableHttp2: false,
    },
  ],
};
```

Repo top level `.npmrc`:
```
engine-strict=true
strict-peer-dependencies=false
@fadi-nextgen-shop:registry=https://npm.pkg.github.com
```

`discover/tests/ui-tests/package.json`:
```json
{
  "name": "ui-tests",
  "version": "1.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "test": "NODE_OPTIONS=\"--loader ts-node/esm\" cucumber-js --profile ci",
  },
  "dependencies": {
    "@fadi-nextgen-shop/ngshop-test-automation": "2.0.1",
    ...
  }
}
```

The error we get is
```
2024-01-10T10:48:59.1971146Z DEBUG: Failed to look up npm package @fadi-nextgen-shop/ngshop-test-automation (repository=fadi-nextgen-shop/ngshop, baseBranch=master, packageFile=discover/tests/ui-tests/package.json, dependency=@fadi-nextgen-shop/ngshop-test-automation)
```

The token does have the correct permissions. I did verify this with a very simple npm setup that also uses this token and `npm i` works in the github action.

I'm happy to provide more data but I could not find anything in the logs that looks related.
