### DISCUSSION TITLE
yarn berry produces different checksum for locally resolved packages

### DISCUSSION THREAD

**Discussion by cranberyxl** [renovatebot/renovate#26672] [Request Help]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### What is your question?

We are using a locally resolved yarn package:
```
 "eslint-plugin-exos": "file:./eslint",
```

```yml
# .yarnrc.yml
compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  teamexos:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.pkg.github.com'

packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'

yarnPath: .yarn/releases/yarn-berry.js
```

When upgrading from yarn v1 to yarn berry (4.0.2) the checksum is being updated on the local file to be different than what I resolve on my local machine or in github actions. 

### Logs (if relevant)

<details><summary>Logs</summary>

```

YN0085: │ + eslint-plugin-exos@file:./eslint#./eslint::hash=54d945&locator=%40teamexos%2Fprince-backend%40workspace%3A., storyblok-js-client@npm:6.6.2\n➤ 
YN0085: │ - eslint-plugin-exos@file:./eslint#./eslint::hash=ef1c99&locator=%40teamexos%2Fprince-backend%40workspace%3A., storyblok-js-client@npm:6.6.1\n➤ 
```

</details>
