### DISCUSSION TITLE
Docker images in ansible playbook or requirements.yaml skipped

### DISCUSSION THREAD

**Discussion by GiraeffleAeffle** [renovatebot/renovate#26694] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

37.131.0

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### What is your question?

I'm trying to onboard a repository with an ansible playbook which contains some docker images. However renovate just skipped it. I also added some fileMatch and matchStrings, but it still was skipped. I also tried to outsource my docker images in requirements.yaml and import them into the playbook, but it still was skipped.

## renovate config

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "description": "Renovate preset to update gitlab remote include for renovate templates",
  "customManagers": [
    {
      "customType": "regex",
      "description": "Update renovate remote includes version",
      "fileMatch": ["\\.gitlab-ci\\.ya?ml$"],
      "matchStrings": [
        "-\\s+remote:\\s+https://gitlab\\.com/renovate-bot/renovate-runner/-/raw/(?<currentValue>v[0-9.]+)/"
      ],
      "datasourceTemplate": "gitlab-releases",
      "depNameTemplate": "renovate-runner",
      "packageNameTemplate": "renovate-bot/renovate-runner",
      "versioningTemplate": "semver"
    },
    {
      "customType": "regex",
      "description": "Update Docker images in Ansible playbook",
      "fileMatch":["(^|\\/)tasks\\/(.*[.ya?ml$])"],
      "matchStrings": [
        "\\s*geth_container_image:\\s+?(:?[\\\/a-z\\.-]+\\\/)*(?<depName>[\\\/a-z-]+)(?::(?<currentValue>[a-z0-9.-]+))?",
        "\\s*lighthouse_container_image:\\s+?(:?[\\\/a-z\\.-]+\\\/)*(?<depName>[\\\/a-z-]+)(?::(?<currentValue>[a-z0-9.-]+))?",
        "\\s*mev_boost_container_image:\\s+?(:?[\\\/a-z\\.-]+\\\/)*(?<depName>[\\\/a-z-]+)(?::(?<currentValue>[a-z0-9.-]+))?"
      ],
      "datasourceTemplate": "docker"
    }
  ]
}
```

## ansible playbook + requirements.yaml

The playbook is located in a `tasks` folder, so the path to the ansible playbook would be `tasks/ansible.yaml`:

```
- name: Load Docker Image Versions
  hosts: localhost
  tasks:
    - name: Include Docker Image Versions
      include_vars:
        file: requirements.yaml
        name: collections

- name: SafeStake Geth Lighthouse MEV-Boost
  hosts: hetzner_germany_safestake
  become: yes
  roles:
    # Install dependencies
    - role: geerlingguy.docker
    - role: geerlingguy.pip
      pip_install_packages: #only required for hetzner_germany
        - name: docker #only required for hetzner_germany

    # Install pre-tasks
    - role: roles/pretasks

    # Install ansible collection role from ethpandaOps
    - role: ethpandaops.general.ethereum_node
      ethereum_node_mev_boost_enabled: true
      ethereum_node_cl_validator_fee_recipient: ""
      # Choose EL & CL
      ethereum_node_el: geth
      ethereum_node_cl: lighthouse

      # Client specific configuration

      # Geth
      geth_container_image: "{{ collections[0].name }}:{{ collections[0].version }}"
      geth_container_command_extra_args:
        - --goerli
        - --ws
        - --ws.port=8545
        - --ws.addr=0.0.0.0
        - --ws.origins=*
        - --http.corsdomain=*
        - --http.vhosts=*
        - --state.scheme=path

      # Lighthouse
      lighthouse_container_image: "{{ collections[1].name }}:{{ collections[1].version }}"
      lighthouse_checkpoint_sync_enabled: true
      checkpoint_sync_url: https://goerli.checkpoint-sync.ethpandaops.io
      lighthouse_container_command_extra_args:
        - --network=goerli
        - --builder=http://mev-boost:18550
        - --suggested-fee-recipient=
        - --target-peers=100

      # MEV-Boost
      mev_boost_container_image: "{{ collections[2].name }}:{{ collections[2].version }}"
      mev_boost_container_name: mev-boost
      mev_boost_container_command_extra_args:
        - --goerli
        - --relays=

    # SafeStake
    - role: roles/safestake

    # Prometheus
    - role: ethpandaops.general.prometheus
      prometheus_container_ports:
        - "0.0.0.0:9090:9090"
      prometheus_container_networks:
        - name: shared
      prometheus_config: |
        # my global config
        global:
          scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
          evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
          # scrape_timeout is set to the global default (10s).

          # Attach these labels to any time series or alerts when communicating with
          # external systems (federation, remote storage, Alertmanager).
          external_labels:
            monitor: 'codelab-monitor'

        # Alertmanager configuration
        alerting:
          alertmanagers:
            - static_configs:
                - targets:
                  # - alertmanager:9093

        # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
        rule_files:
          # - "first_rules.yml"
          # - "second_rules.yml"

        # A scrape configuration containing exactly one endpoint to scrape:
        # Here it's Prometheus itself.
        scrape_configs:
          # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
          - job_name: "prometheus-canada"

            # metrics_path defaults to '/metrics'
            # scheme defaults to 'http'.

            static_configs:
              - targets: ["localhost:9090"]
                labels:
                  name: 'prometheus'
                  location: 'canada'
                  server_ip: '{{ ansible_default_ipv4.address }}'

          - job_name: 'lighthouse-canada'
            metrics_path: /metrics

            static_configs:
              - targets: ['lighthouse:5054']
                labels:
                  name: 'lighthouse'
                  location: 'canada'
                  server_ip: '{{ ansible_default_ipv4.address }}'

          - job_name: 'geth-canada'
            scrape_interval: 15s
            scrape_timeout: 10s
            metrics_path: /debug/metrics/prometheus
            scheme: http
            static_configs:
              - targets: ['geth:6060']
                labels:
                  name: 'geth'
                  location: 'canada'
                  server_ip: '{{ ansible_default_ipv4.address }}'

          - job_name: 'ssv-canada'
            scrape_interval: 15s
            scrape_timeout: 10s
            scheme: http
            static_configs:
              - targets: ['ssv-node:15000']
                labels:
                  name: 'ssv'
                  location: 'canada'
                  server_ip: '{{ ansible_default_ipv4.address }}'

    # Garbage collection
    - role: ethpandaops.general.docker_cleanup
```

```
collections:
  - name: ethereum/client-go
    version: v1.13.10
  - name: sigp/lighthouse
    version: v4.5.0-amd64-modern
  - name: flashbots/mev-boost
    version: 1.6
```

How can I make sure that renovate can detect my ansible playbook or the images in the requirements.yaml?

Thank you!

### Logs (if relevant)

INFO: Repository started
       "renovateVersion": "37.131.0"
 INFO: Repository has no package files - skipping

**Comment by github-actions** [comment]
Hi there,

Get your discussion fixed faster by creating a minimal reproduction. This means a repository dedicated to reproducing this issue with the minimal dependencies and config possible.

Before we start working on your issue we need to know exactly what's causing the current behavior. A minimal reproduction helps us with this.

To get started, please read our guide on creating a [minimal reproduction](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md).

We may close the discussion if you, or someone else, haven't created a minimal reproduction within two weeks. If you need more time, or are stuck, please ask for help or more time in a comment.

Good luck,

The Renovate team

**Reply by GiraeffleAeffle** [reply]
Here is the minimal reproduction:

https://github.com/GiraeffleAeffle/minimal-reproduction-renovate

**Reply by rarkins** [reply]
Why are any custom cornered managers even needed to reproduce a a single manager problem? Regex managers don't belong inside Ansible config either

**Reply by GiraeffleAeffle** [reply]
I had already tried different renovate config files. The one I mentioned above does not contain that like you see here. 

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "description": "Renovate preset to update gitlab remote include for renovate templates",
  "customManagers": [
    {
      "customType": "regex",
      "description": "Update renovate remote includes version",
      "fileMatch": ["\\.gitlab-ci\\.ya?ml$"],
      "matchStrings": [
        "-\\s+remote:\\s+https://gitlab\\.com/renovate-bot/renovate-runner/-/raw/(?<currentValue>v[0-9.]+)/"
      ],
      "datasourceTemplate": "gitlab-releases",
      "depNameTemplate": "renovate-runner",
      "packageNameTemplate": "renovate-bot/renovate-runner",
      "versioningTemplate": "semver"
    },
    {
      "customType": "regex",
      "description": "Update Docker images in Ansible playbook",
      "fileMatch":["(^|\\/)tasks\\/(.*[.ya?ml$])"],
      "matchStrings": [
        "\\s*geth_container_image:\\s+?(:?[\\\/a-z\\.-]+\\\/)*(?<depName>[\\\/a-z-]+)(?::(?<currentValue>[a-z0-9.-]+))?",
        "\\s*lighthouse_container_image:\\s+?(:?[\\\/a-z\\.-]+\\\/)*(?<depName>[\\\/a-z-]+)(?::(?<currentValue>[a-z0-9.-]+))?",
        "\\s*mev_boost_container_image:\\s+?(:?[\\\/a-z\\.-]+\\\/)*(?<depName>[\\\/a-z-]+)(?::(?<currentValue>[a-z0-9.-]+))?"
      ],
      "datasourceTemplate": "docker"
    }
  ]
}
```

But how would a config file that would detect the docker images look like? Also is it generally possible to outsource the images in the requirements.yaml to have it separated, so it is more clean and detectable by renovate?

**Reply by rarkins** [reply]
Which of these is true?
1. You have standard ansible syntax and expected Renovate's ansible manager to detect your images by default
2. You are using non standard syntax so a custom manager is necessary

**Reply by GiraeffleAeffle** [reply]
I first tried that Renovate would detect the images in the ansible playbook, without any additional settings, but since this didn't work I created a custom manager, because for example my images are named 'component_container_image' instead of just 'image' so I think it would need a custom manager to be able to detect them. 

I was just able to detect the content of the requirements.yaml with ansible-galaxy because I renamed it to requirements.yml . Seems like .yml is the default setting, but Renovate was not able to detect the .yaml.  However now I get the error that it failed to lookup the git-tags package with ansible-galaxy. I understood that the datasource git-tags would not be suited to detect the docker images, so I created a regexManager that datasource docker, but that still does not work. What would I need to add that it can correctly detect the images?

## renovate config

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "description": "Renovate preset to update gitlab remote include for renovate templates",
  "customManagers": [
    {
      "customType": "regex",
      "description": "Update renovate remote includes version",
      "fileMatch": ["\\.gitlab-ci\\.ya?ml$"],
      "matchStrings": [
        "-\\s+remote:\\s+https://gitlab\\.com/renovate-bot/renovate-runner/-/raw/(?<currentValue>v[0-9.]+)/"
      ],
      "datasourceTemplate": "gitlab-releases",
      "depNameTemplate": "renovate-runner",
      "packageNameTemplate": "renovate-bot/renovate-runner",
      "versioningTemplate": "semver"
    },
    {
      "customType": "regex",
      "description": "Update Docker images in Ansible playbook",
      "fileMatch": ["requirements\\.yml"],
      "matchStrings": [
        "\"name\":\\s*\"(?<depName>[^\"]+)\",\\s*\"version\":\\s*\"(?<currentValue>[^\"]+)\""
      ],
      "datasourceTemplate": "docker"
    }
  ]
}
```

## requirements.yml

```
collections:
  - name: ethereum/client-go
    version: v1.12.0
    source: https://docker.io
  - name: sigp/lighthouse
    version: v4.4.0
    source: https://docker.io
  - name: flashbots/mev-boost
    version: 1.5
    source: https://docker.io
```

## pipeline output

```
"config": {
         "ansible-galaxy": [
           {
             "deps": [
               {
                 "depType": "galaxy-collection",
                 "currentValue": "v1.12.0",
                 "registryUrls": ["https://docker.io/"],
                 "depName": "ethereum/client-go",
                 "datasource": "git-tags",
                 "packageName": "ethereum/client-go",
                 "updates": [],
                 "versioning": "semver-coerced",
                 "warnings": [
                   {
                     "topic": "ethereum/client-go",
                     "message": "Failed to look up git-tags package ethereum/client-go"
                   }
                 ]
               },
               {
                 "depType": "galaxy-collection",
                 "currentValue": "v4.4.0",
                 "registryUrls": ["https://docker.io/"],
                 "depName": "sigp/lighthouse",
                 "datasource": "git-tags",
                 "packageName": "sigp/lighthouse",
                 "updates": [],
                 "versioning": "semver-coerced",
                 "warnings": [
                   {
                     "topic": "sigp/lighthouse",
                     "message": "Failed to look up git-tags package sigp/lighthouse"
                   }
                 ]
               },
               {
                 "depType": "galaxy-collection",
                 "currentValue": "1.5",
                 "registryUrls": ["https://docker.io/"],
                 "depName": "flashbots/mev-boost",
                 "datasource": "git-tags",
                 "packageName": "flashbots/mev-boost",
                 "updates": [],
                 "versioning": "semver-coerced",
                 "warnings": [
                   {
                     "topic": "flashbots/mev-boost",
                     "message": "Failed to look up git-tags package flashbots/mev-boost"
                   }
                 ]
               }
             ],
             "packageFile": "requirements.yml"
           }
         ]
```

**Reply by rarkins** [reply]
Please update your reproduction repo, i.e. remove all custom manager config and any non-default config which is not essential, so that it reproduces the lookup problem

**Reply by GiraeffleAeffle** [reply]
Ok, I updated it. It should be like my gitlab repo now. The custom manager is in my renovate runner repo, not in the renovate.json of the repo that should be updated by renovate, I put that config in the README.md for reference.

**Reply by rarkins** [reply]
Here is an example:

```
collections:
  - name: ethereum/client-go
    version: v1.12.0
    source: https://docker.io
```

Obviously we know that docker.io is Docker images, but how can a tool know, without a hardcoded list of known Docker registries? e.g. it could also be `source: https://quay.io` or others.

Without logic or hardcoding, Renovate assumes these are git tags.

I think we need to find the documentation for `collections` which defines the possible syntax types.
