### DISCUSSION TITLE
[helm-values] support digest

### DISCUSSION THREAD

**Discussion by ira-gordin-sap** [renovatebot/renovate#26710] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

37.105.0

### If you're self-hosting Renovate, select which platform you are using.

github.com

### What is your question?

How to configure digest to work here?:
```
image:
  registry: docker.io
  repository: busybox
  digest: sha256:4b6ad3a68d34da29bf7c8ccb5d355ba8b4babcad1f99798204e7abb43e54ee3d
```

### Logs (if relevant)

<details><summary>Logs</summary>

```

Copy/paste the relevant log(s) here, between the starting and ending backticks

```

</details>
