### DISCUSSION TITLE
PR #26451 breaks fetching pulls for private repos on Gitea

### DISCUSSION THREAD

**Discussion by Apocalypsor** [renovatebot/renovate#26772] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

lastest

### If you're self-hosting Renovate, select which platform you are using.

Gitea

Gitea version: lastest

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the problem

I'm using GitHub Action to run Renovate for my Gitea Instance:

config.yaml:
```yaml
# Self-hosted
autodiscover: true
autodiscoverFilter: "!/.*Mirror/.+/"
logFileLevel: error

# Repository
automerge: true
commitBodyTable: true
configMigration: true
dependencyDashboard: true
gitLabIgnoreApprovals: true

hostRules:
  - enableHttp2: true
lockFileMaintenance:
  enabled: true
platformAutomerge: true
ignoreDeps:
  - python
  - node
```

.github/workflows/Renovate.yaml:
```yaml
name: Renovate

on:
  schedule:
    - cron: 07 */3 * * *

  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    container: renovate/renovate:latest
    steps:
      - name: Load config
        run: ***
      - name: Self-hosted Renovate
        run: renovate || echo "failed"
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_USERNAME: ${{ secrets.RENOVATE_USERNAME }}
          RENOVATE_ENDPOINT: ${{ secrets.RENOVATE_ENDPOINT }}
          RENOVATE_PLATFORM: gitea
          RENOVATE_GIT_URL: endpoint
          RENOVATE_CONFIG_FILE: /tmp/config.yaml
          RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.RENOVATE_GIT_PRIVATE_KEY }}
          LOG_LEVEL: ERROR
          GITHUB_COM_TOKEN: ${{ secrets.GH_TOKEN }}
```

I have tested version [37.133.1](https://github.com/renovatebot/renovate/releases/tag/37.133.1) and version [37.134.0](https://github.com/renovatebot/renovate/releases/tag/37.134.0), I only see this error in the latter version.

### Relevant debug logs

<details><summary>Logs</summary>

```
ERROR: Repository has unknown error (repository=***/***)
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1705822066278,
           "socket": 1705822066278,
           "upload": 1705822066279,
           "response": 1705822066389,
           "end": 1705822066389,
           "phases": {
             "wait": 0,
             "request": null,
             "firstByte": 110,
             "download": 0,
             "total": 111
           }
         },
         "message": "Response code 404 (Not Found)",
         "stack": "HTTPError: Response code 404 (Not Found)\n    at Request.<anonymous> (/opt/containerbase/tools/renovate/37.134.0/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/37.134.0 (https://github.com/renovate***/renovate)",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://git.***.***/api/v1/repos/***/***/pulls?page=2&sort=recentupdate&state=all",
           "hostType": "gitea",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": true
         },
         "response": {
           "statusCode": 404,
           "statusMessage": "Not Found",
           "body": {
             "errors": null,
             "message": "The target couldn't be found.",
             "url": "https://git.***.***/api/swagger"
           },
           "headers": {
             ":status": 404,
             "date": "Sun, 21 Jan 2024 07:27:46 GMT",
             "content-type": "application/json;charset=utf-8",
             "content-length": "98",
             "cache-control": "max-age=0, private, must-revalidate, no-transform",
             "x-content-type-options": "nosniff",
             "x-frame-options": "SAMEORIGIN",
             "strict-transport-security": "max-age=[15](https://github.com/Apocalypsor/***/actions/runs/7599765470/job/20697162038#step:4:16)55[20](https://github.com/Apocalypsor/***/actions/runs/7599765470/job/20697162038#step:4:21)00; includeSubDomains; preload",
             "cf-cache-status": "DYNAMIC",
             "report-to": "***",
             "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}",
             "server": "cloudflare",
             "cf-ray": "848dd62a4b940790-IAD",
             "alt-svc": "h3=\":443\"; ma=86400"
           },
           "httpVersion": "2.0",
           "retryCount": 0
         }
       }
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above
