### DISCUSSION TITLE
Is renovate able to detect updates for docker images with multiple suffixes like `docker:24.0.7-dind-alpine3.18`?

### DISCUSSION THREAD

**Discussion by reimer-atb** [renovatebot/renovate#26820] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

37.146.0

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### What is your question?

With the following `.gitlab-ci.yml`:

```
  services:
    - name: docker:24.0.7-dind-alpine3.18@sha256:c90e58d30700470fc59bdaaf802340fd25c1db628756d7bf74e100c566ba9589
      alias: docker
  image: docker:24.0.7-dind-alpine3.18@sha256:c90e58d30700470fc59bdaaf802340fd25c1db628756d7bf74e100c566ba9589
```

renovate does not create a merge request for updating to version [25.0.0-dind-alpine3.19](https://hub.docker.com/layers/library/docker/25.0.0-dind-alpine3.19/images/sha256-7508cb6f10839ccc29db65e90b7fa251d01b87269e2d36fe6ae7110ef5858612?context=explore).

But it does correctly detect the dependency version, and lists it the Dependency Dashboard issue.

If I remove the `-alpine3.18` suffix, and change to:

```
  services:
    - name: docker:24.0.7-dind@sha256:1da2a5af44cfaf60a430e7064abaa25a22f57f888e6c6f119d01fcb1d40672e4
      alias: docker
  image: docker:24.0.7-dind@sha256:1da2a5af44cfaf60a430e7064abaa25a22f57f888e6c6f119d01fcb1d40672e4
```

renovate will create the merge request to update to version [docker:25.0.0-dind](https://hub.docker.com/layers/library/docker/25.0.0-dind/images/sha256-0c268edd5648ec50d8ed899da386728d50a2dcbf71cb714e8ab5cae10b04da77?context=explore).

My question is: should renovate be able to handle `docker:24.0.7-dind-alpine3.18` out of the box? Or is this not supported and I have to create a custom regex manager for this?

### Logs (if relevant)

<details><summary>Logs</summary>

```

Copy/paste the relevant log(s) here, between the starting and ending backticks

```

</details>
