### DISCUSSION TITLE
hostRules -> yarnrc.yml npmRegistries should have https prefix

### DISCUSSION THREAD

**Discussion by RGunning** [renovatebot/renovate#26919] [Suggest an Idea]
### Tell us more.

At the moment, when constructing the yarnrc from the hostRules the https: prefix is stripped off the url

https://github.com/renovatebot/renovate/blob/a5d1b530c3cae2ee1fa9ce4ef0cb16ff226203cd/lib/modules/manager/npm/post-update/rules.ts#L24-L27

e.g.
```yml
npmRegistries:
  "//my-private-regsistry":
    npmAuthToken: xxxxxx
```

However, logging in with `yarn config set --home npmRegistryServer "https://my-private-regsistry"  && yarn config login` would add a .yarnrc.yml
```yml
npmRegistries:
  "https://my-private-regsistry":
    npmAuthToken: xxxxxx
```

This leads to a different config on developers machines vs in renovate. 

then in repository yarnrc files if you need to set npmAlwaysAuth

for it to work on a developer machine you need

```yml
npmRegistries:
  "https://my-private-regsistry":
    npmAlwaysAuth: true
```

but for renovate you need 

```yml
npmRegistries:
  "//my-private-regsistry":
    npmAlwaysAuth: true
```

and yarn get's conflicts if you try adding both with and without the https: prefix.

As Yarn adds the https: prefix it would make sense to modify https://github.com/renovatebot/renovate/blob/a5d1b530c3cae2ee1fa9ce4ef0cb16ff226203cd/lib/modules/manager/npm/post-update/rules.ts#L24-L27
 so that the https: prefix is left there too.

**Comment by rarkins** [comment]
Do we know if all versions of Yarn using yarnrc.yml support https:// ?

**Reply by RGunning** [reply]
not sure, I've just been trying with yarn@4.0.2 

Maybe one option would be to add a fuzzy matching of keys when [merging the existingYarnrRcYml and additionalYarnRcYml.](https://github.com/renovatebot/renovate/blob/a5d1b530c3cae2ee1fa9ce4ef0cb16ff226203cd/lib/modules/manager/npm/post-update/index.ts#L576-L579)

so instead of merging 

A yarnrc.yml 
```yml
npmRegistries:
  "https://my-private-regsistry":
    npmAlwaysAuth: true
```

and B yarnrc.yml
```yml
npmRegistries:
  "//my-private-regsistry":
    npmAuthToken: xxxxxx
```

as 

```yml
npmRegistries:
  "https://my-private-regsistry":
    npmAlwaysAuth: true
  "//my-private-regsistry":
    npmAuthToken: xxxxxx
```

we could detect that A already has a key matching so we get 

```yml
npmRegistries:
  "https://my-private-regsistry":
    npmAlwaysAuth: true
    npmAuthToken: xxxxxx
```

This solve the conflicts documented here
https://docs.renovatebot.com/getting-started/private-packages/#yarn-2


```ts
const fuzzyMatchAdditionalYarnRcYml = {
  ...additionalYarnRcYml,
  npmRegistries: Object.entries(additionalYarnRcYml.npmRegistries || {})
    .map(([k, v]) => {
      const key = Object.keys(existingYarnrRcYml.npmRegistries || {}).find(
        (x) => x.endsWith(k),
      ) ?? k;
      return { [key]: v };
    })
    .reduce((acc, cur) => ({ ...acc, ...cur }), {}),
};

const updatedYarnYrcYml = deepmerge(
existingYarnrRcYml,
fuzzyMatchAdditionalYarnRcYml,
);
```
