### DISCUSSION TITLE
Individual pull request for "override" values in ArgoCD templates

### DISCUSSION THREAD

**Discussion by evilensky** [renovatebot/renovate#26931] [Request Help] [answered]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### What is your question?

I would like to separate a single ArgoCD template's `config.yml` into separate pull requests by override. 

For a given `config.yml` like this:

```
---
# yamllint disable-line rule:line-length
# renovate: datasource=helm depName=bottlerocket-shadow registryUrl=https://bottlerocket-os.github.io/bottlerocket-update-operator   versioning=semver
chart_version: 0.9.0
chart_name: bottlerocket-shadow
# should start with oci:// or https://
repo_url: https://bottlerocket-os.github.io/bottlerocket-update-operator
namespace: brupop-bottlerocket-aws
# enum of crd,controller,cr
apptype: crd
# overrides is a map with a potential for a child and grandchild map
# overrides:
#   tools-dev:
#     somekey: value
overrides:
  poc:
    # renovate: datasource=helm depName=bottlerocket-shadow registryUrl=https://bottlerocket-os.github.io/bottlerocket-update-operator  versioning=semver
    chart_version: 0.9.0
    chart_name: bottlerocket-shadow
  test: ...
  prod: ...
```

I would like for reach `overrides: $env` value to be a separate suggested PR.  I'm not sure where to accomplish this. 

Should I try multiple [recursive managers](https://docs.renovatebot.com/configuration-options/#recursive) for each section that represents an environment override?  But how do I link these managers to a packageRule that can create the appropriate branch?

### Logs (if relevant)

<details><summary>Logs</summary>

```

Copy/paste the relevant log(s) here, between the starting and ending backticks

```

</details>
