### DISCUSSION TITLE
Php 8.0 cannot be installed

### DISCUSSION THREAD

**Discussion by KrohnMi** [renovatebot/renovate#26944] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

37.161.0

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the problem

I have a problem with my PHP 8 projects. The installation of PHP 8.0 always fails. With the following Error.

Installing v2 tool PHP v8.0.0\n[14:50:01.539] INFO (742): Installing tool PHP@8.0.0...\ntar: This does not look like a tar archive\nxz: (stdin): File format not recognized

<details><summary>Docker-Compose.yml</summary>

```
version: '3'
services:
  renovate:
    image: ghcr.io/renovatebot/renovate:37.161.0@sha256:3c9543a3775821c4a05aaff6866158b0638a98abcf6d2c9107aacf042589c828
    environment:
      - RENOVATE_BASE_DIR=$CI_PROJECT_DIR/renovate
      - RENOVATE_ENDPOINT=xxxxxxxxxxxxxxxxxx
      - RENOVATE_PLATFORM=gitlab
      - RENOVATE_OPTIMIZE_FOR_DISABLED=true
      - RENOVATE_REPOSITORY_CACHE=true
      - RENOVATE_CONTAINER_CACHE=false
      - RENOVATE_REQUIRE_CONFIG=required
      - RENOVATE_IGNORE_PR_AUTHOR=false
      - RENOVATE_ONBOARDING=false
      - RENOVATE_EXTENDS=github>whitesource/merge-confidence:beta
      - LOG_LEVEL=debug
      - GITHUB_COM_TOKEN=xxxxxxxxxxxxxxxxxx
      - RENOVATE_BRANCH_CONCURRENT_LIMIT=0
      - RENOVATE_EXTRA_FLAGS=xxxxxxxxxxxxxxxxxx
      - RENOVATE_TOKEN=xxxxxxxxxxxxxxxxxx
      - LOGE_LEVEL=debug

    volumes:
      - ./renovate/:/renovate/
    command:
      - renovate
```

</details>

### Relevant debug logs

<details><summary>Logs</summary>

```

"err": {
    "cmd": "/bin/sh -c install-tool php 8.0.0",
    "stderr": "",
    "stdout": "installing v2 tool php v8.0.0\n[14:50:01.539] INFO (742): Installing tool php@8.0.0...\ntar: This does not look like a tar archive\nxz: (stdin): File format not recognized\ntar: Child returned status 1\ntar: Error is not recoverable: exiting now\n[14:50:01.671] FATAL (742): Command failed with exit code 2: /usr/local/containerbase/bin/install-tool php 8.0.0\n    err: {\n      \"type\": \"Error\",\n      \"message\": \"Command failed with exit code 2: /usr/local/containerbase/bin/install-tool php 8.0.0\",\n      \"stack\":\n          Error: Command failed with exit code 2: /usr/local/containerbase/bin/install-tool php 8.0.0\n              at makeError (/snapshot/dist/containerbase-cli.js:44509:13)\n              at handlePromise (/snapshot/dist/containerbase-cli.js:45224:29)\n              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n              at async InstallLegacyToolService.execute (/snapshot/dist/containerbase-cli.js:52049:5)\n              at async InstallToolService.execute (/snapshot/dist/containerbase-cli.js:52229:9)\n              at async InstallToolShortCommand.execute (/snapshot/dist/containerbase-cli.js:52437:14)\n              at async InstallToolShortCommand.validateAndExecute (/snapshot/dist/containerbase-cli.js:2426:26)\n              at async _Cli.run (/snapshot/dist/containerbase-cli.js:3539:22)\n              at async _Cli.runExit (/snapshot/dist/containerbase-cli.js:3547:28)\n              at async main (/snapshot/dist/containerbase-cli.js:52631:3)\n      \"shortMessage\": \"Command failed with exit code 2: /usr/local/containerbase/bin/install-tool php 8.0.0\",\n      \"command\": \"/usr/local/containerbase/bin/install-tool php 8.0.0\",\n      \"escapedCommand\": \"\\\"/usr/local/containerbase/bin/install-tool\\\" php 8.0.0\",\n      \"exitCode\": 2,\n      \"cwd\": \"/renovate/repos/gitlab/jakota/lueftner-cruises/lc-web-11\",\n      \"failed\": true,\n      \"timedOut\": false,\n      \"isCanceled\": false,\n      \"killed\": false\n    }\n[14:50:01.696] INFO (742): Installed tool php with errors in 157ms.\n",
    "options": {
    "cwd": "/renovate/repos/gitlab/jakota/lueftner-cruises/lc-web-11",
    "encoding": "utf-8",
    "env": {
        "COMPOSER_CACHE_DIR": "/renovate/cache/others/composer",
        "COMPOSER_AUTH": "{\"github-oauth\":{\"github.com\":\"**redacted**\"},\"gitlab-token\":{\"jakota.dev\":\"**redacted**\"},\"gitlab-domains\":[\"jakota.dev\"]}",
        "HOME": "/home/ubuntu",
        "PATH": "/home/ubuntu/.cargo/bin:/home/ubuntu/.local/bin:/go/bin:/home/ubuntu/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/.cargo/bin:/home/ubuntu/.local/bin:/go/bin:/home/ubuntu/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/.cargo/bin:/home/ubuntu/.local/bin:/go/bin:/home/ubuntu/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "LC_ALL": "C.UTF-8",
        "LANG": "C.UTF-8",
        "CONTAINERBASE_CACHE_DIR": "/renovate/cache/containerbase"
    },
    "maxBuffer": 10485760,
    "timeout": 900000
    },
    "exitCode": 1,
    "name": "ExecError",
    "message": "Command failed: install-tool php 8.0.0\n",
    "stack": "ExecError: Command failed: install-tool php 8.0.0\n\n    at ChildProcess.<anonymous> (/opt/containerbase/tools/renovate/37.161.0/node_modules/renovate/lib/util/exec/common.ts:99:11)\n    at ChildProcess.emit (node:events:529:35)\n    at ChildProcess.emit (node:domain:489:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)"
}
        

```

</details>

### Have you created a minimal reproduction repository?

Placeholder value, please select the correct response from the dropdown
