### DISCUSSION TITLE
Private registries and postUpgradeTasks with a npm/yarn install

### DISCUSSION THREAD

**Discussion by RGunning** [renovatebot/renovate#27060] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

37.171.2

### If you're self-hosting Renovate, select which platform you are using.

Bitbucket Cloud (bitbucket.org)

### What is your question?

When running postUpgrade tasks how best should you handle authentication to a private npm registry?
At the moment as far as i can tell the hostRules are ignored for the postUpgradeTasks so running `npm install`/`yarn install` fails.

So far the only solution I have found is to set a global .yarnrc.yml and/or .npmrc  (with   `binarySource: 'install',`) on the image where we run renovate from, which works. Is there a better way to add authentication for postUpgrade tasks with a private registry? Ideally I would want to be able to read from the hostRules? Is there something I am overlooking that would make this work without having to set a global config in addition to having the hostRules set?

e.g. our bitbucket pipeline step looks like this

```yml
 - step: &step/renovate
        name: Renovate
        image: renovate/renovate:full
        caches:
          - renovate-cache
        script:
          - ./generate-npmrc.sh >  ~/.npmrc
          - ./generate-yarnrc.sh >  ~/.yarnrc.yml
          - export RENOVATE_CONFIG_FILE="$BITBUCKET_CLONE_DIR/config.js"
          - renovate --platform=bitbucket ...
```

### Logs (if relevant)

<details><summary>Logs</summary>

```

Copy/paste the relevant log(s) here, between the starting and ending backticks

```

</details>
