### DISCUSSION TITLE
Hostrules encrypted password not working

### DISCUSSION THREAD

**Discussion by froblesmartin** [renovatebot/renovate#27089] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

Using the latest GitHub Action

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

I have not seen this working

### Describe the problem

I am using https://github.com/renovatebot/github-action in a GitHub repository. I have been trying to get the hostrules password encrypted, but it does not work.

I am trying to **authenticate with Google Artifact Registry**, following https://docs.renovatebot.com/docker/#google-container-registry-google-artifact-registry.

I have followed https://docs.renovatebot.com/self-hosted-configuration/#privatekey to **generate both the private and public keys** as RSA with 4096 bits and no passphrase. Then saved the https://app.renovatebot.com/encrypt website locally and **changed the public key** to the one I have generated. With that and my organization, I have encrypted the "password" (**the whole JSON provided by GCP, which I have base64 encoded**). And then written the `hostRules` as:

```json
    "hostRules": [
      {
        "matchHost": "europe-southwest1-docker.pkg.dev",
        "username": "_json_key_base64",
        "encrypted": {
          "password": "ENCRYPTED_STRING_FROM_THE_WEBSITE_WITH_MY_PUBLIC_KEY"
        }
      }
    ]
```

Then, I have defined the private key from a GitHub Secret with the environment variable `RENOVATE_PRIVATE_KEY`, so that it can decrypt the "password".

```yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.0.2
        with:
          configurationFile: .github/renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: DEBUG
          RENOVATE_DRY_RUN: full
          RENOVATE_PRIVATE_KEY: ${{ secrets.RENOVATE_PRIVATE_KEY }}
```

Checking in the logs, it says that it is not even trying to authenticate. Look below in the logs section

If I use the base64 encoded string directly as `password` instead of `encrypted: { password`, it works fine. So it has to be some issue with the encryption/decryption.

I tried with the `LOG_LEVEL=TRACE`, but it did not provide me with any extra information.

For anybody reaching this, for now as a workaround, I am using the environment variable `RENOVATE_HOST_RULES` with a GitHub Secret which has the whole configuration block, with the base64 encoded "password", so that it is not in clear text in the logs:

```yaml
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.0.2
        with:
          configurationFile: .github/renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: DEBUG
          RENOVATE_DRY_RUN: full
          RENOVATE_PRIVATE_KEY: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          RENOVATE_HOST_RULES: ${{ secrets.RENOVATE_HOST_RULES }}
```

### Relevant debug logs

<details><summary>Logs</summary>

```

DEBUG: hostRules: google auth for https://europe-southwest1-docker.pkg.dev/ (repository=MYORG/MYREPO)
DEBUG: Could not get Google access token, using no auth (repository=MYORG/MYREPO)
       "registryHost": "https://europe-southwest1-docker.pkg.dev/",
       "dockerRepository": "MY_GCP_PROJECT/PATH/TO/HELM_CHART"
DEBUG: GET https://europe-southwest1-docker.pkg.dev/v2/token?scope=repository%3AMY_GCP_PROJECT/PATH/TO/HELM_CHART%3Apull&service=europe-southwest1-docker.pkg.dev = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=403 retryCount=0, duration=768) (repository=MYORG/MYREPO)
DEBUG: Not allowed to access docker registry (repository=MYORG/MYREPO)
       "registryHost": "https://europe-southwest1-docker.pkg.dev/",
       "dockerRepository": "MY_GCP_PROJECT/PATH/TO/HELM_CHART"
DEBUG: Response code 403 (Forbidden) (repository=MYORG/MYREPO)
       "err": ***
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": ***
           "start": 1707187233101,
           "socket": 1707187233101,
           "lookup": 1707187233141,
           "connect": 1707187233148,
           "secureConnect": 1707187233155,
           "upload": 1707187233155,
           "response": 1707187233868,
           "end": 1707187233869,
           "phases": ***
             "wait": 0,
             "dns": 40,
             "tcp": 7,
             "tls": 7,
             "request": 0,
             "firstByte": 713,
             "download": 1,
             "total": 768
           ***
         ***,
         "message": "Response code 403 (Forbidden)",
         "stack": "HTTPError: Response code 403 (Forbidden)\n    at Request.<anonymous> (/opt/containerbase/tools/renovate/37.173.2/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
         "options": ***
           "headers": ***
             "user-agent": "RenovateBot/37.173.2 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate, br"
           ***,
           "url": "https://europe-southwest1-docker.pkg.dev/v2/token?scope=repository%3AMY_GCP_PROJECT/PATH/TO/HELM_CHART%3Apull&service=europe-southwest1-docker.pkg.dev",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         ***,
         "response": ***
           "statusCode": 403,
           "statusMessage": "Forbidden",
           "body": ***
             "errors": ***
               ***
                 "code": "DENIED",
                 "message": "Unauthenticated request. Unauthenticated requests do not have permission \"artifactregistry.repositories.downloadArtifacts\" on resource \"projects/MY_GCP_PROJECT/locations/europe-southwest1/repositories/charts\" (or it may not exist)"
               ***
             ***
           ***,
           "headers": ***
             "content-type": "application/json; charset=utf-8",
             "x-content-type-options": "nosniff",
             "x-frame-options": "SAMEORIGIN",
             "x-xss-protection": "0",
             "date": "Tue, 06 Feb 2024 02:40:33 GMT",
             "content-length": "283",
             "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000",
             "connection": "close"
           ***,
           "httpVersion": "1.1",
           "retryCount": 0
         ***
       ***

```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above
