### DISCUSSION TITLE
Why is renovate not opening prs to update my helm charts?

### DISCUSSION THREAD

**Discussion by Goltergaul** [renovatebot/renovate#27172] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

37.180.0

### If you're self-hosting Renovate, select which platform you are using.

Bitbucket Server

### What is your question?

We have some helm charts that are outdated but renovate does not update them. In the hostRules config I have the following:

```
{
  "matchHost": "registry.pteng.lnz.k8s.foo.at",
  "hostType": "helm"
}
```

In the debug logs i can see that the helm-chart version is unsupported (see relevant logs) but it also says `versioning=docker` which kinda sounds that it uses the wrong type to parse it? docker instead of helm?

What could be the issue?

the chart.yaml looks like this (the ruby-service dependency is the one that should be updated):

```
apiVersion: v2
name: zendesk-externals
description: ZendeskExternals service
type: application
version: 0.0.0 # This gets overridden by the CI pipeline
appVersion: "0.0.0" # This gets overridden by the CI pipeline
dependencies:
  - alias: zendesk-externals
    name: ruby-service
    version: ">= 8.0 < 9.0"
    repository: "oci://registry.pteng.lnz.k8s.foo.at/base-charts"
```

### Logs (if relevant)

<details><summary>Logs</summary>

```

DEBUG: Dependency registry.pteng.lnz.k8s.foo.at/base-charts/ruby-service has unsupported/unversioned value >= 8.0 < 9.0 (versioning=docker) (repository=BE/foobar)

```

</details>

**Comment by rarkins** [comment]
I've never seen this syntax in use for helm charts before but you might be able to use packageRules.matchPackageName and versioning=npm

For this to be supported automatically we'd need a reproduction repo plus track down a specification of what syntax is supported for this field.

**Reply by Goltergaul** [reply]
thanks that does unfortunately not work, it does not correctly determine the correct current version it seems. (shows 2.0.0 instead of 7.1.5 which is the version in the chart lockfile) I found this somewhere in the logs:

```
           }
             "packageFile": "chart/Chart.yaml"
             "lockFiles": ["chart/Chart.lock"],
             "packageFileVersion": "0.0.0",
             "datasource": "helm",
             ],
               }
                 "currentVersion": "2.0.0"
                 "homepage": "https://stash.foo.com/projects/PT/repos/helm-charts/browse",
                 "registryUrl": "https://registry.pteng.lnz.k8s.foo.at",
                 "sourceUrl": "https://stash.foo.com/projects/PT/repos/helm-charts/browse/charts/ruby-service",
                 "warnings": [],
                 "versioning": "npm",
                 "updates": [],
                 "pinDigests": false,
                 "packageName": "registry.pteng.lnz.k8s.foo.at/base-charts/ruby-service",
                 "datasource": "docker",
                 "currentValue": "< 8.0",
                 "depName": "ruby-service",
               {
             "deps": [
           {
         "helmv3": [
```

I however got it working when using just specifying a specific version, instead of a range. there the npm versioning rule makes it work.

having this:
```
apiVersion: v2
name: sport-types
description: Sport Types service 
type: application
version: "0.0.0"
appVersion: "0.0.0"
dependencies:
  - name: ruby-service
    alias: sport-types
    version: "8.0.0-rc.1"
    repository: "oci://registry.pteng.lnz.k8s.foo.at/base-charts"
```

and the package rule:
```
"packageRules": [
    {
      "matchPackageNames": ["ruby-service"],
      "versioning": "npm"
    }
  ] 
```

i get a pr that updates it correctly to 8.1.3 however the PR title is `Update ruby-service Docker tag to v8.1.3` which makes me think that somehow something is being confused with docker under the hood?
