### DISCUSSION TITLE
Open one Pull Request per occurrence of an upgrade (for the same dependency)

### DISCUSSION THREAD

**Discussion by morremeyer** [renovatebot/renovate#27248] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

37.170.0

### If you're self-hosting Renovate, select which platform you are using.

github.com

### What is your question?

I would like to configure renovate to open one Pull Request per occurrence of a dependency in a certain file.

I _think_ this is the same like the question in #25550, but since #25550 was marked as incomplete by the bot, I opted to open this new question with more information.

The file in question is a Kubernetes manifest (unneeded lines omitted):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - environment: dev-us-east-1
            version: "1.20.2"
          - environment: prod-us-east-1
            version: "1.20.2"
```

<details>
<summary>Using the following configuration (omitted irrelevant settings)</summary>

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "customManagers": [
    {
      "description": "Update Istio version",
      "fileMatch": ["path/to/yaml/above/istio.yaml"],
      "datasourceTemplate": "helm",
      "registryUrlTemplate": "https://istio-release.storage.googleapis.com/charts",
      "depNameTemplate": "istiod",
      "matchStrings": ["version: \"(?<currentValue>.*)\""]
    }
  ],
  "packageRules": [
    {
      "description": "Do not propose updates to .0 versions of istio for stability reasons",
      "matchManagers": ["regex"],
      "matchDepNames": ["istiod"],
      "allowedVersions": "/^[0-9]+\\.[0-9]+\\.[1-9][0-9]*$/",
      "groupName": "istio",
      "draftPR": true,
      "prHeader": ":warning: This is an Istio update! Follow the instructions in [README.md](README.md) for this upgrade :warning:"
    }
  ]
}
```

</details>

This currently opens one PR that updates both `version: "1.20.2"` occurrences to `version: "1.20.3"`. 

However, I would like one PR per occurrence of the dependency.

In some other cases, we were successful using `additionalBranchPrefix` in the package rule, however in this case, since both are the same version, in the same file, etc., there does not seem to be any attribute that we could use here.

I checked the [template fields](https://docs.renovatebot.com/templates/#other-available-fields), but could also not find anything.

### Logs (if relevant)

No relevant log lines yet.
