### DISCUSSION TITLE
How do I override an OCI helm registry in a helmfile release?

### DISCUSSION THREAD

**Discussion by ksappington275** [renovatebot/renovate#27332] [Request Help]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

Running CI/CD off `main` of https://gitlab.com/renovate-bot/renovate-runner

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### What is your question?

I have the following `helmfile.yaml`
```yaml
releases:
  - name: schema-registry
    chart: oci://{{ .Values.registry }}/somechart
    # renovate: datasource=helm depName=bitnamicharts/schema-registry registryUrl=registry-1.docker.io versioning=helm depType=myapp
    version: 16.6.0
```

When renovate runs, it seems to be pulling registry information from the `chart:` line, and ignoring what I'm setting with `registryUrl`

In my CI/CD job logs I get a 401 Unauthorized, and see it's using `"url": "https://index.docker.io/v2/somechart/tags/list?n=10000"`. I wouldn't expect this to ever reference `index.docker.io` or `somechart`

In my `renovate.json` I'm using the following regex manager
```json
  "regexManagers": [
    {
      "fileMatch": [
        "\\.ya?ml(\\.gotmpl)?$"
      ],
      "matchStrings": [
        "renovate: datasource=(?<datasource>.*?) depName=(?<depName>.*?)( registryUrl=(?<registryUrl>.*?))?( versioning=(?<versioning>.*?))?( depType=(?<depType>.*?))?\\s*(version):\\s*(?<currentValue>.*)"
      ],
      "versioningTemplate": "{{#if versioning}}{{{versioning}}}{{else}}semver{{/if}}"
    }
  ],
```
