### DISCUSSION TITLE
Improvement: Artifact update problem with helm

### DISCUSSION THREAD

**Discussion by xrow** [renovatebot/renovate#27522] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest

### If you're self-hosting Renovate, select which platform you are using.

gitlab.com

### Was this something which used to work for you, and then stopped?

I have not seen this working

### Describe the problem

Renovate outputs the following problem:

```
#### Artifact update problem

Renovate failed to update artifacts related to this branch. You probably do not want to merge this MR as-is.


##### File name: chart/charts/myparser/Chart.lock


No tool releases found.
```

```
dependencies:
- name: common
  repository: oci://registry.gitlab.com/xrow-public/helm-schema/charts
  version: 0.0.0
- name: webserver
  alias: netparser
  repository: oci://registry.gitlab.com/xrow-public/helm-webserver/charts
  version: 1.x.x
```

```
dependencies:
- name: common
  repository: oci://registry.gitlab.com/xrow-public/helm-schema/charts
  version: 0.0.0
- name: webserver
  repository: oci://registry.gitlab.com/xrow-public/helm-webserver/charts
  version: 1.2.11
digest: sha256:79c1327f0ff8014d3240ca8807a2ebb010a6e8805b882298850dab50b7447d4c
generated: "2024-02-14T19:25:26.863119825+01:00"
```

All tools have releases. Though I do not know what it is asking for.

Though there is one specialty for chart webserver:

```
version: 0.0.0
dependencies:
- name: common
  version: x.x.x
```

I current beleive is it can`t handle helm version x.x.x.

### Relevant debug logs

<details><summary>Logs</summary>

```

Copy/paste the relevant log(s) here, between the starting and ending backticks

```

</details>

I am sorry I could not get the LOG_LEVEL=debug to work?!

### Have you created a minimal reproduction repository?

Placeholder value, please select the correct response from the dropdown
