### DISCUSSION TITLE
Changes introduced by PR 26811 break Argo CD

### DISCUSSION THREAD

**Discussion by sherif-fanous** [renovatebot/renovate#27617] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

37.212.0

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the problem

[PR 26811](https://github.com/renovatebot/renovate/pull/26811) seems to have introduced an issue where schema validation is failing for Argo CD application manifests

As a result none of the Argo CD application manifests are being checked by the bot.

Interestingly all my Argo CD manifests are `Applications` so I'm not even sure why it's complaining about `ApplicationSet` as these aren't used at all.

I have reverted back to 37.212.0 and everything is working normally again with that version.

### Relevant debug logs

Setting `LOG_LEVEL` to debug I see this error for each Argo CD manifest

```json
       "error": {
         "message": "Schema error",
         "stack": "ZodError: Schema error\n    at Object.get error [as error] (/opt/homebrew/Cellar/renovate/37.218.0/libexec/lib/node_modules/renovate/node_modules/zod/lib/types.js:43:31)\n    at parseYaml (/opt/homebrew/Cellar/renovate/37.218.0/libexec/lib/node_modules/renovate/lib/util/yaml.ts:53:23)\n    at Object.extractPackageFile (/opt/homebrew/Cellar/renovate/37.218.0/libexec/lib/node_modules/renovate/lib/modules/manager/argocd/extract.ts:36:28)\n    at extractPackageFile (/opt/homebrew/Cellar/renovate/37.218.0/libexec/lib/node_modules/renovate/lib/modules/manager/index.ts:75:9)\n    at getManagerPackageFiles (/opt/homebrew/Cellar/renovate/37.218.0/libexec/lib/node_modules/renovate/lib/workers/repository/extract/manager-files.ts:45:43)\n    at /opt/homebrew/Cellar/renovate/37.218.0/libexec/lib/node_modules/renovate/lib/workers/repository/extract/index.ts:57:28\n    at async Promise.all (index 0)\n    at extractAllDependencies (/opt/homebrew/Cellar/renovate/37.218.0/libexec/lib/node_modules/renovate/lib/workers/repository/extract/index.ts:54:26)\n    at extract (/opt/homebrew/Cellar/renovate/37.218.0/libexec/lib/node_modules/renovate/lib/workers/repository/process/extract-update.ts:140:28)\n    at extractDependencies (/opt/homebrew/Cellar/renovate/37.218.0/libexec/lib/node_modules/renovate/lib/workers/repository/process/index.ts:154:26)\n    at Object.renovateRepository (/opt/homebrew/Cellar/renovate/37.218.0/libexec/lib/node_modules/renovate/lib/workers/repository/index.ts:63:9)\n    at attributes.repository (/opt/homebrew/Cellar/renovate/37.218.0/libexec/lib/node_modules/renovate/lib/workers/global/index.ts:200:11)\n    at start (/opt/homebrew/Cellar/renovate/37.218.0/libexec/lib/node_modules/renovate/lib/workers/global/index.ts:185:7)\n    at /opt/homebrew/Cellar/renovate/37.218.0/libexec/lib/node_modules/renovate/lib/renovate.ts:18:22",
         "issues": {
           "kind": "Invalid literal value, expected \"ApplicationSet\"",
           "spec": {
             "sources": {"1": {"targetRevision": "Required"}},
             "template": "Required"
           }
         }
       },
```

Here's a sample Argo CD manifest that's in my repo

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '0'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: sops-secrets-operator
  namespace: argo-cd
spec:
  destination:
    namespace: sops
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sops-secrets-operator
    repoURL: https://isindir.github.io/sops-secrets-operator
    targetRevision: 0.18.3
  sources:
    - chart: sops-secrets-operator
      helm:
        valueFiles:
          - $root/kubernetes/apps/sops-secrets-operator/helm/values/base/helm-sops-secrets-operator-values.yaml
      repoURL: https://isindir.github.io/sops-secrets-operator
      targetRevision: 0.18.3
    - ref: root
      repoURL: git@github.com:<redacted>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
```

### Have you created a minimal reproduction repository?

Placeholder value, please select the correct response from the dropdown
