### DISCUSSION TITLE
disabling a datasource for a manager

### DISCUSSION THREAD

**Discussion by dunn** [renovatebot/renovate#27690] [Request Help] [answered]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

v37.224.1

### If you're self-hosting Renovate, select which platform you are using.

Gitea or Forgejo

### What is your question?

Is it possible to disable a datasource for a given manager?  My use case is: I have renovate set to update the dependencies of a Helm chart:
```yaml
dependencies:
  - name: postgresql
    version: 13.4.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: minio
    version: 13.1.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: minio.enabled
```
However, because these are OCI repositories, renovate uses the Docker datasource when updating them, and as a consequence does not update the associated `Chart.lock`.  To work around this, I tried to force renovate to use the helm datasource with a custom manager:
```json
  "customManagers": [
    {
      "customType": "regex",
      "datasourceTemplate": "helm",
      "fileMatch": ["^chart/Chart\\.yaml$"],
      "matchStrings": ["name:\\s+(?<depName>[^\\s]+)\\n\\s*version:\\s+(?<currentValue>[^\\s]+)\\n"]
    }
  ],
  "packageRules": [
    {
      "matchDatasources": ["helm"],
      "matchManagers": ["custom.regex"],
      "matchPackageNames": [
        "postgresql",
        "minio"
      ],
      "registryUrls": ["https://charts.bitnami.com/bitnami"]
    }
```
but the docker source seems to take precedence, and this doesn't result in MRs with updated `Chart.lock`

### Logs (if relevant)

<details><summary>Logs</summary>

```

Copy/paste the relevant log(s) here, between the starting and ending backticks

```

</details>
