### DISCUSSION TITLE
Argocd manager not able to parse yaml wrapped in a helm flow control

### DISCUSSION THREAD

**Discussion by lstoeferle** [renovatebot/renovate#27762] [Request Help] [answered]
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab

### Please tell us more about your question or problem

Hi everyone,
we recently ran into a small issue, where Renovate is not able to [parse `argocd` yaml-files](https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/argocd/extract.ts#L36), that are wrapped in a helm flow control like in the following example.

```yaml
{{- if .Values.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  source:
    chart: kube-state-metrics
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 2.4.1
{{- end }}
```

It looks like the current [schema configuration](https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/argocd/schema.ts) can not handle this type of yaml-file, which leads to a parsing failure where the file is skipped silently (only visible via `LOG_LEVEL=debug`).

### Logs (if relevant)

<details><summary>Logs</summary>

```

DEBUG: Failed to parse ArgoCD definition. (repository=gitops, baseBranch=main, packageFile=argocd/templates/application.yaml)
       "err": {
         "name": "YAMLException",
         "reason": "missed comma between flow collection entries",
         "mark": {
           "name": null,
           "buffer": "****",
           "position": 2,
           "line": 0,
           "column": 2,
           "snippet": " ****"
       }

```

</details>
