### DISCUSSION TITLE
Helm / Helmfiles that are using OCI repositories that have / in the chart name fails on isValidChartName()

### DISCUSSION THREAD

**Discussion by webdz9r** [renovatebot/renovate#27808] [Request Help]
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

gitLab

### Please tell us more about your question or problem

Running into an issue when parsing a helmfile dependencies - We're using Harbor for chart storage and use folder names `team/name/chart` for organization. 

renovate skips repos when the chart name `chart: sre/node-labller` has `/` in it on this function `isValidChartName()`

```
bases:
  - configs/environments.yaml

repositories:
  - name: our-private-repo
    url: harbor.internal-domain.com
    oci: true
  - name: jetstack
    url: https://charts.jetstack.io
  
releases:
  - name: node-labeller
    namespace: kube-system
    version: 0.1.1
    condition: node-labeller.enabled
    chart: sre/node-labeller

  - name: metallb
    namespace: metallb-system
    version: 0.1.3
    condition: metallb.enabled
    chart: sre/charts/metallb

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.11.0
    condition: cert-manager.enabled
```

### Logs (if relevant)

<details><summary>Logs</summary>

```

"deps": [
               {
                 "depName": "sre/node-labeller",
                 "currentValue": "0.1.1",
                 "registryUrls": ["harbor.private-repo.com"],
                 "datasource": "docker",
                 "packageName": "harbor.private-repo.com/sre/node-labeller",
                 "skipReason": "unsupported-chart-type",
                 "updates": []
               },
               {
                 "depName": "sre/charts/metallb",
                 "currentValue": "0.1.3",
                 "registryUrls": ["harbor.private-repo.com"],
                 "datasource": "docker",
                 "packageName": "harbor.private-repo.com/sre/charts/metallb",
                 "skipReason": "unsupported-chart-type",
                 "updates": []
               },
               {
                 "depName": "cert-manager",
                 "currentValue": "v1.11.0",
                 "registryUrls": ["https://charts.jetstack.io/"],
                 "updates": [
                   {
                     "bucket": "non-major",
                     "newVersion": "v1.14.3",
                     "newValue": "v1.14.3",
                     "newDigest": "3126d0253ec8b0456e0db924cc3e71b24e51f1e66914218ca39ebb606aff0438",
                     "releaseTimestamp": "2024-02-23T09:22:48.014Z",
                     "newMajor": 1,
                     "newMinor": 14,
                     "updateType": "minor",
                     "branchName": "renovate/cert-manager-1.x"
                   }
                 ],
                 "packageName": "cert-manager",
                 "versioning": "helm",
                 "warnings": [],
                 "sourceUrl": "https://github.com/cert-manager/cert-manager",
                 "registryUrl": "https://charts.jetstack.io/",
                 "currentVersion": "v1.11.0",
                 "isSingleVersion": true,
                 "fixedVersion": "v1.11.0"
               }
             ],

```

</details>
