### DISCUSSION TITLE
Renovate should update the chart version along with image versions

### DISCUSSION THREAD

**Discussion by rajat2911** [renovatebot/renovate#28038] [Request Help] [answered]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Github

### Please tell us more about your question or problem

Hi Team , 

I have a scenario where renovate fetches the chart version and shows me an update for chart version upgrade 

```
  - name: keda-operator
    namespace: keda-operator
    chart: kedacore/keda
    installed: true
    version: 2.12.1
    dependencies:
      - chart: incubator/raw
        version: 0.1.0
```
 with this  Renovate Configuration :
 ```
 {
  $schema: 'https://docs.renovatebot.com/renovate-schema.json',
  extends: [
    'config:best-practices',
  ],
  versioning: 'hashicorp',
  'helm-values': {
    fileMatch: [
      '\\.gotmpl$',
      'argocd_values.yaml',
      'argocd.yaml',
    ],
    versioning: 'docker',
    ignorePaths: [
      'helmfiles/abc.yaml.gotmpl',
      'charts/values.yaml',
    ],
  },
  customManagers: [
    {
      customType: 'regex',
      fileMatch: [
        '^\\.tool-versions$',
      ],
      matchStrings: [
        'terraform\\s+(?<currentValue>\\S+)',
      ],
      depNameTemplate: 'hashicorp/terraform',
      datasourceTemplate: 'github-releases',
    },
    {
      customType: 'regex',
      fileMatch: [
        'scripts/argocd-bootstrap.sh',
      ],
      matchStrings: [
        'export \w+_VERSION=(?<currentValue>[0-9.]+)\s+# renovate: depName=(?<depName>[^ \\n]+) +(extractVersion=(?<extractVersion>[^\\n]+))?',
      ],
      datasourceTemplate: 'github-releases',
    },
  ],
  minimumReleaseAge: '3 days',
  internalChecksFilter: 'strict',
  rebaseWhen: 'behind-base-branch',
  prBodyColumns: [
    'Package',
    'Update',
    'Type',
    'Change',
    'Package file',
  ],
  packageRules: [
    {
      matchDepTypes: [
        'action',
      ],
      extractVersion: '^(?<version>v\\d+\\.\\d+\\.\\d+)$',
      versioning: 'regex:^v(?<major>\\d+)(\\.(?<minor>\\d+)\\.(?<patch>\\d+))?$',
    },
    {
      matchPackageNames: [
        'argoproj/argo-helm',
      ],
      prBodyNotes: [
        'warning: Please consult the SRE team before merging this PR. ArgoCD might break if there is a mismatch between the chart version, and the app version, so for now this has to be done delicately while we figure out a way to improve this',
      ],
      reviewers: [
        'xxxx',
        'xxxx',
      ],
    },
    {
      matchPackageNames: [
        'terraform',
      ],
      matchManagers: [
        'asdf',
      ],
      enabled: false,
    },
    {
      groupName: 'Google Terraform Providers',
      groupSlug: 'terraform-google',
      matchPackageNames: [
        'hashicorp/google',
        'hashicorp/google-beta',
      ],
    },
  ],
}
```    
The ask is while updating the chart version it should also update the image dependencies which are compatible with new chart version . 
```
image:
  keda:
    repository: xxxxxx
    tag: "xxxx"
  metricsApiServer:
    repository: xxxx
    tag: "xxxxx"
  webhooks:
    repository: xxxxx
    tag: "xxxxx"
  pullPolicy: IfNotPresent
  ```
  is this possible to achieve ?

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
