### DISCUSSION TITLE
Unable to fetch Keda dependencies

### DISCUSSION THREAD

**Discussion by rajat053117** [renovatebot/renovate#28044] [Request Help]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Github 

### Please tell us more about your question or problem

I am using a simple renovate.json file given below to fetch the keda dependencies 

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:best-practices"
  ],
  "helm-values": {
    "fileMatch": [
      "keda.yaml.gotmpl$"
    ],
    "versioning": "docker"
  }
}
```
This is my keda.yaml.gotmpl , for ex:
```
image:
  keda:
    repository: europe-west2-docker.pkg.dev/renovatetests/renovate/docker-mirror--keda
    tag: "2.12.0@sha256:xxxxxxxxxxxxxxxx"
```
This does not help to fetch the dependencies , i understand the format for helm-values doesn't support it as given [here](https://docs.renovatebot.com/modules/manager/helm-values/)
My question is how can i have this working 
Many thanks in Advance :thanks

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
