### DISCUSSION TITLE
custom regex not working to fetch the docker images

### DISCUSSION THREAD

**Discussion by rajat053117** [renovatebot/renovate#28056] [Request Help]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Github

### Please tell us more about your question or problem

Using the below Renovate.json to fetch the docker image 
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:best-practices"
  ],
  "helm-values": {
    "fileMatch": [
      "keda.yaml.gotmpl$"
    ],
    "versioning": "docker"
  }
}
```
ked.yaml.gotmpl is 
```
image:
  keda:
    repository: europe-west2-docker.pkg.dev/renovatetests/renovate/docker-mirror--keda
    tag: "2.12.0@sha256:xxxxxxxxxxxxxxxx"
```

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
