### DISCUSSION TITLE
Support OCI charts from public ECR in helmfile

### DISCUSSION THREAD

**Discussion by ahmad-hamade** [renovatebot/renovate#28181] [Request Help]
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Mend Renovate hosted app on github.com

### Please tell us more about your question or problem

I am utilizing Helmfile to install Karpenter from the official ECR OCI registry of Karpenter. However, Renovate Dashboard is issuing a warning: `Renovate failed to look up the following dependencies: Failed to look up Helm package karpenter.`.

<img width="732" alt="image" src="https://github.com/renovatebot/renovate/assets/11910802/6737955f-a2df-4088-8b1a-6356a45d1100">

Here is a snippet of my Helmfile for reference:
```yaml
repositories:
  - name: karpenter
    url: public.ecr.aws/karpenter
    oci: true
---
releases:
  - name: karpenter
    chart: karpenter/karpenter
    version: 0.35.1
    namespace: kube-system
    installed: true
    atomic: true
```
