### DISCUSSION TITLE
Help With Setting Up Renovate With Helm

### DISCUSSION THREAD

**Discussion by zopa-danny-lyubenov** [renovatebot/renovate#28348] [Request Help]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Github Enterprise, Renovate - 37.280.1

### Please tell us more about your question or problem

I am running ArgoCD to deploy my Helm charts and I am trying to setup Renovate to bump the version of Prometheus and any other chart.

**Chart.yaml**
```
chart:
  name: prometheus
  version: 25.17.0
  repo: <artifactory>/helm-remote-prometheus-community
values:
  global:
    zopa:
      prometheus:
        name: &prometheusName prometheus
        host: &prometheusEndpoint <endpoint>
....
```

**renovate.json**
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "gitAuthor": "Renovate Bot <renovate-bot@mycompany.com>",
  "extends" : [
    "config:recommended",
    ":prConcurrentLimitNone",
    ":prHourlyLimitNone",
    ":rebaseStalePrs",
    "regexManagers:dockerfileVersions"
  ],
  "registryAliases": {
    "stable": "https://charts.helm.sh/stable"
  },
  "regexManagers": [
    {
      "description": "k8s-spot-termination-handler",
      "fileMatch": ["^Helm\\/Chart\\.yaml$"],
      "matchStrings": [
        "version:\\s+(?<currentValue>.*)"
      ],
      "depNameTemplate": "stable/k8s-spot-termination-handler",
      "datasourceTemplate": "helm"
    }
  ]
}
```

**config.js**
```
module.exports = {
  endpoint: '<github enterprise>',
  token: 'XXXXX',
  platform: 'github',
  logLevel: 'debug',
  onboardingConfig: {
    extends: ['config:best-practices'],
  },
  repositories: ['test/repo'],
  onboarding: true,
  dryRun : false,
  printConfig: true,
};
```

repo structure
`Repo/Helm/Chart.yaml`

I am struggling to understand what makes the mapping between the Chart.yaml and checking for a new version of the Helm chart. Any help will be much appreciated.

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
