### DISCUSSION TITLE
gitlabci/gitlabci-include does not honor ignorePaths

### DISCUSSION THREAD

**Discussion by JMLX42** [renovatebot/renovate#28430] [Request Help]
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab, 37.279.0

### Please tell us more about your question or problem

Hi,

We have a tool that generates a bunch of package files. Including:

- a `docker-compose.yml`
- some GitLab CI files

Those package files and the corresponding updates are maintained in the source of that tool.
So we want Renovate to ignore those package files in other repos.
For that, we use the following:

```json
  "ignorePaths": [
    "**/smartshape/env/*/target/**/*"
  ],
```

## Expected Result

-  :heavy_check_mark: `smartshape/env/prod/target/docker-compose/docker-compose.yml` is ignored
-  :heavy_check_mark: `smartshape/env/prod/target/docker-compose/gitlab-ci/.gitlab-ci.yml` is ignored
-  :heavy_check_mark: `smartshape/env/prod/target/docker-compose/gitlab-ci/SmartShape.gitlab-ci.yml` is ignored

## Actual Result

-  :heavy_check_mark: `smartshape/env/prod/target/docker-compose/docker-compose.yml` is ignored
-  :heavy_check_mark: `smartshape/env/prod/target/docker-compose/gitlab-ci/.gitlab-ci.yml` is ignored
-  :x: `smartshape/env/prod/target/docker-compose/gitlab-ci/SmartShape.gitlab-ci.yml` is **not** ignored

I think the problems come from the fact that:

1. `/.gitlab-ci-yml` includes `/smartshape/env/prod/target/docker-compose/gitlab-ci/.gitlab-ci.yml`, which includes `/smartshape/env/prod/target/docker-compose/gitlab-ci/SmartShape.gitlab-ci.yml`

<details>

<summary>/.gitlab-ci-yml</summary>

```yml
include: 'smartshape/env/prod/target/docker-compose/gitlab-ci/SmartShape.gitlab-ci.yml'

preflight-checks-prod:
  extends:
    - .image-ubuntu-template
    - .preflight-checks-prod-template
  allow_failure: false

validate-cluster-prod:
  extends:
    - .image-ubuntu-template
    - .validate-cluster-prod-template
  allow_failure: false

deploy-prod:
  extends:
    - .image-ubuntu-template
    - .deploy-prod-template
  allow_failure: false
  needs:
    - preflight-checks-prod
    - validate-cluster-prod
```

</details>
<details>

<summary>/smartshape/env/prod/target/docker-compose/gitlab-ci/.gitlab-ci.yml</summary>

```yml
include: 'smartshape/env/prod/target/docker-compose/gitlab-ci/SmartShape.gitlab-ci.yml'

preflight-checks-prod:
  extends:
    - .image-ubuntu-template
    - .preflight-checks-prod-template
  allow_failure: false

validate-cluster-prod:
  extends:
    - .image-ubuntu-template
    - .validate-cluster-prod-template
  allow_failure: false

deploy-prod:
  extends:
    - .image-ubuntu-template
    - .deploy-prod-template
  allow_failure: false
  needs:
    - preflight-checks-prod
    - validate-cluster-prod
```

</details>
<details>

<summary>/smartshape/env/prod/target/docker-compose/gitlab-ci/SmartShape.gitlab-ci.yml</summary>

```yml
.image-ubuntu-template:
  image: ubuntu:20.04
  before_script:
    - apt-get update && apt-get install -y openssh-client rsync

.deploy-prod-template:
  stage: deploy
  when: manual
  allow_failure: false
  environment:
    name: 'prod'
    url: 'https://cloud.smartshape.com'
    action: start
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - bash smartshape/env/prod/target/docker-compose/gitlab-ci/deploy.sh || exit $?

.preflight-checks-prod-template:
  allow_failure: false
  environment:
    name: 'prod'
    url: 'https://cloud.smartshape.com'
    action: verify
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - bash smartshape/env/prod/target/docker-compose/gitlab-ci/preflight-checks.sh || exit $?

.validate-cluster-prod-template:
  allow_failure: false
  script:
    - bash smartshape/env/prod/target/docker-compose/gitlab-ci/validate-cluster.sh || exit $?
```

</details>

2. `ignorePaths` is not taken into account when evaluating GitLab CI includes

It is also worth noting the unwanted file is somehow detected as a `gitlabci` dependency, instead of a `gitlabci-include` dependency:

![image](https://github.com/renovatebot/renovate/assets/998703/4878a382-c8c0-44d4-a4be-45789d08d9a5)
