### DISCUSSION TITLE
Identifying Helm OCI charts in skaffold.yaml using regex customManager

### DISCUSSION THREAD

**Discussion by chinmaya-n** [renovatebot/renovate#28488] [Request Help] [answered]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitHub

### Please tell us more about your question or problem

When using `skaffold.yaml` to deploy Helm OCI charts, I'm facing a problem to properly identify the dependency, repositoryURL etc. I'm using regex customManager because skaffold.yaml doesn't have its own manager (yet). Below is an example of a skaffold file which uses an OCI helm chart to deploy the application. I believe the problem is, I'm unable to identify proper names for the capture groups and the datasource for this task.

``` yaml
apiVersion: skaffold/v4beta10
kind: Config
deploy:
  helm:
    releases:
    - name: gha-runner-scale-set-controller
      remoteChart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
      valuesFiles:
        - values-arc.yaml
      namespace: gha-controller
      createNamespace: true
      version: 0.9.0
      upgradeOnChange: true
    - name: gha-runner-scale-set
      remoteChart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
      valuesFiles:
        - values-runner-scale-set.yaml
      namespace: gha-runners
      createNamespace: true
      version: 0.9.0
      upgradeOnChange: true
```

Here is the regex customManager config:

``` json
{
"customManagers": [
        {
            "customType": "regex",
            "fileMatch": ["^skaffold.yaml$"],
            "matchStrings": [
                "\\s+remoteChart:\\s+(?<repositoryURL>oci:\/\/(?<registryHost>.*?)\/.*)\/(?<depName>.*?)\\s+(.|\\s)*?version:\\s+('|\")?(?<currentValue>.*?)('|\")?\\s+"
            ],
            "datasourceTemplate": "helm"
        }
    ]
}
```

I tried multiple regex match strings (some are below) and also tried both `helm` and `docker` as the datasource without any luck. All I get is "Package lookup failures". Here is a [saved regex101 search](https://regex101.com/r/qDcssb/1) link to quickly validate the match strings.

* `\s+remoteChart:\s+(?<registryUrl>oci:.*\/(?<depName>.*?))\s+(.|\s)*?version:\s+('|")?(?<currentValue>.*?)('|")?\s+`
* `\s+remoteChart:\s+(?<registryUrl>oci:.*)\/(?<depName>.*?)\s+(.|\s)*?version:\s+('|")?(?<currentValue>.*?)('|")?\s+`
* `\s+remoteChart:\s+(?<registryUrl>oci:\/\/(?<registryHost>.*?)\/(?<dockerRepository>.*))\/(?<depName>.*?)\s+(.|\s)*?version:\s+('|")?(?<currentValue>.*?)('|")?\s+`
* `\s+remoteChart:\s+oci:\/\/(?<registryHost>.*?)\/(?<dockerRepository>.*)\/(?<depName>.*?)\s+(.|\s)*?version:\s+('|")?(?<currentValue>.*?)('|")?\s+`
* `\s+remoteChart:\s+(?<repositoryURL>oci:\/\/(?<registryHost>.*?)\/.*)\/(?<depName>.*?)\s+(.|\s)*?version:\s+('|")?(?<currentValue>.*?)('|")?\s+`

I failed to find any appropriate documentation around this. I would appreciate any pointers regarding this.

### Logs (if relevant)

<details><summary>Logs</summary>

```
WARN: Package lookup failures (repository=*****/k8s-github-arc)                                                                                                                
       "warnings": [                                                                                                                                                                  
         "Failed to look up helm package gha-runner-scale-set-controller",                                                                                                            
         "Failed to look up helm package gha-runner-scale-set"                                                                                                                        
       ],
```

</details>
