### DISCUSSION TITLE
Variable creation in renovate.json

### DISCUSSION THREAD

**Discussion by olvap377** [renovatebot/renovate#28534] [Request Help] [answered]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Gitlab Latest via Pipeline

### Please tell us more about your question or problem

Love renovate, working great, I am using a custom regex manager to play nice with some argocd we use. The regex manager works great and updates the correct line as needed. 

What I am wondering is in Argo we use generators for our various clusters/deployments. Currently with my regex manager it opens a PR for each match it finds which is great except the name of the MR is the same for each. I would like to leverage `commitMessageSuffix` to add a differentiator at the end of the PR title. (i.e. tier or cluster name). This info is already available in the same yaml that the regex manager is working with.

The ask: is there a way to use matchstring or something to save a particular value using regex to a variable in the renovate.json so we can insert it into `commitMessageSuffix` so that way we can see right away in the PR list which cluster the PR corresponds to?

Current argo yaml using generators
```
  generators:
  - list:
      elements:
      - clustername: in-cluster
        clusterpath: tools
        chartversion: 0.15.31 # renovate: depName=DataDog/helm-charts extractVersion=^synthetics-private-location-(?<version>.+)$
        tier: non-prod
      - clustername: in-cluster
        clusterpath: tools
        chartversion: 0.15.31 # renovate: depName=DataDog/helm-charts extractVersion=^synthetics-private-location-(?<version>.+)$
        tier: prod
      - clustername: om-pensions-dev
        clusterpath: dev
        chartversion: 0.15.31 # renovate: depName=DataDog/helm-charts extractVersion=^synthetics-private-location-(?<version>.+)$
        tier: non-prod
      - clustername: om-pensions-prod
        clusterpath: prod
        chartversion: 0.15.31 # renovate: depName=DataDog/helm-charts extractVersion=^synthetics-private-location-(?<version>.+)$
        tier: prod
```

so ideally we would specify regex to match `clusterpath` and that value we would append to the PR title

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
