### DISCUSSION TITLE
Support BitBucket Pipeline pipes

### DISCUSSION THREAD

**Discussion by alumni** [renovatebot/renovate#28586] [Suggest an Idea]
### Tell us more.

BitBucket pipes are nothing more than docker images. It would be nice if they could be updated like the rest of the docker images.

The `pipe` property can either point to:
- another BitBucket repository. E.g.: pipes like `atlassian/trigger-pipeline:5.5.1` should use the docker image specified in `https://bitbucket.org/atlassian/trigger-pipeline/raw/5.5.1/pipe.yml`, which is `bitbucketpipelines/trigger-pipeline:5.5.1`.
- a full URL to a docker image (needs to start with `docker://`).

Example `bitbucket-pipelines.yml`:
```yaml
pipelines:
  default:
    - step:
      script:
        - pipe: atlassian/trigger-pipeline:5.5.1
          variables:
            CUSTOM_PIPELINE_NAME: 'test'
            ...
        - pipe: docker://registry.redhat.io/rhel9/test:0.1.0 
```

More info:
- https://support.atlassian.com/bitbucket-cloud/docs/what-are-pipes/
- https://support.atlassian.com/bitbucket-cloud/docs/write-a-pipe-for-bitbucket-pipelines/
- https://bitbucket.org/product/features/pipelines/integrations
