### DISCUSSION TITLE
Keep indentation in yaml?

### DISCUSSION THREAD

**Discussion by na-jakobs** [renovatebot/renovate#28583] [Request Help] [answered]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitHub

### Please tell us more about your question or problem

I am trying to update my helm `values.yaml` file that has this format:

```yaml
kubeStateMetrics:
  image:
    repository: oss/kubernetes/kube-state-metrics
    tag: v2.10.1
    digest: sha256:60d22fe400d408402c0ffd6394da668b87d402bbdf2f85318c8c832fc2174eb5
```

This is almost works but the indentation is not kept after the PR is created. Here is my config:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "regex": {
    "pinDigests": true
  },
  "enabledManagers": [
    "custom.regex"
  ],
  "branchConcurrentLimit": 10,
  "prConcurrentLimit": 10,
  "prHourlyLimit": 5,
  "customManagers": [
    {
      "customType": "regex",
      "fileMatch": [
        "^values\\.yaml$",
        "kubernetes/(.*)/values.yaml$",
        "kubernetes/(?:[^/]+/)*values.yaml$"
      ],
      "matchStrings": [
        "image:\\n\\s+repository: (?<depName>\\S+)\\n\\s+tag: (?<currentValue>\\S+)\\n\\s+digest: (?<currentDigest>sha256:[a-f0-9]+)"
      ],
      "datasourceTemplate": "docker",
      "versioningTemplate": "docker"
    }
  ]
}
```

The PR that is created:

![image](https://github.com/renovatebot/renovate/assets/64911732/c234b94d-03c0-4665-90a4-e9d1acad2a99)

How can I fix this and add 4 whitespaces?

### Logs (if relevant)

n/a
