### DISCUSSION TITLE
Authentication failure with local gitlab runner

### DISCUSSION THREAD

**Discussion by robin-ln** [renovatebot/renovate#28709] [Request Help] [answered]
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

https://gitlab.com/renovate-bot/renovate-runner/-/blob/main/templates/renovate.gitlab-ci.yml#L10

### Please tell us more about your question or problem

I've reached the limit of GitLab CI's free tier, so I decided to set up a local GitLab Runner on macOS:

```bash
brew install gitlab-runner
gitlab-runner register --url https://gitlab.com --token *********
```

Now, I'm starting a new pipeline. For my GitLab setup with Renovate, I'm using:

```yaml
include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate.gitlab-ci.yml'

renovate:
  stage: 🤖 bot
  variables:
    RENOVATE_GIT_AUTHOR: "Renovate Bot <bot@renovateapp.com>"
    RENOVATE_EXTRA_FLAGS: "$CI_PROJECT_PATH"
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
```

I've set the environment variable `RENOVATE_TOKEN` with all the necessary permissions.

However, when I run the job using [my local GitLab Runner](https://gitlab.com/robin.louarn/monorepo-test/-/jobs/6733044087), I encounter this error:

```plaintext
FATAL: Authentication failure
INFO: Renovate was run at log level "info". Set LOG_LEVEL=debug in environment variables to see extended debug logs.
INFO: Renovate is exiting with a non-zero code due to the following logged errors:
  "loggerErrors": [
    {
      "name": "renovate",
      "level": 60,
      "logContext": "5EJbINx2PFSSBplMAFnse",
      "msg": "Authentication failure"
    }
  ]
```

Can you explain what mistake I made? Why does it work on the GitLab Runner but fail on my local runner?

### Logs (if relevant)

[artifacts.zip](https://github.com/renovatebot/renovate/files/15141253/artifacts.zip)
