### DISCUSSION TITLE
Automerge automerging major updates when it shouldn't

### DISCUSSION THREAD

**Discussion by naanlizard** [renovatebot/renovate#28747] [Request Help]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

None

### Please tell us more about your question or problem

I've got a private gitlab instance (self hosted) and am using renovate-runner to update an old project.

I told renovate-runner to not automerge major versions (I think) with the renovate.json in the repository, below, and I'm also including the renovate-runner repo's .gitlab-ci.yml. 

It merges minor stuff, which is good, but also major patches like this

| Package | Type | Update | Change |
|---|---|---|---|
| [optimize-css-assets-webpack-plugin](https://github.com/NMFR/optimize-css-assets-webpack-plugin) | dependencies | major | [`^5.0.3` -> `^6.0.0`](https://renovatebot.com/diffs/npm/optimize-css-assets-webpack-plugin/5.0.8/6.0.1) |

It also shows some MRs as "major" in the title, but others not. All of them have "Automerge: enabled" in the description

I assume I'm doing something wrong, but I'm unsure what. Would love a hand

```yaml
include:
  - remote: 'https://gitlab.com/renovate-bot/renovate-runner/-/raw/main/templates/renovate.gitlab-ci.yml'

renovate:
  variables:
    RENOVATE_AUTODISCOVER: 'true'
    RENOVATE_AUTODISCOVER_FILTER: 'group/**'
    RENOVATE_PR_HOURLY_LIMIT: 0
    RENOVATE_PLATFORM_AUTOMERGE: true
    RENOVATE_AUTOMERGE_TYPE: branch
    RENOVATE_AUTOMERGE: true
```

{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:best-practices"
  ],
  "packageRules": [
    {
      "matchUpdateTypes": ["minor", "patch", "pin", "digest"],
      "automerge": true
    }
  ]
}

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
