### DISCUSSION TITLE
Cargo source replacement doesn't work correctly

### DISCUSSION THREAD

**Discussion by thian002** [renovatebot/renovate#28752] [Request Help] [answered]
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Self-hosted

### Please tell us more about your question or problem

Hello! Renovate currently supports source replacement if it is defined as follows:
```toml
[registries.my-vendor-source]
index = "https://example.com/path/to/index"

[source.crates-io]
replace-with = "my-vendor-source"
```

However, the way that the [cargo book](https://doc.rust-lang.org/cargo/reference/source-replacement.html) suggests to do source replacement is:
```toml
[source.my-vendor-source]
registry = "https://example.com/path/to/index"

[source.crates-io]
replace-with = "my-vendor-source"
```

I was not able to get the above config to work. If I'm understanding correctly, I believe [this](https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/cargo/extract.ts#L194-L204) code should be modified to support getting the source registry index for this to work

### Logs (if relevant)

<details><summary>Logs</summary>

DEBUG: Replacing index of cargo registry crates-io with cargo-source-replacement
DEBUG: cargo-source-replacement cargo registry is missing index
DEBUG: cargo-source-replacement cargo registry is missing index
DEBUG: Replacing index of cargo registry crates-io with cargo-source-replacement
DEBUG: cargo-source-replacement cargo registry is missing index

</details>
