### DISCUSSION TITLE
How fix warning The \"autodiscover\" option is a global option reserved only for Renovate's global configuration and cannot be configured within a repository's config file.?

### DISCUSSION THREAD

**Discussion by fhg-isi** [renovatebot/renovate#28820] [Request Help] [answered]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitHub

### Please tell us more about your question or problem

I trigger renovate with a GitHub workflow and have autodiscover enabled in a .github/renovate.json5 configuration file. 

When the workflow is running, I get a warning:

```
WARN: Found renovate config warnings (repository=fraunhofer-isi/micat)
       "warnings": [
         {
           "topic": "Configuration Error",
           "message": "The \"autodiscover\" option is a global option reserved only for Renovate's global configuration and cannot be configured within a repository's config file."
         }
       ]
```

However, if I remove the autodiscover option from the configuration, the repository is not found. 

=> What is the recommended way to start renovate and configure it correctly, so that the repository is found and no warning is shown? The GitHub app does not seem to have an option to specify a global config file?

https://github.com/fraunhofer-isi/micat/actions/runs/8938338117/job/24552268761

.github/workflows/renovate.yml:

```
name: renovate
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: self-hosted renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: ./.github/renovate.json5         
          
```

.github/renovate.json5:

{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:recommended",
    ":disableDependencyDashboard"
  ],
  "forkProcessing": "enabled",
  "autodiscover": true,
  "packageRules": [
    {
     "description": "lockFileMaintenance",
     "matchUpdateTypes": [
       "pin",
       "digest",
       "patch",
       "minor",
       "major",
       "lockFileMaintenance"
     ],
     "automerge": true,
     "automergeType": "branch",
     "ignoreTests": true, // set to false if you want updates only to be installed if tests pass
     "dependencyDashboardApproval": false,
     "minimumReleaseAge": null
    }
  ]
}

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>

**Comment by rarkins** [comment]
You are using a repo config filename by mistake. You should be putting these settings in a global config file, such as config.js or config.json. Almost any file name would work, but do not use one of the reserved repo config file names

**Reply by fhg-isi** [reply]
Thank you. Where should that global config file be located for my github organization/App? In an extra repository? Or is "global" still ment in the scope of a single repository?

I enabled the GitHub App explicitly for some repositories. However, without autodiscover they are still not found when running my workflow. 

![image](https://github.com/renovatebot/renovate/assets/76424482/47c391a5-6d25-4585-bb72-4f6169738a16)

**Reply by rarkins** [reply]
Simply rename the file

**Reply by fhg-isi** [reply]
Thank you for the suggestion. I guess I still did not understand the concept at all.  What is the purpose of the repository configuration file in a setup where I use the GitHub App? My assumption was that it should be named renovate.json or renovate.json5, so that it can be found automatically by convention. (And I would expect to adapt global settings in the GitHub App.)

Unfortunately, `.github/renovate.json5` is not automatically found by the workflow action `renovatebot/github-action@v40.1.11`. 
That's why I explicitly specified the path. 

Do you suggest to 
a) Have a single "global" configuration file ".github/config.js" in each repository?
b) Have two configuration files in each repository, one "global" and one "repository" config file?
c) Have a repository configuration file in each respository and put a "global" config file somewher else?  
d) Other?

**Reply by rarkins** [reply]
Please read https://docs.renovatebot.com/config-overview/

**Reply by fhg-isi** [reply]
Thank you. I found the possibility to use env variables for global options there. Unfortuntately, the documentation does not have sections on how global and repository configurations relate to the GitHub App and the workflow action renovatebot/github-action.

Are you saying, that the configurationFile option of renovatebot/github-action  should always point to a "global" configuration file and not to a  "repository" configuration file? Maybe the doc at https://github.com/renovatebot/github-action?tab=readme-ov-file#configurationfile is misleading.

**Reply by rarkins** [reply, marked as answer]
Yes, it should point to a global configuration file. I agree with you that the wording of the first dot point you referenced seems misleading:

![image](https://github.com/renovatebot/renovate/assets/6311784/880456d7-2882-4429-9b80-3d1a788e8f02)

@viceice wdyt?

**Reply by viceice** [reply]
sounds good

**Reply by rarkins** [reply]
https://github.com/renovatebot/github-action/pull/835

**Comment by fhg-isi** [comment]
Using an extra envrionment option `RENOVATE_AUTODISCOVER` in the workflow file did the trick:

```
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: ./.github/renovate.json5
        env:
          RENOVATE_AUTODISCOVER: true
```

If there is a differnt solution that should be used as best practice, please let me know.
