### DISCUSSION TITLE
Wrong image tag being suggested in MR

### DISCUSSION THREAD

**Discussion by cuspofaries** [renovatebot/renovate#28847] [Request Help] [answered]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab

### Please tell us more about your question or problem

Hi,

Renovate creates MR suggesting to use different Tag type than the one is use.

I'am using "apache-bullseye" image flavor however Renovate opens MR based on "vanilla" flavor.

Is my DepName wrong ?

Here is a snippet of my .gitlab-ci.yml:

```yaml
variables:
  DOCKER_IMAGE_NAME:
    value: 'php'
  DOCKER_IMAGE_TAG: 
    # renovate: datasource=docker depName=library/php
    value: '7.4.33-apache-bullseye'
```

**The renovate.json file in the repository to minitor:**

```
{
  "regexManagers": [
	{
	  "fileMatch": [".gitlab-ci\\.yml$"],
	  "matchStrings": [
		"renovate: datasource=(?<datasource>.*?) depName=(?<depName>.*?)( versioning=(?<versioning>.*?))?\\s.*value: '(?<currentValue>.*)'\\s"
	  ],
	  "versioningTemplate": "{{#if versioning}}{{{versioning}}}{{else}}semver{{/if}}"
	}
  ],
  "extends": [
    "config:base",
    ":preserveSemverRanges",
    ":dependencyDashboard",
    ":rebaseStalePrs",
    ":enableVulnerabilityAlertsWithLabel('security')",
    "group:recommended"
  ]
}
```

**Here is the modification suggested in the 2 MR :**

First MR:

```
DOCKER_IMAGE_TAG: 
    # renovate: datasource=docker depName=library/php
    value: '7.4.33-apache-bullseye'
    value: '7.4.33'
```
2nd MR:

 ```
   value: 'php'
  DOCKER_IMAGE_TAG: 
    # renovate: datasource=docker depName=library/php
    value: '7.4.33-apache-bullseye'
    value: '8.3.6'
```
Any idea how I could fix this ?

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
