### DISCUSSION TITLE
[MAVEN]-[S3]: How to configure aws region?

### DISCUSSION THREAD

**Discussion by ajax-kovtunov-o** [renovatebot/renovate#28873] [Request Help]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Mend Renovate hosted app on github.com

### Please tell us more about your question or problem

How to configure aws region for renovate bot?

Configuration
* github
* private s3 maven repository
```json
{
"packageRules": [
      "registryUrls": [
        "s3://ajax-system-maven-repository/snapshots"
      ],
    }
  ],
"hostRules": [
    {
      "hostType": "maven",
      "matchHost": "s3://ajax-system-maven-repository/snapshots",
      "encrypted": {
        "username": "aws-acces-key-id",
        "password": "aws-secret-key"
      }
    }
  ],
"customEnvVariables": {
    "AWS_REGION": "aws-region"
  }
}
```

The problem is
```
DEBUG: Unknown S3 download error

```

I guess that root cause is unconfigured AWS_REGION

### Logs (if relevant)

<details><summary>Logs</summary>

```

DEBUG: Unknown S3 download error
{
  "failedUrl": "<my package>"
  "message": "The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint."
}
```

</details>

**Comment by rarkins** [comment]
Will any region work or needs a specific one?

**Reply by ajax-kovtunov-o** [reply]
need specific one

**Reply by rarkins** [reply]
Can you put a full hostname in the s3:// url?

**Reply by ajax-kovtunov-o** [reply]
do u mean share with you my aws hostname? I guess I can't here.

**Reply by rarkins** [reply]
Have you tested it locally with Renovate and confirm it definitely works if an AWS_REGION is defined?

**Reply by ajax-kovtunov-o** [reply]
I haven't tested it locally. Do u mean run renovate docker image locally and try to pass AWS_REGION as env var to the renovate application? I don't.

But I've use github action, it works:
```
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.0
        env:
          LOG_LEVEL: debug
          AWS_REGION: "region"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```
