### DISCUSSION TITLE
RENOVATE_INCLUDE_FILES variable to force renovate to work with specified files only

### DISCUSSION THREAD

**Discussion by ruzickap** [renovatebot/renovate#28920] [Suggest an Idea]
### Tell us more.

Would it be possible to introduce new Renovate environment variable `RENOVATE_INCLUDE_FILES` - which will force renovate to update versions only in the list of files which are defined in this env variable?

Use case:
* It may be handy to use renovate to update only changed/new files in Pull Requests.

Idea:

Use [tj-actions/changed-files](https://github.com/tj-actions/changed-files) to get the changed files and pass the list of these files to Renovate using environment variable:

```yaml
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: 💡 Self-hosted Renovate
        uses: renovatebot/github-action@89bd050bafa5a15de5d9383e3129edf210422004 # v40.1.5
        env:
          RENOVATE_INCLUDE_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
```

Renovate will update the changed/news file in the PR automatically (depends on the Renovate settings).

---

There is already the environment variable `RENOVATE_INCLUDE_PATHS` which is very similar, but works only with directories and not files...

Using `packageRules/matchFileNames` doesn't work in this case, because it can not be configured via environment variable. 

Thank you...

**Comment by rarkins** [comment]
`includePaths` supports glob patterns so it can be used for both directories and files already

**Reply by ruzickap** [reply]
Thank you...
Works fine...

**Comment by ruzickap** [comment]
In case somebody would like to achieve the same goal - here is my solution:

```yaml
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@03334d095e2739fa9ac4034ec16f66d5d01e9eba # v44.5.1

      - name: List all changed files
        run: |
          set -euxo pipefail
          echo "RENOVATE_INCLUDE_PATHS=${{ steps.changed-files.outputs.all_changed_files }}" | tee -a "${GITHUB_ENV}"

      - name: 💡 Self-hosted Renovate
        uses: renovatebot/github-action@89bd050bafa5a15de5d9383e3129edf210422004 # v40.1.5

```
