### DISCUSSION TITLE
Configure an Azure DevOps endpoint

### DISCUSSION THREAD

**Discussion by Ashley-Emery** [renovatebot/renovate#28944] [Request Help]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Azure Devops, Renovate version 37.235.5

### Please tell us more about your question or problem

We have a self-hosted renovate deployed with kubernetes. I'm having issues configuring the endpoint. 

And in the logs looks like if the endpoint wasn't configured at all, even though it's being set as an environment variable in our config.

```
DEBUG: CLI config
       "config": {}
DEBUG: Env config
       "config": {
         "hostRules": [
           {"hostType": "github", "matchHost": "github.com", "token": "***********"}
         ],
         "baseDir": "/tmp/renovate/",
         "platform": "azure",
         "token": "***********",
         "username": "<username>",
         "autodiscover": false
       }
```

**Error**
```
DEBUG: Setting global hostRules
DEBUG: Adding token authentication for github.com (hostType=github) to hostRules
FATAL: You must configure an Azure DevOps endpoint
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "logContext": "Jxn9fPuFQ2s-XNo7Fdu29",
           "msg": "You must configure an Azure DevOps endpoint"
         }
       ]
```

So far I've tried adding the endpoint using env variable `RENOVATE_ENDPOINT` with values like:
`https://dev.azure.com/<organization>/` & `https://dev.azure.com/<organization>/<project_name>/` but I keep getting the same error above.

This is how we have part of our environment variables:

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-bot
spec:
  schedule: '*/30 8-17 * * 1-5'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: renovate/renovate:37.235.5
              name: renovate-bot
              env:
                - name: RENOVATE_PLATFORM
                  value: 'azure'
                - name: RENOVATE_ENDPOINT
                  value: 'https://dev.azure.com/<organization>/'
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-bot
                      key: ado-personal-access-token
                 ...
```

Also wanted to double check if the proper way to list repositories [for ADO] in the config.json would be 
`repository": '<project_name>/<my_repository>`

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-portal-config
data:
  config.json: |-
    {
      "enabled": true,
      "logFormat": "json",
      "baseBranches": ["master"],
      ...
      "repositories": [
          {
              "repository": '<project_name>/<my_repository>'
          },
          {
              "repository": 'project_name>/<my_repository2>'
        ]
     ...
```

I appreciate any input. Thanks in advance!

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
