### DISCUSSION TITLE
Helm dependency version contraints configuration

### DISCUSSION THREAD

**Discussion by bsadowy-dbschenker** [renovatebot/renovate#29209] [Request Help]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab - Renovate version = 37.354.0

### Please tell us more about your question or problem

I would like to make Renovate create merge requests for Helm dependencies with version constraint looking like this `~1` instead `~1.0.0` so there would be no need for Renovate to create another merge request for every minor version update as according to semVer it shouldn't be breaking change. I am reading through documentation and all I can find is configuring on what version updates Renovate should act on but I can't find is that possible to define what version constraints format it should use when creating merge request.

What Renovate does:
```
# requirements.yaml
dependencies:
  - name: helmChart
    version: "~1.0.0"
```

What I would like it to do:
```
# requirements.yaml
dependencies:
  - name: helmChart
    version: "~1"
```

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
