### DISCUSSION TITLE
Gitlab Includes with anchors

### DISCUSSION THREAD

**Discussion by carlos-lehmann** [renovatebot/renovate#29463] [Request Help]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab

### Please tell us more about your question or problem

```yaml
include:
  - project: myproject
    file: myfile.yml
    ref: &ref "v1.20.3" # see here

parent-job:
  extends: .an_extends_block #from myfile.yml

child-trigger:
  stage: trigger-child
  trigger:
    include:
        - project: myproject
        file: myfile.yml
        ref: *ref #see here
      - artifact: generated-artifact-from-parent-job.yml
        job: parent-job
    strategy: depend
```

can renovate handle anchors in ref for an include?

Thank you!
