### DISCUSSION TITLE
Re-running the renovate pipeline results in different file changes in the pull request.

### DISCUSSION THREAD

**Discussion by ghost** [renovatebot/renovate#29474] [Request Help]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

platform: 'azure', renovate@37.392.0

### Please tell us more about your question or problem

I placed the global configuration file `config.js` and `renovate-pipeline.yml` in a devops repository and placed the repository configuration file `renovate.json5` in the application repository. The first pipeline run looks good, but 

The first run(26 changed files):
![image](https://github.com/renovatebot/renovate/assets/168217771/ff361ab3-4194-4d6e-ab1f-f84dc3a91296)

The second run(2 changed files):
![image](https://github.com/renovatebot/renovate/assets/168217771/050ab552-4358-47c8-95a2-14f26ed4581f)

Each run pushed a new commit(Updates tab):
![image](https://github.com/renovatebot/renovate/assets/168217771/d5c6896b-d27b-420e-b5ef-5a55615a5dc0)
But it always has one commit in Commits tab:
![image](https://github.com/renovatebot/renovate/assets/168217771/a85846c1-0006-4180-bac1-48b349f3d01c)

`config.js`

```js
module.exports = {
    platform: 'azure',
    endpoint: 'https://dev.azure.com/my-org/',
    token: process.env.AZURE_REPO_TOKEN,
    repositories: [ // list of repos that should be watched by renovate bot
        'my-project/my-apps'
    ],
    gitNoVerify: ["commit", "push"] // passes the `--no-verify` flag to `git commit` and `git push`
};
```
`renovate.json5`

```json5
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "enabledManagers": ["npm", "nodenv", "nvm", "bun", "meteor"], // Most managers are enabled by default. We currently only enable JavaScript and Node.js
  "azureWorkItemId": 3022, // used in the pull request
  "packageRules": [
    {
      "matchManagers": ["npm", "nodenv", "nvm", "bun", "meteor"],
      "groupName": "Package dependencies update" // All updates sharing the same groupName will be placed into the same branch/PR.
    }
  ],
  "labels":["renovate", "dependencies"],
  "reviewers": [
    "required:Dev Team",
    "required:DevOps Team"
  ],
  "azure-pipelines": { // enable Azure Pipelines support
    "enabled": true
  },
  "baseBranches": [ // the target branch of the PR
    "feature/3022-renovate-pipeline"
  ],
  "extends": [
    "config:best-practices"
  ],
  "prConcurrentLimit": 5, // Limit to a maximum of 5 concurrent branches/PRs
  "prHourlyLimit": 5,     // Rate limit PRs to maximum 5 created per hour
  "commitMessagePrefix": "3022 feature: ", // Prefix to add to start of commit messages and PR titles
  "semanticCommits": "disabled", // Renovate autodetects if your repository is already using semantic commits or not and follows suit, disable it to have customized commit prefix
  "osvVulnerabilityAlerts": true, // Use vulnerability alerts from https://osv.dev/
  "vulnerabilityAlerts": {
    "groupName": "vulnerabilityAlerts",
    "addLabels": ["renovate", "security", "vulnerability"]
  }
}
```

`renovate-pipeline.yml`

```yaml
schedules:
  - cron: '0 3 * * *'
    displayName: 'Renovate dependency checker'
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: my-apps
      type: git
      name: my-project/my-apps

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: "Renovate"
  - name: self.name
    value: $[ resources.repositories['self'].name ]
  - name: app.name
    value: $[ resources.repositories['my-apps'].name ]

steps:
  - checkout: self
  - checkout: my-apps
  - bash: |
      git config --global user.email 'renovate_bot@re-source.tech'
      git config --global user.name 'Renovate Bot'
      npx renovate
    env:
      AZURE_REPO_TOKEN: $(System.AccessToken)
      GITHUB_COM_TOKEN: $(GITHUB_COM_TOKEN)
      LOG_LEVEL: debug
      DEBUG: true
      RENOVATE_RECREATE_WHEN: always
      RENOVATE_USE_BASE_BRANCH_CONFIG: merge
    displayName: Run Renovate
    workingDirectory: $(System.DefaultWorkingDirectory)/$(self.name)/renovate
```

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
