### DISCUSSION TITLE
Is it possible to automatically lock the pull request after merging?

### DISCUSSION THREAD

**Discussion by alvinsjoy** [renovatebot/renovate#29512] [Request Help]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Mend Renovate hosted app on github.com

### Please tell us more about your question or problem

To avoid spam notifications, I would like to lock the pull requests by renovate after its merge. Is it possible?

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>

**Comment by rarkins** [comment]
Please describe in more details.

- You wrote "close" in the title but "lock" in the body
- You haven't described what you mean by "spam notifications"
- Do you mean PRs you merge, or ones which Renovate automerges?

**Reply by alvinsjoy** [reply]
I'm sorry I actually meant lock. I want to lock the prs by renovate which are automerged to prevent users from commenting on them after they are merged. I don't need to lock prs by me or other users, only the ones by renovate that too after automatically merging it.

**Reply by HonkingGoose** [reply]
## Third-party action to lock PRs

You may want to take a look at the `dessant/lock-threads` GitHub Action, as that can lock Renovate PRs shortly after merging.

> [!IMPORTANT]
> Check the action's code and security before you start using it! Make sure you limit the permissions of the action to only those needed for it to work. Make sure to read the documentation!

> [!TIP]
> I _strongly_ recommend you extend from Renovate's `config:best-practices` preset, as that will automatically pin your Actions to a specific version. Read the [Renovate docs, Upgrade best practices `helpers:pinGitHubActionDigests`](https://docs.renovatebot.com/upgrade-best-practices/#extends-helperspingithubactiondigests) to learn more about this topic.

### How we use the third-party Action

We use the [`dessant/lock-threads` GitHub Action](https://github.com/dessant/lock-threads) on this repository to lock closed Issues and PRs after 30 days. Here's our config for that:

https://github.com/renovatebot/renovate/blob/8371461f0f7692869f27c5056d6105eb4512d32c/.github/workflows/lock.yml#L1-L29

## Pointers for your own `dessant/lock-threads` configuration

I think this `dessant/lock-threads` configuration will do what you want:

```yaml
    steps:
      - uses: dessant/lock-threads@v5
        with:
          pr-inactive-days: 0
          process-only: 'prs'
          include-all-pr-labels: 'renovate-bot-prs'
```          

> [!IMPORTANT]
> Do not copy/paste this yet, first configure Renovate to label its PRs!
> Also, this is only a _small part_ of the total config you need for the Action!

### First label all Renovate PRs

Add this to your Renovate config file, as a top-level option:

```json
{
  "labels": ["renovate-bot-prs"]
}
```

Read the [Renovate docs, `labels` config option](https://docs.renovatebot.com/configuration-options/#labels) for the full details.

### Read the `dessant/lock-threads` readme!

Read the [`dessant/lock-threads`'s readme](https://github.com/dessant/lock-threads/blob/main/README.md) for the full instructions.

## Conclusion

I hope you find this helpful. :smile:

**Reply by alvinsjoy** [reply]
Hi @HonkingGoose, thanks for the reply.
I might have an another question, can github cli be used for locking the prs?
```yml
name: renovate bot auto-lock
on: 
  pull_request:
    types:
      - closed


permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]' && github.event.pull_request.merged == true
    steps:
      - name: Lock prs
        run: gh pr lock "$PR_URL" --reason resolved
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
I just want to know if this is possible. This config works with dependabot. Does it cause any problems with renovate?
Please correct me if I am wrong.
