### DISCUSSION TITLE
Flux OCIRepository fails to process with "Could not determine new digest for update"

### DISCUSSION THREAD

**Discussion by jfroy** [renovatebot/renovate#29521] [Request Help] [answered]
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Mend Renovate hosted app on github.com

### Please tell us more about your question or problem

I have a FluxCD repo with an OCIRepository resource for the kyverno Helm chart:

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 1h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/kyverno/charts/kyverno
  ref:
    tag: 3.2.3
    digest: sha256:d363081e45627aa396d6c8cb2d4ee59fcb7a79c223a967ae601c8c8ba4e7b7f3
```

Renovate fails to update this dependency.

### Logs (if relevant)

<details><summary>Logs</summary>

```
      {
        "packageFile": "kubernetes/flux/repositories/oci/kyverno.yaml",
        "deps": [
          {
            "depName": "ghcr.io/kyverno/charts/kyverno",
            "currentDigest": "sha256:d363081e45627aa396d6c8cb2d4ee59fcb7a79c223a967ae601c8c8ba4e7b7f3",
            "datasource": "docker",
            "updates": [],
            "packageName": "ghcr.io/kyverno/charts/kyverno",
            "versioning": "docker",
            "warnings": [
              {
                "message": "Could not determine new digest for update (docker package ghcr.io/kyverno/charts/kyverno)",
                "topic": "ghcr.io/kyverno/charts/kyverno"
              }
            ]
          }
        ]
      }

```

</details>
