### DISCUSSION TITLE
Onboarding PR gets closed when renovate action is run again.

### DISCUSSION THREAD

**Discussion by ferinagy** [renovatebot/renovate#29569] [Request Help] [answered]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Github action on Github Enterprise

### Please tell us more about your question or problem

When I run the Renovate Github Action from https://github.com/renovatebot/github-action, the onboarding PR in the repository is created successfully. But when I change the config in the onboarding branch and run the action again, the onboarding PR is closed. 

I have a following workflow file:

```yaml
name: Renovate
on:
  - workflow_dispatch
jobs:
  renovate:
    runs-on: runner-label
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          private-key: ${{ secrets.private_key }}
          app-id: ${{ secrets.app_id }}
          owner: ${{ github.repository_owner }}
          repositories: 'repo-name'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          configurationFile: .github/renovate-config.json5
          token: '${{ steps.get_token.outputs.token }}'
        env:
          RENOVATE_ENDPOINT: "https://github.example.org/api/v3"
          LOG_LEVEL: 'debug'
```

The `.github/renovate-config.json5` file is here:
```
{
  $schema: "https://docs.renovatebot.com/renovate-schema.json",
  "branchPrefix": "test-renovate/",
  "username": "self-hosted-renovate",
  "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
  "repositories": [
    "org-name/repo-name",
  ]
}
```

I have created the `self-hosted-renovate` Github app in the `org-name` organization according to https://github.com/renovatebot/github-action?tab=readme-ov-file#example-with-github-app and installed it in the `repo-name` repo.

### Logs (if relevant)

```
WARN: Onboarding PR already exists but cannot find it. It was probably created by a different user. (repository=org-name/repo-name)
```
