### DISCUSSION TITLE
Unclear instructions for Google Artifact Registry login using Workload Identity

### DISCUSSION THREAD

**Discussion by paololazzari** [renovatebot/renovate#29618] [Request Help] [answered]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitHub, version 40.1.12

### Please tell us more about your question or problem

I read the [docs](https://docs.renovatebot.com/docker/#google-container-registry-google-artifact-registry), which state:

> Just configure [ADC](https://cloud.google.com/docs/authentication/provide-credentials-adc) / [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) as normal and don't provide a username, password or token. Renovate will automatically retrieve the credentials using the google-auth-library.

Following that, here's how I am running renovate:

```
- name: 'Google auth'
  uses: 'google-github-actions/auth@v2'
  with:
    project_id: '${{ env.PROJECT_ID }}'
    service_account: '${{ env.SERVICE_ACCOUNT }}'
    workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
    export_environment_variables: true

- name: Self-hosted Renovate
  uses: renovatebot/github-action@v40.1.12
  with:
    configurationFile: .github/renovate-config.json
    token: ${{ secrets.RENOVATE_TOKEN }}
  env:
    LOG_LEVEL: 'debug'
    RENOVATE_HOST_RULES: '[{"matchHost":"us-central1-docker.pkg.dev"}]'
```

this fails with:

> DEBUG: Could not get Google access token, using no auth

**Comment by rarkins** [comment]
Please read the section on environment variables at https://github.com/renovatebot/github-action

**Reply by paololazzari** [reply]
So I should pass a token? Which one?

**Reply by rarkins** [reply]
You'll need to pass through all necessary credentials that the previous action exported

**Reply by paololazzari** [reply]
The documentation is confusing because it says not to pass in anything. The gcloud login action has the following [outputs](https://github.com/google-github-actions/auth?tab=readme-ov-file#outputs):


```
auth_token: The Google Cloud federated token (for Workload Identity Federation) or self-signed JWT (for a Service Account Key JSON). This output is always available.

access_token: The Google Cloud access token for calling other Google Cloud APIs. This is only available when "token_format" is "access_token".

id_token: The Google Cloud ID token. This is only available when "token_format" is "id_token".

```

which one would renovate need? `auth_token` ?

**Reply by rarkins** [reply]
It's complicated due to the use of GitHub actions. The Google action is exporting env which is then not automatically made available to the renovate action which follows it. You need to find a way to pass it through and you're welcome to submit a PR improving the docs after.

**Comment by paololazzari** [comment, marked as answer]
Got this working. Full job:


```yaml
jobs:
  renovate:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: 'Google auth'
        id: google_auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: '${{ env.PROJECT_ID }}'
          service_account: '${{ env.SERVICE_ACCOUNT }}'
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          token_format: "access_token"

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.12
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_HOST_RULES: '[{"matchHost":"us-central1-docker.pkg.dev","username":"oauth2accesstoken","password":"${{ steps.google_auth.outputs.access_token }}"}]'
```

make sure that the service account being used has the `artifactregistry.repositories.downloadArtifacts` permission.
