### DISCUSSION TITLE
Support for helm values in Ansible module

### DISCUSSION THREAD

**Discussion by mueller-ma** [renovatebot/renovate#29672] [Suggest an Idea]
### Tell us more.

Helm, a Kubernetes package manager, can be executed by Ansible. Here's an example of the action `kubernetes.core.helm`:

````yaml
---
- name: Install trivy-operator
  kubernetes.core.helm:
    name: trivy-operator
    namespace: trivy-system
    chart_repo_url: https://aquasecurity.github.io/helm-charts/
    chart_ref: trivy-operator
    chart_version: 0.23.0  # There's a newer version: 0.23.3
    values:
      trivy:
        image:
          registry: ghcr.io
          repository: aquasecurity/trivy
          tag: 0.52.0  # There's a newer version: 0.53.0

# Ansible tasks can be grouped via `block`
- name: Ansible block with a helm task
  block:
    - name: Install trivy-operator
      kubernetes.core.helm:
        name: trivy-operator
        namespace: trivy-system
        chart_repo_url: https://aquasecurity.github.io/helm-charts/
        chart_ref: trivy-operator
        chart_version: 0.23.0
        release_values:  # "release_values" is an alias for "values"
          trivy:
            image:
              registry: ghcr.io
              repository: aquasecurity/trivy
              tag: 0.52.0
````

https://github.com/mueller-ma/renovate-reproduce/blob/main/ansible-helm/tasks.yml

Two things could be updated via Renovate here:
1. `chart_version` is the version of the chart. When using a customManager similar to the `customManagers:dockerfileVersions`, the following arguments can be used to update this version: `datasource=helm depName=trivy-operator registryUrl=https://aquasecurity.github.io/helm-charts/`
2. The value of the keys `values` and `release_values` is like the content of a values.yaml file, which is supported by Renovate: https://docs.renovatebot.com/modules/manager/helm-values/

While I'm not aware of any default file name or file paths for Ansible yaml files, some common paths are:
- `playbooks/*`
- `role/*/tasks/`

**Comment by github-actions** [comment]
Hi there,

Get your discussion fixed faster by creating a minimal reproduction. This means a repository dedicated to reproducing this issue with the minimal dependencies and config possible.

Before we start working on your issue we need to know exactly what's causing the current behavior. A minimal reproduction helps us with this. Discussions without reproductions are less likely to be converted to Issues.

To get started, please read our guide on creating a [minimal reproduction](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md).

Good luck,

The Renovate team

**Reply by mueller-ma** [reply]
https://github.com/mueller-ma/renovate-reproduce/blob/main/ansible-helm/tasks.yml

**Reply by rarkins** [reply]
Can you locate documentation for these fields so we can understand all combinations possible?

**Reply by mueller-ma** [reply]
Sure: https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html

![grafik](https://github.com/renovatebot/renovate/assets/22525368/5f182dcd-08b2-4641-b5a4-cb87636e1f84)

`values` is an alias to `release_values`, so the following task is also valid:
````
- name: Deploy a chart
  kubernetes.core.helm:
    name: test
    chart_ref: foo/bar
    release_namespace: test
    release_values:
      image:
        repository: 'some-docker/dependency'
        version: v1.0.0
````

**Reply by mueller-ma** [reply]
BTW, there's also `chart_version`:

````
- name: Deploy a chart
  kubernetes.core.helm:
    name: test
    chart_ref: foo/bar
    release_namespace: test
    chart_version: 2.0.0  # Version of chart mentioned in chart_ref
    release_values:
      image:
        repository: 'some-docker/dependency'
        version: v1.0.0
````
