### DISCUSSION TITLE
`kustomize` manager seems to not detect overlays/multiple kustomization files

### DISCUSSION THREAD

**Discussion by NINNiT** [renovatebot/renovate#29760] [Request Help] [answered]
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Gitlab - mend-renovate-ce 7.3.0-full / renovate v37.368.10

### Please tell us more about your question or problem

We are struggling to get a working configuration for `kustomize` repos up-and-running. 

Our `renovate.json`:
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:recommended"
  ],
  "kustomize": {
    "enabled": true
  }
}
```

Our file tree:
```
├── base
│   ├── deployment.yml
│   ├── kustomization.yml
│   └── service.yml
├── renovate.json
└── test
    ├── config
    │   ├── ...
    ├── ingress.yml
    ├── kustomization.yml
    └── namespace.yml
```

Our `test/kustomization.yml` file, containing the image:
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yml
  - namespace.yml
namespace: test
images:
  - name: spring-template-image
    newName: some.registry.com/apps/spring-template
    newTag: v1.0.1-beta.3
configMapGenerator:
  - name: spring-template-configmap
    envs:
      - ./config/config.env
secretGenerator:
  - name: spring-template-secret
    envs:
      - ./config/secret.env
```

Looking at the self-hosted renovate-ce logs, renovate seems to detect only the alphabetically first kustomiatzion.yml - which is in `base/` and does NOT contain any image declarations:

```
renovate-app-renovate-1  | DEBUG: Matched 1 file(s) for manager gitlabci: .gitlab-ci.yml (repository=group1/group2/deployment/spring-template-kubernetes)
renovate-app-renovate-1  | DEBUG: Matched 1 file(s) for manager gitlabci-include: .gitlab-ci.yml (repository=group1/group2/deployment/spring-template-kubernetes))
renovate-app-renovate-1  | DEBUG: Matched 1 file(s) for manager kustomize: base/kustomization.yml (repository=group1/group2/deployment/spring-template-kubernetes))
renovate-app-renovate-1  | DEBUG: manager extract durations (ms) (repository=group1/group2/deployment/spring-template-kubernetes))
renovate-app-renovate-1  |        "managers": {"kustomize": 5, "gitlabci": 7, "gitlabci-include": 6}
renovate-app-renovate-1  | DEBUG: Found gitlabci package files (repository=group1/group2/deployment/spring-template-kubernetes))
renovate-app-renovate-1  | DEBUG: Found 1 package file(s) (repository=group1/group2/deployment/spring-template-kubernetes))
renovate-app-renovate-1  |  INFO: Dependency extraction complete (repository=group1/group2/deployment/spring-template-kubernetes), baseBranch=main)
renovate-app-renovate-1  |        "stats": {
renovate-app-renovate-1  |          "managers": {"gitlabci": {"fileCount": 1, "depCount": 1}},
renovate-app-renovate-1  |          "total": {"fileCount": 1, "depCount": 1}
renovate-app-renovate-1  |        }
```

The dependecy dashboard also just lists `gitlab-ci` as detected managers.

We'd appreciate any help we can get! <3 
Is this a bug or are we doing something wrong?

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
