### DISCUSSION TITLE
Renovate suggests upgrade to an older image with higher version

### DISCUSSION THREAD

**Discussion by AndreiGavriliu** [renovatebot/renovate#29916] [Request Help] [answered]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

k3s, Gitea, renovate 37.420.1

### Please tell us more about your question or problem

Hi all,

I'm new to this so please excuse me if I missed something somewhere in the docs/issues...

I have a very _weird_ problem with [calibre-web](https://github.com/janeczku/calibre-web). 

The k8s manifest contains the following image: `- image: lscr.io/linuxserver/calibre-web:0.6.21`, which is the latest according to [DockerHub](https://hub.docker.com/r/linuxserver/calibre-web/tags) and [Linuxserver Fleet](https://fleet.linuxserver.io/image?name=linuxserver/calibre-web). However, renovate opened a PR `Update lscr.io/linuxserver/calibre-web Docker tag to v2021` as follows:

| Package | Update | Change |
|---|---|---|
| [lscr.io/linuxserver/calibre-web](https://github.com/linuxserver/docker-calibre-web/packages) ([source](https://github.com/linuxserver/docker-calibre-web)) | major | `0.6.21` -> `2021.12.16` |

Here, the docker-calibre-web is also `ghcr.io/linuxserver/calibre-web:0.6.21-ls272`

Where is the v2021 coming from?

Any hint is welcome

Cheers!

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>

**Comment by AndreiGavriliu** [comment]
Also, maybe relevant, 

the diff of the PR is:

```
        app: calibre-web
    spec:
      containers:
-       - image: lscr.io/linuxserver/calibre-web:0.6.21
+       - image: lscr.io/linuxserver/calibre-web:2021.12.16
          imagePullPolicy: Always
          name: calibre-web
          env:
```
