### DISCUSSION TITLE
Yaml parse is failed when there are some gotmpl syntaxes in helmfile

### DISCUSSION THREAD

**Discussion by weijiany** [renovatebot/renovate#30076] [Request Help] [answered]
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab

### Please tell us more about your question or problem

I want to use renovate to update my dependencies, and one of my dependenies is helmfile, and I also use some gotmpl syntax in it like this:

```yaml
repositories:
  - name: backstage
    url: https://backstage.github.io/charts
  - name: oauth2-proxy
    url: https://oauth2-proxy.github.io/manifests
environments:
  test: {}
releases:
  - name: backstage
    chart: backstage/backstage
    version: 0.12.0
  {{- if eq .Environment.Name "test" }}
    installed: false
  {{- end }}
  - name: oauth-proxy
    chart: oauth2-proxy/oauth2-proxy
    version: 6.8.0
```

Renovate will raise an error when it read this file. The error is:

```json
{
  "err": {
    "message": "Schema error",
    "stack": "ZodError: Schema error
        at Object.get error [as error] (/usr/src/app/node_modules/renovate/node_modules/zod/lib/types.js:55:31)
        at fromZodResult (/usr/src/app/node_modules/renovate/lib/util/result.ts: 54: 67)
        at Function.parse (/usr/src/app/node_modules/renovate/lib/util/result.ts: 552: 12)
        at updateArtifacts (/usr/src/app/node_modules/renovate/lib/modules/manager/helmfile/artifacts.ts: 73: 24)
        at managerUpdateArtifacts (/usr/src/app/node_modules/renovate/lib/workers/repository/update/branch/get-updated.ts: 434: 12)
        at getUpdatedPackageFiles (/usr/src/app/node_modules/renovate/lib/workers/repository/update/branch/get-updated.ts: 303: 25)
        at processBranch (/usr/src/app/node_modules/renovate/lib/workers/repository/update/branch/index.ts: 472: 19)
        at writeUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/write.ts: 166: 17)
        at update (/usr/src/app/node_modules/renovate/lib/workers/repository/process/extract-update.ts: 214: 11)
        at Object.renovateRepository (/usr/src/app/node_modules/renovate/lib/workers/repository/index.ts: 87: 19)
        at attributes.repository (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts: 217: 11)
        at start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts: 202: 7)
        at /usr/src/app/node_modules/renovate/lib/renovate.ts: 18: 22",
    "issues": "Invalid YAML"
  }
}
```

I spent some time digging into the source code I found the root cause is that renovate parses helmfile as a [Doc](https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/helmfile/schema.ts#L26-L29) object, but [Yaml.pipe](https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/helmfile/artifacts.ts#L75) doesn't recognize the gotmpl syntax and therefore throws a Schema error.

Would you like it fixed in the future? If you don't have the time, I'd be happy to pick it.

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
