### DISCUSSION TITLE
Renovate configuration for Apko and melange files using the wolfi registry

### DISCUSSION THREAD

**Discussion by Conor-Behard333** [renovatebot/renovate#30135] [Request Help]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

gitlab, renovate, 37.428.2

### Please tell us more about your question or problem

We are using Chainguard's [Melange](https://edu.chainguard.dev/open-source/build-tools/melange/overview/) and [Apko](https://edu.chainguard.dev/open-source/build-tools/apko/overview/) to build low to zero vulnerability images. These tools use yaml files to configure the building process of these images. 

Melange is used to build dependencies from source and build them into an alpine like package. These packages can then be used by apko to build images. 

Part of the apko/melnage yaml files is listing the alpine like packages needed to be installed in the image. This looks like:
```YAML
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
    - https://<jfrog-url>/artifactory/test-apko-apk-local/1.0/main
  packages:
    - elasticsearch=8.14.1 # stored in jfrog registry
    - busybox=1.36.1 # stored in wolfi registry
    - openjdk-21=21.0.3 # stored in wolfi registry
```
Where the repositories are defined (wolfi registry and a local jfrog alpine registry), as well as the packages and their versions.

We are having trouble creating a renovate config file to check that the versions of these packages are up to date. I'm aware that for packages renovate use Repology to check the package versions. Wolfi does not have a registry defined in there so that option is not possible. Are there ways around this? 

Any help on the correct config for renovate would be super helpful, thank you.

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
