### DISCUSSION TITLE
Mend Renovate App: Failed to look up git-tags package / remote: Repository not found

### DISCUSSION THREAD

**Discussion by McSim85** [renovatebot/renovate#30211] [Request Help] [answered]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Mend Renovate hosted app on github.com

### Please tell us more about your question or problem

Hey team,
We are trying to onboard the Mend Renovate App.
I am facing some issues with Ansible dependancies.

renovate.json looks like this:
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:recommended"
  ],
  "hostRules": [
    {
      "matchHost": "ghcr.io",
      "hostType": "docker",
      "username": "<*edited*username*>",
      "encrypted": {
        "password": "h<...REMOVED...>"
      }
    }
  ]
}
```
repo requirements.yml looks like this:
```yaml
---
roles:
  - name: role_p
    src: git@github.com:edited-company-labs/role-p.git
    version: v1.3.6

  - name: role_b
    src: git@github.com:edited-company-labs/role-b.git
    version: v1.18.7

  - name: role_sss_ufw
    src: git@github.com:edited-company-labs/role_sss_ufw.git
    version: v0.0.10

  - name: role_utils
    src: git@github.com:edited-company-labs/role_utils.git
    version: v1.0.1

collections:
  - name: ansible.posix
    version: 1.5.4

  - name: community.general
    version: 9.2.0

  - name: ansible.utils
    version: 5.0.0

  - name: edited-company.role_consul
    source: git@github.com:edited-company-labs/role-consul.git
    type: git
    version: 1.40.0
```

So, when Renovate runs, it shows a Warning:

> [!WARNING]
> Renovate failed to look up the following dependencies: `Failed to look up git-tags package git@github.com:edited-company-labs/role-consul.git`, `Failed to look up git-tags package git@github.com:edited-company-labs/role-b.git`, `Failed to look up git-tags package git@github.com:edited-company-labs/role_sss_ufw.git`, `Failed to look up git-tags package git@github.com:edited-company-labs/role_utils.git`.
> 
> Files affected: `requirements.yml`

All repos belong to the same company account and all of them are private.

```json
{
  "renovateVersion": "37.431.4"
}
```

Appreciate any help on this issue 🙏 

### Logs (if relevant)

<details><summary>Logs</summary>

```
DEBUG: Datasource unknown error
{
  "datasource": "git-tags"
  "packageName": "git@github.com:edited-company-labs/role-consul.git"
  "err": {
    "task": {
      "commands": [
        "ls-remote",
        "git@github.com:edited-company-labs/role-consul.git"
      ],
      "format": "utf-8",
      "parser": "[function]"
    },
    "message": "remote: Repository not found.\nfatal: repository 'https://github.com/edited-company-labs/role-consul.git/' not found\n",
    "stack": "Error: remote: Repository not found.\nfatal: repository 'https://**redacted**@3.25.0/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/usr/local/renovate/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/src/lib/plugins/plugin-store.ts:54:29)\n    at /usr/local/renovate/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/local/renovate/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:121:14)\n    at GitExecutorChain.<anonymous> (/usr/local/renovate/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:97:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/local/renovate/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/dist/cjs/index.js:52:24)"
  }
}

DEBUG: Failed to look up git-tags package git@github.com:edited-company-labs/role-consul.git
{
  "dependency": "git@github.com:edited-company-labs/role-consul.git"
  "packageFile": "requirements.yml"
}

```

Here is the full GHGist, if that will be helpful
https://gist.github.com/McSim85/c22768909ee10f049086d5c8744388c1

</details>
