### DISCUSSION TITLE
Pull in blog post about secure and scalable Renovate service on GitLab?

### DISCUSSION THREAD

**Discussion by HonkingGoose** [renovatebot/renovate#30446] [Suggest an Idea]
### Tell us more.

[`@sisp`](https://github.com/sisp) wrote a good article on the [Siemens blog, A secure and scalable Renovate service on GitLab](https://blog.siemens.com/2024/07/a-secure-and-scalable-renovate-service-on-gitlab/). I want to put the blog post in our User Stories part of the docs.

Pulling in the blog post means we'll have to maintain and update it if things change.

Before I do anything, I want to know what you Renovate maintainers think! 😉 

#### Questions

- We have a GitLab pipeline template for Renovate, is that the best way for most users to run Renovate on GitLab?
- The blog is talks about a difficult way to self-host Renovate, meant for those who need a really secure deployment.
- Is the general information correct for us to pull in?
- Do we think the level of difficulty is a good match for our docs? If we think this is too hard, maybe we should _not_ pull it in.

#### Todos if maintainers like my idea

- [ ] Ask `@sisp` for permission
- [ ] Ask `@sisp` if they want to put their work under our license

#### Todos if we get permission

- [ ] Get source files for blog post
- [ ] Link to original blog post
- [ ] Give credit to the original author
- [ ] Enrich the blog post by linking to our config options
- [ ] Rewrite to match our style (simple words, short sentences)
- [ ] Upstream my improvements

**Comment by skycaptain** [comment]
A few thoughts came to mind while reading the article. For context, consider a scenario where a DevOps team aims to offer Renovate as a service on a self-hosted or dedicated GitLab instance, allowing developers to self-service their projects. This service should be straightforward, robust, self-explanatory, and require minimal effort for setup and maintenance.

That’s being said, here are a few thoughts:

- For a per-project setup, what are the best practices for managing the `GITHUB_COM_TOKEN`? Developers in companies using a dedicated/self-hosted GitLab instance typically lack GitHub accounts for work, and creating them solely for this purpose is impractical. Moreover, it's preferable to associate tokens with bot accounts rather than individual users, as employee turnover is inevitable. Consequently, the DevOps team would likely prefer to provide a pre-configured token within the template, either through an instance-wide CI/CD variable (which doesn't support environments) or a group CI/CD variable, rather than having developers set up the `GITHUB_COM_TOKEN` for each project individually? Given that this token only has read-only access to the public API, it should be secure enough to use, correct? However, this approach contradicts the concept mentioned in the article of keeping projects self-contained. WDYT?
- Using private shareable config presets as described [here](https://docs.renovatebot.com/config-presets/#gitlab-hosted-presets) using `local>...` seems not to be possible with this approach: A PrAT inherently lacks access to other repos, and `CI_JOB_TOKEN` doesn't have access to the Repository Files API, which Renovate uses to check for `default.json`. However, a `CI_JOB_TOKEN` can access the job artefacts from a shared config repository. A potential workaround is to set up a pipeline in the shared config repo that publishes `default.json` as an artefact and configure Renovate to [fetch presets via HTTP](https://docs.renovatebot.com/config-presets/#fetching-presets-from-an-http-server) using a URL [like this](https://docs.gitlab.com/ee/api/job_artifacts.html#download-a-single-artifact-file-from-specific-tag-or-branch). Also, ensure to have “Settings > CI/CD > Artifacts > Keep artifacts from most recent successful jobs” enabled. Rough example:
    
    ```yaml
    config:
      stage: build
      rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        - if: $CI_COMMIT_TAG
      image: busybox:stable-uclibc
      script: 'true'
      artifacts:
        paths:
          - default.json
    ```
    
    Use as follows in renovate.json:
    
    ```json
    {
      "$schema": "https://docs.renovatebot.com/renovate-schema.json",
      "extends": [
        "https://gitlab.com/api/v4/projects/my-group%2Frenovate-config/jobs/artifacts/main/raw/default.json?job=config"
      ]
    }
    ```
    
- Ensure to use Bearer token auth opposed to basic auth as described in the article to access GitLab’s API, where basic auth using `CI_JOB_TOKEN` does not work (will return 4XX):
    
    ```yaml
    RENOVATE_HOST_RULES: |
      [
        {
          "matchHost": "${CI_SERVER_HOST}",
          "token": "${CI_JOB_TOKEN}",
        },
        {
          "matchHost": "${CI_REGISTRY}",
          "username": "gitlab-ci-token",
          "password": "${CI_JOB_TOKEN}"
        }
      ]
    ```
    
    I'm uncertain about the author's choice of basic auth for GitLab (maybe it's required for certain package types). Perhaps a separate rule for the API endpoint is necessary instead:
    
    ```yaml
    RENOVATE_HOST_RULES: |
      [
        {
          "matchHost": "${CI_API_V4_URL}",
          "token": "${CI_JOB_TOKEN}",
        },
        {
          "matchHost": "${CI_SERVER_HOST}",
          "hostType": "<datasource>",
          "username": "gitlab-ci-token",
          "password": "${CI_JOB_TOKEN}"
        },
        {
          "matchHost": "${CI_REGISTRY}",
          "username": "gitlab-ci-token",
          "password": "${CI_JOB_TOKEN}"
        }
      ]
    ```
    
- A PrAT lacks access to private shared GitLab components or templates. Consequently, when Renovate pushes a `renovate/` branch and opens a MR using the PrAT, the MR pipeline fails with a `yaml invalid` error. The error message states: "Project `gitlab-ci-templates` not found or access denied! Make sure any includes in the pipeline configuration are correctly defined." However, a `CI_JOB_TOKEN` is allowed to trigger a MR pipeline and access other repos. For another project I used (admittedly a very ugly) workaround, which included a git-post-push hook that triggered the MR pipeline using the `CI_JOB_TOKEN` via the REST API, after the branch has been pushed using the PrAT. I haven’t tested whether this is feasible here.
- Based on my understanding of the article, the main security concern with `CI_JOB_TOKEN` is that it grants users with Developer role write access to the Container and Package registries of allow-listed projects where they also have at least Developer role. However, it's worth noting that some companies, including ours, use external solutions like Artifactory to store artefacts and have disabled Container and Package registries for all projects on our instance.
- An example or reference project could be in the form of a [CI/CD component](https://docs.gitlab.com/ee/ci/components/).
