### DISCUSSION TITLE
[gitlab-tags datasource] Extend parsing to CI/CD catalog snippets

### DISCUSSION THREAD

**Discussion by DyspC** [renovatebot/renovate#30502] [Suggest an Idea]
### Tell us more.

I'm using [this CI/CD component](https://gitlab.com/explore/catalog/to-be-continuous/gradle) in one of my projects and it has two exposed usage snippets:

- A user provided one (maybe they new of this particular issue)
```yml
include:
  # 1: include the component
  - component: gitlab.com/to-be-continuous/gradle/gitlab-ci-gradle@2.7.1
    # 2: set/override component inputs
    inputs:
      image: "registry.hub.docker.com/library/gradle:jdk11" # ⚠ this is only an example
```

- The gitlab generated snippet (thus their usage recommendation I guess)
```yml
include:
  - component: $CI_SERVER_FQDN/to-be-continuous/gradle/gitlab-ci-gradle@2.7.1
```

When using the latter the renovate onboarding MR ends with a warning that the repository tags were not resolved. This was fixed by hardcoding the fqdn in my CI config file.

Perhaps some of the [predefined variables](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html) could be extrapolated based on the repository location or the renovate running method (A CI runner would probably have the same values in its job env). (CI_SERVER_FQDN, CI_SERVER_HOST and CI_SERVER_PORT at first)

PS: At the moment a gitlab CI component can only be imported from the very same instance the project runs its CI on
