### DISCUSSION TITLE
Renovate exits with code 0 in the middle of the process

### DISCUSSION THREAD

**Discussion by florianmutter** [renovatebot/renovate#30529] [Request Help]
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitHub

### Please tell us more about your question or problem

In most of the runs renovate just stops when processing the last dependency (at least I think this is where it is). It exits with status code 0. Here is the end of the log of a "failed" run:
![Screenshot 2024-08-01 at 13 52 43](https://github.com/user-attachments/assets/ebbe6ae9-1af2-4a87-8e88-33bedc012a88)
In a successful run it continues to list all the packages it finds:
![Screenshot 2024-08-01 at 13 53 20](https://github.com/user-attachments/assets/4ca7d8bf-560d-46fb-8396-d2841d29d8ae)

### Logs (if relevant)

Logs are to long for inline. File attached: 
[job-logs.txt](https://github.com/user-attachments/files/16455789/job-logs.txt)

**Comment by rarkins** [comment]
It's unlikely that renovate is exiting itself without any message. Most likely is that the process or container is being killed by the OS or scheduler, such as for out of memory problems.

**Reply by florianmutter** [reply]
Hmm ok, what is confusing to me is that Github says the action did finish successful. There is no indication whatsoever that something went wrong. Ususally when an action hits a timeout there is an error message.

This is the summary and the view of the job for a run that did stop to early:
![Screenshot 2024-08-01 at 14 37 05](https://github.com/user-attachments/assets/db043077-c0fc-4c28-8dd1-878958049ba8)
![Screenshot 2024-08-01 at 14 37 19](https://github.com/user-attachments/assets/ba21157a-b89f-41e9-a2db-a93fdf074164)

The timeout of the action is 120 minutes. This is our action:

```
name: Renovate
on:
  pull_request:
    paths:
      - ".github/workflows/renovate.yml"
  workflow_dispatch:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0 */2 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: 186101
          private_key: ${{ secrets.RENOVATE_APP_KEY }}

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@8ce0fe8066eb6b16e1bf499b21bc96e5ccd962a4 # v40.2.3
        with:
          configurationFile: .github/renovate-config.js
          token: '${{ steps.generate-token.outputs.token }}'
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_GITHUB_TOKEN_FOR_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
```
