### DISCUSSION TITLE
code=ERR_BODY_PARSE_FAILURE, statusCode=200

### DISCUSSION THREAD

**Discussion by Devinwong** [renovatebot/renovate#30690] [Request Help] [answered]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Mend Renovate hosted app on github.com

### Please tell us more about your question or problem

Hi. I hit the following message when configuring customDatasources.

```
DEBUG: GET https://packages.microsoft.com/ubuntu/22.04/prod/dists/testing/main/binary-amd64/Packages = (code=ERR_BODY_PARSE_FAILURE, statusCode=200 retryCount=0, duration=671)
DEBUG: Retry-After: unexpected status code 200
```

Don't understand why code 200 is unexpected in the logs. Or just for info?
The url `https://packages.microsoft.com/ubuntu/22.04/prod/dists/testing/main/binary-amd64/Packages` is publicly accessible

My CustomDatasources look like this
```
"customDatasources": {
    "containerd": {
      "defaultRegistryUrlTemplate": "https://packages.microsoft.com/ubuntu/22.04/prod/dists/testing/main/binary-amd64/Packages",
      "format": "json",
      "transformTemplates": [
        "{\"releases\":$map($match($, /Package:\\s*moby-containerd\\s*Version:\\s*([^\\s]+)/g), function($v) {\"version\": $v.groups[0]})}"
      ]
    }
}
```
Is my configuration incorrect or the URL needs special configuration for Renovate to access?
I've double checked my JSONata query in `transformTemplates`. It should be able to get what I need from the URL.
Thanks for taking a look.

### Logs (if relevant)

<details><summary>Logs</summary>

```

DEBUG: hostRules: no authentication for packages.microsoft.com
DEBUG: Using queue: host=packages.microsoft.com, concurrency=16
DEBUG: GET https://packages.microsoft.com/ubuntu/22.04/prod/dists/testing/main/binary-amd64/Packages = (code=ERR_BODY_PARSE_FAILURE, statusCode=200 retryCount=0, duration=671)
DEBUG: Retry-After: unexpected status code 200
{
  "url": "https://packages.microsoft.com/ubuntu/22.04/prod/dists/testing/main/binary-amd64/Packages"
}

DEBUG: Failed to look up custom.containerd package containerd
{
  "dependency": "containerd"
  "packageFile": "<some json file>"
}

DEBUG: PackageFiles.add() - Package file saved for base branch
{
  "baseBranch": "master"
}

DEBUG: Package releases lookups complete
{
  "baseBranch": "master"
}

```

Also
```
{
        "deps": [
          {
            "packageName": "containerd",
            "currentValue": "1.3.20",
            "datasource": "custom.containerd",
            "versioning": "semver",
            "replaceString": "\"name\": \"containerd\",\n      \"downloadLocation\": \"/opt/containerd/downloads\",\n      \"downloadURIs\": {\n        \"ubuntu\": {\n          \"current\": {\n            \"versions\": [\n              \"1.3.20\"",
            "depName": "containerd",
            "updates": [],
            "warnings": [
              {
                "topic": "containerd",
                "message": "Failed to look up custom.containerd package containerd"
              }
            ]
          }
        ],
```

</details>

**Comment by rarkins** [comment]
A 200 OK response with a Retry-After header is unexpected.

**Reply by rarkins** [reply]
Is that response actually JSON?

**Reply by RahulGautamSingh** [reply]
its yaml. please change you format

**Comment by Devinwong** [comment]
Thanks for replying over the weekend!
My bad. I tried `plain` and `json` but didn't realize it's yaml.
After changing it to `yaml`, the first error is gone. _(code=ERR_BODY_PARSE_FAILURE, statusCode=200)_
But the second error still presents. 
```
DEBUG: Failed to look up custom.containerd package containerd
{
  "dependency": "containerd"
  "packageFile": "parts/linux/cloud-init/artifacts/test_components.json"
}
```
```
{
        "deps": [
          {
            "packageName": "containerd",
            "currentValue": "1.3.20",
            "datasource": "custom.containerd",
            "versioning": "semver",
            "replaceString": "\"name\": \"containerd\",\n      \"downloadLocation\": \"/opt/containerd/downloads\",\n      \"downloadURIs\": {\n        \"ubuntu\": {\n          \"current\": {\n            \"versions\": [\n              \"1.3.20\"",
            "depName": "containerd",
            "updates": [],
            "warnings": [
              {
                "topic": "containerd",
                "message": "Failed to look up custom.containerd package containerd"
              }
            ]
          }
        ],
        "matchStrings": [
          "\"name\":\\s*\"(?<packageName>containerd)\"[^}]*\"current\"[^}]*\"versions\":\\s*\\[\\s*\"(?<currentValue>[^\"]+)\""
        ],
        "datasourceTemplate": "custom.containerd",
        "versioningTemplate": "semver",
        "packageFile": "<some json>"
      }
```

Is there a quick way for me to validate my `transformTemplates`? Or at least providing more debugging info for `transformTemplates`.
Let me know if I should create another discussion.

My configuration is updated as follows. (changed `json` to `yaml`)
```
"containerd": {
      "defaultRegistryUrlTemplate": "https://packages.microsoft.com/ubuntu/22.04/prod/dists/testing/main/binary-amd64/Packages",
      "format": "yaml",
      "transformTemplates": [
        "{\"releases\":$map($match($, /Package:\\s*moby-containerd\\s*Version:\\s*([^\\s]+)/g), function($v) {\"version\": $v.groups[0]})}"
      ]
    },
```

**Reply by RahulGautamSingh** [reply, marked as answer]
Invalid yaml as it shows here: https://codebeautify.org/yaml-validator

One/more of the `Description` fields have the `system:` text within it which is causing the error. 

Example:
```yaml
Package: moby-containerd
Version: 1.6.21+azure-ubuntu22.04u3
Architecture: amd64
Section: admin
Priority: optional
Installed-Size: 125665
Maintainer: Microsoft <support@microsoft.com>
Description: Industry-standard container runtime
 containerd is an industry-standard container runtime with an emphasis on
 simplicity, robustness and portability. It is available as a daemon for Linux
 and Windows, which can manage the complete container lifecycle of its host
 system: image transfer and storage, container execution and supervision,      # culprit
 low-level storage and network attachments, etc.
 .
 containerd is designed to be embedded into a larger system, rather than being
 used directly by developers or end-users.
Homepage: https://github.com/containerd/containerd
Conflicts: containerd, containerd.io, moby-engine (<= 3.0.12)
Depends: libc6 (>= 2.34), moby-runc (>= 1.0.2)
Recommends: ca-certificates
Provides: containerd, containerd.io
Replaces: containerd, containerd.io
SHA256: 1b6ed3cf6cbcbf4535ab07c77c396d1f6a94a447bfdf4d574bbbbd5d983657b9
Size: 34928016
Filename: pool/main/m/moby-containerd/moby-containerd_1.6.21+azure-ubuntu22.04u3_amd64.deb
```
