### DISCUSSION TITLE
nuget on private Github packages does not work

### DISCUSSION THREAD

**Discussion by pdcemulator** [renovatebot/renovate#30773] [Request Help]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

github-action@v40.2.6 / Renovate 38.28.2

### Please tell us more about your question or problem

Hello,
I try to get updates for nuget hosted on private Github Packages repos using a PAT. But this does not work. I always get `Failed to look up nuget package` errors and see 401 status in the logs.

I am able to fetch package metadata from package url using curl and the same credentials. So they are valid and have the right permissions.
Probably something with me Renovate config is wrong. I spend a lot of time reading the docs and discussions and tried many things. None of them are working and I think my config is ok. What am I doing wrong?

Renovate config
```json
  "hostRules": [
    {
      "matchHost": "https://nuget.pkg.github.com/xxx/",
      "hostType": "nuget",
      "username": "${{ secrets.GH_USER }}",
      "password": "${{ secrets.GH_TOKEN }}"
    }
  ],
```

GH Action
```yaml
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.6
        with:
          token: '${{ steps.get_token.outputs.token }}'
        env:
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: "xxx/*"
          RENOVATE_AUTODISCOVER_TOPICS: "['managed-by-renovate']"
          RENOVATE_PLATFORM: github
          RENOVATE_SECRETS: "{GH_TOKEN: '${{ secrets.GH_TOKEN }}', GH_USER: '${{ secrets.GH_USER }}'}"
```

### Logs (if relevant)

<details><summary>Logs</summary>

```

 DEBUG: Combined config
       "config": {
         "hostRules": [],
         "secrets": {
           "GH_TOKEN": "***********",
           "GH_USER": "***********"
         },
         "platform": "github",
         "token": "***********",
         "autodiscover": true,
         "autodiscoverFilter": ["xxx/*"],
         "autodiscoverTopics": ["managed-by-renovate"]

...

DEBUG: Adding password authentication for https://nuget.pkg.github.com/xxx/ (hostType=nuget) to hostRules (repository=xxx/xxx)

...

 DEBUG: Adding registry URL https://nuget.pkg.github.com/xxx/index.json (repository=xxx/xxx)
       "registryUrl": "https://nuget.pkg.github.com/xxx/index.json",
       "sourceMappedPackagePatterns": [
         "xxx.*",
         "xxx.*",
         "xxx",
         "xxx.*",
         "xxx.*",
         "Microsoft.Css.Parser",
         "xxx.*"
       ]

...

DEBUG: GET https://nuget.pkg.github.com/xxx/xxx/index.json = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=401 retryCount=0, duration=62) (repository=xxx/xxx)
DEBUG: Datasource unauthorized (repository=xxx/xxx)
       "datasource": "nuget",
       "packageName": "xxx",
       "url": "https://nuget.pkg.github.com/xxx/xxx/index.json"
DEBUG: Failed to look up nuget package xxx (repository=xxx/xxx, packageFile=xxx/xxx/xxxScripts.csproj, dependency=xxx)

```

</details>
