### DISCUSSION TITLE
Support for Kluctl

### DISCUSSION THREAD

**Discussion by justyns** [renovatebot/renovate#30794] [Suggest an Idea]
### Tell us more.

I'd like to suggest official support for [kluctl](https://github.com/kluctl/kluctl), it's similar to something like helmfile, but uses kustomize under the hood.

The docs are here: https://kluctl.io/docs/kluctl/deployments/

Some of the files are already supported by things like the kubernetes manager, but one thing I haven't figured out yet is the helm chart definitions, described here: https://kluctl.io/docs/kluctl/deployments/helm/

For example, you'll have a `helm-chart.yaml` file like this:

```yaml
helmChart:
  repo: https://kubernetes.github.io/ingress-nginx
  chartName: ingress-nginx
  chartVersion: 4.11.1
  releaseName: ingress-nginx
  namespace: ingress-nginx
```

Please let me know if there is already a way to accomplish this with existing managers.  The closest I've come so far is a custom regex manager and re-defining the repo / chartName in a comment.
