### DISCUSSION TITLE
Helm v3 - Unsupported Chart apiVersion. Only v2 is supported.

### DISCUSSION THREAD

**Discussion by JerkyTreats** [renovatebot/renovate#31059] [Request Help]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Mend Renovate hosted app on github.com

### Please tell us more about your question or problem

Given an example 

```yaml
apiVersion: v3
name: foo
version: 1.0.0
dependencies:
  - name: foo
    version: v1.0.0
    repository: https://foo.bar
```

Renovate logs give 

```
DEBUG: Unsupported Chart apiVersion. Only v2 is supported.
{
  "packageFile": "path/to/foo/Chart.yaml"
}
```

I'm using default renovate config. Is there some config that can be updated to fix or am I truly unable to use v3 charts? 

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
