### DISCUSSION TITLE
Is it possible to pin the bun version?

### DISCUSSION THREAD

**Discussion by snowleo208** [renovatebot/renovate#31149] [Request Help] [answered]
Hello all, I really wanted to use this action for our project, but we have pinned bun version in our codebase. I tried this action and realized it used the latest stable version of bun and I can't find out a way to pin the bun version.

Is it possible to run the action with a pinned bun version? Please let me know if I posted in the wrong channel!

**Comment by rarkins** [comment]
I have moved this discussion to the correct repo.

Yes it should be possible but first please provide the logs of what you're seeing today when bun runs

**Comment by github-actions** [comment]
Hi there,

This issue or discussion is missing some logs, making it difficult or impossible to help you. Depending on which situation applies follow one, some or all of these instructions.

### No logs at all
If you haven't posted any log yet, we need you to find and copy/paste the log into the issue template.

#### Finding logs on hosted app
<details><summary>Select me to read instructions</summary>

If you use the Mend Renovate app (GitHub):
1. Log in to [the Mend Developer Portal](https://developer.mend.io/)
1. Navigate to the correct organization and repository
1. Locate the appropriate log (it may not always be the latest one)
1. Copy/paste the log contents
1. Follow the steps in the **formatting your logs** section
</details>

#### Finding logs when self-hosting
<details><summary>Select me to read instructions</summary>

Read the [Renovate docs, troubleshooting, self-hosted](https://docs.renovatebot.com/troubleshooting/#self-hosted) to learn how to find the logs.
</details>

### Insufficient logs
<details><summary>Select me to read instructions</summary>

If you already gave us a log, and the Renovate team said it's not enough, then follow the instructions from the **No logs at all** section.
</details>

### Formatting your logs
<details><summary>Select me to read instructions</summary>

Please put your logs in a `<details>` and `<summary>` element like this:


    <details><summary>Select me to see logs</summary>

    ```
    Copy/paste your logs here, between the starting and ending backticks
    ```

    </details>

</details>

If you feel the logs are too large to paste here, please use a service like [GitHub Gist](https://gist.github.com/) and paste the link here.

Good luck,

The Renovate team

**Comment by snowleo208** [comment]
Hello, sorry I forgot to attach my logs!

Here is my renovate action file:

```yml
name: Renovate

env:
    NODE_VERSION: '20.11.1'

on:
    schedule:
        - cron: '0 6-9 * * 1'

jobs:
    renovate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Self-hosted Renovate
              uses: renovatebot/github-action@v40.2.6
              with:
                  configurationFile: renovate-config.js
                  node-version: ${{ env.NODE_VERSION }}
              env:
                  LOG_LEVEL: 'debug'
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BUN_VERSION: '1.0.35'
```


Here is what I saw in the Github Action logs:

```log
DEBUG: updateArtifacts for updatedPackageFiles (repository=<MY_REPO>, branch=renovate/9aa75b4e3b4)
DEBUG: bun.updateArtifacts(package.json) (repository=<MY_REPO>, branch=renovate/9aa75b4e3b4)
DEBUG: Setting CONTAINERBASE_CACHE_DIR to /tmp/renovate/cache/containerbase (repository=<MY_REPO>, branch=renovate/9aa75b4e3b4)
DEBUG: Using containerbase dynamic installs (repository=<MY_REPO>, branch=renovate/9aa75b4e3b4)
DEBUG: Resolved stable matching version (repository=<MY_REPO>, branch=renovate/9aa75b4e3b4)
       "toolName": "bun",
       "constraint": undefined,
       "resolvedVersion": "1.1.26"
DEBUG: Executing command (repository=<MY_REPO>, branch=renovate/9aa75b4e3b4)
       "command": "install-tool bun 1.1.26"
DEBUG: exec completed (repository=<MY_REPO>, branch=renovate/9aa75b4e3b4)
       "durationMs": 1957,
```

I have a `BUN_VERSION = 1.0.35` in my env, but in the pipeline, it installed bun@1.1.26 for me (i.e. `install-tool bun 1.1.26`). Maybe `BUN_VERSION` is not supported yet? Any ways to mitigate this issue?
