### DISCUSSION TITLE
Add customs labels on PR errors

### DISCUSSION THREAD

**Discussion by philippe-granet** [renovatebot/renovate#31166] [Suggest an Idea]
### Tell us more.

We use Renovate in a big platform project that consists of many projects and it's difficult to find PR where errors occurs.  
I think it would be great when Renovate have errors in a MR/PR (artifactErrors, lockFileErrors, etc...) to have possibility of adding custom label(s).
So we could:
* easily filter MR/PR by error labels where errors have occurred
* skip CI on failed MR, based on labels (CI_MERGE_REQUEST_LABELS variable for Gitlab) to prevent unnecessary build resource usage, exemple for Gitlab CI:
```
somejob:
  stage: somestage
  rules:
    - if: $CI_MERGE_REQUEST_LABELS =~ /renovate-error-label/
      when: never
    - if: $CI_MERGE_REQUEST_ID
  script:
    - echo $CI_MERGE_REQUEST_LABELS
```
