### DISCUSSION TITLE
How to use azure pipelines tasks versions provided by ou own on premise server ?

### DISCUSSION THREAD

**Discussion by mathisgauthey** [renovatebot/renovate#31252] [Request Help]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Azure

### Please tell us more about your question or problem

Hey there. I'm running Renovate inside a scheduled AzureDevOps pipeline like so : 

```
trigger: none

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight dependencies checking
    branches:
      include:
        - main

pool:
  name: default
  demands: Agent.OS -equals Linux

steps:
  - checkout: self

  - task: NodeTool@0
    displayName: Use node 20.x
    inputs:
      versionSpec: "20.x"

  - bash: |
      git config --global user.email 'bot@renovateapp.com'
      git config --global user.name 'Renovate Bot'
      npx renovate
    env:
      RENOVATE_CONFIG_FILE: $(Build.SourcesDirectory)/.azure/renovate_bot_config.json
      RENOVATE_TOKEN: $(System.AccessToken)
      LOG_LEVEL: debug
```

I do get some versions bumping PR thanks to my `renovate_bot_config.json` : 

```
{
  "platform": "azure",
  "endpoint": "https:/https://{AZURE_BASE_URL}/{ORGANIZATION_NAME}/",
  "token": "process.env.RENOVATE_TOKEN",
  "azure-pipelines": {
    "enabled": true
  },
  "repositories": [
    "{PROJECT_NAME}/{REPO_NAME}"
  ],
  "prHourlyLimit": 0,
  "baseBranches": [
    "main"
  ]
}
```

But it gets versions from the official [AzureDevOps repo](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks) using #16904, #16949 and #17050.

I hear that I can get my own versions of tasks using `https://{AZURE_BASE_URL}/{ORGANIZATION_NAME}/_apis/distributedtask/tasks?allVersions=true`, and I do.

But how can I tell Renovate to use that json file to check for versions ? I can't seem to find any information about that. Someone else started a [discussion](https://github.com/renovatebot/renovate/discussions/24820) around that topic, but it didn't get any traction.

Thanks in advance !

PS: We are using AzureDevOps Server 2022.
