### DISCUSSION TITLE
Trying to use nightly cargo

### DISCUSSION THREAD

**Discussion by TimDiekmann** [renovatebot/renovate#31264] [Request Help]
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Self-hosted (Mainly to test things out, the issue should happen on the hosted version as well)

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitHub through GitHub Actions

### Please tell us more about your question or problem

I'm trying to use a nightly version of cargo so I can use unstable features. Currently, I'm particularly interested in public dependencies and the 2024 edition, but there are several other unstable cargo features which is interesting to people. Renovate currently uses the latest Rust stable release to install cargo, but stable cargo cannot use unstable features. After digging quite a bit I found out that in theory, I could set `constraints` in the configuration, so I tried multiple things such as:
```json
{
	"constraints": {
		"rust": "nightly-2024-09-02"
	}
}
```
or 
```json
{
	"constraints": {
		"rust": "nightly"
	}
}
```

Both are valid tokens passed to rustup, however, Rustup doesn't seem to be used to install the toolchain. Instead, it fails the constraint validation and continues with the latest stable release.
Is it possible to somehow specify a nightly Cargo? If not, would it be hard to support that? The relevant code section seems to be in this function: https://github.com/renovatebot/renovate/blob/e064c5e40da736aeb598eec9897e9f9313dc4477/lib/util/exec/containerbase.ts#L276

### Logs

```
DEBUG: Using containerbase dynamic installs (repository=TimDiekmann/hash, branch=deps/rs/async-trait-0.x-lockfile)
 WARN: Invalid tool constraint (repository=TimDiekmann/hash, branch=deps/rs/async-trait-0.x-lockfile)
       "toolName": "rust",
       "constraint": "nightly-2024-09-02",
       "versioning": "semver"
DEBUG: getLabels(https://index.docker.io,/ library/rust, latest) (repository=TimDiekmann/hash, branch=deps/rs/async-trait-0.x-lockfile)
DEBUG: Docker Hub library image - skipping label lookup (repository=TimDiekmann/hash, branch=deps/rs/async-trait-0.x-lockfile)
DEBUG: Resolved stable matching version (repository=TimDiekmann/hash, branch=deps/rs/async-trait-0.x-lockfile)
       "toolName": "rust",
       "constraint": undefined,
       "resolvedVersion": "1.81.0"
DEBUG: Executing command (repository=TimDiekmann/hash, branch=deps/rs/async-trait-0.x-lockfile)
       "command": "install-tool rust 1.81.0"
DEBUG: exec completed (repository=TimDiekmann/hash, branch=deps/rs/async-trait-0.x-lockfile)
       "durationMs": 22265,
       "stdout": "[18:31:59.544] INFO (107): Installing tool rust@1.81.0...\ninstalling v2 tool rust v1.81.0\ninstall: creating uninstall script at /opt/containerbase/tools/rust/1.81.0/lib/rustlib/uninstall.sh\ninstall: installing component 'cargo'\ninstall: installing component 'rust-std-x86_64-unknown-linux-gnu'\ninstall: installing component 'rustc'\ninstall: WARNING: failed to run ldconfig. this may happen when not installing as root. run with --verbose to see the error\n\n    rust installed.\n\nlinking tool rust v1.81.0\ncargo 1.81.0 (2dbb1af80 2024-08-20)\nrustc 1.81.0 (eeb90cda1 2024-09-04)\n[18:32:21.155] INFO (107): Install tool rust succeeded in 21.6s.\n",
       "stderr": ""
DEBUG: Executing command (repository=TimDiekmann/hash, branch=deps/rs/async-trait-0.x-lockfile)
       "command": "cargo update --config net.git-fetch-with-cli=true --manifest-path Cargo.toml --workspace"
DEBUG: rawExec err (repository=TimDiekmann/hash, branch=deps/rs/async-trait-0.x-lockfile)
       "err": {
         "cmd": "/bin/sh -c cargo update --config net.git-fetch-with-cli=true --manifest-path Cargo.toml --workspace",
         "stderr": "error: failed to load manifest for workspace member `/tmp/renovate/repos/github/TimDiekmann/hash/apps/hash-graph/bins/cli`\nreferenced by workspace at `/tmp/renovate/repos/github/TimDiekmann/hash/Cargo.toml`\n\nCaused by:\n  failed to load manifest for dependency `authorization`\n\nCaused by:\n  failed to parse manifest at `/tmp/renovate/repos/github/TimDiekmann/hash/libs/@local/hash-authorization/Cargo.toml`\n\nCaused by:\n  feature `public-dependency` is required\n\n  The package requires the Cargo feature called `public-dependency`, but that feature is not stabilized in this version of Cargo (1.81.0 (2dbb1af80 2024-08-20)).\n  Consider trying a newer version of Cargo (this may require the nightly release).\n  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#public-dependency for more information about the status of this feature.\n",
         "stdout": "",
         "options": {
           "cwd": "/tmp/renovate/repos/github/TimDiekmann/hash",
           "encoding": "utf-8",
           "env": {
             "GIT_CONFIG_KEY_0": "url.https://**redacted**@github.com/.insteadOf",
             "GIT_CONFIG_VALUE_0": "ssh://**redacted**@github.com/",
             "GIT_CONFIG_KEY_1": "url.https://**redacted**@github.com/.insteadOf",
             "GIT_CONFIG_VALUE_1": "git@github.com:",
             "GIT_CONFIG_KEY_2": "url.https://**redacted**@github.com/.insteadOf",
             "GIT_CONFIG_VALUE_2": "https://github.com/",
             "GIT_CONFIG_COUNT": "3",
             "HOME": "/home/ubuntu",
             "PATH": "/home/ubuntu/.local/bin:/home/ubuntu/bin:/home/ubuntu/.local/bin:/home/ubuntu/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
             "LC_ALL": "C.UTF-8",
             "LANG": "C.UTF-8",
             "RUSTUP_TOOLCHAIN": "nightly",
             "CONTAINERBASE_CACHE_DIR": "/tmp/renovate/cache/containerbase"
           },
           "maxBuffer": 10485760,
           "timeout": 900000
         },
         "exitCode": 101,
         "name": "ExecError",
         "message": "Command failed: cargo update --config net.git-fetch-with-cli=true --manifest-path Cargo.toml --workspace\nerror: failed to load manifest for workspace member `/tmp/renovate/repos/github/TimDiekmann/hash/apps/hash-graph/bins/cli`\nreferenced by workspace at `/tmp/renovate/repos/github/TimDiekmann/hash/Cargo.toml`\n\nCaused by:\n  failed to load manifest for dependency `authorization`\n\nCaused by:\n  failed to parse manifest at `/tmp/renovate/repos/github/TimDiekmann/hash/libs/@local/hash-authorization/Cargo.toml`\n\nCaused by:\n  feature `public-dependency` is required\n\n  The package requires the Cargo feature called `public-dependency`, but that feature is not stabilized in this version of Cargo (1.81.0 (2dbb1af80 2024-08-20)).\n  Consider trying a newer version of Cargo (this may require the nightly release).\n  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#public-dependency for more information about the status of this feature.\n",
         "stack": "ExecError: Command failed: cargo update --config net.git-fetch-with-cli=true --manifest-path Cargo.toml --workspace\nerror: failed to load manifest for workspace member `/tmp/renovate/repos/github/TimDiekmann/hash/apps/hash-graph/bins/cli`\nreferenced by workspace at `/tmp/renovate/repos/github/TimDiekmann/hash/Cargo.toml`\n\nCaused by:\n  failed to load manifest for dependency `authorization`\n\nCaused by:\n  failed to parse manifest at `/tmp/renovate/repos/github/TimDiekmann/hash/libs/@local/hash-authorization/Cargo.toml`\n\nCaused by:\n  feature `public-dependency` is required\n\n  The package requires the Cargo feature called `public-dependency`, but that feature is not stabilized in this version of Cargo (1.81.0 (2dbb1af80 2024-08-20)).\n  Consider trying a newer version of Cargo (this may require the nightly release).\n  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#public-dependency for more information about the status of this feature.\n\n    at ChildProcess.<anonymous> (/usr/local/renovate/lib/util/exec/common.ts:101:11)\n    at ChildProcess.emit (node:events:531:35)\n    at ChildProcess.emit (node:domain:488:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:294:12)"
       },
```

**Comment by rarkins** [comment]
Renovate's tooling is controlled by https://github.com/containerbase/base

Currently Containerbase does not use rustup

**Reply by TimDiekmann** [reply]
I see, thank you. Is there a plan to support rustup?

**Reply by rarkins** [reply]
No, but contributions or research into it would be welcomed

**Reply by viceice** [reply]
BTW: it's not a bug, it's intentional 😉

**Reply by TimDiekmann** [reply]
I'm not really aware of the codebase, but I guess this would be required:
- Add a fallback to the `constraints` check for Rust if the passed value is not a valid SemVer version, i.e. if passed `^1.62` it will use it as a SemVer check, but don't bail if `nightly` is passed.
- When invoking `install_tool rust <VERSION>` don't use the static page to download Rust, but instead `wget -q -O- https://sh.rustup.rs | sh -s -- -y --default-toolchain <VERSION> --profile minimal` instead. As an alternative, it's also possible to pass `none` to the `--default-toolchain` argument and then invoke `rustup show`, this implies that rustup will detect the toolchain for you (i.e. it will consider the `RUSTUP_TOOLCHAIN` environment variables or `rust-toolchain.toml`)

**Reply by TimDiekmann** [reply]
> BTW: it's not a bug, it's intentional 😉

Could you elaborate on why?

**Reply by viceice** [reply]
we don't want to use rust up because we're in work to use our own mirror for all tooling and we can't control the rust up download urls.

**Reply by TimDiekmann** [reply]
Ah, fair enough. So I guess you will never support installing nightly toolchains? Note, that this will lock out all users who want to use unstable cargo options.

**Comment by TimDiekmann** [comment]
I was able to work around this, but I think that's not really a great solution.
1. I installed Rust manually using rustup in the CI
2. I changed the owner for the installation
3. I mapped the volume of the rust installation
4. I changed the `PATH` variable to include the installation folder

```yml

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Install Rust toolchain
        # This uses our `rust-toolchain.toml`, use whatever you need to install your desired toolchain
        uses: ./.github/actions/install-rust-toolchain

      - name: Change owner for cargo
        run: sudo chown -R runneradmin:root /home/runner/.cargo/

      - name: Run renovate
        uses: renovatebot/github-action@v40.2.7
        with:
          token: ${{ steps.app-token.outputs.token }}
          configurationFile: .github/renovate.json
          docker-volumes: |
            /tmp:/tmp ;
            /home/runner/.cargo:/home/ubuntu/.cargo ;
        env:
          RENOVATE_ALLOWED_ENV: '["PATH"]'
          RENOVATE_ENV: '{"PATH":"/home/ubuntu/.cargo/bin:/home/ubuntu/.local/bin:/home/ubuntu/bin:/home/ubuntu/.local/bin:/home/ubuntu/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}'
```
