### DISCUSSION TITLE
Renovate Bot didn't detect Version Upgrades

### DISCUSSION THREAD

**Discussion by amrap030** [renovatebot/renovate#31333] [Request Help]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

renovatebot/github-action@dd4d265eb8646cd04fc5f86ff8bc8d496d75a251 # v40.2.8

### Please tell us more about your question or problem

Hello together,

I would like to clarify, why renovate didn't register some package updates in my case. Every day I use the github action to detect package updates in my Kubernetes GitOps repository. Renovate detected the following update:

```yaml
apiVersion: v2
name: minio
version: 0.0.0
dependencies:
  - name: minio
    version: 14.7.7 # previously 14.7.6
    repository: https://charts.bitnami.com/bitnami
```

Then I looked into the code of minio what has been changed and noticed, that also some docker containers have been updated in the `values.yaml` file. Now my question is, why does renovate only notice the change in the `Chart.yaml` file but not in the `values.yaml` file? My `values.yaml` file has the following entries:

```yaml
minio:
  ...
  clientImage:
    registry: <harbor proxy cache url>
    repository: bitnami/minio-client
    tag: 2024.8.29-debian-12-r1 # should detect 2024.9.9-debian-12-r0
    digest: ""
  ...
```

I am not sure if it has something to do with the harbor proxy cache we are using internally in our company, but sometimes I get new version updates even for the docker images used through the proxy cache.

This is my configuration file:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": ["config:best-practices"],
  "dependencyDashboard": true,
  "helm-values": {
    "fileMatch": ["cluster/.+\\.ya?ml$"]
  },
  "kubernetes": {
    "fileMatch": ["cluster/.+\\.ya?ml$"]
  },
  "prHourlyLimit": 30,
  "prConcurrentLimit": 30,
  "enabledManagers": [
    "dockerfile",
    "github-actions",
    "helm-values",
    "helmv3",
    "kubernetes",
    "terraform",
    "terragrunt",
    "ansible"
  ],
  "vulnerabilityAlerts": {
    "addLabels": ["security"]
  }
}
```
