### DISCUSSION TITLE
poetry update --lock with google artifacts and workload identity

### DISCUSSION THREAD

**Discussion by JoelDimbernat** [renovatebot/renovate#31463] [Request Help] [answered]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Github / Renovate 38.82.0

### Please tell us more about your question or problem

I have a project managed with poetry. When a dependency needs to be updated, in the PR, renovate fails to update the lock file during the artifact update step.

It says that it's not authorized to get a dependency (not the one being update) from our private registry.

Renovate runs on a GKE cluster, the pod uses a service account, this service account is configure to work with Workload Identity to be able to access Google Artifact Registry.

It all looks like poetry doesn't use Workload Identity.

How can I fix this?

### Logs (if relevant)

<details><summary>Logs</summary>

What we get in the PR:
```

Updating dependencies
Resolving dependencies...

Source (<Redacted>): Authorization error accessing https://europe-python.pkg.dev/<redacted>/<redacted>/simple/<redacted>/

Package redacted (1.5.0) not found.


```

in the logs:
```
Command failed: poetry update --lock --no-interaction SQLAlchemy\nCreating virtualenv redacted-brgus_xE-py3.11 in /home/ubuntu/.cache/pypoetry/virtualenvs\nSource (Redacted): Authorization error accessing https://europe-python.pkg.dev/<redacted>/<redacted>/simple/<redacted>/\n\nPackage <redacted> (1.5.0) not found.\n
```
</details>

**Comment by rarkins** [comment]
You first need to answer "Can Poetry use Workload Identity?" (i.e. independently of Renovate)

If Poetry can't use workload identity directly then the question would be: how does Poetry authenticate with your registry elsewhere (e.g. developer machines, CI/CD, etc)?

**Reply by JoelDimbernat** [reply]
Poetry can use workload identity when you install the package `keyrings.google-artifactregistry-auth` before.

How would you do that with renovate? I guess it should happen right after `install-tool poetry x.x.x`

**Reply by JoelDimbernat** [reply]
demonstration in a pod using a service account and workload identity:

Without `keyrings.google-artifactregistry-auth`
```
root@test-wi:/usr/src/app# poetry install
Creating virtualenv app-VA82Wl8V-py3.12 in /root/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (0.6s)Source (Redacted): Authorization error accessing https://europe-python.pkg.dev/redacted-registry/redacted/simple/redacted/


Because app depends on redacted (1.5.0) which doesn't match any versions, version solving failed.
```
Then with `keyrings.google-artifactregistry-auth`:
```
root@test-wi:/usr/src/app# poetry self add keyrings.google-artifactregistry-auth
Using version ^1.1.2 for keyrings-google-artifactregistry-auth

Updating dependencies
Resolving dependencies... (2.4s)

Package operations: 7 installs, 0 updates, 0 removals

  - Installing pyasn1 (0.6.1)
  - Installing cachetools (5.5.0)
  - Installing pyasn1-modules (0.4.1)
  - Installing rsa (4.9)
  - Installing google-auth (2.34.0)
  - Installing pluggy (1.5.0)
  - Installing keyrings-google-artifactregistry-auth (1.1.2)

Writing lock file
root@test-wi:/usr/src/app# poetry install
Updating dependencies
Resolving dependencies... Downloading https://europe-python.pkg.dev/redacted-registry/redacted/redacted/redacted-1.5.0-cp38-cp38-linux_x86_64.whl#sha256=
Resolving dependencies... (1.7s)

Package operations: 3 installs, 0 updates, 0 removals

  - Installing cython (0.29.32)
  - Installing networkx (2.8.5)
  - Installing redacted (1.5.0)

Writing lock file

Installing the current project: app (0.1.0)
```

**Reply by rarkins** [reply]
If you're self hosted then you can customize your Renovate image to add this tool and see if that's enough. If you confirm that then we can decide what to do next. It does not seem appropriate to install only for poetry if it's a generic tool. It also needs special handling if must be installed as root.

**Reply by JoelDimbernat** [reply, marked as answer]
What ended up working for us:

```
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-bot
spec:
  suspend: false
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: renovate
          containers:
            - image: renovate/renovate:38.82.0
              name: renovate-bot
              command:
                - /bin/bash
                - '-c'
              args:
                - |
                  install-tool python 3.11.4
                  install-tool poetry 1.8.3
                  CONTAINER_BASE_CACHE_DIR=/tmp/renovate/cache/containerbase PIP_CACHE_DIR=/tmp/renovate/cache/others/pip poetry self add keyrings.google-artifactregistry-auth
                  renovate
              envFrom:
                - secretRef:
                    name: renovate-tokens
              env: 
                - name: RENOVATE_BASE_DIR
                  value: '/tmp/renovate/'
                - name: RENOVATE_CONFIG_FILE
                  value: '/opt/renovate/config.json'
                - name: LOG_LEVEL
                  value: debug
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
```

Setting `CONTAINER_BASE_CACHE_DIR` and `PIP_CACHE_DIR` before installing `keyrings.google-artifactregistry-auth` was key here.
