### DISCUSSION TITLE
Workaround for Feature Request [#21987] - Regex Manager Support for Azure DevOps Pipeline in Renovate

### DISCUSSION THREAD

**Discussion by cospeedster** [renovatebot/renovate#31465] [Request Help] [answered]
### What would you like help with?

Other

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Azure DevOps Server

### Please tell us more about your question or problem

While waiting for the feature request in [issue #21987](https://github.com/renovatebot/renovate/issues/21987) to be implemented, I am looking for an alternative solution. Specifically, I am considering using a regex manager for an Azure DevOps pipeline that runs Renovate. 

I'm really new to renovate so this approach does not work yet.

I would greatly appreciate your input. Can you please help me out?

Azure pipeline `test-pipeline.yaml`:
```yaml
schedules:
  - cron: "0 * * * *"
    displayName: cron
    branches:
      include:
        - main
    always: true
    batch: false

pool: <redacted-docker-agent-pool>

jobs:
  - job: renovate
    displayName: 'Renovate'
    container:
      image: <redacted-private-proxy-registry>/renovatebot/renovate:38
      # Needed by azure devops agent to add users etc
      options: --user 0
    steps:
      - checkout: self

      - bash: |
          renovate-config-validator --strict
        displayName: 'Validate config'

      - bash: |
          renovate
        displayName: 'Run renovate'
        env:
          # Renovate configuration options
          RENOVATE_TOKEN: $(System.AccessToken)
          LOG_LEVEL: "debug"
```

Excerpts from my tries in the repository's `renovate.json`:

```json
  "customManagers": [
    {
      "customType": "regex",
      "description": "Update container job images in azure-pipelines.yaml",
      "fileMatch": ["(^|/)azure-pipelines.ya?ml$", "(^|/)test-pipeline.ya?ml$"],
      "matchStrings": [
        "\\s*image:\\s+(?<packageName>[\\w\\-\\./]+)(?::(?<currentValue>[\\w\\.\\-]+))?(?:@(?<currentDigest>[A-Za-z0-9:]+))?"
      ],
      "versioningTemplate": "docker",
      "datasourceTemplate": "docker"
    }
  ]
```

```json
  "customManagers": [
    {
      "customType": "regex",
      "description": "Update container job images in azure-pipelines.yaml",
      "fileMatch": ["(^|/)azure-pipelines.ya?ml$", "(^|/)test-pipeline.ya?ml$"],
      "matchStrings": [
        "image:\\s*(?<depName>[\\w.-]+(?:\\/[\\w.-]+)+):(?<currentValue>\\d+\\.\\d+\\.\\d+)"
      ],
      "depNameTemplate": "{{{depName}}}",
      "versioningTemplate": "docker",
      "extractVersionTemplate": "{{{currentValue}}}",
    }
  ]
```

### Logs (if relevant)

<details><summary>Log excerpts</summary>

From second snippet:
```

DEBUG: packageFiles with updates (repository=OSI_Integrator/huthco_renovate, baseBranch=main)
       "config": {
         "regex": [
           {
             "deps": [
               {
                 "depName": "<redacted-private-proxy-registry>/renovatebot/renovate",
                 "currentValue": "36.0.0",
                 "datasource": "docker",
                 "versioning": "docker",
                 "extractVersion": "36.0.0",
                 "replaceString": "image: <redacted-private-proxy-registry>/renovatebot/renovate:36.0.0",
                 "updates": [],
                 "packageName": "<redacted-private-proxy-registry>/renovatebot/renovate",
                 "warnings": [],
                 "sourceUrl": "[https://github.com/renovatebot/renovate",](https://github.com/renovatebot/renovate%22,)
                 "registryUrl": "<redacted-private-proxy-registry>",/
                 "homepage": "https://renovatebot.com",/
                 "lookupName": "renovatebot/renovate"
               }
             ],
             "matchStrings": [
               "image:\\s*(?<depName>[\\w.-]+(?:\\/[\\w.-]+)+):(?<currentValue>\\d+\\.\\d+\\.\\d+)"
             ],
             "depNameTemplate": "{{{depName}}}",
             "datasourceTemplate": "docker",
             "versioningTemplate": "docker",
             "extractVersionTemplate": "{{{currentValue}}}",
             "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
             "packageFile": "test-pipeline.yaml"
           }
         ]
       }
```

</details>

**Comment by cospeedster** [comment, marked as answer]
This works for me:

```yaml

{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "customManagers": [
    {
      "customType": "regex",
      "description": "Update container job images in azure-pipelines.yaml",
      "fileMatch": ["(^|/)azure-pipelines.ya?ml$"],
      "matchStrings": [
        "image:\\s+(?<depName>[^\\s:@\\\"]+):(?<currentValue>[-a-zA-Z0-9.]+)(?:@(?<currentDigest>sha256:[a-zA-Z0-9]+))?"
      ],
      "autoReplaceStringTemplate": "image: {{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
      "datasourceTemplate": "docker"
    }
  ]
}

```
