### DISCUSSION TITLE
Problem with packageSourceMapping in nuget.config

### DISCUSSION THREAD

**Discussion by David198** [renovatebot/renovate#31489] [Request Help] [answered]
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Azure Pipeline npm renovate@38.89.2

### Please tell us more about your question or problem

Im running renovate from cli in an azure pipeline. In the root of my repository I have the following nuget.config placed

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <clear />
        <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
        <add key="Azure-Internal" value="https://pkgs.dev.azure.com/**redacted**/nuget/v3/index.json" />
    </packageSources>
    <packageSourceMapping>
        <packageSource key="nuget.org">
            <package pattern="*" />
        </packageSource>
        <packageSource key="Azure-Internal">
            <package pattern="Company.*" />
        </packageSource>
    </packageSourceMapping>
</configuration>
```

Locally and in other CI pipelines this works just fine.

But somehow the packagesourcemapping for the internal feed is not recognized correctly from renovate. Renovate sets it to undefined (see logs) and therefore the internal packages are searched in the public nuget.org feed.

Can you please help me pinpoint my problem or is this a new bug?

I found also this discussion https://github.com/renovatebot/renovate/discussions/29436 <-- where it seems to work quite fine with similar nuget.config file.

My **config.js** 

```js
module.exports = {
    $schema: "https://docs.renovatebot.com/renovate-schema.json",
    repositories: ["**redacted**"],
    extends: ["config:recommended", ":semanticCommits"],
};
```

and my **renovate.json5** in the repository

```json
{
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "enabledManagers": [
        "npm",
        "nuget"
    ]
}
```

**Yaml pipeline used**

```yml

trigger: none

pool:
  vmImage: 'ubuntu-latest' # also tried with windows-latest

variables:
- group: GithubSecrets

steps:
  - checkout: self
    persistCredentials: true
    clean: true

  - task: UseNode@1
    inputs:
      version: "20.17.0"
    displayName: "Install Node.js"

  - task: npmAuthenticate@0
    displayName: 'Npm Authenticate'
    inputs:
      workingFile: .npmrc

  - task: NuGetAuthenticate@1    # also tried without this task 
    displayName: 'NuGet Authenticate'

  - bash: |
      git config --global user.email 'renovatebot@company.de'
      git config --global user.name 'Renovate Bot'
      npx renovate
    displayName: Run renovate Bot
    env:
      RENOVATE_PLATFORM: azure
      RENOVATE_ENDPOINT: $(System.CollectionUri)
      RENOVATE_TOKEN: $(System.AccessToken)
      LOG_LEVEL: debug
      GITHUB_COM_TOKEN: $(GITHUB_COM_TOKEN)
      RENOVATE_ONBOARDING_CONFIG_FILE_NAME: "renovate.json5"
      RENOVATE_GIT_AUTHOR: "Renovate Bot <renovatebot@company.de>"

```

One last thing I tried was checking out this repo and run the test defined in https://github.com/renovatebot/renovate/blob/c45a20a0c19836fe4723e32fa74c058373807ff7/lib/modules/manager/nuget/util.spec.ts#L35
locally with my nuget.config. This test is green, so it seems that somehow it has to do with the azure pipeline, but I don't know what the problem could be... any help much appreciated. This is the last problem to finalize renovate integration.

### Logs (if relevant)

<details><summary>Logs</summary>

```

DEBUG: Found NuGet.config at nuget.config (repository=**redacted**)
DEBUG: clearing registry URLs (repository=**redacted**)
DEBUG: Adding registry URL https://api.nuget.org/v3/index.json (repository=**redacted**)
       "registryUrl": "https://api.nuget.org/v3/index.json",
       "sourceMappedPackagePatterns": ["*"]
DEBUG: Adding registry URL https://pkgs.dev.azure.com/**redacted**/nuget/v3/index.json (repository=**redacted**)
       "registryUrl": "https://pkgs.dev.azure.com/**redacted**/nuget/v3/index.json",
       "sourceMappedPackagePatterns": undefined


```

</details>
