### DISCUSSION TITLE
matched groups in handlebars replace at infix pos

### DISCUSSION THREAD

**Discussion by Stefanqn** [renovatebot/renovate#31570] [Request Help]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab

### Please tell us more about your question or problem

I'm trying to match nextcloud/server image version within a `values.yaml`. Due to marked (non-pre-release) github-releases, I'd like to match for github releases, not docker. Yet, the docker image has specific tags, e.g. `28.0.10-fpm` or `28.0.10-apache`. So I need to match the version but update the tag by adding a suffix.

The values.nextcloud.yaml begins with 
```yaml
image:
  # renovate: source=github-releases repo=nextcloud/server vSuffix=-apache
  tag: 29.0.6-apache
```
my `renovate.json5` contains:
```json5
  customManagers: [
    {
      customType: 'regex',
      fileMatch: [
        'values.nextcloud.yaml'
      ],
      matchStrings: [
        '# renovate: source=(?<datasource>[a-z-]+?) repo=(?<depName>[^\\s]+?)(?: vSuffix=(?<vSuffix>[^\\s]+?))?(?: versioning=(?<versioning>[^\\s]+?))?[\\t\\s]*\\r?\\n[\\t\\s]*(?m)^[ ]*[^\\r\\n:]+?\\s*:\\s*(?<currentValue>\\S+)',
      ],
      currentValueTemplate: "{{{ replace '-apache' '' currentValue }}}"
}
```

Replacing with hard coded '-apache' works, but if I try to use the matched group `vSuffix`, it doesn't.

What am I doing wrong or is it a bug?

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>

**Comment by rarkins** [comment]
You should be using versionCompatibility and not manipulating currentValue that way

**Reply by Stefanqn** [reply]
I just tried it, but adding
```yaml
    {
      "matchDatasources": ["github-releases"],
      "matchPackageNames": ["nextcloud/server"],
      "versionCompatibility": "^(?<version>[^-]+)(?<compatibility>-[^\\s]+)?$",
      "versioning": "semver"
    }
```
to 
```yaml
image:
  # renovate: source=github-releases repo=nextcloud/server
  tag: 29.0.6-apache
```
doesn't find any updates.

The logs contain:
```
       "versionCompatibility": "^(?<version>[^-]+)(?<compatibility>-[^\\s]+)?",
       "currentValue": "29.0.6-apache",
       "packageName": "nextcloud/server",
       "groups": {"version": "29.0.6", "compatibility": "-apache"}
```
and 
```
"regex": [
           {
             "deps": [
               {
                 "depName": "nextcloud/server",
                 "currentValue": "29.0.6-apache",
                 "datasource": "github-releases",
                 "replaceString": "# renovate: source=github-releases repo=nextcloud/server\n  tag: 29.0.6-apache",
                 "updates": [],
                 "packageName": "nextcloud/server",
                 "versioning": "semver",
                 "warnings": [],
                 "sourceUrl": "https://github.com/nextcloud/server",
                 "registryUrl": "https://github.com"
               }
             ],
             "matchStrings": [
               "# renovate: source=(?<datasource>[a-z-]+?) repo=(?<depName>[^\\s]+?)(?: versioning=(?<versioning>[^\\s]+?))?[\\t\\s]*\\r?\\n[\\t\\s]*(?m)^[ ]*[^\\r\\n:]+?\\s*:\\s*(?<currentValue>\\S+)"
             ],
             "packageFile": "app/nextcloud/values.nextcloud.yaml"
           }
         ]
```

**Reply by rarkins** [reply]
Apply versionCompatibility using packageRules and not customManagers. An alternative to this would be setting versioningTemplate=docker

**Reply by Stefanqn** [reply]
I did apply the versionCompatibility using package rules and now explicitly added docker versioning without success:
```yaml
{
  "packageRules": [
    {
      "matchDatasources": ["github-releases"],
      "matchPackageNames": ["nextcloud/server"],
      "versionCompatibility": "^(?<version>[^-]+)(?<compatibility>-[^\\s]+)?$",
      "versioning": "docker"
    }
  ]
}
```

In another run, I removed `"versioning": "docker"` from the packageRules and added `versioningTemplate: "docker"` to the regex customManagers, also without success.
