### DISCUSSION TITLE
Match registry URL in package rules

### DISCUSSION THREAD

**Discussion by msullivan613** [renovatebot/renovate#31625] [Request Help]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Github - Renovate v38.93.3

### Please tell us more about your question or problem

We are looking for ways to delay updates to open-source packages but at the same time not apply these delays to our internal packages. I believe I could do this using the [`minimumReleaseAge` option](https://docs.renovatebot.com/configuration-options/#minimumreleaseage), but the issue is setting this option specifically for open-source packages.

As an example, I can configure the `pyproject.toml` for a Python package with something like this:
```toml
[tool.poetry]
name = "foo"
version = "1.0.0"

[tool.poetry.dependencies]
python = "^3.12"

[[tool.poetry.source]]
name = "remote-for-open-source"
url = "https://my-artifactory.com/artifactory/api/pypi/pypi-remote/simple"
priority = "primary"

[[tool.poetry.source]]
name = "internal-packages"
url = "https://my-artifactory.com/artifactory/api/pypi/pypi-local/simple"
priority = "supplemental"
```

And then I have the following Renovate config to go with it:
```json
{
    "packageRules": [
        {
            "matchDatasources": ["pypi"],
            "registryUrls": [
                "https://my-artifactory.com/artifactory/api/pypi/pypi-remote/simple",
                "https://my-artifactory.com/artifactory/api/pypi/pypi-local/simple"
            ]
        }
    ]
}
```

I noticed that there's not a  `matchRegistryUrls` `packageRule` option, but that's basically what I'm looking for. How can I add an additional `packageRule` that looks something like this:
```json
{
    "minimumReleaseAge": "1 week",
    "matchRegistryUrls": ["https://my-artifactory.com/artifactory/api/pypi/pypi-remote/simple"]
}
```

Thank you!

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
