### DISCUSSION TITLE
chartfile.yaml support

### DISCUSSION THREAD

**Discussion by ushitora-anqou** [renovatebot/renovate#31672] [Suggest an Idea]
### Tell us more.

Grafana Tanka uses `chartfile.yaml` to track Helm chart versions, and I'd like to request support for this in Renovate.

Here's an example of `chartfile.yaml` (taken from https://tanka.dev/helm/):
```yaml
version: 1
directory: charts
repositories:
  - name: stable
    url: https://charts.helm.sh/stable
requires:
  - chart: stable/mysql
    directory: 1.6.7
    version: 1.6.7
  - chart: stable/mysql
    directory: 1.6.8
    version: 1.6.8
```
