### DISCUSSION TITLE
how do I use with gradle and a github maven repository?

### DISCUSSION THREAD

**Discussion by xenoterracide** [renovatebot/renovate#31713] [Request Help]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Mend Renovate hosted app on github.com

### Please tell us more about your question or problem

for a github maven repository you need to use the actor/token github creates with the job in download scenario. It's still a "public" repository, they just force you to use credentials, but one should be able to pull with any github account. In order to use these credentials I then have to map them into a username password that gradle understands. I do this in my github jobs as follows.

```yml
    env:
      ORG_GRADLE_PROJECT_ghUsername: ${{ secrets.GITHUB_ACTOR }}
      ORG_GRADLE_PROJECT_ghPassword: ${{ secrets.GITHUB_TOKEN }}
```

Renovate does run, but if it's actually capable of updating locks it can't because of the failure. It just fails like dependabot does, with missing credentials, and/or inability to proceed due to a mismatch on the locks.

How can I configure these? do I need to use the github action? if so, does this require that I use a config.js and script the environment access?
