### DISCUSSION TITLE
Dash "-" before "uses: docker://" in github actions is not supported?

### DISCUSSION THREAD

**Discussion by dadezzz** [renovatebot/renovate#31736] [Request Help]
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Mend Renovate hosted app on github.com

### Please tell us more about your question or problem

Looking at [the regex](https://github.com/renovatebot/renovate/blob/135e71017e4f2e934c15748e7fd178fb02790ff4/lib/modules/manager/github-actions/extract.ts#L16) for the GitHub actions manager, I don't think it's possible to write a step like this:

```yaml
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: docker://docker.io/pipelinecomponents/hadolint:0.26.4
        with:
          args: -c "find . -name 'Dockerfile' | while read f ; do hadolint \"$f\" ; done"
          entrypoint: sh
```

The regex doesn't match the `uses: docker://` line because of the dash in front of it.

Would it be possible to copy the start of the regex from the [line below](https://github.com/renovatebot/renovate/blob/135e71017e4f2e934c15748e7fd178fb02790ff4/lib/modules/manager/github-actions/extract.ts#L18) to the docker one?

### Minimal reproduction

https://github.com/dvdzara/renovate-reproduction-31736
