### DISCUSSION TITLE
Need help with versioning string for checkmk

### DISCUSSION THREAD

**Discussion by gilly42** [renovatebot/renovate#31825] [Request Help] [answered]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

gitlab

### Please tell us more about your question or problem

Hello,

I try to let renovate update my checkmk version. I use the custom manager and major updates are working, but patch level not (patch means at checkmk the number behind the p, not the thrid number) so its not a real semver and semver-coerced also doen't work) I tried a lot, here a minimal example that I like to work:

renovate.json
```yaml
{
 "$schema": "https://docs.renovatebot.com/renovate-schema.json",
 "extends": ["config:recommended"],
 "packageRules": [
   {
     "matchManagers": ["custom.regex"],
     "matchPackageNames": ["checkmk/checkmk"],
     "versioning": "regexp:^v(?<major>\\d+)\\.(?<minor>\\d+)\\.0(p(?<patch>\\d+))?$"
   }
 ],
 "customManagers": [
   {
      "customType": "regex",
      "fileMatch": ["^working.playbook.yml$"],
      "matchStrings": ["#\\s*renovate:\\s*(datasource=(?<datasource>.*?) )?depName=(?<depName>.*?)( versioning=(?<versioning>.*?))?\\s*\\w*:\\s*(?<currentValue>.*)\\s?"],
      "versioningTemplate": "{{#if versioning}}{{{versioning}}}{{else}}semver{{/if}}"
    }
 ]
}
```
working.playbook.yml part
```yaml
...
  vars:
    # renovate: datasource=github-tags depName=checkmk/checkmk
    checkmk_version: v2.3.0p1
...
```

I think only semver-coerced is taken for the compare and the in the 2.3.0p16 the p16 is ignored.
Does anybody has an Idea?

### Logs (if relevant)

<details><summary>Logs</summary>
...
```
DEBUG: packageFiles with updates (repository=local)
       "config": {
         "regex": [
           {
             "deps": [
               {
                 "depName": "checkmk/checkmk",
                 "currentValue": "v2.3.0p1",
                 "datasource": "github-tags",
                 "versioning": "regexp:^v(?<major>\\d+)\\.(?<minor>\\d+)\\.0(p(?<patch>\\d+))?$",
                 "replaceString": "# renovate: datasource=github-tags depName=checkmk/checkmk\n    checkmk_version: v2.3.0p1\n",
                 "updates": [],
                 "packageName": "checkmk/checkmk",
                 "warnings": [],
                 "sourceUrl": "https://github.com/checkmk/checkmk",
                 "registryUrl": "https://github.com",
                 "currentVersion": "v2.3.0p1",
                 "currentVersionTimestamp": "2024-09-24T14:35:23.000Z",
                 "fixedVersion": "v2.3.0p1"
               }
             ],
             "matchStrings": [
               "#\\s*renovate:\\s*(datasource=(?<datasource>.*?) )?depName=(?<depName>.*?)( versioning=(?<versioning>.*?))?\\s*\\w*:\\s*(?<currentValue>.*)\\s?"
             ],
             "versioningTemplate": "{{#if versioning}}{{{versioning}}}{{else}}semver{{/if}}",
             "packageFile": "working.playbook.yml"
           }
         ]
       }
TRACE: branches (repository=local)
```
...
</details>

**Comment by seraphblade2010** [comment]
+1, I also use CheckMK and cant figure out how to implement the versioning string correctly.

**Comment by rarkins** [comment]
Try setting either:
- versioning=loose
- regex versioning, making use of the "build" capture group for the `p` part (make sure it's optional)

If that doesn't work, please create a reproduction repo (instructions to follow)

**Comment by seraphblade2010** [comment]
@rarkins versioning=loose is not working.
Sadly I have no idea how regex works but more than a few attempts to use chatgpt and other information from forums and nothing that produces the right outcome. What exactly do you need for a reproduction repo?

If it is simply to test, create the following docker-compose.yaml:
```
name: checkmk
services:
  checkmk:
    container_name: checkmk
    image: checkmk/check-mk-cloud:2.3.0p1
    restart: unless-stopped
```

If you need anything further, i will provide as many details as I can in order to find a solution to this and thanks for any help in this case^^

**Comment by github-actions** [comment]
Hi there,

Get your discussion fixed faster by creating a minimal reproduction. This means a repository dedicated to reproducing this issue with the minimal dependencies and config possible.

Before we start working on your issue we need to know exactly what's causing the current behavior. A minimal reproduction helps us with this. Discussions without reproductions are less likely to be converted to Issues.

Please follow these steps:
 1. Read our guide on creating a [minimal reproduction](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md).
 2. Go to our [minimal reproduction template repository](https://github.com/renovatebot/minimal-reproduction-template).
 3. Select the _Use this template_ button to create a new repository based on the template.
 4. Work on the minimal reproduction in your own repository.
 5. Fill out the information in your repository's `README.md`.
 6. Add the link to your reproduction to the first post of your Discussion. If you are not the original author, you can post a new comment with the link.

If you need help with running renovate on your minimal reproduction repository, please refer to our [Running Renovate guide](https://docs.renovatebot.com/getting-started/running/).
Good luck,

The Renovate team

**Comment by seraphblade2010** [comment]
Here is the reproduction repo: https://github.com/seraphblade2010/renovate-checkmk

**Reply by gilly42** [reply]
thx for providing the sample

**Comment by rarkins** [comment, marked as answer]
Try this:

```
  packageRules: [{
    matchPackageNames: ['checkmk/check-mk-cloud'],
    versioning: "regex:^(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)(p(?<build>\\d+))?$",
  }]
```

It requires major.minor.patch but has an optional pBuild

**Reply by seraphblade2010** [reply]
That seems to work, thanks a ton ^^

**Comment by gilly42** [comment]
playbook.yml
```yml
# renovate: datasource=docker depName=checkmk/check-mk-raw
checkmk_version: 2.3.0p16
```
renovate.json
```yml
"packageRules": [
    {
      "matchPackageNames": ["checkmk/check-mk-raw"],
      "versioning": "regex:^(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)(p(?<build>\\d+))?$"
    }
  ],
  "customManagers": [
    {
      "customType": "regex",
      "fileMatch": ["\\.yml$"],
      "matchStrings": ["#\\s*renovate:\\s*(datasource=(?<datasource>.*?) )?depName=(?<depName>.*?)( versioning=(?<versioning>.*?))?\\s*\\w*:\\s*(?<currentValue>.*)\\s?"],
      "versioningTemplate": "{{#if versioning}}{{{versioning}}}{{else}}semver{{/if}}"
    }
  ]
```

works perfect, thx
