### DISCUSSION TITLE
`Configuration option repositories should be a list (Array)` while using RENOVATE_REPOSITORIES

### DISCUSSION THREAD

**Discussion by Herve-M** [renovatebot/renovate#31887] [Request Help]
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Azure DevOps Service, npm, 38.106.3

### Please tell us more about your question or problem

We are trying to pass repositories to a YAML template and we transform a YAML object list into a valid json array which is then set to `RENOVATE_REPOSITORIES` while the Renovate config. is set to use it. 

Result is a warning which state the array is empty but debug & printed config shows the contrary, in consequences it seems Renovate ignore the whole config. and go default behavior. 

Config. in question: 
```js
module.exports = {
    $schema: 'https://docs.renovatebot.com/renovate-schema.json',
    platform: 'azure',
    prFooter: 'This PR was automatically created by Renovate, from Software Architecture team.',	
    extends: [
      'local>SoftwareArchitecture/Contoso-renovabot//configs/erp-net-base.json',
      'local>SoftwareArchitecture/Contoso-renovabot//configs/erp-net-monthly.json',
    ],
    hostRules: [
      {
        hostType: 'nuget',
        matchHost: 'pkgs.dev.azure.com',
        username: 'apikey',
        password: process.env.RENOVATE_TOKEN,
      }
    ],
    repositories: process.env.RENOVATE_REPOSITORIES,
  };
```

`RENOVATE_REPOSITORIES` being set like: 
```yaml
- bash: |
          git config --global user.email 'bot@renovateapp.com'
          git config --global user.name 'Renovate Bot'
          echo $RENOVATE_REPOSITORIES
          npx --userconfig .npmrc renovate
        displayName: 'run renovate'
        env:
          RENOVATE_ENDPOINT: $(System.CollectionUri)
          RENOVATE_TOKEN: $(AccessToken)
          RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'
          RENOVATE_CONFIG_FILE: $(Build.SourcesDirectory)/renovate-configs/erp-net-monthly.js
          RENOVATE_REPOSITORIES: '["AProject/Project1", "AProject/Project2", "AProject/Project3"]'
          LOG_LEVEL: debug
          RENOVATE_PRINT_CONFIG: true
```

### Logs (if relevant)

<details><summary>Logs</summary>

```
DEBUG: Using RE2 regex engine
DEBUG: Parsing configs
DEBUG: Checking for config file in /home/vsts/work/1/s/renovate-configs/erp-net-monthly.js
 WARN: Config validation warnings found in /home/vsts/work/1/s/renovate-configs/erp-net-monthly.js
       "warnings": [
         {
           "topic": "Configuration Error",
           "message": "Configuration option `repositories` should be a list (Array)."
         }
       ]
DEBUG: File config
       "config": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "platform": "azure",
         "prFooter": "This PR was automatically created by Renovate, from Software Architecture team.",
         "extends": [
           "local>SoftwareArchitecture/Contoso-renovabot//configs/erp-net-base.json",
           "local>SoftwareArchitecture/Contoso-renovabot//configs/erp-net-monthly.json"
         ],
         "hostRules": [
           {
             "hostType": "nuget",
             "matchHost": "pkgs.dev.azure.com",
             "username": "apikey",
             "password": "***********"
           }
         ],
         "repositories": "[\"AProject/Project1\",\"AProject/Project2\",\"AProject/Project3\"]"
       }
DEBUG: CLI config
       "config": {}
DEBUG: Env config
       "config": {
         "hostRules": [],
         "useCloudMetadataServices": false,
         "printConfig": true,
         "githubTokenWarn": false,
         "endpoint": "https://dev.azure.com/Contoso/",
         "token": "***********",
         "repositories": [
           "AProject/Project1",
           "AProject/Project2",
           "AProject/Project3"
         ],
         "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
         "executionTimeout": 30
       }
DEBUG: Combined config
       "config": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "platform": "azure",
         "prFooter": "This PR was automatically created by Renovate, from Software Architecture team.",
         "extends": [
           "local>SoftwareArchitecture/Contoso-renovabot//configs/erp-net-base.json",
           "local>SoftwareArchitecture/Contoso-renovabot//configs/erp-net-monthly.json"
         ],
         "hostRules": [
           {
             "hostType": "nuget",
             "matchHost": "pkgs.dev.azure.com",
             "username": "apikey",
             "password": "***********"
           }
         ],
         "repositories": [
           "AProject/Project1",
           "AProject/Project2",
           "AProject/Project3"
         ],
         "useCloudMetadataServices": false,
         "printConfig": true,
         "githubTokenWarn": false,
         "endpoint": "https://dev.azure.com/Contoso/",
         "token": "***********",
         "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
         "executionTimeout": 30
       }
```

</details>

### Edit / answer as I got locked @rarkins 
Not sure to get `It should be a comma separated list, not JSON` as `["AProject/Project1", "AProject/Project2", "AProject/Project3"]` is a comma separated list! 

And it follow the documentation sample: https://docs.renovatebot.com/modules/platform/codecommit/#renovate-docker-buildspecyml 

According to most JSON linter, this is a valid JSON input: `["AProject/Project1", "AProject/Project2", "AProject/Project3"]` as spec. state `An array is an ordered collection of values. An array begins with [left bracket and ends with ]right bracket. Values are separated by ,comma. [..] A  value can be a string in double quotes, or a number, or true or false or null, or an object or an array. These structures can be nested.`
