### DISCUSSION TITLE
Authenticate Github App through action for private packages gives response 401 and 403

### DISCUSSION THREAD

**Discussion by eama-trifork** [renovatebot/renovate#31915] [Request Help] [answered]
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Self-hosted

### Please tell us more about your question or problem

When using my Github App to look up private packages using the App Installation token I get response 401 and 403. 
I would've thought an App with [the listed permissions](https://docs.renovatebot.com/modules/platform/github/#running-as-a-github-app) aswell as read packages would work, but am I missing something?

Im running the App against my organization repos.

```
name: Renovate
on:
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1.11.0
        with:
          private-key: ${{ secrets.private_key }}
          app-id: ${{ secrets.app_id }}
          owner: ${{ github.repository_owner }}
          repositories: ...
      - name: Checkout
        uses: actions/checkout@v4.2.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.1
        with:
          token: ${{ steps.get_token.outputs.token }}
          configurationFile: config.js
        env:
          RENOVATE_TOKEN: ${{ steps.get_token.outputs.token }} 
```

```
module.exports = {
  token: process.env.RENOVATE_TOKEN,
  hostRules: [
    {
      hostType: 'maven',
      matchHost: 'https://maven.pkg.github.com',
      token: `${ process.env.RENOVATE_TOKEN }`,
    },
    {
      hostType: 'nuget',
      matchHost: 'https://nuget.pkg.github.com',
      token: `${ process.env.RENOVATE_TOKEN }`,
    },
    {
      hostType: 'docker',
      matchHost: 'ghcr.io',
      token: `${ process.env.RENOVATE_TOKEN }`,
    },
  ],
};
```

### Logs (if relevant)

<details><summary>Logs</summary>

```

DEBUG: GET https://ghcr.io/token?scope=repository%privaterepo%3Apull&service=ghcr.io = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=401 retryCount=0, duration=47) (repository=privaterepo)
DEBUG: Unauthorized docker lookup (repository=privaterepo)
       "registryHost": "https://ghcr.io/",
       "dockerRepository": "privaterepo"
DEBUG: Response code 401 (Unauthorized) (repository=privaterepo)
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1728638097157,
           "socket": 1728638097157,
           "lookup": 1728638097157,
           "connect": 1728638097157,
           "secureConnect": 1728638097157,
           "upload": 1728638097157,
           "response": 1728638097204,
           "end": 1728638097204,
           "phases": {
             "wait": 0,
             "dns": 0,
             "tcp": 0,
             "tls": 0,
             "request": 0,
             "firstByte": 47,
             "download": 0,
             "total": 47
           }
         },
         "message": "Response code 401 (Unauthorized)",
         "stack": "HTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/usr/local/renovate/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/38.117.1 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "authorization": "***********",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://ghcr.io/token?scope=repository%3Aorgname%2Fprivaterepo%3Apull&service=ghcr.io",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 401,
           "statusMessage": "Unauthorized",
           "body": {
             "errors": [{"code": "UNAUTHORIZED", "message": "authentication required"}]
           },
           "headers": {
             "content-type": "application/json",
             "docker-distribution-api-version": "registry/2.0",
             "www-authenticate": "***"[https://ghcr.io/token\](https://ghcr.io/token/)",service=\"ghcr.io\",scope=\"repository:user/image:pull\"",
             "date": "Fri, 11 Oct 2024 09:14:57 GMT",
             "content-length": "73",
             "x-github-request-id": "E800:2EEFF3:4513E4:4F6121:6708EC91"
           },
           "httpVersion": "1.1",
           "retryCount": 0
         }
       }
DEBUG: Failed to get authHeaders for getTags lookup (repository=privaterepo)


DEBUG: GET https://nuget.pkg.github.com/orgname/index.json = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=403 retryCount=0, duration=359) (repository=privaterepo)
DEBUG: Datasource unauthorized (repository=privaterepo)
       "datasource": "nuget",
       "packageName": "privatepackage",
       "url": "https://nuget.pkg.github.com/privaterepo/index.json"
DEBUG: Failed to look up nuget package privatepackage (repository=privaterepo, packageFile=packagefile)

```

</details>
