### DISCUSSION TITLE
Support helmfile helm-charts from private repositories

### DISCUSSION THREAD

**Discussion by mashiofu-cafex** [renovatebot/renovate#31974] [Suggest an Idea]
### Tell us more.

I am looking to utilize renovate to update my helmfile helm-chart versions as new versions are released. The feature works fine for normal `helmfile.yaml` and `repositories.yaml` config, grafana example: 

helmfile.yaml:
```
- name: grafana
  namespace: monitoring
  chart: grafana/grafana
  version: 8.5.1
  installed: true
  values:
    - grafana-values.yaml.gotmpl
    - grafana-values.yaml
```

repositories.yaml
```
repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts

---
```
This config give me a successful run in which the renovate logs displays as follows:
```
{
                 "depName": "grafana",
                 "currentValue": "8.5.1",
                 "registryUrls": ["https://grafana.github.io/helm-charts"],
                 "updates": [
                   {
                     "bucket": "non-major",
                     "newVersion": "8.5.2",
                     "newValue": "8.5.2",
                     "newDigest": "20e837fc6a1e22da2ead492bb266448b30f4d12b5396355411bc8978f086a5dd",
                     "releaseTimestamp": "2024-10-02T07:45:48.603Z",
                     "newMajor": 8,
                     "newMinor": 5,
                     "newPatch": 2,
                     "updateType": "patch",
                     "branchName": "renovate/helmfile-helm/helm-charts/monitoring-helmfile-chart-updates"
                   }
                 ],
                 "packageName": "grafana",
                 "versioning": "helm",
                 "warnings": [],
                 "sourceUrl": "https://github.com/grafana/helm-charts",
                 "registryUrl": "https://grafana.github.io/helm-charts",
                 "homepage": "https://grafana.com/",
                 "currentVersion": "8.5.1",
                 "currentVersionTimestamp": "2024-09-04T17:04:03.867Z",
                 "isSingleVersion": true,
                 "fixedVersion": "8.5.1"
               },
```

My issue is, I have pulled and pushed all helm-charts used in my environment to private AWS ECR. Therefore my `helmfile.yaml` & `repositories.yaml` files are not configured to be utilized as intended by renovate. Example of my current config:

helmfile.yaml:
```
- name: grafana
  namespace: monitoring
  chart: ecr/grafana
  version: 8.5.1
  installed: true
  values:
    - grafana-values.yaml.gotmpl
    - grafana-values.yaml
```

repositories.yaml:
```
repositories:
- name: ecr
  url: {{ .Values.image.repository }}
  oci: true
---
```

When running renovate with this config, the logs are as follows:
```
         {
                 "depName": "grafana",
                 "currentValue": "8.5.2",
                 "registryUrls": [],
                 "skipReason": "unknown-registry",
                 "updates": [],
                 "packageName": "grafana"
               },
```

It would be nice if Renovate can add a feature in the helmfile config of the `renovate.json` to specify which `registryUrls` to use regardless of what is shown in the `repositories.yaml`. I think of it as an override feature. This will allow version updates to still be detected for those who are using private repositories for open-source helm-charts.

**Comment by rarkins** [comment]
Please try with `registryAliases`. And if not possible, provide a public reproduction (instructions to follow) which fails in the same way as you get privately.

**Reply by mashiofu-cafex** [reply]
Resolved this by utilizing `registryAliases` and renaming helm repository name within `helmfile.yaml` and `repositories.yaml`. Grafana example:

```
- name: grafana
  namespace: monitoring
  chart: ecr-grafana/grafana
  version: 8.5.1
  installed: true
  values:
    - grafana-values.yaml.gotmpl
    - grafana-values.yaml
```
```
repositories:
- name: ecr-grafana
  url: {{ .Values.image.repository }}
  oci: true
---
```
