### DISCUSSION TITLE
Is it possible to extract meta information from packageFile content and add it to the prBodyNotes?

### DISCUSSION THREAD

**Discussion by hebestreit** [renovatebot/renovate#32060] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab 38.128.6

### Please tell us more about your question or problem

I would like to know if it's possible to extract information from the processed `{{packageFile}}` and add the content to the `prBodyNotes` configuration option to be used by the template engine.

In the example below I want to get the value from `link.argocd.argoproj.io/upgrade-guide` either by using a regex or parsing the YAML object. This information should be then displayed inside the PR body so that the user can click on the referenced upgrade guide.

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/upgrade-guide: https://www.vaultproject.io/docs/upgrading
spec:
  destination:
    namespace: vault
  project: infra
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.27.0
    # ...
```
