### DISCUSSION TITLE
Add support for Python `dependency-groups` (PEP 735)

### DISCUSSION THREAD

**Discussion by mkniewallner** [renovatebot/renovate#32147] [Suggest an Idea]
### Tell us more.

[PEP 735](https://peps.python.org/pep-0735/) recently got accepted. Similarly to `optional-dependencies` or `tool.pdm.dev-dependencies`, it allows defining groups of dependencies in `pyproject.toml` like so:

```toml
[dependency-groups]
test = ["pytest==8.3.3", "pytest-cov==5.0.0"]
typing = ["mypy==1.13.0"]
all = [{include-group = "test"}, {include-group = "typing"}, "click"]
```

When a dependency in a group is not a string, but instead a table, we should skip parsing it, as the only key is `include-group`, which is not relevant for Renovate itself (it only allows reusing a group in another group).

Not all tools that support PEP 621 support `dependency-groups` yet (so far, only [uv supports it](https://github.com/astral-sh/uv/releases/tag/0.4.27), AFAIK), but I don't think it would be too problematic to already assume that all tools support it, as if a user uses a dependency manager that does not yet support `dependency-groups`, they would have no reason to use the feature anyway.

Would be happy to work on the implementation.
