### DISCUSSION TITLE
Renovate does not recognize the last commit author

### DISCUSSION THREAD

**Discussion by rblin081** [renovatebot/renovate#32157] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitHub

### Please tell us more about your question or problem

We're using Renovate to manage the dependencies in several of our GitHub repositories. We've noticed that recently there's a comment being added to the Renovate managed PRs

```
Renovate will not automatically rebase this PR, because it does not recognize the last commit author and assumes somebody else may have edited the PR.
```

Renovate is configured to use GitHub application 'honor-gh-bot'  to authenticate to the different GitHub repositories

Here's the relevant GitHub action yaml
```
      - name: Generate GitHub app authentication token
        id: generate-app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.HONOR_GH_BOT_APP_ID }}
          private-key: ${{ secrets.HONOR_GH_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Renovate GitHub Action
        uses: renovatebot/github-action@v40.1.12
        with:
          configurationFile: ${{ matrix.renovateConfigFilePath }}
          token: ${{ steps.generate-app-token.outputs.token }}
```

and here's the relevant Renovate configuration
```
    gitAuthor: 'Renovate Bot <bot@renovateapp.com>',
    gitIgnoredAuthors: ["honor-gh-bot"],
    platform: 'github',

    automerge: true,
    platformAutomerge: true,
    autoApprove: true,
    assigneesFromCodeOwners: true,
```

Note that `honor-gh-bot` is specifically added as an entry `gitIgnoredAuthors`. 

Any ideas why Renovate is not recognizing the commit author?

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
