### DISCUSSION TITLE
How to get latest versions of operators in the “redhat-operators” catalog

### DISCUSSION THREAD

**Discussion by karl-johan-grahn** [renovatebot/renovate#32180] [Request Help]
### How are you running Renovate?

A Mend.io-hosted app

### Please tell us more about your question or problem

We install operators via https://github.com/stakater/charts/tree/main/operators-installer

Sample values file, abridged to only contain the relevant troubleshooting info:

```yaml
operators-installer:
  operators:
    - channel: gitops-1.10
      source: redhat-operators
      csv: openshift-gitops-operator.v1.10.1
```

From this values file, `operators-installer` will create a subscription:

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
spec:
  channel: "gitops-1.10"
  source: "redhat-operators"
  startingCSV: "openshift-gitops-operator.v1.10.1"
```

In the example above we are currently using `openshift-gitops-operator v1.10.1`, how can Renovate programmatically detect if a new version of the operator is available?

Renovate can manually find new versions via https://access.redhat.com/labs/ocpouic/?upgrade_path=4.14%20to%204.15, however the page is not easily parsed.

The command `oc-mirror list operators` would give us the list of versions, however:
* Renovate should not have to rely on third-party commands to find versions
* It’s awfully slow on a local machine, can take 20 min to run, because everytime it pings `registry.redhat.io` for the image to get latest hash and then processes it

Quay is the backend for registry.redhat.io: https://access.redhat.com/solutions/3625131
However, Quay only has information about index images, not about the operators inside the index images.

Do we have to run opm or oc-mirror as a Kubernetes job and publish it in a way that Renovate can easily consume?

Ideally redhat-operators should somehow be available to Renovate as GitHub releases, that would mean the least amount of development effort to get dependency updates working.

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
