### DISCUSSION TITLE
docker registry : authentication with Harbor robot account username containing '$' sign fails

### DISCUSSION THREAD

**Discussion by sylvainmetayer** [renovatebot/renovate#32194] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Gitlab, version 38.133.0

### Please tell us more about your question or problem

By default, [the docker registry Harbor use $ as robot prefix account](https://goharbor.io/docs/2.10.0/administration/robot-accounts/#configure-robot-account-prefix). When I configured renovate to use a robot account, I used global host rules variables to define username and password to get update from the private registry.

However, the $ sign is interpreted and cause the authentication to fail. I'm not sure if this, or should be intended.

To reproduce : 

- Use an Harbor registry, managed or not (in my case, OVH managed)
- Declare a robot account with pull permissions (`robot$read`)
- In the renovate configuration, declare the following environnement variable in the Gitlab stage

```
variables:
  # https://dille.name/blog/2022/11/27/using-private-container-registries-with-renovate/#passing-secrets-to-renovate
  DOCKER_REGISTRY_URL_USERNAME: $CI_HARBOR_READ_ONLY_USER
  DOCKER_REGISTRY_URL_PASSWORD: $CI_HARBOR_READ_ONLY_PASSWORD
```

Where `$CI_HARBOR_READ_ONLY_USER` value is `robot$read` and `$CI_HARBOR_READ_ONLY_PASSWORD` the correct password for this robot account

Expected behavior : 

The `$CI_HARBOR_READ_ONLY_USER` variable should be interpreted to resolve as `robot$read` and I should be able to authenticate against the registry

Current behavior : 

The authentication seems to be done with `robot$read` interpreted, resulting in `robot` variable value.

Workaround : 

Configure Harbor to use a different prefix : with the `robot-` prefix, I can authenticate against the registry.

This issue seems similar to this one : https://github.com/renovatebot/renovate/discussions/26373

### Logs (if relevant)

<details><summary>Logs</summary>

```
DEBUG: GET https://REGISTRY_URL/v2/docker-mirror/alpine/git/tags/list?n=10000 = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=401 retryCount=0, duration=25)
```

</details>
