### DISCUSSION TITLE
Identify Helm chart dependencies specified in Helm value file

### DISCUSSION THREAD

**Discussion by ohlen1** [renovatebot/renovate#32269] [Request Help]
### How are you running Renovate?

A Mend.io-hosted app

### Please tell us more about your question or problem

Hi,

I want to be able to instruct Renovate to identify and suggest updates of Helm chart versions for 3rd party charts in different public repositories, based on a Helm values file that contains these elements:
```yaml
  ingress-nginx:
    enabled: true
    chart:
      repoUrl: https://kubernetes.github.io/ingress-nginx
      name: ingress-nginx
      version: 4.11.1
  external-dns:
    enabled: true
    chart:
      repoUrl: https://charts.bitnami.com/bitnami
      name: external-dns
      version: 6.35.0
```

Note that, since this is YAML, there is no guarantee that the child variables of `chart` comes in any particular order. 
Is a "custom manager" of type "regex" my only possibility for this? Or are there other alternatives available that I haven't found yet?

Thanks
