### DISCUSSION TITLE
Renovatebot not detecting version updates

### DISCUSSION THREAD

**Discussion by amrap030** [renovatebot/renovate#32277] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitHub

### Please tell us more about your question or problem

I have a `values.yaml` file of a Helm Chart with the following content (*** due to privacy reasons):

```yaml
traefik:
  # Default values for Traefik
  # This is a YAML-formatted file.
  # Declare variables to be passed into templates

  image: # @schema additionalProperties: false
    # -- Traefik image host registry
    registry: registry-***.app.***.net/dockerhub
    # -- Traefik image repository
    repository: traefik
    # -- defaults to appVersion
    tag: v3.1.4 # @schema type:[string, null]
    # -- Traefik image pull policy
    pullPolicy: IfNotPresent

...
```

For some reason, renovatebot doesn't recognize updates, even though there is already v3.2.0 available. Why is that? Do I need to create a `customManager` or something?

This is my config:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": ["config:best-practices"],
  "dependencyDashboard": true,
  "helm-values": {
    "fileMatch": ["cluster/.+\\.ya?ml$"]
  },
  "kubernetes": {
    "fileMatch": ["cluster/.+\\.ya?ml$"]
  },
  "prHourlyLimit": 30,
  "prConcurrentLimit": 30,
  "enabledManagers": [
    "dockerfile",
    "github-actions",
    "helm-values",
    "helmv3",
    "kubernetes",
    "terraform",
    "terragrunt",
    "ansible"
  ],
  "vulnerabilityAlerts": {
    "addLabels": ["security"]
  }
}

```
