### DISCUSSION TITLE
node: not found

### DISCUSSION THREAD

**Discussion by dh-harald** [renovatebot/renovate#32336] [Request Help] [answered]
### How are you running Renovate?

Github/gitea action, official docker container

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

I've a self hosted gitea with actions enabled.

### Please tell us more about your question or problem

Hi,

I'm using renovate for my environment with the usual way:
```
    container:
      image: ghcr.io/renovatebot/renovate:39.0.1
[...]
    steps:
    - uses: actions/checkout@v4
    - run: renovate
      env:
[...]
 ```
 
 I've realized, in the official docker image, the node binary is no longer in $PATH, therefore my pipeline fails (can't run the checkout step).
 ```
 $ docker run -ti --rm ghcr.io/renovatebot/renovate:39.0.1 sh
sh: 3: Syntax error: "(" unexpected
$ node
sh: 1: node: not found
$
```
Could you readd `/usr/local/renovate` to PATH please?

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
