### DISCUSSION TITLE
Problem with custom entrypoint since version 39.0.0

### DISCUSSION THREAD

**Discussion by BeneHa** [renovatebot/renovate#32396] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Github

### Please tell us more about your question or problem

Hi,

since version 39.0.0 I have an issue with my custom Entrypoint script. It installs some tools that are used in post upgrade tasks of many repos globally and has been working fine:
```
#!/bin/sh
set -euxo

curl https://mise.jdx.dev/mise-latest-linux-x64 > ~/mise
chmod +x ~/mise

~/mise use -g --yes terraform@latest terraform-docs@latest pre-commit@latest
~/mise install --yes --force terraform terraform-docs pre-commit
export PATH="$HOME/.local/share/mise/installs:$PATH"

renovate
```

I run renovate from a Github Action:
```
      - name: Run Renovate Bot (${{ matrix.org-configs }})
        id: renovate
        uses: renovatebot/github-action@v40.3.4
        with:
          configurationFile: tmp.json
          token: ${{ secrets.USER_GIT_TOKEN }}
          renovate-version: full     # 38.142.7 works, 39.0.0 does not work
          docker-cmd-file: scripts/renovate-entrypoint.sh
          docker-user: ubuntu
        env:
          RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.USER_GPG_KEY }}
          RENOVATE_GITHUB_TOKEN: ${{ secrets.USER_GIT_TOKEN }}
          RENOVATE_HOST_RULES: ...
          RENOVATE_POST_UPGRADE_TASKS: ...
          RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: ...
```

I get the error:
```
DEBUG ARGS: /home/ubuntu/mise use -g --yes terraform@latest terraform-docs@latest pre-commit@latest
WARN  Failed to setup fake asdf: failed create_dir_all: ~/.local/share/mise/.fake-asdf: File exists (os error 17)
DEBUG install_versions: terraform@latest terraform-docs@latest pre-commit@latest
Error: 
   0: failed create_dir_all: ~/.cache/mise/lockfiles
   1: File exists (os error 17)
Location:
   src/file.rs:170
```
I have also tried all RENOVATE_BINARY_SOURCE options but the result is the same. One of the breaking changes in v39 must be the cause but I do not know which one causes the mkdir -p to fail.

It would be great if someone could point me in the direction how to get this running again with the latest renovate version!

Thanks and best regards
BeneHa
