### DISCUSSION TITLE
Difficulties with onboarding in Azure DevOps Server 2022

### DISCUSSION THREAD

**Discussion by asfswa** [renovatebot/renovate#32531] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Azure DevOps Server 2022; Renovate Version 39.13.1

### Please tell us more about your question or problem

I have configured Renovate Bot to keep track of dependencies in a number of repositories. I'm not using the autodiscovery mechanism and have manually listed all repositories. For most repositories the onboarding process was successful.

In those case where the onboarding was not successful, the situation is as follows:
Renovate Bot creates an onboarding PR that adds a default renovate.json file to the repository. After I approve the PR, Renovate Bot adds a comment to the PR ("Renovate is disabled
Renovate is disabled because there is no Renovate configuration file. To enable Renovate, you can either (a) change this PR's title to get a new onboarding PR, and merge the new onboarding PR, or (b) create a Renovate config file, and commit that file to your base branch."). On subsequent runs of Renovate Bot the repository is ignored (see logs). 
 
I tried following the recommendations from the comment but it is not possible to change the title of closed PRs in ADO and there is a configuration file present in the repository. Editing the renovate.json file dit not help either. I have tried to start over by reimporting the affected repositories into ADO to get rid of the PR history and the configuration file. So far without success as I keep running into the same problem.

### Logs (if relevant)

<details><summary>Logs</summary>

```
...
DEBUG: config file not found (repository=<ADO-project>/<repository-name>)
DEBUG: Found closed onboarding PR (repository=<ADO-project>/<repository-name>)
DEBUG: Repo is not onboarded and no merged PRs exist (repository=<ADO-project>/<repository-name>)
...

```

</details>

**Comment by github-actions** [comment]
Hi there,

Get your discussion fixed faster by creating a minimal reproduction. This means a repository dedicated to reproducing this issue with the minimal dependencies and config possible.

Before we start working on your issue we need to know exactly what's causing the current behavior. A minimal reproduction helps us with this. Discussions without reproductions are less likely to be converted to Issues.

Please follow these steps:
 1. Read our guide on creating a [minimal reproduction](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md).
 2. Go to our [minimal reproduction template repository](https://github.com/renovatebot/minimal-reproduction-template).
 3. Select the _Use this template_ button to create a new repository based on the template.
 4. Work on the minimal reproduction in your own repository.
 5. Fill out the information in your repository's `README.md`.
 6. Add the link to your reproduction to the first post of your Discussion. If you are not the original author, you can post a new comment with the link.

If you need help with running renovate on your minimal reproduction repository, please refer to our [Running Renovate guide](https://docs.renovatebot.com/getting-started/running/).
Good luck,

The Renovate team

**Comment by rarkins** [comment]
You say you approved the PR, but Renovate says the PR is closed. Is it merged, or closed without merging?

**Reply by asfswa** [reply]
The PR war approved by me and automerged by Renovate Bot. Renovate Bot added the comment on its first run after merging the onboarding PR.

I use the following configuration in the `config.js` from the Renovate Repository:
```json
  "automerge": true,
  "automergeType": "pr",
  "automergeStrategy": "squash",
  "platformAutomerge": true, 
```

**Reply by rarkins** [reply]
I'm not aware of onboarding PRs ever being automerged. Please provide the debug logs from when that occurred, if you're sure about it. Otherwise we need to assume that didn't happen like you describe

**Reply by asfswa** [reply]
I will retry the onboarding on a a new repository and provide more detailed/complete logs.

**Reply by asfswa** [reply]
Hello, I was wrong. The onboarding PR was not automatically merged. I confused this with the behavior we have by default for all PRs.

I created a clone of a repository where I observed the behavior and deleted the renovate.json with a commit. I then ran Renovate and an onboarding PR was created. I merged this one. I then ran Renovate again and the described behavior occurred. Please have a look at the attached log. 

[20241125_renovate_log.txt](https://github.com/user-attachments/files/17899730/20241125_renovate_log.txt)

**Reply by rarkins** [reply]
Per the logs, it's not finding a renovate.json in the default branch (master). Perhaps there's an old version of `git` on client or server which is causing the problem.

**Reply by asfswa** [reply]
On the client side we use the Renovate Image 39.28.0@sha256:7cf419a3177d4cff065f1fa589c80b603c80fa7c3e1792ef1bcad8267be67325 which includes `git` version 2.47.0.
We are still trying to determine the git version that is being used on the server.

Wouldn't versions mismatch be a problem that would affect all or at least many repositories?

**Comment by github-actions** [comment]
Hi there,

We need more information about your environment.

Please explain in detail how you are running Renovate. For example:
  - Are you running via an official Renovate image, or using the Renovate npm package?
  - Which exact image tag are you running?
  - Which config/parameters are you using when running the image?
  - Which config are you using in your CI/CD pipeline, if relevant?

Thanks, the Renovate team

**Reply by asfswa** [reply]
- I am using the official Renovate image from https://hub.docker.com/r/renovate/renovate
- Image tag: 39.28.0@sha256:7cf419a3177d4cff065f1fa589c80b603c80fa7c3e1792ef1bcad8267be67325 
- The config is as follows:
```js
module.exports = {
  "platform": "azure",
  "endpoint": process.env.SYSTEM_COLLECTIONURI,
  "gitAuthor": "<redacted>",
  "extends": [
    // https://docs.renovatebot.com/presets-config/#configbest-practices
    "config:best-practices",
    // https://docs.renovatebot.com/presets-default/#rebasestaleprs
    ":rebaseStalePrs",
    // https://docs.renovatebot.com/presets-default/#separatemultiplemajorreleases
    ":separateMultipleMajorReleases",
    // https://docs.renovatebot.com/presets-default/#separatemultipleminorreleases
    ":separateMultipleMinorReleases",
    // https://docs.renovatebot.com/presets-default/#separatepatchreleases
    ":separatePatchReleases",
    // https://docs.renovatebot.com/semantic-commits/
    ":semanticCommits",
    // https://docs.renovatebot.com/presets-default/#disabledependencydashboard
    // https://docs.renovatebot.com/faq/#renovate-core-features-not-supported-on-all-platforms
    ":disableDependencyDashboard"
  ],
  "hostRules": [
    {
      "matchHost": "<redacted>",
      "username": process.env.<redacted>,
      "password": process.env.<redacted>
    }
  ],
  // General automerge config
  "automerge": true,
  "automergeType": "pr",
  "automergeStrategy": "squash",
  "platformAutomerge": true,

  "packageRules": [
    // Auto merge for docker digest pinning
    {
      "matchDatasources": ["docker"],
      "matchUpdateTypes": ["pinDigest"],
      "autoApprove": true,
      "automerge": true
    }
  ],
  // List of repos that should be watched by renovate bot
  "repositories": [
    process.env.SYSTEM_TEAMPROJECT + "<redacted>"
  ]
};
```
- This is the pipeline I am using:
```yml
trigger:
  branches:
    include:
      - main

schedules:
  - cron: "0 * * * *"
    displayName: cron
    branches:
      include:
        - main
    always: true
    batch: false

pool: <redacted>

jobs:
  - job: renovate
    displayName: 'Renovate'
    container:
      image: <redacted>/renovate/renovate:39.28.0@sha256:7cf419a3177d4cff065f1fa589c80b603c80fa7c3e1792ef1bcad8267be67325
      # Needed by azure devops agent to add users etc
      options: --user 0
    variables:
      - group: <redacted>
    steps:
      - checkout: self

      - bash: |
          renovate-config-validator --strict
        displayName: 'Validate config'
        env:
          # Access private repositories and registries
          <redacted>: "$(<redacted>)"
          <redacted>: "$(<redacted>)"

      - bash: |
          renovate
        displayName: 'Run renovate'
        env:
          # Renovate configuration options
          RENOVATE_TOKEN: $(System.AccessToken)
          # Access private repositories and registries
          <redacted>: "$(<redacted>)"
          <redacted>: "$(<redacted>)"
          LOG_LEVEL: "debug"

```
