### DISCUSSION TITLE
Support for yaml anchor for compose file

### DISCUSSION THREAD

**Discussion by vic1707** [renovatebot/renovate#32805] [Suggest an Idea]
### Tell us more.

Hi,

I wanted to add renovate to my repo but found out that yaml anchors aren't supported yet (minimal example)

```yml
x-GICKUP: &GICKUP docker.io/buddyspencer/gickup:0.10.36

services:
    gickup:
        image: *GICKUP
```
Above yml file doesn't add 1 to the count of dependencies, but 

```yml
services:
    gickup:
        image: docker.io/buddyspencer/gickup:0.10.36
```
does.

Tested with `npx renovate  --platform=local  --onboarding=false`
```diff
 INFO: Dependency extraction complete (repository=local)
       "stats": {
         "managers": {
-           "docker-compose": {"fileCount": 1, "depCount": 0},
+           "docker-compose": {"fileCount": 1, "depCount": 1},
         },
         "total": {"fileCount": 1, "depCount": 0}
       }
```
The dep appears when removing the anchor.

I don't know how hard it would be to add support for anchors but it would certainly be a nice to have 👍.
