### DISCUSSION TITLE
Azure DevOps | Work Item strategy

### DISCUSSION THREAD

**Discussion by gioce90** [renovatebot/renovate#32988] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Azure DevOps

### Please tell us more about your question or problem

Following issue #3395, we now have a Work Item linked to a Pull Request on Azure DevOps. My question is: is this approach sufficient?

Sometimes it might be better to have a specific Work Item dedicated to a specific repository. Other times, it could make sense to have one Work Item for all low-impact updates (e.g., covering all patches and minor updates) and separate Work Items for each major update.

Additionally, assigning the Work Item ID dynamically doesn’t seem possible (correct me if I'm wrong). Maybe a sort of pre-upgrade task would be more appropriate?

I’d be curious to hear about your strategies on this topic. How do you use the `azureWorkItemId` configuration options?

**Comment by joshknutson** [comment]
I do this for my projects. I create a work item, and then have RenovateMe run. sometimes it will create a work item with no issues found, but at that point I can just delete it, otherwise depending on the project it might find a few, but this way once the pull requests are approved, the work item can be assigned to someone within the iteration and then they can verify if it worked correctly and if they find an issue they can work to resolve it. Mostly just helps to organize what changes occurred for the iteration better.

```yml
  - task: CreateWorkItem@1
    displayName: 'Create User Story for RenovateMe'
    inputs:
      workItemType: 'User Story'
      title: 'Update Dependencies'
      fieldMappings: |
        Tags=renovate; dependencies
      areaPath: 'Project'
      iterationPath: 'Project'
      preventDuplicates: false
      keyFields: |
        System.AreaPath
        System.IterationPath
        System.Title
      createOutputs: true
      outputVariables: |
        workItemId=ID
  - task: NodeTool@0
    displayName: 'Use Node 22.x'
    inputs:
      versionSpec: 22.x

  - task: RenovateMe@0
    displayName: Renovate
    inputs:
      renovateOptionsArgs: '--azure-work-item-id $(workItemId)
```
