### DISCUSSION TITLE
versioning example for linuxserver/openssh-server in docs does not work

### DISCUSSION THREAD

**Discussion by pfaelzerchen** [renovatebot/renovate#33024] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

k3s with version 39.60.0

### Please tell us more about your question or problem

I tried to use the last example from the docs regarding linuxserver/openssh-server: <https://docs.renovatebot.com/modules/versioning/regex/> 

My deployment contains this image definition:
```yaml
image: lscr.io/linuxserver/openssh-server:9.7_p1-r4-ls179
```

my renovate.json uses the following package rule
```json
        {
          "description": "Detect openssh-server image updates",
          "matchDatasources": ["kubernetes"],
          "matchPackageNames": ["lscr.io/linuxserver/openssh-server"],
          "versioning": "regex:^(?<major>\\d+)\\.(?<minor>\\d+)_p(?<patch>\\d+)-r(?<build>\\d)-ls(?<revision>.+)$"
        }
```

By now, ls180 is already available, so renovate should immediately detect an update. But nothing happens. The dependency dashboard mentions 

```
lscr.io/linuxserver/openssh-server 9.7
```

So it seems, only the major and minor version are detected. For me, the regex looks fine. Is there some typo I did not recognize?

By the way, the docs contain a typo in `matchPackageNamees` (double e).

**Comment by github-actions** [comment]
Hi there,

Get your discussion fixed faster by creating a minimal reproduction. This means a repository dedicated to reproducing this issue with the minimal dependencies and config possible.

Before we start working on your issue we need to know exactly what's causing the current behavior. A minimal reproduction helps us with this. Discussions without reproductions are less likely to be converted to Issues.

Please follow these steps:
 1. Read our guide on creating a [minimal reproduction](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md).
 2. Go to our [minimal reproduction template repository](https://github.com/renovatebot/minimal-reproduction-template).
 3. Select the _Use this template_ button to create a new repository based on the template.
 4. Work on the minimal reproduction in your own repository.
 5. Fill out the information in your repository's `README.md`.
 6. Add the link to your reproduction to the first post of your Discussion. If you are not the original author, you can post a new comment with the link.

If you need help with running renovate on your minimal reproduction repository, please refer to our [Running Renovate guide](https://docs.renovatebot.com/getting-started/running/).
Good luck,

The Renovate team

**Comment by kennethso168** [comment]
Hey there, I tried to test if the documentation is correct (notwithstanding typos) by creating a [minimal reproduction repository](https://github.com/kennethso168/linuxserver-io-openssh-server-repr-20241225). And renovate is able to propose a PR for `9.7_p1-r4-ls181` -> `9.7_p1-r4-ls182`, showing that at least the regex is correct.

I don't use kubernetes, but I guess the reasons why yours don't work might be as below:

- There is no datasource called `kubernetes` ([docs here](https://docs.renovatebot.com/modules/datasource/)). The `kubernetes` manager [supports extracting the following datasources](https://docs.renovatebot.com/modules/manager/kubernetes/), `docker` and `kubernetes-api`, so the line `"matchDatasources": ["kubernetes"],` should be incorrect according to docs.
- [The kubernetes manager has no fileMatch default patterns, so it won't match any files until you configure it with a pattern.](https://docs.renovatebot.com/modules/manager/kubernetes/). I can't see if you have configured such pattern from the `renovate.json` extract
- Also make sure that the correct image name is used in both the `renovate.json` and your kubernetes file (e.g. `lscr.io` vs `ghcr.io`

It'd be best to create a minimal reproduction as outlined from the above bot comment.

Anyway I'm planning to update that page of doc as per #33270 . Just seeking maintainers' opinion there. When updating the page I'll fix the typos too.

**Comment by pfaelzerchen** [comment]
@kennethso168 Thanks for your effort. I was too busy the last weeks to create a minimal reproduction repository earlier, but did so now: <https://github.com/pfaelzerchen/linuxserver-io-openssh-reproduction>

I placed both my kubernetes deployment yaml and your docker compose.yml in the repo. And I can confirm, that your minimal docker reproduction works just fine, while kubernetes won't work. I'll attach my log files, but I think the interesting part is:

```json
DEBUG: packageFiles with updates
{
  "baseBranch": "main"
  "config": {
    "docker-compose": [
      {
        "deps": [
          {
            "depName": "lscr.io/linuxserver/openssh-server",
            "currentValue": "9.7_p1-r4-ls181",
            "replaceString": "lscr.io/linuxserver/openssh-server:9.7_p1-r4-ls181",
            "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
            "datasource": "docker",
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "9.7_p1-r4-ls182",
                "newValue": "9.7_p1-r4-ls182",
                "newMajor": 9,
                "newMinor": 7,
                "newPatch": 1,
                "updateType": "patch",
                "branchName": "renovate/lscr.io-linuxserver-openssh-server-9.x"
              }
            ],
            "packageName": "lscr.io/linuxserver/openssh-server",
            "versioning": "regex:^(?<major>\\d+)\\.(?<minor>\\d+)_p(?<patch>\\d+)-r(?<build>\\d)-ls(?<revision>.+)$",
            "warnings": [],
            "sourceUrl": "https://github.com/linuxserver/docker-openssh-server",
            "registryUrl": "https://lscr.io",
            "homepage": "https://github.com/linuxserver/docker-openssh-server/packages",
            "lookupName": "linuxserver/openssh-server",
            "currentVersion": "9.7_p1-r4-ls181",
            "isSingleVersion": true,
            "fixedVersion": "9.7_p1-r4-ls181"
          }
        ],
        "packageFile": "compose.yml"
      }
    ],
    "kubernetes": [
      {
        "deps": [
          {
            "depName": "lscr.io/linuxserver/openssh-server",
            "currentValue": "9.7",
            "replaceString": "lscr.io/linuxserver/openssh-server:9.7",
            "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
            "datasource": "docker",
            "updates": [],
            "packageName": "lscr.io/linuxserver/openssh-server",
            "versioning": "regex:^(?<major>\\d+)\\.(?<minor>\\d+)_p(?<patch>\\d+)-r(?<build>\\d)-ls(?<revision>.+)$",
            "warnings": [],
            "skipReason": "invalid-value"
          },
          {
            "depName": "Deployment",
            "currentValue": "apps/v1",
            "datasource": "kubernetes-api",
            "versioning": "kubernetes-api",
            "updates": [],
            "packageName": "Deployment",
            "warnings": [],
            "currentVersion": "apps/v1",
            "fixedVersion": "apps/v1"
          }
        ],
        "packageFile": "openssh-deployment.yaml"
      }
    ]
  }
}
```

It seems that there goes something wrong with the detection of the image version when using kubernetes. For compose.yml it recognizes `"currentValue": "9.7_p1-r4-ls181"` which matches the pattern. For the openssh-deployment.yaml it detects `"currentValue": "9.7"` which does not match the pattern: `"skipReason": "invalid-value"`

Is it a bug in renovate or did I miss something in my config?

**Reply by viceice** [reply]
it's a config error. you need to limit your custom versioning to specific content.

**Reply by pfaelzerchen** [reply]
I really appreciate your work and your effort to point me into the right direction. But I really don't understand what you tried to tell me. Even after rereading the docs regarding package rules. How do a properly limit the package rule to specific content?

When I completely remove the packageRule (and making the docker-compose file failing also), the look still indicates that there is a difference between the detected version string between docker-compose and kubernetes:

```yaml
DEBUG: packageFiles with updates
{
  "baseBranch": "main"
  "config": {
    "docker-compose": [
      {
        "deps": [
          {
            "depName": "lscr.io/linuxserver/openssh-server",
            "currentValue": "9.7_p1-r4-ls181",
            "replaceString": "lscr.io/linuxserver/openssh-server:9.7_p1-r4-ls181",
            "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
            "datasource": "docker",
            "updates": [],
            "packageName": "lscr.io/linuxserver/openssh-server",
            "versioning": "docker",
            "warnings": [],
            "sourceUrl": "https://github.com/linuxserver/docker-openssh-server",
            "registryUrl": "https://lscr.io",
            "homepage": "https://github.com/linuxserver/docker-openssh-server/packages",
            "lookupName": "linuxserver/openssh-server",
            "currentVersion": "9.7_p1",
            "fixedVersion": "9.7_p1-r4-ls181"
          }
        ],
        "packageFile": "compose.yml"
      }
    ],
    "kubernetes": [
      {
        "deps": [
          {
            "depName": "lscr.io/linuxserver/openssh-server",
            "currentValue": "9.7",
            "replaceString": "lscr.io/linuxserver/openssh-server:9.7",
            "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
            "datasource": "docker",
            "updates": [],
            "packageName": "lscr.io/linuxserver/openssh-server",
            "versioning": "docker",
            "warnings": [],
            "sourceUrl": "https://github.com/linuxserver/docker-openssh-server",
            "registryUrl": "https://lscr.io",
            "homepage": "https://github.com/linuxserver/docker-openssh-server/packages",
            "lookupName": "linuxserver/openssh-server",
            "currentVersion": "9.7",
            "fixedVersion": "9.7"
          },
          {
            "depName": "Deployment",
            "currentValue": "apps/v1",
            "datasource": "kubernetes-api",
            "versioning": "kubernetes-api",
            "updates": [],
            "packageName": "Deployment",
            "warnings": [],
            "currentVersion": "apps/v1",
            "fixedVersion": "apps/v1"
          }
        ],
        "packageFile": "openssh-deployment.yaml"
      }
    ]
  }
}
```

Or is the packagerule the wrong place for configuring this after all?
