### DISCUSSION TITLE
`lockfileMaintenance` ignores `uv`'s `resolution-mode`

### DISCUSSION THREAD

**Discussion by stefanofusai** [renovatebot/renovate#33345] [Request Help]
### How are you running Renovate?

A Mend.io-hosted app

### Please tell us more about your question or problem

As you can see in [this PR](https://github.com/stefanofusai/pyamldantic/pull/63), Renovate's `lockfileMaintenance` overwrites the `resolution-mode` that is set in `uv.lock`'s options.
![image](https://github.com/user-attachments/assets/17dc445c-c9a9-4442-bba9-4cc7baed13b7)

I would expect the custom options to be preserved, or for a way to specify which command `lockfileMaintenance` should run (in my case: `uv lock -resolution=lowest-direct`)

What approach do you suggest? Thank you!

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>

**Comment by rarkins** [comment]
Is there a definitive list of all such options which should be retained?

**Reply by stefanofusai** [reply]
I'm unfortunately not sure of all the available options, but IMO the more robust and future-proof solution would be to allow passing arbitrary arguments to the `uv lock` command, just like [uv-pre-commit](https://github.com/astral-sh/uv-pre-commit) allows:
```yaml
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.11
    hooks:
      - id: uv-lock
        args:
          - --resolution=lowest-direct
```
