### DISCUSSION TITLE
Renovate trying to pin empty tags in Helm chart values

### DISCUSSION THREAD

**Discussion by Luzifer** [renovatebot/renovate#33465] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Gitea / 39.93.0@sha256:957f722

### Please tell us more about your question or problem

Somewhere in the last few versions a bug has been introduced into the digest pinning inside Helm chart values. (Cannot trace to an exact version as I'm auto-updating the Renovate release and seeing these PRs for a few days now.)

#### Setup

```yaml
# Chart.yaml
# [...]
appVersion: 3.10.2

# values.yaml
image:
  repository: docker.io/bloomberg/goldpinger
  tag: ''

# templates/ds.yaml
# [...]
image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
```

#### Expected behavior

Empty tag is ignored as the default is to use the `appVersion` from the Chart as a tag (which then is not pinned but that's another "issue"). Only when the tag is set to a non-empty value it may be pinned to a digest.

#### Actual behavior

```diff
diff --git a/charts/goldpinger/values.yaml b/charts/goldpinger/values.yaml
index 5e056419..c2eb4f83 100644
--- a/charts/goldpinger/values.yaml
+++ b/charts/goldpinger/values.yaml
@@ -2,6 +2,6 @@

 image:
   repository: docker.io/bloomberg/goldpinger
-  tag: ''
+  tag: '@sha256:3c75265e397a23c8bd3ef01eaf73c4f430ec798e1c0735698408efb47f98fedf'
 ...
```

Which would break the fallback to the `appVersion` and also wouldn't even work as `docker.io/bloomberg/goldpinger:@sha256:3c75265e397a23c8bd3ef01eaf73c4f430ec798e1c0735698408efb47f98fedf` is an `invalid reference format`
