### DISCUSSION TITLE
Is it possible to pass a variable or named capture group from customManagers to customDatasources (transformTemplates) ?

### DISCUSSION THREAD

**Discussion by lordoe** [renovatebot/renovate#33592] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

OpenShift, Renovate version 39.49.3

### Please tell us more about your question or problem

My problem is very simmilar to this [known issue](https://github.com/renovatebot/renovate/discussions/30810) exept that i want to use the capturegroup in the **transformTemplate** part of the customDatasources.

My config is as follows:

```yaml
{
  "customManagers": [
    {
      "customType": "regex",
      "fileMatch": ["values.yaml"],
      "matchStrings": [
        "channel:\\s+(?<channel>\\S+)[\\s\\S]*?csv:\\s+(?<depName>[^\\s]+)\\.v(?<currentValue>\\d+\\.\\d+\\.\\d+)"
      ],
      "versioningTemplate": "semver",
      "datasourceTemplate": "custom.operators-installer"
    }
  ],
  "customDatasources": {
    "operators-installer": {
      "defaultRegistryUrlTemplate": "https://api.openshift.domain:6443/apis/packages.operators.coreos.com/v1/namespaces/openshift-marketplace/packagemanifests/{{ packageName }}",
      "format": "json",
      "transformTemplates": [
        "{ 'releases': status.channels[name={{ channel }}].entries.{ 'version': version } }"
      ]
    }
  }
}
```

As you see i am trying to save the channel to a capureGroup 'channel' and use this capture group in the transformTemplates section.

When hardcoding the value of channel in the transformTemplate part, it works as expected.

Is there any way to do this? 

Thank you in advance

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>

**Comment by rarkins** [comment]
You would need to pass it via one of the fields which is already passed through, e.g. registryUrl and packageName

**Comment by lordoe** [comment]
Thank you. I ended up using the packageNameTemplate, to pass more Variables through packageName and splitting it again in the customDatasource Section:

```yaml
customManagers: [
  {
    customType: "regex",
    fileMatch: ["values.yaml"],
    matchStrings: [
      "channel:\\s+(?<channel>\\S+)[\\s\\S]*?csv:\\s+(?<depName>[^\\s]+)\\.v(?<currentValue>\\d+\\.\\d+\\.\\d+)"
    ],
    versioningTemplate: "semver",
    packageNameTemplate: "{{ depName }}|{{ channel }}",
    datasourceTemplate: "custom.operators-installer"
  }
],
customDatasources: {
  "operators-installer": {
    defaultRegistryUrlTemplate: "https://{{ .Values.api_endpoint }}:6443/apis/packages.operators.coreos.com/v1/namespaces/openshift-marketplace/packagemanifests/{{ lookup (split packageName '|') 0 }}",
    format: "json",
    transformTemplates: [
      "{ 'releases': status.channels[name='{{ lookup (split packageName '|') 1 }}'].entries.{ 'version': version } }"
    ]
  }
}
```
