### DISCUSSION TITLE
Helm OCI within ArgoCD Application

### DISCUSSION THREAD

**Discussion by Xeroxxx** [renovatebot/renovate#33679] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Forgejo

### Please tell us more about your question or problem

I do use renovate for updating the Charts pulled within the my ArgoCD Applicaitons. It works perfectly fine if the helm repository is not an OCI registry. However for n8n its an oci and I can't get it to work.

The app.yaml looks like this:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 8gears.container-registry.com/library
    targetRevision: 0.25.2
    chart: n8n
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
```

the relevant part in my renovate.json looks like this:
```
  "customManagers": [
    {
      "customType": "regex",
      "fileMatch": [
        "^charts/.*\\.yaml$"
      ],
      "matchStrings": [
        "repoURL: (?<registryUrl>\\S+)\\s*targetRevision: (?<currentValue>\\S+)\\s*chart: (?<depName>\\S+)"
      ],
      "datasourceTemplate": "{{#if (containsString registryUrl '8gears.container-registry.com')}}docker{{else}}helm{{/if}}",
      "versioningTemplate": "semver"
    }
  ]
```

No matter what I do, if set to helm it pulls from default helm repo via https, if set to docker it pulls from docker.io instead 8gears.container-registry.com.

Can anyone point me in the right direction? Changing the targetVerison manually works perfectly fine to update.

Cheers
