### DISCUSSION TITLE
helm-values manager with custom keys?

### DISCUSSION THREAD

**Discussion by justyns** [renovatebot/renovate#33808] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

bitbucket, helm

### Please tell us more about your question or problem

The [helm-values manager](https://docs.renovatebot.com/modules/manager/helm-values/) supports values files like this, along with a couple other variations:

```yaml
image:
  repository: 'some-docker/dependency'
  version: v1.0.0
```

I want to update the version in a yaml that looks more like this:

```yaml
serviceA:
  serviceVersion: v1.0.0
serviceB:
  serviceVersion: v1.2.1
```

I can mostly get this working using a custom regex manager, but it has some limitations in that the regex is finicky if there are any other keys in between serviceA: and serviceVersion:, like this:

```yaml
serviceA:
  option1: false
  option2: us-east1
  serviceVersion: v1.0.0
serviceB:
  serviceVersion: v1.2.1
```

This might be a feature request, but is it possible to use the helm-values manager and have it look for specific keys instead of the current image.tag/etc?   If not, is there another manager that can parse a yaml file and then change values based on the yaml jsonpath-equivalent?

Note:  I know another option is to add a comment above the serviceVersion line and have the regex manager look at it, but I'm hoping to avoid that route if possible
