### DISCUSSION TITLE
Split dotnet major updates from the rest of nuget updates

### DISCUSSION THREAD

**Discussion by macco3k** [renovatebot/renovate#33828] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Bitbucket v39.119

### Please tell us more about your question or problem

I have the following configuration file. My expectation/wish is to run non-dotnet nuget and docker updates as their own PRs, and all major dotnet-related stuff as another PR. I assumed that matching by source url with a widlcard could work, but the last package rule seems to be completely ignored. What is the behaviour with overlapping rules? Or am I misinterpreting what I can do by matching by source url?

```yaml
# https://docs.renovatebot.com/config-overview/
platform: "bitbucket"
onboarding: false
requireConfig: "optional"
baseBranches:
  - "main"
separateMajorMinor: true
prHourlyLimit: 5
packageRules:
  # Create separate PRs for docker updates
  - groupName: "(docker)"
    groupSlug: "docker"
    matchManagers:
      - "bitbucket-pipelines"
      - "docker-compose"
      - "dockerfile"
    matchPackageNames:
      - "*"
  # Create separate PRs for nuget updates
  - groupName: "(nuget deps)"
    groupSlug: "nuget"
    matchManagers:
      - "nuget"
    matchPackageNames:
      - "*"
    ignoreDeps:
      - FluentAssertions
  # Create separate PRs for dotnet-related updates.
  # This also includes packages published by the dotnet team, e.g., AspNetCore.
  # This needs to be last as the last matching rule wins in case of overlapping rules,
  # see https://github.com/renovatebot/renovate/discussions/15796.
  - groupName: "(dotnet major updates)"
    groupSlug: "dotnet-major"
    matchUpdateTypes: major
    matchManagers:
      - "bitbucket-pipelines"
      - "docker-compose"
      - "dockerfile"
      - "nuget"
    matchSourceUrls: "https://github.com/dotnet/*"
    # Some packages are following AspNetCore, include them as well
    matchPackageNames:
      - Serilog.AspNetCore
enabledManagers:
  - "bitbucket-pipelines"
  - "docker-compose"
  - "dockerfile"
  - "nuget"
repositories:
  - "$BITBUCKET_REPO_FULL_NAME"
```

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
