### DISCUSSION TITLE
Support 'ssh://git@' repositories in pre-commit

### DISCUSSION THREAD

**Discussion by Alicipy** [renovatebot/renovate#33849] [Suggest an Idea]
### Support ssh://git@ in pre-commit repo URL

In pre-commit, it is possible to explicitly state the protocol used in repositories, e.g.

```
- repo: ssh://git@github.com/alicipy/my-hook-repo
  rev: v2.2.0
  hooks:
    - id: check-my-stuff
```

but renovate does not properly parse the URL. This could be improved. 

I am willing to create a PR and implement proper tests for it
