### DISCUSSION TITLE
Registry alias name change (#33922) no longer groups images from the same place together

### DISCUSSION THREAD

**Discussion by JamesMHenderson** [renovatebot/renovate#33966] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab, renovate v39.146.1

### Please tell us more about your question or problem

The recent change to the way aliases were handled (#33922) stops renovate automatically grouping dependencies if they are from the same place but have different alias names.

We have the example where we have a CI variable to reference a harbor cache ($CI_REGISTRY_IMAGE) in our gitlab-ci file which in our CI pipelines are configured to point to our harbor cache 

e.g

```
  services:
    - name: $CI_REGISTRY_CACHE/selenium/standalone-firefox:120.0@sha256:a405fe92b3ce5d7eb31a07e1f99be3d628fdc0e5bdc81febd8dc11786edef024
      alias: selenium
```

Renovate is then configured to alias this to to docker.io

We then have a docker-compose file that we run locally so do not have the variable CI_REGISTRY_CACHE configured so need to reference docker.io directy

```
version: '3.8'
services:
  chrome:
    image: 'docker.io/selenium/standalone-chrome:121.0@sha256:529a9b0ab0e41bf1bc9a8984c4b803e30160042d3bec9a8454d65afd6db023ee'
    container_name: chrome-selenium
```

Before the change in #33922 as the images were the same these were grouped as they are updating the same docker image, but not renovate separates them out to treat them as separate dependencies. Is it possible to revert this breaking change of behaviour in config so that aliases are treated as they were previously without configuring custom package rules?

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
