### DISCUSSION TITLE
override default registry in helm-values

### DISCUSSION THREAD

**Discussion by JamesMHenderson** [renovatebot/renovate#34125] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab

### Please tell us more about your question or problem

When specifying an image you need to specify the `registry` key when the image doesn't come from `docker.io` is it possible to override the default registry so it can use a custom registry as the default?

This is so I don't need to specify the custom registry when defining each image to get renovate updating the images

```
guiImage:
  repository: "product/gui"
  version: "7.8.0"
  registry: "custom.registry.com"
  
apiImage:
  repository: "product/api"
  version: "5.7.0"
  registry: "custom.registry.com"
```

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
