### DISCUSSION TITLE
regex manager only detecting first dependency

### DISCUSSION THREAD

**Discussion by JanMalte** [renovatebot/renovate#34245] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab 39.170.1

### Please tell us more about your question or problem

I have configured a custom `regex` manager to update my `pip install XXX==yyy` statements in the `.gitlab-ci.yaml`.

The first depdency is shown in the dependency dashboard and gets updated. But the second one is not listed and therefor not getting any updates.

minimal reproduction repo: https://github.com/JanMalte/renovate-regex-test

```json
{
  "customManagers": [
    {
      "customType": "regex",
      "description": "RegEx Manager for pypi packages in GitLab CI/CD and Dockerfile",
      "fileMatch": ["Dockerfile$", "\\.gitlab-ci\\.yml$"],
      "matchStrings": [
        "\\n((RUN)|(\\s+-))\\s+pip\\s+install\\s*(?<depName>[\\w\\.\\-]+)==(?<currentValue>[\\d\\.]+)\\s*\\n"
      ],
      "datasourceTemplate": "pypi"
    }
  ]
}
```

```yaml
python_job:
    image: python:3.11.11
    before_script:
        # print tool versions for debug purpose if job is failing
        - python --version
        # install pip and poetry
        - pip install pip==24.3.1
        - pip install poetry==1.6.1
        # print tool versions for debug purpose if job is failing
        - pip --version
        - poetry --version
```
