### DISCUSSION TITLE
Multiple repos with gitlab ci/cd

### DISCUSSION THREAD

**Discussion by apolienko** [renovatebot/renovate#34287] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab 

### Please tell us more about your question or problem

 include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate.gitlab-ci.yml'
    ref: v20.0.0
    
    CI_RENOVATE_IMAGE: ghcr.io/renovatebot/renovate:39.171.2
    
    Hey! I have a question how to configure Renovate in separate repo in the gitlab project to make it work with other repos in this project? 
    I know how to configure it for one repo. But then I realized that I need to schedule a job in 50 microservice repositories, so the way to separate Renovate and create schedule pipeline for it in only one repo seems more convinient. 
    I tried to google it and didnt find any solution. My current configuration:
    
  ```
    renovate:
  stage: deps-update
  image: ${CI_RENOVATE_IMAGE}
  variables:
    RENOVATE_EXTRA_FLAGS: '$CI_PROJECT_PATH'
    LOG_LEVEL: 'debug'
    RENOVATE_HOST_RULES: '[{"matchHost": "gitlab.com","token": "${RENOVATE_TOKEN}"}]'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  tags:
    - "$RUNNER_TAG"
 ```
 
    
    renovate.json:
    
```
{
  "extends": ["config:base"]
}
```

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
