### DISCUSSION TITLE
bumpVersion does not work with static version field for PEP621/Poetry

### DISCUSSION THREAD

**Discussion by straurob** [renovatebot/renovate#34331] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab; Renovate version: 39.173.1

### Please tell us more about your question or problem

In a Python project with Poetry, I'd like to use Renovate's `bumpVersion` option to automatically update the version in the `pyproject.toml`.

Renovate successfully recognizes the update of `requests` and updates the version to 2.32.2. However, the version in the `pyproject.toml` is not updated.

I inspected the code and it should at least print a debug output with:

> Checking if we should bump pyproject.toml version

I cannot find this in the log files so maybe there is something else I need to configure?

https://github.com/renovatebot/renovate/blob/37.435.0/lib/modules/manager/pep621/update.ts#L14

### pyproject.toml
```toml
[project]
name = "pythonproject"
version = "0.1.0"
description = "Test description"
authors = [
    { name = "Foo Bar", email = "foo@bar" }
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests (==2.32.1)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
```

### renovate.json
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:best-practices",
    "group:allNonMajor"
  ],
  "bumpVersion": "minor"
}
```

### Minimum Reproduction Repository
https://github.com/straurob/renovate-bump-version-repro

### Logs (if relevant)

https://gist.github.com/straurob/b6e41e5380045ea33726850d4e1a66a6

**Comment by github-actions** [comment]
Hi there,

You're reporting a problem with an old version of Renovate. Please try the latest version and tell us if that fixes your problem.

Be sure to provide updated logs once you have run with a newer version.

Good luck,

The Renovate team

**Reply by straurob** [reply]
Updated to latest version 39.

**Comment by github-actions** [comment]
Hi there,

Please help this Discussion progress by creating a minimal reproduction. This means a repository dedicated to reproducing this issue with the minimal dependencies and config possible.

Before we start working on your issue we need to know exactly what's causing the current behavior. A minimal reproduction helps us with this. Discussions without reproductions are less likely to be converted to Issues.

Please follow these steps:
 1. Read our guide on creating a [minimal reproduction](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md).
 2. Go to our [minimal reproduction template repository](https://github.com/renovatebot/minimal-reproduction-template).
 3. Select the _Use this template_ button to create a new repository based on the template.
 4. Work on the minimal reproduction in your own repository.
 5. Fill out the information in your repository's `README.md`.
 6. Add the link to your reproduction to the first post of your Discussion. If you are not the original author, you can post a new comment with the link.

If you need help with running renovate on your minimal reproduction repository, please refer to our [Running Renovate guide](https://docs.renovatebot.com/getting-started/running/).
Good luck,

The Renovate team

**Reply by straurob** [reply]
https://github.com/straurob/renovate-bump-version-repro

**Comment by straurob** [comment, marked as answer]
Ok, it seems as if I found the reason. The `version` property must not be defined statically but dynamically.

This works:

```toml
[project]
dynamic = ["version"]

[tool.poetry]
version = "0.2.0"
```
