### DISCUSSION TITLE
Problem with Helm values.yaml updates

### DISCUSSION THREAD

**Discussion by alita1991** [renovatebot/renovate#34464] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab and Renovate:39.106.0-full

### Please tell us more about your question or problem

Hi,

I'm looking for guidance on updating the **opentext/verticadb-operator** and **kubebuilder/kube-rbac-proxy** images defined in **values.yaml**. Currently, the setup works well only for **nginx**. Could you please advise on the best approach to achieve this?

renovate.json
```
{
    "extends": [
        "config:base"
    ]
}

```
values.yaml
```
image:
  repo: docker.io
  name: opentext/verticadb-operator:24.4.0-0
  pullPolicy: IfNotPresent

rbac_proxy_image:
  repo: gcr.io
  name: kubebuilder/kube-rbac-proxy:v0.0.1

nginx_image:
  repository: nginx
  tag: 1.0.0
  pullPolicy: IfNotPresent

```

### Logs (if relevant)

```
{
  "branchName": "renovate/nginx-1.x",
  "prNo": null,
  "prTitle": "chore(deps): update nginx docker tag to v1.27.4",
  "result": "no-work",
  "upgrades": [
    {
      "datasource": "docker",
      "depName": "nginx",
      "displayPending": "",
      "fixedVersion": "1.0.0",
      "currentVersion": "1.0.0",
      "currentValue": "1.0.0",
      "newValue": "1.27.4",
      "newVersion": "1.27.4",
      "packageFile": "verticadb-operator/values.yaml",
      "updateType": "minor",
      "packageName": "nginx"
    }
  ]
},
```
