### DISCUSSION TITLE
Helm renovate bot setup - gitea.com

### DISCUSSION THREAD

**Discussion by plsnotracking** [renovatebot/renovate#34525] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

gitea

### Please tell us more about your question or problem

I'm using ArgoCD - Helm charts to deploy renovate bot. I'm about mostly there.

Here's what my `values.yaml` for renovate bot helm chart looks like

```YAML
renovate:
  # -- Inline global renovate config.json
  # See https://docs.renovatebot.com/self-hosted-configuration
  config: |
    {
      "platform": "gitea",
      "endpoint": "https://gitea.com/api/v1",
      "gitAuthor": "Renovate Bot <bot@renovatebot.com>",
      "autodiscover": "false",
      "dryRun": false,
      "printConfig": false,
      "repositories": ["sample/external"],
      "extends": ["config:base"],
      "enabledManagers": ["helmv3"],
      "commitMessageTopic": "helm chart {{depName}}",
    }
.
.
.
```

The structure of my git `repo` looks like this
```
/root
  /external
    /project-1
      / Chart.yaml <-- file with the helm chart version
    /project-2
      / Chart.yaml <-- file with the helm chart version
    /project-3
      / Chart.yaml <-- file with the helm chart version
    /project-4
      / Chart.yaml <-- file with the helm chart version
    /project-5
      / Chart.yaml <-- file with the helm chart version
.
.
.
```

As a sample (if it helps), this is what my `Chart.yaml` look like
```YAML
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
spec:
  destination:
    namespace: renovate
    name: external
  project: external
  sources:
    # Chart from Chart Repo
    - chart: renovate
      repoURL: https://docs.renovatebot.com/helm-charts
      targetRevision: 39.182.3
.
.
.
```

However, no files are picked up, as confirmed by logs below. Any help would be appreciated, thank you.

### Logs (if relevant)

<details><summary>Logs</summary>

```
INFO: Dependency extraction complete (repository=sample/external, baseBranch=main)
       "stats": {"managers": {}, "total": {"fileCount": 0, "depCount": 0}}

```

</details>
