### DISCUSSION TITLE
matchStringsStrategy = any with jsonata?

### DISCUSSION THREAD

**Discussion by evilensky** [renovatebot/renovate#34700] [Request Help]
### How are you running Renovate?

A Mend.io-hosted app

### what I think my question is

Can I get a jsonata manager to match multiple times per file?

### What I'm trying to do

My source document looks like this:

<details><summary>Details</summary>
<p>

```yaml
---
# yamllint disable-line rule:line-length
# renovate: datasource=helm depName=twistlock-defender registryUrl=https://helm-repository.jfrog.io/artifactory/helm-local versioning=loose
chart_version: v33.02.134
chart_name: twistlock-defender
repo_url: https://helm-repository.jfrog.io/artifactory/helm-local
namespace: twistlock
apptype: controller
overrides: {}
  tools-dev:
    # renovate: environment=tools-dev datasource=helm depName=twistlock-defender registryUrl=https://helm-repository.jfrog.io/artifactory/helm-local versioning=loose
    chart_version: v33.00.169
    chart_name: twistlock
```

</p>
</details> 

I have a regex manager that looks like this:

The intent of this is to create separate PRs for different values in the same file for the same package: ArgoCD is configured with a general version number but has an `overrides` key that can specify other keys which are environments. We want to receive separate suggestions for overrides if present. I've overloading `depType` for the environment name value.

<details><summary>Details</summary>
<p>

```json
  "regex": {
    "packageRules": [
      {
        "description": "argocd-platform-config: Create a separate PR for overrides for tools-dev environment",
        "commitMessageTopic": "dependency {{depName}}{{#if depType}} for environment {{depType}}{{/if}}",
        "recreateClosed": true,
        "matchUpdateTypes": ["major", "minor", "patch"],
        "additionalBranchPrefix": "argocd-{{depType}}-{{depName}}-{{newVersion}}",
        "matchFileNames": ["addons/*/config.yml"
         ],
        "pinDigests": false,
        "matchManagers": ["regex"]
      }
    ]
  },
  // Manager for addons in the path `addons/**/*.yml` or `addons/**/*.yaml`
  // It should identify chart_version: 1.0.0 in the file and manage the version
  "regexManagers": [
    {
      "description": "Manager for helm chart versions in argocd config.yml, one match on main value and one match per environment",
      "fileMatch": ["^addons\\/[^\\/]*\\/config\\.yml$"],
      "matchStringsStrategy": "any",
      "matchStrings": [
        "#\\s?renovate:\\s?datasource=(?<datasource>.*?)\\s+depName=(?<depName>.*?)\\s+registryUrl=(?<registryUrl>.*?)\\s+versioning=(?<versioning>.*?)\\s*\\n\\s*chart_version:\\s*(?<currentValue>.*)",
        "#\\s?renovate:\\s?environment=(?<depType>.*?)datasource=(?<datasource>.*?)\\s+depName=(?<depName>.*?)\\s+registryUrl=(?<registryUrl>.*?)\\s+versioning=(?<versioning>.*?)\\s*\\n\\s*chart_version:\\s*(?<currentValue>.*)"
      ],
      "versioningTemplate": "{{#if versioning}}{{{versioning}}}{{else}}semver{{/if}}"
    }
  ]
```
</p>
</details> 

I would like to replace regex with jsonata.  

* I tried various things including two separate match managers
* a very complex jsonata query that matches on both
* using matchstrings and trying to set `matchStringsStrategy` to any

Is there a more correct approach here?

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
