### DISCUSSION TITLE
Add support for `pnpm/action-setup` with `version:` updates

### DISCUSSION THREAD

**Discussion by alexfaxe** [renovatebot/renovate#34724] [Suggest an Idea]
### Tell us more.

Similar to the recent feature addition done in https://github.com/renovatebot/renovate/issues/34658

The `github-actions` manager should be updated to extract the version value when using [pnpm/action-setup](https://github.com/pnpm/action-setup).

Example syntax:
```
- name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.6.1
```
