### DISCUSSION TITLE
Any way to disable oci registries for helm?

### DISCUSSION THREAD

**Discussion by muja** [renovatebot/renovate#34743] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### Please tell us more about your question or problem

Nexus does not support OCI type helm dependencies: https://github.com/sonatype/nexus-public/issues/201

Unfortunately Nexus doesn't filter them out in the `index.yaml` (for proxied repositories) so Renovate will still see them and try to update to them.

Is there any way to disable OCI registries for helm?

For example, `bitnami/postgresql` started using oci:// URLs starting 16.2.2, in the index.yaml it is evident that it is used when you compare 16.2.1 and 16.2.2 (note the URL at the end):

16.2.1:

```yaml
  - annotations:
      category: Database
      images: |
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r33
        - name: postgres-exporter
          image: docker.io/bitnami/postgres-exporter:0.16.0-debian-12-r1
        - name: postgresql
          image: docker.io/bitnami/postgresql:17.1.0-debian-12-r0
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 17.1.0
    created: "2024-11-14T16:48:19.364183696Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: 7722aeed7add5856336b739de740e0d80c4587e81f145e2cfba5124fd8acec93
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    urls:
    - https://charts.bitnami.com/bitnami/postgresql-16.2.1.tgz
    version: 16.2.1
```

16.2.2: 

```yaml
  - annotations:
      category: Database
      images: |
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r33
        - name: postgres-exporter
          image: docker.io/bitnami/postgres-exporter:0.16.0-debian-12-r1
        - name: postgresql
          image: docker.io/bitnami/postgresql:17.2.0-debian-12-r0
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 17.2.0
    created: "2024-11-21T20:34:46.452749188Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: a6cc6189b9d506d13f6b6873d30003d46c2623697944ffaf0c8eb49bdac6673f
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    urls:
    - oci://registry-1.docker.io/bitnamicharts/postgresql:16.2.2
    version: 16.2.2
```

Renovate provides these update values:

```json
{
    "depName": "postgresql",
    "currentValue": "15.5.0",
    "registryUrls": [
        "https://nexus.internal/repository/bitnami-helm-proxy"
    ],
    "updates": [
        {
            "bucket": "non-major",
            "newVersion": "15.5.38",
            "newValue": "15.5.38",
            "newDigest": "6537de714df16f71c720921bd0ad8fad90bb01525fb3aacff3503781de3f9f8b",
            "releaseTimestamp": "2024-10-01T17:40:21.624Z",
            "newVersionAgeInDays": 160,
            "newMajor": 15,
            "newMinor": 5,
            "newPatch": 38,
            "updateType": "patch",
            "libYears": 0.34347392744799593,
            "branchName": "renovate/postgresql-15.x"
        },
        {
            "bucket": "major",
            "newVersion": "16.5.0",
            "newValue": "16.5.0",
            "newDigest": "6a3fc8b3605a7695a35120d858e215f0594310b6e2d5f7c453c663f9b0bbb28c",
            "releaseTimestamp": "2025-03-10T11:32:31.556Z",
            "newVersionAgeInDays": 0,
            "newMajor": 16,
            "newMinor": 5,
            "newPatch": 0,
            "updateType": "major",
            "libYears": 0.78113025456621,
            "branchName": "renovate/postgresql-16.x"
        }
    ],
    "packageName": "postgresql",
    "versioning": "helm",
    "warnings": [],
    "sourceUrl": "https://github.com/bitnami/charts",
    "registryUrl": "https://nexus.internal/repository/bitnami-helm-proxy",
    "sourceDirectory": "bitnami/postgresql",
    "currentVersion": "15.5.0",
    "currentVersionTimestamp": "2024-05-29T08:50:27.848Z",
    "currentVersionAgeInDays": 285,
    "isSingleVersion": true,
    "fixedVersion": "15.5.0"
}
```

My current workaround is to use the releaseTimestamp, but it is not exactly robust:

```json
    {
      "matchDatasources": [
        "helm"
      ],
      "matchJsonata": [
        "$contains(registryUrl, '/bitnami-helm-proxy') and releaseTimestamp >= '2024-11-21T20:34:46.452749188Z'"
      ],
      "enabled": false
    }
```

is there another way?

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
