### DISCUSSION TITLE
Gitlab Pypi Registry - pyproject.toml contains ENV Vars

### DISCUSSION THREAD

**Discussion by jseiser** [renovatebot/renovate#34741] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Gitlab Runner

### Please tell us more about your question or problem

We get `⚠️ Artifact update problem` on any MR that includes our self hosted, private, Gitlab Pypi registry.  

It does correctly detect there is a new version, but the `pipenv` step fails to find any versions.

our Pipfile looks like this, and there is a new version of the `company` python lib out there.

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "https://${USERNAME}:${PASSWORD}@gitlab.company.network/api/v4/groups/4/-/packages/pypi/simple"
verify_ssl = true
name = "company_gitlab"

[packages]
fastapi = {extras = ["standard"], version = "*"}
uvicorn = {extras = ["standard"], version = "==0.32.0"}
company = {version = "==0.10.0", index="company_gitlab"}
```

In our gitlab-ci.yaml, when we build etc, we do the below, and everything works.

```
    - echo "USERNAME=gitlab-ci-token" > .env
    - echo "PASSWORD=$CI_JOB_TOKEN" >> .env
```

My current attempt to make this work, looks like this

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "local>renovate/renovate-config",
    "local>renovate/renovate-config:assignees-all"
  ],
  "packageRules": [
    {
      "matchManagers": ["pipenv"],
      "labels": ["python"]
    }
  ],
  "hostRules": [
    {
      "hostType": "pypi",
      "matchHost": "https://gitlab.company.network/api/v4/groups/4/-/packages/pypi/simple",
      "username": "gitlab-ci-token",
      "password": "${CI_JOB_TOKEN}"
    }
  ],
  "enabledManagers": ["pipenv"],
  "baseBranches": ["develop"]
}
```

### Logs (if relevant)

Full Gist: https://gist.github.com/jseiser/7d9d5697f30a05e824e5c0c0a97c8840
