### DISCUSSION TITLE
Gitlab Runner Working Parallel Matrix Job

### DISCUSSION THREAD

**Discussion by jseiser** [renovatebot/renovate#34751] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

gitlab-runner

### Please tell us more about your question or problem

Renovate runs so long, we actually do not get through all our repo's.  So we are trying to find a way to run multiple jobs at once.  Like documented here: https://medium.com/notive/optimizing-renovate-for-gitlab-with-500-repositories-6d225f24ff79

I assume things have since changed with the runner job template, because whats shown no longer works.

Copying what that blog post shows, but using the current template.

```
> tree -a -L 2
.
├── config.js
├── .gitlab-ci.yml
├── README.md
└── template
    └── .gitlab-ci.yml
```

.gitlab.yml
```yaml
include:
  - project: "renovate/renovate-runner"
    file: "/templates/renovate.gitlab-ci.yml"

renovate:
  variables:
    RENOVATE_AUTODISCOVER: "true"
    RENOVATE_AUTODISCOVER_FILTER: "company/depends/*"
    RENOVATE_ONBOARDING: "false"
  script:
    - renovate --write-discovered-repos=template/renovate-repos.json
    - sed "s~###RENOVATE_REPOS###~$(cat template/renovate-repos.json)~" template/.gitlab-ci.yml > .gitlab-renovate-repos.yml
  artifacts:
    paths:
      - renovate-repos.json
      - .gitlab-renovate-repos.yml

renovate:repos:
  stage: deploy
  needs:
    - renovate
  inherit:
    variables: false
  trigger:
    include:
      - job: renovate
        artifact: .gitlab-renovate-repos.yml
```

template/.gitlab.yml
```yaml
include:
  - project: "renovate/renovate-runner"
    file: "/templates/renovate.gitlab-ci.yml"

variables:
  RENOVATE_ONBOARDING: "false"

renovate:
  parallel:
    matrix:
      - RENOVATE_EXTRA_FLAGS: ###RENOVATE_REPOS###
  resource_group: $RENOVATE_EXTRA_FLAGS
```

This errors when you push.

>  Unable to create pipeline 'renovate:repos' job needs 'renovate' job, but 'renovate' is not in any previous stage

I assume this has something to do with the rules on the `renovate` pipeline, but I have not been able to find a combination that allows this to run

**Comment by viceice** [comment]
yes, you need to override `rules` on your jobs

**Reply by jseiser** [reply]
Any idea to what?

I tried it like this, where I had the `renovate:repos` use the same rules

```
renovate:
  variables:
    RENOVATE_AUTODISCOVER: "true"
    RENOVATE_AUTODISCOVER_FILTER: "group/**"
    RENOVATE_ONBOARDING: "false"
  script:
    - renovate --write-discovered-repos=template/renovate-repos.json
    - sed "s~###RENOVATE_REPOS###~$(cat template/renovate-repos.json)~" template/.gitlab-ci.yml > .gitlab-renovate-repos.yml
  artifacts:
    paths:
      - template/renovate-repos.json
      - .gitlab-renovate-repos.yml

renovate:repos:
  stage: deploy
  needs:
    - job: renovate
  inherit:
    variables: false
  trigger:
    include:
      - job: renovate
        artifact: .gitlab-renovate-repos.yml
  rules:
    - !reference [renovate, rules]

```

I then tried it, w/out rules on the `renovate:repos` and either way it fails to run `renovate:repos` because

```
gitlab downstream pipeline cannot be created the resulting pipeline would have been empty
```

I am getting `.gitlab-renovate-repos.yml` created, and it looks how i imagine it should

```
include:
  - project: "renovate/renovate-runner"
    file: "/templates/renovate.gitlab-ci.yml"

variables:
  RENOVATE_ONBOARDING: "false"

renovate:
  parallel:
    matrix:
      - RENOVATE_EXTRA_FLAGS: ["big", "list", "of", "repos"]
  resource_group: $RENOVATE_EXTRA_FLAGS
```

**Reply by jseiser** [reply]
we got it.

**Reply by viceice** [reply]
please provide the solution for other users 🙏

**Comment by jseiser** [comment]
The template/.gitlab-ci.yml is what needs rules on it

**Comment by jseiser** [comment]
In out of the office, I'll post it Monday, it's 99% what you posted with a
few tweaks

**Comment by jseiser** [comment, marked as answer]
OK here is my working example, NOTE, we also added some options to run manually as well.

Here is our dir structure.

```
> tree -a -L 2
.
├── config.js
├── .gitlab-ci.yml
├── README.md
└── template
    └── .gitlab-ci.yml
```

.gitlab-ci.yml
```yaml
variables:
  RENOVATE_EXTRA_FLAGS:
    description: "Specify which repo to run against"

include:
  - remote: https://gitlab.com/renovate-bot/renovate-runner/-/raw/v20.1.0/templates/renovate.gitlab-ci.yml

renovate:
  image:
    name: ghcr.io/renovatebot/renovate:39.200.2
    pull_policy: if-not-present
  variables:
    RENOVATE_AUTODISCOVER: "true"
    RENOVATE_AUTODISCOVER_NAMESPACES: "GITLAB_GROUP"
    RENOVATE_ONBOARDING: "false"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: never
  script:
    - renovate --write-discovered-repos=template/renovate-repos.json
    - |
      # Define the input JSON file
      input_file="template/renovate-repos.json"

      # Read the JSON array from the input file
      json_array=$(cat "$input_file")

      # Split the JSON array into smaller arrays of 5 elements
      split_array=$(echo "$json_array" | jq -r '.[]' | xargs -n10)

      # Merge the split JSON arrays into a single array with elements joined by spaces
      merged_array=$(echo "$split_array" | jq -R . | jq -s '.')

      # Write the merged array to the output file
      echo "$merged_array" | tr -d '\n' > "template/renovate-repos-merged.json"

    - sed "s~###RENOVATE_REPOS###~$(cat template/renovate-repos-merged.json)~" template/.gitlab-ci.yml > .gitlab-renovate-repos.yml
  artifacts:
    paths:
      - template/renovate-repos.json
      - .gitlab-renovate-repos.yml

renovate:repos:
  stage: deploy
  needs:
    - job: renovate
  inherit:
    variables: false
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: never
  trigger:
    include:
      - job: renovate
        artifact: .gitlab-renovate-repos.yml

renovate:manual:
  extends: .renovate
  image:
    name: ghcr.io/renovatebot/renovate:39.200.2
    pull_policy: if-not-present
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
  variables:
    RENOVATE_AUTODISCOVER: "false"
    RENOVATE_ONBOARDING: "false"
```


Note, you do not need to hardcode the images, or have `renovate:manual` at all.  `renovate:manual` lets you just specify a specific repo to run renovate against, which works nicely if you want to test/rebase etc outside of the scheduled job.


template/.gitlab-ci.yml
```yaml
include:
  - remote: https://gitlab.com/renovate-bot/renovate-runner/-/raw/v20.1.0/templates/renovate.gitlab-ci.yml
variables:
  RENOVATE_ONBOARDING: "false"

renovate:
  parallel:
    matrix:
      - RENOVATE_EXTRA_FLAGS: ###RENOVATE_REPOS###
  resource_group: $RENOVATE_EXTRA_FLAGS
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
```
