### DISCUSSION TITLE
upgrading images from helm values files with multiple images

### DISCUSSION THREAD

**Discussion by christf** [renovatebot/renovate#34826] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

forgejo, renovate updates itself so I am using whatever is most recent :-)

### Please tell us more about your question or problem

I am looking for guidance on how to keep deployments properly patched for helm charts that deploy multiple containers. An example would be mailu (but there are certainly more out there): https://github.com/Mailu/helm-charts/blob/master/mailu/values.yaml

The common element is that these charts specify values files with a structure that has multiple containers and images

```
values:
  webmail:
    image:
      tag: 1.2.3
  redis:
    image:
      tag: 5.6.7
```

Currently I use regexManagers to identify tags in such values files and renovate will raise pull requests for those just fine. However that will only work for one image-tag in one file.
In the above situation I cannot split the values file (and therefore using multiple regex managers is not possible) nor can I use a regex matcher for both, the webmail and the redis container as both follow very different versioning cycles.

What would be a good way of tackling this?
I feel this should be easy and right there in the docs but somehow this is eluding me.

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>

**Comment by Nold360** [comment, marked as answer]
I like to use a simple custom regex manager for these cases: https://docs.renovatebot.com/modules/manager/regex/

your values could look something like that:
```yaml
values:
  webmail:
    image:
      # renovate: datasource=docker depName=somename/webmail registryUrl=https://quay.io
      tag: 1.2.3
  redis:
    image:
      # renovate: datasource=docker depName=somename/redis
      tag: 5.6.7
```
