### DISCUSSION TITLE
How to setup allowedCommands with template: Should the regex match the template value or resolved value?

### DISCUSSION THREAD

**Discussion by jase88** [renovatebot/renovate#34894] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab

### Please tell us more about your question or problem

Given the following Repository configuration:
```json
{
  "allowedCommands": ["ng update {{{depName}}} --from={{{currentVersion}}} --to={{{newVersion}}} --migrate-only --allow-dirty --force"]
}
```

How would I need to setup the self hosted configuration with `allowedCommands`? Should the regex cover the template string or the resolved value?

Should it be
```yml
variables:
  RENOVATE_ALLOW_COMMAND_TEMPLATING: "true"
  RENOVATE_ALLOWED_COMMANDS: '["ng update ([a-zA-Z@\/.-]+) --from=([0-9]+.[0-9]+.[0-9]+) --to=([0-9]+.[0-9]+.[0-9]+) --migrate-only --allow-dirty --force$"]'
 ```

or

```yml
variables:
  RENOVATE_ALLOW_COMMAND_TEMPLATING: "true"
  RENOVATE_ALLOWED_COMMANDS: '["ng update {{{depName}}} --from={{{currentVersion}}} --to={{{newVersion}}} --migrate-only --allow-dirty --force$"]'
 ```

This isn't reflected in the docs
