### DISCUSSION TITLE
Renovate should auto-group between OCI Helm Charts in a Helmfile and a Flux OCIRepository

### DISCUSSION THREAD

**Discussion by onedr0p** [renovatebot/renovate#35005] [Request Help]
### How are you running Renovate?

A Mend.io-hosted app

### Please tell us more about your question or problem

When using helmfile with regular Helm charts (non-OCI) and Flux with a HelmRepository, the PRs are auto-grouped, however I have a Helmfile with OCI charts and also Flux OCIRepository with the same chart, these could be auto-grouped together...

## helmfile.yaml

```yaml
releases:
  - name: flux-operator
    namespace: flux-system
    atomic: true
    chart: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
    version: 0.17.0
```

## ocirepository.yaml

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux-operator
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.17.0
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
```

I would expect when a PR is opened to bump these versions they would be auto-grouped in the same PR, however it currently looks like this:

<img width="675" alt="image" src="https://github.com/user-attachments/assets/d6d23825-f5b0-4438-9133-92fa344dfe12" />

Reproduction repo incoming...

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
