### DISCUSSION TITLE
Better sorting of SemVer version updates.

### DISCUSSION THREAD

**Discussion by ThomasSteinbach** [renovatebot/renovate#35108] [Suggest an Idea]
### Tell us more.

When using `separateMultipleMinor=true` and thus having multiple minor version upgrade PRs, I noticed that Renovate sorts SemVer versions alphabetically instead of numerical.

Wrong sorting example: `1.1.0` -> `1.10.0` -> `1.2.0`

Expected sorting: `1.1.0` -> `1.2.0` -> `...` -> `1.10.0`

## Example

Using `"extends": ["config:best-practices", ":disableRateLimiting"]`, for following `kustomization.yaml`...

```yaml
helmCharts:
  # https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/Chart.yaml
  - name: gitlab
    repo: https://charts.gitlab.io
    version: 7.1.8
    releaseName: gitlab
    namespace: gitlab
    valuesFile: values.yaml
    includeCRDs: true
```

... Renovate creates PRs in following order ...

<img width="500" alt="Bildschirmfoto 2025-03-31 um 14 38 46" src="https://github.com/user-attachments/assets/d32babc0-ce99-4ff7-bbaf-3cdf8cda1426" />

Have a look at the dependency dashboard of my minimal reproduction repo:

👉 https://github.com/ThomasSteinbach/renovate-wrong-semver-sorting-example/issues/12

## Conclusion

Renovate should sort SemVer version upgrades numerically by patch, then minor, then major. This is necessary, when using `automerge=true` and the deployed application is doing migration tasks after each (minor) upgrade, like Gitlab does for example.

## minimal reproduction repository

👉 https://github.com/ThomasSteinbach/renovate-wrong-semver-sorting-example
