### DISCUSSION TITLE
go.sum not fully updated when bumping the version of a package in the 1.24 tools section

### DISCUSSION THREAD

**Discussion by richjyoung** [renovatebot/renovate#35162] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitHub

### Please tell us more about your question or problem

When Renovate (v39.232.2) updates a package in the tool section of the go.mod (golang 1.24+), I can see some entries in the go.sum but I get an error next time I run the tool. For background this was encountered when github.com/vektra/mockery/v2 was upgraded from v2.45.1 to v2.53.3 by Renovate.

Running `go tool mockery` resulted in:
```
missing go.sum entry for module providing package github.com/vektra/mockery/v2; to add:
        go mod download github.com/vektra/mockery/v2
```

This is the relevant content from the go.mod file:

```
module example.com/redacted

go 1.24

require (
	...
)

tool (
	github.com/vektra/mockery/v2
)

require (
	github.com/vektra/mockery/v2 v2.53.3 // indirect
)
```

Post-merge, Renovate has the following entries in the go.sum for mockery:

```
github.com/vektra/mockery/v2 v2.45.1 h1:6HpdnKiLCjVtzlRLQPUNIM0u7yrvAoZ7VWF1TltJvTM=
github.com/vektra/mockery/v2 v2.45.1/go.mod h1:XNTE9RIu3deGAGQRVjP1VZxGpQNm0YedZx4oDs3prr8=
github.com/vektra/mockery/v2 v2.53.3/go.mod h1:hIFFb3CvzPdDJJiU7J4zLRblUMv7OuezWsHPmswriwo=
```

After running `go mod download github.com/vektra/mockery/v2` as instructed in the error and `go mod tidy`, only the 2.53.3 lines for mockery should be in the go.sum, including a missing `h1:` line:

```
github.com/vektra/mockery/v2 v2.53.3 h1:yBU8XrzntcZdcNRRv+At0anXgSaFtgkyVUNm3f4an3U=
github.com/vektra/mockery/v2 v2.53.3/go.mod h1:hIFFb3CvzPdDJJiU7J4zLRblUMv7OuezWsHPmswriwo=
```

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>

**Comment by github-actions** [comment]
Hi there,

Please help this Discussion progress by creating a minimal reproduction. This means a repository dedicated to reproducing this issue with the minimal dependencies and config possible.

Before we start working on your issue we need to know exactly what's causing the current behavior. A minimal reproduction helps us with this. Discussions without reproductions are less likely to be converted to Issues.

Please follow these steps:
 1. Read our guide on creating a [minimal reproduction](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md).
 2. Go to our [minimal reproduction template repository](https://github.com/renovatebot/minimal-reproduction-template).
 3. Select the _Use this template_ button to create a new repository based on the template.
 4. Work on the minimal reproduction in your own repository.
 5. Fill out the information in your repository's `README.md`.
 6. Add the link to your reproduction to the first post of your Discussion. If you are not the original author, you can post a new comment with the link.

If you need help with running renovate on your minimal reproduction repository, please refer to our [Running Renovate guide](https://docs.renovatebot.com/getting-started/running/).
Good luck,

The Renovate team

**Comment by trim21** [comment]
renovate handle the major upgrade with https://github.com/marwan-at-work/mod (`mod upgrade --mod-name=${depName} -t=${newMajor}`) , I guess should also report this issue there

**Comment by tboerger** [comment]
Is there any proper way within Renovate available? Currently I'm working around it by labeling the PR if it updates specific packages and I have added a workflow like the following to update the dependency correctly, but the workflow quite often fails after merging a PR:

```
---
name: tools

"on":
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  tools:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'tools')

    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Update golangci
        if: contains(github.event.pull_request.labels.*.name, 'golangci')
        run: |
          go get github.com/golangci/golangci-lint/v2/cmd/golangci-lint
          go mod tidy

      - name: Update revive
        if: contains(github.event.pull_request.labels.*.name, 'revive')
        run: |
          go get github.com/mgechev/revive
          go mod tidy

      - name: Update mockgen
        if: contains(github.event.pull_request.labels.*.name, 'mockgen')
        run: |
          go get github.com/golang/mock/mockgen
          go mod tidy

      - name: Update codegen
        if: contains(github.event.pull_request.labels.*.name, 'codegen')
        run: |
          go get github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen
          go mod tidy

      - name: Update repo
        run: git pull --rebase --autostash

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: github@example.com
          add: go.*
          message: "chore: update modules for tools update"
          push: true
          commit: --signoff

...
```

This is the renovate config to label the related PRs:

```

{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "packageRules": [
    {
      "matchPackageNames": [
        "/^github.com\/golangci\/golangci-lint\/v2/"
      ],
      "labels": [
        "tools",
        "golangci"
      ]
    },
    {
      "matchPackageNames": [
        "/^github.com\/mgechev\/revive/"
      ],
      "labels": [
        "tools",
        "revive"
      ]
    },
    {
      "matchPackageNames": [
        "/^github.com\/golang\/mock/"
      ],
      "labels": [
        "tools",
        "mockgen"
      ]
    },
    {
      "matchPackageNames": [
        "/^github.com\/oapi-codegen\/oapi-codegen\/v2/"
      ],
      "labels": [
        "tools",
        "codegen"
      ]
    }
  ]
}
```
