### DISCUSSION TITLE
pixi: seems unusable without `matchPixiFeature` or similar

### DISCUSSION THREAD

**Discussion by lucascolley** [renovatebot/renovate#35251] [Request Help]
### How are you running Renovate?

A Mend.io-hosted app

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitHub, 39.235.2

### Please tell us more about your question or problem

Renovate having support for Pixi is amazing, thanks @trim21 ! However, it currently seems unusable for me, as I need to be able to ignore dependencies based on their Pixi `feature`. I foresee this being a widespread issue for Pixi users.

An example unwanted PR is https://github.com/data-apis/array-api-extra/pull/205. There, we have a feature which deliberately pins a specific NumPy version. We would never want renovate to try to update this dependency:

```toml
 [tool.pixi.feature.numpy1.dependencies] 
 # Oldest NumPy version supported by scikit-learn. 
 numpy = "=1.22.0" 
```

In a _different feature_, we have a NumPy dependency which we would like renovate to update:

```toml
[tool.pixi.feature.lint.dependencies]
numpy = "*"
```

In general, I don't think I want renovate to touch any package with an `=` or `~=` version set.

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
