### DISCUSSION TITLE
RenovateBot fails with 404 error when using GitHub repository rulesets for branch protection

### DISCUSSION THREAD

**Discussion by bertellil-prom** [renovatebot/renovate#35308] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitHub

### Description
When using RenovateBot self-hosted via GitHub Actions with a GitHub App for authentication, the bot fails with a 404 error when attempting to access branch protection information on repositories that use the new repository rulesets feature for branch protection, but works correctly with classic branch protection rules.

### Error Message
```
DEBUG: GET https://api.github.com/repos/<org>/<repo>/branches/<branch>/protection = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=404 retryCount=0, duration=69) (repository=<org>/<repo>, branch=renovate/github.com-<org>-<dep-module>-1.x)
```

### Investigation Results
When branch protection is enabled using repository rulesets, the API response for branch protection shows:
```json
"protected": true,
"protection": {
  "enabled": false,
  "required_status_checks": {
    "enforcement_level": "off",
    "contexts": [],
    "checks": []
  }
},
"protection_url": "https://api.github.com/repos/<org>/<repo>/branches/<branch>/protection"
```

However, when classic branch protection rules are enabled, the API returns a proper response with all protection details:
```json
{
  "url": "https://api.github.com/repos/<org>/<repo>/branches/<branch>/protection",
  "required_pull_request_reviews": {
    "url": "https://api.github.com/repos/<org>/<repo>/branches/<branch>/protection/required_pull_request_reviews",
    "dismiss_stale_reviews": false,
    "require_code_owner_reviews": false,
    "require_last_push_approval": false,
    "required_approving_review_count": 0
  },
  "required_signatures": {
    "url": "https://api.github.com/repos/<org>/<repo>/branches/<branch>/protection/required_signatures",
    "enabled": false
  },
  // ... additional protection details ...
}
```

This suggests that RenovateBot is not yet compatible with GitHub's newer repository ruleset feature for branch protection, and is expecting the classic branch protection API response format.

### Environment
- RenovateBot self-hosted using GitHub Actions
- Authentication via GitHub App
- Repository using GitHub's repository rulesets for branch protection

### GitHub Workflow Configuration
Here's the GitHub Actions workflow configuration I'm using:

```yaml
- name: Get token for Renovate
  id: get-token
  uses: actions/create-github-app-token@v1
  with:
    app-id: ${{ vars.APP_ID }}
    private-key: ${{ secrets.PRIVATE_KEY }}
    owner: ${{ github.repository_owner }}

- name: Get GitHub App User ID
  id: get-user-id
  run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
  env:
    GH_TOKEN: ${{ steps.app-token.outputs.token }}

- name: Configure Git for private modules
  run: |
    # Configure Git to use the token for GitHub URLs
    git config --global url."https://x-access-token:${GITHUB_APP_TOKEN}@github.com/".insteadOf "https://github.com/"
    git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
    git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

- name: Run renovate
  uses: renovatebot/github-action@v41.0.18
  with:
    configurationFile: renovate.json
    token: ${{ steps.get-token.outputs.token }}
  env:
    LOG_LEVEL: debug
    RENOVATE_USERNAME: ${{ steps.app-token.outputs.app-slug }}[bot]
    RENOVATE_GIT_AUTHOR: ${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com
    RENOVATE_PLATFORM: github
    RENOVATE_PLATFORM_COMMIT: "true"
    RENOVATE_DRY_RUN: false
    RENOVATE_AUTODISCOVER: true
    RENOVATE_AUTODISCOVER_FILTER: /<org>/<repo>/
```

### Steps to Reproduce
1. Set up a GitHub repository with repository rulesets for branch protection
2. Configure RenovateBot self-hosted via GitHub Actions using a GitHub App for authentication
3. Run RenovateBot
4. Observe 404 errors when RenovateBot attempts to access branch protection information

### Expected Behavior
RenovateBot should be able to work with repositories that use GitHub's repository rulesets for branch protection, just as it works with repositories using classic branch protection rules.
