### DISCUSSION TITLE
Dependencies between strings

### DISCUSSION THREAD

**Discussion by cstisa** [renovatebot/renovate#35370] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab v17.10, Renovate v39.240.1

### Please tell us more about your question or problem

Hello!

I'm trying to build a Docker image in a [GitLab CI/CD pipeline](https://docs.gitlab.com/ci/pipelines/) based on [gitlab/gitlab-runner-helper](https://hub.docker.com/r/gitlab/gitlab-runner-helper) which has the following tag format: `alpine3.21-x86_64-v17.10.1`

The pipeline basically pulls the public Docker image, makes changes to it and then pushes it to our private registry, but ideally with a different tag (based on the `IMAGE_TAG` variable).

Here is my `.gitlab-ci.yml` file for example:

```
variables:
  # renovate: datasource=docker depName=gitlab/gitlab-runner-helper versioning=regex:^alpine3.(?<build>\d+)-(?<compatibility>x86_64)-v(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$
  GITLAB_RUNNER_HELPER_VERSION: alpine3.19-x86_64-v17.8.5
  IMAGE_SOURCE: "${HARBOR_HOST}/proxy.docker.io/gitlab/gitlab-runner-helper:${GITLAB_RUNNER_HELPER_VERSION}"
  IMAGE_TAG: 17.8.5
```

I'm using the following custom manager (defined in `config.js`) to update the GitLab variables:

```
module.exports = {
  'customManagers': [
    {
      customType: 'regex',
      description: 'Update _VERSION environment variables in GitLab pipeline file',
      fileMatch: ['.*\\.ya?ml$'],
      matchStrings: ["# renovate: datasource=(?<datasource>[a-z-.]+?) depName=(?<depName>[^\\s]+?)(?: (?:packageName)=(?<packageName>[^\\s]+?))?(?: versioning=(?<versioning>[^\\s]+?))?(?: extractVersion=(?<extractVersion>[^\\s]+?))?(?: registryUrl=(?<registryUrl>[^\\s]+?))?\\s+(-\\s)?[A-Za-z0-9_]+?_VERSION\\s*:\\s*[\"']?(?<currentValue>.+?)[\"']?\\s"]
    }
  ],
  [...]
}
```

Renovate successfully parse and update the variable `GITLAB_RUNNER_HELPER_VERSION`, but I would like to update the variable `IMAGE_TAG` accordingly. Is this something I could achieve with Renovate?

Thanks for your help.
