### DISCUSSION TITLE
Pypi replacementVersion not working right?

### DISCUSSION THREAD

**Discussion by sichapman** [renovatebot/renovate#35395] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab

### Please tell us more about your question or problem

I have a basic replacement packageRule:

```yaml
{
      "matchPackageNames": ["safety"],
      "matchDatasources": ["pypi"],
      "replacementName": "pip-audit",
      "replacementVersion": "2.9.0"
}
```

But Renovate fails to create the branch. The debug logs just have a generic error message (see logs section) but I did notice this:

```yaml
"branchesInformation": [
         {
           "branchName": "renovate/safety-replacement",
           "prNo": null,
           "prTitle": "Replace dependency safety with pip-audit",
           "result": "error",
           "upgrades": [
             {
               "datasource": "pypi",
               "depName": "safety",
               "displayPending": "",
               "fixedVersion": "2.3.5",
               "currentVersion": "2.3.5",
               "currentValue": "==2.3.5",
               "newValue": "2.9.0",
               "packageFile": "requirements_test.in",
               "updateType": "replacement",
               "packageName": "safety"
             }
           ]
         },
```

Specifically `"newValue": "2.9.0",` I think should be `"newValue": "==2.9.0",`? If I change `replacementVersion` in the packageRule to have `==` then it does all work as expected, but that feels more of a workaround than how I should be expected to do it?

Using pip-compile manager if that makes a difference

### Logs (if relevant)

<details><summary>Logs</summary>

```

"repoProblems": ["WARN: Error updating branch: update failure"]

```

</details>
