### DISCUSSION TITLE
Updating Github Actions Input?

### DISCUSSION THREAD

**Discussion by Maddin-M** [renovatebot/renovate#35777] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Forgejo, i use the renovate:40 image

### Please tell us more about your question or problem

Hey!
I would like for Renovate to update a parameter for a Github Action, specifically the Setup-Node action:

```
name: Foo
on: push
jobs:
  build:
    steps:
      - name: Setup Node
        uses: https://github.com/actions/setup-node@v4.4.0
        with:
          node-version: "23.7.0"
```

Is it possible for me to setup Renovate in a way to update the `node-version` property if possible?
Thanks!

**Comment by rarkins** [comment]
https://docs.renovatebot.com/modules/manager/github-actions/#withversion-support-for-built-in-actions

It's possibly not working for you as it's expecting `actions/setup-node` and not the full `https://` string. You can:

- Fix/improve this yourself via a PR to this repo, or
- Create a reproduction repo (on github.com) with this syntax and then create a new "Suggest an Idea" Discussion for adding support for this, and we'll convert it into an Issue for someone else to do (one day)

**Reply by viceice** [reply]
the sample is a forgejo action (similar to gitea actions). they can use full urls in actions and you'll see a lot of them in those workflows

- https://code.forgejo.org/forgejo/forgejo/src/commit/a696ad132c837797ee47cc8c2a35c31644a09b7c/.forgejo/workflows/testing.yml#L36
- https://code.forgejo.org/forgejo/forgejo/src/commit/a696ad132c837797ee47cc8c2a35c31644a09b7c/.forgejo/workflows-composite/setup-cache-go/action.yaml#L20

**Reply by Maddin-M** [reply]
What I've done now, is to just create a little custom manager in my renovate.json:
```json
"customManagers": [
  {
    "customType": "regex",
    "fileMatch": ["(^|/)\\.forgejo/workflows/.+\\.ya?ml$"],
    "matchStrings": ["node-version: (?<currentValue>.*) # renovate: (?<datasource>.*?) (?<depName>.*?)\\s"],
    "versioningTemplate": "semver-coerced"
  }
]
```
And use it in my workflow like:
```yaml
- name: Setup Node
  uses: https://github.com/actions/setup-node@v4.4.0
  with:
    node-version: "23.7.0" # renovate: github-tags nodejs/node
```
And because I also have Renovate check node images for Docker, I bundle it into one group:
```json
"packageRules": [
  {
    "matchDatasources": ["docker", "github-tags"],
    "matchPackageNames": ["/node/", "/nodejs\\/node/"],
    "groupName": "node"
  }
]
```
