### DISCUSSION TITLE
Error parsing Cargo.toml file with `version.workspace = true`

### DISCUSSION THREAD

**Discussion by LeoniePhiline** [renovatebot/renovate#35809] [Request Help] [answered]
In Rust cargo workspace projects, it is possible for workspace member crates to inherit the workspace's package version.

See https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table

```toml
# [PROJECT_DIR]/Cargo.toml
[workspace]
members = ["bar"]

[workspace.package]
version = "1.2.3"
```

```toml
# [PROJECT_DIR]/bar/Cargo.toml
[package]
version.workspace = true
```

In renovate, this causes a `ZodError` schema error: "Error parsing Cargo.toml file".

For `package.version` a string is expected, (like "1.2.3") but an object found (`.workspace = true`).

The object is correct, the schema appears to be outdated.

This might be considered a bug?
