### DISCUSSION TITLE
[feature request] Support for `uv` relative path editable dependencies

### DISCUSSION THREAD

**Discussion by kkom** [renovatebot/renovate#35846] [Suggest an Idea]
### How are you running Renovate?

A Mend.io-hosted app

### Please tell us more about your question or problem

`uv` supports editable dependencies specified through a relative path:

* https://docs.astral.sh/uv/concepts/projects/dependencies/#path
* https://docs.astral.sh/uv/concepts/projects/dependencies/#editable-dependencies

But Renovate doesn't update all the uv lockfiles in a monorepo using this feature.

#### More detailed example

In a monorepo, one Python package can depend on another. In the the example below `foo` depends on `shared`:

`foo`

```toml
[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
dependencies = ["shared"]
name = "foo" 
requires-python = ">=3.13"
version = "0.1.0"

[tool.uv.sources]
shared = {editable = true, path = "../shared"}
```

`shared`

```toml
[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
dependencies = [
    "jax==0.5.3",
]
name = "shared"
requires-python = ">=3.13"
version = "0.1.0"
```

When a dependency of `shared` gets updated, Renovate will correctly update the `uv.lock` file of `shared`, but not that of `foo`.

As a result `foo`'s lock file ends up being out-of-date / corrupted.  

Here's a repro PR: https://github.com/kkom/renovate-uv-editable-dependencies/pull/2 – `packages/foo/uv.lock` should get updated, but wasn't.

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
