### DISCUSSION TITLE
Does renovate support mulitple yaml documents in one file?

### DISCUSSION THREAD

**Discussion by another-novelty** [renovatebot/renovate#35888] [Request Help] [answered]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Gitlab  v17.11.1-ee, renovate 40.10.3

### Please tell us more about your question or problem

Gitlab-CI can have a header section, delimited by `---`. Most YAML-parsers treat this as a seperate document.

Since adopting a header for input variables, renovate fails to detect a dependency declared in the second document within the ci-file.

```yaml filename=.gitlab-ci.yml
spec:
  inputs:
    log_level:
      description: "The log level. Possible values are info, warn, error or debug"
      default: "info"
      type: string
      regex: "^(info|warn|error|debug)$"
    repo:
      description: "The repos (comma-separated) to run the Test Renovate on"
      default: "platform-services/devops/ci/renovate/renovate-bot-config"
      type: string
      regex: "^([a-zA-Z0-9_.\\-/]+)(,[a-zA-Z0-9_.\\-/]+)*$"
    dry_run:
      description: "If set to true, the job will not run any changes. It will only show what would be done."
      default: false
      type: boolean
---
include:
  - remote: https://gitlab.com/renovate-bot/renovate-runner/-/raw/v22.0.0/templates/renovate.gitlab-ci.yml

variables:
  ...
  # This image version is not found anymore:
  CI_RENOVATE_IMAGE: https://harbor.example.com/devops/renovate:40.10.6
  ...

Renovate Test:
  extends: renovate
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
  variables:
    LOG_LEVEL: $[[ inputs.log_level ]]
    RENOVATE_REPOSITORIES: $[[ inputs.repo ]]
    RENOVATE_EXTRA_FLAGS: "--autodiscover=false"
    RENOVATE_DRY_RUN: ${if $[[ inputs.dry_run ]], 'full', 'null'}
```

The renovate config:
``` json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:recommended"
  ],
  "automerge": true,
  "automergeType": "pr",
  "schedule": ["* 6 * * *"],
  "packageRules": [
    {
      "matchUpdateTypes": ["major"],
      "automerge": false
    }
  ]
}
```

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>

Link to the minimal repo: https://github.com/akdb-devops/minimal-gitlab-ci-header/tree/main
