### DISCUSSION TITLE
Support updating dependencies without constraints  with uv

### DISCUSSION THREAD

**Discussion by TheSuperiorStanislav** [renovatebot/renovate#35931] [Request Help]
https://github.com/TheSuperiorStanislav/test-renovate

We have a project using uv. Here is an example of pyproject.toml

```toml
[project]
name = "autotests"
version = "0.0.0"
requires-python = ">=3.13"
classifiers = ["Private :: Do Not Upload"]
dependencies = [
    "pomcorn",
]
```

This makes renovate ignore `pomcorn`, and it will not update it at all. The only way to fix it is to set the `>=0` constraint and set `rangeStrategy`  to `bump`. 
Is there a chance renovate can update deps without constraints(just update lock file) or include changelog in `Lock file maintenance`?
