### DISCUSSION TITLE
Docker compose is flapping , or is it intended?

### DISCUSSION THREAD

**Discussion by humpalu** [renovatebot/renovate#36025] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Platform:Bitbucket Version:40

### Please tell us more about your question or problem

Hi,
I setup the Renovate in docker and connected to Bitbucket. I created a docker-compose file 

```
services:
  renovate:
    image: renovate/renovate:40
    container_name: renovate
    environment:
      - TZ=Europe/Vienna
      - RENOVATE_CONFIG_FILE=/config/config.js
      - LOG_LEVEL=debug
    networks:
      - proxy
    volumes:
      - /docker/renovate/data:/data
      - /docker/renovate/config/config.js:/config/config.js
    restart: always
networks:
  proxy:
    name: proxy
    external: true
```

It seems like when the Renovate is finish with the repositories and the dependency check, its just simply go the Exit 0. It cause flapping because the restart is set to always.
If I remove the restart:always, renovate will run once and thats it. How can I make Renovate running without flapping container?
I dont see any suspicious in the Renovate logs. For me it seems like when its done with the scan its just simply goes down

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
