### DISCUSSION TITLE
Alternate (additional) pre-commit files are not identified/included

### DISCUSSION THREAD

**Discussion by ahgraber** [renovatebot/renovate#36036] [Request Help]
### How are you running Renovate?

A Mend.io-hosted app

### Please tell us more about your question or problem

I have copier template that includes a pre-commit-config template in addition to the pre-commit-config at the repository root.  Ideally renovate would keep the versions of the files in sync; however, regardless of how I configure the `managerFilePatterns`, only the root pre-commit-config is detected.

## renovate.json5

```json
{
  $schema: "https://docs.renovatebot.com/renovate-schema.json",
  extends: [
    "config:recommended",
    ":dependencyDashboard",
    ":enablePreCommit",
    ":automergeBranch",
  ],
  dependencyDashboard: true,
  dependencyDashboardTitle: "Renovate Dashboard 🤖",
  schedule: ["before 5am"],
  commitMessageTopic: "{{depName}}",
  commitMessageExtra: "to {{newVersion}}",
  commitMessageSuffix: "",
  packageRules: [
    {
      description: ["Auto merge Github Actions"],
      matchManagers: ["github-actions"],
      automerge: true,
      automergeType: "branch",
      ignoreTests: true,
      matchUpdateTypes: ["minor", "patch"],
    },
    {
      description: ["Auto-merge updates for trusted pre-commit packages"],
      matchDatasources: ["github-tags"],
      automerge: true,
      automergeType: "branch",
      matchUpdateTypes: ["patch"],
      matchPackageNames: [
        "/pre-commit/pre-commit-hooks",
        "/Lucas-C/pre-commit-hooks",
        "/sirosen/texthooks/",
        "/zricethezav/gitleaks/",
        "/stefmolin/exif-stripper",
        "/charliermarsh/ruff-pre-commit/",
        "/igorshubovych/markdownlint-cli/",
        "/adrienverge/yamllint/",
        "/crate-ci/typos/",
      ],
    },
    {
      matchDatasources: ["github-releases", "github-tags"],
      matchUpdateTypes: ["major"],
      commitMessagePrefix: "feat(github-release)!: ",
    },
    {
      matchDatasources: ["github-releases", "github-tags"],
      matchUpdateTypes: ["minor"],
      semanticCommitType: "feat",
      semanticCommitScope: "github-release",
    },
    {
      matchDatasources: ["github-releases", "github-tags"],
      matchUpdateTypes: ["patch"],
      semanticCommitType: "fix",
      semanticCommitScope: "github-release",
    },
    {
      matchManagers: ["github-actions"],
      matchUpdateTypes: ["major"],
      commitMessagePrefix: "feat(github-action)!: ",
    },
    {
      matchManagers: ["github-actions"],
      matchUpdateTypes: ["minor"],
      semanticCommitType: "feat",
      semanticCommitScope: "github-action",
    },
    {
      matchManagers: ["github-actions"],
      matchUpdateTypes: ["patch"],
      semanticCommitType: "fix",
      semanticCommitScope: "github-action",
    },
    {
      matchUpdateTypes: ["major"],
      labels: ["type/major"],
    },
    {
      matchUpdateTypes: ["minor"],
      labels: ["type/minor"],
    },
    {
      matchUpdateTypes: ["patch"],
      labels: ["type/patch"],
    },
    {
      matchDatasources: ["github-releases", "github-tags"],
      addLabels: ["renovate/github-release"],
    },
    {
      matchManagers: ["github-actions"],
      addLabels: ["renovate/github-action"],
    },
  ],
  "pre-commit": {
    commitMessageTopic: "pre-commit hook {{depName}}",
    enabled: true,
    managerFilePatterns: [
      // Renovate will _extend_ the existing managerFilePatterns; the patterns are "additive"
      "(^|/)template/\\.pre-commit-config\\.ya?ml\\.jinja$/i",
    ],
    prBodyNotes: [
      "Note: The `pre-commit` manager in Renovate is not supported by the `pre-commit` maintainers or community.\\\nPlease do not report any problems there, instead [create a Discussion in the Renovate repository](https://github.com/renovatebot/renovate/discussions/new) if you have any questions.",
    ],
  },
}
```

## /.pre-commit-config.yaml

```yaml
---
# renovate: datasource=github-tags depName=pre-commit/pre-commit-hooks
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  (?x)^(
    ^.*(copier-answers\.ya?ml)$
  )$

repos:
  - repo: local
    hooks:
      - id: forbid-yml
        name: Forbid .yml file extensions (use .yaml)
        entry: YAML file extensions must be .yaml
        language: fail
        files: \.yml$
        exclude: |
          (?x)^(
            ^.*(copier-answers\.ya?ml)$
          )$
      - id: forbid-rej
        name: Forbid .rej file extensions from `copier update`
        entry: Forbid .rej file extensions from `copier update`
        language: fail
        files: \.rej$
  # renovate: datasource=github-tags depName=pre-commit/pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-added-large-files
        args: [--maxkb=500000]
        stages: [pre-commit]
      - id: check-case-conflict
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: check-ast
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: mixed-line-ending
        stages: [pre-commit]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        stages: [pre-commit]
  # renovate: datasource=github-tags depName=Lucas-C/pre-commit-hooks
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: "v1.5.5"
    hooks:
      - id: remove-crlf
        stages: [pre-commit]
      # - id: remove-tabs
      #   stages: [pre-commit]
  # renovate: datasource=github-tags depName=sirosen/texthooks
  - repo: https://github.com/sirosen/texthooks
    rev: "0.6.8"
    hooks:
      - id: fix-smartquotes
        stages: [pre-commit]
      - id: fix-ligatures
        stages: [pre-commit]
  # renovate: datasource=github-tags depName=zricethezav/gitleaks
  - repo: https://github.com/zricethezav/gitleaks
    rev: "v8.26.0"
    hooks:
      - id: gitleaks
  # renovate: datasource=github-tags depName=editorconfig-checker/editorconfig-checker.python
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "3.2.1"
    hooks:
      - id: editorconfig-checker
        name: Check editorconfig compliance
        exclude: |
          (?x)^(
            # these file types may have nonstandard indents
            ^(LICENSE)$ |
            ^.*(\.md)$ |
            ^.*(\.rst)$
          )$
        stages: [pre-commit]
  # renovate: datasource=github-tags depName=stefmolin/exif-stripper
  - repo: https://github.com/stefmolin/exif-stripper
    rev: 0.6.2
    hooks:
      - id: strip-exif
        name: Strip exif metadata from images
        stages: [pre-commit]
  # renovate: datasource=github-tags depName=igorshubovych/markdownlint-cli
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "v0.45.0"
    hooks:
      - id: markdownlint
        name: Lint markdown files
        args:
          - --config=.markdownlint.yaml
          - --fix
        stages: [pre-commit]
  # renovate: datasource=github-tags depName=kynan/nbstripout
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        name: Strip metadata and outputs from ipynb files
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: prettier
        name: Format with Prettier
        language: system
        entry: prettier
        args:
          - --write
          - --ignore-unknown
          - --no-error-on-unmatched-pattern
          # - "--ignore-path '**/*.md'"
          # - "--ignore-path '**/*.y*ml'"
        stages: [pre-commit]
  # renovate: datasource=github-tags depName=charliermarsh/ruff-pre-commit
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.11.10"
    hooks:
      - id: ruff
        name: Lint and Format with Ruff
        args: [--fix]
        stages: [pre-commit]
  ### NOTE: ".typos.toml" may be required to have _already been committed_
  ### in order for typos pre-commit hook to read it.
  ### In this case, comment out this block until ".typos.toml" has been committed successfully
  # renovate: datasource=github-tags depName=crate-ci/typos
  - repo: https://github.com/crate-ci/typos
    rev: "v1.32.0"
    hooks:
      - id: typos
        name: Spellcheck with Typos
        args: ["--config", ".typos.toml"]
        exclude: |
          (?x)^(
            # need to include typos configs in templates/ as well
            ^.*(\.typos\.toml).*$ |
            ^.*(\.git.*)$
          )$
        stages: [pre-commit]
  # renovate: datasource=github-tags depName=adrienverge/yamllint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: "v1.37.1"
    hooks:
      - id: yamllint
        name: Lint yaml files
        args: [-c=.yamllint.yaml]
        stages: [pre-commit]
```

## /template/.pre-commit-config.yaml.jinja

```yaml
---
# renovate: datasource=github-tags depName=pre-commit/pre-commit-hooks
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite
  {%- if conventional_commits %}
  - pre-push
  - commit-msg
  {%- endif %}

default_stages:
  - pre-commit

exclude: |
  (?x)^(
    ^.*(copier-answers\.ya?ml)$
    ^.*\.rej$
  )$

repos:
  - repo: local
    hooks:
      - id: forbid-yml
        name: Forbid .yml file extensions (use .yaml)
        entry: YAML file extensions must be .yaml
        language: fail
        files: \.yml$
        exclude: |
          (?x)^(
            ^.*(copier-answers\.ya?ml)$
          )$
      - id: forbid-rej
        name: Forbid .rej file extensions from `copier update`
        entry: Forbid .rej file extensions from `copier update`
        language: fail
        files: \.rej$
  # renovate: datasource=github-tags depName=pre-commit/pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-added-large-files
        args: [--maxkb=500000]
        stages: [pre-commit]
      - id: check-case-conflict
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: check-ast
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: detect-private-key
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: mixed-line-ending
        stages: [pre-commit]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        stages: [pre-commit]
  # renovate: datasource=github-tags depName=Lucas-C/pre-commit-hooks
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: "v1.5.5"
    hooks:
      - id: remove-crlf
        stages: [pre-commit]
      # - id: remove-tabs
      #   stages: [pre-commit]
  # renovate: datasource=github-tags depName=sirosen/texthooks
  - repo: https://github.com/sirosen/texthooks
    rev: "0.6.6"
    hooks:
      - id: fix-smartquotes
        stages: [pre-commit]
      - id: fix-ligatures
        stages: [pre-commit]
  # renovate: datasource=github-tags depName=zricethezav/gitleaks
  - repo: https://github.com/zricethezav/gitleaks
    rev: "v8.18.2"
    hooks:
      - id: gitleaks
  {% if conventional_commits -%}
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.5.1
    hooks:
    - id: commitizen
      {%- if cz_gitmoji %}
      {%- if repository_provider == 'github' %}
      # needed by Renovate to support additional dependencies
      # see https://docs.renovatebot.com/modules/manager/pre-commit/
      language: python
      {%- endif %}
      additional_dependencies:
        - cz-conventional-gitmoji
      {%- endif %}
      stages:
      - commit-msg
  {%- endif %}{%- if editorconfig %}
  # renovate: datasource=github-tags depName=editorconfig-checker/editorconfig-checker.python
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.7.3"
    hooks:
      - id: editorconfig-checker
        name: Check editorconfig compliance
        exclude: |
          (?x)^(
            # these file types may have nonstandard indents
            ^(LICENSE)$ |
            ^.*(\.md)$ |
            ^.*(\.rst)$
          )$
        stages: [pre-commit]
  {%- endif %}{% if exif-stripper %}
  # renovate: datasource=github-tags depName=stefmolin/exif-stripper
  - repo: https://github.com/stefmolin/exif-stripper
    rev: 0.5.0
    hooks:
      - id: strip-exif
        name: Strip exif metadata from images
        stages: [pre-commit]
  {%- endif %}{% if docker %}
  - repo: local
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        language: system
        entry: hadolint
        types: ["dockerfile"]
        stages: [pre-commit]
  {%- endif %}{% if markdown %}
  # renovate: datasource=github-tags depName=igorshubovych/markdownlint-cli
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "v0.40.0"
    hooks:
      - id: markdownlint
        name: Lint markdown files
        args:
          - --config=.markdownlint.yaml
          - --fix
        stages: [pre-commit]
  {%- endif %}{% if jupyter %}
  # renovate: datasource=github-tags depName=kynan/nbstripout
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.0
    hooks:
      - id: nbstripout
        name: Strip metadata and outputs from ipynb files
        stages: [pre-commit]
  {%- endif %}{% if biome %}
  # renovate: datasource=github-tags depName=biomejs/pre-commit
  - repo: https://github.com/biomejs/pre-commit
    rev: v0.6.1
    hooks:
      - id: biome-check
        name: Lint with Biome
        args: [--fix]
        stages: [pre-commit]
  {%- endif %}{% if prettier %}
  - repo: local
    hooks:
      - id: prettier
        name: Format with Prettier
        language: system
        entry: prettier
        args:
          - --write
          - --ignore-unknown
          - --no-error-on-unmatched-pattern
          # - "--ignore-path '**/*.md'"
          # - "--ignore-path '**/*.y*ml'"
        stages: [pre-commit]
  {%- endif %}{% if python %}
  # renovate: datasource=github-tags depName=charliermarsh/ruff-pre-commit
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.4.4"
    hooks:
      - id: ruff
        name: Lint and Format with Ruff
        args: [--fix]
        stages: [pre-commit]
  {%- endif %}{% if shell %}
  - repo: local
    hooks:
      - id: shellcheck
        name: Lint shell scripts
        language: system
        entry: shellcheck
        types: ["shell"]
        exclude: "^.*zsh$" # ignore '*.zsh" scripts'
        stages: [pre-commit]
  # renovate: datasource=github-tags depName=scop/pre-commit-shfmt
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: "v3.8.0-1"
    hooks:
      - id: shfmt
        name: Format shell scripts
        args:
          - -i
          - "2"
          - -ci
          - -bn
        stages: [pre-commit]
  {%- endif %}{% if typos %}
  ### NOTE: ".typos.toml" may be required to have _already been committed_
  ### in order for typos pre-commit hook to read it.
  ### In this case, comment out this block until ".typos.toml" has been committed successfully
  # renovate: datasource=github-tags depName=crate-ci/typos
  - repo: https://github.com/crate-ci/typos
    rev: "v1.22.2"
    hooks:
      - id: typos
        name: Spellcheck with Typos
        args: ["--config", ".typos.toml"]
        exclude: |
          (?x)^(
            ^.*(\.typos\.toml)$ |
            ^.*(\.git.*)$
          )$
        stages: [pre-commit]
  {%- endif %}{% if yaml %}
  # renovate: datasource=github-tags depName=adrienverge/yamllint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: "v1.35.1"
    hooks:
      - id: yamllint
        name: Lint yaml files
        args: [-c=.yamllint.yaml]
        stages: [pre-commit]
  {%- endif %}
```

### Logs (if relevant)

<details><summary>Logs</summary>

```
DEBUG: Existing config file confirmed
DEBUG: Repository config
{
...
    "pre-commit": {
      "commitMessageTopic": "pre-commit hook {{depName}}",
      "enabled": true,
      "managerFilePatterns": [
        "(^|/)template/\\.pre-commit-config\\.ya?ml\\.jinja$/i"
      ],
      "prBodyNotes": [
        "Note: The `pre-commit` manager in Renovate is not supported by the `pre-commit` maintainers or community.\\\nPlease do not report any problems there, instead [create a Discussion in the Renovate repository](https://github.com/renovatebot/renovate/discussions/new) if you have any questions."
      ]
    }
...
}
...
INFO: Dependency extraction complete
{
  "baseBranch": "main"
  "stats": {
    "managers": {
      "github-actions": {
        "fileCount": 3,
        "depCount": 10
      },
      "pip_requirements": {
        "fileCount": 1,
        "depCount": 4
      },
      "pre-commit": {
        "fileCount": 1,
        "depCount": 11
      }
    },
    "total": {
      "fileCount": 5,
      "depCount": 25
    }
  }
}
...
"pre-commit": [
      {
        "deps": [
          {
            "currentValue": "v5.0.0",
            "currentVersion": "v5.0.0",
            "currentVersionAgeInDays": 226,
            "currentVersionTimestamp": "2024-10-05T18:42:33.000Z",
            "datasource": "github-tags",
            "depName": "pre-commit/pre-commit-hooks",
            "depType": "repository",
            "fixedVersion": "v5.0.0",
            "packageName": "pre-commit/pre-commit-hooks",
            "registryUrl": "https://github.com",
            "sourceUrl": "https://github.com/pre-commit/pre-commit-hooks",
            "versioning": "semver-coerced",
            "warnings": [],
            "updates": []
          },
          {
            "currentValue": "v1.5.5",
            "currentVersion": "v1.5.5",
            "currentVersionAgeInDays": 461,
            "currentVersionTimestamp": "2024-02-13T21:21:27.000Z",
            "datasource": "github-tags",
            "depName": "Lucas-C/pre-commit-hooks",
            "depType": "repository",
            "fixedVersion": "v1.5.5",
            "packageName": "Lucas-C/pre-commit-hooks",
            "registryUrl": "https://github.com",
            "sourceUrl": "https://github.com/Lucas-C/pre-commit-hooks",
            "versioning": "semver-coerced",
            "warnings": [],
            "updates": []
          },
          {
            "currentValue": "0.6.8",
            "currentVersion": "0.6.8",
            "currentVersionAgeInDays": 168,
            "currentVersionTimestamp": "2024-12-02T19:17:18.000Z",
            "datasource": "github-tags",
            "depName": "sirosen/texthooks",
            "depType": "repository",
            "fixedVersion": "0.6.8",
            "packageName": "sirosen/texthooks",
            "registryUrl": "https://github.com",
            "sourceUrl": "https://github.com/sirosen/texthooks",
            "versioning": "semver-coerced",
            "warnings": [],
            "updates": []
          },
          {
            "currentValue": "v8.26.0",
            "currentVersion": "v8.26.0",
            "currentVersionAgeInDays": 7,
            "currentVersionTimestamp": "2025-05-12T20:58:42.000Z",
            "datasource": "github-tags",
            "depName": "zricethezav/gitleaks",
            "depType": "repository",
            "fixedVersion": "v8.26.0",
            "packageName": "zricethezav/gitleaks",
            "registryUrl": "https://github.com",
            "sourceUrl": "https://github.com/zricethezav/gitleaks",
            "versioning": "semver-coerced",
            "warnings": [],
            "updates": []
          },
          {
            "currentValue": "3.2.1",
            "currentVersion": "3.2.1",
            "currentVersionAgeInDays": 50,
            "currentVersionTimestamp": "2025-03-30T15:57:25.000Z",
            "datasource": "github-tags",
            "depName": "editorconfig-checker/editorconfig-checker.python",
            "depType": "repository",
            "fixedVersion": "3.2.1",
            "packageName": "editorconfig-checker/editorconfig-checker.python",
            "registryUrl": "https://github.com",
            "sourceUrl": "https://github.com/editorconfig-checker/editorconfig-checker.python",
            "versioning": "semver-coerced",
            "warnings": [],
            "updates": []
          },
          {
            "currentValue": "0.6.2",
            "currentVersion": "0.6.2",
            "currentVersionAgeInDays": 91,
            "currentVersionTimestamp": "2025-02-17T22:26:33.000Z",
            "datasource": "github-tags",
            "depName": "stefmolin/exif-stripper",
            "depType": "repository",
            "fixedVersion": "0.6.2",
            "packageName": "stefmolin/exif-stripper",
            "registryUrl": "https://github.com",
            "sourceUrl": "https://github.com/stefmolin/exif-stripper",
            "versioning": "semver-coerced",
            "warnings": [],
            "updates": []
          },
          {
            "currentValue": "v0.45.0",
            "currentVersion": "v0.45.0",
            "currentVersionAgeInDays": 2,
            "currentVersionTimestamp": "2025-05-18T01:03:29.000Z",
            "datasource": "github-tags",
            "depName": "igorshubovych/markdownlint-cli",
            "depType": "repository",
            "fixedVersion": "v0.45.0",
            "packageName": "igorshubovych/markdownlint-cli",
            "registryUrl": "https://github.com",
            "sourceUrl": "https://github.com/igorshubovych/markdownlint-cli",
            "versioning": "semver-coerced",
            "warnings": [],
            "updates": []
          },
          {
            "currentValue": "0.8.1",
            "currentVersion": "0.8.1",
            "currentVersionAgeInDays": 183,
            "currentVersionTimestamp": "2024-11-17T10:28:20.000Z",
            "datasource": "github-tags",
            "depName": "kynan/nbstripout",
            "depType": "repository",
            "fixedVersion": "0.8.1",
            "packageName": "kynan/nbstripout",
            "registryUrl": "https://github.com",
            "sourceUrl": "https://github.com/kynan/nbstripout",
            "versioning": "semver-coerced",
            "warnings": [],
            "updates": []
          },
          {
            "currentValue": "v0.11.10",
            "currentVersion": "v0.11.10",
            "currentVersionAgeInDays": 4,
            "currentVersionTimestamp": "2025-05-15T14:15:07.000Z",
            "datasource": "github-tags",
            "depName": "charliermarsh/ruff-pre-commit",
            "depType": "repository",
            "fixedVersion": "v0.11.10",
            "packageName": "charliermarsh/ruff-pre-commit",
            "registryUrl": "https://github.com",
            "sourceUrl": "https://github.com/charliermarsh/ruff-pre-commit",
            "versioning": "semver-coerced",
            "warnings": [],
            "updates": []
          },
          {
            "currentValue": "v1.32.0",
            "currentVersion": "v1.32.0",
            "currentVersionAgeInDays": 17,
            "currentVersionTimestamp": "2025-05-02T14:48:24.000Z",
            "datasource": "github-tags",
            "depName": "crate-ci/typos",
            "depType": "repository",
            "fixedVersion": "v1.32.0",
            "packageName": "crate-ci/typos",
            "registryUrl": "https://github.com",
            "sourceUrl": "https://github.com/crate-ci/typos",
            "versioning": "semver-coerced",
            "warnings": [],
            "updates": []
          },
          {
            "currentValue": "v1.37.1",
            "currentVersion": "v1.37.1",
            "currentVersionAgeInDays": 15,
            "currentVersionTimestamp": "2025-05-04T08:24:35.000Z",
            "datasource": "github-tags",
            "depName": "adrienverge/yamllint",
            "depType": "repository",
            "fixedVersion": "v1.37.1",
            "packageName": "adrienverge/yamllint",
            "registryUrl": "https://github.com",
            "sourceUrl": "https://github.com/adrienverge/yamllint",
            "versioning": "semver-coerced",
            "warnings": [],
            "updates": []
          }
        ],
        "packageFile": ".pre-commit-config.yaml"
      }
    ]
  }
}
```

</details>
