### DISCUSSION TITLE
Monorepo of GitHub Actions workflows

### DISCUSSION THREAD

**Discussion by marians** [renovatebot/renovate#36283] [Request Help]
### How are you running Renovate?

None

### Please tell us more about your question or problem

We want to use Renovate to keep called GitHub workflows in a number of repositories up-to-date. Our reusable workflows all reside in a repository named `github-workflows`. We use commit SHAs for referencing, like this:

```yaml
jobs:
  publish:
    uses: myorg/github-workflows/.github/workflows/create-release-pr.yaml@6bacf73d582b8088d41b8eaec469c40c14398081
```

The problem: whenever something changed in the repository, Renovate updates the SHA in **all** workflow references, even if nothing has changed on the specific workflow (in this example: `create-release-pr.yaml`). We would prefer update PRs only in case the workflow in question changed.

Is it possible to configure Renovate that way?
