### DISCUSSION TITLE
Helmfile extract with templated repository url

### DISCUSSION THREAD

**Discussion by DANIILSKRIPCHENKO** [renovatebot/renovate#36306] [Request Help]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Self-managed GitLab. Using latest renovate version (40.40.3)

### Please tell us more about your question or problem

Content of helmfile.yml:

``` yaml
bases:
  - environments.yaml

---
repositories:
  - name: private
    url: {{ requiredEnv "HELM_CHARTS_REGISTRY_URL" }}
    oci: true

releases:
  - name: foo-release
    namespace: foo-namespace
    chart: private/foo-app
    version: 8.0.19
```

When running renovate, I get following in logs:
```
"config": {
  "helmfile": [
    {
      "deps": [
        {
          "depName": "foo-app",
          "currentValue": "8.0.19",
          "registryUrls": [],
          "skipReason": "unknown-registry",
          "updates": [],
          "packageName": "foo-app"
        }
      ],
      "datasource": "helm",
      "packageFile": "helmfile/helmfile.yaml"
    }
  ]
}
```

How can i fix it? Is it possible to pass repository url using ENV variable? Maybe some workarounds?

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
