### DISCUSSION TITLE
Suggest adding https://github.com/step-security/harden-runner to GitHub Actions workflow

### DISCUSSION THREAD

**Discussion by vlsi** [renovatebot/renovate#36706] [Suggest an Idea]
### Tell us more.

https://github.com/step-security/harden-runner enables increasing the security of the builds, and I guess it might be great if Renovate could automatically suggest adding the base configuration.

See https://github.com/step-security/harden-runner?tab=readme-ov-file#step-1-add-harden-runner-to-your-workflow

```yaml
steps:
  - name: Harden Runner
    uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
    with:
      egress-policy: audit
```
