### DISCUSSION TITLE
how to configure with kubernetes

### DISCUSSION THREAD

**Discussion by dharmendrakariya** [renovatebot/renovate#8043] [Request Help] [answered]
Hi, 

I am confused with the envs to set 

I am using secret.yaml and cronjob.yaml for my kubernetes.

I have set cronjob.yaml as below

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              # Update this to the latest available and then enable Renovate on
              # the manifest
              image: renovate/renovate
              args:
                - dharmendrakariya/PubQuiz
              # Environment Variables
              envFrom:
                - secretRef:
                    name: renovate-env
          restartPolicy: Never
```  
 and secret.yaml as this

```
apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
type: Opaque
stringData:
  #GITHUB_COM_TOKEN: 'any-personal-user-token-for-github-com-for-fetching-changelogs'
  # set to true to run on all repos you have push access to
  RENOVATE_AUTODISCOVER: 'false'
  RENOVATE_ENDPOINT: 'https://github.com/dharmendrakariya/PubQuiz'
  RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'
  RENOVATE_PLATFORM: 'github'
  RENOVATE_TOKEN: '4603b55d2583f14***014b9560f9b0a560691e9' 
```
as RENOVATE_TOKEN i set my github personal access token, 
what should be at RENOVATE_ENDPOINT and RENOVATE_GIT_AUTHOR ?

also I am commenting out the GITHUB_COM_TOKEN because I am using github platform, is that right?

and also what should be there if I am using the different platform. sorry but I didnt get the clear from docs.
