### DISCUSSION TITLE
Python sidecar container cannot access Pipfile

### DISCUSSION THREAD

**Discussion by hisener** [renovatebot/renovate#8169] [Request Help] [answered]
After I hit the limitation in https://github.com/renovatebot/renovate/issues/8163, I started using the slim image docker as the binary source. For some reason, the sidecar cannot access `Pipfile` and I couldn't figure out why.

##### Main Renovate container
```
$ id
uid=1000(ubuntu) gid=1000(ubuntu) groups=1000(ubuntu)
```

##### `config.js`
```
...
  "dockerUser": "1000:1000"
...
```

```
File name: python-test/Pipfile.lock
Command failed: docker run --rm --name=renovate_python --label=renovate_child --user=1000:1000 -v "/tmp/renovate/repos/github/PicnicSupermarket/picnic-scratch":"/tmp/renovate/repos/github/PicnicSupermarket/picnic-scratch" -v "/tmp/renovate/cache":"/tmp/renovate/cache" -v "/tmp/renovate/cache/others/pipenv":"/tmp/renovate/cache/others/pipenv" -e PIPENV_CACHE_DIR -w "/tmp/renovate/repos/github/PicnicSupermarket/picnic-scratch/python-test" docker.io/renovate/python:3.8.6 bash -l -c "pip install --user pipenv && pipenv lock"
Creating a virtualenv for this project...
Pipfile: /tmp/renovate/repos/github/PicnicSupermarket/picnic-scratch/python-test/Pipfile
Using /usr/local/python/3.8.6/bin/python3 (3.8.6) to create virtualenv...

⠋ Creating virtual environment...�
⠙ Creating virtual environment...�
⠏ Creating virtual environment...created virtual environment CPython3.8.6.final.0-64 in 632ms
  creator CPython3Posix(dest=/home/ubuntu/.local/share/virtualenvs/python-test-zKYyy-c-, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/ubuntu/.local/share/virtualenv)
    added seed packages: pip==20.3.1, setuptools==51.0.0, wheel==0.36.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

�✔ Successfully created virtual environment! 
Virtualenv location: /home/ubuntu/.local/share/virtualenvs/python-test-zKYyy-c-
Creating a Pipfile for this project...
Traceback (most recent call last):
...
PermissionError: [Errno 13] Permission denied: '/tmp/renovate/repos/github/PicnicSupermarket/picnic-scratch/python-test/Pipfile'
```

Currently, I have the following setup (removed unrelated parts):

```
      container:
        image: renovate/renovate:24.11.2-slim
        command:
          - /bin/bash
          - -c
        args:
          - id && renovate
        env:
          - name: DOCKER_HOST
            value: 127.0.0.1
        securityContext:
          runAsNonRoot: true
          runAsGroup: 1000
          fsGroup: 1000
      sidecars:
        - name: renovate-dind
          image: docker:19.03.14-dind
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          securityContext:
            privileged: true
```

**Comment by rarkins** [comment, marked as answer]
1. Don't configure `dockerUser` unless you need to
2. Have you mapped `/tmp/renovate` on your **host** to `/tmp/renovate` in your main Renovate container? It needs to be on the host so that it can be mapped to the sibling containers

**Reply by hisener** [reply]
Thanks for the answer.

1. Ack
2. Nope, will try. Does it mean that I can drop `securityContext` configuration from the main Renovate container?

**Reply by hisener** [reply]
Added the following and still the same error 🤔 
```
  container:
    image: renovate/renovate:24.11.2-slim
...
    volumeMounts:
      - name: tmp-renovate
        mountPath: /tmp/renovate
  volumes:
    - name: tmp-renovate
      emptyDir: {}
```

**Reply by viceice** [reply]
You need to mount `/tmp/renovate` to renovate and docker dind container

**Reply by hisener** [reply]
It's already mounted to both.
```
  main:
    Image:         renovate/renovate:24.11.2-slim
    Mounts:
      /tmp/renovate from tmp-renovate (rw)
  renovate-dind:
    Image:          docker:19.03.14-dind
    Mounts:
      /tmp/renovate from tmp-renovate (rw)
Volumes:
  tmp-renovate:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
```

**Reply by hisener** [reply]
The minimal pod that I can reproduce the issue I am having: 🤔 
```
apiVersion: v1
kind: Pod
metadata:
  name: dind-test-halil
  namespace: renovate
spec:
  containers:
    - name: main
      image: renovate/renovate:24.11.2-slim
      command:
        - /bin/bash
        - -c
        - >-
          id &&
          echo 'test' > /tmp/renovate/test-file &&
          ls -al /tmp/renovate/ &&
          sleep 10 &&
          docker run --rm -v /tmp/renovate:/tmp/renovate renovate/python:3.8.6 /bin/bash -c 'ls -al /tmp/renovate/ && cat /tmp/renovate/test-file'
      env:
        - name: DOCKER_HOST
          value: 127.0.0.1
      volumeMounts:
        - name: tmp-renovate
          mountPath: /tmp/renovate
    - name: renovate-dind
      image: docker:19.03.14-dind
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      securityContext:
        privileged: true
      volumeMounts:
        - name: tmp-renovate
          mountPath: /tmp/renovate
  volumes:
    - name: tmp-renovate
      emptyDir: {}
```

The logs:
```
uid=1000(ubuntu) gid=0(root) groups=0(root),999(docker),1000(ubuntu)
total 4
drwxrwxrwx 2 root   root 23 Dec 31 12:59 .
drwxrwxrwt 1 root   root 22 Dec 31 12:59 ..
-rw-r--r-- 1 ubuntu root  5 Dec 31 12:59 test-file
Unable to find image 'renovate/python:3.8.6' locally
3.8.6: Pulling from renovate/python
...
Status: Downloaded newer image for renovate/python:3.8.6
total 0
drwxr-xr-x 2 root root 40 Dec 31 12:59 .
drwxrwxrwt 1 root root 22 Dec 31 12:59 ..
cat: /tmp/renovate/test-file: No such file or directory
```

**Reply by viceice** [reply]
Can you try to mount only `/tmp`, so renovate can create the `/tmp/renovate` folder?

**Reply by hisener** [reply]
It worked. 🎉  Thank you!

For future readers, the relevant parts:

```yaml
containers:
  - name: renovate
    image: renovate/renovate:24.11.2-slim
    env:
      - name: DOCKER_HOST
        value: 127.0.0.1
    volumeMounts:
      - name: renovate-tmp-volume
        mountPath: /tmp
  - name: renovate-dind
    image: docker:19.03.14-dind
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    securityContext:
      privileged: true
    volumeMounts:
    - name: renovate-tmp-volume
      mountPath: /tmp
volumes:
  - name: renovate-tmp-volume
    emptyDir: {}
```
