### DISCUSSION TITLE
Update multiple versions based on a global stack version definition

### DISCUSSION THREAD

**Discussion by andreabettich** [renovatebot/renovate#8204] [Request Help] [answered]
Hi there.
I am trying to have a central place where I can define which library, image etc. version are for a specific stack version .
So that way we can create a new version of the stack definition and let renovate make PR on all the repos to update the stack libraries, images etc. 
I hope this was sort of understandable. If not I can describe it in a further comment a little more.
Is there a solution for this? If not I'm also willing to build it and create a PR but I would need someone to lead me into the right direction and maybe explain me some parts of the application.

**Comment by viceice** [comment]
Please explain this more derailed. 

- What type of files should updated? 
- Where to lookup the new versions?
- Which language / environment is this?
- What is a stack in that context?

**Reply by viceice** [reply]
Some pseudo code for your sample or a public sample repo would help too

**Comment by andreabettich** [comment]
Thanks for the fast reply.
I'll try to give you more insight on the whole idea.

> What type of files should updated?

The already supported files/managers like pom.xml, dockerfile, gitlab-ci.yaml etc. and maybe an extra file where the stack version is defined.


> Where to lookup the new versions?

The current idea was, that we have a git repository which has git tags of the different stack versions and there you have a definition which version of which type of dependency you have.
The file could look like something like this. 

version 1.0.0 of a stack
```
components:
  maven:
    - name: spring-boot-starter-parent
      package: org.springframework.boot
      version: 2.4.0
    - name: foo-bar-security-library
      package: ch.foo.bar
      version: 1.0.0
  docker:
    - name: openjdk
      version: 11-jre
  helm-requirements:
    - name: redis
      version: 6.0.0
```
In the consumer repository there would be a file which could look as simple as this:
```
stack:
  version: 1.0.0
  repository: foo/bar/backend-stack-version
```
And if we have a update on the `foo-bar-security-library` or on any other component, we can create a new stack version 1.0.1, update the library version and let renovate make a PR on all repos that there is a new stack version.
I think the tricky part is, that we have to update the stack version and then also lookup the new file and update the different files (pom, helm etc)


> Which language / environment is this?

Don't know what you mean with this question.
We have a self-hostet instance (bot) on gitlab.


> What is a stack in that context?

A stack in our context is just a compilation of compatible components. Like a parent pom in maven where the versions are defined just in our case we want to define it more globally over multiple technologies (maven, docker, helm).

I hope this give you a little more infos about the functionality we are looking for.
