### DISCUSSION TITLE
How to use env variables within config.json

### DISCUSSION THREAD

**Discussion by mhubig** [renovatebot/renovate#8393] [Request Help] [answered]
Hi there, I'm new to renovate and I'm wondering if there is a best practice / recommended way to use secrets exposed as environment variables within the renovate `config.json` file.

I'm using renovate as a k8s cronjob an so I usually expose secrets to the cronjob pod like so:

```yaml
env:
- name: ARTIFACTORY_PASSWORD
  valueFrom:
    secretKeyRef:
      name: renovate-secrets
      key: ARTIFACTORY_PASSWORD
```

Now I like to inject those variables into my `config.json` file, maybe like so:

```json
{
  "dryRun": true,
  "logLevel": "debug",
  "platform": "gitlab",
  "token": "${GITLAB_TOKEN}",
  "endpoint": "https://my.gitlab.com/api/v4",
  "gitAuthor": "Renovate Bot <bot@my.gitlab.com>",
  "autodiscover": true,
  "autodiscoverFilter": "apps/**",
  "npmrc": "@dm:registry=my.artifactory.com/api/npm/repo-my\n//my.artifactory.com/api/npm/:_authToken=${NPM_TOKEN}",
  "hostRules": [
    {
      "platform": "maven",
      "endpoint": "https://my.artifactory.com",
      "username": "${ARTIFACTORY_USERNAME}",
      "password": "${ARTIFACTORY_PASSWORD}"
    }
  ]
}
```

Is there any way of doing this?
