### DISCUSSION TITLE
cp permission denied after 24.38 build

### DISCUSSION THREAD

**Discussion by igorP3** [renovatebot/renovate#8572] [Request Help]
Need some help.
When using a version newer than 24.38 I get permission denied in Gitlab CI on ```cp ./config.js /usr/src/app/config.js```

Build log:
```
Pulling docker image renovate/renovate ...
Using docker image sha256:7c7b91aa6091b64438e46d7d53d862d8f060aa1b8c062ef5897c8d55dc494fc1 for renovate/renovate with digest renovate/renovate@sha256:0440882b16eb3e2a0678e558c558c93c0277aca8d11d8b6d90dbb001f3ddefb0 ...
Preparing environment

Skipping Git submodules setup
Executing "step_script" stage of the job script
00:01
$ cp ./config.js /usr/src/app/config.js
cp: cannot create regular file '/usr/src/app/config.js': Permission denied
```

This is my gitlab config
```
image: renovate/renovate:latest

services:
  - docker:20.10.1-dind

renovate-dryrun:
  before_script:
    - cp ./config.js /usr/src/app/config.js
    - echo "$NPMRC" > .npmrc
  script:
    - renovate --dry-run $RENOVATE_EXTRA_FLAGS
  except:
    - schedules
  allow_failure: true
```

Was working like a charm with 24.38 builds.
What changed?
