### DISCUSSION TITLE
Artifact Update Problem

### DISCUSSION THREAD

**Discussion by loganknecht** [renovatebot/renovate#8778] [Request Help]
Hello!

My organization has a bit of a problem with our `renovate` integration and I'm not sure where to start debugging for it.

We currently have a `renovate-runner` set up with a default configuration like this

```javascript
module.exports = {
  // Auto discover
  autodiscover: true,

  // Do not onboard
  onboarding: false,

  // Require config in repo
  requireConfig: true
};
```

And then in our downstream projects using `renovate` we use a simple configuration to extend this
```javascript
{
    "extends": ["config:base"],
    "labels": ["Dependencies"]
}
```

And this works wonderfully! We seem to have no issues running in general.

However we are seeing messages pop up saying
![image](https://user-images.githubusercontent.com/1308524/108565170-1adadf80-72b9-11eb-9cca-2aea3bde5a2c.png)

Is there anyone who can provide guidance on this?

It states

```
docker: read tcp 127.0.0.1:60718->127.0.0.1:2376: read: connection reset by peer.
See 'docker run --help'.
```
and
```
docker: read tcp 127.0.0.1:60730->127.0.0.1:2376: read: connection reset by peer.
See 'docker run --help'.
```

And I'm unsure where the `connection` issue in `docker` is happening?
Where should I be looking to debug this?

**Comment by viceice** [comment]
Please provide some more details how you run renovate

**Comment by loganknecht** [comment]
We have a separate repo configured in `GitLab` that uses a `.gitlab-ci.yml` file that is scheduled to execute the `renovate` job. It points to a project, `/templates/renovate-dind.gitlab-ci.yml` that was forked and duplicated from the template provided in `GitLab` here.
https://gitlab.com/renovate-bot/renovate-runner

Its configuration file is here
```yaml
include: '/templates/_common.gitlab-ci.yml'

image: renovate/renovate:24.17.2-slim

services:
  - docker:20.10.1-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
```

The job for CI/CD configuration is configured as such

```yaml
include:
  - project: "infra/gitlab/renovate-runner"
    file: "/templates/renovate-dind.gitlab-ci.yml"

variables:
  # Force docker to use TLS
  DOCKER_HOST: "tcp://docker:2376"
  DOCKER_TLS_CERTDIR: "${DOCKER_TLS_CERTDIR}"
  # Renovate
  RENOVATE_REQUIRE_CONFIG: "true"
  RENOVATE_ONBOARDING: "false"
  LOG_LEVEL: "info"

renovate:
  secrets:
    GITHUB_COM_TOKEN:
      vault: infra/gitlab/renovate-ci/github.com/token@ci
  before_script:
    # Expose secrets directly as vars
    - export GITHUB_COM_TOKEN=$(cat "${GITHUB_COM_TOKEN}")
  only:
    - schedules
    # Manual web triggers
    - web
```
