### DISCUSSION TITLE
Incremental update supported?

### DISCUSSION THREAD

**Discussion by kamatama41** [renovatebot/renovate#8930] [Request Help] [answered]
Hi, I'm maintaining some Go libraries and they support multiple Go versions, so that multiple Go versions are written in CI yaml (for GitHub Actions) like following.

```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.14
          - 1.15
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
```

When Go 1.16 is released, I would like to update `go-version` incrementally like this. Is it possible on  Renovate (for GitHub Apps)?

 ```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.15
          - 1.16
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
```
