### DISCUSSION TITLE
Repository limit and concurrency

### DISCUSSION THREAD

**Discussion by emirot** [renovatebot/renovate#8949] [Request Help] [answered]
Hey there,

Let's say I'm on a private gitlab with more than 4000 repositories, it looks like it will take a long time to run renovatebot on every repo. I've just tried on 4 repos it took 5min with a runner with a decent runner more than 4Gb and 1 core.
Is there a way to use some concurrency ?
I was wondering if we could break up the repo list into multiple sublists and have different schedules take care of that.

**Comment by rarkins** [comment, marked as answer]
You could run several in parallel and use non overlapping autodiscoverFilter configs on each.

**Reply by emirot** [reply]
So what you propose @rarkins  is having one stage like so:
```yaml
stages:
  - Renovate

renovate:
  image:
    name: renovate/renovate
    entrypoint: [""]
  stage: Renovate
  tags:
    - high-memory
  variables:
    RENOVATE_CONFIG_FILE: ./config.js
    RENOVATE_TOKEN: $RENOVATE_BOT_API_TOKEN
  script:
    - echo "Using Config :"
    - cat $RENOVATE_CONFIG_FILE
    - ls -la
    - renovate
```
And then get the list of all repos from that create N schedule jobs that point to N config files (containing the non overlapping repos) programmatically  passing the name of the config as an ENV variable ? With the right tuning to make it run fast enough without affecting gitlab performances in non business days.
Is there another  solution?

I'm curious to know what large organizations have done ?
