### DISCUSSION TITLE
Replacement with Docker version but not full value

### DISCUSSION THREAD

**Discussion by Boojapho** [renovatebot/renovate#9207] [Request Help] [answered]
Does Renovate have the ability to match and replace just the Docker version and not the entire value?

In the example below, the docker tags on `quay.io/strimzi/kafka` are `<strimzi version>-kafka-<kafka version>`.  For example, `0.22.0-kafka-2.7.0`.  When replacing the full tag, everything works great.  Renovate will match the capability `kafka-2.7.0` and upgrade only the tag.  But, I also have an environmental variable named `STRIMZI_VERSION` that gets set to `0.22.0`.  This does not match anything currently.  What I'd like is to be able to use the `STRIMZI_VERSION` and `KAFKA_VERSION` lines below to match the tag up and then replace the `STRIMZI_VERSION` with the updated value.  I played around with templating a little, but could not figure it out.  Any suggestions?

Here is an example `renovate.json`, but I want to change the match string to replace with `currentVersion` rather than `currentValue`:
```json
{
    "regexManagers": [
      {
        "fileMatch": [
          "^hardening_manifest.yaml$"
        ],
        "matchStrings": [
          "strimzi_version:\\s+\"(?<currentValue>.+?)\""
        ],
        "depNameTemplate": "quay.io/strimzi/kafka",
        "datasourceTemplate": "docker",
        "versioningTemplate": "docker"
      }
    ]
}
```

And the `hardening_manifest.yaml`
```yaml
# Build args passed to Dockerfile ARGs
args:
  strimzi_version: "0.22.0"
  KAFKA_VERSION: "2.7.0"
  KAFKA_EXPORTER_VERSION: "1.2.0"

# List of resources to make available to the offline build context
resources:
- tag: strimzi/kafka:latest
  url: docker://quay.io/strimzi/kafka@sha256:a2eb8ed7daac114843de5fc1b8d80e5c655f1de93d5cd7f1d061c7e68e571eae

```
