### DISCUSSION TITLE
Create custom group with matching packageName

### DISCUSSION THREAD

**Discussion by jeff-cook** [renovatebot/renovate#9371] [Request Help] [answered]
I want to create a group where the `packageName` matches and updates from the same version to the same version.
The file being updated is the same however, the manager is different.

When the package `my_tools/gitleaks` gets updated to `v1.3.12` I currently get 2 merge requests.

I want them to be bundled in the same update/commit.

`.gitlab-ci.yml`
```yaml
include:
  - project: my_tools/gitleaks
    ref: v1.3.11
    file: /gitleaks/.gitlab-ci.yml

.gitleaks:
  image:
    name: registry.gitlab.com/my_tools/gitleaks:v1.3.11
```
