### DISCUSSION TITLE
regexManagers matchingStrings question

### DISCUSSION THREAD

**Discussion by biergit** [renovatebot/renovate#9609] [Request Help] [answered]
Dependencies are declared in a file `application.yml`
```
something:
      image-version: 18.0-20201126-70
      image-name: an-image-name
something-else:
      image-version: 33.0-20210331-1107
      image-name: another-image-name
```
`renovate.json`:
```
{
    "extends": [
      "config:base"
    ],
    "enabledManagers": [
      "regex"
    ],
    "packageRules": [
      {
        "managers": [
          "regex"
        ]
      }
    ],
    "hostRules": [
      {
        "hostName": "registry.mydomain.net",
        "insecureRegistry": true
      }
    ],
    "regexManagers": [
        {
          "fileMatch": ["application\\.yml$"],
          "matchStrings": ["image-version:\\s*(?<currentValue>.*?)\\s*image-name:\\s*(?<depName>.*?)$"],
          "datasourceTemplate": "docker",
      "versioningTemplate": "docker"
        }
    ]
  }
```
Renovate log output:
```
...
DEBUG: Using file match: \.application\.yml$ for manager regex (repository=~user/my.repository)
DEBUG: Found 0 package file(s) (repository=~user/my.repository)
...
```
