### DISCUSSION TITLE
How to use the config.js in gitlab-ci.yml?

### DISCUSSION THREAD

**Discussion by ninomllr** [renovatebot/renovate#9664] [Request Help] [answered]
I have used renovate bot together with my gitlab ci and it worked quite well until end of last year. After a while it stopped working because I think the docker container changed access rights within the instance. The path /usr/src/app is owned by root, but the pipeline runs as ubuntu. Does someone have an idea on how I can get my script back working? There is no wheel or sudo in place, so I am not sure on how to solve this problem..

```yaml
image: 
  name: renovate/renovate
  entrypoint: [""]

stages:
  - renovate

before_script:
  - cp config.js /usr/src/app/config.js

renovate:
  stage: renovate
  only:
    - master
  script: 'node /usr/src/app/dist/renovate.js'
```
