### DISCUSSION TITLE
Private NPM package lookup failure

### DISCUSSION THREAD

**Discussion by chris-dura** [renovatebot/renovate#9801] [Request Help] [answered]
So, our IT dept. has banned "shared/service/bot" accounts on our Self-Hosted GitLab instance. I'm attempting to workaround this by having each repo [run renovate on itself](https://github.com/renovatebot/renovate/discussions/9167#discussioncomment-494323).

But, now I'm experiencing a lookup error when the renovate tries to get my private npm packages, because, for some reason, it's attempting to look them up on the public npmjs.registry.org, and not my private registry. I'm using the same exact `config.js` file I was using successfully before.

- **This works:** Scheduled Pipeline on separate `renovatebot` repo runs `npm run renovate` to renovate `my-foo-project`.
- **This throws lookup error:** Scheduled Pipeline on `my-foo-project` repo runs `npm run renovate` to renovate `my-foo-project`.

```yaml
# .gitlab-ci.yml

stages:
  - run

default:
  tags:
    - docker

run:
  image: node:14
  only:
    - schedules
  stage: run
  before_script:
    - npm config set registry https://my-registry.my-company.com
    - npm install
  script:
    - npm config list
    - npm run renovate
```

```bash
DEBUG: Dependency lookup failure: not found (repository=my-foo-project)
       "err": {
         
         ...

         "options": {
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://registry.npmjs.org/my-private-library",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         
         ...
       },
       "packageName": "my-private-library"
DEBUG: Failed to look up dependency my-private-library (repository=my-foo-project, packageFile=package.json, dependency=my-private-library)
```
