### DISCUSSION TITLE
Loose regex versioning

### DISCUSSION THREAD

**Discussion by sparhomenko** [renovatebot/renovate#9919] [Request Help] [answered]
I've recently started using Renovate and ran into difficulty with dependencies that:
1. Use a non-standard versioning scheme that required `regex` versioning.
2. Have more than three version number components, usually caused by a semver from an upstream project suffixed with a release number by a 'distributor' (Bitnami, LinuxServer, Rancher).

Some examples are: [bitnami/mariadb](https://hub.docker.com/r/bitnami/mariadb/tags?page=1&ordering=last_updated) (`10.5.10-debian-10-r0`), [linuxserver/duplicati](https://hub.docker.com/r/linuxserver/duplicati/tags?page=1&ordering=last_updated) (`v2.0.6.1-2.0.6.1_beta_2021-05-03-ls99`), [rancher/rke2](https://github.com/rancher/rke2/releases/) (`v1.20.6+rke2r1`). Some of them also have tags without a release number (eg. `10.5.10` and `version-v2.0.6.1-2.0.6.1_beta_2021-05-03`), but they are akin to `latest` - moved with each release build defeating the purpose of immutable versioning.

I'm using `regex` versioning, but since it only supports major/minor/patch versions I can't find a way to correctly recognize all new releases. Best I was able to come up with was to ignore the version component(s) that change less frequently, eg. `regex:^10\.(?<major>\d+)\.(?<minor>\d+)-.*-r(?<patch>\d+)$`. Along with the obvious downside of ignoring the new major versions (if MariaDB 11 will ever see daylight) it confuses update-type-specific functionality like `separateMajorMinor`.

[fluxcd/image-automation-controller](https://github.com/fluxcd/image-automation-controller) allows a slightly better workaround based on semver 2.0 numeric pre-release identifiers:
```yaml
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: mariadb
spec:
  imageRepositoryRef:
    name: mariadb
  filterTags:
    pattern: "^(?P<semver>\\d+\\.\\d+.\\d+)-debian-(?P<os>\\d+)-r(?P<r>\\d+)$"
    extract: "$semver-$os.$r"
  policy:
    semver:
      range: ">=0.0.0-0"
```
It had a downside of treating all versions as a pre-release, requiring `range: ">=0.0.0-0"` (`ignoreUnstable: false`). Still seems to be a better workaround, but I wasn't able to replicate it with Renovate as `regex` versioning expects prerelease identifier to be captured as a single `(?<prerelease>)` named group.

Can anyone more experienced with Renovate comment whether I'm missing a better way?
