### ISSUE TITLE
`semanticCommitType` in packageRule is ignored

### ISSUE THREAD

**Issue by Zyava** [renovatebot/renovate#10184]
**How are you running Renovate?**

- [x] Self hosted

Renovate version: **25.0.0 and any version above**

**Describe the bug**

There is a weird bug introduced in version `25.0.0` which doesn't exist in `24.119.22` but  I can't figure out exact commit when it was introduced, [all commits between these 2 tags](https://github.com/renovatebot/renovate/compare/24.119.22...25.0.0) look unrelated.

We have the following `config.js`:

```js
module.exports = {
  extends: [
    "config:base",
    ":semanticCommitScope(deps)"
  ],
  "gitlabci": {"fileMatch": ["^*/*.yml$"]},
  "gitlabci-include": {"fileMatch": ["^*/*.yml$"]},
  "packageRules": [
...
    {
      "description": "Update references to Gitlab CI template files",
      "matchPaths": ["!(.gitlab-ci).yml"],
      "matchDatasources": ["docker"],
      "automerge": false,
      "commitMessageTopic": "references of {{{depName}}}",
      "commitMessagePrefix": null,
      "semanticCommitType": "fix",
      "semanticCommitScope": "deps",
      "additionalBranchPrefix": "ci-template-deps-"
    },
...
  ],
...
```

and the following yaml file with gitlab-ci template snippet:

```yaml
.renovate:
  stage: renovate
#  image: renovate/renovate:24.119.22
  image: renovate/renovate:25.0.0
  extends:
    - .tags_default
    - .cache_disabled
    - .run_on_schedule
    - .variables_default
    - .functions
  variables:
    LOG_LEVEL: debug
    RENOVATE_PLATFORM: gitlab
    RENOVATE_ENDPOINT: $CI_API_V4_URL
    RENOVATE_GIT_AUTHOR: "Gitlab Bot <gitlab.bot@domain.com>"
    RENOVATE_TOKEN: $GITLAB_TOKEN
    RENOVATE_DRY_RUN: "false"
    RENOVATE_ASSIGNEES: $RENOVATE_ASSIGNEES
    DOCKER_USERNAME: gitlab-ci-token
    DOCKER_PASSWORD: $GITLAB_TOKEN
    GITHUB_COM_TOKEN: $GITHUB_COM_TOKEN
    NODE_TLS_REJECT_UNAUTHORIZED: 0
#    EXTRA_ARGS: --trust-level=high --pr-hourly-limit=0 --pr-concurrent-limit=0
    EXTRA_ARGS: --expose-all-env --allow-scripts --allow-custom-crate-registries --pr-hourly-limit=0 --pr-concurrent-limit=0
    PROJECT_PATH: $CI_PROJECT_PATH
    PROJECT_ID: $CI_PROJECT_ID
    DEFAULT_BRANCH: $CI_DEFAULT_BRANCH
  script:
    - export RENOVATE_ASSIGNEES=$(echo "$RENOVATE_ASSIGNEES" | tr -d '"')
    - check_variables_defined RENOVATE_PLATFORM RENOVATE_ENDPOINT RENOVATE_GIT_AUTHOR RENOVATE_TOKEN RENOVATE_DRY_RUN DOCKER_USERNAME DOCKER_PASSWORD GITHUB_COM_TOKEN
    - configure_git "${RENOVATE_TOKEN}"
    - renovate ${EXTRA_ARGS} "${PROJECT_PATH}"
```

With renovate version `24.119.22` and below commit and MR are correctly created with text "fix(deps)" while with `25.0.0` and above commit and MR are created with  text "chore(deps)" (i.e. `"semanticCommitType": "fix"` in packageRule is ignored) while `"additionalBranchPrefix": "ci-template-deps-"` is still applied to the branch name.

**Relevant debug logs**

Logs of renovate v25.0.0 like these:

```
...
DEBUG: Creating PR (repository=platform/ci-templates, branch=renovate/ci-template-deps-renovate-renovate-25.x)
       "prTitle": "chore(deps): update references of renovate/renovate to v25.31.9"
DEBUG: Creating Merge Request: chore(deps): update references of renovate/renovate to v25.31.9 (repository=platform/ci-templates, branch=renovate/ci-template-deps-renovate-renovate-25.x)
 INFO: PR created (repository=platform/ci-templates, branch=renovate/ci-template-deps-renovate-renovate-25.x)
       "pr": 265,
       "prTitle": "chore(deps): update references of renovate/renovate to v25.31.9"
```

while logs of `24.119.22` (and versions below) with **the same** `config.js` are ok:

```
DEBUG: Creating PR (repository=platform/ci-templates, branch=renovate/ci-template-deps-renovate-renovate-24.x)
       "prTitle": "fix(deps): update references of renovate/renovate to v24.119.22"
DEBUG: Creating Merge Request: fix(deps): update references of renovate/renovate to v24.119.22 (repository=platform/ci-templates, branch=renovate/ci-template-deps-renovate-renovate-24.x)
 INFO: PR created (repository=platform/ci-templates, branch=renovate/ci-template-deps-renovate-renovate-24.x)
       "pr": 262,
       "prTitle": "fix(deps): update references of renovate/renovate to v24.119.22"
```

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [x] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

...
