### ISSUE TITLE
Pin the GitHub actions we use on this repo to a full length commit SHA

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#10841]
**What would you like Renovate to be able to do?**

@rarkins and @viceice now that PR #10835 is merged, we can start thinking about pinning our GitHub Actions to the current full length Git commit SHA?

**Did you already have any implementation ideas?**

@viceice can you explain what pattern we need to follow to make things work properly?
I think you can use a comment to say what "tagged version" you're at???

As an example I've grabbed the commit to which `actions/setup-node@v2.2.0` points right now.

```yml
- name: Set up Node.js ${{ env.NODE_VERSION }}
  uses: actions/setup-node@38d90ce44d5275ad62cc48384b3d8a58c500bb5f
  with:
    node-version: ${{ env.NODE_VERSION }}
    cache: yarn
```

Or maybe we can add a comment which says what tag we're "following".

```yml
- name: Set up Node.js ${{ env.NODE_VERSION }}
  uses: actions/setup-node@38d90ce44d5275ad62cc48384b3d8a58c500bb5f # setup-node: tag=v2
  with:
    node-version: ${{ env.NODE_VERSION }}
    cache: yarn
```

We'll also need to update the `default.json` over on the `renovate/.github` repository, to make use of the new feature.
