### ISSUE TITLE
Add first-class support for build version matrixes (especially Node)

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#11175]
**What would you like Renovate to be able to do?**

Support build matrixes in a non-hacky manner.

**Did you already have any implementation ideas?**

Travis support previously had this but in a hacky approach which needed removing. We need to think of a better way which can co-exist with our regular updating approach.

**Comment by vindvaki** [comment]
Would love to have this for GitLab's [`parallel:matrix`](https://docs.gitlab.com/ee/ci/yaml/#parallelmatrix)!

My use case is that I have jobs of the form

```yaml
test:
  parallel:
    matrix:
      - K3S_VERSION:
        - v1.20.15-k3s1
        - v1.21.10-k3s1
        - v1.22.7-k3s1
        - v1.23.4-k3s1
  services:
    - name: registry.gitlab.com/gitlab-org/cluster-integration/test-utils/k3s-gitlab-ci/releases/$K3S_VERSION
      alias: k3s
  # ... 
```

and I want `K3S_VERSION` to be a sliding window of the latest `N` minor releases, each kept at their latest patch release. And would prefer a single MR updating the entire `K3S_VERSION` array.

I can imagine this working as a combination of two more general features:

- a generic YAML/JSON manager that can do structural replacements  based on something like jq or jsonpath (or even just full blown javascript)
- multi-version support, such as the sliding window of latest `N` minor releases
