### ISSUE TITLE
Regression with 26.15.0: GitLab dependencies no longer properly updated

### ISSUE THREAD

**Issue by knutwannheden** [renovatebot/renovate#11591]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

gitlab.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

Latest version provided via renovate-bot/renovate-runner

### Describe the bug

Last week we started noticing that some GitLab dependencies managed using the `gitlabci-include` manager stopped getting updated when running the Renovate job. Looking at the logs we found some debug messages which looked suspicious (see below).

With older versions of Renovate (specifically 26.14.1) we hadn't seen these `GitLab API 404` and `Datasource 404` messages and even though they are logged at the DEBUG level, we get the impression that they hint at the problem with updating the `gitlab-include` dependency in question. We have now downgraded to 26.14.1 (using the renovate-runner v3.13.3) and everything appears to work again.

Everything else runs smoothly. Does this possibly have anything to do with the new feature implemented by https://github.com/renovatebot/renovate/pull/11226? Is it possible that the GitLab PAT token is missing in the request?

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: GitLab API 404 (repository=diemobiliar/it/glu/test/glu-test-shipment-service)
       "url": "https://gitlab.com/api/v4/projects/diemobiliar%2Fit%2Fglu%2Fservice%2Fglu-service-stack/repository/tags?per_page=100"
DEBUG: Datasource 404 (repository=diemobiliar/it/glu/test/glu-test-shipment-service)
       "datasource": "gitlab-tags",
       "lookupName": "diemobiliar/it/glu/service/glu-service-stack",
       "url": "https://gitlab.com/api/v4/projects/diemobiliar%2Fit%2Fglu%2Fservice%2Fglu-service-stack/repository/tags?per_page=100"
DEBUG: Failed to look up dependency diemobiliar/it/glu/service/glu-service-stack (repository=diemobiliar/it/glu/test/glu-test-shipment-service, packageFile=.gitlab-ci.yml, dependency=diemobiliar/it/glu/service/glu-service-stack)
```
and further down (part of a longer message starting with `DEBUG: packageFiles with updates`):
```
         "gitlabci-include": [
           {
             "packageFile": ".gitlab-ci.yml",
             "deps": [
               {
                 "datasource": "gitlab-tags",
                 "depName": "diemobiliar/it/glu/service/glu-service-stack",
                 "depType": "repository",
                 "currentValue": "1.0.2111",
                 "registryUrls": ["https://gitlab.com"],
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [
                   {
                     "topic": "diemobiliar/it/glu/service/glu-service-stack",
                     "message": "Failed to look up dependency diemobiliar/it/glu/service/glu-service-stack"
                   }
                 ],
                 "versioning": "semver"
               }
             ]
           }
         ],
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
@viceice do you think this is a similar problem to the github one seen last week? e.g. needs more `hostRules`?

**Comment by viceice** [comment]
@knutwannheden how do you configure the gitlab auth?

@rarkins yes, it can be the hostType changes

**Comment by knutwannheden** [comment]
We use the `RENOVATE_TOKEN` variable. Our `.gitlab-ci.yml` file basically looks like this:

```yaml
include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate-dind.gitlab-ci.yml'

variables:
  RENOVATE_PLATFORM: gitlab
  RENOVATE_TOKEN: $GITLAB_TOKEN
  RENOVATE_GIT_AUTHOR: 'Renovate Bot <renovate-bot-noreply@mobi.ch>'
  RENOVATE_ONBOARDING: 'false'
  RENOVATE_ONBOARDING_CONFIG: '{"$$schema": "https://docs.renovatebot.com/renovate-schema.json", "extends": ["config:base"] }'
  RENOVATE_AUTODISCOVER: 'false'
  RENOVATE_OPTIMIZE_FOR_DISABLED: 'true'
  RENOVATE_REPOSITORY_CACHE: 'true'
  RENOVATE_REQUIRE_CONFIG: 'true'
  RENOVATE_IGNORE_PR_AUTHOR: 'true'
  RENOVATE_EXTENDS: ''
  RENOVATE_LOG_FILE: renovate-log.ndjson
  RENOVATE_LOG_FILE_LEVEL: debug
  LOG_LEVEL: debug
```

The `GITLAB_TOKEN` variable is defined in the GitLab settings.
