### ISSUE TITLE
Helmsman support

### ISSUE THREAD

**Issue by ekhaydarov** [renovatebot/renovate#11848]
### What would you like Renovate to be able to do?

following on from #11844 where @viceice has suggested it should be straight forward to add helmsman support.

### If you have any ideas on how this should be implemented, please tell us here.

you need to search for a `desired-state.yaml` within which you only need two keys to look up dependencies.

```
helmRepos:
  ingress-nginx: "https://kubernetes.github.io/ingress-nginx"
  jetstack: "https://charts.jetstack.io"

apps:
  ingress-nginx:
    enabled: true
    chart: ingress-nginx/ingress-nginx
    version: 3.33.0

  cert-manager:
    enabled: true
    chart: jetstack/cert-manager
    version: v1.3.1
```
The chart can be expanded to the full url using the `helmRepos` dict to then make a call and search for updates

If you need any more information, then happy to help 👍 

### Is this a feature you are interested in implementing yourself?

No
