### ISSUE TITLE
Helmv3 OCI dependencys with aliases

### ISSUE THREAD

**Issue by irrandon** [renovatebot/renovate#12199]
### What would you like Renovate to be able to do?

OCI registry lookup with the helmv3 manager should also work with aliases.

renovate.json:
```json
{
  "helmv3": {
    "aliases": {
      "artifactory": "oci://artifactory.example.com"
    }
  }
}
```

Chart.yaml:
```yaml
apiVersion: v2
description: Renovate example
name: example
version: 0.0.1
dependencies:
  - name: "example"
    version: "1.0.2"
    repository: "alias:artifactory"
```

### If you have any ideas on how this should be implemented, please tell us here.

Remove/rewrite [this](https://github.com/renovatebot/renovate/blob/c43554b69343fb131209997c52cac518b3048fe0/lib/manager/helmv3/extract.ts#L60) if/else block

### Is this a feature you are interested in implementing yourself?

No
