### ISSUE TITLE
Update GitHub Actions reusable workflows

### ISSUE THREAD

**Issue by DanySK** [renovatebot/renovate#12212]
### What would you like Renovate to be able to do?

It is now possible to write [reusable workflows in GitHub Actions]. This proposal is to support updates to referenced reusable workflows, just as it does for actions.

```yaml
jobs:
  classic-job:
    steps:
      - uses: some/action@v1 # <- Renovate can update this already
  call-workflow-1:
    uses: octo-org/this-repo/.github/workflows/workflow-1.yml@172239021f7ba04fe7327647b213799853a9eb89 # <- Renovate should be able to update also this...
  call-workflow-2:
    uses: octo-org/another-repo/.github/workflows/workflow-2.yml@v1 # <- ...and this
```

### If you have any ideas on how this should be implemented, please tell us here.

I have not checked the github actions manager code yet, but I guess it does extract a repo reference from values associated to `uses:`. If this is the case, I'd expect the implementation to be rather simple -- basically, if the current extraction is with a regex like `(owner match)/(repo match)@(version match)`, change it to something like `(owner match)/(repo match)(?:/.github/workflows/.*\.ya?ml)?@(version match)`

(I am using a pseudo-regex just to convey the idea).

### Is this a feature you are interested in implementing yourself?

Yes
