### ISSUE TITLE
Support intermediate captured groups in recursive strategy

### ISSUE THREAD

**Issue by sclorng** [renovatebot/renovate#12279]
### What would you like Renovate to be able to do?

I have a file with multiple group sections like

````
group: 
  ccm:
    baseRepository: foo

  components:
    ccm:
      repository: banana
      version: 1.0.0

group: 
  ccm:
    baseRepository: bar

  components:
   ccm:
      repository: apple
      version: 1.0.0
````

I would like to be able to first match a group content  and capture baseRepository, and then capture each component.
so that I can write a depNameTemplate as  `{{baseRepository}}/{{repository}}`
with something like :

```
"matchStrings": [
        "group:\\s+ccm:\\s+baseRepository: (?<baseRepository>.*?)\\s.*",
        "components:\\s.*",
        "ccm:\\s+repository: (?<repository>.*?)\\s*branch: (?<currentValue>.*)\\s?"
      ],
```

It should give out dependencies: `foo/banana` and `bar/apple`

### If you have any ideas on how this should be implemented, please tell us here.

groups can be pass to handleRecursive calls and mergeGroups be call before createDependency

### Is this a feature you are interested in implementing yourself?

No
