### ISSUE TITLE
Go dependencies update fails with `Could not forward go, probably wrong PATH variable.`

### ISSUE THREAD

**Issue by julienvey** [renovatebot/renovate#13256]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.11.6

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

We are running renovate on a Kubernetes cluster as a cronjob

### Describe the bug

At some point in time, not sure why, but our Go projects started to fail to update due to the following error

```
Command failed: go get -d ./...\nCould not forward go, probably wrong PATH variable.
```

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: go get command included (repository=struktur/sk, branch=renovate/patch-patch-updates)
       "cmd": "go",
       "args": "get -d ./..."
DEBUG: go mod tidy command included (repository=struktur/sk, branch=renovate/patch-patch-updates)
       "cmd": "go",
       "args": "mod tidy"
DEBUG: additional go mod tidy command included (repository=struktur/sk, branch=renovate/patch-patch-updates)
       "cmd": "go",
       "args": "mod tidy"
DEBUG: Executing command (repository=struktur/sk, branch=renovate/patch-patch-updates)
       "command": "go get -d ./..."
DEBUG: rawExec err (repository=struktur/sk, branch=renovate/patch-patch-updates)
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "go get -d ./...",
         "stdout": "PATH=/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n",
         "stderr": "Could not forward go, probably wrong PATH variable.\n",
         "message": "Command failed: go get -d ./...\nCould not forward go, probably wrong PATH variable.\n",
         "stack": "Error: Command failed: go get -d ./...\nCould not forward go, probably wrong PATH variable.\n\n    at ChildProcess.exithandler (child_process.js:383:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:475:12)\n    at maybeClose (internal/child_process.js:1058:16)\n    at Socket.<anonymous> (internal/child_process.js:443:11)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:475:12)\n    at Pipe.<anonymous> (net.js:686:12)"
       }
DEBUG: Failed to update go.sum (repository=struktur/sk, branch=renovate/patch-patch-updates)
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "go get -d ./...",
         "stdout": "PATH=/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n",
         "stderr": "Could not forward go, probably wrong PATH variable.\n",
         "message": "Command failed: go get -d ./...\nCould not forward go, probably wrong PATH variable.\n",
         "stack": "Error: Command failed: go get -d ./...\nCould not forward go, probably wrong PATH variable.\n\n    at ChildProcess.exithandler (child_process.js:383:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:475:12)\n    at maybeClose (internal/child_process.js:1058:16)\n    at Socket.<anonymous> (internal/child_process.js:443:11)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:475:12)\n    at Pipe.<anonymous> (net.js:686:12)"
       }
```

</details>

### Have you created a minimal reproduction repository?

https://gitlab.com/radiofrance/kubecli/-/merge_requests/27

**Comment by rarkins** [comment]
That sounds like it's being thrown from `go` itself?

**Comment by julienvey** [comment]
🤷 I checked on the pod directly, go is present in `/usr/local/bin` 

If I run a fresh `git clone` then `go get -d ./...` in the pod, I don't see any errors

**Comment by viceice** [comment]
Please describe your renovate deployment in more detail? which docker image are you using? are you doing any special modifications?

**Comment by julienvey** [comment]
We are using a copy of the docker hub image renovate/renovate. (we just reuploaded it to our internal registry)

We run it with the following cronjob, the only setup we do is for git credentials and token access

<details><summary>Cronjob</summary>

```
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: renovate-my-gitlab
    app.kubernetes.io/managed-by: example
    branch: production
    environment: production
    platform: tools
  name: renovate-my-gitlab
  namespace: prodtools
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            example.com/image.busybox.source: v1
            example.com/image.renovate.source: 31.11.6
          labels:
            app: renovate-my-gitlab
            branch: production
            environment: production
            platform: tools
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kops.k8s.io/instancegroup
                    operator: In
                    values:
                    - nodes_spot
          containers:
          - args:
            - -c
            - cp -R /shared/.ssh /home/ubuntu && node /usr/src/app/dist/renovate.js
            command:
            - /bin/sh
            env:
            - name: DOCKER_HUB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DOCKER_HUB_PASSWORD
                  name: renovate-my-gitlab-env
            - name: DOCKER_HUB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DOCKER_HUB_USERNAME
                  name: renovate-my-gitlab-env
            - name: GCR_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  key: GCR_CREDENTIALS
                  name: renovate-my-gitlab-env
            - name: GITHUB_COM_TOKEN
              valueFrom:
                secretKeyRef:
                  key: GITHUB_COM_TOKEN
                  name: renovate-my-gitlab-env
            - name: GONOSUMDB
              value: mygitlab.com/*
            - name: LOG_LEVEL
              value: debug
            - name: RENOVATE_CONFIG_FILE
              value: /etc/renovate/config.js
            - name: RENOVATE_ENDPOINT
              value: https://mygitlab.com/api/v4
            - name: RENOVATE_TOKEN
              valueFrom:
                secretKeyRef:
                  key: RENOVATE_TOKEN
                  name: renovate-my-gitlab-env
            image: myregistry.com/renovate@sha256:4e80252ae3c6b33012575b1ec166085d5a4f55b66d709c93f00549076655b66d
            imagePullPolicy: Always
            name: renovate
            resources:
              limits:
                cpu: 2048m
                memory: 2Gi
              requests:
                cpu: 512m
                memory: 2Gi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /downwardAPI
              name: podinfo
            - mountPath: /home/ubuntu/.config/git
              name: renovate-git-config
              readOnly: true
            - mountPath: /etc/renovate
              name: renovate-my-gitlab-config
              readOnly: true
            - mountPath: /secrets/ssh
              name: renovate-ssh-config
              readOnly: true
            - mountPath: /shared
              name: shared
          dnsPolicy: ClusterFirst
          imagePullSecrets:
          - name: gcr-json-key
          initContainers:
          - args:
            - -c
            - cp -R /secrets/ssh /shared/.ssh && chown -R 1000:0 /shared/.ssh
            command:
            - /bin/sh
            image: myregistry.com/busybox@sha256:d9c778abf14836dee94bfc321cc91d45b1dbee7430ecf9b40450707515838886
            imagePullPolicy: Always
            name: chown-ssh-key
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /home/ubuntu/.config/git
              name: renovate-git-config
              readOnly: true
            - mountPath: /etc/renovate
              name: renovate-my-gitlab-config
              readOnly: true
            - mountPath: /secrets/ssh
              name: renovate-ssh-config
              readOnly: true
            - mountPath: /shared
              name: shared
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          tolerations:
          - effect: NoSchedule
            key: dedicated
            operator: Equal
            value: spot
          volumes:
          - downwardAPI:
              defaultMode: 420
              items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels
                path: labels
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations
                path: annotations
            name: podinfo
          - configMap:
              defaultMode: 420
              name: renovate-git-config
            name: renovate-git-config
          - configMap:
              defaultMode: 420
              name: renovate-my-gitlab-config
            name: renovate-my-gitlab-config
          - name: renovate-ssh-config
            secret:
              defaultMode: 420
              items:
              - key: config
                path: configapiVersion: batch/v1

```

</details>

We use the following config

<details><summary>Config</summary>

```
module.exports = {
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "platform": "gitlab",
  "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
  "autodiscover": true,
  "autodiscoverFilter": "{group1/*,group2/*}",
  "labels": ["dependencies"],
  "rebaseLabel": "needs-rebase",
  "rebaseWhen": "auto",
  "extends": [
    ":separateMajorReleases",
    ":automergePatch",
    ":ignoreUnstable",
    ":prImmediately",
    ":semanticPrefixChore",
    ":updateNotScheduled",
    ":ignoreModulesAndTests",
    ":prConcurrentLimit10",
    "group:recommended",
    "schedule:daily",
    "workarounds:all"
  ],
  "minor": {
    "groupName": "minor-updates"
  },
  "patch": {
    "groupName": "patch-updates"
  },
  "packageRules": [
    {
      "matchDatasources": ["docker"],
      "matchUpdateTypes": ["minor", "patch"],
      "groupName": "docker-minor-patch"
    }
  ],
  "postUpdateOptions": ["gomodUpdateImportPaths", "gomodTidy", "npmDedupe"],
  "timezone": "Europe/Paris",
  "hostRules": [
    {
      "matchHost": "docker.io",
      "username": process.env.DOCKER_HUB_USERNAME,
      "password": process.env.DOCKER_HUB_PASSWORD,
    },
    {
      "matchHost": 'mygitlab.com',
      "token": process.env.RENOVATE_TOKEN,
    },
    {
      "matchHost": 'eu.gcr.io',
      "username": '_json_key',
      "password": process.env.GCR_CREDENTIALS,
    }
  ]
}
```

</details>
