### ISSUE TITLE
Support artifacthub's 'artifacthub.io/changes' annotation for Helm release changelogs

### ISSUE THREAD

**Issue by onedr0p** [renovatebot/renovate#13385]
### What would you like Renovate to be able to do?

It would be neat if renovate could render a changelog from the `artifacthub.io/changes` field in the Helm charts's `Chart.yaml`

`artifacthub.io/changes` is explained here: https://artifacthub.io/docs/topics/annotations/helm/

This is set by either an array:

```yaml
# Chart.yaml
...
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Cool feature
      links:
        - name: Github Issue
          url: https://github.com/issue-url
        - name: Github PR
          url: https://github.com/pr-url
    - kind: fixed
      description: Minor bug
      links:
        - name: Github Issue
          url: https://github.com/issue-url
...
```

or by a simple string:

```yaml
# Chart.yaml
...
annotations:
  artifacthub.io/changes: |
    - Added cool feature
    - Fixed minor bug
...
```

### If you have any ideas on how this should be implemented, please tell us here.

I haven't found any other references to this artifacthub annotation.

### Is this a feature you are interested in implementing yourself?

Maybe
