### ISSUE TITLE
Pulling Private OCI dependencies in Helm Chart

### ISSUE THREAD

**Issue by pspurlock07** [renovatebot/renovate#13524]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.22.0

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitLab Community Edition 14.5.2

### Describe the bug

Discussion for reference: https://github.com/renovatebot/renovate/discussions/11607

I am unable to update Chart.yaml OCI Dependencies when using gitlab private registry. I am not 100% on the issue, but I think I see 2 possible reasons why this is not working.

Given sample Chart.yml

```yaml
apiVersion: v2
name: test-app
description: Test applicaton's main chart
type: application
version: 1.0.0
appVersion: 0.0.0
dependencies:
  - name: test-dependency
    repository: oci://reg.gitlab.com/group/project/charts
    version: 1.0.0
   ```
   
   The error received shows this:
   
   `DEBUG: Datasource 404 (repository=group/project/charts)
       "datasource": "docker",
       "lookupName": "reg.gitlab.com/group/project/charts",
       "url": "https://reg.gitlab.com/v2/group/project/charts/tags/list?n=10000"`
       
Issue 1) The lookupName and/or url are wrong. The url should be "reg.git.act3-ace.com/group/project/charts/**test-dependency**/tags/list?n=10000"

Helm convention doesn't allow the full path as the repo, since it adds the name of the chart "test-dependency" to the end of the repo path.
       
Issue 2) Issue 1 may solve everything, but figure I would bring this up in case. To use docker registry HTTP v2 in gitlab requires a jwt token first, and then have to use that bearer token in the call. 

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository
