### ISSUE TITLE
Private docker registries in bitbucket-pipelines.yml

### ISSUE THREAD

**Issue by sti0** [renovatebot/renovate#13553]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.23.4

### Please select which platform you are using if self-hosting.

Bitbucket Cloud (bitbucket.org)

### Describe the bug

Bitbucket pipelines supports private Docker registries. This images are not hooked up by renovate.

Example:

```
image:
  name: "my.custom-domain.com/myimage:1.0.0"
  username: my-user
  password: my-password

pipelines:
  default:
    - step:
        name: Echo
        script:
          - echo "Hello World"
```

Checking for `image: "my.custom-domain.com/myimage:1.0.0"` works as expected.

See: [Using private build images](https://support.atlassian.com/bitbucket-cloud/docs/use-docker-images-as-build-environments/)

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository
