### ISSUE TITLE
Support private Docker registries in bitbucket-pipelines.yml 

### ISSUE THREAD

**Issue by sti0** [renovatebot/renovate#13555]
### What would you like Renovate to be able to do?

Bitbucket pipelines supports private Docker registries. This images are not hooked up by renovate.

Example:

```yml
image:
  name: "my.custom-domain.com/myimage:1.0.0"
  username: my-user
  password: my-password

pipelines:
  default:
    - step:
        name: Echo
        script:
          - echo "Hello World"
    - step:
        name: Important
        image:
          name: "my.custom-domain.com/importantimg:1.0.0"
          username: my-user
          password: my-password
        script:
          - important-cli
```

Checking for `image: "my.custom-domain.com/myimage:1.0.0"` works as expected.

See: [Using private build images](https://support.atlassian.com/bitbucket-cloud/docs/use-docker-images-as-build-environments/)

### If you have any ideas on how this should be implemented, please tell us here.

Improve the [current regex](https://github.com/renovatebot/renovate/blob/main/lib/manager/bitbucket-pipelines/extract.ts#L7)

### Is this a feature you are interested in implementing yourself?

No

**Comment by viceice** [comment]
I don't think this can be easily covered by regex, as the keys can be in any order. We should instead parse the file as yaml.

**Comment by sti0** [comment]
Please note that the syntax could appear within the steps as well:

```
image:
  name: "my.custom-domain.com/myimage:1.0.0"
  username: my-user
  password: my-password

pipelines:
  default:
    - step:
        name: Echo
        script:
          - echo "Hello World"
    - step:
        name: Important
        image:
          name: "my.custom-domain.com/importantimg:1.0.0"
          username: my-user
          password: my-password
        script:
          - important-cli
```
