### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by horjulf** [renovatebot/renovate#13604]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.28.2

### Please select which platform you are using if self-hosting.

gitlab.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

14.6

### Describe the bug

Crash during helmfile processing when the version field is dynamically generated.

```json
"currentValue": {"[object Object]": null},
"err": {
             "message": "constraint?.startsWith is not a function",
}
```

For example:

```yaml
releases:
  - name:  "external-dns"
    chart: "bitnami/external-dns"
    namespace: "external-dns"
    version: {{ .Values | getOrNil "external_dns.version" | default "4.5.5" }}
    installed: {{ .Values | getOrNil "external_dns.installed" | default false }}
```

https://gitlab.com/gitlab-com/gl-infra/k8s-workloads/gitlab-helmfiles/-/blob/master/releases/external-dns/helmfile.yaml

Full error in the logs below.

### Relevant debug logs

<details><summary>Logs</summary>

```
INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "EEI9CVsZ0mmjXsUC3kQSb",
           "repository": "gitlab-com/gl-infra/k8s-workloads/gitlab-helmfiles",
           "currentValue": {"[object Object]": null},
           "datasource": "helm",
           "depName": "external-dns",
           "followTag": null,
           "packageFile": "releases/external-dns/helmfile.yaml",
           "pinDigests": false,
           "rollbackPrs": false,
           "updatePinnedDependencies": true,
           "err": {
             "message": "constraint?.startsWith is not a function",
             "stack": "TypeError: constraint?.startsWith is not a function\n    at Object.isSingleVersion (/usr/src/app/node_modules/renovate/lib/versioning/npm/index.ts:39:18)\n    at lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:319:43)\n    at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:38:32)\n    at /usr/src/app/node_modules/p-map/index.js:57:22"
           },
           "msg": "lookupUpdates error"
         }
       ]
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs
