### ISSUE TITLE
Add support for OCI registries in helmfile

### ISSUE THREAD

**Issue by pspurlock07** [renovatebot/renovate#13656]
### What would you like Renovate to be able to do?

It would be nice to have support to be able to use OCI registries in helmfiles and have renovate be able to update dependencies on that. Currently, renovate only supports using helm chart repositories.

I created a minimum reproduction repo of this here: https://github.com/pspurlock07/renovate-helmfile-oci-reproduction

### If you have any ideas on how this should be implemented, please tell us here.

In a way, similar to how it is being implemented in the helmv3 manager.

Currently, helmfile requires oci to be specified as a key if being used:

```yaml
repositories:
- name: test-app-chart
  url: ghcr.io/pspurlock07
  oci: true
```

Using this example, if `oci:true` then set the `datasource: docker` or something to that effect.

```yaml
releases:
- name: test-app-chart
  namespace: {{ .Values.namespace }}
  chart: test-app-chart/test-app
```

I believe what may be the tricker part is the name that needs be used in the lookupName appears at the end of `chart: test-app-chart/**test-app**`

so an example lookupName that works would be `ghcr.io/pspurlock07/test-app`

The release name does not need to match/can be whatever a user wants. What's important is what they put after the slash ( / ) in their `chart: ` value under releases:

### Is this a feature you are interested in implementing yourself?

No
