### ISSUE TITLE
ArgoCD: Update OCI helm charts

### ISSUE THREAD

**Issue by patst** [renovatebot/renovate#13699]
### What would you like Renovate to be able to do?

We are using ArgoCD to define applications with helm charts.

The helm charts are stored as OCI image in a (private) container registry.
An example definition may look like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  source:
    repoURL: somecontainer.registry.io
    targetRevision: v1.2.0
    chart: some/image
```

At the moment the Argocd manager is not able to update these definitions because either the `GitTagsDatasource` or `HelmDatasource` are used for lookups. (see: https://github.com/renovatebot/renovate/blob/main/lib/manager/argocd/extract.ts#L34 )

### If you have any ideas on how this should be implemented, please tell us here.

The only trigger to see if a chart is an OCI chart is checking if a protocol (like `https` or `gs:`) exist in the `repoUrl` value.

Afaik, in case there is no protocol we can assume it is an OCI chart definition and use the docker datasource for lookups.

### Is this a feature you are interested in implementing yourself?

Yes
