### ISSUE TITLE
not updating docker image in docker-compose with build context defined

### ISSUE THREAD

**Issue by zeridon** [renovatebot/renovate#14102]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I have the following docker-compose section
```
  luftdaten2mqtt:
    restart: unless-stopped
    image: zeridon/luftdaten2mqtt:1.1.1
    build:
      context: https://github.com/zeridon/luftdaten2mqtt.git#v1.1.1
    depends_on:
      - mqtt
```
Due to PR #4272 no updates pushed to docker registry will be considered.

I am aware this is probably a corner case but my workflow is to develop locally. Changhe some configs in another repo and pull the changes on a third (quite old rpi2 in fact).

Being able to PULL docker image is valuable for me for the case of running it on a low power machine that might not be able to handle the compile load.

The repo in question is: https://github.com/zeridon/homeassistant

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs
