### ISSUE TITLE
Support for inflating helmchart deptype upgrades in the kustomize manager

### ISSUE THREAD

**Issue by pnordh** [renovatebot/renovate#14137]
### What would you like Renovate to be able to do?

Right now when the kustomize manager resolves an upgrade for a dependency of the helmchart deptype the kustomization.yaml is upgraded but the chart dependency is not inflated which means that the resulting Renovate PR is incomplete for repositories where the inflated chart is vendored (as per kustomizes best practice: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md#best-practice).

### If you have any ideas on how this should be implemented, please tell us here.

Renovate would likely need to first be able to determine if the chart is vendored, first because it likely needs to pull out if the chart is not vendored, but also in order to delete it before running `kustomize build --enable-helm` on the upgraded kustomization.yaml as per https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md#how-does-the-pull-work (i.e kustomize doesn't pull down the chart if it's already inflated regardless of version).

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
Sounds like this would fit into our "artifacts" concept, as we already support vendored components in other managers too. A reproduction is needed here so that we can see an example, and particularly an example of a current PR which is incomplete.

**Comment by pnordh** [comment]
Hi, you can find a reproduction here https://github.com/pnordh/renovate-14137-reproduction with the pnordh/renovate-14137-reproduction#1 PR as an example of an "incomplete" PR.

**Comment by rarkins** [comment]
Thanks, reproduction forked to https://github.com/renovate-reproductions/renovate-14137-reproduction

**Comment by MPV** [comment]
Looping in @andrein (who built the original feature in https://github.com/renovatebot/renovate/pull/12628), in case you have ideas (or want to help out with) a solution for this. 😊

**Comment by rarkins** [comment]
Can someone give an example of what a *complete* PR would look like? Then I am better placed to comment

**Comment by MPV** [comment]
@andrein Thanks for taking a look! 

That sentence in the Kustomize docs means “if there is already a chart downloaded, it won’t try again”. 

However, if one were to remove the downloaded chart, running Kustomize again, it will download it again.

So I think running `helm` for downloading shouldn’t be necessary as `Kustomize` can do it (as long as the “cached” chart in the repo has been deleted beforehand).

I’m thinking:
1. Renovate detects and bumps the version (as today).
2. Renovate deletes the related `<thedirectory>/charts/*.tar.gz` files. 
3. Renovate runs `kustomize build <thedirectory>`.

Thoughts?

**Comment by MPV** [comment]
@rarkins Here's an example of a _complete_ (expected) PR: 
https://github.com/pnordh/renovate-14137-reproduction/pull/3 

...compared to the already shown actual behavior in:
https://github.com/pnordh/renovate-14137-reproduction/pull/1

**Comment by rarkins** [comment]
Definitely looks similar to the `gomod` manager support for "vendored" modules. Is `charts/` reserved for this purpose?

**Comment by pnordh** [comment]
While `charts/` is the common convention it's not reserved for it. Users of the helm chart inflator also have the possibility of using another path, see https://github.com/kubernetes-sigs/kustomize/blob/master/api/types/helmchartargs.go#L7-L19

**Comment by rarkins** [comment]
Sorry I don't understand exactly how that file works. If the user changes the default path would we see it in a file in the repo we can parse?

**Comment by andrein** [comment]
@rarkins yes, we can read that field from `kustomize.yaml`, with a default of `charts` if it's not present. 

See [this example](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md#build-the-base-and-the-variants).
```
helmGlobals:
 chartHome: charts
```

**Comment by rarkins** [comment]
I'm not sure who's meant to be moving it forward, but I don't see any impediments

**Comment by andrein** [comment]
I'm sorry, I haven't found the time to fix this (yet). I hope I'll get a chance next week.

**Comment by MPV** [comment]
In the meanwhile, I can demo the workaround we have working somewhat okay in our repos; a GitHub actions workflow that looks like this:

```yaml
name: Renovate Chart Refresh
on:
  pull_request:
    paths:
      - "**/kustomization.yaml"

jobs:
  renovate-chart-refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAGERO_CI_GITHUB_TOKEN }}

      - run: |
          kustomize_dirs=`git diff --name-only origin/master | grep 'kustomization.yaml' | sed 's|/kustomization.yaml||'`

          for x in $kustomize_dirs; do
            rm -rf "$x/charts"
            kustomize build --enable-helm "$x" > /dev/null
          done

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(deps): update kustomize helm chart vendoring"
```
