### ISSUE TITLE
Support Argo CD Image Updater annotations

### ISSUE THREAD

**Issue by strayer** [renovatebot/renovate#14314]
### What would you like Renovate to be able to do?

Argo CD Image Updater can automatically update Docker image tags in ArgoCD GitOps repos. This is configured by annotations on the Application manifest.

Ideally I'd like Argo CD Image Updater to auto update semver patch releases and let Renovate open PRs for major and minor releases.

Argo CD Image Updater documentation: https://argocd-image-updater.readthedocs.io/en/stable/

Annotated application example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: gcr.io/heptio-images/ks-guestbook-demo:^0.1
    argocd-image-updater.argoproj.io/write-back-method: git
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: guestbook
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/argocd-example-apps/argocd-example-apps
    targetRevision: HEAD
```

### If you have any ideas on how this should be implemented, please tell us here.

Still new to Renovate and Argo CD, so no ideas on how to implement this, sorry!

### Is this a feature you are interested in implementing yourself?

No
