### ISSUE TITLE
Rename `dart` datasource to `pub`

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#14755]
### Describe the proposed change(s).

@zeshuaro proposed we rename the `dart` datasource to `pub` in a discussion on Slack.
`@rarkins` already agreed on Slack, so I'm capturing the discussion in a GitHub issue.

Artifactory calls private registries a pub registry. [^artifactory]

[^artifactory]: https://jfrog.com/blog/how-to-use-pub-repositories-in-artifactory/

**Comment by zeshuaro** [comment]
Can you assign the issue to me please? 🙂

**Comment by viceice** [comment]
This would cause a name collision again, as our manager is also called `pub`

**Comment by zeshuaro** [comment]
I'm missing a lot of context of why we we can't have same names for datasource and manager. But if this is causing issue, should we continue with the renaming? If so, should we then rename the `pub` manager and/or the `dart` datasource to something else?

**Comment by rarkins** [comment]
It's much easier when we have separate names for datasource and manager, although we don't want to be *wrong*. We have npm/npm and maven/maven for example.

**Comment by rarkins** [comment]
<img width="950" alt="image" src="https://user-images.githubusercontent.com/6311784/159852497-b5d33dfb-edf7-4a56-8aca-6941756a1082.png">

Dart is a programming language.

Flutter is.. a wrapper around Dart?

Pub is a package manager for both Dart and Flutter. But within Renovate will we need to have both `pub` and `flutter` "manager" modules, or just `pub`?

pub.dev is the default registry for this datasource, which is for both Dart and Flutter.

At the moment it seems like the benefit of using `dart` for the datasource to distinguish it from the `pub` manager is maybe worth it. But I'm not certain on that and happy to hear other opinions.

**Comment by zeshuaro** [comment]
> Dart is a programming language.

Yes.

> Flutter is.. a wrapper around Dart?

Flutter is a framework that uses Dart as the programming language. More like React/Angular that uses JavaScript for example.

> Pub is a package manager for both Dart and Flutter. But within Renovate will we need to have both pub and flutter "manager" modules, or just pub?

Yes this is correct. Pub is also bundled within Dart and Flutter. For Dart projects, you can use `dart pub`, whereas for Flutter projects, you can use `flutter pub`. Every Flutter project is a Dart project but not every Dart project is a Flutter project if that makes sense. 

I don't think we need to have two Pub managers for as the packages for both Dart and Flutter are all published onto the same registry - pub.dev. If we do end up with two managers, I would imagine that they'll function exactly the same.

> pub.dev is the default registry for this datasource, which is for both Dart and Flutter.

Every point you've made is correct haha. Both Dart and Flutter packages are published onto pub.dev. Similar to the point I've made from above, Flutter projects can use both Dart and Flutter packages but Dart projects can only use Dart packages. Pub will resolve this when it downloads and installs the packages. 

This is similar to NPM where there are JavaScript packages and React packages being published onto the registry.

> At the moment it seems like the benefit of using dart for the datasource to distinguish it from the pub manager is maybe worth it. But I'm not certain on that and happy to hear other opinions.

I would still argue that naming `pub` as the datasource is more appropriate as this is the registry for the packages. But if it will complicate things then I guess I don't have a strong opinion on this.

**Comment by rarkins** [comment]
On the other hand, if `dart` is the programming language, we usually don't use the language as the datasource name, e.g. we don't have `js`, `java` or `python` datasources. So in that case `pub` is better.

**Comment by viceice** [comment]
Btw: can flutter be used to update dart only project lockfiles?

**Comment by zeshuaro** [comment]
> Btw: can flutter be used to update dart only project lockfiles?

Yup I just tried using `flutter pub` to update a Dart project and was able to do so.

If you're curious on the differences between Dart and Flutter project config file `pubspec.yaml`, here's the two config files:

### Dart project

```yml
name: cli
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
```

### Flutter project

```yml
name: hello_world
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
```

Basically Flutter projects will have this dependency specified:

```yml
flutter:
  sdk: flutter
```
