### ISSUE TITLE
Ansible-galaxy datasource : enable the customRegistrySupport

### ISSUE THREAD

**Issue by lutin-malin** [renovatebot/renovate#14799]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.6.12

### Please select which platform you are using if self-hosting.

Bitbucket Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

N/A

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

According the the [galaxy documentation](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#install-multiple-collections-with-a-requirements-file), a declared collection can specify its own source.

[My] use case : a self hosted galaxy server hosting private collections. 

here could be an example :
```
#requirements.yml
---
collections:
  - name: awx.awx
    version: 19.0.0
    source: [my internal galaxy server]
```

At runtime, the specified source is ignored, and fallback to hardcoded value 'https://galaxy.ansible.com/'
https://github.com/renovatebot/renovate/blob/main/lib/modules/datasource/galaxy-collection/index.ts#L22

which leads to unretreived version values.

### Relevant debug logs

<details><summary>Logs</summary>

```
 WARN: Custom registries are not allowed for this datasource and will be ignored (repository=[my repo])
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
So are the custom sources extracted correctly by the manager but then ignored by the datasource?

**Comment by lutin-malin** [comment]
> So are the custom sources extracted correctly by the manager but then ignored by the datasource?

yes, out of the shelf !

**Comment by rarkins** [comment]
In that case this might work if we just set the custom registry flag from false to true

**Comment by lutin-malin** [comment]
that's what i did locally, and it is working 'almost' well.
> Remains a typo with the registry url for which the trailing backslash is removed( ... )

**Comment by TheLastProject** [comment]
Am I correct in understanding this issue also affect git clones? We seem to be suffering from something similar:

```
{"name":"renovate","hostname":"<removed>","pid":8,"level":40,"logContext":"<removed>","repository":"<removed>","datasource":"git-tags","registryUrls":["git@gitlab.<removed>:<removed>/mirrors/ansible-collections/community.docker"],"defaultRegistryUrls":null,"msg":"Custom registries are not allowed for this datasource and will be ignored","time":"2023-04-18T08:53:54.136Z","v":0}
```

With the following requirements.yml:
```
collections:
  - name: community.docker
    source: git@gitlab.<removed>:<removed>/mirrors/ansible-collections/community.docker
    type: git
    version: 2.7.5
```
