### ISSUE TITLE
gradle/libs.versions.toml replaces comment, not the version value

### ISSUE THREAD

**Issue by TWiStErRob** [renovatebot/renovate#15044]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

`gradle/libs.versions.toml` has contents like:
```toml
[versions]
# GitHub releases: https://github.com/mockk/mockk/releases
# TODO can't go farther than 1.12.3 yet https://github.com/mockk/mockk/issues/794
mockk = "1.12.2"

[libraries]
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
```

renovate updates the comment, not the version number:

https://github.com/TWiStErRob/net.twisterrob.gradle.renovate.test/pull/4/files#diff-697f70cdd88ba88fe77eebda60c7e143f6ad1286bca75017421e93ad84fb87dfR55-R56

### Relevant debug logs

<details><summary>Logs</summary>

https://app.renovatebot.com/dashboard#github/TWiStErRob/net.twisterrob.gradle.renovate.test/628749206

```json
 {
            "depName": "io.mockk:mockk",
            "groupName": "io.mockk",
            "currentValue": "1.12.2",
            "managerData": {
              "fileReplacePosition": 2420,
              "packageFile": "gradle/libs.versions.toml"
            },
            "fileReplacePosition": 2420,
            "registryUrls": [
              "https://repo.maven.apache.org/maven2",
              "https://dl.google.com/android/maven2/",
              "https://plugins.gradle.org/m2/",
              "https://jcenter.bintray.com/"
            ],
            "depIndex": 44,
            "updates": [
              {
                "bucket": "patch",
                "newVersion": "1.12.3",
                "newValue": "1.12.3",
                "releaseTimestamp": "2022-02-28T13:53:38.000Z",
                "newMajor": 1,
                "newMinor": 12,
                "updateType": "patch",
                "branchName": "renovate/patch-io.mockk"
              }
            ],
            "warnings": [],
            "versioning": "gradle",
            "sourceUrl": "https://github.com/mockk/mockk",
            "homepage": "http://mockk.io",
            "currentVersion": "1.12.2",
            "isSingleVersion": true,
            "fixedVersion": "1.12.2"
          },
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs
