### ISSUE TITLE
Add GitLab API 429 retries

### ISSUE THREAD

**Issue by adam-moss** [renovatebot/renovate#1578]
Hi,

I'm currently running Renovate in docker through GitLab CI:

```yaml
.renovate: &renovate
    stage: maintenance
    variables:
        RENOVATE_CONFIG_FILE: '$CI_PROJECT_DIR/config.js'
    <<: *executor-docker
    image: node:alpine
    script:
        - apk add --no-cache git
        - npx renovate
```

However if rate limiting is enabled  then Renovate will, correctly, gracefully exit when it gets a http/429 response.

However when it next initialises as a new container is provisioned it has no concept of where it left off.

Does the Renovate process maintain some sort of state file I can cache?

Cheers
