### ISSUE TITLE
[helm-values/docker] Support for arrays for docker image definition in values.yaml

### ISSUE THREAD

**Issue by arthurzenika** [renovatebot/renovate#15988]
### What would you like Renovate to be able to do?

For a list/array of images used in helm / kubernetes deployments such as : 

```
components: 
  - image: 
      repository: 'project/component/subcomponentA'
      registry: 'harbor.example.org'
      tag: '0.0.1'
  - image: 
      repository: 'project/component/subcomponentB'
      registry: 'harbor.example.org'
      tag: '0.0.1'
```

Details of the discussion on : https://github.com/renovatebot/renovate/discussions/15976

### If you have any ideas on how this should be implemented, please tell us here.

Nope, sorry. 

### Is this a feature you are interested in implementing yourself?

No
