### ISSUE TITLE
Support Rancher Fleet definitions

### ISSUE THREAD

**Issue by secustor** [renovatebot/renovate#16051]
### What would you like Renovate to be able to do?

Similar to ArgoCD and Flux, Fleet allows to deploy pull based GitOps.    

Fleet uses 2 kind of yaml files. The first has a defined name ( `fleet.yaml` ) which can be located in the repo root or any folder.    
The second one is a CR which is deployed onto Kubernetes and can therefore be located in any YAML file. 

 
[fleet.yaml](https://fleet.rancher.io/gitrepo-structure/#reference): 
```yaml
defaultNamespace: cattle-monitoring-system
helm:
  releaseName: rancher-monitoring-crd
  chart: rancher-monitoring-crd
  repo: https://charts.rancher.io
  version: 9.4.201
```
[GitRepo.yaml](https://fleet.rancher.io/gitrepo-add/): 
```yaml
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
  namespace: fleet-local
spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - single-cluster/helm
  revision: v0.3.0
```

### If you have any ideas on how this should be implemented, please tell us here.

A new manager is needed. The datasources can reused as the dependencies used are Helm and Git references. 

### Is this a feature you are interested in implementing yourself?

Maybe
