### ISSUE TITLE
GitHub Actions: Update service container image

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#16351]
### What would you like Renovate to be able to do?

Renovate should support updating service container images. [^gh-docs]

Let's say I have this `redis.yml` file in my `.github/workflows` directory:

```yaml
services:
      postgres:
        image: postgres:13.5
        env:
          POSTGRES_DB: db
          ...
```

Then Renovate should:

- create updates for the `postgres:13.5` image
- be able to pin the digest like it does for "normal" GitHub Action workflow files [^renovate-docs]

[^renovate-docs]: [Renovate docs, `pinDigests`](https://docs.renovatebot.com/configuration-options/#pindigests)
[^gh-docs]: [GitHub docs, about service containers](https://docs.github.com/en/actions/using-containerized-services/about-service-containers)

### If you have any ideas on how this should be implemented, please tell us here.

@paulzakin already created some custom regex that may help us figure out how to get started?

> ```json
>  "regexManagers": [
>     {
>       "fileMatch": ["^(\\.github\\/workflows)\\/[^/]+\\.ya?ml$"],
>       "matchStrings": ["image: (?<depName>.*):(?<currentValue>.*)"],
>       "datasourceTemplate": "docker"
>     }
>   ]
> ```

### Is this a feature you are interested in implementing yourself?

No

**Comment by maxbrunet** [comment]
I think Job container needs support as well (with/without image keyword)

```yaml
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
```

```yaml
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: node:14.16
```

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontainer
