### ISSUE TITLE
Support Helm Yaml Superset in Helmfile manager

### ISSUE THREAD

**Issue by SebastianGoeb** [renovatebot/renovate#17199]
### What would you like Renovate to be able to do?

It would be great if the Helmfile manager was able to parse all possible `helmfile.yaml`s, however a lot of helm/helmfile templates are not strictly valid yaml afaict, e.g.
```yaml
releases:
- name: my-release
  chart: my-custom-chart
  version: "1.2.3"
  namespace: {{ env "NAMESPACE" | quote }}
```
where `namespace: {{...}}` breaks the yaml parser because it looks like a broken object literal, when in reality templating will get rid of it.

This either locks me out of doing templating in my helmfiles, if I want them to be renovate-friendly, or at the very least forces me to do some unsafe string sanitization:

Not quoting the template string and instead piping to the `quote` function is common practice, as it is the only way to correctly sanitize all possible strings. For a namespace I can kinda get away with `namespace: '{{ env "NAMESPACE" | quote }}'`, as namespaces are generally alphanumeric, but this is not the case for all properties, especially labels, annotations, and such.

### If you have any ideas on how this should be implemented, please tell us here.

Is there maybe a different parser library that can handle these things out-of-the-box? I think Helm itself (which probably faces the same issue) uses ghodss/yaml (go of course, so not helpful here, but maybe worth a look at). Or is this fundamentally unsolvable?

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
These files use Go templating. Some possible approaches:

1. Stop using YAML parsing, instead make our own parser to understand "just enough" of the file to extract dependencies, ignoring templates
2. Fully strip any line containing `{{` and `}}` before YAML parsing. Maybe some work?
3. Reverse engineer Go's templating and compile the templates before parsing
4. Shell out to CLI and run Go templating first before YAML parsing

We want to avoid (4) because we currently have no CLI/shell in our extract phase

**Comment by viceice** [comment]
@rarkins We're already removing any templates from yaml before parsing, so it seems like a bug to me

https://github.com/renovatebot/renovate/blob/c9b21cee48ebf8e3a09de35ea6dcc422a94fbc1a/lib/modules/manager/helmfile/extract.ts#L27

https://github.com/renovatebot/renovate/blob/c9b21cee48ebf8e3a09de35ea6dcc422a94fbc1a/lib/modules/manager/helmfile/extract.ts#L13-L16

- #15106

**Comment by SebastianGoeb** [comment]
Ah, then actually it seems I jumped to the wrong conclusion.

So the actual file that is broken in our project has the namespace formulated like this:
```yaml
releases:
- name: my-release
  chart: my-custom-chart
  version: "1.2.3"
  namespace: "{{ env "NAMESPACE" }}"
```
which is improper quoting, but does work after templating, despite the nested double quotes. This also shows up as invalid YAML in VSCode.

I patched it like this:
```yaml
releases:
- name: my-release
  chart: my-custom-chart
  version: "1.2.3"
  namespace: '{{ env "NAMESPACE" }}'
```
which looks like a proper yaml string to a yaml parser, but turns in to a different yaml string after templating. It's still improper quoting though, however VSCode does not complain about syntax.

When I try proper quoting:
```yaml
releases:
- name: my-release
  chart: my-custom-chart
  version: "1.2.3"
  namespace: {{ env "NAMESPACE" | quote }}
```
VSCode again complain about invalid yaml. This led me to believe I would run into the same issue. Turns out, VSCode reads `helmfile.yaml` as "Language: YAML, JSON schema: helmfile", hence the yaml syntax errors for `{{ }}`, whereas actual Helm `template.yaml` files are read as "Language: helm-template", no syntax errors for `{{ }}`.
