### ISSUE TITLE
ansible-galaxy / parsing ends when a comment is found in dependencies

### ISSUE THREAD

**Issue by nesies** [renovatebot/renovate#17281]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

if galaxy.yml dependencies contains comments, renovate seems to stop parsing:

```
dependencies:
  ansible.posix: "1.0.0"
  # comment whih makes renovate end parsing
  # latest is 2.6.1
  ansible.utils: "1.0.0"
```

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description
