### ISSUE TITLE
feat: Vendir manager

### ISSUE THREAD

**Issue by gberche-orange** [renovatebot/renovate#17711]
### What would you like Renovate to be able to do?

Vendir is a tool to vendor a fair variety of resources on the local file system that map to renovate datasources:

https://carvel.dev/vendir/docs/v0.30.0/
> Supported sources for fetching:
>     git
>     image (image from OCI registry)
>     githubRelease
>     helmChart
> 

Sample:  
```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:

- path: k8s-manifests 
  contents:

  - path: github.com/vmware-tanzu/carvel-kapp-controller
    githubRelease:
      slug: vmware-tanzu/carvel-kapp-controller
      tag: v0.30.0
```

Full syntax spec: https://carvel.dev/vendir/docs/v0.30.0/vendir-spec/

Currently, I'm using the regexp manager with the following rules, however a built-in manager would enable more efficient sharing with the community

```json
  "regexManagers": [
    {
      "fileMatch": ["vendor/vendir-k8s-manifest.yml$"],
      "matchStrings": [
        " +githubRelease:\\n +slug: (?<depName>[a-z0-9\\.\\/\\-]*?)\\n +tag: (?<currentValue>[a-z0-9\\.\\/\\-\\+]*?) *\\n/"
      ],
      "datasourceTemplate": "github-releases",
      "versioningTemplate": "regex:v?(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)?$"
    },
    {
      "description": "https://regex101.com/r/SChCZX/1",
      "fileMatch": ["vendor/vendir-k8s-manifest.yml$"],
      "matchStrings": [
        " +git:\\n +url: (?<depName>[a-z0-9\\.\\/\\-:]*?)\\n +ref: (?<currentValue>[a-z0-9\\.\\/\\-\\+]*?) *\\n"
      ],
      "datasourceTemplate": "git-refs",
      "versioningTemplate": "regex:v?(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)?$"
    }
  ]

```

### If you have any ideas on how this should be implemented, please tell us here.

a new manager

### Is this a feature you are interested in implementing yourself?

Maybe
