### ISSUE TITLE
Renovate manager helm values should support image name  

### ISSUE THREAD

**Issue by teimyBr** [renovatebot/renovate#18119]
### What would you like Renovate to be able to do?

stakater/Reloader is using 

```
 image:
      name: stakater/reloader
      tag: v0.0.122
      pullPolicy: IfNotPresent
```
https://github.com/stakater/Reloader/blob/e0fcc3bfa6bce6ea9e1dd8b4b79760c512cec997/deployments/kubernetes/chart/reloader/values.yaml#L66

This is at the moment not supported
https://docs.renovatebot.com/modules/manager/helm-values/ 

### If you have any ideas on how this should be implemented, please tell us here.

Pls support this style of helm values

### Is this a feature you are interested in implementing yourself?

No

**Comment by teimyBr** [comment]
Renovate Task: 
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "postUpgradeTasks": {
    "commands": [ "helm dependency update" ],
    "fileFilters": [ "**/charts/*.tgz" ],
    "executionMode": "update"
  }
}
```
my values file: 

```
reloader:
  reloader:
    deployment:
      image:
        name: mycostumimageregistry/stakater/reloader
        tag: v0.0.121
```
compare to 
https://github.com/stakater/Reloader/blob/e0fcc3bfa6bce6ea9e1dd8b4b79760c512cec997/deployments/kubernetes/chart/reloader/values.yaml#L66

Helm update works and it updates 
- Chart.yaml 
- Chart.lock
- and the tgz file 

but it dont update the values file with the image tag. 

I want Renovate also to Update the values.yaml
