### ISSUE TITLE
Rancher's Fleet version handling problem

### ISSUE THREAD

**Issue by marthydavid** [renovatebot/renovate#18177]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

If I start to use a renovate to manage my Helm Chart versions for [fleet.rancher.io](https://fleet.rancher.io/), I'm only able to use the functionality at top level.

There is an option in fleet that you could manage helm chart version per cluster.
Here is an example fleet.yaml file:
```yaml

defaultNamespace: cattle-monitoring-system
dependsOn:
  - name: rancher-charts-fleet-rancher-charts-01-crd-monitoring
helm:
  releaseName: rancher-monitoring
  chart: rancher-monitoring
  repo: https://charts.rancher.io/
  version: "100.1.3+up19.0.3"
targetCustomizations:
- name: rke2
  clusterSelector:
    matchLabels:
      provider.cattle.io: rke2
      topology.kubernetes.io/region: budapest
      topology.kubernetes.io/zone: my-zone
  helm:
    version: "100.1.3+up19.0.3"
    valuesFiles:
      - rke2.yaml
targetCustomizations:
- name: rke2-2
  clusterSelector:
    matchLabels:
      provider.cattle.io: rke2
      topology.kubernetes.io/region: budapest
      topology.kubernetes.io/zone: my-zone-2
  helm:
    version: "100.1.2+up19.0.3"
    valuesFiles:
      - rke2-2.yaml
```
In this usecase renovate only uses 
```yaml
helm:
  version: 1.1
``` 

I trie to use it in my homelab repo:
https://github.com/marthydavid/homelab

### Relevant debug logs

<details><summary>Logs</summary>

```
        "packageFile": "fleet/rancher-charts/01-monitoring/fleet.yaml",
        "deps": [
          {
            "depType": "fleet",
            "datasource": "helm",
            "depName": "rancher-monitoring",
            "registryUrls": [
              "https://charts.rancher.io/"
            ],
            "currentValue": "100.1.3+up19.0.3",
            "depIndex": 0,
            "updates": [],
            "warnings": [],
            "versioning": "helm",
            "sourceUrl": "https://github.com/prometheus-community/helm-charts",
            "homepage": "https://github.com/prometheus-operator/kube-prometheus",
            "currentVersion": "100.1.3+up19.0.3",
            "fixedVersion": "100.1.3+up19.0.3"
          }
        ]
      },
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs
