### ISSUE TITLE
Flux: Support updating OCI helm charts

### ISSUE THREAD

**Issue by onedr0p** [renovatebot/renovate#18509]
### What would you like Renovate to be able to do?

Support OCI HelmRepositories for the Flux datasource, on the docs it lists this as not being supported.

https://docs.renovatebot.com/modules/manager/flux/

## Example `HelmRepository`

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 6h
  url: oci://ghcr.io/kyverno/charts
  type: oci
```

## Example `HelmRelease` that uses the above `HelmRepository`

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 6h
  releaseName: kyverno
  targetNamespace: kyverno
  install:
    createNamespace: true
  chart:
    spec:
      chart: kyverno
      version: 2.6.0
      interval: 6h
      sourceRef:
        kind: HelmRepository
        name: kyverno
  values:
    networkPolicy:
      enabled: true
```

### If you have any ideas on how this should be implemented, please tell us here.

Looks like under `.spec.type` of the `HelmRepository` we could query if it is `oci`, and also the `.spec.url` starts with `oci://`

### Is this a feature you are interested in implementing yourself?

Maybe
