### ISSUE TITLE
Pin GitLab include digests

### ISSUE THREAD

**Issue by l0b0** [renovatebot/renovate#18753]
### What would you like Renovate to be able to do?

To ensure reproducibility it would be good if the gitlabci-include manager supported pinning by the digest. Basically, instead of producing

```yaml
include:
- project: 'renovate-bot/renovate-runner'
  file: '/templates/renovate-dind.gitlab-ci.yml'
  ref: v10.14.2
```

it would produce

```yaml
include:
- template: Security/SAST.gitlab-ci.yml
- project: 'renovate-bot/renovate-runner'
  file: '/templates/renovate-dind.gitlab-ci.yml'
  ref: 326c8a25654e3bd8f9d9c3eb7d2e7646e0715c37 # v10.14.2
```

### If you have any ideas on how this should be implemented, please tell us here.

N/A

### Is this a feature you are interested in implementing yourself?

Maybe
