### ISSUE TITLE
Detect workspace.dependencies for rust/cargo

### ISSUE THREAD

**Issue by kjuulh** [renovatebot/renovate#18786]
### What would you like Renovate to be able to do?

A newer feature in rust, is that crates can inherit dependencies from a given workspace. 

This looks like this:

```
Cargo.toml
crates/some_crate/Cargo.toml
```

The topmost cargo.toml can define dependencies available to the rest of the crates

```toml
[workspace]
members = ["crates/some_crate"]

[workspace.dependencies]
serde = "some-version"
```

The some_crate cargo toml can then use this

```toml
[package]

#...

[dependencies]
serde = {workspace=true}
```

Right now the base config doesn't detect these by default, it can quite easily be done using the regex sourcer. But it would be awesome if it was allowed by default. 

### If you have any ideas on how this should be implemented, please tell us here.

This seems to be a feature complementary to the existing rust/cargo dependency checker and would probably live in the same space. Though it may be a different module, if we don't have handling for workspaces already.

### Is this a feature you are interested in implementing yourself?

Yes
