### ISSUE TITLE
Upgrade Terraform version in Atlantis projects

### ISSUE THREAD

**Issue by secustor** [renovatebot/renovate#18847]
### What would you like Renovate to be able to do?

Atlantis is a deployment tool which is used to apply Terraform IaC.     

It provides a option to define repository level configuration in a defined file ( `atlantis.yml` ).  
Here the to be used Terraform version can be defined. 

```yaml
version: 3
automerge: false
projects:
  - name: my-project
    dir: ./my-project
    terraform_version: v1.1.5
    autoplan:
      when_modified:
        - "*.tf"
        - "./**/*.tf*"
      enabled: true
  - name: my-other-project
    dir: ./my-other-project
    terraform_version: v1.2.0
    autoplan:
      when_modified:
        - "*.tf"
        - "./**/*.tf*"
      enabled: true
``` 

### If you have any ideas on how this should be implemented, please tell us here.

For this a new manager is needed to parse the file and extract the Terraform version.     
The datasource and most of the implementation can be reused from the `terraform-version` manager. 

### Is this a feature you are interested in implementing yourself?

Maybe
