### ISSUE TITLE
feature(manager/flux): Support helm-values for flux HelmRelease resource

### ISSUE THREAD

**Issue by 5cat** [renovatebot/renovate#18902]
### What would you like Renovate to be able to do?

I would like renovate to update the helm contents of `HelmRelease` resources in the `values:` key as it can be seen here https://fluxcd.io/flux/use-cases/helm/#customizing-your-release and here https://fluxcd.io/flux/guides/helmreleases/#define-a-helm-release

### If you have any ideas on how this should be implemented, please tell us here.

import the `extractPackageFile` or `findDependencies` from the `helm-values` manager, and run it on the `values: ` content from the `HelmRelease` resource and append it to the rest of the `deps`.

the `findDependencies` function doesnt have the `export` keyword next to it so i guess it is a no go. So will serialize the content back to string and feed it to  `extractPackageFile`, unless it is okay to export `findDependencies`.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by 5cat** [comment]
I will work on this feature after https://github.com/renovatebot/renovate/pull/18782 gets merged to avoid conflicts.

**Comment by onedr0p** [comment]
@5cat Unless I am missing something, Renovate already supports upgrading images in the values section of a HelmRelease. Was there some other feature you are missing?

**Comment by Kampfmoehre** [comment]
Hi there, is there a way to update the helm chart itself instead of the image used in the chart with Renovate? We re moving from GitLab agent to FluxCD. With GitLab agent we had Helm with the `helmCharts` property in a `kustomzation.yaml` which was working fine with Renovate.

Now with Flux we have something like this:
```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 17.8.0
  interval: 1h0m0s
  releaseName: redis
  ```
Which may be later overridden via a helm values file. I configured the paths in Renovate flux `fileMatch` and I can see in the Dashboard that renovate at least recognizes the base HelmRelease but seems unable to extract a version out of it. Is there a way to update that with Renovate?

**Comment by onedr0p** [comment]
@Kampfmoehre renovate supports flux helmrelease chart versions.

**Comment by Kampfmoehre** [comment]
@onedr0p Can you guide me to what I am doing wrong then? The above yaml is recognized by Renovate, but in the issue dashboard there is no version extracted and no update MR is generated for it.
![image](https://user-images.githubusercontent.com/14077931/228468426-f4409ffd-af9b-49a3-8d72-ceb1adb01623.png)

**Comment by Dariusch** [comment]
https://docs.renovatebot.com/modules/manager/flux/

```json5
{
  flux: {
    enabled: true,
    fileMatch: ["\\.yaml$"]
  }
}

```

**Comment by Kampfmoehre** [comment]
Yeah I followed that, I think the problem is, Renovate can't resolve the Helm repo url. I can see the following in the Renovate logs: `"skipReason": "unknown-registry"` but the HelmRelease is pointing to
```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://charts.bitnami.com/bitnami
```
which is working fine for Flux.
