### ISSUE TITLE
Templates: allow to specify custom templates fields 

### ISSUE THREAD

**Issue by Byh0ki** [renovatebot/renovate#19323]
### What would you like Renovate to be able to do?

A user would be able to provide a list of custom templates field to allow more options than the defaults values listed [here](https://docs.renovatebot.com/templates/)

### If you have any ideas on how this should be implemented, please tell us here.

In the case of the regexManagers, custom fields could be passed to renovate using capture groups

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by viceice** [comment]
Not possible, as the capture groups are not stored. Storing arbitrary values will work against our latest efforts to repo change detection.

**Comment by Byh0ki** [comment]
I see, my use case was that I need Renovate to generate multiples MRs for the same dependency in the same file (for example, one per geo), so I was thinking about an extra templates field to use in the `additionalBranchPrefix` setting. I'll continue to try other things then :+1:

**Comment by rarkins** [comment]
What type of fields? Any concrete examples?

**Comment by Byh0ki** [comment]
@rarkins I think that we commented at the same time :sweat_smile: 

I'll add a little bit of context, I have an argoCD applicationSet that will be deployed on multiple regions, I would like to be able to reference a different version for each region to deploy progressively and let Renovate create one MR for each region, something like that:
```
spec:
  generators:
    - list:
        elements:
          - region: eu
            version: 0.1.0
          - region: us
            version: 0.1.0
          - region: apac
            version: 0.1.0
```
But as far as I know, it's not possible as the branch name would be the same for each of the potentials MRs. So my idea was to use multiples regexManager and capture the region so that I could use them in `additionalBranchPrefix` templates.

**Comment by viceice** [comment]
i think you can capture groups and reuse them inside depName template, so you get different branches. pass real name for lookup inside packageName.

**Comment by Byh0ki** [comment]
Hello,

Thank you for your advice, it worked!

Here is the conf I used if anyone need to achieve something similar:
### renovate.json
```json
{
   "commitMessagePrefix": "{{packageName}}: ",
    "additionalBranchPrefix": "{{packageName}}-",
    "regexManagers": [
        {
            "fileMatch": [
                "^apps/*/*/.+\\.ya?ml$"
            ],
            "matchStrings": [
                "# renovate: registryURL=(?<registryUrl>.*?) packageName=(?<packageName>.*?)\n *- region: (?<depName>.*?)\n *version: (?<currentValue>.*)"
            ],
            "datasourceTemplate": "docker"
        }
    ]
}
```
### argocd-app.yml
```yaml
spec:
  generators:
    - list:
        elements:
          # renovate: registryURL=<my_registry_url> packageName=<docker_image_name>
          - region: eu
            version: 0.1.0
```

### Resulting branches/MRs/commits:
Branches: `renovate/<package_name>-<region>-0.x`
MRs titles/commit: `<docker_image_name>: Update eu Docker tag to v0.2.0`
