### ISSUE TITLE
Support for .pre-commit-config.yaml files

### ISSUE THREAD

**Issue by NaffanDroo** [renovatebot/renovate#19344]
### What would you like Renovate to be able to do?

Analyse dependencies in .pre-commit-config.yaml files, for example the below has multiple dependencies as well as `additional_dependencies` - which sometimes have a dependency clash if not all updated together.

```yaml
ci:
  autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys]
      - id: check-ast
      - id: debug-statements
      - id: check-docstring-first

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: python-check-blanket-type-ignore
      - id: python-check-blanket-noqa

  - repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
      - id: yesqa
        additional_dependencies: &flake8_deps
          - flake8-annotations==2.9.1
          - flake8-broken-line==0.4.0
          - flake8-bugbear==21.9.2
          - flake8-comprehensions==3.7.0
          - flake8-eradicate==1.2.0
          - flake8-no-pep420==1.2.0
          - flake8-quotes==3.3.1
          - flake8-simplify==0.14.2
          - flake8-tidy-imports==4.5.0
          - flake8-type-checking==1.1.0
          - flake8-typing-imports==1.11.0
          - flake8-use-fstring==1.3
          - pep8-naming==0.12.1

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
        exclude: '^(install|get)-poetry.py$'

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: "isort (python)"
        types: [python]
      - id: isort
        name: "isort (pyi)"
        types: [pyi]
        args: [--lines-after-imports, "-1"]

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: *flake8_deps

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        pass_filenames: false
        additional_dependencies:
          - types-dataclasses
          - types-requests

  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.16.0
    hooks:
      - id: validate_manifest

```

### If you have any ideas on how this should be implemented, please tell us here.

Analyse this with the same approach as you would for Python, except it should be treated as **separate** to the overall project dependencies - i.e. these versions are isolated from something like poetry.lock or pyproject.toml - if the repo is a python project.

Pre commit can be used with any language repo, but it's own plugins get installed into a separate virtual env so needs to be treated in isolation.

### Is this a feature you are interested in implementing yourself?

No
