### ISSUE TITLE
Rancher Fleet Multiple PRs when version is the same

### ISSUE THREAD

**Issue by atsai1220** [renovatebot/renovate#20157]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.119.3 (we pull the latest on cron)

### If you're self-hosting Renovate, select which platform you are using.

GitHub Enterprise Server

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

While using the Rancher Fleet module, Renovate will generate PRs for each `targetCustomization` target even if there is not a version specified for each `targetCustomization` in addition the the "root" level `helm.version` PR. The behavior of Fleet would be to take the "default" version under `helm.version` if a `helm.version` is not specified under `targetCustomization`.

Therefore it is redundant to create multiple PRs for each item under `targetCustomization` when the change is the same as the "root" `helm.version`'. Perhaps it is a configuration change on our end?

Here is a `fleet.yaml` for reproduction purposes

``` yaml
defaultNamespace: kube-system
name: cluster-autoscaler
helm:
  releaseName: rancher-cluster-autoscaler
  chart: cluster-autoscaler
  version: 9.23.0
  repo: https://kubernetes.github.io/autoscaler
  values:
    foo: yay

targetCustomizations:
- name: a
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: usw1-a
  helm:
    values:
      foo: daz
- name: b
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: usw1-b
  helm:
    values:
      foo: caz
- name: c
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: aws-usw2-c
  helm:
    values:
      foo: dar
- name: d
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: aws-usw2-d
  helm:
    values:
      foo: car
- name: e
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: aws-usw2-e
  helm:
    values:
      foo: baz
- name: f
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: aws-usw2-f
  helm:
    values:
      foo: bar
```

Here is the renovate configuration
``` json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "labels": ["dependencies"],
  "enabledManagers": ["fleet"]
}
```

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description
