### ISSUE TITLE
ansible kubernetes.core.helm is not tracked

### ISSUE THREAD

**Issue by yellowhat** [renovatebot/renovate#20352]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.132.0-slim

### If you're self-hosting Renovate, select which platform you are using.

gitlab.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitLab.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Hi,
I have noticed that in the latest versions, renovate is not keeping track of the helm chart version installed via ansible.
I have an helm chart definied in a ansible playbook:

```yaml
    - name: ArgoCD - Install
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo-cd
        chart_repo_url: https://argoproj.github.io/argo-helm
        chart_version: "5.19.12"
        namespace: "{{ argocd_namespace }}"
        create_namespace: true
        wait: true
        values: "{{ lookup('file', 'argocd_values.yaml') | from_yaml }}"
```

In my `renovate.json` I have added:

```json
    "ansible": {
        "fileMatch": [
            "bootstrap/[^/]+\\.ya?ml$"
        ]
    },
    "ansible-galaxy": {
        "fileMatch": [
            "bootstrap/[^/]+\\.ya?ml$"
        ]
    },
    "helmv3": {
        "fileMatch": [
            "bootstrap/[^/]+\\.ya?ml$"
        ]
    },
    "helm-values": {
        "fileMatch": [
            "bootstrap/[^/]+\\.ya?ml$"
        ]
    }
```

Any ideas?

Thanks

### Relevant debug logs

```
DEBUG: Failed to find required fields in Chart.yaml (repository=yellowhat-labs/mule, baseBranch=main)
       "fileName": "bootstrap/install.yaml"
```

### Have you created a minimal reproduction repository?

No reproduction repository
