### ISSUE TITLE
Update a file (e.g. CHANGELOG.md) within PR

### ISSUE THREAD

**Issue by jonathanweiss** [renovatebot/renovate#2094]
**What would you like Renovate to be able to do?**
Renovate should be able to be configured in a way to add entries to an existing file. In my particular use case I'm using [verify-changelog](https://www.npmjs.com/package/changelog-verify) in order to make sure that all changes to the codebase are documented in the change log.

**Describe the solution you'd like**
There should be some kind of hook (maybe similar to the way git hook work?) that allow users to run custom scripts when Renovate has done the work and is about to create the PR. It should be possible to automatically change file and add them to the commit.

This could be done using `renovate.json`:
```
{
  "extends": [
    "config:base"
  ],
  "hooks": {
    "before-commit": "./scripts/update-changelog.js"
  }
}
```

Would be great if `commitMessage` could be passed to that script as an argument.

**Describe alternatives you've considered**

If hooks is not a good idea to solve this, Renovate could update the change log itself.

```
{
  "extends": [
    "config:base"
  ],
  "updateChangelog":
    "enabled": true,
    "template": "{{{commitMessage}}}",
    "format": "keepachangelog"
  }
}
```

[If `format` is set to "keepachangelog"](https://keepachangelog.com/en/1.0.0/), Renovate should search for `## [Unreleased]` and check if the line `### Changed` exists below it. If this line exists, it should add an entry below it. If not, it should create this line.

I'm not quite sure how to handle different formats though...

**Comment by rarkins** [comment]
This would be another case of "Handle post-upgrade task" (#838). Happy to keep this open though because it's good to document individual requirements. I anticipate this type of thing to only be a medium-long term feature though due to the security concerns of running arbitrary code.

**Comment by ThibautMarechal** [comment]
I don't think that the postUpgradeTasks is capable of a such thing.
I also wanted to update the Changelog file of the repository. I don't think there is a way to get the pull-request information in the task. (correct me if I'm wrong)
What about parsing the command to the template engine to be able to put some arguments in the command.
That way, we could run a command like "npm run my-script --argA {{{commitMessage}}}" ?

**Comment by tisoft** [comment]
I am using this to auto-update my changelog:

.gitlab-ci.yml in my renovate update repo:
```
include:
  - remote: 'https://gitlab.com/renovate-bot/renovate-runner/-/raw/master/templates/_common.gitlab-ci.yml'

renovate:
  image: renovate/renovate
  variables:
    RENOVATE_EXTRA_FLAGS: --autodiscover --trust-level high --allow-post-upgrade-command-templating --allowed-post-upgrade-commands ^update_changelog.*
  before_script:
    # install chan to allow changelog updates
    - npm install @geut/chan
    # make chan available in path
    - export PATH="$PATH:$(pwd)/node_modules/.bin"
    # make our update_changelog script available in path
    - export PATH="$PATH:$(pwd)"
```

file update_changelog in my renovate update repo:
```
#!/usr/bin/env bash

# only run if changelog exists and does not already contain this specific version update
if test -f "CHANGELOG.md" && ! grep -q "$@" "CHANGELOG.md"; then
    chan changed -g 'Dependency Updates' "$@"
fi
```

renovate.json in my project repo:
```
 "packageRules": [
    {
      "$doc": "Update CHANGELOG.md",
      "postUpgradeTasks":  {
        "commands": [
           "update_changelog \"{{{depName}}} from {{{currentVersion}}} to {{{newVersion}}}\""
        ],
        "fileFilters": ["CHANGELOG.md"]
      },
      "packagePatterns": [
        ".*"
      ]
    }
  ]
```
Seems to be working fine.

 What I would like is limiting the changelog update to once per branch, but the following is not working:
```
 "packageRules": [
    {
      "$doc": "Update CHANGELOG.md",
      "postUpgradeTasks":  {
        "commands": [
           "update_changelog \"{{{commitMessage}}}\""
        ],
        "fileFilters": ["CHANGELOG.md"],
        "executionMode": "branch"
      },
      "packagePatterns": [
        ".*"
      ]
    }
  ]
```

`commitMessage` is not recognized as valid template. I also tried `newVersion`, `newValue`, `displayTo`, but all are empty for group updates, while the PR title has the correct version in them.
