### ISSUE TITLE
Renovate can no longer lookup private Docker packages

### ISSUE THREAD

**Issue by uhthomas** [renovatebot/renovate#20972]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

35.8.1@sha256:a92caaec84f48c41220166946aa21ae4d836ce828a2d848d2794bb55d69286c5

### If you're self-hosting Renovate, select which platform you are using.

Bitbucket Server

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

The latest version 35.8.1 cannot lookup private Docker dependencies. Previous versions (<35.0.0) seem to work okay. We have custom host rules for the private dependencies. It just says "failed to lookup dependency" and doesn't seem to actually attempt to look anything up. Renovate actively declines the existing PRs.

Possibly related?

https://github.com/renovatebot/renovate/discussions/20809

```yaml
  envList:
    - name: DOCKER_REDACTED_USERNAME
      value: devtools-renovate
    - name: DOCKER_REDACTED_PASSWORD
      valueFrom:
        secretKeyRef:
          name: renovate
          key: dockerRegistryPassword
```

Sorry for not proving a minimal reproduction. It's hard to do that in a public environment.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible
