### ISSUE TITLE
Convert Dependabot config to Renovate config when onboarding

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#21081]
### What would you like Renovate to be able to do?

Convert `dependabot.yml` to `renovate.json` when onboarding. This makes it easier for people to switch from Dependabot to Renovate, while keeping more-or-less the same configuration.

Some Dependabot concepts don't match Renovate concepts cleanly, in those cases do a best-effort conversion. The users's comments will be lost in the conversion process.

### Example source `dependabot.yml`

Taken from a real-world Dependabot config, I only changed the `reviewers` name.

```yaml
version: 2
updates:
  # Maintain dependencies for Ruby
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily" # Checks on Monday through Friday.

  # Maintain GitHub Action runners
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" # Checks on Monday through Friday.

    # Set default reviewer and labels
    reviewers:
      - "HonkingGoose"
    labels:
      - "dependabot"
```

### Example `renovate.json` conversion

Here's the one-to-one conversion:

```json5
{
  "reviewers": ["HonkingGoose"],
  "labels": ["dependabot"], // Edge-case: if convert to renovate label, breaks user scripts/actions
  "packageRules": [
    {
      "matchPackageNames": ["bundler"],
      "enabled": true,
      "extends": [":schedule:earlyMondays"]
    },
    {
      "matchPackageNames": ["github-actions"],
      "enabled": true,
      "extends": [":schedule:earlyMondays"]
    }
  ]
}
```

### Convert one-to-one or also nudge?

Do we want to convert one-to-on, or do we want to "nudge" users into using things like the Dependency Dashboard, `config:base` or `config:best-practices`?

### Resources for Dependabot config options

- [GitHub Docs, Configuration options for the dependabot.yml file](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)

### If you have any ideas on how this should be implemented, please tell us here.

> The dependabot.yml file has two mandatory top-level keys: `version`, and `updates`. You can, optionally, include a top-level `registries` key. The file must start with `version: 2`. [^quote]

1. Check if `version: 2` is present in the `dependabot.yml` file. If this version is not found: abort, and alert user with suitable error message.
1. Check if the two mandatory top-level keys are present: `version` and `updates`. If the keys are missing: abort, and alert user with suitable error message.
1. Convert _required_ fields:
    - `package-ecosystem`
    - `directory`
    - `schedule.interval`
1. Convert the other fields.

[^quote]: [GitHub Docs, Configuration options for the dependabot.yml file](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)

### Is this a feature you are interested in implementing yourself?

No

**Comment by HonkingGoose** [comment]
@jamietanna mentioned this `dependabot.yml` config file they'd want to get converted: [^source]

```
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
---
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Jenkins core is stuck on Groovy 2.4 due to JENKINS-53372, and CodeNarc
      # 1.x is the last version to support Groovy 2.4. Until Jenkins core moves
      # forward, this plugin is stuck on CodeNarc 1.x.
      - dependency-name: "org.codenarc:CodeNarc"
        versions: [">=2.0.0"]
      # Jenkins core is stuck on Groovy 2.4 due to JENKINS-53372, and Spock 1.x
      # is the last version to support Groovy 2.4. Until Jenkins core moves
      # forward, this plugin is stuck on Spock 1.x. See:
      # https://github.com/jenkinsci/job-dsl-plugin/pull/1273
      - dependency-name: "org.spockframework:spock-core"
        versions: [">=2.0", "1.3-groovy-2.5"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "job-dsl-plugin"
    schedule:
      interval: "weekly"
    ignore:
      # Breaks the appearance of the API viewer. See:
      # https://github.com/jenkinsci/job-dsl-plugin/pull/1270
      - dependency-name: "bootstrap"
        versions: [">=4.0.0"]
```

[^source]: https://github.com/jenkinsci/job-dsl-plugin/blob/6fe5d8e0f4b0085b9e0b86355f260ed40d63ccb7/.github/dependabot.yml
