### ISSUE TITLE
Check ".gitlab-ci.yml" for "helm install --version x.y.z" i.e. for newer chart versions

### ISSUE THREAD

**Issue by lathspell** [renovatebot/renovate#21128]
### What would you like Renovate to be able to do?

Helm charts are often installed using Gitlab ".gitlab-ci.yml" or similar Jenkins control files.:

```
deploy_dev:
  stage: deploy_dev
  image: alpine/helm:3.11.2
  script:
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm repo update
    - helm upgrade foo bitnami/postgresql --version=12.1.9 --install --debug --wait -f values.yaml
```

Here version "12.1.9" ist not the Postgres version but the version of the Helm chart that is used to deploy Postgres.

Currently Renovate Bot does not seem to check for updates of the helm chart.

### If you have any ideas on how this should be implemented, please tell us here.

It is probably a bit tricky to find and extract the version number from such a shell script but scanning for "helm install" or "helm upgrade" and then searching the same line for "--version=(.*)" should do the trick in most situations.

### Is this a feature you are interested in implementing yourself?

No
