### ISSUE TITLE
Renovate not detecting docker image in Kubernetes file if there's a comment behind the image name

### ISSUE THREAD

**Issue by mbleichner** [renovatebot/renovate#21218]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

35.24.6

### If you're self-hosting Renovate, select which platform you are using.

Gitlab

### Was this something which used to work for you, and then stopped?

I don't know

### Describe the bug

If there's a trailing comment in a line containing a docker image, renovate won't recognize and update the image tag. For example:
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - image: mattermost/mattermost-team-edition:7.8.1 # trailing comment
```

As soon as the comment is removed, the image will get picked up.

### Relevant debug logs

See comment below

### Have you created a minimal reproduction repository?

See comment below
