### ISSUE TITLE
ArgoCD matching within a helm template

### ISSUE THREAD

**Issue by patrickleet** [renovatebot/renovate#21460]
### What would you like Renovate to be able to do?

I am using argocd to create preview environments - the way this works is a preview chart in the codebase that creates an argocd `Application`.

When that argocd application does not contain any signs of being a template, it works as expected - able to update the referenced git tag or helm chart version - however, when there are signs of templating, it does not match.

I'm guessing this is by design, but I'd like a way to tell renovate that it's ok.

Here's an example that will not match:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.name }}-{{ .Values.pr }}-preview-environment
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-preview-envs
  source:
    path: .gitops/deploy/helm
    repoURL: https://github.com/MYORG/environment.git
    targetRevision: v0.12.0
    helm:
      version: v3
  destination:
    namespace: {{ .Values.name }}-{{ .Values.pr }}-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
```

In this example `metadata.name` uses values from the chart, and the `destination.namespace` as well. 

I still would like PRs for updates to the `targetRevision` of `https://github.com/MYORG/environment.git`, despite this, but that doesn't seem to happen.

Without the templates, the PR does get created.

### If you have any ideas on how this should be implemented, please tell us here.

I have not dug into the source for suggestions.

### Is this a feature you are interested in implementing yourself?

No
