### ISSUE TITLE
Gitlab: api project url encodes `/` as `%2F`

### ISSUE THREAD

**Issue by OrbisK** [renovatebot/renovate#21516]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

I am trying to get this working for the first time

### Describe the bug

i am setting up renovate in `gitlab-ci.yml`

```yaml
image: renovate/renovate

variables:
  RENOVATE_BASE_DIR: $CI_PROJECT_DIR/renovate
  RENOVATE_GIT_AUTHOR: Renovate Bot <...>
  RENOVATE_OPTIMIZE_FOR_DISABLED: 'true'
  RENOVATE_REPOSITORY_CACHE: 'true'
  LOG_LEVEL: debug


cache:
  key: ${CI_COMMIT_REF_SLUG}-renovate
  paths:
    - $CI_PROJECT_DIR/renovate

renovate:
  resource_group: production
  only:
    - schedules
  script:
    - renovate $RENOVATE_EXTRA_FLAGS
```

with `cofig.js`

```javascript
module.exports = {
        endpoint: 'https://self-hosted.com/api/v4/',
        platform: 'gitlab',
        persistRepoData: true,
        logLevel: 'debug',
        onboardingConfig: {
                'extends': [
                        "local>groups/subgroups/renovate/renovate-config"
                ],
        },
        autodiscover: true,
};

```

### Relevant debug logs

<details><summary>Logs</summary>
e.g.

```
DEBUG: http statistics (repository=<group>/<project>)
       "urls": {
         "https://singular-code.de/api/v4/projects/groups%2Fsubgroups%2Frenovate%2Frenovate-config (GET,404)": 1,
         "https://singular-code.de/api/v4/projects/<group>%2F.gitlab (GET,404)": 1,
         "https://singular-code.de/api/v4/projects/<group>%2F<project>/issues (GET,200)": 1,
         "https://singular-code.de/api/v4/projects/<group>%2F<project>/issues (POST,403)": 1,
         "https://singular-code.de/api/v4/projects/<group>%2F<project>/merge_requests (GET,200)": 1,
         "https://singular-code.de/api/v4/projects/<group>%2Frenovate-config (GET,404)": 1
       },
       "hostStats": {"singular-code.de": {"requestCount": 6, "requestAvgMs": 99, "queueAvgMs": 0}},
       "totalRequests": 6
```

</details>

### Have you created a minimal reproduction repository?

I have explained  a minimal reproduction
