### ISSUE TITLE
not update terraform modules

### ISSUE THREAD

**Issue by andruwa13** [renovatebot/renovate#21592]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

registry.hub.docker.com/renovate/renovate:latest

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

I am trying to get this working for the first time

### Describe the bug

**repository renovate:**

file **config.js**
```
module.exports = {
  "platform": "gitlab",
  "dependencyDashboardAutoclose": true,
  "repositoryCache": "enabled",
  "autodiscover": true,
  "extends": [
    "github>whitesource/merge-confidence:beta"
  ],
  "ignorePrAuthor": true,
  "onboardingConfig": { "extends": ["config:base", ":disableDependencyDashboard"] }
};

```

file **renovate.json**
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json"
}

```

file **.gitlab-ci.yml**

```

stages:
  - build
  - test

variables:
  RENOVATE_IMAGE: "registry.hub.docker.com/renovate/renovate:latest"
  RENOVATE_BASE_DIR: $CI_PROJECT_DIR/renovate
  RENOVATE_ENDPOINT: $CI_API_V4_URL
  
  RENOVATE_LOG_FILE: renovate-log.ndjson
  RENOVATE_AUTODISCOVER_FILTER: '${CI_PROJECT_ROOT_NAMESPACE}/**'
  RENOVATE_BINARY_SOURCE: install
  RENOVATE_LOG_FILE_LEVEL: debug
  LOG_LEVEL: info

workflow:
  rules:
    # exclude merge requests
    - if: $CI_MERGE_REQUEST_ID
      when: never
    # run the pipeline in other cases
    - when: always
.renovate-base:
  image: $RENOVATE_IMAGE
  # Cache downloaded dependencies and plugins between builds.
  # To keep cache across branches add 'key: "$CI_JOB_NAME"'
  # TODO (if necessary): define cache policy here
  cache:
    key: ${CI_COMMIT_REF_SLUG}-renovate
    paths:
      - renovate/cache/renovate/**


# (example) validator job
renovate-validator:
  extends: .renovate-base
  stage: build
  # force no dependency
  dependencies: []
  script:
    - renovate-config-validator

# dependency check job: on manual or schedule (dry-run otherwise)
renovate-depcheck:
  extends: .renovate-base
  stage: test
  # force no dependency
  dependencies: []
  variables:
    # dry-run by default
    RENOVATE_DRY_RUN: "true"
  script:
    - renovate $RENOVATE_EXTRA_FLAGS
  artifacts:
    when: always
    expire_in: 1d
    paths:
      - "$RENOVATE_LOG_FILE"
  rules:
    # not dry run on manual or schedule
    - if: '$CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web"'
      variables:
        RENOVATE_DRY_RUN: "false"
    - if: $RENOVATE_TOKEN

```

repository aws sg:

file security_group.tf

```
module "default_service_sg" {
  source  = "terraform-aws-modules/security-group/aws"
  version = "4.17.0"

  name        = "default Security Group"
  description = "Security group for default"
  vpc_id      = var.vpc_id
  tags        = var.default_tags

  ingress_with_cidr_blocks = [
    {
      rule        = "ssh-tcp"
      cidr_blocks = var.cidr_blocks_ssh_k8s_api
    },
    {
      rule        = "kubernetes-api-tcp"
      cidr_blocks = var.cidr_blocks_ssh_k8s_api
    },
  ]
}

```

### Relevant debug logs

<details><summary>Logs</summary>

```
INFO: Repository started (repository=***/modules/infrastructure)
       "renovateVersion": "35.53.0"
 INFO: Dependency extraction complete (repository=***/modules/infrastructure, baseBranch=master)
       "stats": {
         "managers": {
           "gitlabci": {"fileCount": 2, "depCount": 2},
           "gitlabci-include": {"fileCount": 2, "depCount": 2},
           "terraform": {"fileCount": 63, "depCount": 64}
         },
         "total": {"fileCount": 67, "depCount": 68}
       }
 WARN: GitHub token is required for some dependencies (repository=***/modules/infrastructure)
       "githubDeps": ["hashicorp/terraform"]
 INFO: Repository finished (repository=***/modules/infrastructure)
       "cloned": true,
       "durationMs": 7937
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above
