### ISSUE TITLE
Renovate not parsing version strings of the form "2023.04.25.204636"

### ISSUE THREAD

**Issue by jauderho** [renovatebot/renovate#21808]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I am trying to get this working for the first time

### Describe the bug

Renovate works great for the most part however, I just noticed that it is not parsing and taking action on the following compose.yml file. 

```
services:
    yt-dlp:
        container_name: yt-dlp
        #build: . 
        image: ghcr.io/jauderho/yt-dlp-nightly-builds:2023.04.22.232519@sha256:9e1d5d97677b7b33262b6d2d4f80b06f179ed3ddb0b4216d266dbc7fb2d1a457
        volumes:
            - './config:/config'
            - './data:/downloads'
```

Images are located at `https://github.com/jauderho/dockerfiles/pkgs/container/yt-dlp-nightly-builds` and `https://hub.docker.com/r/jauderho/yt-dlp-nightly-builds/`

As you can see, the most recent tag corresponds to `jauderho/yt-dlp-nightly-builds:2023.04.25.204636` (at time of bug report) which is several versions newer than what is documented in the compose.yml file. 

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above
