### ISSUE TITLE
Add Bitrise ( CI provider ) manager

### ISSUE THREAD

**Issue by secustor** [renovatebot/renovate#21957]
### What would you like Renovate to be able to do?

[Bitrise](https://bitrise.io/) is a platform which provides CI services for mobile apps. 

Bitrise uses step definitions which are defined in yaml files with the name `bitrise.yaml`. 

Users of Bitrise are: 
- reddit
- duolingo
- equinox
- ... 

### If you have any ideas on how this should be implemented, please tell us here.

Steps are hosted and managed by repos with following pattern: `https://github.com/bitrise-steplib/steps-{{step reference}}`.

```yaml
format_version: 11
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: android
app:
  envs:
  - MY_NAME: My Name
workflows:
  test:
    steps:
    - script@1.1.5:
        inputs:
        - content: echo "Hello ${MY_NAME}!"
```
Should result in a dependency with `github-release` datasource and `bitrise-steplib/steps-script` as `packageName`.

If `default_step_lib_source` deviates from `https://github.com/bitrise-io/bitrise-steplib.git`, `skipReason` should be set as we have no datasource to extract the folders in a generic way. 

### Is this a feature you are interested in implementing yourself?

Maybe
