### ISSUE TITLE
Add feature to validate and migrate presets in same repo

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#22525]
### Describe the proposed change(s).

Add a new config option to be added to repository configs which can say "Also check these preset files in this repo".

### Describe why we need/want these change(s).

Mainly so that migration can also be added.

One challenge is that presets can sometimes be embedded deeply. I'm wondering we can _not_ support this type of preset, because I would like to deprecate them anyway.

**Comment by Finkregh** [comment]
A workaround could be to use pre-commit with this config:

```yaml
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 38.18.17
    hooks:
      - id: renovate-config-validator
        args: [--strict]
        files: \.(json|json5)$
```

From that you can get these logs:
```
 WARN: Config migration necessary
       "oldConfig": {
...
       },
       "newConfig": {
...
```

It would be nice if it would be able to actually apply the proposed changes without manual intervention :/
