### ISSUE TITLE
Support digest updating in pre-commit manager

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#22567]
### Describe the proposed change(s).

Support updating digests in pre-commit manager. For example this:

```
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: a00caac4f0cec045f7f67d222c3fcd0744285c51 # frozen: 0.23.1
    hooks:
      - id: check-renovate
```

### Describe why we need/want these change(s).

See #22488

https://github.com/renovate-reproductions/22488
