### ISSUE TITLE
Support GitLab CI/CD components

### ISSUE THREAD

**Issue by secustor** [renovatebot/renovate#23431]
### Discussed in https://github.com/renovatebot/renovate/discussions/23424

<div type='discussions-op-text'>

<sup>Originally posted by **fgreinacher** July 18, 2023</sup>
### Tell us more.

CI/CD components are a new way to reuse CI logic within GitLab, see [upstream documentation](https://docs.gitlab.com/ee/ci/components/#use-a-component-in-a-cicd-configuration).

They look very similar to other `include`s and can probably be implemented in [the existing `gitlabci-include` datasource](https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/gitlabci-include/readme.md).

```yaml
include:
  - component: gitlab.com/gitlab-org/ruby-test@1.0
```

</div>

**Comment by viceice** [comment]
this should be added to the gitlabci manager, as the gitlab-include manager will be merged to it

**Comment by fgreinacher** [comment]
I started having a look at this. I think with the current syntax it might be challenging to implement: https://gitlab.com/groups/gitlab-org/-/epics/9897#note_1494759770.

**Comment by autotmp** [comment]
Does the directory structure update in 16.3 make the project/component distinction firm enough to move forward? Reference [Merge Request](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/127448).

**Comment by mbrodala** [comment]
Does someone maybe already have a working (read: tested) [custom manager](https://docs.renovatebot.com/modules/manager/regex/) for this which could be used in the meantime?

**Comment by lorenzogrv** [comment]
I'm researching about GitLab CI/CD components. I'm curious about why the include syntax is challenging. My understanding about:

```yaml
include:
   - component: $CI_SERVER_HOST/$CI_PROJECT_PATH/$EXAMPLE@$REF
```

where:

- `$CI_SERVER_HOST` points to GitLab instance, i.e. `gitlab.com`
- `$CI_PROJECT_PATH` points to namespace within domain, i.e. `iaigz/gitlab-ci`
- `$EXAMPLE` references to component name  - i.e. `lint-yaml-files`
- `$REF` references to repository history - tag, branch, or commit sha

Within the component definitions themselves, the YAML syntax is the usual Gitlab CI syntax, preceded with more YAML front-matter. any other `gitlabci-include` can contain that `spec:` syntax too, up from GitLab 16.x, as [it's usable from `include:local`](https://docs.gitlab.com/ee/ci/yaml/inputs.html#set-input-values-when-using-include)

```yaml
---
spec:
  inputs:
    job-stage:
      default: test
    search-path:
      default: .
    search-name:
      default: Dockerfile
---
lint-dockerfiles:
  image: hadolint/hadolint:v2.12.0-alpine
  stage: $[[ inputs.job-stage ]]
  script:
    - hadolint --version
    - find $[[ inputs.search-path ]] -type f -name $[[ inputs.search-name ]]
      -exec hadolint
      '{}'
      \+
```

The key part seems matching for the `- component: <host><repo><depName>@<version>` pattern. Note that version can't be specific to one component within the repository, but the same to every component for any given git reference
