### ISSUE TITLE
Support GitLab CI templates

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#24567]
### Describe the proposed change(s).

Details in https://github.com/renovatebot/renovate/discussions/24562

Reproduction repo forked to https://github.com/renovate-reproductions/24562

**Comment by mnacken** [comment]
Any news about the gitlabci-templates manager? We are highly interested in using this. Since switching to the new component structure, we have noticed that the Renovatebot no longer works properly.

Behaviour is exactly as described here: #24562

**Comment by viceice** [comment]
I think we don't need a new manager, as this are still gitlab pipeline configurations.

**Comment by mnacken** [comment]
You are right. I‘m fine if for example gitlabci manager will be supporting this 😄

**Comment by sapher** [comment]
Would be cool to integrate that, the new gitlabci component is a multi doc yaml file and the manager does not like that : 

`expected a single document in the stream, but found more`

**Comment by benedikt-bartscher** [comment]
> Would be cool to integrate that, the new gitlabci component is a multi doc yaml file and the manager does not like that :
> 
> `expected a single document in the stream, but found more`

see https://github.com/renovatebot/renovate/discussions/28386

**Comment by nejch** [comment]
Just to clarify the wording here, this is for GitLab CI/CD Components, despite the fact that they're confusingly placed in `templates/` in a component project. Templates are a more generic concept in GitLab CI.

AFAIK components are the only GitLab CI config with multi-document YAML formats.

https://docs.gitlab.com/ee/ci/components/

---

Related question: it might make sense to change the  gitlabci manager file match to support at least some of these component files by default. There are [two conventions](https://docs.gitlab.com/ee/ci/components/#directory-structure):
* `templates/my-component.yml`
* templates/my-component/template.yml`

Not sure about the first one but at least the second case I think could be included as it's pretty sure to be a GitLab component IMO. WDYT? Something like

```diff
export const defaultConfig = {
- fileMatch: ['\\.gitlab-ci\\.ya?ml$'],
+ fileMatch: ['\\.gitlab-ci\\.ya?ml$', '(^|/)templates/.+/template\\.yml$'],
};
```

/cc @fgreinacher

**Comment by viceice** [comment]
that's not enough, it will still fail to parse multi yaml docs

**Comment by outofrange** [comment]
> AFAIK components are the only GitLab CI config with multi-document YAML formats.
> 
> /cc @fgreinacher

Not sure if it matters, but I think _CI/CD components_ just means _a project with one or more template.ymls, optionally released to a catalog_.

Specifying _inputs_ in a multi-document YAML seems to be not directly related to components, as it's working with other _includes_ as well:

```yaml
include:
- local: templates/my-component-but-not-included-with-component/template.yml
  inputs:
    key: value
```

**Comment by fgreinacher** [comment]
> that's not enough, it will still fail to parse multi yaml docs

Multi-document YAML support has been added to the `gitlabci` manager with https://github.com/renovatebot/renovate/pull/28521.

**Comment by NINNiT** [comment]
We're also looking forward to GitLab CI/CD Component support!

```
spec:
  inputs:
    stage:
      default: build
    image:
      default: maven:3.9.6-eclipse-temurin-21
    mvn_cli_opts:
      default: "-s .m2/settings.xml --batch-mode"
---
mvn-build:
  image: $[[ inputs.image ]]
  stage: $[[ inputs.stage ]]
  artifacts:
    paths:
      - target/
  script:
    - mvn $[[ inputs.mvn_cli_opts ]] clean package -DskipTests
```
Please keep in mind that some components might allow users to set custom images and versions using an input variable - and provide a default if none is given. 

It would be great if renovate could handle that too.

**Comment by fgreinacher** [comment]
> We're also looking forward to GitLab CI/CD Component support!
> 
> 
> 
> ```
> 
> spec:
> 
>   inputs:
> 
>     stage:
> 
>       default: build
> 
>     image:
> 
>       default: maven:3.9.6-eclipse-temurin-21
> 
>     mvn_cli_opts:
> 
>       default: "-s .m2/settings.xml --batch-mode"
> 
> ---
> 
> mvn-build:
> 
>   image: $[[ inputs.image ]]
> 
>   stage: $[[ inputs.stage ]]
> 
>   artifacts:
> 
>     paths:
> 
>       - target/
> 
>   script:
> 
>     - mvn $[[ inputs.mvn_cli_opts ]] clean package -DskipTests
> 
> ```
> 
> Please keep in mind that some components might allow users to set custom images and versions using an input variable - and provide a default if none is given. 
> 
> 
> 
> It would be great if renovate could also handle those cases - but that might be tricky/impossible?

@NINNiT This is not something Renovate can/should handle in a generic way. IMO this is a perfect use case for [a custom RegEx manager](https://docs.renovatebot.com/modules/manager/regex/).

**Comment by nejch** [comment]
> > that's not enough, it will still fail to parse multi yaml docs
> 
> Multi-document YAML support has been added to the `gitlabci` manager with #28521.

It seems like once this is also added to the `gitlabci-include` manager, CI components will be fully supported. Currently the include parser still fails on multi-doc for `gitlabci-include`.

**Comment by jduepmeier** [comment]
Gitlab CI/CD components can be included via the components parameter (https://docs.gitlab.com/ee/ci/components/#use-a-component).

```yaml
include:
  - component: $CI_SERVER_FQDN/my-org/security-components/secret-detection@1.0.0
    inputs:
      stage: build
```

Does this issue include the update of the component reference?
