### ISSUE TITLE
Composer not found

### ISSUE THREAD

**Issue by Jamesking56** [renovatebot/renovate#2611]
**What Renovate type are you using?**
Renovate Docker: https://hub.docker.com/r/renovate/renovate/

**Describe the bug**
`composer` is now suddenly missing from Docker image.

**Did you see anything helpful in debug logs?**

**To Reproduce**
1.  `docker run renovate/renovate --platform gitlab --timezone Europe/London --token <token> <repo with composer deps>`
2. Notice that `composer` is missing:

```
Command failed: composer update laravel-notification-channels/telegram --ignore-platform-reqs --no-ansi
/bin/sh: composer: not found
 `composer update laravel-notification-channels/telegram --ignore-platform-reqs --no-ansi` (exited with error code 127)
```

**Expected behavior**
`composer` is found and run to update deps.

**Screenshots**
N/A

**Additional context**
I'm using GitLab with GitLab CI to run the renovate container, here is my `.gitlab-ci.yml`:

```yml
image: docker:latest

services:
  - docker:dind

stages:
  - renovate

renovate:
  stage: renovate
  script:
    - docker pull renovate/renovate
    - docker run renovate/renovate --platform gitlab --timezone Europe/London --token $RENOVATE_TOKEN <repo1> <repo2> <repo3>
```

**Comment by rarkins** [comment]
Another option is to stop building Renovate based on the node alpine image and instead build it based on the PHP one and then add node.js, which seems easier. But ideally we have a better way to copy in all the files we need using multi-stage builds.

**Comment by Jamesking56** [comment]
Well I want to check my composer dependencies, I didn't realise its not enabled by default. So I've worked around this by making my own renovate `Dockerfile` which GitLab CI now builds and uses:

```dockerfile
FROM composer/composer:alpine as composer

FROM renovate/renovate:latest
COPY --from=composer /usr/local/bin/composer /usr/local/bin/composer
```

Now my `.gitlab-ci.yml` looks like this:

```yml
image: docker:latest

services:
  - docker:dind

stages:
  - renovate

renovate:
  stage: renovate
  script:
    - docker build -t renovate .
    - docker run renovate --platform gitlab --timezone Europe/London --token $RENOVATE_TOKEN <repo1> <repo2> <repo3>
```
