### ISSUE TITLE
manager/pdm: do not add dep group to depName

### ISSUE THREAD

**Issue by secustor** [renovatebot/renovate#27535]
PDM is not uses as expected and this creates for the user unexpected behaviour. 

Currently dependencies which are located in a dependency group get the group name as prefix. This leads to that these dependencies are not group automatically with similar deps in other groups or managers. 

```toml
[tool.pdm.dev-dependencies]
dev = ["pytest==8.0.0"]
```

e.g. https://github.com/renovatebot/renovate/discussions/27372
