### ISSUE TITLE
Validate relative links with docs tests

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#28561]
### Describe the proposed change(s).

Creating this issue as asked by @viceice in this comment:

- https://github.com/renovatebot/renovate/pull/27583#issuecomment-2068166761

We should check if all relative links in our Markdown files (`*.md`) are correct, this makes sure that the published docs has working links. This check should be automated, via tests or configuration of existing tools.

The `mkdocs` dependency in our `renovatebot/renovatebot.github.io` repository already warns us about _some_ bad link types, here's the relevant snippet: [^1]

```yaml
# Build settings

# Halt processing when a warning is raised when building the docs.
# https://www.mkdocs.org/user-guide/configuration/#strict
strict: true

# Use MkDocs maintainer's recommended strictness settings for link validation.
# https://www.mkdocs.org/user-guide/configuration/#validation

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
```

`mkdocs` already warns about bad relative links, but we only see that warning output when we (or Renovate) create a new docs build in the docs repo... So that warning can't help you decide if a PR is good to merge. :upside_down_face: 

We have a [`documentation.spec.ts` file](https://github.com/renovatebot/renovate/blob/main/test/documentation.spec.ts) that has some docs specific tests. I don't see code that tests for relative links?

[^1]: [`mkdocs.yml` config file on `renovatebot.github.io` repository](https://github.com/renovatebot/renovatebot.github.io/blob/9de62bf4611635235f4ffcbc4f4fcdb75edbc14c/mkdocs.yml#L1-L13)
