### ISSUE TITLE
Let `flux` manager update tags and digests (`flux` currently ignores tags)

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#29768]
### Describe the proposed change(s).

Renovate's `flux` manager does _not_ support updating tags _and_ digests yet:

https://github.com/renovatebot/renovate/blob/8975c9bda67880fd4c91bdc32534e24f98a90e0e/lib/modules/manager/flux/extract.ts#L214

`@viceice` says Renovate should support updating tags _and_ digests. `@viceice` will look next week if there's an easy way to add support.

Related Discussion:

- #29521

**Comment by onedr0p** [comment]
@HonkingGoose @jfroy keep in mind that tag and digest are mutally exclusive so I don't think there's really anything to do here

https://fluxcd.io/flux/components/source/ocirepositories/#reference

https://fluxcd.io/flux/components/source/ocirepositories/#digest-example

> This field takes precedence over all other fields.

**Comment by onedr0p** [comment]
Maybe there could be support added for like how GHA is done, by renovate putting the version next to the digest in a comment? e.g.

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 1h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/kyverno/charts/kyverno
  ref:
    digest: sha256:d363081e45627aa396d6c8cb2d4ee59fcb7a79c223a967ae601c8c8ba4e7b7f3 # 3.2.3
```

**Comment by onedr0p** [comment]
So I am guessing that the `tag` field in the YAML can just be used as a placeholder for the tag the digest relates to?

e.g.

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 1h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/kyverno/charts/kyverno
  ref:
    tag: 3.2.3 # <- Ignored by flux but renovate uses it to keep track of the digest tag below
    digest: sha256:d363081e45627aa396d6c8cb2d4ee59fcb7a79c223a967ae601c8c8ba4e7b7f3
```
