### ISSUE TITLE
Validate fetched presets

### ISSUE THREAD

**Issue by RahulGautamSingh** [renovatebot/renovate#30968]
The config validator CI job outputs:

```
Using docker image sha256:c6431e4a0b69c93b85047101fcfd546fa510a998faa60985e099a7c38e0477b1 for ghcr.io/renovatebot/renovate:38.47.0@sha256:ad47f0412f2c49ec7da77c0c32ff3f6a4129591e465860b86fcc9596e078fb24 with digest ghcr.io/renovatebot/renovate@sha256:ad47f0412f2c49ec7da77c0c32ff3f6a4129591e465860b86fcc9596e078fb24 ...
$ renovate-config-validator $RENOVATE_CONFIG_VALIDATOR_EXTRA_FLAGS
 INFO: Validating renovate.json
DEBUG: Checking for config file in config.js
DEBUG: No config file found on disk - skipping
 INFO: Config validated successfully
```

`.gitlab-ci.yml` (very lightly redacted):

```yaml
include:
  - project: clients/client/infra/ci-templates
    ref: main
    file: workflow-stages.yml

  - project: clients/client/infra/ci-templates
    ref: main
    file: prettier.yml

  - remote: https://gitlab.com/renovate-bot/renovate-runner/-/raw/v18.23.0/templates/renovate.gitlab-ci.yml

  - remote: https://gitlab.com/renovate-bot/renovate-runner/-/raw/v18.23.0/templates/renovate-config-validator.gitlab-ci.yml

variables:
  LOG_LEVEL: debug
  RENOVATE_DETECT_HOST_RULES_FROM_ENV: "true"
  RENOVATE_GIT_AUTHOR: Renovate Bot <renovate-bot@company.com>
  RENOVATE_ONBOARDING_CONFIG: '{"$$schema": "https://docs.renovatebot.com/renovate-schema.json", "extends": ["local>clients/client/infra/renovate-runner"]}'
  RENOVATE_REPOSITORIES: <list of space-separated repo paths>
```

I would need to configure the config validator to not only check `renovate.json`, but also `default.json` (used by all other packages) and other, more specific includes.

I.e., the actual projects import these files, which appear to be unchecked by the validator:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "local>clients/client/infra/renovate-runner",
    "local>clients/client/infra/renovate-runner:typo3-12",
    "local>clients/client/infra/renovate-runner:typo3-extension"
  ]
}
```

_Originally posted by @LeoniePhiline in https://github.com/renovatebot/renovate/discussions/30967#discussioncomment-10421389_

The fetched presets are not being validated before being used. This can cause silent problems and waste time during debugging for minor issues in config. Better to handle this when presets are resolved.

Will need to do separately for repo config and admin config as they are reolved at different stages.
