### ISSUE TITLE
Poetry: support multiple constraint dependencies

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#31406]
### Describe the proposed change(s).

Support multiple-constraint dependencies like this:

```
[tool.poetry.dependencies]
numpy = [
  {python = "^3.9", version = "^1.26"},
  {python = "^3.8, <3.12", version = "^1.24"}
]
```

Reproduction repo: https://github.com/renovate-reproductions/31339
Discussion ref: https://github.com/renovatebot/renovate/discussions/31339

**Comment by goseind** [comment]
We're facing similar issues with multiple constraint dependencies when it comes to platforms with custom source:

`pyproject.tml`:
```toml
torch = [
    { platform = "darwin", version = "^2.1.0", source = "pypi" },
    { platform = "win32", version = "^2.1.0+cpu", source = "pytorch" },
    { platform = "linux", version = "^2.1.0+cpu", source = "pytorch" },
]

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"
```

Renovate output:

```bash
{
   "datasource": "pypi",
   "skipReason": "multiple-constraint-dep",
   "depName": "torch",
   "depType": "dependencies",
   "lockedVersion": "2.4.1+cpu",
   "updates": [],
   "packageName": "torch"
 }
```
