### ISSUE TITLE
CircleCI Orb with a range is skipped as "unsupported-value"

### ISSUE THREAD

**Issue by miyajan** [renovatebot/renovate#3161]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
[This article](https://renovatebot.com/blog/automatically-update-circleci-orbs) says

> if you have defined your Orb with a “range”, then Renovate creates a PR to “pin” it (e.g. from cypress-io/cypress@1 to cypress-io/cypress@1.2.0)

I wrote `.circleci/config.yml` like below.

```yaml
version: 2.1

orbs:
  cypress: cypress-io/cypress@1.5

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.0-node-browsers
    steps:
      - run: echo "hoge"

workflows:
  test:
    jobs:
      - test
```

But no PRs to pin `cypress-io/cypress` are created.

**Did you see anything helpful in debug logs?**

On Renovate Dashboard, "1.5" is skipped as "unsupported-value".

```text
...
DEBUG: Dependency cypress has unsupported value 1.5
...
DEBUG: packageFiles with updates
{
  "config": {
    "circleci": [
      {
        "packageFile": ".circleci/config.yml",
        "manager": "circleci",
        "deps": [
          {
            "depType": "orb",
            "depName": "cypress",
            "currentValue": "1.5",
            "lineNumber": 3,
            "purl": "pkg:orb/cypress-io/cypress",
            "commitMessageTopic": "{{{depName}}} orb",
            "versionScheme": "semver",
            "rangeStrategy": "pin",
            "updates": [],
            "warnings": [],
            "skipReason": "unsupported-value"
          },
...
```

**To Reproduce**

https://github.com/miyajan/reproduce-renovate-issue

**Expected behavior**
A PR to pin `cypress-io/cypress` to `1.5.1` is created.
