### ISSUE TITLE
Private registry does not work

### ISSUE THREAD

**Issue by Journerist** [renovatebot/renovate#3200]
**What Renovate type are you using?**
CLI / Docker container

**Describe the bug**
Renovate does not use my npm proxy. My .npmrc looks like:

```
registry=https://nexus.corp.de/repository/corp-npm-all/
strict-ssl=false
```

and my docker file looks like:

```
version: '3'
services:
  renovate:
    image: "renovate/renovate:latest"
    command: "--token aabbbccc --endpoint https://github.corp.com/api/v3/ --dry-run false"
    environment:
     - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
     - ${PWD}/config.js:/usr/src/app/config.js
     - ${PWD}/.npmrc:/home/node/.npmrc
```

**Did you see anything helpful in debug logs?**
No

**To Reproduce**
Setup docker compose file, config repos, and check lock-file paths

**Expected behavior**
I want to always use the given proxy url and urls in the package-lock.json should never contain the public repository url.

**Additional context**
It worked a few weeks ago. After fetching the new Docker image it seems to stop working. Anyhow, I want to understand where I can configure the default proxy url. Putting an .npmrc in the repo is not suitable for me, because it seems like this is a more environment related file and should not be in the repo itself. Workarounds like`strict-ssl=false` should not be checked in.
