### ISSUE TITLE
When using yaml aliases, CircleCI executor docker images not updated

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#34221]
### Discussed in https://github.com/renovatebot/renovate/discussions/33657

<div type='discussions-op-text'>

<sup>Originally posted by **yanns** January 17, 2025</sup>
### How are you running Renovate?

A Mend.io-hosted app

### Please tell us more about your question or problem

Minimal reproduction: https://github.com/yanns/circleci-executors

When using yaml aliases, the docker images used for CircleCI executors are not updated anymore.
```
aliases:
  - &working_directory ~/circleci-executors

executors:
  rust-docker:
    docker:
      - image: cimg/rust:1.82.0
    working_directory: *working_directory
```

### Logs (if relevant)

```
EBUG: Error extracting circleci images
{
  "err": {
    "message": "Schema error",
    "stack": "ZodError: Schema error\n    at Object.get error [as error] (/usr/local/renovate/node_modules/.pnpm/zod@3.24.1/node_modules/zod/lib/types.js:55:31)\n    at ZodObject.parse (/usr/local/renovate/node_modules/.pnpm/zod@3.24.1/node_modules/zod/lib/types.js:131:22)\n    at parseSingleYaml (/usr/local/renovate/lib/util/yaml.ts:136:17)\n    at Object.extractPackageFile (/usr/local/renovate/lib/modules/manager/circleci/extract.ts:61:35)\n    at extractPackageFile (/usr/local/renovate/lib/modules/manager/index.ts:75:9)\n    at getManagerPackageFiles (/usr/local/renovate/lib/workers/repository/extract/manager-files.ts:58:43)\n    at /usr/local/renovate/lib/workers/repository/extract/index.ts:57:28\n    at async Promise.all (index 0)\n    at extractAllDependencies (/usr/local/renovate/lib/workers/repository/extract/index.ts:54:26)\n    at extract (/usr/local/renovate/lib/workers/repository/process/extract-update.ts:160:28)\n    at extractDependencies (/usr/local/renovate/lib/workers/repository/process/index.ts:158:26)\n    at Object.renovateRepository (/usr/local/renovate/lib/workers/repository/index.ts:71:9)\n    at attributes.repository (/usr/local/renovate/lib/workers/global/index.ts:206:11)\n    at start (/usr/local/renovate/lib/workers/global/index.ts:191:7)\n    at /usr/local/renovate/lib/renovate.ts:19:22",
    "issues": {
      "aliases": {
        "0": "Expected object, received string"
      }
    }
  }
  "packageFile": ".circleci/config.yml"
}
```
</div>

**Comment by jamesbassett** [comment]
It looks like there was an incorrect assumption when changing the YAML parsing of CircleCI configs (i.e. [here](https://github.com/renovatebot/renovate/blob/b5ff90f2bd9bba668908852a5a6093630637e552/lib/modules/manager/circleci/schema.ts#L4)) that `aliases` is a standard configuration key and contains a docker image.

It's not part of the [CircleCI reference](https://circleci.com/docs/configuration-reference/) and is used (in renovate's tests, as well as in my build) as a place to store [reusable YAML anchors](https://circleci.com/docs/introduction-to-yaml-configurations/#anchors-and-aliases).

I'm using it as a reusable YAML anchor

```
aliases:
  - &notify_on_failure
    slack/notify:
      channel: my-channel
      branch_pattern: main
      event: fail
```

So I can use it multiple times in my build

```
jobs:
  build:
    steps:
      - another-build-step
      - *notify_on_failure
```

But getting the attached error log (as this doesn't conform to the zod schema).

The workaround in the meantime is to rename this key to anything else, i.e. `anchors`
