### ISSUE TITLE
Renovate doesn't update docker-compose with yaml anchors anymore

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#34369]
### Discussed in https://github.com/renovatebot/renovate/discussions/32918

<div type='discussions-op-text'>

<sup>Originally posted by **mueller-ma** December  5, 2024</sup>
### How are you running Renovate?

A Mend.io-hosted app

### Please tell us more about your question or problem

In the past Renovate had no problems when a Docker compose file had yaml anchors. Now it doesn't extract the image anymore:
- https://github.com/mueller-ma/renovate-reproduce/blob/main/docker-compose.yml
- https://github.com/mueller-ma/renovate-reproduce/issues/2

`docker compose` can use and parse this docker-compose file. You can see that docker includes the `image` in both services:

````
$ docker compose -f docker-compose.yml config
name: tmp
services:
  service-a:
    environment:
      SERVICE: a
    image: debian:11
    networks:
      default: null
  service-b:
    environment:
      SERVICE: b
    image: debian:11
    networks:
      default: null
networks:
  default:
    name: tmp_default
x-shared_setting:
  image: debian:11
````

### Logs (if relevant)

<details><summary>Logs</summary>

```

DEBUG: packageFiles with updates
{
  "baseBranch": "main"
  "config": {
    "docker-compose": [
      {
        "deps": [],
        "packageFile": "docker-compose.yml"
      }
    ]
  }
}

```

</details>
</div>

Reproduction: renovate-reproductions/32918

**Comment by vic1707** [comment]
As added context extracted from the discussion

it appears that adding 
```yml
%YAML 1.1
---
```
At the top of the file help get back _some_ anchors capabilities.

With the fix, merging maps seems to be parsed correctly
working example: 
```yml
%YAML 1.1
---
x-GICKUP: &GICKUP
    image: docker.io/buddyspencer/gickup:0.10.36

services:
    gickup:
        <<: *GICKUP
```
while using a scalar alias for a single value instead of merging a mapping doesn't work.
```yml
%YAML 1.1
---
x-GICKUP: &GICKUP docker.io/buddyspencer/gickup:0.10.36

services:
    gickup:
        image: *GICKUP
```
