### ISSUE TITLE
Renovate 39.177-full Docker image is actually the slim/non-full image

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#34429]
### Discussed in https://github.com/renovatebot/renovate/discussions/34412

<div type='discussions-op-text'>

<sup>Originally posted by **davecheesefish** February 23, 2025</sup>
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab, using Docker image renovate/renovate:39.177-full

### Please tell us more about your question or problem

The "full" version of the Docker image for Renovate 39.177.* has Node installed but not npm. npm was present in previous versions.

This is causing the `renovate/artifacts` job (which updates the package-lock.json file) to fail with the error `/bin/sh: 1: npm: not found`.

Here is my .gitlab-ci.yml file which runs Renovate:

```yml
stages:
  - renovate
  - dry-run

.default-renovate-job:
  image: renovate/renovate:39.177-full

renovate:
  stage: renovate
  extends: .default-renovate-job
  script:
    - renovate
  only:
    - schedules

dry-run:
  stage: dry-run
  extends: .default-renovate-job
  script:
    - node --version
    - npm --version
    - renovate --dry-run
  only:
    - develop
```

In the dry-run job I've added `node --version` and `npm --version` to check for the presence of both. When using the `renovate/renovate:39.177-full` image the Node version check passes but the npm one fails, not being able to find npm. If I downgrade to `renovate/renovate:39-176-full` both pass and Renovate runs successfully.

### Logs (if relevant)

_No response_</div>
