### ISSUE TITLE
Add drone CI support

### ISSUE THREAD

**Issue by btkostner** [renovatebot/renovate#3460]
**What would you like Renovate to be able to do?**
RenovateBot should be able to update Drone CI configuration with new docker image tags.

**Describe the solution you'd like**
RenovateBot updates the `.drone.yml` file just like a `.travis.yml` file or `Dockerfile`

**Additional context**
The default Drone CI configuration is a yaml file set in `.drone.ci`. The code will most likely look a lot like the `travis` manager.

A `drone.yml` file looks like this and may have multiple pipelines:
```yaml
---

kind: pipeline
name: Test

steps:
  - name: mix
    image: elixir:1.8.1-alpine
    environment:
      DB_HOST: mysql
      REDIS_HOST: redis
    commands:
      - apk add --no-cache gcc g++ git imagemagick libc-dev libmcrypt-dev make
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix test

services:
  - name: mysql
    image: mysql:5.7.24
    ports:
      - 3306

  - name: redis
    image: redis:alpine
    ports:
      - 6379
```
