### ISSUE TITLE
Add support for `actions/setup-node` with:node-version` updates

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#34658]
### Describe the proposed change(s).

The `github-actions` manager should be updated to extract the `node-version` value when using [actions/setup-node](https://github.com/actions/setup-node).

Example syntax:

```yaml
- uses: actions/setup-node@v3
  with:
    node-version: '16.x'
```

The `datasource` for this should be `github-releases` and the `depName/`packageName` set to `actions/node-versions`. `versioning` should be set to `node`.
