### ISSUE TITLE
GitLab CI: Renovate does not detect the extended image syntax

### ISSUE THREAD

**Issue by fgreinacher** [renovatebot/renovate#3680]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Renovate does not detect the [extended syntax for docker images in GitLab CI yml files](https://docs.gitlab.com/ce/ci/docker/using_docker_images.html#overriding-the-entrypoint-of-an-image).

**To Reproduce**

1. Create a `.gitlab-ci.yml` file in an empty repo with the following contents:

```yml
image:
        name: renovate/renovate:16.10.8@sha256:55ae14c55b18cdef8530c4cc0676aa442c2f83cafa649757fa54a0358433ff10
        entrypoint: [""]
```
2. Run Renovate against the repository with this file

**Expected behavior**
Renovate should detect the image reference and offer an upgrade

**Actual behavior**
Renovate does not detect the image reference with a message like this:

> INFO: Repository has no package files - skipping (repository=`XYZ`)

**Additional information**

The regex at https://github.com/renovatebot/renovate/blob/master/lib/manager/gitlabci/extract.js#L13 does not seem to understand this syntax.
