### ISSUE TITLE
[kubernetes] Support for updating docker images defined in custom CRD's

### ISSUE THREAD

**Issue by grzesuav** [renovatebot/renovate#3906]
**What would you like Renovate to be able to do?**
Currently kubernetes updater (https://github.com/renovatebot/renovate/tree/master/lib/manager/kubernetes) looks for specific `image` tag inside kubernetes `yaml` file.

But here is a case when we have CRD (like PrometheusCRD defined by Prometheus Operator - https://github.com/coreos/prometheus-operator/tree/master/example/prometheus-operator-crd) which have custom field to define version (https://github.com/coreos/prometheus-operator/blob/master/example/prometheus-operator-crd/prometheus.crd.yaml#L3315).

Example of CRD:
```
--
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: main
  namespace: namespace
spec:
  externalUrl: https://prometheus-url
  replicas: 2
  version: v2.9.1
  scrapeInterval: 5s
  evaluationInterval: 5s
```
currently this `version` will not be picked by renovate for update

**Describe the solution you'd like**
I would like to have possibility to extend configuration of plugin with map like :+1: 
`kind-and-path-to-field -> image which is used there`

example:
`Prometheus:spec:version->mirror-quay.docker.tech.lastmile.com/prometheus/prometheus:v2.9.1`

which would tell kubernetes extractor how to handle it

**Describe alternatives you've considered**
Do not have any idea

**Additional context**
None, can be provided if necessary.
