### ISSUE TITLE
Buildkite plugins not updating

### ISSUE THREAD

**Issue by shavo007** [renovatebot/renovate#3956]
**What Renovate type are you using?**
Renovate Pro?

**Describe the bug**

I added in the preset for buildkite, but i receive no PRs for updates to the plugins.

From looking at renovate logs, it may be due to the fact I have an alias for my shared plugins.

**To Reproduce**

```yaml

plugins: &plugins #alias for shared plugins
  seek-oss/aws-sm#v0.0.3:
    env:
      NPM_TOKEN: "arn:aws:secretsmanager:ap-southeast-2:xxx:secret:npm/xxx"
  seek-oss/private-npm#v1.1.1:
    env: "NPM_TOKEN"
  docker#v3.0.1:
    volumes:
      - /app/node_modules
    workdir: "/app"  
  seek-oss/docker-ecr-cache#v1.1.4:
    dockerfile: Dockerfile-builder
    cache-on:
      - yarn.lock   
```
**Expected behavior**

Get PRs for new versions of the plugins
