### ISSUE TITLE
Grouping for gitlabci and gitlabci-include not working

### ISSUE THREAD

**Issue by svenbs** [renovatebot/renovate#4229]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Renovate does not group gitlabci included updates and gitlabci updates despite a groupingRule in the packageRules.
Instead it creates two single prs.
`update docker-registry.tld/xyz docker tag to v5.2.1`
`update dependency xyz to v5.2.1`

**Did you see anything helpful in debug logs?**
-

**To Reproduce**

1.  Create repository with a .gitlab-ci.yml containing at least following lines:
```
image: docker-registry.tld/xyz:vN.N.N

include:
  - project: 'xyz'
    ref: v5.2.1
    file: '/templates/gitlab-ci-template.yml'
```
2. Configure renovate to group those changes and use same commitType:
```
module.exports = {
  "packageRules": [
    {
      "packagePatterns": ["xyz"],
      "groupName": "xyz group",
      "semanticCommitType": "fix"
    },
  ]
}
```

**Expected behavior**
Renovate should create a single MergeRequest for updates of image tags and gitlabci-includes for the same version.
