### ISSUE TITLE
Support default environment variable values in docker-compose

### ISSUE THREAD

**Issue by l-ross** [renovatebot/renovate#4635]
**What would you like Renovate to be able to do?**
In docker-compose files you can use environment variables to specify config and provide a default value. For example:

```yml
version: "3.7"
services:
  redis:
    image: ${REDIS_IMAGE:-redis:5.0.0@sha256:abcd}
```

If the environment variable REDIS_IMAGE is defined then that value is used, otherwise it falls back to the default value. More information can be found [here](https://docs.docker.com/compose/compose-file/#variable-substitution).

I would like renovate to be able to update the default value for image lines in docker-compose files.

**Describe the solution you'd like**
When renovate runs if it finds the following line:
`image: ${REDIS_IMAGE:-redis:5.0.0@sha256:abcd}`
and there is a 5.0.1 image of redis available then it should update the above line to:
`image: ${REDIS_IMAGE:-redis:5.0.1@sha256:1234}`

The environment variable is left alone and is ignored as far as renovate is concerned.

**Describe alternatives you've considered**
Within renovate I don't believe there are alternatives.

Within docker-compose itself you could split this:

```yml
version: "3.7"
services:
  redis:
    image: ${REDIS_IMAGE:-redis:5.0.0@sha256:abcd}
```

in to 2 separate compose files:
```yml
# docker-compose.yml
version: "3.7"
services:
  redis:
    image: redis:5.0.0@sha256:abcd
```
and: 
```yml
# override.yml
version: "3.7"
services:
  redis:
    image: ${REDIS_IMAGE}
```

Then when calling `docker-compose up` I would only provide the `override.yml` if `REDIS_IMAGE` has been set. However the compose files I want to use renovate on contain several services each of which would require its own override files and makes what should be a fairly simple process in to something more complex than it needs to be.

**Additional context**
n/a
