### ISSUE TITLE
Support Bitbucket Pipe Renovations

### ISSUE THREAD

**Issue by paddymccrudden** [renovatebot/renovate#4647]
**What would you like Renovate to be able to do?**
Create pull requests for Bitbucket pipe versions.

**Describe the solution you'd like**
Bitbucket pipelines uses a bitbucket-pipeline.yaml file for CICD. One feature that is very useful it the [pipe](https://confluence.atlassian.com/bitbucket/pipes-978200560.html). An example of the code is here:
~~~~
script:
  - pipe: atlassian/aws-s3-deploy:0.2.2
    variables:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: 'us-east-1'
      S3_BUCKET: 'my-bucket-name'
      LOCAL_PATH: 'build'
~~~~
Notice that the pipe itself has a version associated with it which increases over time. The version of the particular pipe above is now 0.3.5 - see [aws-s3-deploy](https://bitbucket.org/atlassian/aws-s3-deploy/src/master/) and so the pipeline code needs to be upgraded. 

It would be great if we could configure renovatebot to find these pipes, and upgrade them as per other upgrades. 

**Describe alternatives you've considered**
I haven't considered any alternatives to this. 

**Additional context**
This feature request appears to be very similar to [Support Buildkite plugin renovation ](https://github.com/renovatebot/renovate/issues/1869)

**Comment by rarkins** [comment]
First step would be to add a datasource for fetching bitbucket tags, e.g. https://api.bitbucket.org/2.0/repositories/atlassian/aws-s3-deploy/refs/tags

Then a new manager for bitbucket pipes, that includes extract and update functions.

BTW there also appears to be the need to support Docker images within pipeline definitions too:

```yaml
image: node:10.15.1

pipelines:
  default:
    - step:
        name: Build and Test
        script:
          - npm install
          - npm test
          - npm run dist
        artifacts:
          - dist/**
    - step:
        name: Deploy
        deployment: production
        script:
          - pipe: atlassian/aws-s3-deploy:0.2.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: "us-east-1"
              S3_BUCKET: "my-bucket-name"
              LOCAL_PATH: "dist"
```
([ref](https://confluence.atlassian.com/bitbucket/deploy-to-aws-with-s3-976772858.html))
