### ISSUE TITLE
Support helm chart placeholder repositories

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4681]
**What would you like Renovate to be able to do?**

Support placeholders like this:
```yaml
dependencies:
  - name: generic-service
    version: 5.0.2
    repository: '@axoom-github'
    alias: app
```

Also support `alias:axoom-github` too as allowed in https://github.com/helm/helm/pull/2174

**Describe the solution you'd like**

It seems we need to check other `yaml` files within the repo for placeholder values. Is the location deterministic?

**Describe alternatives you've considered**

Currently we just skip placeholders, so they're not updated.

**Additional context**

Example source: https://github.com/AXOOM/Templates.WebService/blob/b7fca8e6a8aa94283a4aa4a1a98c92d77d6d4f55/content/helmfile.yaml#L6-L8
