### ISSUE TITLE
Artifact update problem with self hosted docker container in OpenShift

### ISSUE THREAD

**Issue by mikaelkolkinn** [renovatebot/renovate#4764]
**What Renovate type are you using?**

Self-hosted docker container in an OpenShift 3.9 environment. Git platform is Bitbucket Cloud.

**Describe the bug**

Renovate seems to run into permission errors when attempting to update the yarn.lock file using lerna. This only occurs when running the `renovate/renovate:19` container in OpenShift.
When using the same config and container on a local machine, lock file creation works fine.

Is there any special configuration we should use? We've based our OpenShift configuration on your documentation for Kubernetes.

**Did you see anything helpful in debug logs?**

> INFO: lock file error (repository=company/web-application, dependencies=@apollo/react-testing, branch=renovate/apollo-react-testing-3.x)
       "cmd": "npm i -g -C ~/.npm/lerna@3.16.4 lerna@3.16.4 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@3.16.4/bin/lerna bootstrap --no-ci -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879",
       "err": {
         "killed": false,
         "code": 7,
         "signal": null,
         "cmd": "npm i -g -C ~/.npm/lerna@3.16.4 lerna@3.16.4 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@3.16.4/bin/lerna bootstrap --no-ci -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879",
         "stdout": "",
         "stderr": "Error: EACCES: permission denied, mkdir '/.npm'\nTypeError: Cannot read property 'loaded' of undefined\n    at exit (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:97:27)\n    at errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:215:3)\n    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:77:20\n    at cb (/usr/local/lib/node_modules/npm/lib/npm.js:225:22)\n    at /usr/local/lib/node_modules/npm/lib/npm.js:263:24\n    at /usr/local/lib/node_modules/npm/lib/config/core.js:83:7\n    at Array.forEach (<anonymous>)\n    at /usr/local/lib/node_modules/npm/lib/config/core.js:82:13\n    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)\n    at afterExtras (/usr/local/lib/node_modules/npm/lib/config/core.js:173:20)\n/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:97\n  var doExit = npm.config.loaded ? npm.config.get('_exit') : true\n                          ^\n\nTypeError: Cannot read property 'loaded' of undefined\n    at exit (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:97:27)\n    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:215:3)\n    at process.emit (events.js:198:13)\n    at process._fatalException (internal/bootstrap/node.js:496:27)\n",
         "message": "Command failed: npm i -g -C ~/.npm/lerna@3.16.4 lerna@3.16.4 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@3.16.4/bin/lerna bootstrap --no-ci -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\nError: EACCES: permission denied, mkdir '/.npm'\nTypeError: Cannot read property 'loaded' of undefined\n    at exit (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:97:27)\n    at errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:215:3)\n    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:77:20\n    at cb (/usr/local/lib/node_modules/npm/lib/npm.js:225:22)\n    at /usr/local/lib/node_modules/npm/lib/npm.js:263:24\n    at /usr/local/lib/node_modules/npm/lib/config/core.js:83:7\n    at Array.forEach (<anonymous>)\n    at /usr/local/lib/node_modules/npm/lib/config/core.js:82:13\n    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)\n    at afterExtras (/usr/local/lib/node_modules/npm/lib/config/core.js:173:20)\n/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:97\n  var doExit = npm.config.loaded ? npm.config.get('_exit') : true\n                          ^\n\nTypeError: Cannot read property 'loaded' of undefined\n    at exit (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:97:27)\n    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:215:3)\n    at process.emit (events.js:198:13)\n    at process._fatalException (internal/bootstrap/node.js:496:27)\n",
         "stack": "Error: Command failed: npm i -g -C ~/.npm/lerna@3.16.4 lerna@3.16.4 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@3.16.4/bin/lerna bootstrap --no-ci -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\nError: EACCES: permission denied, mkdir '/.npm'\nTypeError: Cannot read property 'loaded' of undefined\n    at exit (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:97:27)\n    at errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:215:3)\n    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:77:20\n    at cb (/usr/local/lib/node_modules/npm/lib/npm.js:225:22)\n    at /usr/local/lib/node_modules/npm/lib/npm.js:263:24\n    at /usr/local/lib/node_modules/npm/lib/config/core.js:83:7\n    at Array.forEach (<anonymous>)\n    at /usr/local/lib/node_modules/npm/lib/config/core.js:82:13\n    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)\n    at afterExtras (/usr/local/lib/node_modules/npm/lib/config/core.js:173:20)\n/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:97\n  var doExit = npm.config.loaded ? npm.config.get('_exit') : true\n                          ^\n\nTypeError: Cannot read property 'loaded' of undefined\n    at exit (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:97:27)\n    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:215:3)\n    at process.emit (events.js:198:13)\n    at process._fatalException (internal/bootstrap/node.js:496:27)\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
       },
       "stdout": undefined,
       "stderr": undefined,
       "type": "lerna",
       "lernaClient": "yarn"

[Full log (https://pastebin.com/JACBu8Uj)](https://pastebin.com/JACBu8Uj)

**To Reproduce**

OpenShift job:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: renovate-test
spec:
  backoffLimit: 0
  parallelism: 1
  completions: 1
  template:
    spec:
      containers:
        - name: renovate-test
          image: renovate/renovate:19
          imagePullPolicy: Always
          env:
            - name: RENOVATE_PLATFORM
              valueFrom:
                secretKeyRef:
                  key: renovate-platform
                  name: renovate-env
            - name: RENOVATE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: renovate-username
                  name: renovate-env
            - name: RENOVATE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: renovate-password
                  name: renovate-env
            - name: RENOVATE_NPMRC
              valueFrom:
                secretKeyRef:
                  key: renovate-npmrc
                  name: renovate-env
            - name: RENOVATE_AUTODISCOVER
              valueFrom:
                secretKeyRef:
                  key: renovate-autodiscover
                  name: renovate-env
            - name: RENOVATE_ONBOARDING_CONFIG
              valueFrom:
                secretKeyRef:
                  key: renovate-onboarding-config
                  name: renovate-env
            - name: LOG_LEVEL
              value: "debug"
            - name: RENOVATE_AUTODISCOVER_FILTER
              value: "company/web-application"
      restartPolicy: Never
```
