### ISSUE TITLE
Add support for krew plugin version updates

### ISSUE THREAD

**Issue by grzesuav** [renovatebot/renovate#4769]
**What would you like Renovate to be able to do?**
There is a tool called krew (https://github.com/kubernetes-sigs/krew) which uses plugin list declared as form of xml documents (located here - https://github.com/kubernetes-sigs/krew-index/tree/master/plugins).

Each plugin description is a `yaml.file` which declares the plugin version :
```
    - uri: https://github.com/corneliusweig/rakkess/releases/download/v0.4.1/bundle.tar.gz
      sha256: 50c6321db984dcc4ddadf0d62385145431562450bbac75b67ad3db959dd327de
```
 how difficult it would be to add support of detecting new versions of plugin files and make a PR to update it with renovate ?

**Describe the solution you'd like**
Add a way to make possible to configure renovate to perform updates (detection of new version and proposal of a PR)

**Describe alternatives you've considered**
Some custom script/bot in repository to do the updates.

**Additional context**
Plugin files are usually on github/gitlab.

Few questions :
* is currently renovate able to detect that new release was done on github , get the release file link and calculate sha256 ?
* is currently renovate able to be configured to watch custo yaml files for dependency update ?

**Comment by rarkins** [comment]
This is not possible yet via *configuration* but should be a fairly simple "manager" addition. A more detailed description with extended examples would help, or pointers to a spec if one exists.

**Comment by grzesuav** [comment]
In details, there is above-mentioned repository which contains of `yaml` files like (https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/debug-shell.yaml) :
```yaml

apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: debug-shell
spec:
  platforms:
  - uri: https://github.com/danisla/kubefunc/archive/v1.0.2.zip
    sha256: 93c01f4b4f0862409dfbb10cb48995b70540f359e08742f0f10f7adf9d4326bd
    bin: debug-shell.sh
    files:
    - from: "/*/debug-shell/*"
      to: "."
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin, linux]}
  version: "v1.0.2"
  homepage: https://github.com/danisla/kubefunc
  shortDescription: Create pod with interactive kube-shell.
```

where the main part is a link to archive on github (`https://github.com/danisla/kubefunc/archive/v1.0.2.zip`) with `sha256` (93c01f4b4f0862409dfbb10cb48995b70540f359e08742f0f10f7adf9d4326bd)


For me two parts need to be covered :
* selection of `file path`
* detection of an update (new release of archive pointed in the uri)
