### ISSUE TITLE
Support Helm Chart Docker Tag Updates in `values.yaml`

### ISSUE THREAD

**Issue by dominik-bln** [renovatebot/renovate#4895]
**What would you like Renovate to be able to do?**

Support updating of Docker Tags in Helm Charts `values.yaml`.

**Describe the solution you'd like**

Updating Docker tags of Helm Charts can be somewhat similar to updating Kubernetes templates if the tags are specified inside the templates, but often the used Docker tags are kept inside a `values.yaml` file and combined in the template to make them more configurable (e. g. [Postgres Chart](https://github.com/helm/charts/blob/2b429d052baef11d78d0faf75746e5e15fd840fd/stable/postgresql/values.yaml#L426), [Redis Chart](https://github.com/helm/charts/blob/2b429d052baef11d78d0faf75746e5e15fd840fd/stable/redis/values.yaml#L15)).

This is also the suggested way when creating a new Helm Chart via `helm create my-chart`. 

The two ways I'm aware of that are used inside `values.yaml` files and that I'd like to see supported are:

```yaml
image:
  repository: nginx
  tag: stable
```

```yaml
image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 11.6.0-debian-9-r0
```

These can occur nested and multiple times inside a `values.yaml`

I'd be happy to try to implement a new manager for this if it would be considered.
