### ISSUE TITLE
Support for helmfile.yaml

### ISSUE THREAD

**Issue by gmelillo** [renovatebot/renovate#4967]
**What would you like Renovate to be able to do?**

Supporting helm update on `helmfile.yaml`

**Describe the solution you'd like**

[helmfile](https://github.com/roboll/helmfile) is a manager for `helm` that allows you to manage more easily multiple environment and multiple charts.

In order to do that there is a file called `helmfile.yaml` that contains the definitions of custom repository and release list that contains the version of the different chart that needs to be managed.

Example of repositories definitions:

```yaml
repositories:
# To use official "stable" charts a.k.a https://github.com/helm/charts/tree/master/stable
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
# To use official "incubator" charts a.k.a https://github.com/helm/charts/tree/master/incubator
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com
# helm-git powered repository: You can treat any Git repository as a charts repository
- name: polaris
  url: git+https://github.com/reactiveops/polaris@deploy/helm?ref=master
# Advanced configuration: You can setup basic or tls auth
- name: roboll
  url: http://roboll.io/charts
  certFile: optional_client_cert
  keyFile: optional_client_key
  username: optional_username
  password: optional_password
# Advanced configuration: You can use a ca bundle to use an https repo
# with a self-signed certificate
- name: insecure
   url: https://charts.my-insecure-domain.com
   caFile: optional_ca_crt
```
Example of release definitions:

```yaml
releases:
  - name: external-dns
    namespace: somenamespace
    version: 2.9.0
    chart: stable/external-dns
```

`releases[*].chart` is containing the name of the repository + `/` and then the chart name that should be looked upon the  `repositories` array to get the actual URL of the repo.

I'd be happy to try to implement a new manager for this if it would be considered to be supported.
