### ISSUE TITLE
Renovate does not update gitlab-ci.yml docker image when comments are present

### ISSUE THREAD

**Issue by ViceIce** [renovatebot/renovate#4998]
**What Renovate type are you using?**

Happens on all renovate bots against when renovating `.gitlab-ci.yml`.

**Describe the bug**
Renovate does not find the `name` if there is a comment line between `image` and `name`
![image](https://user-images.githubusercontent.com/1798109/70882385-e4784500-1fcf-11ea-82ec-f69f6294766c.png)

**Did you see anything helpful in debug logs?**

nope.

**To Reproduce**

Use following `.gitlab-ci.yml`
```yml
image:
# comment
  name: renovate/renovate:19.70.8-slim
```

See sample repo:
https://github.com/ViceIce/renovate-test/blob/b0f1d83ab0acb094324442bd23bb7ca2f2fbf7ec/.gitlab-ci.yml#L1-L3

**Additional context**

Maybe we should simply skip comment lines, or use a yml parser to find the images.

**Comment by ViceIce** [comment]
another issue:

```yml
image:
  entrypoint; [""]
  name: renovate/renovate:19.70.8-slim
```

Does not work too. So we should switch to yaml parsing?

@rarkins Any other ideas?

https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#define-image-and-services-from-gitlab-ciyml

![image](https://user-images.githubusercontent.com/1798109/70888523-d7178680-1fe0-11ea-8a08-62d2728f1c89.png)
