### ISSUE TITLE
Support for ansible galaxy dependencies

### ISSUE THREAD

**Issue by timbrd** [renovatebot/renovate#5199]
Please add checking ansible-galaxy's requirements.yml file to renovatebot (see [here](https://galaxy.ansible.com/docs/using/installing.html#installing-multiple-roles-from-a-file)).

Since the dependencies in the requirements.yml file point to git repositories and the versions should either follow a semantic versioning, renovate should already have most of the features to support ansible dependencies.

**Comment by rarkins** [comment]
Let's try to capture all the types of dependencies that we might encounter, and then plan which we would implement in phase 1 and which would be a later phase. For example git-based dependencies should require much less work than any hg-based because we don't have any hg support currently.

**Comment by timbrd** [comment]
The documentation that I have linked has a sample of each dependency type.

I don't think it is neccessary to support the following ones right from the beginning:
* Mercurial (hg)
* A role which is hosted on a webserver and is packaged as an archive (https://domain.com/files/master.tar.gz)

In my opinion the common dependency types are:

```yaml
# from galaxy
- src: yatesr.timezone
  version: "0.1"

# Git repo, accessible by http(s)
- src: https://github.com/bennojoy/nginx
  name: nginx_role
  version: master

# Git repo, accessible by git+http(s)
- src: git+http://bitbucket.org/willthames/git-ansible-galaxy
  version: "v1.4"

# Git repo, accessible by git protocol
- src: git@gitlab.company.com:mygroup/ansible-base.git
  scm: git
  version: "0.1"
```

'version' is optional and defaults to 'master'. It can either by a repo tag, a commit hash or a branch name.

If 'src' is not an url, but a role name (string with a dot in it), it should resolve to `https://galaxy.ansible.com/api/v1/roles/?owner__username=<before the dot>&name=<after the dot>`, e.g. https://galaxy.ansible.com/api/v1/roles/?owner__username=yatesr&name=timezone. Renovate can find the git url of the ansible role there.

Alternatively you could use the ansible-galaxy cli to resolve and download a role from ansible-galaxy though?
