### ISSUE TITLE
Support helmv3

### ISSUE THREAD

**Issue by mikebryant** [renovatebot/renovate#5450]
**What would you like Renovate to be able to do?**
As a user of helm I would like renovate to update my Chart.yaml dependencies. They used to be in requirements.yaml, now they're located inside Chart.yaml

**Describe the solution you'd like**
Renovate should support dependencies in Chart.yaml

**Describe alternatives you've considered**
Staying on helm2, which is no longer being developed

**Additional context**
[Migrating from helm 2 to 3](https://helm.sh/docs/topics/v2_v3_migration/)

**Comment by rarkins** [comment]
@mikebryant can you provide an example public repo to test against?

**Comment by mikebryant** [comment]
I've set up an example here: https://gitlab.com/mikebryant/helmv3-dependency-example

Of particular note, I think, is the chart repository alias feature.

It might be sensible to populate renovate's notion of `stable` - which is by convention https://kubernetes-charts.storage.googleapis.com/

Ideally that should also be extensible, so a repository could define the location of aliases in renovate.json, or in the self-hosted case we can define that default globally for the bot as a whole. It would be preferable to be able to use aliases instead of defining the full chart repository url everywhere.



Possibly out of scope initially - supporting [OCI hosted](https://helm.sh/docs/topics/registries/#enabling-oci-support) charts would also be good - I've yet to experiment with these. Potentially they would be able to benefit from the existing docker datasource.

**Comment by rarkins** [comment]
Re: aliases, have you seen the aliases support we have for v2 charts already? It sounds to me the same as what you're describing, but if not then could you clarify the differences?

It sounds like OCI hosted charts would fit in as a new type of `datasource`, or potentially be combined into the existing [helm datasource](https://github.com/renovatebot/renovate/tree/master/lib/datasource/helm) if we can distinguish them from URL alone. The `helm` manager (tentative name) would then need to be able to extract both types and categorize them correctly for the datasource. I suggest implementing it in a second phase but keeping it in mind while implementing the first.

**Comment by mikebryant** [comment]
This is my current aliases file for v3:
```
m@hotppc17686:~/go/src/gitlab.com/mikebryant/helmv3-dependency-example/example$ cat ~/.config/helm/repositories.yaml 
apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  keyFile: ""
  name: stable
  password: ""
  url: https://kubernetes-charts.storage.googleapis.com/
  username: ""
m@hotppc17686:~/go/src/gitlab.com/mikebryant/helmv3-dependency-example/example$ 
```

No, I haven't seen the v2 aliases stuff, sorry, I will go look... - yes, that looks like exactly the same thing. No differences :)
