### ISSUE TITLE
Renovate schema not available in slim image

### ISSUE THREAD

**Issue by cfra** [renovatebot/renovate#5465]
**What would you like Renovate to be able to do?**

We are validating our Renovate configurations against the json schema provided by Renovate.

That schema has recently been removed from source control in https://github.com/renovatebot/renovate/commit/8e7eec636207cb30f37eeddff488c7a8db1684cc which broke our CI chain, as we were using the file in source control for validation.

**Describe the solution you'd like**

We would like some way to obtain the current JSON schema, ideally without having to generate it ourselves.

We were unable to find a simple solution for this, creating the JSON schema in the `renovate/renovate:slim` Docker image fails like this:

```
$ yarn create-json-schema
yarn run v1.22.0
$ babel-node --extensions ".ts,.js" -- bin/create-json-schema.js && prettier --write "renovate-schema.json"
/bin/sh: 1: babel-node: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Describe alternatives you've considered**

We have not found any other way to obtain the schema directly. Using the large Renovate Docker image is not feasible for CI due to its size.

**Additional context**

This is what we were doing so far on CircleCI. Obviously it's a kludge, but it's the best we were able to come up with:

```yaml
jobs:
  validate:
    docker:
      - image: renovate/renovate:19.128.0-slim
    steps:
      - checkout
      - run:
          command: npm install
          name: Install ajv
      - run:
          command: curl https://raw.githubusercontent.com/renovatebot/renovate/master/renovate-schema.json > renovate-schema.json
          name: Fetch renovate configuration schema
      - run:
          command: npx ajv -s renovate-schema.json -d /home/ubuntu/project/renovate.json
          name: Validate config against JSON schema
```
