### ISSUE TITLE
Add support to update action in GitHub Actions workflow

### ISSUE THREAD

**Issue by vidavidorra** [renovatebot/renovate#5733]
**What would you like Renovate to be able to do?**
I'd like to update actions in an GitHub Action workflow. In the example workflow (shortened) below the `wagoid/commitlint-github-action` can be updated to `1.6.0`.

```yml
jobs:
  commitlint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v1.4.0
```

**Describe the solution you'd like**

I'd like the `github-actions` manager to create updates for action in GitHub Actions workflow.

**Describe alternatives you've considered**

Current alternative is to also add a regex manager ([source](https://github.com/renovatebot/config-help/issues/570#issuecomment-599887952)).

```
{
  ...
  regexManagers: [
    {
      fileMatch: ['^\\.github/workflows/[^/]+\\.ya?ml$'],
      matchStrings: ['uses: (?<depName>.*?)@(?<currentValue>.*?)\\s'],
      datasourceTemplate: 'github-tags',
    },
  ],
  ...
}
```

**Additional context**
See discussions in https://github.com/renovatebot/config-help/issues/570 for this feature.
