### ISSUE TITLE
postUpgradeTasks always executed even when no package is updated

### ISSUE THREAD

**Issue by micheelengronne** [renovatebot/renovate#5791]
**What Renovate type are you using?**

I use the self-hosted Renovate.

**Describe the bug**

I configured the following renovate.json file:

```
{
  "assignees": ["bot"],
  "baseBranches": ["master"],
  "extends": ["config:base"],
  "automerge": true,
  "regexManagers": [
    {
      "fileMatch": ["^inspec.yml$"],
      "matchStrings": [
        "git: (?<depName>.*)?\n    tag: (?<currentValue>.*)"
      ],
      "datasourceTemplate": "git-tags"
    }
  ],
  "postUpgradeTasks": {
    "commands": ["inspec vendor --overwrite ./"],
    "fileFilters": ["inspec.lock"]
  }
}
```
to update the following inspec.yml:

```
---
name: inspec-test
title: Test
maintainer: Test
copyright: Test
copyright_email: test@example.com
license: Test
summary: Test
version: 1.0.0
supports:
  - os-family: linux
depends:
  - name: linux-baseline
    git: https://github.com/dev-sec/linux-baseline.git
    tag: 2.3.0
```

and the inspec.lock:

```
---
lockfile_version: 1
depends:
- name: linux-baseline
  resolved_source:
    git: https://github.com/dev-sec/linux-baseline.git
    ref: 1233a136f319a3f2342c35ec06f325b1b0e94b36
  version_constraints: []
```

The first time renovatebot updates the new version (2.4.0) and its new ref in the lockfile. But, when renovatebot parses it again, it only updates the ref and not the version. Then, when renovatebot parses again, it updates both. And we have a loop.

The configuration works when `postUpgradeTasks` is removed. In that case, the ref is not updated (of course) but the version is updated and the branch is merged (when the CI is green).

**Did you see anything helpful in debug logs?**

Nothing. Except that `postUpgradeTasks` is always triggered even when no package is updated.

What troubles me is the revert of the version. Is the `postUpgradeTasks` triggered before the package update ? In that case, why does it detect the correct ref ? If  `postUpgradeTasks` is triggered after the package update, why the package is reverted ?
