### ISSUE TITLE
Add kubernetes api updates to kubernetes manager

### ISSUE THREAD

**Issue by RmStorm** [renovatebot/renovate#5972]
**What would you like Renovate to be able to do?**
As described [here](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) the kubernetes api will continue to change over time. When this happens the kubernetes team publishes which api updates should be executed by everyone. Currently I use renovatebot to update the docker images in my kubernetes manifests. It would be very helpful if it also checks the `apiversion` field and updates it if the api is being deprecated.

**Describe the solution you'd like**
Renovatebot should automatically update deprecated api's in the apiversion field in kubernetes manifests as described [here](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/).

**Describe alternatives you've considered**
Doing it by hand. It's fine but not amazing.

**Comment by rarkins** [comment]
I don't understand exactly what you need - an example/diff would help.

> if the api is being deprecated

e.g. What logic can Renovate use to determine if an API is being deprecated? Do you mean you don't want Renovate to update the API version if it's updated but *not* being deprecated? If you just mean that Renovate should update the `apiVersion` field whenever it changes, then please clarify that.

We would also need to identify the datasource we can use to know valid versions of the api version.

In summary, this may require:
- [ ] A new datasource used to fetch available versions of the API
- [ ] A new versioning scheme if Kubernetes are not using something we already support like SemVer (I noticed mentions of versions like `v1beta1` so that seems to indicate it's proprietary)
- [ ] The manager/kubernetes/extract code to detect/extract the version so that it can be updated

**Comment by RmStorm** [comment]
I think these depreciation cycles will happen maybe yearly for the next couple of years and everyone will need to update their kubernetes manifests. My suggestion is basically that a mapping is hardcoded into renovatebot that is updated when new depreciations are announced by kubernetes. So as an example I might have a DaemonSet defined somewhere in my repo. Currently only the image is checked and updated if a newer version is available.
``` yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
  namespace: monitoring
  labels:
    app: prometheus
    component: node-exporter
spec:
  template:
    metadata:
      name: prometheus-node-exporter
      labels:
        app: prometheus
        component: node-exporter
    spec:
      containers:
      - image: prom/node-exporter:v0.18.1
        name: prometheus-node-exporter
```
What I propose is that someone (maybe me?) updates a mapping when new depreciations are announced and the mapping would look like this:
``` javascript
const DepreciationMapping = {
  NetworkPolicy: {
    'extensions/v1beta1': 'networking.k8s.io/v1',
  },
  PodSecurityPolicy: {
    'extensions/v1beta1': 'policy/v1beta1',
  },
  DaemonSet: {
    'extensions/v1beta1': 'apps/v1',
    'apps/v1beta2': 'apps/v1',
  },
};
```
Now that I actually write it out I think the process might become to error prone since api depreciations also require additional actions beyond just updating the api version. For example certain fields might no longer be available in the new api.

I do think this is a problem faced by everyone using kubernetes and renovatebot could assist in smoothing this update process. I'm not sure what the best way to go about it is though.

For completeness the above kubernetes object should be updated like so:
``` yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
  namespace: monitoring
  labels:
    app: prometheus
    component: node-exporter
spec:
  template:
    metadata:
      name: prometheus-node-exporter
      labels:
        app: prometheus
        component: node-exporter
    spec:
      containers:
      - image: prom/node-exporter:v0.18.1
        name: prometheus-node-exporter
```
