### ISSUE TITLE
Docker-related errors in log files

### ISSUE THREAD

**Issue by fgreinacher** [renovatebot/renovate#6087]
**What Renovate type are you using?**

Self-hosted GitLab

**Describe the bug**

After upgrading the Renovate image (renovate/renovate) from 19.219.16 to 19.220.0 we are seeing Docker-related errors in our log files. We are running Renovate on a machine without Docker.

**Did you see anything helpful in debug logs?**

```text
WARN: Error removing dangling containers (repository=xyz)
        "err": {
          "killed": false,
          "code": 1,
          "signal": null,
          "cmd": "docker ps --filter label=renovate_child -aq",
          "stdout": "",
          "stderr": "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n",
          "message": "Command failed: docker ps --filter label=renovate_child -aq\nCannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n",
          "stack": "Error: Command failed: docker ps --filter label=renovate_child -aq\nCannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\n    at ChildProcess.exithandler (child_process.js:303:12)\n    at ChildProcess.emit (events.js:310:20)\n    at ChildProcess.EventEmitter.emit (domain.js:482:12)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)"
        }
```

**To Reproduce**

In a GitLab CI yaml:

```yaml
run:
  image:
    name: renovate/renovate:19.219.16
    entrypoint: [""]
  stage: run
  variables:
    RENOVATE_PLATFORM: gitlab
    RENOVATE_ENDPOINT: $CI_API_V4_URL
  only:
    - schedules
  script:
    - node /usr/src/app/dist/renovate.js --autodiscover
```

(Tokens are injected from the outside)
