### ISSUE TITLE
Cannot find preset's package (group:ngxs-storeMonorepo)

### ISSUE THREAD

**Issue by thib3113** [renovatebot/renovate#6088]
**What Renovate type are you using?**

Self hosted, with docker image :
```
{
  "tag": "renovate/renovate:latest",
  "checksum": "sha256:77b87b9e0a1a1e951f86a6ffdb96e65d99d65236d9708c3a816c1565f6e840a0",
  "Labels": {
    "maintainer": "Rhys Arkins <rhys@arkins.net>",
    "name": "renovate",
    "org.opencontainers.image.licenses": "AGPL-3.0-only",
    "org.opencontainers.image.source": "https://github.com/renovatebot/renovate",
    "org.opencontainers.image.url": "https://renovatebot.com",
    "org.opencontainers.image.version": "19.221.0-slim"
  }
}
```

**Describe the bug**

When starting the scan, I got a bug directly.

**Did you see anything helpful in debug logs?**
here is the full log : 
```
 INFO: Throwing preset error
FATAL: Fatal error: config-validation
       "err": {
         "validationError": "Cannot find preset's package (group:ngxs-storeMonorepo). Note: this is a *nested* preset so please contact the preset author if you are unable to fix it yourself.",
         "message": "config-validation",
         "stack": "Error: config-validation\n    at resolveConfigPresets (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:203:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
       }
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "logContext": "_vGZdcQGi",
           "err": {
             "validationError": "Cannot find preset's package (group:ngxs-storeMonorepo). Note: this is a *nested* preset so please contact the preset author if you are unable to fix it yourself.",
             "message": "config-validation",
             "stack": "Error: config-validation\n    at resolveConfigPresets (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:203:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
           },
           "msg": "Fatal error: config-validation"
         }
       ]
```

**To Reproduce**

Doesn't really know, here is my configuration : 
```
module.exports = {
    platform: 'gitlab',
    endpoint: 'https://gitlab.private.com/api/v4/',
    assignees: ['thib3113'],
    baseBranches: ['dev'],
    labels: ['renovate'],
    extends: ['config:base'],
    npmrc: 'registry=http://npm.private.lan:4873',
    logLevel: 'debug'
};
```
My tokens for gitlab and github are set ( maybe you have an idea how to test ? an endpoint ? )

**Additional context**

**Comment by viceice** [comment]
Can somebody please provide a simple github repo to reproduce.

**Comment by thib3113** [comment]
@fastman as @viceice say in https://github.com/renovatebot/renovate/issues/6088#issuecomment-621068291 , github token wasn't needed with version > 19.221.1

**Comment by philippe-granet** [comment]
I'm also facing this issue, on self hosted GitLab, with no access to internet and github (for security reasons)

**Comment by viceice** [comment]
ok, so the issue is: renovate has no internet access while running?

**Comment by viceice** [comment]
how did you used the buildin presets before? do you have an internal npm mirror ?

**Comment by thib3113** [comment]
@viceice I doesn't use github for this, but a private gitlab . So Here is my minimal configuration : 

**.gitlab-ci.yml**
```
variables:
  #RENOVATE_VERSION: slim
  RENOVATE_VERSION: latest
  RENOVATE_IMAGE: renovate/renovate:${RENOVATE_VERSION}
renovabot:
  when: always
  tags:
    - docker-build
  before_script:
    - docker pull -q ${RENOVATE_IMAGE}
    - "docker image inspect ${RENOVATE_IMAGE} | jq '.[0] | {tag: .RepoTags[0], checksum:.Id, Labels:.Config.Labels}'"
  script:
    -  docker run -e RENOVATE_TOKEN="$RENOVABOT_GITLAB_TOKEN" -e "RENOVATE_PLATFORM=gitlab" -e GITHUB_COM_TOKEN="$RENOVABOT_GITHUB_TOKEN" -v $PWD/renovate.js:/usr/src/app/config.js ${RENOVATE_IMAGE} $(cat repositories.txt)
```

**renovate.js**
```
module.exports = {
    platform: 'gitlab',
    endpoint: 'https://gitlab.private.com/api/v4/',
    assignees: ['thib3113'],
    baseBranches: ['dev'],
    labels: ['renovate'],
    extends: ['config:base'],
    npmrc: 'registry=http://npm.private.lan:4873',
    logLevel: 'debug'
};
```

**repositories.txt**
```
renovate
```

( repo `renovate` is the repository that run renovate, useless because no update to do, but crash too )
