### ISSUE TITLE
Support registryUrls using regex manager

### ISSUE THREAD

**Issue by ChipWolf** [renovatebot/renovate#6130]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

I'm attempting to use the regexManager with the Helm datasource to capture the required values from a Kubernetes HelmRelease CRD in order to select the correct registry, chart name, and version.
So far, I've successfully captured the depName and currentValue, but the registryUrl needs to be specified as a list as per [this section of the docs](https://github.com/renovatebot/renovate/blob/4104ba04e3c58063163bc0ae7091fdc2be2d6f97/docs/usage/configuration-options.md#regexmanagers).

I'm not sure how to capture the repository URL as a list using matchStrings, and would appreciate any help in achieving this.

Example HelmRelease CRD:
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 8.12.13
...
```

Current progress with `renovate.json`:
```json
{
  "extends": ["config:base"],
  "regexManagers": [
    {
      "fileMatch": ["\\.yaml$"],
      "matchStrings": [
        "chart:\n *repository: (?<registryUrls>.*?)\n *name: (?<depName>.*?)\n *version: (?<currentValue>.*)\n"
      ],
      "datasourceTemplate": "helm"
    }
  ]
}
```

**Comment by rarkins** [comment]
This is not currently possible, so I moved it as a feature request into the main repo. Because `registryUrls` is technically an array, we need to think how to structure this. One possibility would be to initially support only a *single* `registryUrl` and then convert that into an array of length 1 afterwards.

**Comment by ChipWolf** [comment]
@rarkins thanks for the super quick response.
My initial thought would be to do this for each known repository in the meantime:
```json
{
  "extends": ["config:base"],
  "regexManagers": [
    {
      "fileMatch": ["\\.yaml$"],
      "matchStrings": [
        "chart:\n *repository: https://kubernetes-charts.storage.googleapis.com/\n *name: (?<depName>.*?)\n *version: (?<currentValue>.*)\n"
      ],
      "datasourceTemplate": "helm",
      "registryUrls": ["https://kubernetes-charts.storage.googleapis.com/"]
    }
  ]
}
```

**Comment by rarkins** [comment]
I think it might work if you take the `registryUrls` part out and put it into a `packageRule` instead.

**Comment by ChipWolf** [comment]
Could you possibly provide an example for that please? I'm new to this tool. Thanks! @rarkins

**Comment by rarkins** [comment]
```
{
  "extends": ["config:base"],
  "regexManagers": [
    {
      "fileMatch": ["\\.yaml$"],
      "matchStrings": [
        "chart:\n *repository: https://kubernetes-charts.storage.googleapis.com/\n *name: (?<depName>.*?)\n *version: (?<currentValue>.*)\n"
      ],
      "datasourceTemplate": "helm",
    }
  ],
  "packageRules": [{
    "datasources": ["helm"],
    "managers": ["regex"],
    "registryUrls": ["https://kubernetes-charts.storage.googleapis.com/"]
  }]
}
```

**Comment by ChipWolf** [comment]
Thanks for that. So, what if there's multiple registries for different HelmReleases. How would I pin that packageRule to a specific regexManager? Thanks

**Comment by rarkins** [comment]
You would need to write multiple package rules and match based on `packageNames` or something like that.

**Comment by ChipWolf** [comment]
This config is working for me if anyone reading this is interested:

```json
{
  "extends": ["config:base"],
  "kubernetes": {
    "fileMatch": ["\\.yaml$"]
  },
  "regexManagers": [
    {
      "fileMatch": ["\\.yaml$"],
      "matchStrings": [
        "chart:\n *repository: (?<repository>.*?)\n *name: (?<depName>.*?)\n *version: (?<currentValue>.*)\n"
      ],
      "datasourceTemplate": "helm"
    },
    {
      "fileMatch": ["\\.yaml$"],
      "matchStrings": [
        "chart:\n *git: git@github.com:(?<depName>.*?).git\n *ref: (?<currentValue>.*?)\n"
      ],
      "datasourceTemplate": "github-tags"
    }
  ],
  "packageRules": [
    {
      "datasources": ["helm"],
      "managers": ["regex"],
      "packageNames": [
        "sealed-secrets",
        "kube-ops-view",
        "metrics-server",
        "prometheus-operator"
      ],
      "registryUrls": ["https://kubernetes-charts.storage.googleapis.com/"]
    },
    {
      "datasources": ["helm"],
      "managers": ["regex"],
      "packageNames": [
        "ingress-nginx"
      ],
      "registryUrls": ["https://kubernetes.github.io/ingress-nginx"]
    },
    {
      "datasources": ["helm"],
      "managers": ["regex"],
      "packageNames": [
        "external-dns"
      ],
      "registryUrls": ["https://charts.bitnami.com/bitnami"]
    }
  ]
}
```

**Comment by RichiCoder1** [comment]
Would love to see this, especially as more and more charts are served from the company's repository and not the stable or bitnami repos.

**Comment by Djiit** [comment]
I'd like to see this supported too. Would it be possible to extract the actual repo URL from the yaml file?
I'm willing to help with a little guidance :)

**Comment by rarkins** [comment]
Would support for a single registryUrl satisfy your current use cases?

**Comment by RichiCoder1** [comment]
@rarkins Single registryUrl would work for us, and we're regex because we're using [Helm Operator](https://github.com/fluxcd/helm-operator) (and soon [Helm Controller](https://github.com/fluxcd/helm-controller)) to handle Helm releases. Adding native support for those to Dependabot's Helm support would also work for us, but might not address other abstractions.

**Comment by viceice** [comment]
@RichiCoder1 I've added a new isue to track the `Helm Operator` manager. Shouzld be easy to implement, as it's only some simple yaml.

**Comment by Djiit** [comment]
> Would support for a single registryUrl satisfy your current use cases?

A single registryUrl per chart, yes, not a single one for all the charts.

**Comment by ChipWolf** [comment]
@Djiit does this not work for you? https://github.com/renovatebot/renovate/issues/6130#issuecomment-624061289

**Comment by Djiit** [comment]
@ChipWolf Yes! I'd just like to be able to get rid of the redundancy (redeclare registries in renovate.json)

**Comment by RichiCoder1** [comment]
^ Yup. It works, but it's not sustainable as I mentioned here: https://github.com/renovatebot/renovate/issues/6130#issuecomment-703041160

**Comment by onedr0p** [comment]
Also showing my interest in this there's no doubt @ChipWolf method works but having to redeclare all helm chart sources and apps can get pretty hairy. 

It's also worth noting that Flux is being replaced with Flux2 so having this support the newer version would be great as well.


Sample of a Flux2 HelmRelease:

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: descheduler-helm-chart
      version: 0.19.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-descheduler-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: k8s.gcr.io/descheduler/descheduler
      tag: v0.19.0
      pullPolicy: IfNotPresent
    deschedulerPolicy:
      strategies:
        RemoveDuplicates:
          enabled: false
        RemovePodsViolatingNodeAffinity:
          enabled: true
          params:
            nodeAffinityType:
            - requiredDuringSchedulingIgnoredDuringExecution
        RemovePodsViolatingInterPodAntiAffinity:
          enabled: false
        LowNodeUtilization:
          enabled: false
```
