### ISSUE TITLE
Feature request: Support renovating "resources" in kustomize

### ISSUE THREAD

**Issue by josecv** [renovatebot/renovate#6245]
**What would you like Renovate to be able to do?**
Currently renovate supports updating kustomize bases set via the `bases` list in `kustomization.yaml` files. However, this field [is now deprecated](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/fields.md#bases) and newer kustomize versions place bases in the `resources` list, e.g.:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testing-namespace
resources:
  - git@github.com:moredhel/remote-kustomize.git?ref=v0.0.1
  - deployment.yaml
```

 It would be awesome if renovate were able to renovate bases listed inside of `resources`

**Describe the solution you'd like**
`renovate` should treat `resources` the same as `bases` and update it.

**Describe alternatives you've considered**
I guess an alternative would be to keep using `bases` which renovate does support, but the `kustomize` CLI automatically moves all the bases into `resources` so this isn't really a sustainable solution.
