### ISSUE TITLE
Poetry: Update fails when project is not compatible with latest Python version

### ISSUE THREAD

**Issue by janjagusch** [renovatebot/renovate#6561]
**What Renovate type are you using?**

Self-hosted (v20.20)

**Describe the bug**

When a project is not compatible with the latest Python version, renovate will fail updating the dependencies with a `NoCompatiblePythonVersionFound` error.

**Did you see anything helpful in debug logs?**

```
The currently activated Python version 3.8.3 is not supported by the project (~3.7).
Trying to find and use a compatible version. 

[NoCompatiblePythonVersionFound]
Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.
```

**To Reproduce**

```toml
[tool.poetry]
name = "myproj"
version = "0.1.0"

[tool.poetry.dependencies]
python = "~3.7" # >= 3.7.0, < 3.8.0

[build-system]
requires = ["poetry>=1.0.2"]
build-backend = "poetry.masonry.api"

```

**Additional context**
