### ISSUE TITLE
Feature Request: Support extended Docker configuration options in gitlabci managers

### ISSUE THREAD

**Issue by michael42** [renovatebot/renovate#6659]
**What would you like Renovate to be able to do?**
Renovate doesn't pick up our GitLab CI Services that use the extended syntax, for example:
```yaml
ui-test:
  stage: test
  services:
    - name: internal.docker.hub.company/selenium/standalone-firefox:3.141.59-xenon
      alias: standalone-firefox
    - name: internal.docker.hub.company/selenium/standalone-chrome:3.141.59-xenon
      alias: standalone-chrome
```

**Describe the solution you'd like**
Renovate should be able to parse this syntax. I debugged it and found out the whole parsing is done using regular expressions (instead of a YAML parser) and the regex simply doesn't support this format (and many of other syntactically valid variations).

**Describe alternatives you've considered**
Maybe we can switch to the simplified syntax and use the longer hostnames to access the services, avoiding extended options and not needing the additional support. I'm not sure if/how the 64/255 character-limit for hostname applies to docker services, though.
