### ISSUE TITLE
ENOMEM error from simple-git

### ISSUE THREAD

**Issue by adam-moss** [renovatebot/renovate#6712]
**What Renovate type are you using?**

Self-hosted using the official docker image running in GitLab CI in an on-premise installation of GitLab EE.

**Describe the bug**

Renovate process exits with ENOMEM error.  There is no apparent consistency to the repo that causes this to trigger and if the reported repo is subsequently renovated in isolation it completes successfully.

**Relevant debug logs**

```json
{
  "name": "renovate",
  "hostname": "",
  "pid": 25,
  "level": 50,
  "logContext": "",
  "repository": "",
  "err": {
    "errno": "ENOMEM",
    "code": "ENOMEM",
    "syscall": "spawn",
    "message": "spawn ENOMEM",
    "stack": "Error: spawn ENOMEM\n    at ChildProcess.spawn (internal/child_process.js:407:11)\n    at Object.spawn (child_process.js:548:9)\n    at Git._schedule (/usr/src/app/node_modules/simple-git/src/git.js:1406:41)\n    at Git._run (/usr/src/app/node_modules/simple-git/src/git.js:1368:12)\n    at Git.checkout (/usr/src/app/node_modules/simple-git/src/git.js:516:19)\n    at /usr/src/app/node_modules/simple-git/promise.js:67:24\n    at new Promise (<anonymous>)\n    at /usr/src/app/node_modules/simple-git/promise.js:58:20\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Object.setBaseBranch (/usr/src/app/node_modules/renovate/dist/util/git/index.js:294:13)\n    at async Proxy.setBaseBranch (/usr/src/app/node_modules/renovate/dist/platform/gitlab/index.js:208:27)\n    at async Object.processBranch (/usr/src/app/node_modules/renovate/dist/workers/branch/index.js:48:5)\n    at async Object.writeUpdates (/usr/src/app/node_modules/renovate/dist/workers/repository/process/write.js:25:21)\n    at async Object.update (/usr/src/app/node_modules/renovate/dist/workers/repository/process/extract-update.js:95:15)\n    at async Object.renovateRepository (/usr/src/app/node_modules/renovate/dist/workers/repository/index.js:41:21)\n    at async Object.start (/usr/src/app/node_modules/renovate/dist/workers/global/index.js:76:13)\n    at async /usr/src/app/node_modules/renovate/dist/renovate.js:28:24"
  },
  "msg": "Repository has unknown error",
  "time": "2020-07-08T17:40:19.836Z",
  "v": 0
}
```

**To Reproduce**

We run renovate with `autodiscover: true` processing approximately 167 repos.  Although the job fails consistently with the above error it is inconsistent with which repo triggers it between invocations, and the offending repo always completes successfully in isolation.

**Additional context**

This does not appear to affect renovate processing subsequent repositories _after_ the error has occurred.

**Comment by rarkins** [comment]
Do you have many repositories that have bundler dependencies? It's possible we have a memory leak there.

**Comment by adam-moss** [comment]
Who have a fair few yes, although most of the repos are node or java

**Comment by rarkins** [comment]
@adam-moss first of all, I'm a little surprised if your Renovate still manages to continue happily after this happens. It sounds kind of fatal!

Googling Stack Overflow like any developer would, I found this discussion: https://stackoverflow.com/a/32444643/13699742

I'm not sure how swap even works with GitLab CI and Docker, but thought I'd add it here. Also noting the suggestion in the same thread about `--max-old-space-size=` which again I'm not 100% sure about re: Docker.

**Comment by adam-moss** [comment]
Thanks for that.

Yep, definitely continues, but I think we (you) put something in renovate quite a while back to allow it to complete and then fail at the end when an error occurred 😁

I'll play around with those memory settings and report back, it's a 3 hour run each time so will take a while 😬

**Comment by viceice** [comment]
As you can see, only git crashed and not renovate. So renovate can continue. You should see the repo list at the beginning not logging and you should know which repo fails. Can you exclude that with the autodiscover filter.

Please also share your configs: gitlab.yml, config.js, environment...

Of cause sanitize values as needed. 😉

**Comment by adam-moss** [comment]
Excerpt from `.gitlab-ci.yml`
```yaml
.renovate: &renovate
    stage: maintenance
    resource_group: renovate
    variables:
        RENOVATE_CONFIG_FILE: '$CI_PROJECT_DIR/config.js'
        LOG_FORMAT: 'json'
    <<: *executor-docker
    image:
        name: renovate/renovate:21
        entrypoint: [""]
    before_script:
        - |
          if [ ! -z "$REPOSITORY_LIST" ]; then
              export ADDITIONAL_CONFIG="--force-cli --autodiscover=false $REPOSITORY_LIST"
          fi
    script:
        - mkdir ~/.ssh
        - chmod 700 ~/.ssh
        - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
        - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_keytype
        - chmod 600 ~/.ssh/id_keytpe
        - npm config set registry "https://our.local.package.mirror/repository/npmjs"
        - pip3 config set --user global.index-url https://our.local.package.mirror/repository/pypi/simple
        - LOG_LEVEL=${LOG_LEVEL:-fatal} node /usr/src/app/dist/renovate.js $ADDITIONAL_CONFIG
    artifacts:
        paths:
            - renovate-log.json
        when: on_failure
        expire_in: 7 days
```

Excerpt of `config.js`:
```json
module.exports = {
    "assigneesFromCodeOwners": true,
    "autodiscover": true,
    "automerge": false,
    "branchPrefix": "chore/",
    "commitBody": "Signed-off-by: {{{gitAuthor}}}",
    "docker": {
      "pin": {
        "branchPrefix": "refactor/",
        "semanticCommitType": "refactor",
        "semanticCommitScope": "{{depName}}"
      }
    },
    "endpoint": "https://our.gitlab.instance/api/v4/",
    "gitAuthor": "RenovateBot <renovate-bot@our.mail.domain>",
    "logFile": "renovate-log.json",
    "logFileLevel": "trace",
    "masterIssue": true,
    "masterIssueTitle": "docs(renovate): Renovate Summary",
    "onboarding": false,
    "packageRules": [
        {
          "automerge": true,
          "major": {"automerge": false},
          "depTypeList": ["devDependencies"]
        }
      ],
    "pin": {
      "branchPrefix": "refactor/",
      "semanticCommitType": "refactor",
      "semanticCommitScope": "{{depName}}"
    },
    "pinDigests": true,
    "platform": "gitlab",
    "prCreation": "immediate",
    "prHourlyLimit": 3,
    "rangeStrategy": "pin",
    "rebaseWhen": "behind-base-branch",
    "requireConfig": false,
    "semanticCommits": true,
    "semanticCommitType": "chore",
    "semanticCommitScope": "{{depName}}",
    "timezone": "Europe/London",
  }
```

In terms of `config.toml` its nothing special, basic docker runner on a `t3.large`.

As previously mentioned the failure repo isn't consistent, and renovates successfully in isolation, so an exclusion is not easy 😄
