### ISSUE TITLE
[helm-values] support name aas alias for repository

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#7010]
**What would you like Renovate to be able to do?**

Some helm charts are suing `name` instead of `repository` for the image name. see https://github.com/containous/traefik-helm-chart/blob/98f4575d75b91c6e739ebc0e75c720c998f7dd38/traefik/values.yaml#L3

```yml
# Default values for Traefik
image:
  name: traefik
  tag: 2.2.8
  pullPolicy: IfNotPresent
```

**Did you already have any implementation ideas?**

sure, simply allow name as alias for repository

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**

yes, simply add the repository key too.
```yml
# Default values for Traefik
image:
  name: traefik
  repository: traefik
  tag: 2.2.8
  pullPolicy: IfNotPresent
```

**Is this a feature you'd be interested in implementing yourself?**

sure
