### ISSUE TITLE
Support the python pre-commit configuration

### ISSUE THREAD

**Issue by gerbenoostra** [renovatebot/renovate#7179]
**What would you like Renovate to be able to do?**

I'd like Renovate to be able to handle the configuration of pre-commit (https://pre-commit.com/).

The configuration ( a yaml file named `.pre-commit-config.yaml`) looks like:
```
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: check-json
  - repo: git://github.com/Yelp/detect-secrets
    rev: v0.14.2
```
The repo identifies the source (a github repo, using https://, git:// or ssh://).
The rev identifies the tag of that git repository.

Something similar is probably already implemented somewhere, but would need to be applied to this style of yaml configuration.

**Did you already have any implementation ideas?**
.

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**
Perhaps I just need to have this file parsed by one of the existing languages/platforms? Couldn't find which though.

**Is this a feature you'd be interested in implementing yourself?**

I could help, but have no experience yet in this codebase. So would need some directions (both repo structure and testing)
