### ISSUE TITLE
How to remove the "release-" prefix from a version (e.g. release-1.19.2)?

### ISSUE THREAD

**Issue by platan** [renovatebot/renovate#7297]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

Logs with config file below. 

### What would you like to do?

I would like to update Nginx version in my `versions.yml` file using Renovate. 
```yml
# renovate: datasource=github-releases depName=grafana/grafana
metrics_grafana_version: 7.1.5
# renovate: datasource=github-tags depName=nginx/nginx
metrics_nginx_version: 1.17.10
# renovate: datasource=github-releases depName=prometheus/prometheus
metrics_prometheus_version: 2.21.0
# renovate: datasource=github-releases depName=influxdata/telegraf
metrics_telegraf_version: 1.15.3
```
I have a problem with Nginx, because Nginx repo has [tags](https://github.com/nginx/nginx/tags) in format `release-1.19.2`. 
With my Renovate config:
```json

{
  "extends": ["config:base"],
  "regexManagers": [
    {
      "fileMatch": ["^versions\\.yml$"],
      "matchStrings": [
        "# renovate: datasource=(?<datasource>.*?) depName=(?<depName>.*?)\n.*?: (?<currentValue>.*)"
      ],
      "versioningTemplate": "node"
    }
  ]
}
```
I got:
```
DEBUG: Found no results from datasource that look like a version (nginx/nginx)(dependency="nginx/nginx")
{
  "result": {
    "sourceUrl": "https://github.com/nginx/nginx",
    "releases": []
  }
}
```

When I add `packageRules` to the config:
```
"packageRules": [
    {
      "packageNames": ["nginx/nginx"],
      "versioning": "regex:^release-(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)?$"
    }
  ]
```

I got:
```
Dependency nginx/nginx has unsupported value 1.17.10
[...]
packageFiles with updates
{
            "depName": "nginx/nginx",
            "currentValue": "1.17.10",
            "datasource": "github-tags",
            "versioning": "node",
            "replaceString": "# renovate: datasource=github-tags depName=nginx/nginx\nmetrics_nginx_version: 1.17.10",
            "depIndex": 1,
            "updates": [],
            "warnings": [],
            "skipReason": "unsupported-value"
          },
```

And with:
```
"packageRules": [
    {
      "packageNames": ["nginx/nginx"],
      "versioning": "regex:(release-)?(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)?"
    }
  ]
```
I got:
```
packageFiles with updates
[...]

            "depName": "nginx/nginx",
            "currentValue": "1.17.10",
            "datasource": "github-tags",
            "versioning": "node",
            "replaceString": "# renovate: datasource=github-tags depName=nginx/nginx\nmetrics_nginx_version: 1.17.10",
            "depIndex": 1,
            "updates": [
              {
                "fromVersion": "1.17.10",
                "toVersion": "release-1.19.2",
                "newValue": "release-1.19.2",
                "newMajor": 1,
                "newMinor": 19,
                "updateType": "minor",
                "isSingleVersion": true
              }
            ],
            "warnings": [],
            "fixedVersion": "1.17.10",
            "sourceUrl": "https://github.com/nginx/nginx"
          },
```
and [a PR](https://github.com/platan-forks/metrics-shields-io-config/pull/3/files), which updates the versions file to:
```yml
metrics_nginx_version: release-1.19.2
```

My original repo is https://github.com/platan/metrics-shields-io-config, but I use [a fork](https://github.com/platan-forks/metrics-shields-io-config) for tests. 

I would like to update my file to:
```yml
metrics_nginx_version: 1.19.2
```
