### ISSUE TITLE
[manager] fluxcd helm operator / helm-controller

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#7415]
We should support the `HelmRelease` podinfo.yml files.

https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/introduction/#a-minimal-helmrelease

sample file
```yml
# podinfo.yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  chart:
    repository: https://stefanprodan.github.io/podinfo
    name: podinfo
    version: 3.2.0
```

@rarkins Single registryUrl would work for us, and we're suing regex because we're using [Helm Operator](https://github.com/fluxcd/helm-operator) (and soon [Helm Controller](https://github.com/fluxcd/helm-controller)) to handle Helm releases. Adding native support for those to Dependabot's Helm support would also work for us, but might not address other abstractions.

_Originally posted by @RichiCoder1 in https://github.com/renovatebot/renovate/issues/6130#issuecomment-703695883_

**Comment by RichiCoder1** [comment]
This would be great! As an addendum, the Flux project is putting Helm Operator into maintenance mode, so support for its successor would be great/critical: https://toolkit.fluxcd.io/components/helm/api/. That said, the two CRDs (currently) only differ by `apiVersion` and some spec values that Renovate shouldn't need to care about.

**Comment by viceice** [comment]
@rdicroce Do you think it would be worth to implement this, as it's deprecated? Maybe we should support the successor first.

sample:
```yml
apiVersion: helm.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
 name: podinfo
spec:
 interval: 5m
 chart:
   spec:
     chart: podinfo
     version: '>=4.0.0 <5.0.0'
     sourceRef:
       kind: HelmRepository
       name: podinfo
     interval: 1m
 install:
   remediation:
     retries: 3
 upgrade:
   remediation:
     remediateLastFailure: false
 values:
   resources:
     requests:
       cpu: 100m
       memory: 64Mi
```

https://toolkit.fluxcd.io/components/helm/controller/
