### ISSUE TITLE
Argo-CD Application support

### ISSUE THREAD

**Issue by mikebryant** [renovatebot/renovate#7416]
**What would you like Renovate to be able to do?**

Support the [Argo CD Application](https://argoproj.github.io/argo-cd/operator-manual/application.yaml) objects.

Some examples from my current usage:

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
...
spec:
  source:
    chart: kube-state-metrics
    repoURL: https://kubernetes-charts.storage.googleapis.com
    targetRevision: 2.4.1
---
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  source:
    chart: traefik
    helm:
      values: |
        traefik:
          service:
            spec:
              loadBalancerIP: 1.2.3.4
    repoURL: gs://helm-charts-internal
    targetRevision: 0.0.2
```

**Did you already have any implementation ideas?**

New manager, the existing helm datasource should be fine

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**

Nope, it's already decided we're using Argo CD, so I would very much like Renovate to support it

**Is this a feature you'd be interested in implementing yourself?**

Possibly, but I'm not going to object to anyone getting there first
