### ISSUE TITLE
pyproject.toml some valid TOML syntax not accepted

### ISSUE THREAD

**Issue by intgr** [renovatebot/renovate#7556]
**What Renovate type, platform and version are you using?**

Self-hosting using GitLab, with Python "poetry" package manager

**Describe the bug**

When I enable the "poetry" manager with Renovate, it attempts to read the `pyproject.toml` configuration file in my project.

Python tools are perfectly happy with `pyproject.toml` that contains the following:
```toml
[tool.coverage]
run.omit = ["*/tests_*.py"]
report.precision = 2
```
However, Renovate fails to parse this file ("Error parsing pyproject.toml file"; "SyntaxError").

Thankfully as a workaround I could rewrite the file using different syntax, that works with Renovate:
```toml
[tool.coverage.run]
omit = ["*/tests_*.py"]

[tool.coverage.report]
precision = 2
```

**Relevant debug logs**
```
DEBUG: Using file match: (^|/)pyproject\.toml$ for manager poetry (repository=xxxxx)
DEBUG: Matched 1 file(s) for manager poetry: pyproject.toml (repository=xxxxx)
DEBUG: Error parsing pyproject.toml file (repository=xxxxx)
       "err": {
         "message": "Expected \"=\", [ \\t] or [A-Za-z0-9_\\-] but \".\" found.",
         "expected": [
           {"type": "literal", "value": "=", "description": "\"=\""},
           {"type": "class", "value": "[ \\t]", "description": "[ \\t]"},
           {
             "type": "class",
             "value": "[A-Za-z0-9_\\-]",
             "description": "[A-Za-z0-9_\\-]"
           }
         ],
         "found": ".",
         "offset": 4439,
         "line": 169,
         "column": 4,
         "name": "SyntaxError"
       }
DEBUG: Found 0 package file(s) (repository=xxxxx)
 INFO: Dependency extraction complete (repository=xxxxx)
```

**To Reproduce**

Append the following fragment to a `pyproject.toml` file:
```toml
[tool.coverage]
run.omit = ["*/tests_*.py"]
report.precision = 2
```

**Additional context**

Does Renovate only support some older toml syntax?

**Comment by rarkins** [comment]
Could you give us a full file which fails? It can be as small/redacted as you want, as long as poetry accepts it and our parser rejects it. Then we'll need to work out if we file a bug upstream to our TOML parser

**Comment by intgr** [comment]
Complete failing `pyproject.toml` example:
```toml
[tool.poetry]
name = "app"
version = "1.0.0"
description = "   ლ(ಠ_ಠლ)  "
authors = ["MR <marti@juffo.org>"]

[tool.poetry.dependencies]
python = "^3.8"
"ruamel.yaml" = "0.16.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage]
run.omit = ["*/tests_*.py"]
```

I can successfully run `poetry lock` on this file, but Renovate rejects it:
```
DEBUG: Error parsing pyproject.toml file (repository=xxxxx)
       "err": {
         "message": "Expected \"=\", [ \\t] or [A-Za-z0-9_\\-] but \".\" found.",
         "expected": [
           {"type": "literal", "value": "=", "description": "\"=\""},
           {"type": "class", "value": "[ \\t]", "description": "[ \\t]"},
           {
             "type": "class",
             "value": "[A-Za-z0-9_\\-]",
             "description": "[A-Za-z0-9_\\-]"
           }
         ],
         "found": ".",
         "offset": 290,
         "line": 16,
         "column": 4,
         "name": "SyntaxError"
       }
```
