### ISSUE TITLE
Renovate doesn't update NodeJS version used by GitHub actions

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/renovate#7716]
**What Renovate type, platform and version are you using?**

GitHub

**Describe the bug**

I thought Renovate would pin and keep this version up to date:

https://github.com/felixfbecker/svg-screenshots/blob/a2ddfa85b2b2a606f6eec2e4ee582caf52415f73/.github/workflows/build.yml#L16

But it doesn't update it: https://github.com/felixfbecker/svg-screenshots/pull/7

**Comment by rarkins** [comment]
What's the definitive reference for the possible fields/values? I assume node isn't the only possibility there.

**Comment by felixfbecker** [comment]
It is for the `setup-node` action, but you can find other setup actions in the docs sidebar here: https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs

**Comment by viceice** [comment]
This is currently not supported, but you can use regex manager as workaround

**Comment by rarkins** [comment]
We naturally can't support every parameter of every action out of the box. The question is whether we try to support these particular `actions/*` ones or not. Also: made difficult by the possibility of a matrix of versions.

**Comment by felixfbecker** [comment]
I think it would be great to support the `setup-` actions natively (or at least Node). You are right, with matrixes it may be more difficult.

@viceice do you have an example for what that would look like? Is it possible to group that with package.json `engines.node` ugprades?

**Comment by viceice** [comment]
> We naturally can't support every parameter of every action out of the box. The question is whether we try to support these particular `actions/*` ones or not. Also: made difficult by the possibility of a matrix of versions.

The parameters can change in major versions too, so maybe high maintenance work.

**Comment by viceice** [comment]
> I think it would be great to support the `setup-` actions natively (or at least Node). You are right, with matrixes it may be more difficult.
> 
> @viceice do you have an example for what that would look like? Is it possible to group that with package.json `engines.node` ugprades?

Can try to create a sample tomorrow

**Comment by viceice** [comment]
@felixfbecker Here a sample `regexManagers` for updating `node-version`. You need to set the version to `14`, `14.15` or `14.15.0`.

*regexManagers*
```json
{
  "fileMatch": ["^\\.github\\/workflows\\/.*\\.ya?ml$"],
  "matchStrings": [
    "node-version: '(?<latestVersion>.+?)'"
  ],
  "depName": "node",
  "datasourceTemplate":"docker",
  "versioningTemplate": "docker"
}
```

**Comment by rarkins** [comment]
@viceice shouldn't it be like this?

```json
{
  "fileMatch": ["^\\.github\\/workflows\\/.*\\.ya?ml$"],
  "matchStrings": [
    "node-version: '(?<currentValue>.+?)'"
  ],
  "depNameTemplate": "node",
  "datasourceTemplate":"docker",
  "versioningTemplate": "docker"
}
```

**Comment by viceice** [comment]
Can be, used our internal preset as base for this. 🙃

https://github.com/renovatebot/presets-internal/blob/7426e1de3cc4ff2e156620839abe173c12bbb584/docker-images.json#L48

**Comment by ibratoev** [comment]
@felixfbecker Even better - duplicating the version in your workflows. You can define it in `.nvmrc` and read that in the workflow. Here is how we do it:
```
      - name: Read .nvmrc
        run: echo ::set-output name=nodeVersion::$(cat .nvmrc)
        id: nvm

      - name: Setup node ${{ steps.nvm.outputs.nodeVersion }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ steps.nvm.outputs.nodeVersion }}
```

**Comment by aaronadamsCA** [comment]
If you're instead using the `engines` property in `package.json` to pin your Node.js version, I expect this would work:

```yml
      - name: Read Node.js version from package.json
        run: echo ::set-output name=nodeVersion::$(node -p "require('./package.json').engines.node")
        id: engines

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.engines.outputs.nodeVersion }}
```

**Comment by HonkingGoose** [comment]
## Matrix updates

I agree that the `matrix.node-version` is going to be tough to update. Here's an example YAML file:

```yaml
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x]
```

At the time of writing this, Node.js:

- `12.x` and `14.x` are end of life (EOL)
- `16.x` is active LTS
- `18.x` is current LTS
- `20.x` is latest LTS

## How should Renovate update the matrix?

Given the above, what should Renovate do with the matrix example?

1. Drop `12.x`, `14.x` because EOL, keep `16.x` and `18.x` as they are current
2. Drop `12.x`, `14.x` because EOL, keep `16.x` and `18.x` as they are current, append `20.x` as it's latest LTS
3. Keep `12.x`, `14.x` even though they are EOL, keep `16.x` and `18.x` as they are current
4. Keep `12.x`, `14.x` even though they are EOL, keep `16.x` and `18.x` as they are current, append `20.x` as it's latest LTS
5. Something else

### Summary of complex list above

1. Drop old stuff, keep current stuff
2. Drop old stuff, keep current stuff, and append latest stuff
3. Keep old stuff, keep current stuff
4. Keep old stuff, keep current stuff, and append latest stuff
5. Something else

### Matrix versions often end up in the test names

Also many users name use the `matrix` versions to name their tests like `build (12.x`, `build (14.x)` and so on. So Renovate can't automerge the PRs that it creates to change the `matrix`. The user will have to add the newer node.js tests to their branch protection rules manually, before merging.

**Comment by noahtallen** [comment]
actions/setup-node supports nvm directly now, which makes this super easy:

```yml
- uses: actions/setup-node@v3
  with:
    node-version-file: '.nvmrc'
```
