### ISSUE TITLE
Support reading onboarding json from a file for self-hosted

### ISSUE THREAD

**Issue by nejch** [renovatebot/renovate#7867]
**What would you like Renovate to be able to do?**

Have the ability to read the onboarding json from a file, so it can be more easily validated in CI for self-hosted projects (and for better json formatting if that matters).

**Did you already have any implementation ideas?**

Well, this is basically already possible with the following hack (gitlab self-hosted example), just proposing a native solution maybe.

```yaml
run:
  script:
    - export RENOVATE_ONBOARDING_CONFIG=$(< onboarding.json)
    - renovate
```

I'd be fine with either an extra `RENOVATE_ONBOARDING_CONFIG_FILE` or have it try read a file first and resort to string if not found.

Then it's easier to trick `renovate-config-validator` into checking it in CI:

```yaml
validate:
  stage: test
  variables:
    RENOVATE_CONFIG_FILE: onboarding.json
  script:
    - renovate-config-validator | sed "s|config.js|$RENOVATE_CONFIG_FILE|g"
```

Which should give you, for example:
```
Validating renovate.json
Validating onboarding.json
OK
```
