### ISSUE TITLE
Support JSON5 for bot admin config files

### ISSUE THREAD

**Issue by remal** [renovatebot/renovate#7882]
I'm running Renovate via GitLab CI.

I have `.gitlab/renovate.json5` Renovate config with such content:
```js
{
  $schema: "https://docs.renovatebot.com/renovate-schema.json",
  extends: [
    "github>remal/renovate-config:jre",
  ],
  // ...
}
```

Also, I have such `.gitlab-ci.yml`:
```yml
stages:
- renovate

renovate:
  stage: renovate
  services:
  - docker:dind
  image: renovate/renovate:slim
  variables:
    RENOVATE_CONFIG_FILE: $CI_PROJECT_DIR/.gitlab/renovate.json5
    RENOVATE_BASE_DIR: $CI_PROJECT_DIR/.renovate
    RENOVATE_ENDPOINT: $CI_API_V4_URL
    RENOVATE_PLATFORM: gitlab
    RENOVATE_GIT_AUTHOR: Renovate Bot <bot@renovateapp.com>
    RENOVATE_REQUIRE_CONFIG: 'true'
    RENOVATE_ONBOARDING: 'false'
    RENOVATE_IGNORE_PR_AUTHOR: 'true'
    LOG_LEVEL: debug
  script:
  - renovate
```

When `renovate` job is executed, I get this error: `SyntaxError: Unexpected token 'extends'`

Full log looks like this:
```
DEBUG: Using RE2 as regex engine
DEBUG: Parsing configs
FATAL: Could not parse config file 
        /builds/remal/gradle-plugins/.gitlab/renovate.json5:3
         extends: [
         ^^^^^^^
       
       SyntaxError: Unexpected token 'extends'
           at wrapSafe (internal/modules/cjs/loader.js:979:16)
           at Module._compile (internal/modules/cjs/loader.js:1027:27)
           at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
           at Module.load (internal/modules/cjs/loader.js:928:32)
           at Function.Module._load (internal/modules/cjs/loader.js:769:14)
           at Module.require (internal/modules/cjs/loader.js:952:19)
           at require (internal/modules/cjs/helpers.js:88:18)
           at Object.getConfig (/usr/src/app/node_modules/renovate/lib/config/file.ts:15:14)
           at Object.parseConfigs (/usr/src/app/node_modules/renovate/lib/config/index.ts:52:60)
           at processTicksAndRejections (internal/process/task_queues.js:93:5)
           at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:50:14)
           at /usr/src/app/node_modules/renovate/lib/renovate.ts:10:22
```

I tried to wrap `$schema` and `extends` into quotes (both `'` and `"`) and it doesn't help.

 

I suppose, the root cause is that we load config files for cli execution using `require` function: https://github.com/renovatebot/renovate/blob/5fdac61665345f71dd2a5662418d3892487c7ee0/lib/config/file.ts#L15

However, for auto-discovery execution config format detection is performed (JSON5 lib is used for `.json5` extension and JSON lib is used for other files): https://github.com/renovatebot/renovate/blob/5d99ff9862bac803dcea4e6ded5f3fec34abccfc/lib/workers/repository/init/config.ts#L69-L127

I think that the same logic should be implemented for cli execution.
