### ISSUE TITLE
[poetry] updates to pre-release versions are not provided if allow-prereleases=true

### ISSUE THREAD

**Issue by MrGreenTea** [renovatebot/renovate#7902]
**What would you like Renovate to be able to do?**

currently, If I have a `pyproject.toml` like this I won't get updates for the version `1.1a1` of `example`.
```toml
[tool.poetry.dependencies]
python = "^3.9"
example = { version = "1.0", allow-prereleases=true }
```

With some guidance / introduction I could imaging implementing this myself.
