### ISSUE TITLE
Support Docker registry authentication

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#798]
Currently we support only public Docker Hub images. We should define a config option for supporting authentication with Docker Hub, to later be expanded to custom registries after #797 is implemented.

Related to #1500

**Comment by rarkins** [comment]
From @evilebottnawi in https://github.com/renovateapp/renovate/issues/797#issuecomment-362559935:

> * Use `gitlab` and `gitlab-ci`
> * We use default docker registry (registry.docker.io)
> * We need auth
> * Gitlab already support auth in CI, look https://docs.gitlab.com/ce/ci/docker/using_docker_images.html#define-an-image-from-a-private-container-registry
> 
> For us all works fine except when we need auth, i think better solution check env variables if they present. Maybe for gitlab check `DOCKER_AUTH_CONFIG`, but this is not necessary, it would be enough to indicate through the env variables `login`, `password` and `registry` (for future).

**Comment by rarkins** [comment]
So we need to:

(a) work out how to configure authentication (login/password?)
(b) use that authentication in the right place

For (a) I'm not sure whether to use/override generic terms like login/password so that our definitions don't get too long. We are trialing username/password for BitBucket support right now too, but maybe "login" is more generic.

For (b), it's hopefully contained within https://github.com/renovateapp/renovate/blob/master/lib/manager/docker/registry.js but we'll need to modify the functions or signatures to pass auth through.

**Comment by evilebottnawi** [comment]
@rarkins any news? why blocked?

**Comment by ForbesLindesay** [comment]
It would be great to get support for Amazon's ECR, which looks like this on CircleCI:

```yaml
    docker:
      - image: account-id.dkr.ecr.us-east-1.amazonaws.com/org/repo:0.1
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID_STAGING
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY_STAGING
```
