### ISSUE TITLE
Helm sourceUrl should point to chart repo

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#8049]
**What would you like Renovate to be able to do?**

Currently the helm datasource simply uses the first sourceUrl it can find, which mostly points to the docker image repo.
We should implement a better heuristic to find the chart repo url.

**Did you already have any implementation ideas?**

yes, additionally check the `home` property. eg for https://charts.bitnami.com/bitnami it points to the chart repo and the sources are pointing to image source repo and product home page.

So i would make some heuristic to best match one of the urls as homepage and sourceUrl

**Comment by viceice** [comment]
**index.yaml**
```yml
apiVersion: v1
entries:
  airflow:
  - annotations:
      category: WorkFlow
    apiVersion: v2
    appVersion: 1.10.13
    created: "2020-11-27T18:10:15.83673504Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.x.x
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 12.x.x
    description: Apache Airflow is a platform to programmatically author, schedule
      and monitor workflows.
    digest: 23ec51c1eb551f7f5838dcbb7b4f1147428dbbf5d4efc07ab02b20e9a0c25ffd
    home: https://github.com/bitnami/charts/tree/master/bitnami/airflow
    icon: https://bitnami.com/assets/stacks/airflow/img/airflow-stack-110x117.png
    keywords:
    - apache
    - airflow
    - workflow
    - dag
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: airflow
    sources:
    - https://github.com/bitnami/bitnami-docker-airflow
    - https://airflow.apache.org/
    urls:
    - https://charts.bitnami.com/bitnami/airflow-7.0.3.tgz
    version: 7.0.3
```

**Comment by viceice** [comment]
```yaml
apiVersion: v1
entries:
  gitea:
  - apiVersion: v2
    appVersion: 1.13.0
    created: "2020-12-16T12:59:32.351523727Z"
    dependencies:
    - condition: gitea.cache.builtIn.enabled
      name: memcached
      repository: https://charts.bitnami.com/bitnami
      version: 4.2.20
    - condition: gitea.database.builtIn.mysql.enabled
      name: mysql
      repository: https://charts.bitnami.com/bitnami
      version: 6.14.10
    - condition: gitea.database.builtIn.postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.7.2
    - condition: gitea.database.builtIn.mariadb.enabled
      name: mariadb
      repository: https://charts.bitnami.com/bitnami
      version: 8.0.0
    description: Gitea Helm chart for Kubernetes
    digest: 75bd233367c4ba02f6415f9fbb8e125fb953e6402f5ade325612080364db8c29
    icon: https://docs.gitea.io/images/gitea.png
    keywords:
    - git
    - issue tracker
    - code review
    - wiki
    - gitea
    - gogs
    maintainers:
    - email: charlie@charliedrage.com
      name: Charlie Drage
    - email: maintainers@gitea.io
      name: Gitea Authors
    - email: konrad.lother@novum-rgi.de
      name: Konrad Lother
    - email: lucas.hahn@novum-rgi.de
      name: Lucas Hahn
    name: gitea
    sources:
    - https://gitea.com/gitea/helm-chart
    - https://github.com/go-gitea/gitea
    - https://hub.docker.com/r/gitea/gitea/
    type: application
    urls:
    - https://dl.gitea.io/charts/gitea-2.1.3.tgz
    version: 2.1.3
```

here we should find `https://gitea.com/gitea/helm-chart`

**Comment by HonkingGoose** [comment]
Do you want to work on this @viceice? Not sure if you want to be assigned to this or not, but you seem to have been working on/thinking about this already?

**Comment by viceice** [comment]
no time for this yet 🙃

**Comment by DirtyCajunRice** [comment]
If possible, it would be nice to have control over this. doing the above serves no further purpose to the end user who is using your tool and continues to leave them at the mercy of the chart/bot. Copy pasta of the relevant part of my dup:

Helm and Docker both support `#` comment style, which is commonly used in linters/parsers to notate that their prefix:option is immediately preceding the override it defines. For example

### Chart.yaml
```yaml
dependencies:
  - name: external-dns
    version: 4.11.2
    # renovatebot:alturl=https://github.com/bitnami/charts/tree/master/bitnami/external-dns
    repository: https://charts.bitnami.com/bitnami
```
### values.yaml
```yaml
image:
  # renovatebot:alturl=https://github.com/bitnami/bitnami-docker-external-dns
  repository: bitnami/external-dns
  tag: 0.7.6-debian-10-r91
```

The above currently links to external-dns source code in k8s sigs which is great! but neither docker nor helm are tied to that release cycle, so adding the ability to add user defined secondary/alternate would help a lot to get that quick "is this alright" and get a step closer to always getting accurate release notes
