### ISSUE TITLE
Unable to run go command

### ISSUE THREAD

**Issue by megablend** [renovatebot/renovate#8077]
I'm trying to set up renovate to update my golang projects in bitbucket pipeline with no luck. I found that the problem is because it doesn't have go binary in the image. 

### My Configuration
```yml
pipelines:
  custom:
    renovate:
      - variables:
          - name: UserEmail
      - step:
          image: renovate/renovate:slim
          script:
            - cp config.js /usr/src/app/config.js
            - export LOG_LEVEL=debug
            - git config --global user.email "$UserEmail"
            - git config --global user.name "Renovate Bot"
            - ls -al /home/ubuntu/
            - which go || 'Missing golang'
            - node /usr/src/app/dist/renovate.js $(cat repositories.txt | args)
```

### Error log
```bash
+ umask 000

+ GIT_LFS_SKIP_SMUDGE=1 retry 6 git clone --branch="master" --depth 50 https://x-token-auth:$REPOSITORY_OAUTH_ACCESS_TOKEN@bitbucket.org/$BITBUCKET_REPO_FULL_NAME.git $BUILD_DIR
Cloning into '/opt/atlassian/pipelines/agent/build'...

+ git reset --hard 0c0632af5740bd992284d0ae8eaa9ca77da5a6f3
HEAD is now at 0c0632a DIAD-0: Add go

+ git config user.name bitbucket-pipelines

+ git config user.email commits-noreply@bitbucket.org

+ git config push.default current

+ git config http.${BITBUCKET_GIT_HTTP_ORIGIN}.proxy http://localhost:29418/

+ git remote set-url origin http://bitbucket.org/$BITBUCKET_REPO_FULL_NAME

+ git reflog expire --expire=all --all

+ echo ".bitbucket/pipelines/generated" >> .git/info/exclude

+ chmod 777 $BUILD_DIR

Pipeline Variables:
    UserEmail: xxxxx@xxxxxxxx.com

Images used:
    build : docker.io/renovate/renovate@sha256:3dbc60e3d95f1a9e5d877f246fdc78c62ad48e9952e3e8bd2c8aeabe2ba4350c
+ cp config.js /usr/src/app/config.js

+ export LOG_LEVEL=debug

+ git config --global user.email "$UserEmail"

+ git config --global user.name "Renovate Bot"

+ ls -al /home/ubuntu/
total 44
drwxr-xr-x. 1 ubuntu root 4096 Dec 18 18:15 .
drwxr-xr-x. 1 root   root 4096 Nov 26 01:01 ..
-rw-r--r--. 1 ubuntu root  220 Apr  4  2018 .bash_logout
-rw-------. 1 ubuntu root 3807 Dec 18 18:15 .bashrc
-rw-rw-rw-. 1 ubuntu root   57 Dec 18 18:15 .gitconfig
drwxrwxr-x. 4 ubuntu root 4096 Dec 18 17:01 .npm-global
-rw-r--r--. 1 ubuntu root  807 Apr  4  2018 .profile
drwxr-xr-x. 2 ubuntu root 4096 Dec 18 18:15 .ssh

+ which go || 'Missing golang'
bash: Missing golang: command not found
Searching for test report files in directories named [test-results, failsafe-reports, test-reports, surefire-reports] down to a depth of 4
Finished scanning for test reports. Found 0 test report files.
Merged test suites, total number tests is 0, with 0 failures and 0 errors.
```
