### ISSUE TITLE
Helm repo @stable not found, "helm repo add" required (but unable to)

### ISSUE THREAD

**Issue by MPV** [renovatebot/renovate#8542]
**What Renovate type, platform and version are you using?**

Hosted GitHub app.

**Describe the bug**

Renovate commented on my PR with the following failure:

<img width="934" alt="Skärmavbild 2021-02-04 kl  13 51 53" src="https://user-images.githubusercontent.com/62675/106895823-fe537a80-66f0-11eb-9d30-7d595e05e035.png">

Here's the entire error message:

`Command failed: docker run --rm --name=renovate_helm --label=renovate_child -v "/mnt/renovate/gh/myorg/myrepo":"/mnt/renovate/gh/myorg/cluster-monitoring" -v "/tmp/renovate-cache":"/tmp/renovate-cache" -w "/mnt/renovate/gh/myorg/cluster-monitoring" docker.io/renovate/helm bash -l -c "helm dependency update cluster-monitoring"
Error: no repository definition for @stable, @stable, @stable. Please add them via 'helm repo add'`

Here's the `Chart.yaml` file it fails on:

```yaml
apiVersion: v2
appVersion: "1.0"
description: Cluster-wide monitoring
name: cluster-monitoring
version: 0.1.0
home: https://github.com/helm/charts/tree/master/stable/prometheus-operator
dependencies:
  - name: prometheus-operator
    version: 8.16.1
    repository: "@stable"
  - name: nginx-ingress
    version: 1.36.3
    repository: "@stable"
    condition: nginxIngressEnabled
  - name: prometheus-adapter
    version: 2.0.1
    repository: "@stable"
```

Here is my `renovate.json` config for this repo:

```json
{
  "extends": [
    "config:base"
  ],
  "aliases": {
    "stable": "https://charts.helm.sh/stable",
    "hashicorp": "https://helm.releases.hashicorp.com",
    "jetstack": "https://charts.jetstack.io"
  },
  "helmv3": {
    "lockFileMaintenance": { "enabled": true }
  }
}
```

**Relevant debug logs**

I have found the Renovate job matching this PR, but I don't see anything relevant to this error in those Renovate App logs.

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [x] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**
