### ISSUE TITLE
Updating version numbers within ansible playbooks

### ISSUE THREAD

**Issue by dragetd** [renovatebot/renovate#8865]
**What would you like Renovate to be able to do?**

I deploy my infrastructure using Ansible. My playbooks contain the different software versions we use.

When using Containerfiles or docker-compose.yml files, it is already possible to use renovate which which suggest updates of those files. But this does not work for versions specified within the Ansible playbooks.

Take the following example:
```
- name: Download setup script file from upstream
  get_url:
    url: "https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/v8.0.0/setup.sh"
    dest: "/usr/local/bin/setup-mail"
    mode: "ugo=rx"
```

or
```
- name: Provide borgmatic using pip3
  pip:
    name: "borgmatic==1.5.12"
    executable: "pip3"
```

I know this is a meta-level which might not be trivial to implement… not Ansible dependencies themself, but dependenceis introduced by modules of Ansible.

**Did you already have any implementation ideas?**

The managers would be probably something like 'ansible-pip' and 'ansible-url-github' and could re-use the existing python/github-releases datasources and ansible playbook parsing. But of course get_url with a GitHub URL or pip are not the only combinations that one could consider. To not create too many managers, this might be combined into a 'ansible-module' kind of manager. Less flexible to configure, but once enabled, it would work with any new ansible module implemented.

## Alternative:

An alternative which would be a huge change for renovate, but would be extremely flexible could be a kind of meta-annotation in comments. For YAML it would be something like `# renovate-hint: { package-regex: "^.*.com/(.*)/v\d.\d.\d/.*$", version-regex: "^.*docker-mailserver/v(\d\.\d.\d).*$", datasource: github-releases }` which I would add before the URL into my Ansible playbook.

Using that, renovate would extract the required info from the next line (or the regex could be prefixed with a relative line number to the comment, package and version could be on different lines) and could create MRs based on the regex matching groups. This would also enable externalizing the variables in Ansible into a variable file and use the renovate-annotation there.

If both things are not an option, where would I find the documentation on adding my own custom managers? :-P
