### ISSUE TITLE
Support Jenkins plugins yaml format

### ISSUE THREAD

**Issue by agaudreault-jive** [renovatebot/renovate#9105]
**What would you like Renovate to be able to do?**

Allow to parse the plugin file defined in yaml format. Jenkins plugin manager supports both [text and yaml format](https://github.com/jenkinsci/plugin-installation-manager-tool#plugin-input-format).

I want renovate to update the plugin when a version is specified. The jenkins specification allows pattern to fetch from different registries (release, experimental, incremental), but that would affect the datasource and it could be done in another PR if someones needs it.

```
plugins:
  - artifactId: git
    source:
      version: latest # renovate will not update
  - artifactId: job-import-plugin
    source:
      version: 2.1 # renovate should update
```

**Did you already have any implementation ideas?**

I already started the implementation in https://github.com/renovatebot/renovate/pull/9069, but I might need more help to fully test it and make sure it works.
