### ISSUE TITLE
Renovate doesn't recognize dependency in .gitlab-ci.yml when service has verbose name

### ISSUE THREAD

**Issue by caiofbpa** [renovatebot/renovate#9731]
**What Renovate type, platform and version are you using?**

I'm self-hosting Renovate in a GitLab repository in my organization.

**Describe the bug**

Renovate doesn't recognize dependency in .gitlab-ci.yml when service has verbose name.

Given that I have a .gitlab-ci.yml like this:

```
test-without-services:
  image: cypress/included:4.12.1

test-with-simple-service:
  image: cypress/included:4.12.1
  services:
    - mysql:8.0.23

test-with-named-service:
  image: cypress/included:4.12.1
  services:
    - name: mysql:8.0.23
      command: ["--sql-mode=STRICT_TRANS_TABLES"]
```

The `mysql:8.0.23` in the `test-with-named-service` isn't recognized by Renovate and therefore isn't included in the `mysql` bump PullRequest/MergeRequest.

I'll try to work on a PR to fix this.
