### ISSUE TITLE
[Docker/Helm] Annotated Overrides

### ISSUE THREAD

**Issue by DirtyCajunRice** [renovatebot/renovate#9798]
**What would you like Renovate to be able to do?**

In almost every circumstance of a helm chart, and many circumstances of a docker container, you are getting a link to only the thing not relevant for what is being bumped. 
* When a helm version is bumped you want a link to the helm repo
* When a Docker container is bumped you want a link to the docker container _**source repo**_ and always a link to the actual application to match up release notes.

**Did you already have any implementation ideas?**

Helm and Docker both support `#` comment style, which is commonly used in linters/parsers to notate that their prefix:option is immediately preceding the override it defines. For example

### Chart.yaml
```yaml
dependencies:
  - name: external-dns
    version: 4.11.2
    # renovatebot:alturl=https://github.com/bitnami/charts/tree/master/bitnami/external-dns
    repository: https://charts.bitnami.com/bitnami
```
### values.yaml
```yaml
image:
  # renovatebot:alturl=https://github.com/bitnami/bitnami-docker-external-dns
  repository: bitnami/external-dns
  tag: 0.7.6-debian-10-r91
```

The above currently links to external-dns source code in k8s sigs which is great! but neither docker nor helm are tied to that release cycle, so adding the ability to add user defined secondary/alternate would help a lot to get that quick "is this alright" and get a step closer to always getting accurate release notes
